Cargo nanoui runtimefix
d3athrow/vgstation13 pull request #11871
Opened 2016-09-13 15:51 UTC by BarneyGumball

There were issues where users with no associated bank accounts (admin ghosts, players using a spare ID, etc) would cause runtimes when they tried to order things.  All of them should be fixed now.

Fixes #11866

2016-09-14 03:57 UTC, Intigracy commented
Straight up disallowing everyone without an ID from using it doesn't seem like much of a fix.

2016-09-14 06:27 UTC, BarneyGumball commented
There's only 2 things people without IDs/linked bank accounts can do with cargo consoles:

1. Throw runtimes
2. Annoy cargo techs with orders that are likely never going to be able to be accepted

This is due to behaviour in Topic() that I didn't change with the nanoui update.

2016-09-14 19:00 UTC, PJB3005 commented on code/game/supplyshuttle.dm
> +	var/idname = "*None Provided*"
This code is copy pasted, please standardize it.

2016-09-14 19:00 UTC, PJB3005 requested changes

2016-09-17 02:18 UTC, gbasood commented
oh wow github has a red X or green check for reviews now, I thought it was Travis showing a compile failed

2016-09-17 05:56 UTC, BarneyGumball commented
I HATE GIT

Closing this.  See here: #11930

2016-09-17 05:56 UTC, closed without merging