R_PERMISSIONS can now kick anyone
d3athrow/vgstation13 pull request #11909
Opened 2016-09-15 22:10 UTC by Intigracy

I think we can agree on this at least.

2016-09-15 22:12 UTC, ComicIronic commented
This check should be in the kick behaviour, not in the comparing-rights behaviour, given that you are totally breaking the behaviour of a proc with a weird illogical case.

2016-09-15 22:16 UTC, ComicIronic requested changes
Get this out of the proc

2016-09-15 22:55 UTC, Intigracy commented
I made the requested changes f u github

2016-09-16 05:45 UTC, clusterfack commented
Comic needs to approve them

2016-09-16 07:34 UTC, ComicIronic approved these changes

2016-09-16 16:22 UTC, merged