fixes #11916
d3athrow/vgstation13 pull request #11919
Opened 2016-09-16 10:49 UTC by Kurfursten

fixes #11916
fixes #11858

- bugfix: Boxen no longer grow after death (also fixes a sprite issue with dead boxen)
- bugfix: Boxen now properly give different amounts of meat based on how fat they were.
- bugfix: Boxen now scream when killed, not when gibbed.

200% tested

2016-09-16 14:11 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!..()) return 0
No one-line if statements.

2016-09-16 14:11 UTC, PJB3005 requested changes

2016-09-16 20:06 UTC, Kurfursten commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!..()) return 0
reee

2016-09-16 22:31 UTC, Kurfursten commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!..()) return 0
>comments don't autoresolve anymore

Github turned into a trash heap

2016-09-16 23:05 UTC, PJB3005 approved these changes

2016-09-17 03:31 UTC, Kurfursten commented
You have to get _maintainer approval_ to make changes to your own branch? Wow, that's disgusting. I'm glad I don't have time to contribute anymore, this would be seriously painful if I had a future contributing code.

It's the git equivalent of "your comment is pending approval by our moderation staff".

2016-09-17 12:54 UTC, PJB3005 commented
> You have to get maintainer approval to make changes to your own branch? 

What?

2016-09-17 14:44 UTC, Kurfursten commented
I was wrong, I read the patchnotes for github later.

When you put in an approval I misinterpreted that purpose of what that approval does. It seems dumb to me since a maintainer has to merge the PR in the first place so adding an approval step seems to do literally nothing, but it's not what I thought it was so I don't really care.

2016-09-18 01:44 UTC, gbasood commented
That would be super dumb
Especially considering your own fork of the code is the repo that your branch lives on
Literal open source genocide

2016-09-18 01:44 UTC, merged