Adds "Summon Magic," summon guns alternative for wizard
d3athrow/vgstation13 pull request #12120
Opened 2016-10-08 02:20 UTC by JustSumBody

Saw this when I was looking at the other summon guns PR and thought it might be neat to bring in(back? I couldn't find any evidence we removed it but it looked like we had it at one point)
Basically it's summon guns but with one use spellbooks/artifacts in place of guns, all the spellbooks are the ones that don't need robes. I might be missing one or two. Should some of the ones that need robes be thrown in?
As for artifacts, I'm not sure if I should just throw them all in or what. Right now there's just the scrying orb, wizard hardsuit, and staff of change.
I don't care much about any of the specifics, but I did like the idea when I read it.

2016-10-08 02:22 UTC, kol1th commented on code/game/gamemodes/wizard/rightandwrong.dm
> +		var/randomizemagic = pick("fireball","smoke","blind","mindswap","forcewall","knock","horsemask","blink","subjugate","charge","staffchange","armor","scrying")
Did you mean to leave charge in here?

2016-10-08 02:56 UTC, clusterfack commented
Summon magic is summon guns meme taken too far

2016-10-11 21:29 UTC, gbasood requested changes
This is literally just a purchased spellbook to give everyone summon guns
I liked this idea at first because I thought it'd give random crew members spellbooks
But then I saw the code
I have never been more disappointed

2016-10-11 21:29 UTC, gbasood commented on code/game/gamemodes/wizard/artifacts.dm
> +	H.rightandwrong(1)
N O

2016-10-11 22:15 UTC, gbasood commented on code/game/gamemodes/wizard/artifacts.dm
> +	H.rightandwrong(1)
oh wait im wrong

2016-10-11 22:15 UTC, gbasood approved these changes

2016-10-21 00:06 UTC, Intigracy commented
We had it at some point and it got commented out for whatever reason.

Spellbooks > guns

2016-10-21 00:06 UTC, merged