Borer Bugfixes
d3athrow/vgstation13 pull request #12356
Opened 2016-10-26 11:09 UTC by Shadowmech88

Borers are now properly placed into severed limbs.
Fixes #6629
Fixes #11114

Being turned into a monkey no longer causes head borers to drop.

Fixes #11020
Fixes #10911
Fixes #11385

The fleshshot is no longer capable of being dropped through any means.

2016-10-26 14:16 UTC, Intigracy requested changes
Tabbing this the way you are is breaking eating mobs being properly cleaned up.

2016-10-26 14:16 UTC, Intigracy commented on code/modules/mob/living/carbon/carbon.dm
> +		for(var/mob/M in src)//mobs, all of them
Untab this.

2016-10-26 14:16 UTC, Intigracy commented on code/modules/mob/living/carbon/carbon.dm
> +		for(var/mob/M in src)//mobs, all of them
Unless this somehow works even when no borers are in them.

2016-10-26 21:06 UTC, Shadowmech88 commented on code/modules/mob/living/carbon/carbon.dm
> +		for(var/mob/M in src)//mobs, all of them
Alright, it should function the same way it did before, now.

2016-10-26 21:11 UTC, Intigracy approved these changes

2016-10-27 07:32 UTC, Shadowmech88 commented
Added a new fix for #11897.
It should work in theory, but I can't test it myself.

2016-10-28 03:07 UTC, Shadowmech88 commented
Compile failure fixed.

2016-10-30 11:56 UTC, merged