Living Mannequin + Cult Mannequins
d3athrow/vgstation13 pull request #12378
Opened 2016-10-27 23:25 UTC by JMWTurner

https://dl.dropboxusercontent.com/u/33846352/dreamseeker%202016-10-27%2021-08-19-72.webm

https://dl.dropboxusercontent.com/u/33846352/dreamseeker%202016-10-28%2001-12-41-00.webm

Mappers and vault designers are gonna love those.

:cl:
* rscadd: When using a staff of animation on an already animated object, the object will see the firer as its new master, allowing wizards to take their ownership from other wizards for instance.
* rscadd: Added a new mob, the Living Mannequin. Mannequins will awaken when hit by a bolt of animation. Additionally, I've added a few variables that allow mappers to create mannequins that automatically awaken when they spawn, or when a mob walks next to them, or when you try to strip them, and that make nearby mannequins awaken as well. Destroying a Living Mannequin drop their items. If the mannequin was holding a highly damaging item when it woke up, it'll fight using that item. It doesn't have the dexterity to fire guns however.
* rscadd: Added cult mannequins. They appear when Nar-Sie cultifies a mannequin.

2016-10-27 23:38 UTC, jakmak3 commented
do cult maniquens have any other special properties?

2016-10-27 23:41 UTC, JMWTurner commented
They don't attack cultists (well they do in the webm but I fixed that) they have barely more health than marble ones. By default they are also strip-trapped (if you try to strip them/wrench them/place items on them, they will awaken) and will awaken any mannequin in a 3 tiles radius.

2016-10-27 23:46 UTC, jakmak3 commented
fucking radical

2016-10-28 10:22 UTC, JMWTurner commented
They come alive only if you try to strip them/wrench them/you hit them. They currently can only exist post-narsie.

2016-10-30 01:49 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/mannequin.dm
> +	visible_message("<span class='warning'><b>[src]</b> collapses!</span>")
Won't you want it to inherit the parent proc?

2016-10-30 11:12 UTC, PJB3005 requested changes

2016-10-30 11:12 UTC, PJB3005 commented on code/game/objects/structures/mannequin.dm
> +	I.pixel_x = -1*clothing_offset_x
Just do `-clothing_offset_x`?

2016-10-30 11:15 UTC, JMWTurner commented
revision 1:
* added the wood and cyber living mannequin's custom breakdown procs.

2016-10-30 11:15 UTC, JMWTurner commented on code/game/objects/structures/mannequin.dm
> +	I.pixel_x = -1*clothing_offset_x
done

2016-10-30 11:19 UTC, PJB3005 commented
Did you forget to push the commit?

2016-10-30 16:42 UTC, JMWTurner commented
@PJB3005 as a matter of fact, I did

2016-10-30 16:42 UTC, JMWTurner commented on code/game/objects/structures/mannequin.dm
> +	I.pixel_x = -1*clothing_offset_x
done for real

2016-10-30 16:43 UTC, JMWTurner commented on code/modules/mob/living/simple_animal/hostile/mannequin.dm
> +	visible_message("<span class='warning'><b>[src]</b> collapses!</span>")
no, the point of this proc is that something custom for each subtype can be done on death.

2016-10-30 22:11 UTC, PJB3005 approved these changes

2016-11-01 03:39 UTC, merged