[WIP] IAA-only traitor item : explosive commendation poster
d3athrow/vgstation13 pull request #12411
Opened 2016-10-30 06:51 UTC by coldcola

Currently open to suggestions on explosion size, TC cost etc.
![poster](https://cloud.githubusercontent.com/assets/17585284/19834940/a54e867c-9e4b-11e6-9fa0-533187e65e16.png)

This adds an explosive variant of the commendation poster which can be attached to a wall and activated by being ripped down.
Can be deactivated and re-placed elsewhere with a multitool

2016-10-30 07:12 UTC, Intigracy requested changes

2016-10-30 07:12 UTC, Intigracy commented on html/changelogs/coldcola.yml
> +- rscadd: Added an IAA-only antag item : the explosive commendation poster.
The : is breaking this, either do an in-body changelog, or put "" around the message..
`- rscadd: "Added an IAA-only antag item : the explosive commendation poster."`

2016-10-30 09:13 UTC, PJB3005 requested changes

2016-10-30 09:13 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	name = "Commendation Poster"
Remove the capitalization from this.

2016-10-30 09:13 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	var/obj/structure/sign/poster/explosive/D = new(src)
Why can't you just make this be spawned on the wall in the first place?

2016-10-30 09:13 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +obj/structure/sign/poster/explosive/New()
Add a / before the path here, and the one below it.

2016-10-30 09:13 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	name = "Award of Sufficiency"
Why can't you set these in the prototype instead of using `New()`?

Also, you're not calling `..()`

2016-10-30 09:13 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	switch(alert("Do I want to rip the poster from the wall?","You think...","Yes","No"))
Just do `if (alert(x) == "Yes")`

2016-10-30 10:32 UTC, coldcola commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	var/obj/structure/sign/poster/explosive/D = new(src)
what do you mean by this exactly?

2016-10-30 11:14 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	var/obj/structure/sign/poster/explosive/D = new(src)
You're creating this object inside the src, then moving it onto the wall after that. You could just do `var/obj/structure/sign/poster/explosive/D = new(on_wall)` and remove the `forceMove()`

2016-10-31 03:36 UTC, AutismSpider commented
explosion size  same as a fuel tank.TC cost three or five?

2016-10-31 04:18 UTC, coldcola commented
I was thinking 3 was a bit too low, and 5 is maybe a bit too high, was hoping more discussion would be had.

2016-10-31 04:19 UTC, Intigracy approved these changes

2016-10-31 04:20 UTC, Intigracy commented
Changed what I asked, still have PJB's stuff though.

2016-10-31 06:38 UTC, Durgen commented
eh, no one really rips down commendation posters. maybe it could have a timer or proximity sensor?

2016-10-31 06:40 UTC, Sprok0 commented
3,2,2 is a very odd explosion pattern, the epicenter range is higher than the heavy and light ranges?

2016-10-31 06:42 UTC, coldcola commented
@Sprok0 note the [WIP] and the OP stating I am open to suggestion.

2016-10-31 06:50 UTC, Sprok0 commented
I'd personally make it like an 1,2,4 or so, same as a weldertank. Also has the benefit of maybe not being obvious what it was from the bhangmeter report

2016-10-31 06:53 UTC, Durgen commented
@coldcola I used to all the time, not so much recently
I can't think of an time I saw one torn down.

2016-10-31 07:05 UTC, coldcola commented
@Durgen I would have to massively disagree, considering most of the time I see them torn down is by greyshits, I doubt that the off-chance that an IAA has rolled antag would be enough of a dis-incentive to not griff.

do people just stay the hell away from all janitor signs in the off-chance that they're bombs?
do people check all briefcases to check if they're SMGs?
do people kill anyone with lazarus capsules because they might be antags?
do people check all bananas a clown is carrying to see if it's a bananium sword?

2016-10-31 07:32 UTC, Durgen commented
@coldcola 
all those antag item checks you mentioned would take some amount of effort.
not tearing down posters takes zero effort. It's easier to not tear down a poster than avoid janitor signs.
It seems like the cost (small chance of getting rekt by bomb) would far exceed the benefit of ripping down posters (slightest of griff valids?) A rational, self-interested, changelog savvy spessman would never rip one down.

Maybe i'm wrong though. It's worth a shot.

2016-10-31 07:37 UTC, Shadowmech88 commented
While I don't play IAA at all, I'm also under the impression that commendation posters don't really get ripped down terribly often.

Wouldn't it be more useful for the poster to explode when it's put up, so you could give it to your target and it'd kill them when they tried to hang it in their office?

2016-10-31 07:47 UTC, mrpain666 commented
I see posters get ripped down all the time.

I'm going to love watching the little greyshitting bastards spontaneously explode in the hallways.

2016-10-31 07:47 UTC, Durgen commented
@Shadowmech88 powergaymen would be hesitant to put up any recommendation posters that are handed to them, particularly if it could blow up in their face instantly.
Maybe they could blow after a randomized amount of time. Perhaps between 1 and 5 minutes.
That way the IAA cold also put them up, and scitter away before the explosion.

2016-10-31 19:05 UTC, CptWad commented
poster saying "ur a faget" replacement when

2016-10-31 21:37 UTC, gbasood commented
One cool idea might just be cheaper posters with no devastation that can be remote signaled to blow immediately/after 3 seconds
Less damage but good for hidden sabotage

2016-10-31 22:06 UTC, FudgePucker commented
I like this a lot.
It will fuck with powergamers and shitbags so much.
Normally WeldLocker StunSpace will rip down the star poster because he is a giant asshat who loves ruining fun.
NOW HE WILL RUN AWAY FROM EVERY POSTER.
The best antag items are the ones that make non-antag items more powerful from association.

2016-10-31 22:08 UTC, PJB3005 commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +		return
Trailing return

2016-11-01 18:05 UTC, FudgePucker commented
Also another idea to raise the power of the poster, make it so that using a multitool on a non antag version pops up "why would you think that would do anything? and gives brain damage. Just to fuck with powergamers.

2016-11-01 21:18 UTC, Zennyization commented
The issue I find with traitor items like this, that are specific to station jobs is that as soon as somebody purchases this item and uses it... They are pretty much 100% tagged from that point onwards. 

This item in my opinion is more of a stealthy mayhem causing device that should in theory not give up the person who put it up. You might argue that is not the case because you're causing some serious shit but once you use this you're pretty much stuck to hiding in maint tunnels in a grey uniform for the rest of the round.

I would perhaps suggest maybe making it not IAA specific and having it come as a randomly generated poster like you can find around the station. This would make the item more useful in my opinion and perhaps even more used by traitors on the station.

2016-11-01 21:55 UTC, coldcola commented
@Zennyization : "The issue I find with traitor items like this, that are specific to station jobs is that as soon as somebody purchases this item and uses it... They are pretty much 100% tagged from that point onwards."
I think that's kind of the point of them, if you're a janitor and you take the sign bombs thinking it won't point to you and start a manhunt then you might be a little slow.
What I thought might be interesting about doing another one for IAA is that this is a role that often can have two players at round start so framing your coworker can become an option.

"I would perhaps suggest maybe making it not IAA specific and having it come as a randomly generated poster like you can find around the station. This would make the item more useful in my opinion and perhaps even more used by traitors on the station."
I really don't see crew ripping down regular posters as often as I see commendation posters ripped down, if at all so I think the purpose would sort of be lost.

2016-11-01 21:56 UTC, coldcola commented
@FudgePucker I mean I could.. really?

2016-11-02 14:43 UTC, ComicIronic requested changes

2016-11-02 14:43 UTC, ComicIronic commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +	if(serial_number == -2)
Just merge this into the above check with an or.

2016-11-02 14:43 UTC, ComicIronic commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +/obj/structure/sign/poster/explosive/New(var/serial)
Just do ..(-2) instead of having copypaste.

2016-11-02 15:30 UTC, FudgePucker commented
@coldcola once this gets merged everyone will start multitooling the posters. Hoping to secure valids. By making it call the dude stupid for using a tool for electronics on a poster and giving them brain damage, it would humiliate the person valid hunting.

2016-11-02 17:46 UTC, ghost requested changes

2016-11-02 17:46 UTC, DrCelt commented on code/game/objects/items/mountable_frames/posters/poster.dm
> +		if("No")
There's no need for an else statement that does nothing

2016-11-23 23:28 UTC, ComicIronic commented
WHEN

2016-12-02 00:37 UTC, ComicIronic commented
Requested changes have not yet been made: feel free to reopen when they have.

2016-12-02 00:37 UTC, closed without merging