Drone Ship Vault
d3athrow/vgstation13 pull request #12433
Opened 2016-11-01 16:44 UTC by JMWTurner

drone ship as in, the ship is a drone, not that it contains any drones. only harmless mannequins. :^)

:cl:
* Added a new vault: the Drone Ship.

2016-11-02 00:42 UTC, Shadowmech88 commented
What's in that room behind the blast doors?

2016-11-02 00:47 UTC, Intigracy commented
"A" = (/obj/item/weapon/gun/osipr{pixel_y = 8},/obj/item/energy_magazine/osipr{pixel_x = 8},/obj/item/energy_magazine/osipr{pixel_x = 8; pixel_y = -6},/obj/item/osipr_core{pixel_y = -4},/obj/item/osipr_core{pixel_x = -4; pixel_y = -4},/obj/item/osipr_core{pixel_x = -8; pixel_y = -4},/turf/simulated/floor/greengrid{light_color = "#A9F291"; light_range = 2},/area/vault/droneship)

2016-11-02 01:23 UTC, JMWTurner commented
An OSIPR, along with two rechargeable magazines and 3 dark energy cores. A reward to match the difficulty to obtain it.

2016-11-03 01:40 UTC, Sprok0 commented
I don't really know if the osipr should be obtainable in-game outside of bus/summon guns, it's a 50 brute damage gun that also stuns and destroys walls, with a 30 shot rechargeable magazine. It's a ballistic version of the pulse rifle.

2016-11-03 22:10 UTC, JMWTurner commented
That's why I said a reward to match the difficulty to obtain it. The pod door's id_tag is different every round, so you need to kill the mannequins to get the code. Cyber mannequins have carp speed, 5 times as much HP, and they're all equipped with weapons that deal at least 15 damage, the one behind the glass who holds the code deals 40 damage. If you're dangerous enough to get rid of those guys successfully, then you don't need the OSIPR to be a danger to the station.

2016-11-03 22:11 UTC, Sprok0 commented
Or you cheese it easily with an RPD or telescience.

2016-11-03 22:15 UTC, JMWTurner commented
You're right. I realized that before you even answered, so here we go:

revision 1
* The droneship's area is now super jammed, not even telecrystals can help the telepad get through here.
* Trapped Cyber Mannequins don't awaken until you break their glass shield

2016-11-03 22:41 UTC, PJB3005 requested changes

2016-11-03 22:41 UTC, PJB3005 commented on maps/randomvaults/objects.dm
> +	name = "OSIPR Pod-Door"
Should have improper

2016-11-03 23:12 UTC, JMWTurner commented on maps/randomvaults/objects.dm
> +	name = "OSIPR Pod-Door"
done

2016-11-04 03:49 UTC, PJB3005 approved these changes

2016-11-06 20:42 UTC, merged