Adds the RCS and rcs telepads to cargo order and protolathe
d3athrow/vgstation13 pull request #12438
Opened 2016-11-01 23:41 UTC by jakmak3

This PR adds in 2 new cargo crates. One with the rapid crate sender (RCS) and another with 3 cargo telepad kits to cargo. The RCS teleports crates (not lockers) to cargo telepads which can be made by activating a telepad kit.  To balance this out for cargo RCS and telepad kits have been added to the protolathe.

2016-11-01 23:43 UTC, PJB3005 requested changes

2016-11-01 23:43 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "RCS Crate"
This should get `\improper`

2016-11-01 23:43 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "RCS Telepad Crate"
Again.

2016-11-01 23:43 UTC, PJB3005 commented
>  To balance this out for cargo RCS and telepad kits have been added to the protolathe.

Uh, I don't see that in the diffs.

2016-11-01 23:44 UTC, jakmak3 commented on code/datums/supplypacks.dm
> +	containername = "RCS Telepad Crate"
\mproper next to container type or next to container name?

2016-11-01 23:56 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "RCS Telepad Crate"
Name, of course.

``` dm
containername = "\improper RCS Telepad Crate"
```

2016-11-02 00:06 UTC, PJB3005 approved these changes

2016-11-11 16:47 UTC, gbasood commented
what
could
go
wrong

2016-11-11 16:47 UTC, merged