Adds Hair Dye
d3athrow/vgstation13 pull request #12448
Opened 2016-11-02 07:55 UTC by Shadowmech88

Closes #12074

:cl:
- rscadd: Adds a can of sprayable hair dye, which can make hair into any color. Target the mouth to color facial hair.
- rscadd: The standard costume crate now comes with a can of hair dye.

2016-11-02 14:24 UTC, ComicIronic submitted a review, later dismissed

2016-11-02 14:24 UTC, ComicIronic commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
Not OO, species should be declaring whether or not they have hair.

2016-11-02 14:24 UTC, ComicIronic commented on code/game/objects/items/weapons/cosmetics.dm
> +				user.visible_message("<span class='notice'>[user] colors their [area == "mouth" ? "facial hair" : "hair"] with \the [src].</span>", \
Just take the result of this hair/facial hair conditional once and use it everywhere.

2016-11-03 01:36 UTC, Shadowmech88 commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
To my knowledge, there doesn't exist any flag or variable that governs whether a species can have hair.

2016-11-03 01:57 UTC, clusterfack commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
Are you sure? I'm pretty sure there is, at the very least its used in icon updating

2016-11-03 02:10 UTC, Shadowmech88 commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
I looked at icon_update code.

Apparently each individual hairstyle has a list of species that are allowed to have it. It checks what hairstyle the mob has, then checks if the mob's species is in that hairstyle's list of allowed species.

2016-11-03 02:12 UTC, ComicIronic commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
Then create that variable.

2016-11-03 02:22 UTC, Shadowmech88 commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
Done.

2016-11-03 02:56 UTC, Intigracy commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
https://github.com/d3athrow/vgstation13/blob/58346d73cc2db766b895efc12e66ab7619d21917/code/modules/mob/living/carbon/human/update_icons.dm#L314

2016-11-03 02:57 UTC, Intigracy commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(isjusthuman(H) || isunathi(H))	//Humans and unathi are the only races with actual hair.
https://github.com/d3athrow/vgstation13/blob/58346d73cc2db766b895efc12e66ab7619d21917/code/modules/mob/living/carbon/human/update_icons.dm#L324

2016-11-03 03:54 UTC, Shadowmech88 commented
I changed the species check to a better one that checks whether the mob's particular hairstyle allows coloring via the do_colouration var.

2016-11-03 07:48 UTC, SonixApache commented
Standard Costume Crates are locked to theater access, by the way.

2016-11-03 07:54 UTC, Shadowmech88 commented
Why does this have the "compile failure" tag? It's showing "All checks have passed" for me.

2016-11-03 11:12 UTC, Intigracy requested changes

2016-11-03 11:12 UTC, Intigracy commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(area == "mouth")
Only thing I can think of at this point is checking if they have their hair/face covered.

2016-11-04 06:53 UTC, Shadowmech88 commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(area == "mouth")
Done.

2016-11-04 07:21 UTC, Intigracy requested changes

2016-11-04 07:21 UTC, Intigracy commented on code/game/objects/items/weapons/cosmetics.dm
> +					to_chat(user, "<span class='notice'>\The [H == user ? "You don't" : "\The [H] doesn't"] doesn't seem to have any colorable hair!</span>")
Both of these say \The You or \The \The [H].

2016-11-04 07:22 UTC, Intigracy commented on code/game/objects/items/weapons/cosmetics.dm
> +					to_chat(user, "<span class='notice'>\The [H == user ? "You don't" : "\The [H] doesn't"] doesn't seem to have any colorable hair!</span>")
By both I mean this and 144

2016-11-04 07:48 UTC, Shadowmech88 commented
Typos fixed.

2016-11-04 11:57 UTC, Intigracy approved these changes

2016-11-04 11:58 UTC, Shadowmech88 commented
Do I need @ComicIronic to personally approve his review? Because I did make the changes he wanted.

2016-11-04 12:28 UTC, PJB3005 commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(area == "mouth")
This should all be defines.

2016-11-04 14:57 UTC, ihadtoregisterforthis commented
Is it instantaneous or does it take time to apply?

2016-11-04 17:19 UTC, Shadowmech88 commented
It's instant if you're applying it to yourself, otherwise it has the same delay as applying lipstick to someone else.

2016-11-06 20:44 UTC, merged