I ADDED WINTER COATS BUT NEED TO ADD HOODS
d3athrow/vgstation13 pull request #12455
Opened 2016-11-03 01:27 UTC by Gef21

HOODS SOON(ISH)

PROOF THAT IT WORKS AND IS TESTED https://webmshare.com/vEKAW

THIS TOOK ME MORE THAN TEN HOURS AND IN THE END ALL I DID WAS PORT SOME SPRITES HAHAHAHAHA KILL ME PLEASE

2016-11-03 01:34 UTC, Gef21 commented
It passed all the checks which means you have to merge it without reading it first

2016-11-03 01:37 UTC, ghost requested changes
TEN HOURS

2016-11-03 01:37 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatcargo
Make this inherit from winter coat and remove like 90% of the lines here

2016-11-03 01:37 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatscience
Same

2016-11-03 01:37 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatengineering
Same

2016-11-03 01:37 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatatmos
Same

2016-11-03 01:37 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatmining
Same

2016-11-03 01:38 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatcargo
I don't know what that means

2016-11-03 01:38 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatscience
I don't know what that means

2016-11-03 01:38 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatengineering
I don't know what that means

2016-11-03 01:38 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatatmos
I don't know what that means

2016-11-03 01:38 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatmining
I don't know what that means

2016-11-03 01:39 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatcargo
😦

2016-11-03 01:40 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatscience
😦

2016-11-03 01:40 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatengineering
😦

2016-11-03 01:40 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatatmos
😦

2016-11-03 01:40 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +/obj/item/clothing/suit/wintercoatmining
😦

2016-11-03 01:50 UTC, Zennyization commented
🎉 I support this PR 🎉 

 👍 LONG LIVE GEF 👍

2016-11-03 01:50 UTC, TheFriggenSawbones commented
:tada: I support this PR :tada:

:+1: LONG LIVE GEF :+1:

2016-11-03 02:04 UTC, DrCelt commented
One hour for every ten lines of code

2016-11-03 02:04 UTC, Intigracy commented on code/modules/clothing/suits/toggles.dm
> +    var item_state_slots = list(slot_r_hand_str = "coatwinter", slot_l_hand_str = "coatwinter")
what is this

2016-11-03 02:05 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    var item_state_slots = list(slot_r_hand_str = "coatwinter", slot_l_hand_str = "coatwinter")
Copy pasted vore code I believe

2016-11-03 02:07 UTC, Gef21 commented
15~ days for one bug :^)

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "cargo technicians winter coat"
Don't like this name, doesn't flow, and is grammatically incorrect without an apostrophe

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "scientists winter coat"
Same tbh

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "doctors winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "captains winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "engineers winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "gardeners winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "atmos technicians winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "securitys winter coat"
Same

2016-11-03 02:10 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    name = "miners winter coat"
Same

2016-11-03 02:14 UTC, The-Albinobigfoot commented on code/modules/clothing/suits/toggles.dm
> +    name = "gardeners winter coat"
>gardener

2016-11-03 02:15 UTC, The-Albinobigfoot commented on code/modules/clothing/suits/toggles.dm
> +    name = "atmos technicians winter coat"
>atmos

2016-11-03 02:58 UTC, ghost requested changes

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    var item_state_slots = list(slot_r_hand_str = "coatwinter", slot_l_hand_str = "coatwinter")
@Gef21 what he means is you should remove this and replace it with the actual item states and in hand states

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatcaptain"
You forgot the item state for this, did you even test it.?

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatmedical"
Ditto

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatscience"
Same

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatcargo"
Same

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatengineering"
Same

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatmining"
Same

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatsecurity"
Same

2016-11-03 02:58 UTC, DrCelt commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatatmos"
Same

2016-11-03 03:08 UTC, The-Albinobigfoot commented on code/modules/clothing/suits/toggles.dm
> +    name = "atmos winter coat"
> atmos

2016-11-03 03:24 UTC, clusterfack commented on code/modules/clothing/clothing.dm
> +		// this is for hoods
This is not how you comment an entire block of code, you start it with ```/*``` and end it with ```*/```

2016-11-03 03:41 UTC, Gef21 commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatcaptain"
I think the item states are handled somewhere

2016-11-03 04:33 UTC, Exxion commented on code/modules/clothing/clothing.dm
> +		// this is for hoods
Fuck you Cluster
Block comments fuck up Git
This is a better method

2016-11-03 04:38 UTC, Gef21 commented
Including the item state makes no difference for some reason so I'm leaving it out

Proofs https://webmshare.com/078Kj

2016-11-03 14:29 UTC, Zennyization commented
🎉 I support this PR 🎉

👍 LONG LIVE GEF 👍

2016-11-04 14:42 UTC, Zennyization commented
🎉 I support this PR 🎉

👍 LONG LIVE GEF 👍

2016-11-06 23:13 UTC, ComicIronic commented on code/modules/clothing/suits/toggles.dm
> +    icon_state = "coatcaptain"
Item_state defaults to the icon_state.

2016-11-11 09:33 UTC, Gef21 commented
:(

2016-11-11 09:33 UTC, closed without merging

2016-11-11 12:53 UTC, Shadowmech88 commented
Why?

2016-11-11 18:52 UTC, Gef21 commented
I couldn't figure out hoods so Kolith did it, he'll probably do a pull request soon™

2016-11-11 21:19 UTC, Jeroen52 commented
I did a bit of work on toggles.dm myself.

bad8fa6dc36b331ce252fa1035e829ec1b6614af
dc787faf1f141117ce564789f70ca5e562851ebd

2016-11-11 21:58 UTC, DrCelt commented
We got it working, and with a couple nicer more intuitive features - eg if you put a hat on, the hood will automatically be taken off, so you don't have to toggle hood to do that. Same with taking the hood off the normal way.

2016-11-11 22:44 UTC, Intigracy commented
`>can't wear a hat with the hood up`

smh tbh fam