Adds new virus effects, adds virus say handling
d3athrow/vgstation13 pull request #12496
Opened 2016-11-06 17:18 UTC by Skullyton

100% tested, 110% evil

The say manipulation works largely in the same way that mask chat changes do. I've added 2 viruses that use this new say manipulation so as to demonstrate how to make more in the future

While working with viruses, I found that the var/multiplier would never be actually given a value, so now it should, so now virology has a little more autism to work with

:cl:

- rscadd: Adds say manipulation to viruses, so they can now affect what people are saying
- rscadd: "Adds Hangman Syndrome, G__d l_ck"
- rscadd: "Adds Self-lubricating Footstep Syndrome, it's as interesting as it sounds"
- rscadd: Adds Gyroscopic Manipulation Syndrome
- rscadd: "Adds Pro-tagonista syndrome"
- rscadd: "The previously useless 'Multiplier' for virus effects now actually works"

2016-11-08 04:04 UTC, Intigracy requested changes

2016-11-08 04:04 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +	..()
You should put these three blocks in the file with the clown shoes.

2016-11-08 04:04 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +/datum/disease2/effect/lubefoot/activate(var/mob/living/carbon/mob,var/multiplier)
You forgot a deactivate to remove the shoes or make them removable or something.

2016-11-08 04:04 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +	canremove = 0
Move in with the kitty ears

2016-11-08 04:04 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +datum/disease2/effect/anime_hair/deactivate(var/mob/living/carbon/mob)
Kitty ears meant to stay cursed forever?

2016-11-08 04:23 UTC, JustSumBody commented on code/modules/virus2/effect.dm
> +	name = "Pro-tagonista Syndrome"
You are not the protagonist.

2016-11-08 13:48 UTC, Skullyton commented on code/modules/virus2/effect.dm
> +datum/disease2/effect/anime_hair/deactivate(var/mob/living/carbon/mob)
Yes

2016-11-08 13:48 UTC, ghost commented on code/modules/virus2/effect.dm
> +	canremove = 0
Will do. What about the cursed clown mask a bit further up?

2016-11-08 13:48 UTC, Skullyton commented on code/modules/virus2/effect.dm
> +	..()
Will do. What about the cursed clown mask a bit further up?

2016-11-08 13:48 UTC, ghost commented on code/modules/virus2/effect.dm
> +	name = "Pro-tagonista Syndrome"
Remobe vay

2016-11-08 13:51 UTC, Skullyton commented on code/modules/virus2/effect.dm
> +/datum/disease2/effect/lubefoot/activate(var/mob/living/carbon/mob,var/multiplier)
the shoes are meant to be a holdover. Only  way to disable the honk is to remove its feet

2016-11-08 20:33 UTC, Skullyton commented
All complaints done, likely there's new stuff to complain about!

2016-11-08 20:50 UTC, Intigracy requested changes
should be it

2016-11-08 20:50 UTC, Intigracy commented on code/modules/clothing/masks/gasmask.dm
> +	desc = "A true prankster's facial attire. A clown is incomplete without his wig and mask.<span class = 'notice'>On second look, it looks like it's coming out of the wearers skin!</span>"
space after the period

2016-11-08 20:50 UTC, Intigracy commented on code/modules/mob/living/carbon/human/say.dm
> +			//to_chat(world, "Checking for voice effect")
Go ahead and just remove these commented out debug messages.

2016-11-08 20:50 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +	to_chat(mob, "<span class = 'notice'>You no longer feel quite like the main character</notice>")
punctuation

2016-11-08 20:50 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +		message += pick(" Nyaa", "  nya", " , Nyaa~", "~")
" , Nyaa~"
what?

2016-11-08 21:02 UTC, ghost commented on code/modules/virus2/effect.dm
> +		message += pick(" Nyaa", "  nya", " , Nyaa~", "~")
This is one of those questions where I appear autistic when explaining it, so I shan't bother

2016-11-08 21:04 UTC, Skullyton commented on code/modules/virus2/effect.dm
> +	to_chat(mob, "<span class = 'notice'>You no longer feel quite like the main character</notice>")
Specification

2016-11-08 21:05 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +	to_chat(mob, "<span class = 'notice'>You no longer feel quite like the main character</notice>")
The end of the line.

2016-11-08 21:06 UTC, Intigracy commented on code/modules/virus2/effect.dm
> +		message += pick(" Nyaa", "  nya", " , Nyaa~", "~")
message = "Help I'm being killed in the dorms!"
message += " , Nyaa~"
message = "Help I'm being killed in the dorms! , Nyaa~"

2016-11-09 18:28 UTC, Skullyton commented
Don't merge just yet, realized that how I've gated some of the symptoms, it is potentially impossible for it to actually get to them

2016-11-09 22:12 UTC, Skullyton commented
Okay, should be goooood to go!

2016-11-09 22:28 UTC, merged

2016-11-09 22:35 UTC, Skullyton commented
Eep