[WIP] Character markers for away missions
d3athrow/vgstation13 pull request #12495
Opened 2016-11-06 11:50 UTC by unid15

Character markers are invisible objects that can be placed in away missions and any maps loaded at runtime, under a mob. Then, observers and ghosts will be able to enter that mob

Here's what it roughly looks like (messages will be changed): 

![](http://puu.sh/s8iJE/b7a105e2c1.png)

There are two types of markers: team markers and individual markers. The difference between them is that individual markers each send a message to all observers, allowing observers to choose which mob to enter. Team markers with the same name form "teams", and each team sends a message to observers, allowing observers to enter a random mob from the team.

Syndicate-banned players can't use markers

Currently not compatible with vaults, because the message is only sent once, and tehre are usually no observers when vaults are spawned

Other changes:
* Added spawned_by_map_element(datum/map_element/ME, list/objects) proc, moved some stuff to it
* Turfs now hold a reference to their map element

**TODO LIST**:

* Add better messages, find and fix bugs

  * Clear mob references 

* Admin logging

* Add an example map (like a trader shuttle)

* Add a way for ghosts to see all current vacations and enter them

2016-11-06 12:15 UTC, Shadowmech88 commented
You should add a version that admins can place and activate, to make getting players into mobs a bit more streamlined than saying "ahelp if you want me to manually edit your ckey into this mob I have" in deadchat.

2016-11-06 13:47 UTC, PJB3005 commented on code/game/objects/effects/mapping.dm
> +	to_chat(body, "don't metagame, fucker") //todo
Reminder.

2016-11-06 13:47 UTC, PJB3005 commented on code/game/objects/effects/mapping.dm
> +	if(((O.client.inactivity/10)/60) <= ALIEN_SELECT_AFK_BUFFER) // Filter AFK
Pretty sure we have a proc for this.

2016-11-06 16:23 UTC, Skullyton commented
Needs something to limit what a player can say when they're in control of a mob, maybe to their talk list, else you'll have shit like a hivebot running around shouting 'GAY NIGGERS EAT MY ANUS'

2016-11-06 16:24 UTC, Skullyton commented on code/datums/map_elements.dm
> -	for(var/obj/structure/cable/C in objects)
???

2016-11-06 16:54 UTC, Kurfursten commented on vgstation13.dme
> +#include "maps\test_box.dm"
truly this will become the meme of the new era

2016-11-06 16:57 UTC, Shadowmech88 commented on vgstation13.dme
> +#include "maps\test_box.dm"
One of these days someone's not going to catch this and the players will have to endure an actual round on test_box.

2016-11-06 17:30 UTC, JustSumBody commented on code/datums/map_elements.dm
> -	for(var/obj/structure/cable/C in objects)
It got moved to the `spawned_by_map_element` proc in cable.dm, which is called in the new lines here.

2016-11-08 04:05 UTC, Intigracy commented on code/game/objects/effects/mapping.dm
> +	to_chat(body, "don't metagame, fucker") //todo
:joy:

2016-11-08 21:53 UTC, icantthinkofanameritenow commented
It would probably be a good idea to give players a way to use any spell-like abilities that the mob can use too. I remember once I was in the position of controlling a giant spider that couldn't even ventcrawl.

2016-11-08 22:06 UTC, Intigracy requested changes
pls fix test_box.dm include

2016-11-12 14:14 UTC, unid15 commented
@Skullyton that issue that will rarely occur. and when it will, there are admins to handle that

@Shadowmech88 I'll only include mapping ones for now

2016-11-12 15:37 UTC, unid15 commented
The functionality is ready, the only thing that is missing are example maps and some luxury features (like being able to see all current vacations)

2016-11-12 18:15 UTC, Intigracy approved these changes

2016-12-21 11:15 UTC, Probe1 commented
Please fix what conflicts you can this is really cool.

2016-12-29 15:14 UTC, unid15 commented
Will reopen later

2016-12-29 15:14 UTC, closed without merging