Fluffcomputers
d3athrow/vgstation13 pull request #12575
Opened 2016-11-19 16:23 UTC by jakmak3

This adds in several new computers that do litterally nothing except give a access denied message. The only purpose for these computers is for vaults/away missions for immhulsions purposes. When jwmturners mapping PR is closed/merged i will make a pr to replace some of the empty computer consoles in the white ship with these.

2016-11-19 16:25 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    to_chat(user, "You hold the cryptographic sequencer up to the ID scanner and nothing happens. Guess this only works")
missed a word, oopsies

2016-11-19 16:25 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A code locked console that controls the ship. Doesnt look like you will be flying the ship anytime soon."
Doesn't

2016-11-19 16:25 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A code locked console that controls the ships engines and power systems."
ship's

2016-11-19 16:26 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A console with a map of the local area. Just by looking at this thing you can tell its years out of date and is too old to be used effectivly"
it's or it is

2016-11-19 16:26 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by sillicons")
add a period, and silicons

2016-11-19 16:27 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +	to_chat(user, "The console must be so old that not even the cryptographic sequencer is compatible with it ")
Maybe something like `"The cryptographic sequencer causes some lights on the console to light up before emitting a dull buzzing noise."`

2016-11-19 16:27 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A console displaying the status of the ships engines."
ship's

2016-11-19 16:28 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by sillicons")
same as before

2016-11-19 16:28 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    to_chat(user, "The console must be so old that not even the cryptographic sequencer is compatible with it ")
same as above

2016-11-19 16:28 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +    say("ERROR FUEL RESERVE EMPTY. SHUTTING DOWN") /*needs a better message for why it doesnt work. Taking suggestions */
`WARNING: FUEL RESERVES LOW. ENGINES SHUTTING DOWN.` maybe?

2016-11-19 22:47 UTC, Zth-- commented
Images and gifs _pleeeeeeassssssse_

2016-11-19 23:42 UTC, PJB3005 requested changes

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/buildandrepair.dm
> +	name = "Circut Board (Communications relay)"
All of these need to not be capitalized.

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    name = "Communications Relay"
Remove capitalization.

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    return
This is the worst incident of trailing return I've seen, ever!

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The systems firewall prevents you from accessing it.")
Is GitHub screwing with me or is this line indented twice?

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    say("Access Denied")
Make this check for whether the machine actually has power and such.

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    to_chat(user, "You hold the cryptographic sequencer up to the ID scanner and nothing happens. Guess this only works with NT technology ")
Make this check for whether the machine actually has power and such.

Also, you forgot a period.

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    name = "Shuttle Control"
Remove capitalization.

2016-11-19 23:42 UTC, PJB3005 commented on code/game/machinery/computer/fluffcomputer.dm
> +    name = "Shuttle Control"
Also, same issues that plague the other one.

2016-11-20 01:03 UTC, ComicIronic commented
Put these under an unusable/ type and reduce the copypaste.

2016-11-20 12:35 UTC, kol1th commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The systems firewall prevents you from accessing it.")
It's indented twice

2016-11-20 12:35 UTC, kol1th commented on code/game/machinery/computer/buildandrepair.dm
> +	name = "Circut Board (Communications relay)"
also 

> circut

2016-11-21 06:57 UTC, DrCelt commented on code/game/machinery/computer/fluffcomputer.dm
> +    return
oh my god that's amazing

2016-11-21 06:58 UTC, DrCelt commented on code/game/machinery/computer/fluffcomputer.dm
> +/obj/machinery/computer/unusable_shuttle_control_1 /*fluff shuttle console 1 */
why use /* */ for a single line?

2016-11-21 06:58 UTC, DrCelt commented on code/game/machinery/computer/fluffcomputer.dm
> +    return
OH NO HE DID IT AGAIN

2016-11-21 06:58 UTC, DrCelt commented on code/game/machinery/computer/fluffcomputer.dm
> +    return
AND AGAIN

2016-11-21 06:59 UTC, DrCelt commented on code/game/machinery/computer/fluffcomputer.dm
> +    return
AND AGAAAAIN

2016-11-21 14:37 UTC, Kurfursten commented on code/game/machinery/computer/fluffcomputer.dm
> +    say("Access Denied")
don't these typically use the warning span?

2016-11-22 14:47 UTC, FudgePucker commented
An idea for fluff might be a way to hack it by hand, to give fluff text, or a way to output vault coordinates.

Goons solarium is an example of how you can use puzzles and mysteries to add depth and atmosphere to areas in space rather than just having them be loot zones. The telescience adventures on goon is one of the few parts I liked about that code base (fuck their mining and incomplete material system). I have rarely gotten that sense of emersion that I had going though those areas for the first time, looking around every corner for traps, reading logs left behind.

2016-11-27 15:01 UTC, jakmak3 commented
OK FUCK THIS IM MAKING A NEW PR GIT HATH  REPREHENSIBLY FUCKED ON MY END

2016-11-27 15:01 UTC, closed without merging