Adds new items for traitors and nuke ops
d3athrow/vgstation13 pull request #12576
Opened 2016-11-19 17:37 UTC by uraniummeltdown

Adds Syndicate Bombs (3,7,14), minibombs, (1,2,4), pizzabombs, (1,2,4), syndicate detonator and dehydrated space carp. Syndicate Bombs have a min timer of 120 seconds and beep. You can defuse Syndicate and Pizza bombs. Dehydrated Space Carp are carp plushies that on adding water turn into a real carp that doesn't  attack the owner (use it in hand) because splashing water adds carp pheromones to the owner. The Syndicate Detonator will blow up any existing active Syndicate Bombs.
Syndicate Bombs are in for 13 TC, Minibombs for 6 TC, Pizza Bombs for 5 TC, Detonator for 3 TC(Nuke Only), Carp for 3 TC.
Also added the Blood Red Hardsuit for 8 TC.

:cl:
 * rscadd: Added Blood-Red Hardsuit to uplink for 8 TC
 * rscadd: Added Syndicate Bomb to uplink for 13 TC
 * rscadd: Added Syndicate Minibomb to uplink for 6 TC
 * rscadd: Added Dehydrated Space Carp to uplink for 3 TC
 * rscadd: Added Syndicate Detonator to nuke ops uplink for 3 TC

2016-11-19 17:42 UTC, Shadowmech88 commented
No lasagna bombs?

2016-11-19 17:45 UTC, uraniummeltdown commented
When You Sprite It

2016-11-19 17:45 UTC, ghost commented on code/game/machinery/gashapon.dm
> +		/obj/item/toy/carpplushie,
Sweet jesus what are you doin

2016-11-19 17:47 UTC, Skullyton commented on code/game/objects/items/dehy_carp.dm
> +	new /mob/living/simple_animal/hostile/carp(get_turf(src))
So, this makes a straight up full-grown space carp?

Why not a space carp child? We have those, and it'd interact with carp pheremones better

2016-11-19 17:48 UTC, Shadowmech88 commented on code/game/objects/items/dehy_carp.dm
> +	new /mob/living/simple_animal/hostile/carp(get_turf(src))
I imagine this item is more for traitors who want to immediately deploy pocket carps as a weapon, not raise baby carps and feed them meat until they grow enough to be useful.

2016-11-19 17:49 UTC, ghost commented on code/game/machinery/gashapon.dm
> +		/obj/item/toy/carpplushie,
The sprite is an improvement over gasha/carptoy, otherwise it's the same. This is not the dehydrated one

2016-11-19 17:49 UTC, Shadowmech88 commented on code/game/machinery/gashapon.dm
> +		/obj/item/toy/carpplushie,
I think he means why did you change the object path?

2016-11-19 17:50 UTC, Skullyton commented on code/game/objects/items/dehy_carp.dm
> +	new /mob/living/simple_animal/hostile/carp(get_turf(src))
Baby carp grow from eating, including when they bite a person. It'd just give some potential to being able to fight back against insta-carp, such as grabbing em in your hands

2016-11-19 17:53 UTC, Skullyton commented
>Instant space carp are 3TC, just add water
>Nuke ops have 80TC

26 space carp, jesus christ

2016-11-19 17:53 UTC, uraniummeltdown commented on code/game/objects/items/dehy_carp.dm
> +	new /mob/living/simple_animal/hostile/carp(get_turf(src))
Less health, less damage to mobs. Although I could make special carp and baby carp spawned by the dehydrated one that do more damage to mobs, but carp as they are can already break bones

2016-11-19 17:59 UTC, uraniummeltdown commented on code/game/machinery/gashapon.dm
> +		/obj/item/toy/carpplushie,
The space carp plushie toy comes with a sound, attack_verb and better sprite, I removed the gasha carptoy as it had the same purpose and was inferior

2016-11-19 18:00 UTC, Skullyton commented on code/game/objects/items/dehy_carp.dm
> +	new /mob/living/simple_animal/hostile/carp(get_turf(src))
Yup, and a 25% chance from getting 2 space carp inflatables that one will be a male and another will be a female, so you'd end up with 5~7 space carp when the female explodes into babies

Moreso worse the more space carp dried meals you get as reproduce only requires the one male in vicinity, so 3 could potentially become 9~12, etc.

2016-11-19 19:00 UTC, yclatious commented
When I said, what next, pizza bombs, I was being sarcastic, jesus fuck, please don't add minibombs and pizza bombs, they are shitty antag objects, lazy as fuck traitoring, same with carps, its lazy copouts, plant and forget for massive damage, minibombs are particularly deadly since our atmos system is actually dangerous, sure, its 6tcs, but its still a garbage item that just promotes using and forgetting, for that,  we could use a wrench and some signaler igniter assemblies on welder tanks, takes effort, might expose you, planed chaos with tools that not everyone can get, but skilled players can with ease obtain, like gheto chemming acid, asking for a soldering iron, making a autolathe board and stealing the parts for it, making signalers and igniters without any suspicion of science or cargo, making it also possible for sec to out the blame on them since they have the available materials for it.

Also, 3tc for carps? Don't they reproduce ultra easily, if you are a xenobio or scientist, just steal all the monkey cubes, spray them around in somewhere that's restricted and bam, families of space carps, sounds particularly shit for low pop where you can just make them with ease and destroy a whole station with them, botanist duos in particular could do some major damage with just a few ranching crates, no?

Also, THE blood red hardsuit? The ultra robust, space worthy nuke ops suit, for just 8 tc? Maybe I'm just a sour puss raining on the parade, but minus the actual bombs, all of these item additions seem shit.

2016-11-19 19:07 UTC, jakmak3 commented
It would be pretty bitching to have expensive super hardsuits that cost lots of TC and mags with less slowdown and increased stomp damage for nuke ops. And speaking of which it would be great if hear me out on this completely. Reduce c20r damage and remove the stun BUT give the ops more TC and more guns to buy in which the more expensive guns would have the meme stun.

Also raise the blood red hardsuits  price by like 6 TC

2016-11-19 19:09 UTC, Intigracy commented
If people are bitching about the e20 bombs that are librarian specific now,
just wait until every traitor gets to buy the meme explosives from TG.

They straight up ruined round after round after round when people would buy
the bombs and the detonator that instantly explodes them.

2016-11-19 19:11 UTC, yclatious commented
Fuck no, don't remove the bloody C20r stun, we ain't fucking hippie, its the main gun of the syndies, its made to be a powerful as fuck gun to go madman at, its the most important tool in a syndies arsenal, and not stunning when our combat is so heavily repaint on stuns is stupid as fuck, it'd be a massive nerf to nuke ops and they would loose a fuckton of their threat level by making their most crucial offensive tool made weak.

Tc gimmicks aside, nuke op still fail in a lot of the times they are in, nerfing their most powerful item for no good reason but for the sake of making them use other gear makes no sense.

2016-11-19 19:16 UTC, Intigracy commented
Exploitable because fuck being given grenades that fuck rounds up the first seconds.

2016-11-19 19:17 UTC, jakmak3 commented
I see where your coming from with that yclat but the nukies have no kind of weapon diversity and there isnt much in the way of having to strategically decide what to spend TC on since its common for ops to still have like over half of their tc left by the time they begin the assault and of course removing the stun would come with addition of more uplink purchasable guns the majority of which would have the meme stun in addition to extra TC in the uplink to offset the loss of the c20r stun.

2016-11-19 19:21 UTC, uraniummeltdown commented
Minibombs and Pizza bombs are 1,2,4, only one tile gets blown to space, it's not hard to repair the damage with them. Regular traitors can't buy the detonator for the syndicate bombs. Also I'll increase the hardsuit to 11 TC.

2016-11-19 19:27 UTC, Arthurdentist commented
we don't need to encourage more garbage antags

So what a traitor can buy a bomb but he can't use it? Why even let him buy the bomb in the first place.

2016-11-19 19:28 UTC, uraniummeltdown commented
The Syndicate Bomb has a regular timer of 120 seconds, the detonator is for instantly setting off all active ones

2016-11-19 19:28 UTC, yclatious commented
Nukies don't need weapon diversity, add too many and balancing becomes shit, make their weapons good, if limited, and you have very little room for fuckups, balance shitting or general fuckery.

I am completely against fucking the main tool of a antag group up the ass for the sake of gimmicky weapon variety, they do not need it, Nuke Ops are there to do 2 things, steal the disk and arm it, by force or stealth, fucking their main offensive tool so they have to waste tc to be viable compared to their previous status is shit, no avoiding this bollocks, its a bad idea to being with, nerfing something only to make them spend to go back to their initial quality point.

Why would the major assault weapons of a heavily armed, extremely experienced and well funded group of elite syndicate agents be shit anyways, its a good gun, don't fuck it up so they now need to be wasting tcs to be as good as they should be to begin with, on the bullshit excuse of making new, even more bullshittier guns that would be mandatory.

A single tc change and now we are turning into fucking tg. Fucking explosives that cause massive ZAS fuckery for everyone folks, ultra robust spacesuits, almost HoS tier shit for every traitor, just what we need for quality antagonism, right folks? Just what we all wanted and needed, people advocating the ass pounding of a gun to add more bullshit ones that will be required to be even remotely as good as the initial unerfed ones, for the sake of "variety".

What we all need /vg/, right here, the future of antaging, just stoop as low as fucking tg, that do wonders.

2016-11-19 19:35 UTC, Arthurdentist commented
So a traitor can buy this bomb, hide it somewhere then masturbate in a closet until it explodes? We shouldn't encourage this sort of thing at all. Lazy sods will take it every time. If its auto-traitor with 3 traitors you could conceivably have three very lazy antags blow three holes into the station in the first 5 minutes of the round. At least if you make your bomb you got to put it together first.

2016-11-19 19:38 UTC, TheFriggenSawbones commented
i agree with Arthur Dentist

2016-11-19 19:41 UTC, Intigracy commented
Don't even need to buy the big bomb, just throw the minibomb aka hand grenade at cloning.

2016-11-19 19:41 UTC, jakmak3 commented
Also just realized that the syndicate minibomb and big bomb are for normal traitors and not nukie exclusive. Jesus h christ that is a horrible idea for a normal traitor to have a device that can force a shuttle call 95% of the time

2016-11-19 20:18 UTC, yclatious commented
Change the acesibility of cancer shit all you want uranium, its still cancer shit nobody wants, and nobody should ever use or get due to it being cancerous excrement.

2016-11-19 20:42 UTC, Skullyton commented on code/game/objects/items/dehy_carp.dm
> +	var/owner = null
So, no chance of can_breed = 0?

2016-11-19 21:21 UTC, Ephx1 commented
Why do you keep opening PRs that very few people like?
Are you our new goofball?

2016-11-19 22:10 UTC, AutismSpider commented
@Shadowmech88  hate you so much https://www.youtube.com/watch?v=GmHlh6tQAO4

2016-11-19 22:12 UTC, kilozombie commented
I see nothing wrong with the carp. We already have viscerator grenades, which are plenty dangerous.
The bombs are fucking awful considering we have ZAS and it guarantees a shuttle call. Hell, even one E20 can end a round for everyone involved.
Even if the minibomb can't destroy floors, yeah, throw one at Cloning. That's nice.

2016-11-19 22:14 UTC, AutismSpider commented
carp bomb is fine we have viscerator grenades.

if going port over a bomb port over the fire bomb you fucking num nuts

2016-11-19 23:04 UTC, SonixApache commented
We don't ever have engineers and nobody understands how to open EVA to grab a spacesuit and a stack of metal so blowing a 3,7,14 hole in the station is a guaranteed shuttlecall two minutes in.
Remove minibombs from tators, keep for nukies.

Also protip: blood red suits are practically identical to the standard syndie spacesuit that nobody ever seems to use. Much better to keep them unique to nuke ops IMO.

Syndie spacesuit:
armor = list(melee = 60, bullet = 50, laser = 30,energy = 15, bomb = 30, bio = 30, rad = 30)
Bloodred hardsuit:
armor = list(melee = 60, bullet = 50, laser = 30,energy = 15, bomb = 35, bio = 100, rad = 60)

2016-11-20 01:27 UTC, whorena commented
Delete this, jesus christ we don't need more easy bombs.
There's 0 point giving nuke ops more bombs, even if they are tiny, because they already get huge ass 7 devs to use.
For anyone else, making a bomb, from 1 dev to 7 dev, is easy as hell. A pizza bomb doesn't even make sense, and for a minibomb you might aswell just grenade water and potassium.
The carp idea is a little silly, I don't think we need it. We already have holocarp, carp spawns are very common and if you want to utalize them well, put some effort into pheramones or get the old Pocket Carp out, plus we have the master trainer belt for miners which gives random mobs, I don't feel like we should be taking hostile pets away from traitor miners.

2016-11-20 01:36 UTC, yclatious commented
Not to be a prick, but folks, if Bill of all people is talking sense and even he agrees its hot garbage, maybe its time to fully reconsider how shitty this PR is.

Let's be real and practical here, these won't actually be any decent or would be used much for ops, and a Nuke Ops job isn't to breach halls, its to cripple the fuck out of everyone by carpetbombing important targets with their already existing bomb supply, eliminating the heads of command, all to get that fucking disk, small mini bombs really won't do shit, they will just shoot people anyways, and while you may ask, what about stealth guys who are there to fuck shit up, the actually decent guys won't do anything but get the fucking disk anyhow instead of antagging along.

2016-11-20 01:48 UTC, Blithering commented
If this gets merged new powergamer double agents strat: Buy the detonator, wait ten seconds, blow up every other syndie that has been mashing the bomb button.

2016-11-20 01:49 UTC, ComicIronic commented
_NUKE ONLY_

2016-11-20 01:51 UTC, yclatious commented
*STILL HOT CANCEROUS GARBAGE REGARDLESS OF ANTAG ACESS*

2016-11-20 01:53 UTC, Blithering commented
Ah, you're right, my bad. Don't see why ops would ever buy it then, as they already get enough free bombs to get the job done.

2016-11-20 08:36 UTC, SonixApache commented
It's kinda stupid that we have the syndicate bomb drink but not the actual bombs. 
I'd rather have them and never use them than not have them at all. 
If the bitching continues, maybe just remove the items from the uplinks?

2016-11-20 11:18 UTC, yclatious commented
The syndicate bomb drink is just a ttv with 2 beer glases on the side mate, its a toxins bomb, one they already have, basing the appearance of a bartender drink to justify extra bombs being added to nuke ops, rather shitty ones too, is a really bad excuse to add them.

2016-11-21 11:17 UTC, uraniummeltdown commented
All bombs except Pizza Bomb are now Nuke Ops only. Dehydrated Carp cannot breed.

2016-11-21 14:34 UTC, Kurfursten commented
@TheFriggenSawbones I 👍 Your comment about agreeing with @Arthurdentist

2016-11-25 20:19 UTC, icantthinkofanameritenow commented
Don't nuke ops already have several premade high-yield TTV bombs? I don't see them needing even more of them.

2016-11-27 15:04 UTC, uraniummeltdown commented
Ok Syndicate Bomb and Detonator are out of the Uplink now.

2016-11-27 20:08 UTC, PJB3005 requested changes

2016-11-27 20:08 UTC, PJB3005 commented on code/controllers/garbage.dm
> +	if(!isnull(D.gcDestroyed))
Alternatively, `return !isnull(D.gcDestroyed)`

2016-11-27 20:08 UTC, PJB3005 commented on code/datums/wires/syndicatebomb.dm
> +	if(P.open_panel)
`return P.open_panel`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	layer = MOB_LAYER - 0.1 //so people can't hide it and it's REALLY OBVIOUS
Make this a proper define.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		timer = max(timer - 2,0) // 2 seconds per process()
Make this get the delta time from the processing speed of the machinery process.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	if(active && !defused && (timer > 0)) 	//Tick Tock
Redundant parentheses.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	if(active && !defused && (timer > 0)) 	//Tick Tock
Also, make it so that `active && !defused` isn't duplicated below.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		return
No need for this return, as the below if can't be ran if the `active && !defused` passes.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		return
Again, no need for a return.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	..(user)
`..()` implicitly passes arguments.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	if(istype(I, /obj/item/weapon/wrench))
Make this use the `WRENCHANCHOR` machine flag.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	else if(istype(I, /obj/item/weapon/wirecutters) || istype(I, /obj/item/device/multitool) || istype(I, /obj/item/device/assembly/signaler ))
`is_type_in_list()`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +				payload.loc = user.loc
`forceMove()`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +			to_chat(user, "<span class='notice'>You place [payload] into [src].</span>")
Should have `\the`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +			user.drop_item()
Make this `drop_item` directly drop the item into `src`: `user.drop_item(payload, src)` and remove the below line.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +			to_chat(user, "<span class='notice'>[payload] is already loaded into [src], you'll have to remove it first.</span>")
`\the [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +			to_chat(user, "<span class='notice'>The bomb is bolted to the floor!</span>")
`\the [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	if(in_range(src, user) && isliving(user)) //No running off and setting bombs from across the station
1. Make this use `!Adjacent(user) || user.restrained() || user.isUnconscious()`
2. Make it return instead of the condition passes, and make the code block be outside the if.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		src.loc.visible_message("<span class='notice'>\icon[src] timer set for [timer] seconds.</span>")
Make this use `bicon()`.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +	if(alert(user,"Would you like to start the countdown now?",,"Yes","No") == "Yes" && in_range(src, user) && isliving(user))
Remove the checks at the end of the if.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +				payload.adminlog = "The [src.name] that [key_name(user)] had primed detonated!"
`\The [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +				log_game("[key_name(user)] has primed a [name] ([payload]) for detonation at [A.name]([bombturf.x],[bombturf.y],[bombturf.z])")
`\a`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +				message_admins("[key_name(user)]<A HREF='?_src_=holder;adminmoreinfo=\ref[user]'>?</A> has primed a [name] ([payload]) for detonation at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[bom
1. Use `key_name_and_info` and remove the `<A>` for the `?`
2. use `formatJumpTo`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		holder.loc.visible_message("<span class='danger'>\icon[holder] Alert: Bomb has detonated. Your score is now [defusals] for [attempts]. Resetting wires...</span>")
`bicon()`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		holder.loc.visible_message("<span class='danger'>\icon[holder] Alert: Bomb has detonated. Your score is now [defusals] for [attempts]. Resetting wires...</span>")
Also, use `speak()`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		holder.loc.visible_message("<span class='notice'>\icon[holder] Alert: Bomb has been defused. Your score is now [defusals] for [attempts]! Resetting wires...</span>")
`bicon`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		X.loc = get_turf(src)
Make this `get_turf` the first argument passed to `new` and remove this line.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +				step(X, pick(NORTH,SOUTH,EAST,WEST))
`step_rand()`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		for(var/obj/machinery/syndicatebomb/B in machines)
Make a global list specifically for bombs, please.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +			message_admins("[key_name(user)]<A HREF='?_src_=holder;adminmoreinfo=\ref[user]'>?</A> has remotely detonated [detonated ? "syndicate bombs" : "a syndicate bomb"] using a [name] at <A HREF='?_src_
Use the same admin formatting procs mentioned earlier.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/machinery/syndicatebomb.dm
> +		spawn(30) cooldown = 0
Shouldn't do cooldowns with `spawn()`, use `world.time` timestamps for it:

Store the value of `world.time + 3 SECONDS` in a variable.
If said value is greater than `world.time` when the user tries to active the remote, it'll be on cooldown.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/beacon.dm
> +		to_chat(user, "\blue Locked In")
Oh man.

Remove colour macros.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/beacon.dm
> +	return
Trailing return.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +		to_chat(user, "<span class='notice'>[src] stares up at you with friendly eyes.</span>")
`\the [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +		to_chat(user, "<span class='notice'>You place [src] under a stream of water...</span>")
`\the [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +		loc = get_turf(O)
Make this move part of the `drop_item`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +/obj/item/toy/carpplushie/dehy_carp/afterattack(obj/O, mob/user, proximity)
Make this `get_turf` the first argument passed to `new` and remove this line.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +	visible_message("<span class='notice'>[src] swells up!</span>")
`\The [src]`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		timer = (input(user, "Set a timer, from one second to ten seconds.", "Timer", "[timer]") as num) * 10
`SECONDS`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		if(!in_range(src, usr) || issilicon(usr) || !usr.canmove || usr.restrained())
Should check `Adjacency` and whether the user's alive.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		timer = Clamp(timer, 10, 100)
`SECONDS`

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		to_chat(user, "<span class='notice'>You set the timer to [timer / 10] before activating the payload and closing \the [src].")
Should probably explicitly say seconds here.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		message_admins("[key_name_admin(usr)] has set a timer on a pizza bomb to [timer/10] seconds at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[loc.x];Y=[loc.y];Z=[loc.z]'>(JMP)</a>.")
Format the admin jump to with the correct proc.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +		message_admins("[key_name_admin(usr)] has triggered a pizza bomb armed by [armer] at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[loc.x];Y=[loc.y];Z=[loc.z]'>(JMP)</a>.")
Format admin jump to.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +			var/obj/item/stack/cable_coil/C = new /obj/item/stack/cable_coil(src.loc)
`getFromPool()` this and make the amount be set through the call.

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/devices/pizza_bomb.dm
> +			user.u_equip(src)
What?

2016-11-27 20:08 UTC, PJB3005 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	name = "Boxed Blood Red Suit and Helmet"
Remove capitalization.

2016-11-28 02:21 UTC, Exxion commented on code/game/objects/items/dehy_carp.dm
> +	visible_message("<span class='notice'>[src] swells up!</span>")
You know, if that's a standard, we should write it down.
Because the `\The` is extraneous. It's added automatically anyway.

2016-11-28 03:01 UTC, PJB3005 commented on code/game/objects/items/dehy_carp.dm
> +	visible_message("<span class='notice'>[src] swells up!</span>")
Readability.

2016-11-28 15:16 UTC, Exxion commented on code/game/objects/items/dehy_carp.dm
> +	visible_message("<span class='notice'>[src] swells up!</span>")
Yeah
So we should write it down somewhere

2016-12-04 20:26 UTC, icantthinkofanameritenow commented
Blood red hardsuits should probably be removed too- regular red space suits do all of the same.things for less than half of the proposed price. It would be a better idea to draw attention to that fact in the uplink description instead.

2016-12-04 20:33 UTC, ComicIronic commented
Doesn't the blood red hardsuit have significantly more armor?

2016-12-04 20:40 UTC, icantthinkofanameritenow commented
@ComicIronic 
Actually no. Here's the armor for the nuke op hardsuit:
(melee = 60, bullet = 50, laser = 30, energy = 15, bomb = 35, bio = 100, rad = 60)

And the red space suit:
(melee = 60, bullet = 50, laser = 30,energy = 15, bomb = 30, bio = 30, rad = 30)

Only really notable difference is that the nuke op suit has slightly more resistance to bombs, keeps viruses out, and is better protection from radiation- and in most rounds, none of those things will make a significant difference.

2016-12-04 21:47 UTC, Shadowmech88 commented
What if the traitor *wants* to be kill-on-sight, or make the crew think there are other nuclear operatives on board?

2016-12-04 21:56 UTC, AI-is-rogue commented
@Shadowmech88 A thing you attach to clothing to make it look like another piece of clothing of the same type?

2016-12-04 21:57 UTC, icantthinkofanameritenow commented
The first one is a bit hard for me to believe, given that there are ways of doing it that are more easily concealed so he can go loud at the right time (e.g. revolvers)  rather than being forced to do so. As for the second? Not sure what good that would do, since at the very least everyone with lethals will have them out and areas with already high security will be nearly suicidal to get into- to say nothing of howthere are other, less risky ways of getting the shuttle called. 

Using it simply doesn't seem to offer any advantages over the red space suits.

2016-12-04 21:59 UTC, icantthinkofanameritenow commented
@AI-is-rogue

That sounds very similar if not identical to the chameleon jumpsuit.

2016-12-04 22:04 UTC, AI-is-rogue commented
@icantthinkofanameritenow It is, but you would be able to change the appearance of exosuits and such rather than just jumpsuits.

2016-12-05 04:16 UTC, icantthinkofanameritenow commented
@AI-is-rogue 
Good idea, but like the chameleon jumpsuit it shouldn't be quite as potent as what it's mimicking. Stat-wise, it should be like a ghetto hardsuit- good enough to let you go into space without dying but useless as armor.

2016-12-05 04:37 UTC, Shadowmech88 commented
>but like the chameleon jumpsuit it shouldn't be quite as potent as what it's mimicking
I would expect it to not change the stats of the item at all, merely its appearance.

2016-12-05 04:56 UTC, icantthinkofanameritenow commented
@Shadowmech88 
Of course. So I'd suggest its stats be equivalent to the ghetto hardsuit or the basic grey space suit.

2016-12-05 18:03 UTC, uraniummeltdown commented
I'm not a huge fan of bombs any more, I'll make a bitesize PR with just the Dehydrated Carp and hardsuit later

2016-12-05 18:03 UTC, closed without merging

2016-12-05 20:52 UTC, SonixApache commented
Shame.