Fluff signs
d3athrow/vgstation13 pull request #12581
Opened 2016-11-20 16:42 UTC by unid15

![](http://puu.sh/soDHI/9ae7fa3aea.png)

2016-11-20 16:43 UTC, SkowronX commented
Moom runes go away

2016-11-20 16:44 UTC, unid15 commented
but chyna is a space superpower and also sol common is based on mandarin

2016-11-20 16:46 UTC, kol1th commented
I love you @unid15 

I'm going to make vaults at some point. Or away missions. 🤔

2016-11-20 16:46 UTC, SkowronX commented
sorry I dont speak orange

2016-11-20 22:20 UTC, Exxion commented
Out of curiosity, do those actually say anything, or is it just supposed to *look* like they do?

2016-11-20 22:26 UTC, unid15 commented
they're all real mandarin and most of them are even grammaticaly correct (except maybe for departmental ones because they were made with the assistance of google translate™)

2016-11-20 22:26 UTC, Intigracy commented
Middle one clearly says no humans allowed.

Das raycisst.

2016-11-20 22:49 UTC, PJB3005 requested changes

2016-11-20 22:49 UTC, PJB3005 commented on code/game/objects/structures/signs.dm
> +	name = "Imcomprehensible Sign"
Remove capitalization.

2016-11-20 22:50 UTC, Exxion commented on code/game/objects/structures/signs.dm
> +	name = "Imcomprehensible Sign"
That's the only problem you see with this line?

2016-11-20 22:53 UTC, RemieRichards commented
This is cute.

2016-11-20 22:58 UTC, Zth-- commented
Reminds me of that team fortress 2 map

2016-11-20 23:00 UTC, Intigracy commented on code/game/objects/structures/signs.dm
> +	name = "Imcomprehensible Sign"
The meaning of that first word is a little bit incomprehensible but other than that I dunno

2016-11-20 23:09 UTC, PJB3005 commented on code/game/objects/structures/signs.dm
> +	name = "Imcomprehensible Sign"
You're implying I actually proof read code instead of nitpicking on low hanging fruit. Hah!

2016-11-21 15:35 UTC, unid15 commented
Last 3 signs

![](http://puu.sh/spHlq/837561fc7e.png)

2016-11-22 18:43 UTC, ComicIronic commented
It would be cool if you extended examine so that if someone actually has Sol Common as a language, they would be able to read the sign. These are fine as is, though.

2016-11-23 02:49 UTC, PJB3005 approved these changes

2016-11-23 12:57 UTC, merged