Fluff computers 2.0
d3athrow/vgstation13 pull request #12608
Opened 2016-11-27 15:44 UTC by jakmak3

old PR --> https://github.com/d3athrow/vgstation13/pull/12575

This adds in several new computers that do litterally nothing except give a access denied message. The only purpose for these computers is for vaults/away missions for immhulsions purposes. When jwmturners mapping PR is closed/merged i will make a pr to replace some of the empty computer consoles in the white ship with these.

Github broke so i had to re make the PR. essentially nothing has changed and i fixed some of the stuff the reviewers had pointed out to me.

2016-11-27 18:24 UTC, Signmark commented
if i had a dollar for every "fuck github" commit and branch name...

2016-11-27 18:59 UTC, Intigracy commented
https://xkcd.com/1597/

2016-11-27 19:04 UTC, PJB3005 requested changes
You still need to resolve all the issues in the previous PR, just so you know.

2016-11-28 21:26 UTC, CptWad commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A code locked console that you do not know how to use. Probably doesnt do anything interesting."
...doesn't do anything of interest."

2016-11-28 21:27 UTC, CptWad commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A code locked console that controls the ship. Doesnt look like you will be flying the ship anytime soon."
Doesn't

2016-11-28 21:31 UTC, CptWad commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A console with a map of the local area. Just by looking at this thing you can tell it is years out of date and is too old to be used effectivly"
Remove effectively. "too old to be used" is good enough

2016-11-28 21:32 UTC, CptWad commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by silicons.")
[this] console is so old

2016-11-28 21:55 UTC, Shadowmech88 commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A console with a map of the local area. Just by looking at this thing you can tell it is years out of date and is too old to be used effectivly"
Also lacking a period.

2016-11-28 22:02 UTC, Intigracy commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by silicons.")
[this] doesn't do anything though, and neither does \this if you meant that.

2016-11-28 22:03 UTC, Intigracy commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by silicons.")
Though` The` should be changed to `This`.

2016-11-29 00:17 UTC, CptWad commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "The console is so old that it cannot be remotely controlled by silicons.")
yes replace the with this thats what I meant

2016-11-29 02:21 UTC, Exxion requested changes

2016-11-29 02:21 UTC, Exxion commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "<span class='warning'>The systems firewall prevents you from accessing it.</span>")
`system's`

2016-11-29 02:21 UTC, Exxion commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "<span class='warning'>The systems firewall prevents you from accessing it.</span>")
`system's`

2016-11-29 02:21 UTC, Exxion commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "<span class='warning'>The systems firewall prevents you from accessing it.</span>")
`system's`

2016-11-29 02:21 UTC, Exxion commented on code/game/machinery/computer/fluffcomputer.dm
> +        to_chat(user, "<span class='warning'>The systems firewall prevents you from accessing it.</span>")
`system's`

2016-11-29 03:32 UTC, Exxion requested changes

2016-11-29 03:32 UTC, Exxion commented on code/game/machinery/computer/fluffcomputer.dm
> +    desc = "A code locked console that controls the ship's engines and power system's."
This one was correct to begin with

2016-12-19 20:04 UTC, 9600bauds commented
[Needs Grammar/Spelling)

2016-12-26 19:22 UTC, closed without merging