Can now drink from regular bottles
d3athrow/vgstation13 pull request #12605
Opened 2016-11-26 11:23 UTC by Skullyton

Reapproach of #10631 , now with more integrated suggestions, and less sipping from chempacks

Fixes #10614

:cl:

- rscadd: Can now drink from chem bottles, beakers, etc.
- rscadd: The amount you drink from these bottles/beakers depends on their set transfer rate
- rscadd: If you attempt to force feed somebody from a beaker, the time required scales with the amount you are trying to transfer
- rscadd: To splash a person, or yourself, with the contents of a beaker, you must be in any intent but help

2016-11-26 15:01 UTC, ComicIronic commented on code/modules/reagents/reagent_containers.dm
> +				if(H.species.chem_flags & NO_DRINK)
Don't like the copy paste of this block, put it into its own block.

2016-11-26 20:56 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +				if(H.species.chem_flags & NO_DRINK)
What, like check_drink(H)?

Seems a bit odd for something so specific, but I guess we could have it if anyone adds, say, being able to remove tongues, or jaws

2016-11-26 22:00 UTC, ComicIronic commented on code/modules/reagents/reagent_containers.dm
> +				if(H.species.chem_flags & NO_DRINK)
I mean the entire code for drinking - it's down in imbibe() as well. Anything you write twice in a way that it has to be the same in both cases should be a proc.

2016-11-26 22:52 UTC, FudgePucker commented
I don't know about letting players drink 100 units at a time. That seems like you can put in 100000 units of antitoxin to powergame

2016-11-26 23:45 UTC, kilozombie commented
IIRC a creature's reagent container can only hold like 300u?

2016-11-26 23:54 UTC, Sprok0 commented
A human can hold 1000u

2016-11-27 01:01 UTC, Allspice commented
Can eat 50u pills anyway, no particular difference on that bit.

2016-11-27 03:01 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +				if(H.species.chem_flags & NO_DRINK)
Fair point, and good spot on the weirdness going on there. Sorted now

2016-11-27 09:55 UTC, Zth-- commented
What about the lids? Did you change it or they're still the same?

2016-11-27 17:56 UTC, Skullyton commented
The same as usual. For lids, you click it in-hand. For drinking, you click on your or anothers sprite

2016-11-27 18:08 UTC, Zth-- commented
I'm asking because I do everything with the "Z" key. I drink alcohol with the Z key, and put beaker's lid with the Z key. I guess the default will still be the lid for beakers

2016-11-27 18:58 UTC, Skullyton commented
Z is attack_self IIRC, so should still work

2016-11-27 22:49 UTC, Iamgoofball commented on code/modules/reagents/reagent_containers.dm
> +			reagents.remove_any(amount_per_transfer_from_this)
make it react with the ground below it first, if I chug thermite as a skeleton and it falls to the ground I should be able to light it

2016-11-27 22:52 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +			reagents.remove_any(amount_per_transfer_from_this)
Isnt that what the above reagents.reaction(get turf(h), touch)

2016-11-27 22:53 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +			reagents.remove_any(amount_per_transfer_from_this)
Does?

2016-11-27 23:31 UTC, Intigracy commented on code/modules/reagents/reagent_containers.dm
> +			reagents.remove_any(amount_per_transfer_from_this)
Yes, ignore goofball.

2016-11-28 01:06 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +			reagents.remove_any(amount_per_transfer_from_this)
goof ya goof

2016-11-28 06:37 UTC, kol1th commented
I love you 👍

2016-11-28 14:30 UTC, ComicIronic requested changes

2016-11-28 14:30 UTC, ComicIronic commented on code/modules/reagents/reagent_containers.dm
> +		M.attack_log += text("\[[time_stamp()]\] <font color='orange'>Has been fed [src.name] by [user.name] ([user.ckey]) Reagents: [reagentlist(src)]</font>")
Replace from this down to setting LAssailant with a call to add_attacklogs, it handles all the stuff for you.

2016-11-29 01:31 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +		add_attacklogs(user, M, "force-fed", src, "amount:[amount_per_transfer_from_this], container containing [reagentlist(src)]")
Done, but it might get a bit obnoxious

2016-12-02 00:19 UTC, ComicIronic commented on code/modules/reagents/reagent_containers.dm
> +		add_attacklogs(user, M, "force-fed", src, "amount:[amount_per_transfer_from_this], container containing [reagentlist(src)]")
No, I meant remove the LAssailant stuff as well - add_attacklogs does that too.

2016-12-02 01:38 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +		add_attacklogs(user, M, "force-fed", src, "amount:[amount_per_transfer_from_this], container containing [reagentlist(src)]")
???

2016-12-02 01:39 UTC, Skullyton commented on code/modules/reagents/reagent_containers.dm
> +			M.LAssailant = user
So, this

2016-12-02 13:00 UTC, ComicIronic commented on code/modules/reagents/reagent_containers.dm
> +			M.LAssailant = user
Yes.

2016-12-10 00:01 UTC, Skullyton commented
fork broke, head to #12719

2016-12-10 00:01 UTC, closed without merging