Adds 7 possible artifact effects
d3athrow/vgstation13 pull request #12715
Opened 2016-12-09 21:11 UTC by Sprok0

Needed to remake #12513 due to DMCA issues

Adds 7 new possible effects for large artifacts to be generated with. The effects added are:

Stops time around it
Fires projectiles in random directions around it
Cultifys turfs/windows/grilles in a small or fairly large radius around itself
Generates an anti-light area while active
Pulls objects toward itself
Fully fills a person's reagent vessel for a duration
Revives a nearby dead person, but turns the toucher into a shadowperson

Adds a generic projectile firing proc for future use
Allows artifact batteries to copy any variable needed from an artifact effect

2016-12-09 21:41 UTC, Intigracy commented
I requested a review from Comic since he had some changes on the last one and I dunno if you addressed them all.

2016-12-11 01:33 UTC, Skullyton commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
> +	target.toxloss = 0
Isn't this entire block from here down to 69 just revive() minus the animation?

2016-12-11 01:35 UTC, Sprok0 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
> +	target.toxloss = 0
It's like part revive and part defib revives, but doesn't regenerate limbs that were cut off

2016-12-19 20:37 UTC, 9600bauds commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_darkrevive.dm
> +	target.toxloss = 0
Maybe make it a proc somewhere

2016-12-19 20:39 UTC, 9600bauds commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gravity.dm
> +	pull_strength = pick(STAGE_ONE,STAGE_TWO,STAGE_THREE,STAGE_FOUR,10;STAGE_FIVE)
This makes it 10 times more likely to get STAGE_FIVE than any other stage, right?

2016-12-19 20:39 UTC, 9600bauds commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_reagentblock.dm
> +	if(ishuman(user) && prob(weakness * 100))
Why only for humans?

2016-12-19 20:41 UTC, Sprok0 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gravity.dm
> +	pull_strength = pick(STAGE_ONE,STAGE_TWO,STAGE_THREE,STAGE_FOUR,10;STAGE_FIVE)
I thought it would make it one tenth as likely? That's what the DM ref says, and it didn't come up often in testing.

2016-12-19 20:43 UTC, Sprok0 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_reagentblock.dm
> +	if(ishuman(user) && prob(weakness * 100))
Because things that aren't humans don't really do much with reagents. Monkeys and xenos work I guess, but why bother

2016-12-19 20:43 UTC, 9600bauds commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_gravity.dm
> +	pull_strength = pick(STAGE_ONE,STAGE_TWO,STAGE_THREE,STAGE_FOUR,10;STAGE_FIVE)
Nevermind, DM says the base value is 100, not 1, this is correct

2016-12-19 20:45 UTC, 9600bauds commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_reagentblock.dm
> +	if(ishuman(user) && prob(weakness * 100))
You could change this to iscarbon() and probably not need to adjust anything, I think

2016-12-19 21:30 UTC, 9600bauds commented
:+1:, I'd move the definition of limitedrevive() to some more fitting file though

I think @ComicIronic was supposed to review this too

2016-12-20 04:25 UTC, 9600bauds commented
Preliminarily seems good to me

2016-12-20 04:26 UTC, 9600bauds approved these changes

2016-12-21 08:51 UTC, Intigracy commented
Guess the review request didn't actually work last time I tried, did this time.

2016-12-21 08:53 UTC, Probe1 commented
Wow those are really good.  Nice one @Sprok0

2016-12-23 14:15 UTC, PJB3005 requested changes

2016-12-23 14:15 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_projectiles.dm
> +/var/global/list/validartifactprojectiles = list(
Remove `/global` here.

2016-12-23 14:15 UTC, PJB3005 commented on code/modules/spells/aoe_turf/fall.dm
> +		oureffects += getFromPool(/obj/effect/stop/sleeping, T, sleepfor, user:mind, src, invocation == "ZA WARUDO")
Is the colon still needed here?

2016-12-23 19:04 UTC, Sprok0 commented on code/modules/spells/aoe_turf/fall.dm
> +		oureffects += getFromPool(/obj/effect/stop/sleeping, T, sleepfor, user:mind, src, invocation == "ZA WARUDO")
It seems to work without it, but I can't really test very hard alone

2016-12-23 20:45 UTC, Probe1 approved these changes
Sprok is /ourguy/

2016-12-27 13:12 UTC, PJB3005 approved these changes

2016-12-27 13:12 UTC, merged

2016-12-27 14:06 UTC, BobdaBiscuit commented
tiem 4 artefacts