Sharpness flags
d3athrow/vgstation13 pull request #12728
Opened 2016-12-10 00:14 UTC by 9600bauds

Adds sharpness flags to allow more specific types of sharpness and prevent shit like butchering animals with a syringe

2016-12-10 00:16 UTC, Intigracy commented on code/game/objects/items/stacks/sheets/leather.dm
> +	if(W.is_sharp() >= 1.2 && W.sharpness_flags & SHARP_BLADE)
Not an or for SERRATED_BLADE ?

2016-12-10 00:17 UTC, Intigracy commented on code/game/objects/items/weapons/kitchen.dm
> +	sharpness_flags = SHARP_TIP | SHARP_BLADE
this and plastic inherit from parent

2016-12-10 00:18 UTC, 9600bauds commented on code/game/objects/items/stacks/sheets/leather.dm
> +	if(W.is_sharp() >= 1.2 && W.sharpness_flags & SHARP_BLADE)
You'd fuck up a hide pretty bad with a blunt serrated blade

2016-12-10 00:18 UTC, Intigracy commented on code/game/objects/items/weapons/melee/energy.dm
> +	sharpness_flags = SHARP_BLADE | HOT_EDGE
SHARP_TIP?

2016-12-10 00:18 UTC, Intigracy commented on code/game/objects/items/weapons/melee/energy.dm
> +	sharpness_flags = SHARP_BLADE | HOT_EDGE
Nevermind just saw the subtypes.

2016-12-10 00:30 UTC, Intigracy commented on code/modules/reagents/reagent_containers/food/drinks.dm
> +	sharpness_flags = SHARP_TIP | SHARP_BLADE
Broken bottles are mostly good at stabbing, not swinging to cut.

2016-12-17 17:23 UTC, ComicIronic commented on code/game/objects/items/latexballoon.dm
> +	if (W.sharpness_flags & SHARP_BLADE || W.sharpness_flags & SHARP_TIP || W.sharpness_flags & HOT_EDGE)
`if (W.sharpness_flags & (SHARP_BLADE|SHARP_TIP|HOT_EDGE))` should work, and  is nicer to read.

2016-12-17 17:24 UTC, ComicIronic commented on __DEFINES/setup.dm
> +#define INSULATED_EDGE 	16 // One of the edges of this thing is insulated, even though the rest of it isn't.
What would this be used for?

2016-12-17 17:25 UTC, ComicIronic commented on code/game/objects/structures/flora/flora.dm
> +		if(W.sharpness_flags & CHOPWOOD || W.sharpness_flags & SERRATED_BLADE)
Do a similar thing to the `&` and `||` for this.

2016-12-17 17:26 UTC, ComicIronic commented on code/modules/hydroponics/hydro_tray.dm
> +	else if((O.sharpness_flags & SHARP_BLADE || O.sharpness_flags & SERRATED_BLADE) && harvest)
etc

2016-12-17 18:18 UTC, 9600bauds commented on __DEFINES/setup.dm
> +#define INSULATED_EDGE 	16 // One of the edges of this thing is insulated, even though the rest of it isn't.
Glass spears for example

The spear itself is mostly conductive so if you chuck it at a shocked airlock it should spark and other similar behaviors

The spearhead is insulated so if you ATTACK something with it it shouldn't conduct

2016-12-18 02:27 UTC, 9600bauds commented
Done

2016-12-19 20:44 UTC, 9600bauds commented
will conflict with #12850

and it's just gonna keep conflicting

2016-12-20 11:14 UTC, Skullyton commented
Merge when? Need it for things in the snowmap

2016-12-20 20:33 UTC, Exxion commented on code/game/objects/items/weapons/melee/energy.dm
> +		sharpness = initial(sharpness)
God I hate this use of `initial()`
I know we use it for similar things elsewhere, but it fucks with VV and is just troublesome in general and we shouldn't.
I recommend storing the numbers for its on and off states and reading from those when switched instead.

2016-12-20 20:35 UTC, Exxion commented on code/game/objects/items/weapons/swords_axes_etc.dm
> +	sharpness_flags = SHARP_BLADE
No tip?

2016-12-20 20:36 UTC, Exxion commented on code/game/objects/items/weapons/tools.dm
> +	sharpness_flags = HOT_EDGE
It's at least as pointy as a screwdriver.

2016-12-20 20:36 UTC, unid15 commented on code/game/objects/items/weapons/melee/energy.dm
> +		sharpness = initial(sharpness)
How does it affect VV?

2016-12-20 20:37 UTC, Exxion commented on code/game/objects/items/weapons/twohanded.dm
> +	sharpness_flags = SHARP_TIP | SHARP_BLADE | CHOPWOOD
I'd expect from the name that it would be hot, but I have no idea

2016-12-20 20:38 UTC, Exxion commented on code/game/objects/items/weapons/twohanded.dm
> +	sharpness_flags = SHARP_TIP | INSULATED_EDGE
No blade at all?

2016-12-20 20:41 UTC, Exxion commented on code/game/objects/objs.dm
> +	var/sharpness_flags = 0 //Describe in which way this thing is sharp. Shouldn't sharpness be exclusive to obj/item?
Yes. So should this, `throwforce`, `force`, and `damtype`. But that sounds like a different PR.

2016-12-20 20:42 UTC, Exxion commented on code/game/objects/structures/lattice.dm
> +	if(C.sharpness_flags & CHOPWOOD || C.sharpness_flags & SERRATED_BLADE) // If C is able to cut down a tree
`if(W.sharpness_flags & (CHOPWOOD|SERRATED_BLADE))`
Like you did in `flora.dm`

2016-12-20 20:43 UTC, Exxion commented on code/modules/hydroponics/seed_datums.dm
> +				if(I.sharpness_flags & SHARP_BLADE || I.sharpness_flags & SERRATED_BLADE)
`if(W.sharpness_flags & (SHARP_BLADE|SERRATED_BLADE))`

2016-12-20 20:50 UTC, Exxion requested changes
Only the first part of this is actually important but apparently you can't add single comments while you have a pending review.

2016-12-20 20:50 UTC, Exxion commented on code/modules/mob/living/living.dm
> +			speed_mod = tool.sharpness_flags & SHARP_BLADE
& is not a boolean.
This will return 0 or `SHARP_BLADE`, not 0 or 1.

2016-12-20 20:50 UTC, Exxion commented on code/modules/projectiles/guns/projectile/constructable/hivehand.dm
> +	sharpness_flags = SHARP_TIP
I think it's also bladed, but who knows?

2016-12-20 20:52 UTC, Exxion commented on code/game/objects/items/weapons/melee/energy.dm
> +		sharpness = initial(sharpness)
You can't change the active sharpness of it and have it stick.

2016-12-20 20:56 UTC, 9600bauds commented on code/modules/mob/living/living.dm
> +			speed_mod = tool.sharpness_flags & SHARP_BLADE
Whoops, it was lazy regex, good catch

2016-12-21 00:56 UTC, 9600bauds commented on code/game/objects/items/weapons/twohanded.dm
> +	sharpness_flags = SHARP_TIP | SHARP_BLADE | CHOPWOOD
I think it's just supposed to vibrate really really fast

2016-12-21 00:57 UTC, 9600bauds commented on code/game/objects/items/weapons/twohanded.dm
> +	sharpness_flags = SHARP_TIP | INSULATED_EDGE
I don't quite like the idea of someone skinning an animal with the tip of their makeshift glass shard spear

2016-12-21 02:14 UTC, Exxion approved these changes

2016-12-21 12:19 UTC, merged

2016-12-21 12:25 UTC, Shadowmech88 commented
@9600bauds 
I just noticed that you didn't touch `organ_external` severing code.
Should limbs be able to be severed by items that are sharp, but don't have a blade?

2016-12-21 15:31 UTC, 9600bauds commented
Idunno, what would those be

Welding tools, screwdrivers and spears?

2016-12-21 15:40 UTC, Shadowmech88 commented
For now, more could possibly be added later.