Fixes #5152, Hair selection arrows are bugged
d3athrow/vgstation13 pull request #12809
Opened 2016-12-15 03:39 UTC by DrCelt

2016-12-18 16:42 UTC, PJB3005 requested changes

2016-12-18 16:42 UTC, PJB3005 commented on code/modules/mob/new_player/preferences_setup.dm
> +/datum/preferences/proc/valid_hairstyles(var/gender_restricted = TRUE)
Why does this one have a `gender_restricted` parameter, but not the other one?

Also, unify these.

2016-12-18 16:47 UTC, 9600bauds commented on code/modules/mob/new_player/preferences_setup.dm
> +/datum/preferences/proc/valid_hairstyles(var/gender_restricted = TRUE)
Because whoever coded this before decided there is no conceivable reason for female characters to grow a beard

2016-12-18 22:36 UTC, 9600bauds commented
k dun

2016-12-22 04:46 UTC, Intigracy commented on code/modules/mob/new_player/preferences_setup.dm
> +/datum/preferences/proc/valid_hairstyles(var/gender_restricted = TRUE)
Carn.

2016-12-26 03:06 UTC, Probe1 commented
@PJB3005 get back to this please.

2016-12-30 18:07 UTC, PJB3005 approved these changes

2016-12-30 18:12 UTC, merged