Fixes #11409
d3athrow/vgstation13 pull request #12830
Opened 2016-12-16 05:28 UTC by DrCelt

Fixes #11409 and anything else with an occupant variable that didn't handle this

2016-12-18 16:19 UTC, PJB3005 requested changes

2016-12-18 16:19 UTC, PJB3005 commented on code/game/dna/dna_modifier.dm
> +			if(!(M.gcDestroyed))
Redundant parentheses.

2016-12-18 16:19 UTC, PJB3005 commented on code/game/dna/dna_modifier.dm
> +	if(!(occupant.gcDestroyed))
Again.

2016-12-18 16:19 UTC, PJB3005 commented on code/game/machinery/Sleeper.dm
> +	if(!(occupant.gcDestroyed))
🤔

2016-12-18 16:19 UTC, PJB3005 commented on code/game/machinery/adv_med.dm
> +	if(!(occupant.gcDestroyed))
Again.

2016-12-18 16:19 UTC, PJB3005 commented on code/game/machinery/rechargestation.dm
> +	if(!(occupant.gcDestroyed))
Again.

2017-01-06 22:11 UTC, gbasood commented on code/game/dna/dna_modifier.dm
> +			if(!(M.gcDestroyed))
parens are scary

2017-01-06 22:35 UTC, Exxion commented on code/game/dna/dna_modifier.dm
> +			if(!(M.gcDestroyed))
Everyone knows more parentheses means more safety

<sub>--An actual comment in my old Steambot's code</sub>

2017-01-06 22:38 UTC, gbasood commented
@DrCelt reeee
fix the parens or check the box that lets contributors make changes to your PR

2017-01-08 18:40 UTC, Intigracy commented
It starts ticked by default, he intentionally unticked it.

2017-01-09 23:15 UTC, 9600bauds commented
is this really what passes as a negative review 22 days ago smh

2017-01-14 22:53 UTC, DrCelt commented
. NM

2017-01-14 22:54 UTC, Probe1 commented
But all you had to do is check let collabs make edits

2017-01-14 22:56 UTC, DrCelt commented
Okay so either I closed this due to a multiple personality or I assdialed the closing of the PR

2017-01-14 22:56 UTC, DrCelt commented
It's ticked

2017-01-14 23:31 UTC, gbasood commented
weird I'm not seing the option to pull it
at least Probe does though

2017-01-14 23:34 UTC, PJB3005 approved these changes

2017-01-14 23:34 UTC, merged