Fixes #11342
d3athrow/vgstation13 pull request #12832
Opened 2016-12-16 05:28 UTC by DrCelt

Fixes #11342
Adds feedback for hitting a spider cocoon
also fixes bug where items with nobludgeon would still bludgeon on a spider cocoon

2016-12-17 01:59 UTC, ComicIronic commented on code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
> +	if(W.attack_verb && W.attack_verb.len  && !(W.flags&NOBLUDGEON))
Indent both the if and the else under the parent `if (!(W.flags&NOBLUDGEON))`

2016-12-18 02:54 UTC, Intigracy commented on code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
> +	if(W.attack_verb && W.attack_verb.len  && !(W.flags&NOBLUDGEON))
`>not written as !(W.flags & NOBLUDGEON)`
y u make me cry

2016-12-18 16:26 UTC, PJB3005 requested changes
See what Comic said, doing this so I can see at a glance this PR needs changes.

2016-12-19 19:28 UTC, 9600bauds commented
will also conflict with #12720

2017-01-09 23:14 UTC, 9600bauds commented on code/modules/mob/living/simple_animal/hostile/giant_spider/effects.dm
> +	if(W.attack_verb && W.attack_verb.len  && !(W.flags&NOBLUDGEON))
@DrCelt

2017-01-24 19:42 UTC, N3X15 commented
Celt has vanished and this has conflicts.  RIP.

2017-01-24 19:43 UTC, closed without merging