Fixes MoMMIs nullspacing their hat on death (fixes #8142)
d3athrow/vgstation13 pull request #12893
Opened 2016-12-18 05:24 UTC by DrCelt

2016-12-18 12:03 UTC, PJB3005 commented on code/modules/mob/living/silicon/mommi/inventory.dm
> +		head_state.dropped(src)
Doesn't `drop_item` do all of this?

2016-12-18 12:30 UTC, Shadowmech88 commented on code/modules/mob/living/silicon/mommi/inventory.dm
> +		head_state.dropped(src)
I remember hearing that MoMMIs use some weird bastardized inventory slots that don't behave quite like regular mob inventory slots.

2016-12-18 13:01 UTC, PJB3005 commented on code/modules/mob/living/silicon/mommi/inventory.dm
> +		head_state.dropped(src)
Even then I think having these 4 lines that should be a generic drop proc is a bit bad for maintainability.

2016-12-18 13:23 UTC, PJB3005 requested changes
See my comment

2016-12-18 15:27 UTC, 9600bauds commented on code/modules/mob/living/silicon/mommi/inventory.dm
> +		head_state.dropped(src)
MoMMI inventory code is ASS
ALL
OF
IT

I'm serious, check the rest of the file, drop_item doesn't even support anything but the held item

2016-12-18 16:08 UTC, PJB3005 commented on code/modules/mob/living/silicon/mommi/inventory.dm
> +		head_state.dropped(src)
Doesn't mean this maintainability mess is acceptable.

2016-12-19 16:14 UTC, 9600bauds commented
God, I fucking hate MoMMI inventory code, as if it wasn't awful enough I never play silicon so I'm not even sure how silicon inventories are supposed to WORK

I hope I never have to touch this file again

2016-12-19 16:16 UTC, 9600bauds commented on code/modules/mob/living/silicon/mommi/death.dm
> -/mob/living/silicon/robot/mommi/death(gibbed)
this was literally a 1:1 copypaste of /mob/living/silicon/robot/death(), and it STILL called the parent anyways so it did everything twice

2016-12-19 16:17 UTC, 9600bauds commented on code/modules/mob/living/silicon/mommi/inventory.dm
> -/mob/living/silicon/robot/mommi/remove_from_mob(var/obj/O)
this was also a textual copypaste of /mob/proc/remove_from_mob(), for seemingly no reason, which obviously got outdated with the years

2016-12-19 16:18 UTC, 9600bauds commented on code/modules/mob/living/silicon/mommi/inventory.dm
>  /mob/living/silicon/robot/mommi/u_equip(W as obj)
this proc just wasn't used at all, just hackish copypaste all over the file to try to replace it

2016-12-19 22:47 UTC, PJB3005 approved these changes

2016-12-20 09:38 UTC, merged