Fixes #8231, Plasmamen being forevially jittery, drowsy, confused, et…
d3athrow/vgstation13 pull request #12899
Opened 2016-12-18 05:25 UTC by DrCelt

…c etc etc fuck whoever did this

2016-12-18 06:11 UTC, 9600bauds commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
important, please advise

2016-12-18 06:16 UTC, ghost commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
Yes

2016-12-18 06:17 UTC, 9600bauds commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
yes as in "this won't work"?

2016-12-18 06:18 UTC, 9600bauds commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
okay yeah I just tested and it indeed doesn't work

I'll probably just replace the IS_WHITELISTED flag

2016-12-18 06:21 UTC, Intigracy commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
2^0 through 2^15

2016-12-18 06:22 UTC, 9600bauds commented on __DEFINES/setup.dm
> +#define NO_SKIN 65536 //Is there a limit to how high flag defines can go?
so do I just cannibalize another flag or add a proc for this

2016-12-18 06:42 UTC, Intigracy submitted a review, later dismissed

2016-12-18 06:42 UTC, Intigracy commented on code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
>  	if(status_flags & GODMODE)
This should be above the adjustToxLoss

2016-12-18 11:32 UTC, PJB3005 requested changes
Make a new flags variable for this instead.

2016-12-18 13:45 UTC, BarneyGumball commented
You should update the wiki to reflect this change: http://ss13.moe/wiki/index.php/Races#Plasma_Men

2016-12-18 16:48 UTC, jknpj commented
<s>I liked being forever jitterry after getting shocked in a door

2016-12-18 18:40 UTC, 9600bauds commented
Take coffee

2016-12-18 18:47 UTC, 9600bauds commented
great, it already conflicts

2016-12-18 21:02 UTC, Intigracy commented
You're not going to be able to get rid of the secret repo conflict, whoever merges this has to fix it.

code/modules/mob/new_player/new_player.dm

2016-12-19 09:40 UTC, Imagebard commented
Maybe we should just remove the secret repo.

2016-12-19 11:24 UTC, PJB3005 commented
Hahaha haha a no

2016-12-19 12:03 UTC, ihadtoregisterforthis commented
Plasmamen feeling hunger more like feature loss

2016-12-19 12:18 UTC, PJB3005 approved these changes

2016-12-22 13:39 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21427368/540126fc-c83b-11e6-8c7c-9863cf50c5d0.png)

2016-12-23 03:30 UTC, 9600bauds commented
Fucking hell I'm only gonna fix this up after I get a promise that someone will sekritrepo it up

2016-12-23 14:53 UTC, PJB3005 commented
@9600bauds make an account on http://git.nexisonline.net/ and I'll give you sekrit repo access.

2016-12-28 17:53 UTC, 9600bauds commented
That'd be like

Sekrit repo selfmerging

which is logically the next step to selfmerging

2016-12-28 17:59 UTC, 9600bauds commented
grepped through this conflict bait to see if I missed anything (flags don't give compile errors!!!!!!), it's OK

2016-12-28 17:59 UTC, Exxion commented
Yeah that
That's already how it works, except worse

2016-12-28 18:03 UTC, Intigracy commented
If someone merged it here then clearly you can just add it on the SR and blame their merge.

I remove the conflict tag from PRs after I fix them on the repo, and I fix them on the repo after they're merged.

2016-12-28 18:04 UTC, Intigracy commented
Also fucking Imagebard I see that fucking loli image in my email convo for this PR.

2016-12-28 18:05 UTC, Exxion commented
>Having e-mail notifications on

2016-12-28 18:12 UTC, Probe1 commented
Yeah github support offers their apologies but there's no I'm sending the email

2016-12-30 18:26 UTC, 9600bauds commented
Someone PLEASE look at this conflict bait already

Even if there are no conflicts that Git detects, it has massive potential to cause future errors in other people's PRs
Say someone writes `species.flags & NO_SKIN` in their PR. That would be entirely incorrect after this flag refactor and wouldn't work as they intended - but Git wouldn't realize that, Travis wouldn't realize that, because IT DOESN'T THROW ANY ERRORS. They wouldn't even realize something was wrong unless they rebased to up-to-date and tested the same thing again.

2016-12-30 18:31 UTC, ComicIronic approved these changes
Nice flag split, looks consistent.

2016-12-30 18:32 UTC, ComicIronic commented
Done.

2016-12-30 18:46 UTC, 9600bauds commented
needs sekrit repo magic to be merged

2017-01-02 21:02 UTC, PJB3005 commented
@9600bauds make that account on N3X15's GitLab server and tell me so I can give you secret repo access.

2017-01-02 21:10 UTC, 9600bauds commented
This is the last time I fix conflicts on this thing
PLEASE do the needful for now, it's not my responsibility to have to self-merge it

2017-01-02 21:11 UTC, PJB3005 commented
What do you want me to make the changes to the secret repo?

2017-01-02 21:13 UTC, 9600bauds commented
what do you do when anybody else without secret repo access gets secret repo conflicts

2017-01-02 21:14 UTC, PJB3005 commented
Well, do it myself.

Since you're, you know, collab, I thought you'd want to do it yourself.

2017-01-02 21:17 UTC, merged

2017-01-02 21:27 UTC, 9600bauds commented
Oh, I didn't know the secret repo was an "every collaborator" thing, I never got that memo

Next time then