Adds Internal Bleeding First-Aid Kits to Paramedic Stations
d3athrow/vgstation13 pull request #12926
Opened 2016-12-19 07:26 UTC by Shadowmech88

The paramedic stations on Box, Deff, and Meta each get one kit, containing seven biofoam injectors.

2016-12-19 07:44 UTC, Probe1 commented
😕 

I feel like that's super strong and it will get raided by the crew.  Can't we put it on paramedics when they join and drop the number a bit too?

2016-12-19 13:13 UTC, jakmak commented
Probe you overestimate the crews competence. After the first few days people will forget it exists and paramedics will be the same old doctors with gimped access and only the best of the best medbay players would even acknowledge it's existence. Still it's a cool feature

2016-12-19 14:17 UTC, aceedex commented
This is real dope, but I also agree with probe to an extent. Also, I think it should be a little more secure. Unique items like that usually cause break ins, so I'd eager put them in the EVA locker. 

Maybe 1 injector on any joining Para and 3-4 in the kit

2016-12-19 14:20 UTC, Fruktlimpa commented
Make them not scannable by the device analyzer and make them unique in the sense that you cannot order more, because I would without a doubt pocket two of them at all times as the CEEMO if I knew they existed and weren't limitless.

2016-12-19 14:24 UTC, aceedex commented
I'd disagree on the scanning them part. I feel like the best niche a mechanic could fill is to reproduce items with no other means to do so. 

But I don't see a problem with sticking MECH_SCAN_FAIL on it until you can set a specific cost for it

2016-12-19 14:29 UTC, IsdatAfamas commented
Yeah at worst you can fix popped lungs in like 6 minutes if you are slow and without an incision manager. Id argue against giving something to the paramedics and not adding the kit to medbay storage tbh

2016-12-19 14:32 UTC, aceedex commented
On the other hand, anything that helps differentiate paramedic from MD but with shitty access is tip top stuf for me. Specially something like this that helps a lot in the first responder role the paramedic is supposed to be

2016-12-19 14:37 UTC, IsdatAfamas commented
Yeah but it doesnt make so much sense to give an advanced medication to a typically newer player, and someonw with less responsibilities and knowledge fluff wise. Parameds realistically at best need more actual rescue gear versus meds that straight up gimp the only surgical emergency the MDs deal with.

2016-12-19 14:44 UTC, Shadowmech88 commented
The idea behind paramedics getting these is so they can prevent patients from internally bleeding out as they're transported to Medbay, where the bleeding can actually be fixed.

2016-12-19 18:10 UTC, ghost requested changes

2016-12-19 18:10 UTC, DrCelt commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	return
Remove

2016-12-19 18:10 UTC, DrCelt commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	new /obj/item/weapon/reagent_containers/hypospray/autoinjector/biofoam_injector(src)
For loop this

2016-12-19 18:10 UTC, DrCelt commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	name = "oxygen deprivation first-aid kit"
But that's not atomic!

2016-12-19 18:11 UTC, DrCelt commented
Personally I think it's a little bit too powerful to give to parameds round start especially in this quantity

2016-12-19 18:32 UTC, 9600bauds commented
It just temporarily stops bleeding.

That sounds a lot better than it actually is. The guy probably already bled out by the time you get to him, and he still needs medical attention anyways.

Heck, you can already effectively stop internal bleeding via 40ubicard10uAT pills.

2016-12-19 18:34 UTC, 9600bauds commented
I agree with the limitation of 1 for each para + only 3/4 in the kit thou.

2016-12-19 18:34 UTC, jakmak commented
Celt the only way to stay alive with internal bleeding long enough to get the surgery is a 50 pill of bicard+anti tox to deal with the OD, several hundred U of iron or copious amounts of dex/dex+ or any combination of the 3. Much like the previously mentioned methods only top tier medbay memers like yred remember those methods exist and those same people would be the only ones to use the paramedic only biofoam

2016-12-19 18:35 UTC, 9600bauds commented
What makes you say paramedics wouldn't use their paramedic foam?

2016-12-19 18:38 UTC, 9600bauds commented
About the locker's secure-ness: Lockers are pretty tough to greytide into, you need like 6 IEDs in average to crack them open. I'm only really concerned about CMOs looting.

2016-12-19 18:40 UTC, Shadowmech88 commented
The only reason I didn't put it in the secure locker in the first place was that it was specifically labeled "Paramedic EVA Gear."

2016-12-19 18:44 UTC, 9600bauds commented
Oh, I thought it was in the locker

Put it in the locker or people will greytide for them

2016-12-19 20:00 UTC, Shadowmech88 commented
Should I rename the locker?

2016-12-19 20:03 UTC, 9600bauds commented
I don't think anyone will mind

2016-12-19 20:05 UTC, Shadowmech88 commented
You mean if I do, or if I don't?

2016-12-19 20:07 UTC, 9600bauds commented
If you do

If you add these to the lockers change the locker type instead of modifying the maps though

2016-12-20 05:10 UTC, Shadowmech88 commented
* The internal bleeding first-aid kit now contains just four biofoam injectors.
* The paramedic EVA gear locker has been renamed to paramedic gear.
* The internal-bleeding first-aid kit now spawns in the paramedic gear locker rather than out in the open.
* Paramedics now have a biofoam injector placed in their pocket when they spawn.

2016-12-20 05:17 UTC, 9600bauds approved these changes

2016-12-20 10:26 UTC, Fruktlimpa commented
If it only temporarily stops internal bleeding and surgery is still required then I don't mind. I assumed that they fixed internal altogether.

2016-12-21 08:54 UTC, Intigracy commented
Confrictu.

I still think it should get a recipe to create, probably something requiring multiple departments like medbots. (maybe make mint an ingredient in it :^)) Though that'd be a different PR.

2016-12-23 02:27 UTC, Shadowmech88 commented
Conflicts fixed.

2016-12-23 03:11 UTC, merged

2016-12-23 03:11 UTC, Probe1 commented
We can evaluate and rebalance if needed.