Dr. Acula: Untold
d3athrow/vgstation13 pull request #12930
Opened 2016-12-19 14:05 UTC by Kurfursten

Reopened due to DMCA. Old: #12506

I think everything from the previous PR was fixed except for updating the UI, but I'm not sure it makes sense to use Nano for only one bot.

2016-12-19 14:14 UTC, jknpj commented
>I'm not sure it makes sense to use Nano for only one bot.

No simple bot boy, no simple bot!

2016-12-19 14:14 UTC, PJB3005 commented
Just use Nano.

2016-12-20 12:45 UTC, despotate commented on code/game/machinery/bots/draculabot.dm
> +			dat += "<span class='danger'>WARNING: Viral agent detected. Ineligable for blood donation.</span><BR>"
**Ineligible**

2016-12-22 08:17 UTC, PJB3005 requested changes

2016-12-22 08:17 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +	user << browse("<HEAD><TITLE>Dr. Acula Controls</TITLE></HEAD>[dat]", "window=autoblood")
If you're not gonna use Nano, at least make it use browser datums.

2016-12-22 08:17 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +/obj/machinery/bot/bloodbot/proc/speak(var/message)
Wouldn't it be better to use `say` than `visible_message`?

2016-12-22 09:15 UTC, Kurfursten commented on code/game/machinery/bots/draculabot.dm
> +/obj/machinery/bot/bloodbot/proc/speak(var/message)
Sure, I don't have a strong preference.

2016-12-22 09:24 UTC, Probe1 approved these changes
I only skimmed the code but the design seems solid.

2016-12-23 10:51 UTC, Probe1 commented
![coderkillerwip2](https://cloud.githubusercontent.com/assets/8550416/21452273/cda0df5a-c8d3-11e6-8ca2-2cbfce181499.png)

Waiting on changes requested to be resolved.

2016-12-23 11:47 UTC, Kurfursten commented
A spaceman's greatest weapon

is patience

2016-12-23 11:50 UTC, jknpj commented
>A spaceman's greatest weapon is

autism

2016-12-23 11:52 UTC, Probe1 commented
A coders greatest threat is CONFLICTU and I'd like to see what you've worked so hard on merged.

2016-12-23 12:50 UTC, Kurfursten commented
It may look like it's near ready to go, but it's not. If it went to live like this, it would still be the half-assed version that only accepts empty bags and this really deserves to be full-assed. Rewriting how that works is going to take a little time.

2016-12-23 12:53 UTC, Probe1 commented
That attitude is why you are an awesome coder.

2016-12-27 02:33 UTC, Probe1 commented
THEN

HE

DIED

2016-12-27 06:31 UTC, Kurfursten commented
I'm still getting the mysterious map bug, can't code until we figure out what's up with that.

2016-12-27 12:36 UTC, Probe1 commented
We've resolved that issue here.  https://github.com/d3athrow/vgstation13/commit/3275888e64aec79e673170e76588925ce5a4eb4b#commitcomment-20299318

2017-01-03 22:15 UTC, Probe1 commented
THEN
HE
DIED
AGAIN

2017-02-05 20:38 UTC, Blithering commented
We must perform unholy rituals to raise this PR from it's coffin

2017-02-06 07:21 UTC, Probe1 commented
Reopen if you plan on working on it.

2017-02-06 08:33 UTC, Kurfursten commented
You can't reopen branches closed my collaborators

2017-02-06 09:19 UTC, Exxion commented
You can ask a collab to do it

2017-02-06 09:35 UTC, Iamgoofball commented
Also you totally can I do it all the time

2017-02-06 09:37 UTC, Exxion commented
False.

2017-02-16 11:24 UTC, Kurfursten commented
Curious is the coder's art. His PR unopenable by his own hand.

2017-02-16 12:40 UTC, Probe1 commented
Mortality clarified in a single click!

2017-02-16 12:53 UTC, Kurfursten commented
Status update
* Normal (nonemagged) is 100% tested and working
* Emagged mode still needs some bugfixing
* Needs browser datum or NanoUI

But I haven't fucked with UIs in at least a year. I can do browser datums since they're easy, but I'm willing to do Nano if PJB will link the documentation or whatever.

2017-02-16 19:25 UTC, PJB3005 commented
Just go browser if nano is too much of a hassle.

2017-02-17 01:25 UTC, Kurfursten commented
I don't mind writing it in Nano if you'll explain how to do it or link me to documentation that shows how.

2017-02-18 07:06 UTC, Kurfursten commented
At some point in the line did you lose your zeal for Nano?

2017-02-19 12:08 UTC, PJB3005 commented
https://wiki.baystation12.net/NanoUI

2017-02-20 12:56 UTC, Kurfursten commented
This is ready to merge

I went with a datum instead of nano because templ files were complicated

2017-02-20 18:26 UTC, PJB3005 requested changes

2017-02-20 18:26 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +	onclose(user, "bloodbot")
This is already done by browser datums.

2017-02-20 18:26 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +	var/datum/browser/popup = new(usr, "bloodbot", "[name]", 575, 400, src)
Make the UI key (`"bloodbot"`) be `\ref[src]` instead. No issues having two UIs open at once!

2017-02-20 18:26 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +	dat += "<TT><B>Acula-class Blood Donation Bot v1.0</B></TT><BR><BR>"
Don't browser datums have a title header already? Use that instead.

2017-02-20 18:26 UTC, PJB3005 commented on code/game/machinery/bots/draculabot.dm
> +			dat += "<span class='danger'>WARNING: Viral agent detected. Ineligible for blood donation.</span><BR>"
Are these styles even included in the browser datum CSS?

2017-02-20 19:07 UTC, Kurfursten commented on code/game/machinery/bots/draculabot.dm
> +	dat += "<TT><B>Acula-class Blood Donation Bot v1.0</B></TT><BR><BR>"
This makes the font impact or whatever, it's a sarif font

I use it for the bloodbags down below too, just to make the text look different

2017-02-20 19:13 UTC, Kurfursten commented
Okay, now you can merge it

2017-02-20 19:56 UTC, Probe1 commented
Ping @PJB3005 to check his review.

2017-02-20 20:15 UTC, PJB3005 approved these changes

2017-02-20 21:02 UTC, Probe1 commented
At this point I don't even know what this PR does anymore but the time is now.

2017-02-20 21:02 UTC, merged

2017-02-20 21:04 UTC, Kurfursten commented
It adds a crate to cargo for a fuckton of money that has a bot

The bot comes with 8 preloaded empty bags, and also 4 free cookies, so it's not a small deal. The bot will then collect blood donations from crew members who volunteer and have at least 90% of their blood. Every time 55u are donated, a new reward is dispensed.

Doctors still need to come by to collect and replace bags though.

2017-02-20 21:14 UTC, Probe1 commented
(I was just kidding with you I'm not that bad)

2017-02-20 21:19 UTC, SonixApache commented
yaaaay

2017-02-20 21:20 UTC, Blithering commented
These nightmarish PJB reviews can be felled, they can be beaten!

2017-02-20 21:21 UTC, Probe1 commented
In time you will know the tragic extent of my compile failings.

2017-02-20 21:30 UTC, Kurfursten commented
Glittering merges, feedback and 👍 -- paid for in pomfcoins.