Adds pAI Insertion Into Objects
d3athrow/vgstation13 pull request #12931
Opened 2016-12-19 14:14 UTC by Shadowmech88

This doesn't actually affect the game, this is purely the addition of a framework. I figure maybe now that it exists people might be inspired to do their own things with it.

This allows a pAI to be inserted into any `/obj` with its `can_take_pai` var set to `TRUE`. While inside an object, clicking said object will call `attack_integrated_pai()` on the object, which could be used to trigger a specific function or perhaps bring a menu up for the pAI.

2016-12-19 14:55 UTC, jknpj commented
pAI BUFFS FINALLY

2016-12-19 15:04 UTC, PJB3005 requested changes

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +	if(!istype(H))
Do a regular dexterity check instead.

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +	if (H.stat == DEAD)
Check all of these, and the rest, with `M.incapacitated()`.

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +	if(!istype(H))
You also need to check `Adjacent`

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +/obj/proc/attack_integrated_pai(mob/user as mob)
Again

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +/obj/attackby(obj/item/weapon/W as obj, mob/user as mob)
Again

2016-12-19 15:04 UTC, PJB3005 commented on code/game/objects/objs.dm
> +/obj/proc/install_pai(obj/item/device/paicard/P as obj)
Remove `as obj`, it does nothing.

2016-12-19 15:09 UTC, Ephx1 commented
Unless you actually go through with this, the only way to buff pAIs now would be to nerf borers.
I don't even know what machine interactions you would have for most things aside from being a literal switch to toggle something.

2016-12-19 15:18 UTC, jknpj commented
>I don't even know what machine interactions you would have for most things aside from being a literal switch to toggle something.

Egun pAI as ghetto Lawgiver

2016-12-19 16:29 UTC, pvak commented
pai inside a space suit

2016-12-19 16:34 UTC, Ephx1 commented
That is a genuinely cool feature from Bay that will probably never make its way here due to our hardsuits being simple clothing.

2016-12-19 16:59 UTC, aceedex commented
Maybe I'm stupid for thinking this, but you could recycle some oldborer code for it

2016-12-19 17:56 UTC, jknpj commented
>That is a genuinely cool feature from Bay that will probably never make its way here due to our hardsuits being simple clothing.

They can even use carded AIs in their rigsuit, but then again, rigsuits are way too broken.

>I don't even know what machine interactions you would have for most things aside from being a literal switch to toggle something.

Maybe some items getting stronger alt-versions when activated pAI are inside them? <s>but that's being a literal switch to toggle something.

2016-12-19 18:00 UTC, Ephx1 commented
I actually did outline a few things a loooooong time ago you could put pAIs in, but they were all the simple bots. If you could do that, that would be pretty neat.

2016-12-19 18:30 UTC, Shadowmech88 commented on code/game/objects/objs.dm
> +	if(!istype(H))
Do any mobs besides humans and methylin monkeys have dexterity?

2016-12-19 18:33 UTC, Shadowmech88 commented on code/game/objects/objs.dm
> +/obj/proc/install_pai(obj/item/device/paicard/P as obj)
For future reference, does it always do nothing?

2016-12-19 22:51 UTC, PJB3005 commented on code/game/objects/objs.dm
> +/obj/proc/install_pai(obj/item/device/paicard/P as obj)
When using a verb it IS relevant because then BYOND knows what type the variable is.

Otherwise no.

2016-12-20 03:21 UTC, Kitfox88 commented
>stuff pAI into every mechanical limb
>become megazord

2016-12-20 03:24 UTC, Shadowmech88 commented
Hopefully with pAI buffs will come more pAI players to fill the expanded roles.

2016-12-20 06:04 UTC, Exxion commented on code/game/objects/objs.dm
> +	if(!istype(H))
Adjacent() also checks for blockages.

2016-12-20 08:06 UTC, Shadowmech88 commented
* `/obj`s now also have a `on_integrated_pai_click()` proc, which is called whenever an integrated pAI clicks something that isn't the object itself. By default, the proc simply calls attack_pai().
* While integrated, pAIs can also manually attack_pai() machinery by using Ctrl+click.

This would allow, for example, a pAI to be placed inside a gun and operate it from within, firing at targets onscreen.

2016-12-20 09:52 UTC, Shadowmech88 commented
Since, as far as I know, pAIs have no current use for most hotkeys or for intents, I expanded the number of input-receiving `/obj` procs for integrated pAIs.

* Integrated pAIs can now manipulate their host objects via the equip, drop, throw, swap, cycle-intent-right, cycle-intent-left, help, disarm, grab, and harm hotkeys, as well as the `attack_self()` hotkey and clicking.

This means that a pAI could feasibly control 12 different functions of an item without having to even open a menu.

2016-12-20 13:47 UTC, yclatious commented
Please allow them to use * actions when inside stuff, I am sure sec would very much appreciate having a stun baton or egun spam *LAW as they beat the shit out of people or stun them.

2016-12-20 14:33 UTC, jknpj commented
>I also wanted pAIs to be able to move, but not use mechs, however from what I've seen mech code is already a godawful mess so no one will ever even think of doing that.

Being a co-pilot (switching equips, managing battery, lights, radio, et cetera) would be feasible, no? Even being able to eject your master's dead body from inside a mech would be enogh motivation to carry one with you.

2016-12-20 15:14 UTC, Shadowmech88 commented
>Please allow them to use * actions when inside stuff

I haven't specifically prohibited it, but I'm not sure how it works when a mob uses an emote while in the contents of another object.
Can pAIs even emote at all, as-is?

2016-12-20 17:50 UTC, yclatious commented
Im fairly certain they cannot, they cant even inspect stuff whilst in pockets.

2016-12-21 02:45 UTC, Shadowmech88 commented
>they cant even inspect stuff whilst in pockets

This PR should actually fix their inspecting, since their overridden `ClickOn()` proc now properly calls `ShiftClickOn()` if they're Shift+clicking.

2016-12-22 08:12 UTC, PJB3005 approved these changes

2016-12-22 08:13 UTC, PJB3005 commented
Is this done?

2016-12-22 14:05 UTC, Shadowmech88 commented
Yes.

2016-12-22 14:15 UTC, merged

2016-12-22 14:15 UTC, Shadowmech88 commented
Now the real fun can begin.

2016-12-22 14:18 UTC, Probe1 commented
pls no pAI power creep

2016-12-22 16:49 UTC, Intigracy commented
![zhmbqtx](https://cloud.githubusercontent.com/assets/4043940/21433162/9515a9c8-c823-11e6-80a8-f757abc8853c.jpg)