Fixes #12274
d3athrow/vgstation13 pull request #12941
Opened 2016-12-20 05:30 UTC by DrCelt

Fixes #12274

2016-12-20 09:44 UTC, PJB3005 requested changes

2016-12-20 09:44 UTC, PJB3005 commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Make this return `FALSE` excplicitly.

2016-12-20 09:44 UTC, DrCelt commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Why though

2016-12-20 10:03 UTC, PJB3005 commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Because this function should return a boolean, not either `TRUE` or `null`.

2016-12-20 10:04 UTC, DrCelt commented on code/game/objects/items/weapons/switchtool.dm
> +		return
That's a non standard formatting change

2016-12-20 10:07 UTC, PJB3005 commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Not really.

2016-12-20 10:09 UTC, DrCelt commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Yes really

2016-12-20 10:11 UTC, PJB3005 commented on code/game/objects/items/weapons/switchtool.dm
> +		return
No really.

2016-12-20 10:12 UTC, DrCelt commented on code/game/objects/items/weapons/switchtool.dm
> +		return
Yes really

2016-12-20 14:44 UTC, Exxion commented on code/game/objects/items/weapons/switchtool.dm
> +		return
It's not even a formatting change at all

2016-12-26 12:11 UTC, Probe1 commented
Re open when you address the review.

2017-01-09 23:13 UTC, 9600bauds commented on code/game/objects/items/weapons/switchtool.dm
> +		return
OK, I'll bite
Literally what difference would this ever make

2017-01-10 00:45 UTC, ComicIronic commented on code/game/objects/items/weapons/switchtool.dm
> +		return
1. This function is returning boolean values, so it should use that.
2. This function was converted from not returning anything, so it is not obvious in the code unless you read all the return statements that something actually comes out.
3. We hate Celt.

2017-01-10 01:59 UTC, Exxion commented on code/game/objects/items/weapons/switchtool.dm
> +		return
null and 0 are also not equal, and if you're a complete idiot/mad genius, you can exploit that

2017-01-15 19:56 UTC, gbasood commented
this whole file needs to be reformatted eventually, btw

2017-01-15 20:41 UTC, ComicIronic commented
Harsh

2017-01-15 23:09 UTC, merged