Ice Armor
d3athrow/vgstation13 pull request #12983
Opened 2016-12-21 17:04 UTC by Shadowmech88

Adds ice armor, craftable with 50 snow. Excellent melee and bullet protection, makes wearer cold.

Adds handle_clothing() proc to human/Life(), which calls clothing/on_mob_life() on every piece of clothing worn by the human.

:cl:
 * rscadd: Added ice armor, craftable with 50 snow.

2016-12-21 17:21 UTC, PJB3005 requested changes

2016-12-21 17:21 UTC, PJB3005 commented on code/modules/clothing/clothing.dm
> +/obj/item/clothing/proc/on_mob_life(var/mob/living/M)
There's already an `OnMobLife` in generic item code, better use this.

Make sure to check whether the user's wearing it.

2016-12-21 17:21 UTC, PJB3005 commented on code/modules/clothing/suits/armor.dm
> +	M.bodytemperature = max(M.bodytemperature-2.0 * TEMPERATURE_DAMAGE_COEFFICIENT,T20C)
Redundant decimals.

2016-12-21 17:28 UTC, jknpj commented
He did it the absolute madman

2016-12-21 17:31 UTC, Probe1 commented
think about the douchebaggery going on here.

@devlkiller0 , a person who seems very nice and eager to improve the server through discussion, asks for vox trader armor to have some kind of improvement.

Instead we get Celtic Armor _within 24 hours_.

2016-12-21 17:38 UTC, Nienhaus commented
If you want more ice clothing/armour https://www.dropbox.com/s/h7luzwf33plgdro/J.dmi?dl=0

2016-12-21 17:41 UTC, Probe1 commented
Nice sprites @Nienhaus !

2016-12-21 18:20 UTC, DrCelt commented
You could also set the heat_conductivity of the object to incredibly high levels - it's meant to be a scale from 0 to 1, and I accidentally set it to like 30,000 once, instantly absolute zero whenever anyone would put it on

2016-12-21 18:25 UTC, Shadowmech88 commented
How does `heat_conductivity` affect *gaining* heat from the environment?
Would the person be superheated if they wore it in a plasmafire?

2016-12-21 18:26 UTC, DrCelt commented
They would, aye, which I suppose would be against the purpose of the ice armour, you're right

2016-12-21 18:40 UTC, Nienhaus commented
Thanks @Probe1

2016-12-21 18:44 UTC, DrCelt commented on code/modules/clothing/suits/armor.dm
> +			to_chat(holder, "<span class='warning'>Your [src.name] is melting!</span>")
Every tick?

2016-12-21 18:47 UTC, Shadowmech88 commented on code/modules/clothing/suits/armor.dm
> +			to_chat(holder, "<span class='warning'>Your [src.name] is melting!</span>")
It only amounts to 10 messages maximum.

2016-12-21 18:48 UTC, Shadowmech88 commented
@Nienhaus 
Those sprites have given me some ideas, we will indeed have more ice content coming.

2016-12-21 18:58 UTC, PJB3005 requested changes

2016-12-21 18:58 UTC, PJB3005 commented on code/game/objects/items.dm
> +		if(slot_flags & SLOT_OCLOTHING)
Oh god.

It's probably better to iterate over the active bitflags of the `slot_flags` field and then do `H.get_item_by_slot(slot)`

Probably something along the lines of the following:
```dm
for (var/bit = 0 to 15)
    bit = 1 << bit
    if (bit & slot_flags && H.get_slot_by_id(bit))
        return TRUE
```

2016-12-21 18:58 UTC, PJB3005 commented on code/modules/clothing/suits/armor.dm
> +			to_chat(holder, "<span class='warning'>Your [src.name] is melting!</span>")
This seems like it'd get really spammy.

2016-12-21 19:05 UTC, Shadowmech88 commented on code/modules/clothing/suits/armor.dm
> +			to_chat(holder, "<span class='warning'>Your [src.name] is melting!</span>")
The message is only sent 10 times before the armor gets deleted.

2016-12-21 19:08 UTC, PJB3005 commented on code/modules/clothing/suits/armor.dm
> +			to_chat(holder, "<span class='warning'>Your [src.name] is melting!</span>")
True but still.

2016-12-21 19:10 UTC, DrCelt commented on code/game/objects/items.dm
> +		if(slot_flags & SLOT_OCLOTHING)
@PJB3005 Having a 0 to 15 loop for every clothing object on every human on every tick sounds like not the best idea

2016-12-21 19:29 UTC, PJB3005 commented on code/game/objects/items.dm
> +		if(slot_flags & SLOT_OCLOTHING)
@DrCelt there's little performance difference since he's still running a bunch of ifs.

Though ignore this comment because inventory code is awful and this doesn't work.

2016-12-21 21:19 UTC, PJB3005 approved these changes

2016-12-22 00:23 UTC, Imagebard commented
>Its just a resprited shadow armor

Holy shit Shadowmech why are you such a 1-use cocksleeve.

2016-12-22 00:26 UTC, Exxion commented
Holy shit Imagebard why are you such a 0-use cocksleeve

2016-12-22 00:28 UTC, DrCelt commented
Poor imagebard he's a good boy all he wants to do is shitpost and post loli

2016-12-22 00:33 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21411167/6d1ceffe-c7cd-11e6-9410-ac49919ac9f9.jpg)

2016-12-22 00:43 UTC, Intigracy commented
I'd rather not have github shut us down thanks.

2016-12-22 00:44 UTC, Imagebard commented
Shut this down
![000](https://cloud.githubusercontent.com/assets/7571238/21411341/fc6bb306-c7ce-11e6-8802-26a454aa8a03.jpg)

2016-12-22 00:45 UTC, Exxion commented
@d3athrow Repo ban him

2016-12-22 00:45 UTC, 9600bauds commented
![firefox_2016-12-14_02-51-56](https://cloud.githubusercontent.com/assets/6526157/21411377/d776d31c-c7c6-11e6-9ae9-0a1970b59636.png)

2016-12-22 00:46 UTC, Imagebard commented
Why is chicken so upset at loli?
![000](https://cloud.githubusercontent.com/assets/7571238/21411379/3c4b3140-c7cf-11e6-9a4c-a063da56e6da.jpg)

2016-12-22 00:47 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21411406/6cb77942-c7cf-11e6-828b-25cd94e4b4c2.jpg)

2016-12-22 00:47 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21411409/7a7ac82c-c7cf-11e6-9465-79805882920c.jpeg)

2016-12-22 00:48 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21411421/886932b6-c7cf-11e6-8326-0c403a374967.jpeg)

2016-12-22 00:48 UTC, Imagebard commented
![000](https://cloud.githubusercontent.com/assets/7571238/21411426/9987a2e4-c7cf-11e6-8ea4-cc75ff0e9fd1.jpg)

2016-12-22 00:49 UTC, Exxion commented
I got tired of deleting them.

2016-12-22 01:08 UTC, Intigracy requested changes

2016-12-22 01:08 UTC, Intigracy commented on code/game/objects/items.dm
> +	else
Way too much copypaste here.

```
var/mob/living/carbon/monkey/Mo = user
var/mob/living/carbon/monkey/H = user

if(!istype(H) && !istype(Mo))
   return FALSE
var/mob/M = user
```
then the bit stuff without the else block, call M.get_item_by_flag since you made it a mob level proc

2016-12-22 01:08 UTC, Intigracy commented on code/modules/clothing/suits/armor.dm
> +			qdel(src)
Just to be sure, qdeling suits automatically removes them from the mob, right?

2016-12-22 02:45 UTC, Shadowmech88 commented on code/game/objects/items.dm
> +	else
If I call `/mob/get_item_by_flag()` on a  `/mob/living/carbon/human` that's *cast* as a `/mob` while `/mob/living/carbon/human/get_item_by_flag()` exists, would it call `/mob/get_item_by_flag()` or `/mob/living/carbon/human/get_item_by_flag()`?

2016-12-22 02:48 UTC, Shadowmech88 commented on code/modules/clothing/suits/armor.dm
> +			qdel(src)
Yes, `qdel()` on any item calls `drop_item()` as part of `/obj/item/Destroy()`.

2016-12-22 02:49 UTC, Shadowmech88 commented
@Imagebard
It's not just the shadow armor. I also took the sleeves and legs from the squaddie armor.

2016-12-22 04:33 UTC, Intigracy commented on code/game/objects/items.dm
> +	else
It calls the highest available defined version of that proc it can.

Meaning the latter.

2016-12-23 02:40 UTC, Shadowmech88 commented
This should be good to go, I think.

2016-12-23 07:05 UTC, DrCelt commented
@Shadowmech88 do me a big favour and rebase this to after the dmitool was merged pretty please

2016-12-24 01:47 UTC, Shadowmech88 commented
@DrCelt 
Done.

2016-12-24 07:08 UTC, Intigracy approved these changes

2016-12-25 12:29 UTC, merged