Spelling/grammar/wording/etc fixes
d3athrow/vgstation13 pull request #12993
Opened 2016-12-22 01:19 UTC by Wizardcrying

!!! STILL WORKING ON MORE FIXES! DNM! !!!

I ended up including the entire `vending.dm` file in the first commit but I started with some other changes. 
Feel free to comment on anything I've changed or any changes I should make.

:cl: 
 * bugfix: Fixed many spelling/grammar/standardization/et cetera issues.

2016-12-22 04:56 UTC, Intigracy commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "It's made of a strong material developed by the Soviet Union centuries ago, allows for robust protection."
no comma, which allows for

2016-12-22 04:57 UTC, Intigracy commented on code/modules/clothing/under/jobs/security.dm
> +	desc = "A jumpsuit made of strong material, providing better protection. It has the word \"WARDEN\" written on the shoulders."
all the ones that say `providing better protection` should probably say `providing it better protection`

2016-12-22 05:00 UTC, Intigracy commented on code/modules/recycling/conveyor2.dm
> +	<br><span class='info'>It can be pried into a different direction using a crowbar but cannot be moved without welding it apart.</span>"
comma before but

2016-12-22 06:49 UTC, Wizardcrying commented
what the fuck

2016-12-22 07:20 UTC, PJB3005 approved these changes

2016-12-22 07:54 UTC, Intigracy commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	desc = "Merry Christmas"
But that one was fine?

2016-12-22 07:56 UTC, Intigracy commented on code/modules/reagents/reagent_containers/food/snacks.dm
> -	desc = "Merry Christmas!"
That was fine though.

2016-12-22 08:35 UTC, Probe1 commented
I believe in you @Wizardcrying

2016-12-22 09:09 UTC, Wizardcrying commented
thanks @Probe1

2016-12-22 09:10 UTC, Wizardcrying commented
I think that's it for this round folks, waiting for review, any further needed changes and merge

2016-12-22 09:14 UTC, Probe1 commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "A box containing wind grenades."
I'll take "Shit I didn't even know was in the code" for 500, Alex

2016-12-22 09:17 UTC, Probe1 commented on code/modules/detectivework/evidence.dm
>  	New()
Mental note to clean this shit code up.

2016-12-22 09:20 UTC, Probe1 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> -	desc = "Merry Christmas!"
If he's gonna clean up the bullshit let em clean up the bullshit.

2016-12-22 09:22 UTC, Probe1 commented
 >I'm done
 >Just kidding editing my post saying I'm done to say I'm doing more
TRUST ISSUES.

2016-12-22 09:23 UTC, Probe1 approved these changes

2016-12-22 10:30 UTC, Wizardcrying commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "A box containing wind grenades."
I think I discovered quite a few things on this mystical journey

2016-12-22 10:41 UTC, PJB3005 commented on code/modules/clothing/under/chameleon.dm
> -		A = input("Select colour to change to.", "BOOYEA", A) in clothing_choices
How to give celt a heart attack.

2016-12-22 10:41 UTC, Wizardcrying commented on code/modules/clothing/under/chameleon.dm
> -		A = input("Select colour to change to.", "BOOYEA", A) in clothing_choices
hehehe

2016-12-22 13:22 UTC, Probe1 requested changes
do the needful for syndigolashes please.

2016-12-22 13:22 UTC, Probe1 commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
```  /datum/uplink_item/nukeprice/syndigolashes ```

see above line in same file and edit.  also careful now you're changing paths not desc.

2016-12-22 19:09 UTC, Wizardcrying commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
This isn't defining the nuke price?

2016-12-22 19:27 UTC, Wizardcrying commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
It should already be edited.

2016-12-22 19:29 UTC, Probe1 approved these changes

2016-12-22 19:29 UTC, Probe1 commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
I thought this was the actual file.  I'm an ijiot

2016-12-22 19:54 UTC, Intigracy commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
ensure this is in none of the map files (check vaults too)

2016-12-22 19:57 UTC, Shadowmech88 commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
If it was in map files/vaults, wouldn't it cause a compile failure now that their path no longer exists?

2016-12-22 20:43 UTC, ghost requested changes

2016-12-22 20:43 UTC, DrCelt commented on code/modules/clothing/under/chameleon.dm
> +		A = input("Select color to change to.", "BOOYEA", A) in clothing_choices
this is non atomic

2016-12-22 20:56 UTC, Wizardcrying commented on code/modules/clothing/under/chameleon.dm
> +		A = input("Select color to change to.", "BOOYEA", A) in clothing_choices
no

2016-12-22 21:20 UTC, Wizardcrying commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
This IS the map counterpart. Maps would't use datums unless they use it like this. `code/datum/uplink_item.dm` is what you're looking for @Intigracy

2016-12-23 02:44 UTC, Wizardcrying commented on maps/ministation/uplink_item.dm
> +/datum/uplink_item/stealthy_tools/syndigaloshes/New()
This IS the map counterpart. Maps wouldn't use datums unless they use it like this. `code/datum/uplink_item.dm` is what you're looking for @Intigracy

2016-12-23 11:01 UTC, merged