Ornaments
d3athrow/vgstation13 pull request #13010
Opened 2016-12-22 21:17 UTC by Shadowmech88

![ornaments_on_tree](https://cloud.githubusercontent.com/assets/3991927/21440572/3a4c3e36-c859-11e6-8c4a-2c19af332dfb.png)

Adds ornaments. Boxes of ornaments can be printed from the autolathe for one glass sheet per box.
Ornaments can be colored via application of crayons and pens.
Ornaments can be hung on potted plants, and will show up on the plant's sprite wherever you click on it.

:cl:
 * rscadd: Adds ornaments. Boxes of ornaments can be printed from the autolathe. Ornaments can be colored via application of crayons and pens. Ornaments can be hung on potted plants, and will show up on the plant's sprite wherever you click on it.

2016-12-22 21:23 UTC, 9600bauds commented
![dreamseeker_2016-12-22_18-23-25](https://cloud.githubusercontent.com/assets/6526157/21440843/bf9eec36-c873-11e6-920a-27bb77212dd2.png)

2016-12-22 21:25 UTC, Shadowmech88 commented
My resolution isn't high enough for anything over 32x32 to fit on the screen and 32x32 itself is too small.

2016-12-22 21:30 UTC, PJB3005 requested changes

2016-12-22 21:30 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +					O = new /obj/item/ornament/red(get_turf(src))
I'm not keen on this.

I'd much prefer it if the object's name and such simply changed rather than spawning new objects.

2016-12-22 21:30 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
This is quite the hack.

2016-12-22 21:35 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +					O = new /obj/item/ornament/red(get_turf(src))
Yeah but what if mappers want to spawn a particular color of ornament for festive mapping?
Isn't it better for them to be able to spawn specific types than spawning a general ornament item and varediting it?

2016-12-22 21:37 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +					O = new /obj/item/ornament/red(get_turf(src))
Unless you mean keep the children but just don't use them for this, which seems a little strange to me, but I wouldn't mind.

2016-12-22 21:38 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
I'll change it if you have a better way.

2016-12-22 21:42 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
I think not calling `..()` on the subtype would be enough, can't think of any code that uses base item `attackby`.

2016-12-22 21:42 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +					O = new /obj/item/ornament/red(get_turf(src))
Eh it's fine I guess.

2016-12-22 21:43 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
The pAI code does now, though I doubt pAI-integrated ornaments would ever be a thing.

But it's possible that someone else may in the future put code into `/obj/item/attackby()` or `/obj/attackby()`.

2016-12-22 21:45 UTC, DrCelt commented
Could you wait until #12784 is merged to merge this so I don't have to fix fucken dmi conflicts again aaaaaa

2016-12-22 21:45 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
Hrm, you're right.

Not sure then. Maybe an OOP list on the type so you can remove the copy paste entirely?

2016-12-22 21:54 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
Is there a way to create a list with custom indexes aside from manually adding elements one by one?

2016-12-22 21:55 UTC, PJB3005 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
You mean with numeric indices or assoc indices?

For numeric sadly not, but for assoc you can just do `list("x" = 10, "c" = 20)`

2016-12-22 21:56 UTC, ihadtoregisterforthis commented
Use x2 mode for the screenshot only, looks better

2016-12-22 22:00 UTC, Shadowmech88 commented on code/game/objects/items/ornaments.dm
> +	if(istype(src, /obj/item/ornament/teardrop))
Cool, then I can make a list var associating ornament types with the colors and just override the list for `/ornament/teardrop`.

2016-12-22 22:01 UTC, PJB3005 commented
No.

Use BYOND's built in screenshotting. It's at perfect resolution and objectively the best.

2016-12-23 02:01 UTC, Shadowmech88 commented
* Ornaments can now be hung on any flora, this includes large trees as well as potted plants.

2016-12-23 04:53 UTC, Shadowmech88 commented
* Added tree toppers, which can only be hung once per flora. Each box of normal ornaments has a 10% chance to contain a star topper.

2016-12-23 10:46 UTC, PJB3005 approved these changes

2016-12-23 10:46 UTC, merged