Smart Laser Gun
d3athrow/vgstation13 pull request #13019
Opened 2016-12-23 03:24 UTC by Shadowmech88

Adds smart laser gun, which can take pAIs by default.
Adds smart laser gun crate to Cargo, for twice the price of a standard weapons crate. It contains four smart laser guns.

Also adds framework for any gun to be usable, on a basic level, by pAI if the can_take_pAI var is changed to TRUE, opening up adminbus options.

:cl:
 * rscadd: Added smart laser guns, which can hold pAIs and be operated by them. Smart laser guns are orderable from Cargo.

2016-12-23 03:28 UTC, Kammerjunk commented
>which can take pAIs

Got my vote

2016-12-23 03:28 UTC, JustSumBody commented
>orderable from cargo

Oh
NO

2016-12-23 03:29 UTC, Shadowmech88 commented
I was originally going to put it into the protolathe, but @Sprok0 advised me that Cargo would be better.
At least this way Cargo, the only source of these guns, and Science, the only renewable source of pAIs, will have to collaborate in order for them to be stronger than a normal laser gun.

2016-12-23 03:30 UTC, jakmak3 commented
Why not add them to both cargo order, protolathe, and hell why not add them to the vault locker in armory/replace the xcom lazer in armory

2016-12-23 03:32 UTC, aceedex commented
This is p. neat but, I'm wondering a few things which might be a little stupid to ask.
Smart guns can only be fired by the pAI when held in one hand right? can the owner also shoot the gun if there's a pAI inside? do shots fired by the pAI share the same attack delay as the shots fired by the owner?

whatever the answer is though, this is real neat

2016-12-23 03:34 UTC, kilozombie commented
Holy christ playing a pAI just got twenty times more interesting.
Can't wait for more smart things, thank you

2016-12-23 03:38 UTC, jakmak3 commented
Also while we are at it lets brainstorm things that PAI's could do. Now what if PAI chem inject stuff was buffed to match that of borers and instead of being able to have all the chems in a single module you would have to buy each individual chemical in its own module Like having to download tricord or tramadol or coffee

2016-12-23 03:38 UTC, kilozombie commented
pAIs shouldn't be mobile chem dispensers, borers are already that and they're pretty lame at times. pAI insertion into items is THE FUTURE.

2016-12-23 03:41 UTC, jakmak3 commented
hmmmm borers being designed around to work with the body of its host and ignore all outside objects and technology excluding foreign chems and the PAI designed to have minimal interaction with the physiology of its owner and being intended to augment their owners machinery and equipment. I like that idea

2016-12-23 03:44 UTC, kilozombie commented
Yeah, that makes sense to me too. pAIs shouldn't match up to borers, they should fulfill a different purpose. The main things the two share is that they help you in some way and they're a friend to talk to at times.

2016-12-23 03:47 UTC, jakmak3 commented
exactly. Like what if PAI's were capable of tapping into the camrea net OR being able to get the AI view kinda deal of the area near the PAI cards location and also being able to send/recieve messages over any radio freq that was in the owners radio encryption key. Maybe if they could also provide a detailed HUD of the owners health in extreme detail (damage to each limb, alerts any broken bones/bleeding/internal bleeding)

2016-12-23 03:58 UTC, Shadowmech88 commented
@aceedex
>Smart guns can only be fired by the pAI when held in one hand right?

The pAI has full control, the master isn't a factor. The pAI can even fire the gun while it's on the ground.
>can the owner also shoot the gun if there's a pAI inside?

Yes.

>do shots fired by the pAI share the same attack delay as the shots fired by the owner?

The gun itself has a fire delay built in, so they can't work together to double-fire, if that's what you mean.
The pAI itself doesn't have an attack delay by default, so it's capable of firing the gun *slightly* faster on its own than a human can fire a gun. I don't think it'll be a problem.

2016-12-23 04:12 UTC, kol1th commented
How does it work log-wise?

2016-12-23 04:18 UTC, Ephx1 commented
I envisioned the smart gun from titanfall based on the title and panicked.
Glad to see pAIs are getting something, and this new system isn't just being tossed to the side.

2016-12-23 04:19 UTC, aceedex commented
@Shadowmech88 
It's everything I wanted and more. 
you're alright.
But does that mean you can fire it from a, say, backpack?

2016-12-23 04:21 UTC, Sprok0 commented
Can it fire from inside a recharger? Can I make smart, rapid fire laser turrets?

2016-12-23 04:24 UTC, kilozombie commented
What if you put it in a turret?

2016-12-23 04:29 UTC, Shadowmech88 commented
@aceedex 
Currently the pAI can fire it from literally anywhere.

I suppose I could restrict it to just turfs and mobs, so it can only fire while on the ground or in someone's hand/pocket.

2016-12-23 04:30 UTC, aceedex commented
nah, I don't think it's an issue. leave it as it is.

2016-12-23 04:34 UTC, Blithering commented
Anyone else getting a Rogue Trooper vibe from this?

2016-12-23 04:37 UTC, Shadowmech88 commented
If it becomes a problem in the future, it can always be changed then.

2016-12-23 04:39 UTC, kol1th commented
@Shadowmech88 
kol1th commented 27 minutes ago
How does it work log-wise?

2016-12-23 04:40 UTC, JustSumBody commented
Actually, that's not so bad then.

2016-12-23 04:44 UTC, Shadowmech88 commented
The `Fire()` proc logs shots using the `user` var, to which the pAI is passed as an argument.
So the logs should function normally, reading something along the lines of `pAIguy (pAIguy.ckey) fired gun at targetguy (targetguy.ckey)`.

2016-12-23 11:11 UTC, PJB3005 requested changes

2016-12-23 11:11 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "Smart laser gun crate"
Remove capitalization here.

2016-12-23 11:21 UTC, Shadowmech88 commented on code/datums/supplypacks.dm
> +	containername = "Smart laser gun crate"
Should I do the same for every containername in the file?

2016-12-23 11:22 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "Smart laser gun crate"
Nah don't bother.

2016-12-23 11:24 UTC, Shadowmech88 commented on code/datums/supplypacks.dm
> +	containername = "Smart laser gun crate"
But then if I fix this it's going to be inconsistent.

2016-12-23 12:59 UTC, PJB3005 commented on code/datums/supplypacks.dm
> +	containername = "Smart laser gun crate"
I've told multiple people to do this already, see inflatables.

The thing is, if they're capitalized they'll be proper nouns, so it'll be `That's Smart laser gun crate` vs `That's a smart laser gun crate`.

2016-12-23 22:02 UTC, Exxion commented
OK for most things I'd say leave being able to fire from anywhere as-is, but please for the love of god don't allow firing from within pipes or disposals

2016-12-23 22:03 UTC, Exxion commented
(For now just hardcode that. I plan on making a system in the future to handle that kind of thing properly, as well as some other stuff)

2016-12-23 23:51 UTC, Shadowmech88 commented
Do you happen to know offhand of a specific way to check whether something is inside a pipe or disposal pipe?

2016-12-23 23:57 UTC, Exxion commented
`get_holder_of_type()` or `get_holder_at_turf_level()`, checking if you're in either kind of pipe

2016-12-24 02:46 UTC, Shadowmech88 commented
* pAIs are now incapable of firing their gun if they're inside a pipe or disposal pipe

2016-12-26 13:57 UTC, PJB3005 approved these changes

2016-12-26 14:01 UTC, merged