Opposite Syndrome
d3athrow/vgstation13 pull request #13034
Opened 2016-12-23 16:06 UTC by Shadowmech88

Stage 2 virus symptom that causes victims to say the opposites of the words they mean to say.

Uses two big lists. Attempting to say a word that's in list 1 causes you to say the word at the equivalent position in list 2, and vice versa. New words can be added as long as both lists remain the same length.

:cl:
 * rscadd: Added opposite syndrome virus symptom, causing victims to say the opposites of the words they mean to say.

2016-12-23 16:08 UTC, Jeroen52 commented
Do make sure that Admins and logsurfers know that it is caused by the virus.

2016-12-23 16:10 UTC, Shadowmech88 commented
What would be the best way to go about that? Flashing a message to admins every time someone with the symptom says something?

2016-12-23 16:11 UTC, Exxion commented
I'm pretty sure that logs always record what you typed in, not what ended up coming out of your mouth

2016-12-23 16:28 UTC, Probe1 commented
This could be a headache for admins but that's never stopped us.

👍

2016-12-23 16:38 UTC, despotate requested changes

2016-12-23 16:38 UTC, despotate commented on code/modules/virus2/effect.dm
> +	if(!triggered)
Use if(count > 0)

2016-12-23 16:38 UTC, despotate commented on code/modules/virus2/effect.dm
> +	var/triggered = 0
remove

2016-12-23 16:38 UTC, despotate commented on code/modules/virus2/effect.dm
> +		triggered = 1
remove

2016-12-23 16:38 UTC, despotate commented on code/modules/virus2/wordlists.dm
> +//For lists of words to be used with viruses.
Try putting this in a folder in virus2 - maybe an "effect" folder, and move effect.dm into it as well?

2016-12-23 16:39 UTC, despotate commented
And thanks for fixing the whitespace I added everywhere in effect.dm!

2016-12-24 02:11 UTC, Shadowmech88 commented
@despotate 
I've done the formatting changes you requested.

I don't plan on changing functionality from where it is in this PR, because working with the text was a real headache for me so I'd like to see if a change is actually *necessary* before doing it.

2016-12-24 02:42 UTC, despotate commented
You still need a deactivate method unless you want your effect to run **forever** even after the virus gets cured.

2016-12-24 03:03 UTC, Shadowmech88 commented
I modeled it after hanging man syndrome, which I didn't see any such thing for.

Does that last forever after curing?

2016-12-24 03:11 UTC, DrCelt commented
Wouldn't using an assoc list be better in this case?

2016-12-24 03:15 UTC, Exxion commented
This is a two-way lookup
I honestly don't know if BYOND's list `Find()` proc even works with associative lists

2016-12-24 03:30 UTC, despotate commented
Hanging man's syndrome apparently does also last forever...

2016-12-24 07:15 UTC, Shadowmech88 commented
@despotate 
Done, it's got a `deactivate()` now.

2016-12-24 11:56 UTC, despotate commented
Final nitpick and I'm sorry for saying this after making you jump through so many hoops already especially considering how little I've contributed to the codebase myself, but would it be better for the `effects` folder to be renamed `effect` considering the datums in it are all children of `effect`, not `effects`?

2016-12-24 12:27 UTC, Shadowmech88 commented
The logic behind the naming was that it is to hold the relevant code for the multiple viral effect*s* we have.
I'll change it, though.

2016-12-24 12:32 UTC, Shadowmech88 commented
Okay, *now* this should be ready.

2016-12-25 22:46 UTC, ComicIronic commented
Rather than using two lists, use one indexed list i.e. `list("word" = "opposite")`

2016-12-26 04:22 UTC, Shadowmech88 commented
That would let me call list["word"] to return "opposite," but what if I wanted to give "opposite" as an argument to return "word"?
Would the list just need two indexes for each pair of words?

2016-12-26 13:47 UTC, ComicIronic commented
You'd have to do something more like 

```
for(var/word in list)
    var/opposite = list[word]
    if(myword == word)
        myword = opposite
    else if (myword == opposite)
        myword = word
```

2016-12-26 14:15 UTC, Shadowmech88 commented
Won't `for(var/word in list)` loop through the strings themselves though, rather than their indices?
Would I need to keep a separate list of indices, then loop through that list as I call the associative list on each iteration?

2016-12-26 14:19 UTC, despotate commented
This now has yuge conflicts because it conflicts with https://github.com/d3athrow/vgstation13/pull/13045 which moved around almost all of effect.dm.

Pull again, move effect.dm and your file to the effect folder, copy your function to its appropriate position (stages are ordered correctly now).

2016-12-26 14:50 UTC, ComicIronic commented
Looping through a string indexed list loops through the indexes, best I remember.

2016-12-26 14:53 UTC, Intigracy commented
Shadow that's what the ´var/opposite = list[word]´ line is for, it's getting the index of each word, and each word is gotten through the for loop.

2016-12-26 14:59 UTC, unid15 commented
here's an idea - have only one indexed list at first, BUT then use it to generate two lists like you have now

2016-12-27 17:14 UTC, Exxion commented
Comic is right

2017-01-01 05:32 UTC, Shadowmech88 commented
Conflicts fixed, also it uses a single associated list now instead of two lists.

2017-01-03 02:35 UTC, Shadowmech88 commented
Conflicts fixed *again*.

2017-01-05 20:52 UTC, PJB3005 requested changes

2017-01-05 20:52 UTC, PJB3005 commented on code/modules/virus2/effect/wordlists.dm
> +/datum/disease2/proc/initialize_word_lists()
Why is this on the main disease type instead of the opposite syndrome's one?

2017-01-05 20:52 UTC, PJB3005 commented on code/modules/virus2/effect/wordlists.dm
> +var/global/list/virus_opposite_word_list
Remove `global` here

2017-01-05 20:52 UTC, PJB3005 commented on code/modules/virus2/effect/wordlists.dm
> +	virus_opposite_word_list = list("to"		=	"from",				//1
You should make the first line here start blank and only indent the actual list content by 1 tab.

2017-01-05 20:52 UTC, PJB3005 commented on code/modules/virus2/effect/wordlists.dm
> +	virus_opposite_word_list = list("to"		=	"from",				//1
Also, why're you keeping those numbers around?

2017-01-05 20:57 UTC, Shadowmech88 commented on code/modules/virus2/effect/wordlists.dm
> +/datum/disease2/proc/initialize_word_lists()
I was accounting for the fact that someone else might at some point make a symptom that needs to use one or more such word lists, so I made it a basic disease-level proc so any symptom could call it.

2017-01-05 21:45 UTC, PJB3005 commented on code/modules/virus2/effect/wordlists.dm
> +/datum/disease2/proc/initialize_word_lists()
Seems oddly specific to me.

2017-01-05 21:50 UTC, Shadowmech88 commented on code/modules/virus2/effect/wordlists.dm
> +/datum/disease2/proc/initialize_word_lists()
I'll change it if it matters that much.

2017-01-06 12:05 UTC, Shadowmech88 commented
Changes made and conflicts fixed.

2017-01-06 12:39 UTC, PJB3005 approved these changes

2017-01-06 15:06 UTC, merged