Here, fixes locking properly.
d3athrow/vgstation13 pull request #13074
Opened 2016-12-26 13:38 UTC by PJB3005

closes #13065 

Not yet tested my DD server is literally starting as I type this.

2016-12-26 13:38 UTC, sonime commented
So this is 💯?

2016-12-26 13:47 UTC, ghost requested changes
for no reason

2016-12-26 14:08 UTC, 9600bauds commented on code/game/atoms_movable.dm
> +// If this returns TRUE, it means that get_locked with the same parameters will return a list with at least a size of 1.
Why this return inconsistency?

2016-12-26 14:10 UTC, ComicIronic commented on code/game/objects/structures/vehicles/wheelchair.dm
> +	var/list/L = get_locked(is_locking(/datum/locking_category/buckle/chair/vehicle))
Did you mean to do this? It doesn't look like it would work.

2016-12-26 14:12 UTC, 9600bauds commented on code/game/objects/structures/vehicles/wheelchair.dm
> +	var/list/L = get_locked(is_locking(/datum/locking_category/buckle/chair/vehicle))
I think it's supposed to be the weird return I pointed out above

2016-12-26 14:20 UTC, 9600bauds commented on code/modules/hydroponics/spreading/spreading_growth.dm
> +			var/mob/V = get_locked(/datum/locking_category/plantsegment)[1]
Should be find in get_locked maybe

2016-12-26 14:21 UTC, 9600bauds commented on code/game/objects/structures/cage.dm
> +	return locked.Find(checked)
Weird that this isn't a helper proc in itself

2016-12-26 14:32 UTC, PJB3005 commented on code/modules/hydroponics/spreading/spreading_growth.dm
> +			var/mob/V = get_locked(/datum/locking_category/plantsegment)[1]
Doesn't really matter.

2016-12-26 14:32 UTC, PJB3005 commented on code/game/objects/structures/vehicles/wheelchair.dm
> +	var/list/L = get_locked(is_locking(/datum/locking_category/buckle/chair/vehicle))
uh, fuck.

Hey I wasn't done testing it yet.

2016-12-26 14:33 UTC, PJB3005 commented on code/game/objects/structures/cage.dm
> +	return locked.Find(checked)
Actually I can write this more cleanly.

2016-12-26 14:36 UTC, 9600bauds commented on code/modules/hydroponics/spreading/spreading_growth.dm
> +			var/mob/V = get_locked(/datum/locking_category/plantsegment)[1]
Only if nothing in the future ever happens to make it matter

what a gamble!

2016-12-26 14:40 UTC, PJB3005 commented on code/modules/hydroponics/spreading/spreading_growth.dm
> +			var/mob/V = get_locked(/datum/locking_category/plantsegment)[1]
Actually you're right I can think of where this could be useful.

2016-12-26 17:13 UTC, Probe1 commented
seems fine 🤷‍♂️

2016-12-26 18:34 UTC, DrCelt commented
This is absolutely worse in functionality than my PR for several reasons.

2016-12-26 18:37 UTC, Probe1 commented
If you two don't start discussing this _in complete sentences that describe what you are doing and why_ I'm going with PJBs and we're moving forward to fixing the snow map.

2016-12-26 18:38 UTC, DrCelt commented
There are some pros, which definitely should be added to the game
- get locking is better, but that won't conflict with what I have

But in terms of optimisation, you're missing some of the crucial things

- Lists don't get deleted after being unlocked 
- Lists get intialised when they don't need to be
- 

I don't get why you called my fix half assed when this is worse though

Sorry for not making this post instantly, I was typing up my reasoning

2016-12-26 18:47 UTC, ghost requested changes

2016-12-26 18:47 UTC, DrCelt commented on code/game/atoms_movable.dm
> +	locking_init()
Why are you initialising three lists here? You really shouldn't be. You're UNLOCKING an atom, this is your chance to get rid of unused lists, not create them.

2016-12-26 18:47 UTC, DrCelt commented on code/game/atoms_movable.dm
> +	locking_init()
You shouldn't intialised a list here either. If it's just initialised, it's always going to return null

2016-12-26 18:47 UTC, DrCelt commented on code/game/atoms_movable.dm
> +	locking_init()
Again, there should be no init here.

2016-12-26 18:47 UTC, 9600bauds commented
I was going to comment on keeping empty lists around but figured it wasn't all that much of a big deal probably, where are the lists needlessly initialized though?

2016-12-26 18:48 UTC, DrCelt commented
@9600bauds the whole point is to get rid of unnecessary lists, but this PR only goes half way to achieving that

2016-12-26 18:51 UTC, PJB3005 commented
@DrCelt you are retarded. Fuck off.

2016-12-26 18:51 UTC, 9600bauds commented
and here we go again

2016-12-26 18:53 UTC, PJB3005 commented
I can optimize the access of `get_locked` and such, but otherwise Celt's a damn moron.

2016-12-26 19:06 UTC, PJB3005 commented
The point of lazy initialization is to be more efficient on resources. You won't create something that won't be used. Not having a million fucking lists be spawned is good because 99.999% of those wouldn't be used anyways.

If you honestly think that there's a need to delete lists once they run empty you're retarded. Mark my fucking word with this fix in we'll never run out of lists anymore before we have a fucking remake, unless you do something really stupid.

So stop trying to be so smart and calling my fix "inferior" and stop talking about things you clearly don't understand.

And fuck off too.

2016-12-26 19:08 UTC, Intigracy commented
Baddy Paddy versus Belgium, regardless of who wins, we all lose.

2016-12-26 19:10 UTC, 9600bauds commented
What, so we HAVE to skimp on single vars and insignificantly unprofilable syntax, but keeping all these empty lists around is A-OK because "lol we'll probably never have a problem until the remake"

You said you'd do it, go ahead and fuckin' do it. Celt's concerns are entirely legitimate and you know it'd take minutes to fix.

2016-12-26 19:11 UTC, PJB3005 commented
> legitimate

Nice fucking meme.

2016-12-26 19:11 UTC, 9600bauds submitted a review, later dismissed
Said he would do it properly, needs to just do it properly so we can get this over with.

2016-12-26 19:13 UTC, 9600bauds commented
Listen, getting you to write a sensible post was a childbirth. You already devolved back into autistic screeching and I won't go through that effort again.

So just fucking fix it.

2016-12-26 19:14 UTC, PJB3005 commented
I did fucking do it, though?

Celt gets pissy over what's probably less than a hundred lists or so, which is fucking nothing. Me "properly doing it" was never intended to be as holy memory efficient at our shitposter here.

2016-12-26 19:20 UTC, 9600bauds commented
Yes. I don't care what's up between you and Celt. You've ragged people out about stuff even more insignificant before and this time it's actually trivial to fix (and you know how to). No lazy code.

2016-12-26 19:22 UTC, PJB3005 commented
It's also irrelevant to fix.

And if I knew celt isn't doing this because he needs to be a shitter, I maybe would've.

2016-12-26 19:22 UTC, 9600bauds commented
I just told you I don't care what you think of Celt and I just told you to fix it.

2016-12-26 19:23 UTC, 9600bauds commented
Hell you even said above

>I can optimize the access of get_locked

2016-12-26 19:24 UTC, PJB3005 commented
Yes, and I will do that.

2016-12-26 19:25 UTC, PJB3005 commented
The other part celt said is fucking retarded though.

2016-12-26 19:26 UTC, DrCelt commented
Why have a hundred or so lists when you can have none

2016-12-26 19:26 UTC, PJB3005 commented
@DrCelt because fuck you.

Unused RAM is wasted RAM.

2016-12-26 19:26 UTC, 9600bauds commented
aahah what the fuck?

2016-12-26 19:33 UTC, 9600bauds requested changes
very very easy fixes for very very lazy coding, can we please just get all of this over with nice and easy and fast

2016-12-26 19:33 UTC, 9600bauds commented on code/game/atoms_movable.dm
> +	locking_init()
Correct

2016-12-26 19:33 UTC, 9600bauds commented on code/game/atoms_movable.dm
> +	locking_init()
Correct

2016-12-26 19:33 UTC, 9600bauds commented on code/game/atoms_movable.dm
> +	locking_init()
Correct

2016-12-26 19:36 UTC, PJB3005 commented
If you're gonna be Petty over the locking lists, I can be just as Petty over the CPU usage from needing to recreate lists from repeated locks.

2016-12-26 19:43 UTC, 9600bauds commented
We get enough of you being Petty daily, you could have fixed this ten times already, let's not waste everyone's time anymore.

2016-12-26 20:00 UTC, PJB3005 commented
The incorrect init is something I've already said I was gonna fix no matter what.

2016-12-26 20:18 UTC, TheFriggenSawbones commented
pjb has a point, rAM is a good album. While I like Discovery better lets put this into space
https://www.youtube.com/watch?v=XfH3erWacsQ

2016-12-26 21:12 UTC, ComicIronic commented
Lazy loading takes less CPU for creation because you only have lists as needed. It's generally better performance in all areas.

2016-12-26 21:28 UTC, DrCelt commented
@PJB3005 who's being pretty about the locking lists?

2016-12-26 21:29 UTC, PJB3005 commented
@DrCelt you.

2016-12-26 21:29 UTC, DrCelt commented
... How?

2016-12-26 21:37 UTC, Signmark commented
@PJB3005 Chill out dude and take requests to the credit.

2016-12-26 21:40 UTC, 9600bauds commented
👌

2016-12-26 21:40 UTC, 9600bauds approved these changes

2016-12-26 21:42 UTC, 9600bauds commented on code/game/atoms_movable.dm
> +	locking_init()
What happened here?

2016-12-26 21:43 UTC, DrCelt commented
There's still some optimisations to be made here but that doesn't mean this shouldn't be merged. I will change #13065 to include those instead

2016-12-26 21:48 UTC, 9600bauds commented
Well this is still not nulling the lists AND still initializing them in get_lock_cat() so honestly what the fuck.

2016-12-26 21:55 UTC, PJB3005 commented
@9600bauds if you were to read the code, you would see that `get_lock_cat` initializes the category if it doesn't exist yet.

So yes, it's needed.

2016-12-26 22:27 UTC, sonime commented
Bunch of fucking babies that makes Congress look mature.

2016-12-26 22:27 UTC, Probe1 commented
Please stop provoking them.

2016-12-26 22:30 UTC, sonime commented
They're doing a good job of that themselves.

2016-12-26 22:50 UTC, ComicIronic commented
Oh my god it's TermedClepe 2.0

2016-12-26 22:55 UTC, sonime commented
?

2016-12-26 22:57 UTC, Kitfox88 commented
lol

2016-12-26 23:57 UTC, d3athrow commented
bork

2016-12-27 00:06 UTC, sonime commented
@PJB3005 http://puu.sh/t1YYY/ba40a17d39.jpg

2016-12-27 00:07 UTC, sonime commented
@PJB3005 ![Holy word of Pomf](http://puu.sh/t1YYY/ba40a17d39.jpg)

2016-12-27 00:16 UTC, 9600bauds commented
https://www.youtube.com/watch?v=LP0HYIkHs2Q

2016-12-27 00:25 UTC, Senaat1 commented
DEDITATED
WAAAM

2016-12-27 04:29 UTC, DrCelt commented
Hi there @PJB3005 - please edit the PR's description from closes #13065, that PR has content in it other than what you're replacing, thanks

2016-12-27 05:01 UTC, 9600bauds commented
Celt, like 95% of that PR would conflict with this one anyways (and 95% of the comments would be outdated/best forgotten too). It'd be best if you just opened a new one afterwards.

2016-12-27 05:33 UTC, clusterfack commented
Lists aren't the reason we're hitting the ram limit anyway, it's images.

Doesn't the snow map have some sort of shadow image on everything?

2016-12-27 05:54 UTC, 9600bauds commented
I thought we had ran out of ram due to lists back when we went 512x512 for the first time (space turfs had locking lists), and the problem was reappearing because snow turfs had them again

How wrong am I

2016-12-27 07:10 UTC, sonime commented
@clusterfack The shadows are done with matrices IIRC.

2016-12-27 07:22 UTC, DrCelt commented
@clusterfack We ran out of lists; I read the runtimes. We've ran out on lists on the live server before, This is the reason why.
I don't believe shadows has anything to do with it.

2016-12-27 10:57 UTC, merged

2016-12-27 10:57 UTC, Probe1 commented
Just add what you feel it doesn't address on top of it @DrCelt

2016-12-28 00:03 UTC, clusterfack commented
@sonime 
If you can see it ingame, it has an image. From the memory stats pomf has shown me in recent times, those are the causes of crashes from running out of memory.

@9600bauds 
Only atom movables have locking lists, so completely off the mark, and I cant even imagine a world where snow turfs have locking lists

@DrCelt 
If you're talking about a runtime solely about running out of lists, which I would be surprised if such a thing existed, then yes this would help alleviate that. But we've had a LOT more lists than this in the past at several points, since atom movables make up about 250,000 instances, and atoms themselves make up about 2 million and we've had lists on atoms in the past without issue.

If there is such an issue one of you guys probably dun fucked it up by adding some self replicating list somewhere and this would be a bandaid to that.

2016-12-28 04:53 UTC, DrCelt commented
@clusterfack Unfortunately on this issue all I can say is that before a fix similar to this it runtimed due to lack of lists and after it, it didn't. Another fix in the other PR was that of mineral turfs having two lists on them which doesn't help matters

2016-12-28 22:53 UTC, clusterfack commented
@DrCelt Which means you keep bandaiding it without finding the real problem, thats literally all you're saying to me.