Allows traders to strengthen their armor by adding goliath hides just like miners.
d3athrow/vgstation13 pull request #13100
Opened 2016-12-27 12:34 UTC by Probe1

Closes https://github.com/d3athrow/vgstation13/issues/12928

🆑 

 * rscadd: Vox Traders can now use goliath hides to fortify their suits and helmets.

2016-12-27 12:53 UTC, ComicIronic commented
>typelist

Disgusting.

2016-12-27 13:50 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
> +		if(istype(target, /obj/item/clothing/suit/space/rig/mining) || istype(target, /obj/item/clothing/head/helmet/space/rig/mining) || istype(target, /obj/item/clothing/suit/space/plasmaman/miner) || is
We seriously need an is_goli_reinforcable() check or something, this is getting a tad ridiculous

2016-12-27 13:55 UTC, Probe1 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
> +		if(istype(target, /obj/item/clothing/suit/space/rig/mining) || istype(target, /obj/item/clothing/head/helmet/space/rig/mining) || istype(target, /obj/item/clothing/suit/space/plasmaman/miner) || is
``` if(istype(WYCI, /obj/module/work_in_progress/things_you_care_about)) ```

2016-12-27 13:59 UTC, PJB3005 requested changes

2016-12-27 13:59 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
> +		if(istype(target, /obj/item/clothing/suit/space/rig/mining) || istype(target, /obj/item/clothing/head/helmet/space/rig/mining) || istype(target, /obj/item/clothing/suit/space/plasmaman/miner) || is
Nope.

Code quality.

2016-12-27 14:00 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
> +		if(istype(target, /obj/item/clothing/suit/space/rig/mining) || istype(target, /obj/item/clothing/head/helmet/space/rig/mining) || istype(target, /obj/item/clothing/suit/space/plasmaman/miner) || is
Okay, gimme a minute

2016-12-27 14:14 UTC, Probe1 commented
@PJB3005 I'm not doing shit until you clearly explain what is wrong then cite where else in the code it is handled how you would like it to be.

2016-12-27 14:39 UTC, Intigracy commented
He/they mean a clothing proc that returns false by default but returns true for things that can be reinforced via goliath hides.

Istype lists are horrid for maintainability.

2016-12-27 16:25 UTC, PJB3005 approved these changes

2016-12-29 05:11 UTC, Intigracy commented
sure why not

2016-12-29 05:11 UTC, merged