more flavor text fixes round 2
d3athrow/vgstation13 pull request #13126
Opened 2016-12-28 08:02 UTC by Wizardcrying

don't merge quite yet

revival of old PR
fixes some flavor text stuff and also triggers celt/fixes two bugs related to the KEEPER AI module (which shouldn't be tangible but is on box centcomm anyway whyyy)

2016-12-28 11:03 UTC, Skullyton commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A civilian space pod with a gold body, must have cost somebody a pretty penny"
>Removing fun

2016-12-28 11:03 UTC, Skullyton commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "You attempt to enter \the [src.name], but [M.name] pulls you back!")
>Removing fun

2016-12-28 11:04 UTC, Skullyton commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "[src.occupant] has already entered the pod.")
>Removing fun

2016-12-28 11:05 UTC, Skullyton commented on code/game/objects/items/weapons/cigs_lighters.dm
> +	desc = "A large roll of tobacco and chemicals."
>Removing fun

2016-12-28 11:06 UTC, Skullyton commented on code/modules/admin/admin.dm
> +			<A href='?src=\ref[src];secretsfun=eagles'>Egalitarian Station Mode (all-access for everyone)</A><BR>
It removes door access, not gives all access

2016-12-28 11:07 UTC, Skullyton commented on code/modules/clothing/shoes/magboots.dm
> -	desc = "Reverse-engineered magnetic boots that have a heavy magnetic pull. Property of Gorlex Marauders."
>Removing [LORE]

2016-12-28 11:08 UTC, Skullyton commented on code/modules/mob/living/simple_animal/friendly/crab.dm
> +	desc = "A crab with a white shell."
>Removing fun

2016-12-28 11:08 UTC, Skullyton commented on code/modules/reagents/reagent_dispenser.dm
> +	desc = "A massive keg containing beer."
May not necessarily contain beer

2016-12-28 15:51 UTC, BestName commented on code/datums/uplink_item.dm
> +	desc = "A traditional handgun which fires .357 rounds. Has 7 chambers. Can down an unarmored target with two shots."
![asd](https://cloud.githubusercontent.com/assets/3892856/21525480/36929084-cd26-11e6-984d-04abca1ae27d.jpg)

2016-12-28 15:53 UTC, BestName commented on code/game/gamemodes/cult/cult_items.dm
> +	name = "cult armor"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525497/526360b8-cd26-11e6-8e11-b9da95bdc668.jpg)

2016-12-28 15:53 UTC, BestName commented on code/game/gamemodes/cult/cult_items.dm
> +	desc = "A bulky suit of armor covered in spikes. It looks space proof."
![asd](https://cloud.githubusercontent.com/assets/3892856/21525520/85759732-cd26-11e6-97f9-2ecd925c4bd9.jpg)

2016-12-28 15:53 UTC, BestName commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
![asd](https://cloud.githubusercontent.com/assets/3892856/21525528/8dfca33c-cd26-11e6-8921-a30d36c69a21.jpg)

2016-12-28 15:55 UTC, BestName commented on code/game/objects/structures/crates_lockers/closets/syndicate.dm
> +	name = "vox armory closet"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:55 UTC, BestName commented on code/game/objects/structures/crates_lockers/closets/syndicate.dm
> +	name = "armory closet"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:55 UTC, BestName commented on code/game/objects/structures/crates_lockers/closets/syndicate.dm
> +	name = "vox armory closet"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:57 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +// Vox space gear (vaccuum suit, low pressure armor)
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:58 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A huge, armored, pressurized suit, designed for distinctly nonhuman proportions."
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:58 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +	name = "alien carapace armor"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:58 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "An armored, segmented carapace with glowing purple lights. It looks pretty run-down."
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:58 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +	name = "alien armor"
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 15:58 UTC, BestName commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A pair of heavy, jagged armored foot pieces."
![asd](https://cloud.githubusercontent.com/assets/3892856/21525559/c0d744ba-cd26-11e6-80b9-63b3732ef4c5.jpg)

2016-12-28 16:02 UTC, BestName approved these changes
Patriotic/10
God bless America.
![bald-eagle-crying](https://cloud.githubusercontent.com/assets/3892856/21525746/ecdde842-cd27-11e6-8046-b9d32737ea7c.png)

2016-12-28 16:19 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "You attempt to enter \the [src.name], but [M.name] pulls you back!")
`\the [src.name]` doesn't work.

2016-12-28 16:26 UTC, DrCelt commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A pair of heavy, jagged armored foot pieces."
![](http://i.dailymail.co.uk/i/pix/2014/04/08/article-0-1978CBC800000578-568_634x538.jpg)

2016-12-28 16:26 UTC, DrCelt commented on code/modules/clothing/spacesuits/alien.dm
> +	name = "alien armor"
![](http://i.dailymail.co.uk/i/pix/2014/04/08/article-0-1978CBC800000578-568_634x538.jpg)

2016-12-28 16:26 UTC, DrCelt commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "An armored, segmented carapace with glowing purple lights. It looks pretty run-down."
![](http://i.dailymail.co.uk/i/pix/2014/04/08/article-0-1978CBC800000578-568_634x538.jpg)

2016-12-28 16:26 UTC, DrCelt commented on code/modules/clothing/spacesuits/alien.dm
> +	name = "alien carapace armor"
![](http://i.dailymail.co.uk/i/pix/2014/04/08/article-0-1978CBC800000578-568_634x538.jpg)

2016-12-28 16:26 UTC, DrCelt commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A huge, armored, pressurized suit, designed for distinctly nonhuman proportions."
![](http://i.dailymail.co.uk/i/pix/2014/04/08/article-0-1978CBC800000578-568_634x538.jpg)

2016-12-28 16:27 UTC, DrCelt commented
>make a grammar PR

>misspell words 

Shaking my head to be honest

2016-12-28 16:32 UTC, Intigracy submitted a review, later dismissed

2016-12-28 16:32 UTC, Intigracy commented on code/modules/admin/admin.dm
> +			<A href='?src=\ref[src];secretsfun=eagles'>Egalitarian Station Mode (all-access for everyone)</A><BR>
All door access but command and sec iirc

2016-12-28 16:32 UTC, Intigracy commented on code/modules/clothing/shoes/magboots.dm
> -	desc = "Reverse-engineered magnetic boots that have a heavy magnetic pull. Property of Gorlex Marauders."
At least describe it as being a tag on the tongue.

2016-12-28 16:32 UTC, Intigracy commented on code/modules/reagents/reagent_dispenser.dm
> +	desc = "A massive keg containing beer."
labeled as or something

2016-12-28 16:45 UTC, Skullyton commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
It's even commented out, the heck is this?

2016-12-28 16:47 UTC, BestName commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
The good ol' find and replace.

2016-12-28 16:49 UTC, Skullyton commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A pair of heavy, jagged armored foot pieces."
Damn it celt, stop trying to force the irish to be relevant

2016-12-28 20:08 UTC, Wizardcrying commented
I wasn't lying when I wrote

>triggers celt

Now I can make that

>triggers celt AND bestname

2016-12-28 20:12 UTC, Wizardcrying commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
I did it just to piss you off.

2016-12-28 20:42 UTC, Wizardcrying commented on code/modules/admin/admin.dm
> +			<A href='?src=\ref[src];secretsfun=eagles'>Egalitarian Station Mode (all-access for everyone)</A><BR>
thanks

2016-12-28 21:42 UTC, Exxion requested changes

2016-12-28 21:42 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "You attempt to enter \the [src.name], but [M.name] pulls you back!")
I was being serious. It should be `\the [src]` and `\the [M]`

2016-12-28 21:42 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +	visible_message("<span class='notice'>[usr] starts to climb into [src.name].</span>")
`\the [src]`

2016-12-28 21:42 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "<span class='notice'><B>\The [src.name] is already occupied!</B></span>")
Remove `.name`

2016-12-28 21:51 UTC, Wizardcrying commented
god damn it @Skullyton you commented on the removal and not the addition

2016-12-29 00:31 UTC, BestName commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
![1444689196582](https://cloud.githubusercontent.com/assets/3892856/21534382/e816d250-cd6e-11e6-9649-cd8db0886c1b.png)

2016-12-29 01:06 UTC, Skullyton commented on code/modules/clothing/shoes/magboots.dm
> -	desc = "Reverse-engineered magnetic boots that have a heavy magnetic pull. Property of Gorlex Marauders."
Lore has been restored

2016-12-29 01:42 UTC, Wizardcrying commented on code/game/gamemodes/cult/talisman.dm
> +//<A href='?src=\ref[src];rune=armor'>Sa tatha najin</A> - Allows you to summon armored robes and an unholy blade<BR> //Kept for reference
If I did use find & replace, then it would have broken a lot of things, such as maps and references to `.dmi`s.

2016-12-29 02:13 UTC, ghost requested changes
It's spelled armour tbh

2016-12-29 06:05 UTC, Wizardcrying commented
@Exxion i fixed em

2016-12-29 06:17 UTC, 9600bauds commented
why are you REMOVING flavor
god what the fuck is this whole PR

2016-12-29 06:18 UTC, 9600bauds commented on code/game/objects/items/devices/flash.dm
> +	desc = "Used for blinding and incapacitation. Can be directed at an individual or used to disorient an area."
whyyy

2016-12-29 06:18 UTC, 9600bauds commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	desc = "A closet containing medical supplies."
whyy

2016-12-29 06:20 UTC, 9600bauds commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			desc = "A space pod painted black."
this is a case of a description that might as well not be there

why are you replacing descriptions with something that might as well not be there

2016-12-29 06:21 UTC, 9600bauds commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			to_chat(usr, "You're too busy getting the life sucked out of you by [M.name]!")
should this really be using .name, and shouldn't it be using \the?

2016-12-29 06:23 UTC, 9600bauds commented on code/game/gamemodes/cult/cult_items.dm
> -	desc = "A bulky suit of armour, bristling with spikes. It looks space proof."
bristling is such a good adjective and I can't fathom why are you removing it

2016-12-29 06:35 UTC, Wizardcrying commented on code/game/objects/items/devices/flash.dm
> +	desc = "Used for blinding and incapacitation. Can be directed at an individual or used to disorient an area."
I meant the in-hand interaction?

2016-12-29 06:37 UTC, Wizardcrying commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	desc = "A closet containing medical supplies."
Explain?

2016-12-29 06:39 UTC, Wizardcrying commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +			desc = "A space pod painted black."
I don't know how having no insignias is worth inclusion. I'll make the text more descriptive, though.

2016-12-29 06:43 UTC, Wizardcrying commented on code/game/gamemodes/cult/cult_items.dm
> -	desc = "A bulky suit of armour, bristling with spikes. It looks space proof."
agreed, fixed

2016-12-29 18:24 UTC, 9600bauds commented
God dammit and this is part 2?

2016-12-29 20:25 UTC, DrCelt commented
Every single time I look at this PR The plus to minus ratio goes down and down and down

2016-12-29 21:42 UTC, Wizardcrying commented
stop shitposting and tell me what's actually wrong

2016-12-29 22:01 UTC, Exxion requested changes
Most of these are opinion, so feel free to ignore them if most people disagree

2016-12-29 22:01 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A civilian space pod with a gold body, must have cost somebody a pretty penny"
I'd personally say keep the original wording and just fix the comma splice and missing period.

2016-12-29 22:01 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	desc = "An alarm used to control the area's atmospherics systems."
Put this up in the object definition rather than this proc. The name has to be here because it involves a variable, but this is  always the same.

2016-12-29 22:01 UTC, Exxion commented on code/game/objects/items/devices/flash.dm
> +	desc = "Used for blinding and incapacitation. Can be directed at an individual or used to disorient an area."
I suggest you leave this iconic description how it was

2016-12-29 22:01 UTC, Exxion commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	desc = "A closet containing medical supplies."
Maybe this one's iconic too? I don't play medbay

2016-12-29 22:01 UTC, Exxion commented on code/modules/admin/admin.dm
> +			<A href='?src=\ref[src];secretsfun=eagles'>Egalitarian Station Mode (removed access on doors except for Command and Security)</A><BR>
Change it to "removes" to keep consistency with other verb descriptions.

2016-12-29 22:01 UTC, Exxion commented on code/modules/admin/admin.dm
> +			<A href='?src=\ref[src];secretsfun=onlyone'>Highlander Mode (There can be only one!)</A><BR>
Technically this button is also used for Wizard Wars, but whatever

2016-12-29 22:01 UTC, Exxion commented on code/modules/admin/admin.dm
>  			<A href='?src=\ref[src];secretsfun=bombernodestroy'>Make Bomberman Bombs harmless to the environnement(default)</A><BR>
While you're here, add a space to this one, too

2016-12-29 22:01 UTC, Exxion commented on code/modules/mob/living/simple_animal/hostile/faithless.dm
> +	desc = "A being of shadow. It posesses a menacing gaze and a tortured voice."
OK this one was probably iconic too, but to be fair yours is better in this case

2016-12-29 22:05 UTC, Wizardcrying commented on code/game/machinery/alarm.dm
> +	desc = "An alarm used to control the area's atmospherics systems."
Whoops, nice catch

2016-12-29 22:11 UTC, Wizardcrying commented on code/modules/admin/admin.dm
>  			<A href='?src=\ref[src];secretsfun=bombernodestroy'>Make Bomberman Bombs harmless to the environnement(default)</A><BR>
Didn't notice the `environement` either. Thanks.

2016-12-29 22:12 UTC, Exxion commented on code/modules/admin/admin.dm
>  			<A href='?src=\ref[src];secretsfun=bombernodestroy'>Make Bomberman Bombs harmless to the environnement(default)</A><BR>
I didn't either, somehow

2016-12-29 22:59 UTC, DrCelt commented
>+2/-9

>Not controversial

2016-12-29 23:00 UTC, DrCelt commented
>I did it just to piss Celt off

>Please give me feedback of why you don't like it Celt 

🤔

2016-12-29 23:00 UTC, Exxion commented
He changed most of the things people were downvoting about
Probably
You can't really tell what someone's upset about if they only vote

2016-12-29 23:04 UTC, Wizardcrying commented
@DrCelt you said that my change of colour to color in the last pr was non-atomic

2016-12-29 23:12 UTC, Exxion approved these changes

2016-12-29 23:31 UTC, 9600bauds commented
hi yes i believe there is plenty of controversy here

2016-12-29 23:34 UTC, 9600bauds commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	desc = "A closet containing medical supplies."
This is just downgrading a snarky description (for something that needs no description) into a useless and bland description (for something that needs no description)

2016-12-29 23:35 UTC, 9600bauds commented
This has actually improved since the last time I looked at it so I'm removing my :-1:

2016-12-30 00:29 UTC, Wizardcrying commented
what fucking votes

2016-12-30 00:41 UTC, PJB3005 commented
I'm against removing non-descriptive descriptions on objects that can go without it.

2016-12-30 00:42 UTC, PJB3005 commented on code/game/objects/items/weapons/shields.dm
> +	desc = "A device that completely hides a user."
Eeeh.

2016-12-30 00:43 UTC, PJB3005 commented on code/modules/clothing/spacesuits/alien.dm
> +	desc = "A pair of heavy, jagged armored foot pieces."
eeeh

2016-12-30 00:43 UTC, Wizardcrying commented on code/game/objects/items/weapons/shields.dm
> +	desc = "A device that completely hides a user."
"Use this to become invisible to the human eye"?

2016-12-30 00:43 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/hostile/faithless.dm
> +	desc = "A being of shadow. It posesses a menacing gaze and a tortured voice."
Yeah eeeh on this one.

2016-12-30 00:44 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A lightweight, fast firing gun. Uses .45 rounds."
eeeeh

2016-12-30 00:44 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A lightweight, fast firing gun. Uses 12mm rounds. Has a 'Scarborough Arms - Per falcis, per pravitas' buttstamp."
eeeeeh

2016-12-30 00:51 UTC, Shadowmech88 commented
>fixes some flavor text stuff

That's a funny way to say "unnecessarily makes a bunch of descriptions clinical and boring."

2016-12-30 00:54 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "A lightweight, fast firing gun. Uses 12mm rounds. Has a 'Scarborough Arms - Per falcis, per pravitas' buttstamp."
Also if you're gonna revert this, maybe consider making the `REALLY` into `<b>really</b>` for fancy styling.

2016-12-30 00:55 UTC, Wizardcrying commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	desc = "A closet containing medical supplies."
@9600bauds I see what these were for now. Thanks.

2016-12-30 00:57 UTC, Wizardcrying commented
@Shadowmech88 Bauds' recent comment explained why these descriptions exist. Thanks @9600bauds.

2016-12-30 00:59 UTC, 9600bauds commented
Again sorry for the original dumb "whyy" comment, I woke up annoyed at things entirely unrelated to spess. Just by making a proper comment we are already all communicating better.

2016-12-30 01:29 UTC, Shadowmech88 commented on code/defines/obj/weapon.dm
> -	desc = "The remnants of a being between the world of the dead and that of the living. Spooky."
Why remove this?

2016-12-30 01:33 UTC, Wizardcrying commented on code/defines/obj/weapon.dm
> -	desc = "The remnants of a being between the world of the dead and that of the living. Spooky."
That was a change I made. It was previously just `desc = "spooky"`. I suppose this could be a useful description.

2016-12-30 01:38 UTC, Shadowmech88 commented on code/defines/obj/weapon.dm
> -	desc = "The remnants of a being between the world of the dead and that of the living. Spooky."
If it didn't have it originally, then I don't mind. Whatever you feel like.

2016-12-30 01:39 UTC, Wizardcrying commented on code/defines/obj/weapon.dm
> -	desc = "The remnants of a being between the world of the dead and that of the living. Spooky."
It is too wordy, for one.

2016-12-30 01:45 UTC, Wizardcrying commented
That's it for this PR.

2016-12-30 01:46 UTC, Wizardcrying commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A civilian space pod with a gold body, must have cost somebody a pretty penny"
Fixed.

2016-12-30 02:04 UTC, 9600bauds commented
Everyone satisfied now?

2016-12-30 02:08 UTC, Shadowmech88 commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A dark grey space pod brandishing the Nanotrasen Military insignia"
"Military" may have been correct here, in the same vein as "United States Armed Forces."

2016-12-30 02:10 UTC, Wizardcrying commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A dark grey space pod brandishing the Nanotrasen Military insignia"
The capitalization seemed off, since there's been no mention of the "Nanotrasen Military" from what I've seen.

2016-12-30 02:11 UTC, Wizardcrying commented
@9600bauds The only downvoters who have commented on this are Celt and Shadowmech, so probably.

2016-12-30 02:31 UTC, Aurantiaco commented
We must delete fun at once.

2016-12-30 02:36 UTC, Intigracy commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A dark grey space pod brandishing the Nanotrasen Military insignia"
If it's THE Nanotrasen Military insignia, I think that's the name of it.

2016-12-30 02:36 UTC, Intigracy commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A dark grey space pod brandishing the Nanotrasen Military insignia"
Or it's just laziness and not describing the insignia correctly.

2016-12-30 02:39 UTC, Wizardcrying commented
@Aurantiaco Why do you propose this and how do you propose going about it?

2016-12-30 02:51 UTC, Aurantiaco commented
I say that we remove anything that causes enjoyment among players with swiftness. Fun is a toxic, horrible thing that has no reason to exist in space. My family was murdered by fun. Literally. They were playing hopscotch in the street, talking about how fun it was, when a drunk driver hit them with a car. Fun killed them.

Also this is just hyperbole I have few problems with the actual PR.

2016-12-30 02:55 UTC, Wizardcrying commented
@Aurantiaco That's pretty sad. I'll get to work on removing fun ASAP. 

What are your specific issues?

2016-12-30 03:15 UTC, Wizardcrying commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> -			desc = "A dark grey space pod brandishing the Nanotrasen Military insignia"
I've never heard "Nanotrasen Military" used before, so I think it's the latter. "Nanotrasen Enforcement and Protection Division" or something shorter, perhaps?

2016-12-30 03:20 UTC, Aurantiaco commented
People have too much fun with

combat

being an antag

playing space

we must delete the game at once.

2016-12-30 03:22 UTC, Wizardcrying commented
@Aurantiaco what about the PR?

2016-12-30 03:40 UTC, Aurantiaco commented
nah this is fine merge it

2016-12-30 03:48 UTC, Wizardcrying commented
ok

2016-12-30 20:51 UTC, PJB3005 approved these changes

2016-12-30 21:14 UTC, DrCelt commented
Still mispelling armour deliberately

2016-12-31 12:55 UTC, ultraplen commented
>deleting fun flavour texts in favour of boring ones

delete this

2016-12-31 18:02 UTC, 9600bauds commented
Shame about part 1 not getting the FUN intervention

2016-12-31 18:02 UTC, merged