Adds sanity to Xenoarch's replicator artifact
d3athrow/vgstation13 pull request #13186
Opened 2016-12-30 23:04 UTC by jknpj

Fucking faggot ghosts man i swear to god

Closes #7195

2016-12-30 23:07 UTC, ComicIronic commented on code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
> +	to_chat(user, "<span class='rose'>Your ghostly hand goes right through!</span>")
Indent.

2016-12-30 23:07 UTC, ComicIronic commented on code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
> +			return
TOO MUCH INDENT

2016-12-30 23:07 UTC, ComicIronic commented on code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
> +			return
Too much indent.

2016-12-30 23:08 UTC, ComicIronic requested changes
Bad

2016-12-30 23:09 UTC, Probe1 commented
We intentionally did not add sanity to it.

2016-12-30 23:23 UTC, Sprok0 commented
This was the best part of that artifact what are you doing

2016-12-30 23:28 UTC, Skullyton commented
Keep it xenoarchy by it having a chance to not care about ghost hands

2016-12-30 23:38 UTC, Skullyton commented
Or hell, if ghosts are really bothering you, do it the IC way and get a chaplain to bless that shit with holy water

2016-12-31 00:51 UTC, jknpj commented
@Sprok0 & @Probe1
I know it is the iconic part of it but it is way too much exploitable and allowing ghosts to summon hostile mobs is just bananas

@Skullyton 
>deal with it ICly
Kinda hard when there's about fifty mimics and dozen viscerators around it because ghosts

2016-12-31 00:53 UTC, Sprok0 commented
At least make it hit its own buttons sometimes if you're that set on blocking ghosts from it

2016-12-31 00:53 UTC, Shadowmech88 commented
If the volume of mobs is a problem, add a cooldown to the artifact.
Removing the ability for ghosts to use it is dumb. Chaplains exist, the problem could be solved IC if people in the round cared enough.

2016-12-31 01:02 UTC, 9600bauds commented
EVERYTHING could be solved IC via chaplain
That's not really a compelling argument to let ghosts fuck with important things

2016-12-31 01:04 UTC, Shadowmech88 commented
Alright but in this case letting ghosts fuck with it was explicitly left in as a feature.

2016-12-31 01:06 UTC, ComicIronic commented
Does `incapacitated()` stop ghosts?

2016-12-31 01:10 UTC, 9600bauds commented
ye

2016-12-31 01:12 UTC, jknpj commented
Yes but i kinda wanted a ghostly flavor text so i ended `isobserver` for them and `incapacitated()` for the living

2016-12-31 01:18 UTC, ComicIronic approved these changes

2017-01-05 19:02 UTC, jknpj commented
Will do something about this without removing the FEAAAATUUUUREEEEEEEEE

2017-01-05 19:02 UTC, closed without merging