Adds *scream and *vent to Cyborg's emotes
d3athrow/vgstation13 pull request #13213
Opened 2017-01-01 21:34 UTC by jknpj

What am i doing with my life

Adds scream and vent (silicon fart) emotes. Allow borgs to literally vent their frustration in a colorful way and a whole new meaning to "gas the vox".

Closes #11761

:cl:
 * rscadd: Adds *scream and *vent(robo fart) to Cyborgs

2017-01-01 21:40 UTC, PJB3005 requested changes

2017-01-01 21:40 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +				for(var/mob/living/M in view(0))
`in loc` is probably cleaner.

2017-01-01 21:40 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +								src.attack_log += text("\[[time_stamp()]\] <font color='orange'>[src] vented oxygen in [M]'s face.</font>")
There's a proc for adding to attack logs, see https://github.com/d3athrow/vgstation13/pull/12949/files

2017-01-01 21:40 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +					if(M != src && M.loc == src.loc)
Doesn't even check whether the mob is actually lying on the floor! Are these vents head-level?

2017-01-01 21:51 UTC, Ephx1 commented
What does the scream sound like?

2017-01-01 21:52 UTC, PJB3005 commented
https://raw.githubusercontent.com/jknpj/qwilfish-on-head-retard/8a785eff4570ef4eef046a0e67037bd93b02f0d4/sound/machines/scream.ogg

Like that

2017-01-01 21:53 UTC, Ephx1 commented
Well I'm all for more borg sounds but ripping out R2-D2's screech ain't something I want

2017-01-01 21:55 UTC, SkowronX commented
Audible screams should never be manually done.

2017-01-01 22:08 UTC, jknpj commented
@Ephx1 
I'm not actually very fond of using it, too. But sinde we already have R2D2 serviceborg sprite and the ED209 complete with ripped voice and roar i just ended usint it for not having anything else that sounded "robotic" enough.

If anyone got a better sound i'm all in for scraping the R2D2 one

2017-01-01 22:10 UTC, Ephx1 commented
We could just
y'know
not have it instead?

2017-01-01 22:11 UTC, yclatious commented
Why are we adding shitty voice emotes to borgs? Especially just a fart and scream one, both of which garbage from TTT tier servers?

Fucks sake, why? Do we need borgs screeching ingame? Do we need more farting? Did anyone even want these?

2017-01-01 22:54 UTC, PJB3005 requested changes

2017-01-01 22:54 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +					if(M != src && M.loc == src.loc && M.lying || M.resting)
Operator precedence is gonna screw you over here, move the `||` into parentheses.

2017-01-02 00:30 UTC, PJB3005 requested changes

2017-01-02 00:30 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +						if(istype(M, /mob/living/carbon/human/vox))
Make this `isvox()`

2017-01-02 00:30 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/emote.dm
> +					if(M != src && M.loc == src.loc && (M.lying || M.resting))
Since you're looping through Loc now, checking whether the Loc is the same as src is redundant.

2017-01-02 00:30 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/lastvent = 0 //Vent cooldown.
Maybe mention this is for the emote?

2017-01-02 01:22 UTC, Skullyton commented
Was hoping the scream'd be this https://youtu.be/Hv6RbEOlqRo?t=14s

2017-01-02 01:23 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/emote.dm
> +								add_logs(src, M, "vented", admin = M.ckey ? TRUE : FALSE)//Only add this to the server logs if they're controlled by a player.
>Literally fartgassing the vox

What the fuck.

2017-01-02 01:43 UTC, jknpj commented
All right i just need to find a non-terrible way to do the TTS thing

2017-01-02 05:13 UTC, Aurantiaco commented
Make it the moonbase alpha tts and it will be gucci.

2017-01-02 10:57 UTC, Kitfox88 commented
![20120227-robotthatscreams](https://cloud.githubusercontent.com/assets/16981475/21588024/64eb94ca-d0b0-11e6-8dc2-a574c2b46ad9.png)

2017-01-02 19:51 UTC, Shadowmech88 commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> flaps it's utility arms as through they were wings."
>as through

2017-01-02 20:20 UTC, AI-is-rogue commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> flaps it's utility arms as through they were wings."
>it's

2017-01-02 20:58 UTC, Exxion requested changes

2017-01-02 20:58 UTC, Exxion commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> clangs it's utility claws together in a crude simulation of applause."
Should be "its"

2017-01-02 20:58 UTC, Exxion commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> flaps it's utility arms as through they were wings."
"its"
"though"

2017-01-02 20:58 UTC, Exxion commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> flaps it's utility arms ANGRILY!"
"its"

2017-01-03 02:20 UTC, Shadowmech88 commented on code/modules/mob/living/silicon/robot/emote.dm
> +				message = "<B>[src]</B> flaps its utility arms as through they were wings."
>as through

2017-01-03 03:43 UTC, Chronakai commented
I was actually half hoping for the monotone scream from FNAF2, when you're in the Freddy suit.
If there's even a source for that soundclip.

2017-01-03 17:34 UTC, jknpj commented
I still don't like how some of them sound ingame, i'll try to work on them later today :man_shrugging:

2017-01-05 19:03 UTC, NigglyWiggly commented
>Borgs releasing gas in people's faces

Is this fucking farting for borgs

2017-01-05 19:04 UTC, Exxion commented
Yes.
Congrats on just realizing that.

2017-01-05 19:54 UTC, AI-Is-Rogue commented
The vent emote seems a bit descriptive, and the way it's described makes me think "fetish fuel".

2017-01-05 22:05 UTC, jknpj commented
@NigglyWiggly It is literally the old commented silicon *fart reworked to be more like robotic simulation of, well, a fart. Racism added as bonus.

@AI-is-rogue This is literally what it is supposed to look like.:

![1471312429719](https://cloud.githubusercontent.com/assets/17928298/21699303/d5e3fbce-d379-11e6-912d-7ae7bcbd6497.jpg)

2017-01-05 22:19 UTC, AI-is-rogue commented
@jknpj I figured it would be a robot farting.

2017-01-05 23:43 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/emote.dm
> +						if(isvox(M))
But, why specifically vox?

Why not gas the plasmamen as well?

2017-01-06 03:20 UTC, gbasood commented on code/modules/mob/living/silicon/robot/emote.dm
> +						if(isvox(M))
Not to mention, how is it gassing vox *through internals*

2017-01-06 03:53 UTC, Ephx1 commented
I like how you're trying to pass off farting as something cool.

2017-01-06 12:28 UTC, jknpj commented on code/modules/mob/living/silicon/robot/emote.dm
> +						if(isvox(M))
@Skullyton you mean making plasmaman ignite even in non-o2 atmos?

@gbasood Is there a way to have internals without having a mask on?

2017-01-06 12:33 UTC, jknpj commented
@Ephx1 Hey, it worked with Elvis!

2017-01-06 12:43 UTC, PJB3005 approved these changes

2017-01-06 15:20 UTC, Exxion approved these changes

2017-01-07 02:13 UTC, ComicIronic commented on code/modules/mob/living/silicon/robot/emote.dm
> +				for (var/mob/A in view(null, null))
`view(null, null)`?

2017-01-07 20:00 UTC, gbasood commented on code/modules/mob/living/silicon/robot/emote.dm
> +						if(isvox(M))
@jknpj misread the if() check below this line comment

2017-01-09 23:40 UTC, jknpj commented on code/modules/mob/living/silicon/robot/emote.dm
> +				for (var/mob/A in view(null, null))
It checks if your *[emote]-[target] is in view using some kind of oldcode sorcery in the beginning of the file that just works

![something](https://cloud.githubusercontent.com/assets/17928298/21788096/9cb107cc-d6ab-11e6-8ab7-466ae096272f.png)

2017-01-10 00:33 UTC, Exxion commented on code/modules/mob/living/silicon/robot/emote.dm
> +				for (var/mob/A in view(null, null))
Might it just be explicitly calling `view()` with the default arguments?

2017-01-10 00:39 UTC, ComicIronic commented on code/modules/mob/living/silicon/robot/emote.dm
> +				for (var/mob/A in view(null, null))
Oh, so it does.

2017-01-12 20:59 UTC, merged

2017-01-12 21:14 UTC, Ephx1 commented
_oh, great_

2017-01-12 22:31 UTC, AutismSpider commented
Why did this get in?

2017-01-12 23:00 UTC, SkowronX commented
Because you *aflap yourself at night.

2017-01-13 00:37 UTC, 9600bauds commented
Probe, what the FUCK?

2017-01-13 00:40 UTC, Probe1 commented
I thought it was ahead.

I'm still not sure why everyone cares so strongly about this.

2017-01-13 00:41 UTC, PJB3005 commented
I thought this was a legit meme PR.

2017-01-13 20:35 UTC, clusterfack commented
Hahaha WHAT

2017-01-13 20:53 UTC, Probe1 commented
We should probably add it back in for malf.