Light Cycles
d3athrow/vgstation13 pull request #13231
Opened 2017-01-03 01:13 UTC by Shadowmech88

http://puu.sh/t9e6B/c8ff166839.webm

Adds light rods.
Adds light cycles.

Light rods are assigned a random color when they spawn, or can be given a custom color as an argument to their `New()`. When used, a light rod manifests a light cycle around the user. When used again, the light cycle disappears.
Light cycles move forward constantly while they have an occupant. The occupant can change the light cycle's direction, but not directly influence its movement. When a light cycle bumps into any dense object except a mob, the occupant is gibbed and the light cycle disappears. Light cycles leave a trail of light ribbon objects as they move. These can be removed by attacking them with any object, as long as you're not riding a light cycle.

I figure these could be a neat tool for adminbus-games in the same vein as the Bomberman equipment.

2017-01-03 01:14 UTC, Probe1 commented
siiiick

2017-01-03 02:07 UTC, Shadowmech88 commented
What do you mean? Like when they crash?
They just get qdel()'d.
The rider drops the light rod they were using so it can be picked up and used to summon the cycle again.

2017-01-03 02:25 UTC, Intigracy commented
He means the light barriers.

2017-01-03 02:28 UTC, Shadowmech88 commented
Oh, you just smack the barrier with something to make it disappear from that tile.

2017-01-03 02:32 UTC, 9600bauds commented
Maybe hitting a color of barrier with that colors' corresponding light rod deletes all light barriers of that color?

2017-01-03 02:34 UTC, 9600bauds commented on code/game/objects/structures/vehicles/lightcycle.dm
> +		M.stop_pulling()
I believe this is implicit for Knockdown() and not needed but whatever

2017-01-03 02:35 UTC, 9600bauds commented on code/game/objects/structures/vehicles/lightcycle.dm
> +		M.lying = 1
This is DEFINITELY implicit for Knockdown() and not needed

2017-01-03 02:36 UTC, Shadowmech88 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +		M.stop_pulling()
I took it from the code executed when a MULE runs over a mob, I don't know how old it is.

2017-01-03 02:36 UTC, 9600bauds commented on code/game/objects/structures/vehicles/lightcycle.dm
> +		M.stop_pulling()
hahaha oh god

2017-01-03 02:38 UTC, Shadowmech88 commented
I suppose I could add that, but why? There's no delay on attacking the barriers, so clearing them out isn't much of a task.

2017-01-03 02:39 UTC, 9600bauds commented
Oh there's no delay, neat
I figured to quickly clear the board during adminbus

2017-01-03 02:42 UTC, Shadowmech88 commented
I'd have to keep a global list of lists of all the light walls of each color, right?
Or would it be better to just have each light wall check for adjacent ones of the same color and delete them when it's deleted, so that the effect propagates outwards along the wall?

2017-01-03 02:43 UTC, Shadowmech88 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +		M.stop_pulling()
Think I should go ahead and remove it?

2017-01-03 02:47 UTC, 9600bauds commented
Well you could just keep the list in the rod itself, if you say cleaning these up isn't a hassle though it's okay

2017-01-03 02:49 UTC, Shadowmech88 commented
I was thinking of the hassle for other players after lightcycles ride through the station, not for the admins in clearing the game board. Something to clean it up all at once would probably be good.

2017-01-03 02:50 UTC, Shadowmech88 commented
I'll make it a proc that admins can call manually so riders can't use their rods to instantly reclaim a bunch of space for themselves.

2017-01-03 02:54 UTC, 9600bauds commented
If these cycles are meant to be used inside the station at all, consider giving them PASSDOOR so they can at least move through the hallways

2017-01-03 06:30 UTC, Aurx commented
Admins already have tools to mass-delete objs, and it'd be easy to use SDQL to wipe out all lightribbons of a certain color.  I'm not sure how useful another mass-delete proc for just lightribbons would be.

2017-01-03 06:32 UTC, Exxion commented
There's a goddamn delete all of type button in VV, if memory serves

2017-01-03 06:53 UTC, Nienhaus commented
This is something I've wanted in SS13 for the longest time. I am damn impressed.

2017-01-03 09:31 UTC, Aurx commented
A proc that has to be manually called via debug tools is going to be forgotten by or never known to admins.

2017-01-03 09:34 UTC, Shadowmech88 commented
The ones who don't know can still run around the arena swinging a crowbar to take the light ribbons down.

Do you have a better suggestion for accessing the deletion proc?

2017-01-03 09:47 UTC, Aurx commented
Would you be able to make it so that an adminghost clicking a lightribbon opens a  "Delete this ribbon Y/N?" prompt and nukes it if Y?  I think that'd be the most elegant solution because it wouldn't need extra verbs.  Fuck if I know UI practices though, the codermins would likely have the best input.

2017-01-03 12:13 UTC, PJB3005 requested changes

2017-01-03 12:13 UTC, PJB3005 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	l_color = "[rgb(rgb_list[1],rgb_list[2],rgb_list[3])]"
`rgb` already returns a string, so you don't need the wrapping string.

2017-01-03 12:13 UTC, PJB3005 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	if(!istype(user, /mob/living/carbon/human))
`ishuman`

2017-01-03 12:13 UTC, PJB3005 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	var/obj/structure/bed/chair/vehicle/lightcycle/summoned_cycle = null
Any reason you can't just replace any code checking `cycle_active` with whether or not `summoned_cycle` is null or not?

2017-01-03 12:13 UTC, PJB3005 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	var/obj/structure/bed/chair/vehicle/lightcycle/summoned_cycle = null
Also, the vehicle code for both keys and vehicles themselves track eachother already, any reason you can't use the key's paired vehicle variable and vice versa?

2017-01-03 12:20 UTC, Shadowmech88 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	var/obj/structure/bed/chair/vehicle/lightcycle/summoned_cycle = null
Can I re-cast vars as different types from their parent? The `paired_to` var is cast as an `/obj/structure/bed/chair/vehicle` meaning I couldn't access light cycle-specific vars and procs.

2017-01-03 12:22 UTC, PJB3005 commented on code/game/objects/structures/vehicles/lightcycle.dm
> +	var/obj/structure/bed/chair/vehicle/lightcycle/summoned_cycle = null
Oh, right, didn't think of that.

It's fine then.

2017-01-04 23:21 UTC, ihadtoregisterforthis commented
The trails could despawn automatically after a reasonably long time, like a minute or two. It's not like someone riding it would survive forever.

Also change light cycles to lightcycles please

2017-01-05 02:49 UTC, Shadowmech88 commented
According to https://en.wikipedia.org/wiki/Tron_(franchise), the correct phrasing is "light cycle."

2017-01-05 13:37 UTC, PJB3005 approved these changes

2017-01-05 19:32 UTC, merged

2017-01-08 18:53 UTC, Intigracy commented
The point of the controller smacking the lights to remove them all was so that PLAYERS could remove them all easily.

2017-01-08 22:23 UTC, Shadowmech88 commented
But then players could just easily clear half the board in the middle of a duel by getting off their cycle and hitting their trail once.

2017-01-10 05:46 UTC, Aurx commented
Now we need a verb that puts everybody on a lightcycle and doesn't let them get off.

2017-01-10 06:04 UTC, Shadowmech88 commented
I could make a child of the keys that disallows dismounting, and then the verb could just spawn a key in everyone's hand and call `attack_self()`.

2017-01-10 08:47 UTC, Aurx commented
You'd also need to check for hand existence and forcedrop whatever they were holding, wouldn't you?

2017-01-10 09:06 UTC, Shadowmech88 commented
Correct.