Balloons
d3athrow/vgstation13 pull request #13257
Opened 2017-01-04 18:37 UTC by Shadowmech88

![beeellee](https://cloud.githubusercontent.com/assets/3991927/21654249/5557d70a-d27a-11e6-9389-73d1537c87b7.png) ![ddsss](https://cloud.githubusercontent.com/assets/3991927/21654252/5906e1fc-d27a-11e6-83ba-de43884a592c.png)

Adds balloons. Balloons can be inflated by any mob that breathes or has lungs.
Once inflated, you can tie some cable coil to the balloon, which allows it to be visible when you hold it.
Each balloon is assigned a random color when it spawns.
Balloons can be popped by any pointed object.
Boxes of balloons can be obtained from the party supplies crate orderable from Cargo.

2017-01-04 18:45 UTC, PJB3005 requested changes

2017-01-04 18:45 UTC, PJB3005 commented on code/game/objects/items/toys.dm
> +	icon += col
You should really be using the `color` var instead.

2017-01-04 18:45 UTC, PJB3005 commented on code/game/objects/items/toys.dm
> +/obj/item/toy/balloon/New(turf/T, var/ccol)
Make the first argument `atom`

2017-01-04 19:48 UTC, AI-is-rogue commented
Clowns should be able to turn the balloons into various shapes.

2017-01-04 19:56 UTC, Intigracy commented
Make the existing glove balloon a subtype of this please.

2017-01-04 20:09 UTC, SangriaMonkey commented
>that shading

:grimacing:

2017-01-05 02:43 UTC, Shadowmech88 commented
If anyone has a better sprite, I'm more than happy to accept it.

@AI-is-rogue
I plan to do that in a later PR.

2017-01-05 14:38 UTC, Shadowmech88 commented
I could also reparent the Syndicate balloon, but the only functionality it would gain would be popping and I'm not sure if people would want it to be poppable.

2017-01-05 14:55 UTC, PJB3005 requested changes

2017-01-05 14:55 UTC, PJB3005 commented on code/game/objects/items/toys.dm
> +		icon += col
Still need to use `color`

2017-01-05 22:36 UTC, ComicIronic commented on code/game/objects/items/toys.dm
> +/obj/item/toy/balloon/New(atom/A, var/ccol)
`ccol` is a pretty bad name, `chosen_col` would be better if that's what you're going for.

2017-01-05 22:50 UTC, ComicIronic commented on code/game/objects/items/toys.dm
> +/obj/item/toy/balloon/glove/inflate(mob/user, datum/gas_mixture/G)
If this is just copy-pasted for the glove spawning, you can make that a type var or a proc.

2017-01-05 22:59 UTC, Shadowmech88 commented on code/game/objects/items/toys.dm
> +/obj/item/toy/balloon/glove/inflate(mob/user, datum/gas_mixture/G)
How do I reference an object created from a type held in a var? Would
```
var/type = /obj/path
var/O = new type(loc)
```
work?

2017-01-05 23:01 UTC, ComicIronic commented on code/game/objects/items/toys.dm
> +/obj/item/toy/balloon/glove/inflate(mob/user, datum/gas_mixture/G)
Yes.

2017-01-06 04:19 UTC, gbasood commented
okay but can mommis use these

2017-01-06 04:32 UTC, Shadowmech88 commented
Yes.

2017-01-07 13:11 UTC, Shadowmech88 commented on code/game/objects/items/toys.dm
> +		icon += col
Is not using `color` going to prevent a merge?

2017-01-08 02:22 UTC, Blithering commented
Do balloons inflated by plasmamen become tiny bombs?

2017-01-08 03:20 UTC, Shadowmech88 commented
No, because plasmamen exhale CO2.

2017-01-08 04:00 UTC, Blithering commented
Dang. There go my hopes of creepy clown handing out doom balloons becoming a thing

2017-01-08 05:42 UTC, Shadowmech88 commented
You *can* fill the balloon with some of the contents of an air tank and use that,

2017-01-16 10:22 UTC, Shadowmech88 commented
New sprite with another attempt at shading.
![bbaalllloonn](https://cloud.githubusercontent.com/assets/3991927/21979161/671d37d2-dba3-11e6-932d-5ac67ec62516.png)

2017-01-16 10:23 UTC, Shadowmech88 commented
@PJB3005 
I've fixed it so that it uses the `color` var, now.

2017-01-16 10:28 UTC, Probe1 commented
Look at you go!  Those look much better.

2017-01-16 16:11 UTC, PJB3005 requested changes

2017-01-16 16:11 UTC, PJB3005 commented on code/game/objects/items/toys.dm
> +		B.air_contents.carbon_dioxide = 0.5
Very naive to assume every species breaths out CO2.

Also this should be using adjust to edit the mole counts.

2017-01-16 16:21 UTC, Shadowmech88 commented on code/game/objects/items/toys.dm
> +		B.air_contents.carbon_dioxide = 0.5
Every species *does* exhale CO2.
But I'll change it just in case that changes in the future.

2017-01-16 21:06 UTC, PJB3005 approved these changes

2017-01-18 06:24 UTC, merged

2017-01-18 16:29 UTC, Shadowmech88 commented
Dang, I forgot the changelog.

2017-01-18 18:30 UTC, Probe1 commented
Just open a PR of shame