(dnm) Rainbow laser + allows for RGB laserbeams
d3athrow/vgstation13 pull request #13320
Opened 2017-01-08 22:15 UTC by ultraplen

Some dude in OOC requested a clown themed laser that would shoot beams that progressed through the colors of the rainbow with each shot and that also had a secondary firemode that dealt braindamage, so here it is. Its a basic but fun gun that might be a suitable addition to some vault loottable. It is in need of a sprite which is primarily why I opened a PR for an unfinished project - if someone could make a clownlaser sprite Id be greatful.

Perhaps more important than the rainbow laser is the added support for rgb colored laserbeams + a grey-white beam sprite that looks decent colored. There is also a variable added for projectile weapons that colors the bullets.

(video  will be uploaded in a minute)

2017-01-08 22:16 UTC, BobdaBiscuit commented
Remember to make it so clumsy clowns get some different functionality that doesn't kill them

2017-01-08 22:17 UTC, ultraplen commented
Perhaps instead of two firemodes, being a clown and using the gun should cause it to shoot braindamage beams ?

2017-01-08 22:44 UTC, Intigracy commented on code/modules/projectiles/projectile.dm
> +/obj/item/projectile/proc/apply_projectile_color(var/proj_color)
please add whitespace

aka press enter

2017-01-08 22:45 UTC, Intigracy commented on code/modules/projectiles/projectile/beams.dm
> +/obj/item/projectile/beam/rainbow/rainbow/braindamage
whitespace

2017-01-08 22:45 UTC, Intigracy commented on code/modules/projectiles/projectile/beams.dm
> +/obj/item/projectile/beam/rainbow/braindamage/on_hit(var/atom/target, var/blocked = 0)
whitespace

2017-01-09 02:17 UTC, 9600bauds commented
@Intigracy Don't leave negative reviews over non-standard formatting requests please

2017-01-09 18:25 UTC, Intigracy approved these changes

2017-01-09 19:30 UTC, PJB3005 requested changes

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "A fearsome gun used by clown special forces"
Period here.

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +	var/fire_mode = 1
This can use better naming, or usage of defines so you can do `FIRE_MODE_KILL`, `FIRE_MODE_MINDFLAY`...

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +	var/list/color_list = list("#FF0000","#FF8C00","#FFFF00","#00FF00","#00BFFF","#0000FF","#9400D3")
You're not changing this list, so you should give it `/static` for cleanliness sake.

```dm
var/static/list/color_list = list("#FF0000","#FF8C00","#FFFF00","#00FF00","#00BFFF","#0000FF","#9400D3")
```

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/weapon/gun/energy/laser/rainbow/attack_self(mob/living/user as mob)
`as mob` does nothing here, remove it.

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +	if(current_color < 7 )
Better would be to make it use the length of the `color_list` list, so adding new colours isn't a problem.

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/weapon/gun/energy/laser/rainbow/Fire(atom/target as mob|obj|turf|area, mob/living/user as mob|obj, params, reflex = 0, struggle = 0, var/use_shooter_turf = FALSE)
Remove all the `as xxxx` things here.

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +			to_chat(user, "<span class='warning'>The [src.name] is now set to mindflay.</span>")
Use `\The [src]`

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +			to_chat(user, "<span class='warning'>The [src.name] is now set to kill.</span>")
Use `\The [src]`

2017-01-09 19:30 UTC, PJB3005 commented on code/modules/projectiles/projectile/beams.dm
> +/obj/item/projectile/beam/rainbow/rainbow/braindamage
What's with this typepath?

2017-01-09 20:50 UTC, ultraplen commented on code/modules/projectiles/projectile/beams.dm
> +/obj/item/projectile/beam/rainbow/rainbow/braindamage
its a mistake

2017-01-09 20:54 UTC, ultraplen commented on code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/weapon/gun/energy/laser/rainbow/attack_self(mob/living/user as mob)
what does `as mob` do exactly ? I copy-pasted this code from the egun.

2017-01-09 21:18 UTC, PJB3005 commented on code/modules/projectiles/guns/energy/laser.dm
> +/obj/item/weapon/gun/energy/laser/rainbow/attack_self(mob/living/user as mob)
The proc is used as a verb it communicates to BYOND what type of input is valid for the arguments, for the built in input windows.

This however has no relevance when working without regular procs so it's only clutter, as the type is better communicated by casting the variable.

2017-01-10 19:00 UTC, PJB3005 approved these changes

2017-01-12 12:31 UTC, ultraplen commented
![autistic_schreeching1](https://cloud.githubusercontent.com/assets/20318196/21889896/756dd24a-d8cb-11e6-8878-818fae7c0963.png)

2017-01-14 22:51 UTC, merged