Best borer
d3athrow/vgstation13 pull request #13369
Opened 2017-01-10 12:40 UTC by Gef21

Adds 1/10,000 chance of a borer egg hatching into a super cool special borer with new emotes, a new look (made by blithering), a new walk (made by blithering) and a new smell

http://i.imgur.com/1lF9a0U.png
http://i.imgur.com/BiV3qbY.png

2017-01-10 12:43 UTC, Gef21 commented
I realised my mistake don't meme me for it

2017-01-10 12:47 UTC, Skullyton commented
My immersions

2017-01-10 16:26 UTC, adriandias commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		if(defect == 666)
:1st_place_medal:

2017-01-10 16:34 UTC, PJB3005 approved these changes

2017-01-10 16:34 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		var defect = rand(1,10000)
You should use `var/defect` here.

2017-01-10 16:34 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		if(defect == 666)
You shouldn't copy paste all this code, and make a variable that gets set to the type of borer to spawn, then use that variable and remove the copy paste.

2017-01-10 16:35 UTC, PJB3005 requested changes
Wrong button

2017-01-10 17:17 UTC, Gef21 commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		if(defect == 666)
I wanted to do that but honestly I don't really know what I'm doing

2017-01-10 17:18 UTC, Gef21 commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		var defect = rand(1,10000)
done

2017-01-10 18:58 UTC, Aurx commented
That sprite looks like trash.

2017-01-10 19:01 UTC, Aurx commented
Disregard above, this entire thing is just trash.  
What in the world is the intended point of this, aside from shoving shit into the repo?

2017-01-10 19:03 UTC, yclatious commented
Literally just a joke pr aurx, don't get mad, its gef we are talking about here, you should not expect a serious pr from him.

2017-01-10 19:04 UTC, Gef21 commented
it adds depth to borers

2017-01-10 19:40 UTC, PJB3005 requested changes

2017-01-10 19:40 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/borer/egg.dm
> +		if(defect == 666)
I meant you should do the following:
```dm
var/borer_type = (defect == 666 ? /mob/living/simple_animal/borer/defected_borer : /mob/living/simple_animal/borer)

var/mob/living/simple_animal/borer/B = new borer_type(T, child_prefix_index)
B.transfer_personality(O.client)
```

2017-01-10 19:48 UTC, PJB3005 approved these changes

2017-01-11 00:50 UTC, SangriaMonkey commented
:eggplant:

2017-01-11 03:10 UTC, Megamaw commented
Finally, I can play a dog.

2017-01-11 07:35 UTC, SonixApache commented
delete this

2017-01-12 21:04 UTC, merged

2017-01-12 21:05 UTC, Probe1 commented
If it EVER comes up and people hate it we'll revert it.

2017-01-12 21:32 UTC, Intigracy commented
I hate you.

2017-01-12 21:34 UTC, Exxion commented
This is excellent except the word is "defective"