AI cameras can no longer track invisible mobs
d3athrow/vgstation13 pull request #13373
Opened 2017-01-10 17:08 UTC by 9600bauds

Before anyone can say "this guy is just butthurt because an AI tracked his shit!!!" I have literally all antag preferences turned off :^)

Invisible mobs don't show up in the AI's tracking options and tracking mode ends if the mob becomes invisible. This will affect the following:
* Humans with the Chameleon gene that remained still long enough to be transparent
* Wizards/Vampires using Jaunt
* The invisibility cape
This will NOT affect:
* Vampire cloak of darkness

I partly consider this a bugfix but tagging it balance anyways

:cl: 
 * tweak: AI camera can no longer track invisible mobs.

2017-01-10 17:10 UTC, Shadowmech88 commented
>This will affect the following:
>The invisibility cape

But the cloaking cloak sets alpha to 1, not 0.

2017-01-10 17:14 UTC, 9600bauds commented
![mime construct sierra 2017-01-10 141349 1](https://cloud.githubusercontent.com/assets/6526157/21816482/12257658-d73f-11e6-929e-e0f5dc70f153.png)
![mime construct sierra 2017-01-10 141359 1](https://cloud.githubusercontent.com/assets/6526157/21816483/13132b50-d73f-11e6-8df0-c55b27cd33bb.png)
I think that counts as invisible

2017-01-10 17:18 UTC, Shadowmech88 commented
What I mean is, your code checks `alpha < 1`. The cloaking cloak sets alpha to exactly 1, so `alpha < 1` will be false.

2017-01-10 17:19 UTC, 9600bauds commented
Oh derp, I tested it with == 1 and hastily changed it

2017-01-10 21:29 UTC, PJB3005 requested changes

2017-01-10 21:29 UTC, PJB3005 commented on code/game/machinery/camera/tracking.dm
> +			if(target.digitalcamo || target.invisibility || target.alpha <= 1)
The invisibility check should go relative to the AI's `see_invisible` instead.

2017-01-10 21:29 UTC, 9600bauds commented on code/game/machinery/camera/tracking.dm
> +			if(target.digitalcamo || target.invisibility || target.alpha <= 1)
Correct

2017-01-10 21:42 UTC, PJB3005 approved these changes

2017-01-11 02:50 UTC, aceedex commented
improved jaunt is super free. I don't see why an AI shouldn't be able to track it, speaking from a balance perspective. Its a get out of jail free card you can use very often with no downsides. 
everything else is fine

2017-01-12 01:05 UTC, Aurx commented
@aceedex
Instead of letting the AI track invisible jaunting wizards, it'd be better to make jaunting wizards visible.

2017-01-13 09:20 UTC, merged

2017-01-13 09:21 UTC, Probe1 commented
@aceedex @Aurx make upgrading jaunt change your opacity until you are visible.