Trader vending machine (again)
d3athrow/vgstation13 pull request #13381
Opened 2017-01-10 23:43 UTC by Zth--

Revives #12395

The list so far is:
- Box of marauder circuits (one is missing, because vox are jews)
- Box of natural blue space crystals, with an extra blue tomato
- Bag of Holding
- Bluespace beaker
- Advanced magboots
- Borer egg
- A small bottle of peridaxon
- A small bottle of nanites
- A bottle of rezadone

:cl:
- rscadd: New vending machine for traders. It spawns with a few random items including stuff like marauder circuits, borer eggs, a small bottle of peridaxon. This doesn't add it to the map yet.
- rscadd: This machine can only be operated with special trader coins.
- rscadd: Every trader spawns with a single trader coin.
- rscadd: Since these are big changes, expect getting jobbanned or even permabanned if misused.

2017-01-10 23:45 UTC, 9600bauds commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
If you add more items to the premium list you'd have to modify the 5 here, use `premium.len - #` or add to the premium list instead

2017-01-10 23:47 UTC, 9600bauds commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/trader/attackby(var/obj/item/W, var/mob/user) //This shitcode is needed.
Seems to me like you could just have an `accepted_coins` list and implement this in the parent

2017-01-10 23:49 UTC, 9600bauds commented
About the items:
10u peridaxon is good for ONE pair of lungs
10u rezadone is basically, well, piss, too
The CE's magboots is honestly kind of iffy, the least that could be done is make them look different

2017-01-10 23:50 UTC, Zth-- commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
`I guess premium.len / 2 will do the trick`

2017-01-10 23:51 UTC, 9600bauds commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
I figured the idea here was that you only get a fixed amount of items no matter how many different ones are possible

2017-01-10 23:54 UTC, Probe1 commented
No to the CE magboots/antag steal item. Just not a good idea.  Subtyping it is ok.

2017-01-10 23:54 UTC, Zth-- commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
Actually, yes, I was thinking of something else.

2017-01-10 23:56 UTC, Zth-- commented
Rezadone is 30 units, I'll move peridaxon to 30 units too. Yeah I was thinking the CE magboots was stupid

2017-01-10 23:56 UTC, 9600bauds commented on code/game/objects/items/trader.dm
> +	name = "Trader coin"
missed opportunity to add cluckbucks

2017-01-11 00:18 UTC, kilozombie commented
Big bad list of a lot of items that could be added
https://github.com/d3athrow/vgstation13/issues/13364

2017-01-11 02:11 UTC, Durgen commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
>"When you charge a customer $100, and he pays you by mistake $200, you have an ethical dilemma — should you tell your partner?"

keked

2017-01-11 02:21 UTC, Kurfursten commented
@9600bauds 10u Peridaxon is good for two (2) infinite chem farms with Odysseus

2017-01-11 02:25 UTC, 9600bauds commented
Odysseus duping was a mistake that should be rectified and ABSOLUTELY should not be balanced against

2017-01-11 02:26 UTC, Kurfursten commented
I don't disagree but as long as it still exists we have to acknowledge that it exists.

2017-01-11 02:51 UTC, Aurx commented
[BALANCE]

2017-01-11 03:13 UTC, jakmak4 commented
yeahhh maybe the high tech stuff (adv mags, bluespace bags, and medi nanos) is to much but the peraxadone rezadone and bluespace crystals are in the right direction. Vox shouldnt have high tech gear BUT should have easy access to exotic and rare items like rezadone or natural bluespace crystals. Maybe also include the dartguns raiders get (filled with healing chems instead of chloral+stox ofcourse) or even things like limited phazite sheets, switchtools (surgeon, swiss army, tool switchtool), maybe even a really rare chance for some of the obscure wizard summon only guns (uzi, deagle, demoman grenade launcher ,hectate stuff like that). Also the crossbow raiders have wouldnt be that bad of an idea either. Perhaps even things like thermomonacles or NV goggles. The idea is in the right direction but could use some tweaking. Either way this change is an excellent idea.

2017-01-11 03:23 UTC, kilozombie commented
Jakmak, not sure if the issue I made was read at all, but we DEFINITELY don't want to give traders shit that can benefit them. Guns fall straight into that category.
I'll repost my revised list for this PR

>The idea with items are to make them unviable for a Trader to use, but valuable to a Crew. This encourages a relationship of commerce without allowing the birds to powergame with their items, even as an antag. This means weapons and strong toys should generally be out of the list.


- Box of marauder circuits (1 missing)
- Box of natural bluespace crystals
- Flawless bluespace crystal
- Bluespace beakers
- Advanced magboots
    Vox have their own even better pair at roundstart.
- Bottle of peridaxon
- Bottle of nanites
- Bottle of rezadone
- Random virus sample dish
    Vox doesn't have Virology equipment and can't use this to cause havoc.
- Borer egg
    Technically these can already be obtained with accurate no-fruit pie shenanigans.
- Clown spacesuit and helmet.
- Small number of Phazon sheets.
- Bananium sheets.
- Single bananium coin.
- Paper with location and identification of two Genetics powers.
    Two or one? Shouldn't be an injector, else Traders will just put good powers in themselves.
- Some sort of unanchored machinery?
- Random clothing/costume crate
    The more variety, the better. In an uplink or cargo shuttle implementation, these should be cheap.
- Box of random advanced machinery parts
    R&D hardly makes these for other departments. If traders could offer up a kit to DIY upgrade your workplace, that'd be pretty cool.
- Unobtainable food items, or food with an unobtainable modifier.
    Golden food? Magic food? Bluespace sweet sundae ramen? Nar-Sliders? Who knows, it's completely up to the coders. There aren’t currently any adminbus food items that I know of.
    Possibly some special Vox crackers? Feed to Poly for special effects??
- Lazarus injectors.
    Miners rarely ever give these out, and every department excluding Cargo has pets that they don't want to die. Sell the HoP an injector for Ian!
- Cages with random animals in them.
    Specifically slimes? Or just all kinds of mobs? Is this a golden-slime situation where it's usually not worthwhile to open?
- Triple capacity fire extinguisher.
    For ease of Xenobiology. Also potentially great with dangerous chemicals. Need input on if this can be exploited badly.
- Xenoarch-esque modified items.
    I don’t know all the details of Xenoarch. Do small artifacts (wrenches made of aluminum or whatever) have any effects? Less, more brute damage? Could we get Vox traders selling some tacky adamantine clown shoes for an insane price?
- Plastic, cardboard, wired tiles, carpet, etc.
    Some of this spawns in moderate quantities at random on Box and Meta. They’re not obtainable from mining IIRC but a nice sellable item.
- Portable recharger.
    Presumably would recharge at ⅓ or ¼ the normal rate, but extremely handy if you’re a Security officer always on the run. Stick it in your backpack and juggle your energy weapons around.
- A variety of implants.
    Potentially fun to sell. Non-crew birds wouldn’t have things like loyalty implants, though.
- Special or improved borg parts/modules.
    Vox can’t use these for themselves, as there are few lawsets that respect non-crew non-humans, and they don’t exactly have a Robotics bay. Also, borgs will now want to buy parts from traders. Wew.
- Infinite ammo foam dart pistol, cap gun, laser tag gun, etc.

2017-01-11 03:35 UTC, jakmak4 commented
alright i see what your getting at with the guns and i admit you are probably right about them but the  other things i suggested have a potential to work. Thermogoggles and NVGs fill a specific niche that doesnt fit a bird often and swiss army knifes/switch tools would be usefull to basically everyone especially sec/assistants. The idea of giving them high tech gear like nanobots and marauder circuts doesnt fit traders very well in my opinion but most of the other stuff you mentioned do seem like low tech exotic items that travelers across the universe might encounter in their journey.

2017-01-11 07:50 UTC, Durgen commented
>Bag of Holding

Shouldn't be included imo. People would just keep it for themselves, and it's not particularly useful to the crew.

2017-01-11 07:51 UTC, Kurfursten commented
@Durgen I think the idea is to include something highly desirable to miners on the list.

A bag of holding isn't a very big boon for a trader, but it's a huge benefit for a miner since it lets you stow your drill.

2017-01-11 08:08 UTC, Durgen commented
@Kurfursten ah, forgot about miners

2017-01-11 09:22 UTC, Kitfox88 commented
1 (s) balloon

2017-01-11 10:27 UTC, yclatious commented
Celtic board, for shits and giggles, alongside some stolen magboots of the regular kind, maybe a syndie balloon like kitfox said and maybe a aeg kit for the distinct traitor or sec, can't be abused because like you said, any vox who was niggering the armory for a egun will get baned when this gets merged anyways, and science never gives enough of these to sec, despite them being amazing.

2017-01-11 10:32 UTC, Kurfursten commented
>will get baned

If I pull that nitrogen mask off, will they die?

2017-01-11 18:18 UTC, Intigracy commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/trader/attackby(var/obj/item/W, var/mob/user) //This shitcode is needed.
^ + the premium.len - # fix

2017-01-11 18:20 UTC, Intigracy requested changes

2017-01-11 18:20 UTC, Intigracy commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/trader/attackby(var/obj/item/W, var/mob/user) //This shitcode is needed.
This would be the best way to go about it.

2017-01-11 18:20 UTC, Intigracy commented on code/game/machinery/vending.dm
> +	for(var/random_items = 1 to 5)
If you want premium items to always have four items, do `premium.len - 4` instead of the 5

2017-01-11 18:20 UTC, Intigracy commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		..()
too many tabs

2017-01-11 18:20 UTC, Intigracy commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		..()
too many tabs

2017-01-11 18:25 UTC, Durgen commented
can the vending machine get some emag functionality so vox tra(itor)ders can finally have some fun?

2017-01-12 20:57 UTC, Zth-- commented
Will test tonight to see if it's finished

2017-01-13 02:40 UTC, Zth-- commented
This one is ready to go.

2017-01-13 02:43 UTC, Intigracy approved these changes

2017-01-13 02:57 UTC, merged

2017-01-13 03:02 UTC, Probe1 commented
If you feel items should be added or removed pop open a PR 

@kilozombie 

Lotta great ideas there.

2017-01-13 03:51 UTC, Probe1 commented on code/game/machinery/vending.dm
> +	name = "Jewvend"
![1463211427303](https://cloud.githubusercontent.com/assets/8550416/21917907/a7a99bb0-d919-11e6-965a-aea2bc5de1a0.png)

2017-01-13 03:54 UTC, Kurfursten commented on code/game/machinery/vending.dm
> +	name = "Jewvend"
We were all thinking it but nobody wanted to be the one to say it

2017-01-13 04:01 UTC, Probe1 commented on code/game/machinery/vending.dm
> +	name = "Jewvend"
I just skimmed over it without taking it in.

2017-01-13 05:20 UTC, PromethTK11 commented
What about another pod parts?

Maybe a odd-looking bot, buttbots, xenoarch artifacts, gas miners, maybe even some random cargo crates

2017-01-13 05:28 UTC, Durgen commented
can it at least get a sprite with a 6 pointed star on it?