Invisible Spray
d3athrow/vgstation13 pull request #13390
Opened 2017-01-11 08:09 UTC by Shadowmech88

![invisible_spray_display](https://cloud.githubusercontent.com/assets/3991927/21840388/e2b5e5c4-d7a2-11e6-8255-205624b7efae.png)
Invisible spray can be used on any mob or object in order to render it invisible for five minutes.
Each can is limited to one use by default.

A can of invisible spray can be bought from clown and mime traitor uplinks for 8 TC.

:cl:
 * rscadd: Added invisible spray to clown and mime traitor uplinks for 8 TC.

2017-01-11 08:11 UTC, Probe1 commented
neat but why the clown and not just the mime?

2017-01-11 08:22 UTC, Shadowmech88 commented
I saw that the super glue was clown+mime and that made me think about the fact that this item is somewhat prank-themed, and so could easily fit with either the clown's or mime's motif.

2017-01-11 08:29 UTC, Probe1 commented
Kay works for me.

2017-01-11 08:53 UTC, Skullyton commented
>Invisible esword murder
>The spray can't be washed off by showers or something

Why would you do this?

2017-01-11 10:04 UTC, Probe1 commented
This suddenly got a lot more horrifying.

2017-01-11 10:27 UTC, Shadowmech88 commented
What if I make it so that any water source washes it off, including spray bottles/extinguishers/splashing?

2017-01-11 11:55 UTC, PJB3005 commented
... Is this from SpongeBob?

How did they get it off in SpongeBob?

2017-01-11 11:59 UTC, Shadowmech88 commented
By being splashed with a bucket of water.

2017-01-11 12:14 UTC, yclatious commented
While the though of a mime being invisible and doing esword murderboning isn't my taste, the image of sec spraying everything with a extinguisher to find the sneaky mute fucker makes me laugh too much.
Plus, any mime or clown could fill the extinguishers with other shit to make them not work, and sec unwillingly lubing the halls would also be hilarious, promote active antaging and be a great example of sabotage done right.

2017-01-11 14:48 UTC, Megamaw commented
honestly, bump up the TC cost a little and make it permanent unless washed off

this will lead to more advanced pranks than what can be pulled off in five minutes

(or maybe an alternate Advanced Invisible Spray)

but either way, A++ i fucking love it

2017-01-11 21:20 UTC, Probe1 commented
Still too powerful to be able to make weapons or even yourself invisible and go on an invisible murder spree.

2017-01-11 23:45 UTC, Aurx commented
Why not make it so that it makes you but NOT what you're wearing invisible?

2017-01-11 23:48 UTC, Probe1 commented
https://www.youtube.com/watch?v=9OPc7MRm4Y8

2017-01-12 00:42 UTC, ComicIronic requested changes

2017-01-12 00:42 UTC, ComicIronic commented on code/game/objects/items/weapons/cosmetics.dm
> +		spawn(invisible_time)
Do not assume the mob still exists after five minutes.

2017-01-12 00:42 UTC, ComicIronic commented on code/game/objects/items/weapons/cosmetics.dm
> +		spawn(invisible_time)
Do not assume the atom still exists after five minutes.

2017-01-12 11:47 UTC, Skullyton commented on code/game/objects/items/weapons/cosmetics.dm
> +		spawn(invisible_time)
So, just do a check to see if src still exists?

2017-01-12 12:11 UTC, Shadowmech88 commented on code/game/objects/items/weapons/cosmetics.dm
> +		spawn(invisible_time)
To see if `target` still exists.

2017-01-12 15:04 UTC, Shadowmech88 commented
* When spraying a mob, invisible spray now only makes its *body* invisible, not the items it's wearing or holding. See http://puu.sh/tjOOL/81d725051d.webm for example.
* Invisible items no longer show up on a mob's body or in a mob's hands.
* Reduced price of invisible spray from 8 TC to 4 TC.

2017-01-12 15:16 UTC, Shadowmech88 commented
* Invisible items held by a mob no longer show up when examining the mob.

2017-01-12 15:30 UTC, LemonTheFruit commented
I think the idea of having it stay until washed off is really good. Maybe keep the telecrystal price at 8 for balance, if that happens. And how does it work with applying it to a backpack, as opposed to putting it in a backpack?

2017-01-12 15:51 UTC, Shadowmech88 commented
>And how does it work with applying it to a backpack, as opposed to putting it in a backpack?

To put it into a backpack, you must open the backpack's inventory and click an inventory slot. Clicking the backpack itself will spray the backpack.

2017-01-14 22:50 UTC, Probe1 commented
I still think this is entirely too powerful and should not be merged in its current state.

Acceptable changes in my mind:

Only works on mobs (so clothing, weapons, etc are visible)
Explicitly does not work on weapons
Interacting with anything breaks its invisibility like a cham projector

2017-01-14 23:29 UTC, ComicIronic requested changes

2017-01-14 23:29 UTC, ComicIronic commented on code/modules/mob/living/carbon/human/examine.dm
> +	if(w_uniform && !(slot_w_uniform in obscured) && !(w_uniform.invisibility || w_uniform.alpha <= 1))
I don't like this copy-paste. Add a proc to do it, like `w_uniform.can_see_equipped()`.

2017-01-14 23:29 UTC, ComicIronic commented on code/modules/mob/living/carbon/monkey/update_icons.dm
> +		var/lowest_alpha = 255
Don't particularly like how often this loop is copypasted. Make it a proc like `get_lowest_alpha()`.

2017-01-14 23:29 UTC, ComicIronic commented
It's almost there.

2017-01-19 01:09 UTC, ComicIronic approved these changes

2017-01-19 18:42 UTC, StreptoMutans commented
What happens if you apply it to a shard?

2017-01-19 18:51 UTC, ComicIronic commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(body_alphas.len)
Shouldn't this still use `get_lowest_body_alpha()`?

2017-01-19 18:52 UTC, Shadowmech88 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(body_alphas.len)
It should, I forgot about this one.

2017-01-19 18:52 UTC, ComicIronic submitted a review, later dismissed
Just need to fix your proc use.

2017-01-19 18:52 UTC, ComicIronic commented on code/modules/mob/living/carbon/monkey/examine.dm
> +	if (src.handcuffed && !(handcuffed.invisibility || handcuffed.alpha <= 1))
Forgot to use `is_visible()` in this file.

2017-01-19 18:55 UTC, Shadowmech88 commented
A supermatter shard? It works as normal.

2017-01-19 18:59 UTC, Shadowmech88 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(body_alphas.len)
Done.

2017-01-21 01:01 UTC, Megamaw commented
i'd like to reiterate my stance: making it last only five minutes is a good way to make it only useful for a quick killing spree, rather than actual pranks

i mean, if there's still attack messages from invisible people, we can just arm up security with cleaning equipment

tl;dr i think making last as indefinitely until washed a: keeps to source material better and b: allows applications other than stealth murderbone

2017-01-21 01:05 UTC, Shadowmech88 commented
Making it indefinite would allow someone to use it to hide essentially forever.

2017-01-21 01:07 UTC, Megamaw commented
unless they got doused, and if they stayed quiet. iirc making noise will still blow your cover-- so opening doors to move to other parts of the hall, or interacting with closets or anything really

heck, your backpack makes noise.

if you're able to circumvent all these things and evade a bunch of fucks out for you with space cleaner, you deserve to be rewarded.

2017-01-21 01:14 UTC, LemonTheFruit commented
I agree with mega, the prospect of security going on a search, needing to work to get cleaner and such will add a whole new demension of gameplay. Increase the cost to balance it. It'd be interesting for all the reasons mega pointed out earlier.

2017-01-21 01:23 UTC, Megamaw commented
also mind you this is a mime/clown item only. it's not like literally every traitor can buy this.

2017-01-21 01:24 UTC, LemonTheFruit commented
You have to be completely naked as well, unless you purchase more.

2017-01-21 01:26 UTC, Shadowmech88 commented
>unless they got doused, and if they stayed quiet

This is the issue, that they'd have to make themselves noticed in order to be found. If someone is visible, you can have the main station keep an eye out and Security search Maintenance bit by bit, and you're decently likely to find them.
If they're invisible forever and don't want to be found, what hope would you have? If there's more than just you in the room, something like a backpack ruffling wouldn't be a tip off that there's an invisible man there. The AI isn't even capable of tracking them. You could probably lay down in the corner of the bar and never be found, much less if you were actively avoiding Security.

These things can be varedited, feel free to ask an admin to take all your TC in exchange for making the `invisible_time` var ludicrously large.

2017-01-21 01:30 UTC, LemonTheFruit commented
So the point is, if they do nothing as you suggest, they aren't antagging and thus not attracting security.

2017-01-21 01:33 UTC, Shadowmech88 commented
They could also do stuff that doesn't make it obvious there's an invisible person doing them. They could spray themselves and a backpack and tailgate anyone into anywhere and, once they're alone, take whatever they want and flush themselves down disposals.
At least this way the station will only have to endure that for a short time, if someone decides to do so.

2017-01-22 03:24 UTC, Megamaw commented
so let me get this straight, mr. 88

it's broken if it has any practical application for the traitor?

five minutes isn't a lot of time to do anything interesting other than murderbone.

2017-01-22 10:08 UTC, PJB3005 commented
I think infinite would be better yes.

Honestly this is the kind of thing we can't predict and the best we can do is to push it in and rebalance it if it's proving to be too OP.

I say make it infinite and ship it.

2017-01-22 16:15 UTC, Shadowmech88 commented
How much should it cost, then?

2017-01-22 19:13 UTC, LemonTheFruit commented
5 TC, max of four invisible items

2017-01-23 01:09 UTC, Shadowmech88 commented
Alright, we'll see.

2017-01-23 01:09 UTC, Shadowmech88 commented
* The invisible spray that can be purchased from mime and clown traitor uplinks is now an invisible variant that will never wear off on its own.

2017-01-23 01:13 UTC, Intigracy commented
Water removes it, right?

2017-01-23 01:19 UTC, Shadowmech88 commented
From mobs, yes.

It doesn't remove it from items because I couldn't think of a good way to track whether an item has been sprayed with invisibility spray, since items don't have a list of alphas that gets regularly checked like mobs do in their Life().

2017-01-23 08:41 UTC, Probe1 commented
That is even worse than before.

2017-01-23 14:34 UTC, Lokiamis commented
Anybody who thinks it should be infinite doesn't remember the cloaking device and when we had to have thermals in security. 
-requires heavy metagaming to counter. 
-invisible bodies are essentially removed from the game even if they're in the middle of the bar
-free escape if objective is completed with <15 tc
-at least prevent it from being used on the disk
-ability to buy 4 covers jumpsuit(pockets), weapon, backpack, radio. 
-can spray your objective items, spare ID, or whatever and security will never know even if they catch you
I'm not crazy and TCs/costs were doubled, right? 5tc now is equal to 2.5tc befote, making this one of the cheapest syndicate items.

2017-01-23 14:40 UTC, Exxion commented
The cost is a good point
Personally, I'd say make it 10 or more

As for the rest, I play neither antag nor jobs from whom antags commonly steal, so I'm not exactly an authority

2017-01-23 14:45 UTC, LemonTheFruit commented
I think it's important to find a way for water to wash away the spray from items. That will be a huge issue if there's no way to counter against items. How do monkey cubes change from an object to a mob, with water? Maybe something similar can be done to make washing it off items possible.

2017-01-23 19:23 UTC, Shadowmech88 commented
>How do monkey cubes change from an object to a mob, with water?

Monkey cubes specifically have an interaction with water.
The issue isn't making code execute when an item contacts water, it's keeping track of whether an item has been sprayed with invisible spray. I guess I could make an `/obj`-level var for it, but I don't like the idea of making a new var for just this one specific interaction with this one specific item.

2017-01-24 23:12 UTC, Shadowmech88 commented
* Invisible spray can now be washed off of objects with water.

2017-01-27 19:18 UTC, N3X15 commented
Conflicts, must be fixed before merge.

2017-01-27 19:46 UTC, Shadowmech88 commented
Conflicts fixed.

2017-01-31 04:18 UTC, merged