Logs artifact finding, breaking and effects
d3athrow/vgstation13 pull request #13482
Opened 2017-01-15 19:36 UTC by jknpj

Adds artifact investigation log with findings, breaking, effect triggering, button pressing and spawning.

Closes #6649

:cl:

 * bugfix: Gas/Temp triggered secondary artifact effects can be toggled off now

2017-01-15 20:58 UTC, ComicIronic requested changes

2017-01-15 20:58 UTC, ComicIronic commented on code/modules/mining/mine_turfs.dm
> +							B.investigation_log(I_ARTIFACT, "|| [B.artifact_find.artifact_find_type] || found by [user.name]([user.ckey]).")
Use the proc for formatting ckey and mob name properly.

2017-01-15 21:31 UTC, jknpj commented on code/modules/mining/mine_turfs.dm
> +							B.investigation_log(I_ARTIFACT, "|| [B.artifact_find.artifact_find_type] || found by [user.name]([user.ckey]).")
It is using user from `/turf/unsimulated/mineral/attackby(obj/item/weapon/W as obj, mob/user as mob)`
![user](https://cloud.githubusercontent.com/assets/17928298/21966267/5014fc54-db4f-11e6-83ad-34ec96173614.png)
This log is from before adding that second ||

2017-01-15 22:45 UTC, ComicIronic commented on code/modules/mining/mine_turfs.dm
> +							B.investigation_log(I_ARTIFACT, "|| [B.artifact_find.artifact_find_type] || found by [user.name]([user.ckey]).")
Yes, but `key_name(user)` is the correct way to do it, instead of manual formatting.

2017-01-15 23:18 UTC, jknpj commented on code/modules/mining/mine_turfs.dm
> +							B.investigation_log(I_ARTIFACT, "|| [B.artifact_find.artifact_find_type] || found by [user.name]([user.ckey]).")
The more you know

2017-01-19 01:03 UTC, ComicIronic approved these changes

2017-01-19 01:03 UTC, ComicIronic commented
Let's see if this breaks something.

2017-01-19 01:04 UTC, merged