Harlequin Ichthyosis
d3athrow/vgstation13 pull request #13503
Opened 2017-01-16 22:58 UTC by Shadowmech88

Adds new stage 4 virus symptom, harlequin ichthyosis.
This symptom causes the sufferer's skin to become incredibly thick and dry, with the severity getting worse the longer the sufferer goes without quenching their skin with water.
As their skin dries out and hardens, it loses its ability to effectively disperse heat, causing the sufferer to overheat more easily. However, the sufferer also takes decreased brute damage, due to their skin thickening and hardening.
As the symptom progresses untreated, the sufferer's heat dispersal grows worse. Once their skin dries out enough, they lose the ability to sweat, which further contributes to the risk of overheating.
As the symptom reaches advanced stages, the sufferer will also experience difficulty breathing and frequent bleeding.

:cl:
 * rscadd: Added harlequin ichthyosis as a new stage 4 virus symptom, causes overheating among other negative effects the longer you go without quenching your skin with water.

2017-01-16 23:16 UTC, PJB3005 requested changes

2017-01-16 23:16 UTC, PJB3005 commented on code/modules/mob/thermoregulation.dm
> +		if(!(H.species.anatomy_flags & HAS_SWEAT_GLANDS))
Do ` if(~H.species.anatomy_flags & HAS_SWEAT_GLANDS)` instead.

2017-01-16 23:16 UTC, PJB3005 commented on code/modules/reagents/Chemistry-Reagents.dm
> +		if(istype(M, /mob/living/carbon))
`iscarbon`

2017-01-16 23:36 UTC, PJB3005 requested changes

2017-01-16 23:36 UTC, PJB3005 commented on code/modules/virus2/effect/effect.dm
> +										if(!(H.flags & NO_BREATHE))
`!(x & y)` -> `~x & y`

2017-01-17 00:59 UTC, Probe1 commented
All that is needed is to apply water anywhere?

2017-01-17 03:54 UTC, Shadowmech88 commented
In the same way you'd have to if you were on fire, yes.
Each application of water only reduces the multiplier by 1-3 though, and it gets increased by 10 every time it activates, so you have to be very diligent about keeping it under control.

2017-01-17 04:31 UTC, carshalash commented
Harlequin people are gross and look like krispy kreme donuts.

2017-01-17 05:10 UTC, kol1th commented
Make their eyes pop out too. :^)

2017-01-24 21:44 UTC, PJB3005 approved these changes

2017-01-25 01:57 UTC, merged