Yep, You Guessed It: It's Even More Chemistry Autism, Yet Again
d3athrow/vgstation13 pull request #13544
Opened 2017-01-19 03:52 UTC by 9600bauds

@nuklearcellphoneg wanted this
When not loaded with a bloodpack, instead of a wonky set rate of transfer, IV drips will now transfer each chemical individually. Bloodpacks not affected. Here's the why/before/after/how/why:

BEFORE
IV loaded with a beaker containing 1 chemical: Transfers 0.2u per tick regardless of metabolism rate. Normal chemicals metabolise at 0.2u, so everything works OK. Chemicals will a lower metabolism rate slowly build up. Drinks, like DD, effectively have full effectiveness but are only drained half as fast, thus letting you squeeze twice as many heals.
IV loaded with a beaker containing 2 chemicals split 50-50: Transfers 0.2u per tick regardless of metabolism rate. Assuming both have default metabolism, you are effectively squeezing twice as many heals out of both. If either is DD it won't work.
IV loaded with a beaker containing 3+ chemicals: NONE OF THEM WORK BECAUSE THEY GO UNDER THE MINIMUM METABOLIZABLE AMOUNT

AFTER
IV loaded with # chemicals: All chemicals are individually transferred at their exact metabolism rate. No build-ups can happen and no effective "squeezing twice as much out of your chemical". If the chemicals in the beaker are at an uneven ratio, such as 40/60, some will simply run out before the others.

![dreamseeker_2017-01-19_00-41-17](https://cloud.githubusercontent.com/assets/6526157/22093078/7b1b99a0-dde1-11e6-9cc5-551f16664ee3.png)
after 1 tick
![dreamseeker_2017-01-19_00-41-37](https://cloud.githubusercontent.com/assets/6526157/22093081/810e84bc-dde1-11e6-8ee3-159269f3c5c2.png)
after a while
![Uploading dreamseeker_2017-01-19_00-52-16.png…]()

:cl:
 * tweak: Changed how IV drips handle non-bloodbag containers, they will now transfer each chemical in the solution individually, meaning they should now work (at all) when loading a beaker with 2+ chemicals in it.

2017-01-19 03:56 UTC, Shadowmech88 commented
What advantage do IVs have over just taking horse pills of whatever meds you need?

2017-01-19 04:03 UTC, Probe1 commented
Wow that is some quality autism.

@Shadowmech88 you can choose the dose by taking them off the IV instead of making the pill on demand or having a jumbo pill that sends half the reagents to waste.

2017-01-19 04:13 UTC, 9600bauds commented
It's like a pill that you can force the guy to regurgitate halfway through,  then feed it to someone else. It also has all the downsides of not being actually a fucking pill.

2017-01-19 04:20 UTC, Sprok0 commented
RIP holy water IVs

2017-01-19 04:21 UTC, Probe1 commented
I don't understand how this affects that.

2017-01-19 04:22 UTC, Sprok0 commented
Holy water has a metabolism rate of 5, IVs could be used to stretch it. Now it burns through it super fast

2017-01-19 04:28 UTC, Probe1 commented
That is a little disappointing but I'm not super broken up over it inadvertently addressing unintended behavior.  

I guess this kills monkeymen radium IVs curing viruses super fast too.

2017-01-19 04:41 UTC, Zth-- commented
Now give IV drips a new sprite and they'll feel as _new_

2017-01-19 04:57 UTC, Probe1 commented
zth understands.

2017-01-19 05:28 UTC, 9600bauds commented
I didn't know about holywater IVs but from the sounds of it they probably died with #11362 and nobody noticed, if anything this makes holywater actually WORK in IVs now.

I don't understand how would IV drips make radium cure monkeys faster

I think Goon has a nice IV drip sprite we could steal?

2017-01-19 06:11 UTC, nuklearcellphoneg commented
I just started bawling IRL

2017-01-19 06:11 UTC, nuklearcellphoneg commented
Where do I donate money

2017-01-19 06:12 UTC, Zth-- commented
@9600bauds check https://github.com/9600bauds/vgstation13/pull/1

2017-01-19 06:21 UTC, 9600bauds commented
OK serious question: Someone made a /goon/ folder for goon-stolen icons, is this actually needed/a thing?

2017-01-19 20:21 UTC, 9600bauds commented
A few issues with Goon's icon:
It has no hooked/unhooked versions, so it would look the same whether it was hooked to someone or not
It has no gradual unfilling, so it would look the same at 1u remaining or 100u remaining

2017-01-20 05:12 UTC, Probe1 commented
"A few issues"

It's worse in every way.

2017-01-20 09:25 UTC, PJB3005 commented
I agree it has issues but nothing is worse than the current IV.

2017-01-20 09:27 UTC, Probe1 commented
Except goons.  A sprite should convey information while looking nice.  Goons conveys a lot less information and it's arguable whether it looks better.

2017-01-20 17:34 UTC, Exxion commented
There's nothing wrong with the current IV sprite

2017-01-20 22:25 UTC, Iamgoofball requested changes

2017-01-20 22:25 UTC, Iamgoofball commented on code/game/machinery/iv_drip.dm
> +					beaker.reagents.trans_to(attached, 4)
lets be real here this + below transfer should really be faster, it's way better to just syringe blood into people

2017-01-20 22:25 UTC, Iamgoofball commented on code/game/machinery/iv_drip.dm
> +					for(var/datum/reagent/reagent in beaker.reagents.reagent_list)
istypeless loop this meme, if there's anything other than reagents in here you've got bigger problems

2017-01-20 22:25 UTC, Iamgoofball commented on code/modules/reagents/reagent_containers/blood_pack.dm
> +	if(reagents.total_volume == 0 && name != "\improper Empty Bloodback")
oh god why is the name checked at all here

2017-01-20 22:26 UTC, Iamgoofball commented
all of those issues with the goon sprite could probably be easily fixed with additional sprites

2017-01-20 22:27 UTC, Iamgoofball commented
although no real medics actually use IVs nowadays

2017-01-20 22:35 UTC, Exxion commented on code/modules/reagents/reagent_containers/blood_pack.dm
> +	if(reagents.total_volume == 0 && name != "\improper Empty Bloodback")
Don't pretend you haven't done that too

That said, it's still awful

2017-01-20 22:36 UTC, Exxion commented on code/game/machinery/iv_drip.dm
> +					for(var/datum/reagent/reagent in beaker.reagents.reagent_list)
The only meme here is typeless loops.

2017-01-20 22:41 UTC, 9600bauds commented on code/game/machinery/iv_drip.dm
> +					for(var/datum/reagent/reagent in beaker.reagents.reagent_list)
Goofball no goofing

2017-01-20 23:12 UTC, Iamgoofball commented on code/game/machinery/iv_drip.dm
> +					for(var/datum/reagent/reagent in beaker.reagents.reagent_list)
fugg

2017-01-21 07:52 UTC, Probe1 commented
>although no real medics actually use IVs nowadays

what

2017-01-21 08:01 UTC, Iamgoofball commented on code/modules/reagents/reagent_containers/blood_pack.dm
> +	if(reagents.total_volume == 0 && name != "\improper Empty Bloodback")
prove that I've done this

2017-01-21 08:01 UTC, Iamgoofball commented
IVs are shit-tier, use syringes

faster and deliver more blood

2017-01-21 13:30 UTC, PJB3005 commented
You clearly don't play on our server don't you?

2017-01-22 00:34 UTC, Iamgoofball commented
can't prove it

2017-01-22 06:07 UTC, merged

2017-01-22 20:16 UTC, Iamgoofball commented
FAKE NEWS, SAD!