Librarians now start with one additional language
d3athrow/vgstation13 pull request #13571
Opened 2017-01-21 08:37 UTC by JustSumBody

For obvious metagay reasons, restricted languages like mouse and cult are not included in the possible languages.

2017-01-21 08:42 UTC, 9600bauds commented
OK, better idea:
Random language books spawn in the middle of the 6000 doujins, you must spot the odd title out and read it to get your languages

2017-01-21 08:46 UTC, Probe1 commented
Anything to flesh out librarians ok

2017-01-21 11:06 UTC, PJB3005 requested changes

2017-01-21 11:06 UTC, PJB3005 commented on code/game/jobs/job/civilian.dm
> +			if(!(lang.flags & RESTRICTED) && !(lang in H.languages))
`~lang.flags & RESTRICTED` instead.

2017-01-21 13:30 UTC, PJB3005 approved these changes

2017-01-21 14:21 UTC, ComicIronic commented on code/game/jobs/job/civilian.dm
> +		to_chat(H, "Due to your well read nature, you find yourself versed in the language of [picked_lang].")
Better add how to use the language in question, for a new player.

2017-01-22 00:17 UTC, kilozombie commented on code/game/jobs/job/civilian.dm
> +		to_chat(H, "Due to your well read nature, you find yourself versed in the language of [picked_lang].")
Appears in 'known languages', not sure if that's really necessary.

2017-01-22 10:43 UTC, Skullyton commented
Does this check if you would already know the language?

2017-01-22 11:16 UTC, PJB3005 commented
@Skullyton yes.

2017-01-22 17:52 UTC, gbasood commented on code/game/jobs/job/civilian.dm
> +			if(~lang.flags & RESTRICTED && !(lang in H.languages))
I don't think `~` does what you think it does here

2017-01-22 17:56 UTC, gbasood commented on code/game/jobs/job/civilian.dm
> +			if(~lang.flags & RESTRICTED && !(lang in H.languages))
I'm wrong though

2017-01-22 17:56 UTC, gbasood approved these changes

2017-01-23 18:45 UTC, LemonTheFruit commented
But why can't we be the mice master librarian?

2017-01-23 19:06 UTC, AI-is-rogue commented
Mouse king sawbones, the librarian

2017-01-23 19:28 UTC, ihadtoregisterforthis commented
**squeek squeek, it's nukeops, they want to enter by the singularity, kill me so I can watch them and I'll be back in 5 minutes, admins are AFK, squeek\*\*

2017-01-23 19:30 UTC, LemonTheFruit commented
Well, they'll just eat a bannu for ock ick. Same concept as diona joining with a meta name, or ghosts pointing chairs at antags.

2017-01-23 23:13 UTC, merged