Adds a manual crank cell charger
d3athrow/vgstation13 pull request #13572
Opened 2017-01-21 12:35 UTC by JustSumBody

Revival of #4947
Constructable from an APC frame, metal rod, cables, and wirecutters
Insert a power cell and attack_self it to crank it for a whopping TEN WATTS per crank

Video: https://dl.dropboxusercontent.com/s/md3dytttf6o2iu6/2017-01-21_07-10-31.mp4

NOTE THAT FOR SOME REASON CRAFTING ONE MAKES TWO THIS IS NOT INTENDED AND I'M NOT SURE HOW TO FIX

Besides that, I guess it could do with construction sprites or an inhand but eh.

2017-01-21 12:59 UTC, yclatious commented
Even more ghetto tools, nice.

2017-01-21 13:22 UTC, PJB3005 commented
> watts per crank.

Basic physics class is that way ➡️

2017-01-21 13:26 UTC, PJB3005 requested changes

2017-01-21 13:26 UTC, PJB3005 commented on code/game/machinery/cell_charger.dm
> +		stored = W
This should check whether it's even possible to drop the item before actually storing it.

2017-01-21 13:26 UTC, PJB3005 commented on code/game/machinery/cell_charger.dm
> +/obj/item/device/crank_charger/Destroy()
This needs to do a super call.

2017-01-21 13:26 UTC, PJB3005 commented on code/game/machinery/cell_charger.dm
> +		stored.loc = user.loc
Put on hands should already handle this.

2017-01-21 13:56 UTC, SkowronX commented
This isnt how energy workssss REEEEEEEEEEE

2017-01-21 15:41 UTC, BobdaBiscuit commented
Would it be possible to have the lights on the frame indicate how charged the cell is, if it doesn't already?

2017-01-21 15:54 UTC, Kurfursten commented
@BobdaBiscuit It would be possible but only if someone sprited it

2017-01-21 16:54 UTC, Shadowmech88 commented
I think you need to add some sort of miniscule delay to the cranking, else people with autoclickers will be churning out a ton of power due to there being no delay on attack_self() by default.

2017-01-21 17:52 UTC, PJB3005 commented
There's a delay of one decisecond.

2017-01-22 00:23 UTC, kol1th commented
People use autoclickers?

2017-01-22 00:25 UTC, JustSumBody commented
>he doesn't use an autoclicker

2017-01-22 00:38 UTC, Intigracy commented
My mouse came with a button that automatically clicks 3x.

Welcome to the future.

2017-01-22 20:46 UTC, Exxion commented
Now that vaults exist and thus space exploration is actually relevant, this will be much more useful for charging spacepods on the go

2017-01-22 20:59 UTC, PJB3005 requested changes

2017-01-22 20:59 UTC, PJB3005 commented on code/game/machinery/cell_charger.dm
>  		user.drop_item(W,src)
Assuming that can't drop js the only thing that can make an item not be droppable is a very wild assumption.

2017-01-22 22:05 UTC, ComicIronic commented on code/game/machinery/cell_charger.dm
>  		user.drop_item(W,src)
It's also not encapsulated. You should just check the result of `drop_item`.

2017-01-22 22:07 UTC, gbasood commented
quality Metro 2033 gameplay

2017-01-24 01:36 UTC, Kitfox88 commented
jack in the boxes when

2017-01-24 16:23 UTC, PJB3005 approved these changes

2017-02-09 01:15 UTC, Probe1 commented on code/game/machinery/cell_charger.dm
> +/obj/item/device/crank_charger/Destroy()
@JustSumBody

2017-02-09 04:47 UTC, merged

2017-07-07 21:49 UTC, SonixApache commented
UPDATE WIKI