[WIP] Overhauls large artifact harvesting
d3athrow/vgstation13 pull request #13598
Opened 2017-01-23 03:05 UTC by BobdaBiscuit

The aim of this PR is to make working with anomaly batteries more robust so that secondary effects can be extracted, without any methods to cheese the system.

Current behaviour:
- Put artifact on the scanner
- Insert a battery
- Harvest
- The primary effect of that artifact magically goes into the battery, even if you don't know what it does

PR behaviour:
- Put artifact on the scanner and initialise the containment field
- Use the trigger of whatever effect you want in order to toggle the artifact
- Isolate the single effect you want
- Harvest
- The effect you selected is put into the battery, you have to have discovered it's trigger in order to do this

TODO:
- [ ] Make the containment field contain effects that don't use process()
- [ ] Detect the activation of effects that cannot be toggled, I/E single use on touch effects

2017-01-23 04:53 UTC, BobdaBiscuit commented
Tested everything sane I could, it all works.
Only real issue I've found is some effects can bypass the containment field as they don't use process(), ie forcefield. It shouldn't be a major issue.

2017-01-23 05:47 UTC, AI-is-rogue commented
So will this fix some artifact effects not doing anything in conjunction with the batteries?

2017-01-23 05:49 UTC, BobdaBiscuit commented
Due to PRs having to be atomic I haven't touched that, however it is on my shitlist of things to do right after if this gets merged.

2017-01-23 10:57 UTC, JMWTurner commented
Oh fuck yes

2017-01-23 21:58 UTC, BobdaBiscuit commented
On touch effects (eg harm, gas) are now blocked by the containment field.
Since they cannot be toggled, you have 10 seconds after triggering it to isolate the effect.

Working on blocking effects such as forcefield and darkness.

2017-01-27 13:41 UTC, PJB3005 requested changes

2017-01-27 13:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			spawn(100)
`10 SECONDS`

2017-01-27 13:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			spawn(100)
`10 SECONDS`

2017-01-27 13:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +				spawn(100)
`10 SECONDS`

2017-01-27 13:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +				spawn(100)
`10 SECONDS`

2017-01-27 13:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +	var/display_msg = "expells energy which is blocked by the containment field!"
Why is this not inside the `visible_message`?

2017-01-27 14:14 UTC, PJB3005 approved these changes

2017-01-29 07:20 UTC, N3X15 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			secondary_effect.ToggleActivate(2)
That argument smells like a magic number.  Given that the current proc signature is `/datum/artifact_effect/proc/ToggleActivate(var/reveal_toggle = 1)`, this should probably be made a `#define` so it's clearer what the difference between 0 and 2 are.

2017-01-29 07:21 UTC, BobdaBiscuit commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			secondary_effect.ToggleActivate(2)
Can I define it there? The idea is to differentiate between secondary and primary effects toggling, hence the numbers.

2017-01-29 07:29 UTC, N3X15 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			secondary_effect.ToggleActivate(2)
Nevermind then.

2017-01-30 15:08 UTC, merged