Audible Manual Screaming
d3athrow/vgstation13 pull request #13645
Opened 2017-01-25 19:55 UTC by Shadowmech88

Manually screaming with *scream now causes an audible scream.
If you *scream too much in a short time, you lose the ability to audibly scream for five minutes, to prevent constant, endless screaming.

:cl:
 * rscadd: Using *scream will now cause an audible scream. If you *scream too much in a short time, you lose the ability to audibly scream for five minutes.

2017-01-25 19:58 UTC, Probe1 commented
[spoiler]add a toggle for admins under secrets to disable the cooldown[/spoiler]

2017-01-25 20:01 UTC, Shadowmech88 commented
Like, disabling it globally? Or for a specific mob?
I'm not sure what the best way to do either would be.

2017-01-25 20:04 UTC, Probe1 commented
Its ok

2017-01-25 20:16 UTC, ihadtoregisterforthis commented
Does failing to scream have a flavor IC text, like throat irritation?
Do automated screams count for the scream cooldown?

2017-01-25 20:35 UTC, SkowronX commented
warning you this is a bad idea. Pretty sure paradise did this and it wasn't pretty

2017-01-25 20:35 UTC, JustSumBody commented
Screaming too much kills your vocal chords and makes you talk quietly for a bit.
FUND IT

2017-01-25 20:36 UTC, Shadowmech88 commented
No flavor text or other changes, you still do the emote the sound just doesn't play.
Automated screaming doesn't apply to the cooldown.

2017-01-25 20:42 UTC, Intigracy commented
Pretty sure Paradise's didn't have a cooldown.

2017-01-25 20:43 UTC, Intigracy submitted a review, later dismissed

2017-01-25 20:43 UTC, Intigracy commented on code/modules/mob/living/carbon/human/emote.dm
> +								var/list/screamSound = list('sound/misc/malescream1.ogg', 'sound/misc/malescream2.ogg', 'sound/misc/malescream3.ogg', 'sound/misc/malescream4.ogg', 'sound/misc/malescream5.ogg', 'sound/misc/w
These two lists should honestly just be global lists.

2017-01-25 20:49 UTC, yclatious commented
Do we really, actually want tg and hippie tier screaming shit to happen.

We already had the venting borg shit, do we actually want or need to have screaming greyshits or the clown screaming till they can't anymore because they got 3 minutes in the brig, anyone who slips to scream, people at maint just screaming for no good reason, its a meme ability, don't condone it.

2017-01-25 20:50 UTC, Shadowmech88 commented
"Screaming 'till they can't anymore" is four screams in a 30 second period, after which they can't scream for five minutes.
Doesn't seem so bad to me.

2017-01-25 20:56 UTC, yclatious commented
Just because it isn't horrible, non ending ear screeching doesn't mean it still isn't bad.

2017-01-25 21:00 UTC, JustSumBody commented
>Do we really, actually want tg and hippie tier

It keeps happening

2017-01-25 21:04 UTC, Intigracy commented on code/modules/mob/living/carbon/human/emote.dm
> +								var/list/screamSound = list('sound/misc/malescream1.ogg', 'sound/misc/malescream2.ogg', 'sound/misc/malescream3.ogg', 'sound/misc/malescream4.ogg', 'sound/misc/malescream5.ogg', 'sound/misc/w
Actually, they already are.

https://github.com/d3athrow/vgstation13/blob/b5f047bb965e55eaa1169a482b78a6bbabca404e/code/game/sound.dm#L15

2017-01-25 21:10 UTC, Intigracy commented
The obvious solution is to make it cause oxygen damage if you try while on cooldown.

2017-01-25 21:23 UTC, Lokiamis commented
I don't want to hear dudes screaming at me and I don't want to scream at dudes. Well, sometimes I do, but I'll just say "Ahhhh!".

2017-01-26 02:14 UTC, CptWad commented
I requested this

2017-01-26 03:50 UTC, Zth-- commented
No. Manual scream is cancer and gets old super quickly

2017-01-26 06:52 UTC, kol1th commented
@yclatious So once more your argument saying it's bad it "i don't like it fuck OFF hippie"?

You literally kill people for not listening to you or insulting you. Maybe you're the hippie reject.

2017-01-26 08:22 UTC, yclatious commented
If you think that everyone out there is living in the best place on earth and outside factors don't influence how people act, you are naive as hell kolith. Everyone makes dumb mistakes, and I admit making them and being a retard because of outside factors, doesn't make my opinion any less valuable.

Ive seen it, literally just a meme feature made to annoy people with audio screaming, would just get used when people slip, greyshits who dindunuffin and other dumb as hell moments, why am I not allowed to dislike a meme feature from meme servers that does nothing but annoy everyone? I don't want to screech, I don't want to hear screeching, I don't want to be screeched at a clown named Pepe or some shit, just because I did some questionable killings back when doesn't mean I can't post my opinion or that is it magically null.

2017-01-26 08:40 UTC, Shadowmech88 commented
>literally just a meme feature made to annoy people

Players could use it to attempt to call for help through opaque objects where played sounds will reach, but speaking won't.

2017-01-26 08:59 UTC, yclatious commented
Never got myself in a situation where that ever happened before, and if you already got your headset stolen or comms are down, you are probably screwed anyways, if you are stuck in some random place where there are no cameras for the AI to get you, no headset, no ability to get a radio or anything of the like, screeching probably won't help. Plus, how the hell did you get into a situation like that?

2017-01-26 10:32 UTC, ShoMek commented
I think this will still draw attention, so it's a nerf to all antags. Do you really want that to happen? 
Did you even consider that aspect?

2017-01-26 13:34 UTC, Probe1 commented
I don't understand how it's different from yelling help

2017-01-26 13:35 UTC, JustSumBody commented
Sound will go through walls, unlike the say message

2017-01-26 13:37 UTC, Probe1 commented
; help is less characters than *scream.  I'm not seeing it.

2017-01-26 14:12 UTC, Exxion commented
*scream works without a headset

2017-01-26 14:39 UTC, kol1th commented
God I just get dumber and dumber trying to understand you yclatious

You ruin prs by shitting them up with your shitty opinions

Hope you get permad soon, lad

2017-01-26 16:14 UTC, PJB3005 commented
Yet we have goon tier farting and everything is fine.

If it's really annoying revert it but otherwise 👍

2017-01-26 16:30 UTC, CptWad commented
what pbj said, it adds stuff not detracts, even if it is terrible we can remove it if its a problem

2017-01-26 16:39 UTC, ShoMek commented
@Probe1 
People are not paying attention to the chat 24/7.  If you are walking around and you see a maint door open and suddenly you hear a *scream, you'd notice it way faster than someone writing anything. You'd notice it instantly regardless of what you were doing. You wouldn't need to be staring at the chat. Sure, *scream will be used as a meme a lot too, but if you are a validhunter and you are roaming suspicious places, this will definetely help you.
Also, there are several players who use macros. This will be another tool for them as well.

2017-01-26 16:40 UTC, PJB3005 approved these changes

2017-01-26 19:12 UTC, Gef21 commented
*scream

2017-01-26 19:21 UTC, ThePlapatin commented
This is too far.

Shitty of coders to justify pushing bad changes because "if you don't like it just revert". We all are aware that they will not let a revert happen and if you try to get one then you're just a shitter that hates change.

This adds nothing good to the game, it's a nerf to antags that don't just instantly kill people, it'll be spammed and annoy players and there is no toggle to disable it.

2017-01-26 19:23 UTC, yclatious commented
I can't tell if this is the real plap or not.

2017-01-26 19:23 UTC, Gef21 commented
I hope it is

2017-01-26 19:36 UTC, Exxion commented
Calm down
This already has almost twice as many downvotes than upvotes
It's not getting merged unless some massive opinion shift happens. Or some dumbass merges it anyway. But I don't see that happening.

Also, try typing the word "revert" into the search bar if you think they never happen

2017-01-26 20:14 UTC, N3X15 commented
Closing at 8 for, 14 against., 2 meme

2017-01-26 20:15 UTC, Shadowmech88 commented
It's only been a day, I doubt all possible votes are in.

2017-01-26 20:18 UTC, SonixApache commented
This would've saved my ass in various situations where I was tied up in maint. A shame.

2017-01-26 20:27 UTC, ThePlapatin commented
It'd be even more no votes if left open for a few more days

2017-01-26 20:36 UTC, Shadowmech88 commented
There's no harm in waiting and seeing, is there?

2017-01-26 21:10 UTC, PJB3005 commented
I still think this PR is a good idea and you're all overreacting.

And fuck off with "reverts never happen". If they're not happening then who's to blame? The collabs who generally don't care that much or the angry shitters that are too lazy to revert a simple PR and would rather shitpost?

2017-01-26 21:18 UTC, ThePlapatin commented
"I still think this PR is a good idea and you're all overreacting."

That's nice, the players don't seem to agree though and N3X15 closed it. Keep the pr open until it's either winning in upvotes or people forget and you can merge eh pjb?  Before you get angry and call me a retarded thread shitter who has no understanding of the true art of coding I'd like it if you answered a question that nobody in this thread has answered yet.

How does this improve the game? How will this feature make the game more enjoyable for the playerbase?

2017-01-26 21:20 UTC, Zth-- commented
@PJB3005 You'll no longer know when someone is screaming because he's really dying or if it's the clown or an assistant fucking with you.

People will attach hotkeys to the fucking emote, making it less fun for everyone.

Roundstart? *scream *scream *scream *scream *scream *scream in every department.

More than 3 people in a room? *scream *scream *scream *scream *scream *scream

2017-01-26 21:20 UTC, PJB3005 commented
@ThePlapatin have you READ the conversation of this thread or are you just shitposting?

> or people forget and you can merge eh pjb?

* "Muh coder illuminati"
* Even if this thread was stale for 10 fucking years, as soon as it was merged everybody gets a loud bell. It wouldn't matter I merged it now or in 10 years.

2017-01-26 21:22 UTC, ThePlapatin commented
Yeah I've read it, I don't see any positive this feature brings. So I am asking (You) to enlighten me since you think it's a good idea.

If you like the idea, surely you can justify why you like it right?

2017-01-26 21:22 UTC, PJB3005 commented
@Zth-- yet we have farting and shit's fine.

Also you rarely scream when getting hurt anyways, maybe if you break a bone and if an observer can't see who broke a bone then they need to learn what situational awareness is.

2017-01-26 21:22 UTC, PJB3005 commented
@ThePlapatin I agree with most of the points others have brought up.

2017-01-26 21:23 UTC, Riekland commented
>yet we have farting and shit's fine.
![1441608328495](https://cloud.githubusercontent.com/assets/9220789/22350963/b49d3b34-e40d-11e6-9bff-9ca7fcdcd404.png)

2017-01-26 21:27 UTC, Zth-- commented
Yeah but farting is a complete different thing. Screams are louder, longer sounds that can and _**will**_ be used to powergame.

I'd really like this feature if we had a proper sound system, but we don't. You can't hear a low volume scream from the other side of maintenance. Or reverb. Or echoes. Our screams are obnoxious.

2017-01-26 21:28 UTC, Riekland commented
Just fucking remove sound from emotes that aren't *ping *buzz or *beep
Yes I mean *vocalize or whatever it is fuck that awful fucking emote it sounds like shit and ruins my imulshion

2017-01-26 21:30 UTC, ThePlapatin commented
The only actual point I read is "Can scream through walls"

Let me now list negatives that make this not worth it
>Antags now have a much harder time, can't kidnap a guy as he'll just spam scream 2 times every 30 seconds until he's rescued
>Shitters can and will abuse this to annoy players, after a few rounds since it's been merged there will be a clown running around doing *scream as often as he can without hitting cooldown
>It's not toggleable, you have to hear it even if you don't want to, you can mute admin sounds, the juke and what have you but you give the players a free tool to make annoying noise
>Nowhere is safe, you can scream through walls so not even autists hiding in telescience are free from the *scream if it goes off nearby
>This part is the slippery slope argument: By adding more sounds and removing the need to read the chatbox you encourage a more gameplay focused playstyle rather than a roleplaying and talking playstyle leading to a further casualization into a pvp server (this argument is pretty exaggerated)

2017-01-26 21:31 UTC, Riekland commented
Sounds are the gateway to the TG chatwheel
Mark my words, if we don't get rid of sound emotes we'll have it within the year

2017-01-26 21:36 UTC, Zth-- commented
Controversial tag please.

2017-01-26 21:40 UTC, PJB3005 commented
Centering things around the chat box is not a good thing. We need more audio and visual feedback everywhere.

2017-01-26 21:41 UTC, ThePlapatin commented
Alright and how about the others points that I didn't say were exaggerated for argument's sake?

2017-01-26 21:43 UTC, Riekland commented
>We need more audio and visual feedback everywhere.
Says who though?
I don't feel as though focusing on the bit where people can't actually explain shit to you is a terrible idea.
There are people who still can't manage to use punctuation in their say " for the love of god. You absolutely have to cater to the lowest kind of idiot to make sure that the server has at least some semblance of RP.

2017-01-26 21:43 UTC, yclatious commented
Audio and visual feedback is a alright idea, making it so we have unending meme screeching is not something I think fits in either of those, it fits in the annoying as shit and useless/powergamey category, but if you are trying to make things more intuitive in terms of audio and such, you have everywhere else to improve other than massive, retarded yelling.

2017-01-26 21:44 UTC, Iamgoofball commented
>Antags now have a much harder time, can't kidnap a guy as he'll just spam scream 2 times every 30 seconds until he's rescued

Or I could scream as an antag so people try to help me and I can bait them into traps.

>Shitters can and will abuse this to annoy players, after a few rounds since it's been merged there will be a clown running around doing *scream as often as he can without hitting cooldown

Have you considered beating people up who are being shitters? You have 50 billion different ways to kill people, use it.

>It's not toggleable, you have to hear it even if you don't want to, you can mute admin sounds, the juke and what have you but you give the players a free tool to make annoying noise
>>Have you considered beating people up who are being shitters? You have 50 billion different ways to kill people, use it.
Also you don't get to bring ~~friends~~toggles

>Nowhere is safe, you can scream through walls so not even autists hiding in telescience are free from the *scream if it goes off nearby

This could be fixed easily.

2017-01-26 21:45 UTC, Gef21 commented
I think it would be better if you could only use it once or twice before you can't use it for a while, and if the time before you could use it again was longer, since this would bring in the risk of not being able to scream while you're being killed because you were stood in medbay spamming your *scream macro ten minutes ago and would make people less likely to spam it

2017-01-26 21:45 UTC, Riekland commented
>This could be fixed easily.

Then why hasn't anyone made it so that sounds quieter than a gunshot don't pass through walls and airlocks?

2017-01-26 21:46 UTC, Iamgoofball commented
>Says who though?
I don't feel as though focusing on the bit where people can't actually explain shit to you is a terrible idea.
There are people who still can't manage to use punctuation in their say " for the love of god. You absolutely have to cater to the lowest kind of idiot to make sure that the server has at least some semblance of RP.

If you don't like how the codebase is run, here's a helpful infographic.
![capture](https://cloud.githubusercontent.com/assets/4081722/22351668/d853ae72-e3cd-11e6-9807-0511fb1b0696.PNG)

Have you considered that your opinion isn't the only opinion that matters on the subject?

2017-01-26 21:47 UTC, Iamgoofball commented
>Then why hasn't anyone made it so that sounds quieter than a gunshot don't pass through walls and airlocks?

Because not enough people have complained, and so no coders bothered.

2017-01-26 21:47 UTC, yclatious commented
You can't kill people for being shitters, your shithole may allow it without any restriction, but I know dang well that mindless killing of incompetent players is both not allowed and dumb as shit.

And despite it being able to be "fixed", its still a awful addition with a clear cut majority of people supporting it not being a thing. Its mindless shitty screeching that adds nothing, if you want to add audio feedback and such, you can do it in other ways than adding yelling. And you don't even play here goof, why do you think your opinion matters.

2017-01-26 21:50 UTC, ThePlapatin commented
>Or I could scream as an antag so people try to help me and I can bait them into traps.

This is alright, if not for the fact that you can do the same by shouting for help on common and it doesn't make a sound. Really a lot of players will investigate just to get them to shut up, not to actually help anyone.

>Have you considered beating people up who are being shitters? You have 50 billion different ways to kill people, use it.

Ah yes, turning the server into a pvp server. Here is the shitter's guide to free non-antag murder. 1) scream a lot 2) wait for somebody to attack you since goof said they can 3) retaliate and murder them, get away with it as it's self defence
Maybe just don't make problems that should be solved with murdering people. Maybe just don't add features that will cause admins a bunch of bother when the inevitable murder and crittings occur solely because of the feature existing.

>This could be fixed easily.

By fixing the scream going through walls, you thus remove the only advantage of scream. It's sole advantage is also it's biggest disadvantage. You either have an annoying scream everyone hates, or a silent regular scream emote.

>Have you considered that your opinion isn't the only opinion that matters on the subject?

Why do coders do this, of course people know their opinion isn't the only one that matters but they still wish to state their opinion. Why does your opinion matter goof, why does pjb's opinion matter enough to re-open the closed pr. Riekland plays a lot, I'd say their opinion counts for more than most people since they're active.

2017-01-26 21:51 UTC, Riekland commented
Nice
Epic
I like it
Tell me to stop complaining and do something and then tell me that nothing's been done because no-one complained
Truly ebin
Also, what yclat said, if you fucking beat people over spamming something you'll get a one way trip to the brig for assault/bwoinkland

2017-01-26 21:52 UTC, Iamgoofball commented
if you people aren't allowed to beat up nerds who are being obnoxious little shits do you just forward all punches to ahelps automatically or something?

2017-01-26 21:52 UTC, Iamgoofball commented
or do you guys do a shoot to miss style system

2017-01-26 21:52 UTC, Iamgoofball commented
also lol @ the deep and complex metagame of sound screams

this kills tactical screams

2017-01-26 21:52 UTC, ThePlapatin commented
Can everyone please not respond anymore to the goof, it's clear he cannot form a proper argument and is probably past his bedtime.

2017-01-26 21:53 UTC, Iamgoofball commented
this is true i haven't slept in a day

2017-01-26 21:53 UTC, Iamgoofball commented
idk what I'm doing arguing with 5 year olds who apparently are too much of pussies to put the boots to people who act like obnoxious assholes and need the coders/admins to solve their problems for them

2017-01-26 21:53 UTC, yclatious commented
We have quality players in a quality server, they get arrested or we stun and cuff them instead of killing them like every other shitter server, mindlessly killing people for being retarded isn't how shit is done when half the playerbase isn't slobering retards from reddit.

When a account named after a 13 year old spess player with issues is making more sense than you, I dunno good, maybe you should quit.

2017-01-26 21:53 UTC, Iamgoofball commented
please clap

2017-01-26 21:54 UTC, Iamgoofball commented
>We have quality players in a quality server, they get arrested or we stun and cuff them instead of killing them like every other shitter server, mindlessly killing people for being retarded isn't how shit is done when half the playerbase isn't slobering retards from reddit.

Then throw them in the brig, punish them in some IC way instead of just demanding the feature be removed. Make that emergent roleplaying experience over a trial because a guy wouldn't stop screaming in public.

2017-01-26 21:54 UTC, PJB3005 commented
> We have quality players in a quality server,

I disagree.

A lot.

If we did then this PR wouldn't have "muh meme scream" backlash now would it?

2017-01-26 21:55 UTC, Iamgoofball commented
also for reference yclatious is making some actual points here props to him

the "nice epic guy" is a shithead though

2017-01-26 21:56 UTC, Iamgoofball commented
@PJB3005 i think it's a problem of the playerbase's self control and their self control of their reaction to other's lack of self control

2017-01-26 21:57 UTC, PJB3005 commented
@Iamgoofball hooray you won the lotto and figured it out.

2017-01-26 21:57 UTC, ThePlapatin commented
>If we did then this PR wouldn't have "muh meme scream" backlash now would it?

Because coders insist on creating problems for players, the coders then complain that the players are not just dealing with it. Creating problems burdens admins and ruins rounds for players. This brings no benefit and solely negatives, why do you insist on causing problems and bringing no gain.

>idk what I'm doing arguing with 5 year olds who apparently are too much of pussies to put the boots to people who act like obnoxious assholes and need the coders/admins to solve their problems for them

see above comment

2017-01-26 21:58 UTC, PJB3005 commented
> Because coders insist on creating problems for players, the coders then complain that the players are not just dealing with it. Creating problems burdens admins and ruins rounds for players. This brings no benefit and solely negatives, why do you insist on causing problems and bringing no gain.

It does have gain you shit.

2017-01-26 21:58 UTC, yclatious commented
Except we know that this will literally make the rp standard we currently hold worse because some random greyshit thinks its funny to just scream all fucking day long. We don't need fuel to the fire, we don't want shit to make more arests, we don't need loud noises, we don't want loud fucking screaming.

We have fucking standards Goof. You might not, but for fucks sake, /vg/ does. We might not all be perfect, but we are not hippie, we are not a playerbase that never speaks, we are a playerbase that actually rps and interacts, we fucking try to keep a standard, to enforce min-med rp, we thrive better this way, fucking BlackPantsLegion loved the shit out of us because of our higher standards and he almost exclusively plays TG.

Quit adding shitty meme features that add nothing good to the game.

2017-01-26 22:00 UTC, ThePlapatin commented
>It does have gain you shit.

I've asked you time and time again PJB. If you're so set on having this added to the game, please clearly outline where this benefits players. It's not hard, it'd take two minutes at most. Just copy and paste points you think will benefit the game from other comments if you must.

2017-01-26 22:00 UTC, Iamgoofball commented
so giving the security players some extra stuff to do and therefore a longer playtime/investment and more enjoyability, and the potential for deeper RP such as the greytide assistant being put on trial for his screaming, deteriorates RP?

i argue that this creates RP not by the people screaming, but how the people react to the screaming

2017-01-26 22:00 UTC, PJB3005 commented
> rp standard

>> rp standard

>  we are a playerbase that actually rps and interacts

Are you out of touch or am I out of touch? Not even sure anymore honestly.

Our playerbase is consistent of powergaming shitters who can't help themselves and react violently to the slightest shit (see: design doc).

Are you for real right now?

2017-01-26 22:01 UTC, PJB3005 commented
> I've asked you time and time again PJB. If you're so set on having this added to the game, please clearly outline where this benefits players. It's not hard, it'd take two minutes at most. Just copy and paste points you think will benefit the game from other comments if you must.

See my other comment where I clearly outlined this.

2017-01-26 22:01 UTC, NigglyWiggly commented
Our server has more RP stuff than something like Goon, which _coincidentally_ also has scream verbs

2017-01-26 22:02 UTC, Riekland commented
>Our playerbase is consistent of powergaming shitters who can't help themselves and react violently to the slightest shit (see: design doc).

Your solution is, instead of waiting until the chaff is ding dong bannu'd to put in shit retards can use to be annoying, to just put it in whenever and hope for the best?

2017-01-26 22:03 UTC, PJB3005 commented
And farts.

And flips.

"we have a good playerbase" and "this will memely get abused" are mutually exclusive.

2017-01-26 22:03 UTC, Iamgoofball commented
@ThePlapatin 
pros:
more feedback for the game, makes characters feel more alive and real instead of being emotionless pawns we shuffle around and (e)rp with in the bar.
allows for that "scream for help" mechanic **but lets be real here no one's going to use it for that, and I'm in favor of the PR**
security now has another crime to bust people for and therefore more potential for legal RP via courts
cons:
greytide mcshitter will scream his heart out and security has to deal with him


HOWEVER

keep in mind that GreyTide McShitter is still probably going to be an obnoxious little shit regardless. If someone wants to be an obnoxious little shit, they'll find a way to be an obnoxious little shit screaming sounds or no.

2017-01-26 22:04 UTC, Intigracy commented
What part of "5 minute cooldown when spammed" are you guys not reading?

2017-01-26 22:04 UTC, Jeroen52 commented
"Before you get angry and call me a retarded thread shitter who has no understanding of the true art of coding I'd like it if you answered a question that nobody in this thread has answered yet.

How does this improve the game? How will this feature make the game more enjoyable for the playerbase?" - @ThePlapatin 
You are either dishonest or you haven't read this PR properly.

"Sound will go through walls, unlike the say message" @JustSumBody

That is one answer to your question. Sometimes people get kidnapped and stripped of their headset and succ'd somewhere in maint. You can `say` all you want but text doesn't go through walls. However a *scream is audible from the other side of the wall.

2017-01-26 22:04 UTC, Riekland commented
> security now has another crime to bust people for and therefore more potential for legal RP via courts

YOU FUCKING RETARD
ON THE RARE OCCASION THERE IS A TRIAL, IF WE NEED TO FUCKING GAG THE CRIMINAL BECAUSE THEY WON'T STOP SCREAMING IT'S JUST GOING TO CAUSE MORE ISSUES
SEE: EVERY FUCKING TRIAL WITH A BORG PRESENT

2017-01-26 22:04 UTC, Iamgoofball commented
also yes what @Intigracy said, there's a 5 minute cooldown so you can't even spam it

2017-01-26 22:05 UTC, NigglyWiggly commented
Goofball you just keep talking about how if someone is screaming a lot you should just beat the shit out of them or kill them or arrest them.
Screaming isn't a crime or valid, it's just fucking annoying

2017-01-26 22:05 UTC, Iamgoofball commented
@Riekland 
Then gag them. What more issues will it cause?

Also, borgs and AIs are shit and i hate the core design just saying

2017-01-26 22:05 UTC, ShoMek commented
May I suggest we stay on topic? 

> Our playerbase is consistent of powergaming shitters 

@PJB3005 So why do you think this PR is a good idea then? 
Clearly this will benefit shitters who powergame and/or just validhunt, which means antags being nerfed. 

I do think people will try to annoy everyone with the feature, but I think the validhunters/antag issue is way more important.

2017-01-26 22:06 UTC, ThePlapatin commented
>i argue that this creates RP not by the people screaming, but how the people react to the screaming

Roleplay does not need gameplay mechanics to be added to create roleplay. Roleplay is a mindset that is seperate from the game, it just needs a decent setting and others that will engage.

>See my other comment where I clearly outlined this.

You basically said from what I can see by ctrl + f on your name
"adds more audio and visual feedback"
You yourself said basically no benefit, and I'd say that the negatives outweigh the positives you have posted.

>What part of "5 minute cooldown when spammed" are you guys not reading?

Four screams in 30 seconds invokes the cooldown. I can scream 3 times in 30 seconds and be fine, I can scream once every 10 seconds forever. How is that not bad?

2017-01-26 22:06 UTC, Iamgoofball commented
@NigglyWiggly 
People in this game across ALL servers often commit crimes all the time, but the only crimes they get arrested for are the ones that are super fucking annoying(like killing people, breaking and entering, or theft).

2017-01-26 22:06 UTC, yclatious commented
Much like a shitty unclean station causes more chaos, endless shitty noise and audio griff makes people behave differently. You think a sec officer beating the shit out of a greyshit who is constantly screaming ir rp, or even good rp? Get a grip goof.

Im not out of touch PJB, you seem to be. I actively do a accent, I actively participated in gimmicks, Ive talked in bars, Ive tried out personalities, Ive chilled in bars, Ive talked to vox, to think its all nothing but endless hippie trash is nonsense, you haven't seen that shitpile. Your design doc was shit and was apropriately responded with hatred because it fucked everything up, if you still can't deal with people shitting on you for that, shame.

More feedback for the game? A yelling retard is not more feedback. Makes characters feel more alive and real instead of being emotionless pawns? Mate, a screeching retarded verb for audio annoyance will not do that. More crimes for sec to get pissed at, woo, thats always a plus, ain't it good?

If somebody wants to be obnoxious, let him, but don't make him screech like a retarded vox. I like my dang ears to be functional.

2017-01-26 22:06 UTC, Intigracy requested changes

2017-01-26 22:06 UTC, Intigracy commented on code/modules/mob/living/carbon/human/emote.dm
> +								var/list/screamSound = list('sound/misc/malescream1.ogg', 'sound/misc/malescream2.ogg', 'sound/misc/malescream3.ogg', 'sound/misc/malescream4.ogg', 'sound/misc/malescream5.ogg', 'sound/misc/w
I misread, you still need to do this.

2017-01-26 22:06 UTC, Riekland commented
> Then gag them. What more issues will it cause?

THE SAME AMOUNT OF ISSUES IT ALWAYS DOES
The fucking point is that we don't need ANOTHER reason to gag people

2017-01-26 22:07 UTC, Iamgoofball commented
I asked you what the reasons were and you just said that it causes issues again.

State the actual reasons please.

2017-01-26 22:07 UTC, PJB3005 commented
Also if being able to hear through walls (which I want to code anyways like on goon) is such an issue because you can be saved really quickly by powergamers that drop everything to get valids, is it an RP?

2017-01-26 22:09 UTC, yclatious commented
We gain literally nothing from adding this.

We get more retarded shitters being annoying, sec being even more pissed and being yelled at even louder, even worse rp standards, more validhunting, we all get a nice dose of ear schreeching goodness after someone is slipped or if they simply don't get what they want like a retarded manchild, what, audio feedback, from a retarded as fuck player who is actively so upset they make sure you hear a ingame screech?

For fucks sake, this is a joke.

2017-01-26 22:09 UTC, PJB3005 commented
> Your design doc was shit and was apropriately responded with hatred because it fucked everything up, if you still can't deal with people shitting on you for that, shame.

Oh hey throwing ideas into the wind isn't allowed anymore. Nice tolerant playerbase you've got there.

> Im not out of touch PJB, you seem to be. I actively do a accent, I actively participated in gimmicks, Ive talked in bars, Ive tried out personalities, Ive chilled in bars, Ive talked to vox, to think its all nothing but endless hippie trash is nonsense, you haven't seen that shitpile. 

This happens on every fucking server, even goon.

Goon's RP atmosphere is actually quite enjoyable from what I've heard when RP does happen.

> If somebody wants to be obnoxious, let him, but don't make him screech like a retarded vox. I like my dang ears to be functional.

People have always had ability to be obnoxious as fuck. Spamming the fucking sound synth for example. Does it happen? No.

2017-01-26 22:09 UTC, Jeroen52 commented
Kind of odd that in a server where players have the stereotype that they constantly try to get dem valids, they pass on one of the best methods to get the valids just out of spite of other codebases.

2017-01-26 22:10 UTC, Riekland commented
THE REASON IS THAT IT CAUSES ISSUES
THE PROS DO NOT OUTWEIGH THE CONS IN THE EYES OF THE LAW

2017-01-26 22:11 UTC, PJB3005 commented
> We gain literally nothing from adding this.

I disagree

> We get more retarded shitters being annoying, sec being even more pissed and being yelled at even louder, even worse rp standards, more validhunting, we all get a nice dose of ear schreeching goodness after someone is slipped or if they simply don't get what they want like a retarded manchild, what, audio feedback, from a retarded as fuck player who is actively so upset they make sure you hear a ingame screech?

If people are actually being obnoxious enough to fuck your ears up I'm sure the admins agree with a good beating.

> Kind of odd that in a server where players have the stereotype that they constantly try to get dem valids, they pass on one of the best methods to get the valids just out of spite of other codebases.

The people that go to GitHub try to pretend they're not part of that group.

2017-01-26 22:11 UTC, NigglyWiggly commented
>Oh hey throwing ideas into the wind isn't allowed anymore. Nice tolerant playerbase you've got there.

I imagine the reason so many people got upset about the design doc stuff was because they assumed it was some kind of plan for the future of the server, instead of just potential concepts for stuff in the future.

2017-01-26 22:12 UTC, Iamgoofball commented
>THE REASON IS THAT IT CAUSES ISSUES

What. Are. The. Issues.

2017-01-26 22:13 UTC, PJB3005 commented
@Iamgoofball you're feeding a troll I think.

2017-01-26 22:13 UTC, Iamgoofball commented
fuck

2017-01-26 22:13 UTC, yclatious commented
There is a difference between getting ideas out there and all of them being god awfull pjb. People reacted that badly because they were fucking awfull and broke balance.

Yeah, it happens in every server. It happens here too, in bigger ammounts than you think.

Synth sound maker is rectricted to clowns and mimes, you give everyone their portable, hand free and instant sound synth and you can bet a clowns ass itl be used.

No PJB, killing people for being annoying is not acceptable. SETTING THE STANDARD TO THAT IS EVEN FUCKING WORSE. Jesus christ, its like you want your make believe server that is filled with nothing but hippie tier retards to actually come true by enabling shitter shit.

2017-01-26 22:14 UTC, Riekland commented
>What. Are. The. Issues.

>ON THE RARE OCCASION THERE IS A TRIAL, IF WE NEED TO FUCKING GAG THE CRIMINAL BECAUSE THEY WON'T STOP SCREAMING IT'S JUST GOING TO CAUSE MORE ISSUES

The issue here is you can't have good RP if you have a defendant who can't defend himself
We NEVER, NEVER have lawyers, so don't shit out the excuse that they can speak for them

2017-01-26 22:14 UTC, Fruktlimpa commented
We can scream(heh) at each other here all day but in the end this shit should not be merged with the current votes. 
No point in having this circular argument party because everything that wanted to be said has been said.

Just honor the fucking reddit upvote system and it is fine.

2017-01-26 22:15 UTC, PJB3005 commented
> There is a difference between getting ideas out there and all of them being god awfull pjb. People reacted that badly because they were fucking awfull and broke balance.

No, there is not. The ideas were far from being implemented if it would even come to that.

> Synth sound maker is rectricted to clowns and mimes, you give everyone their portable, hand free and instant sound synth and you can bet a clowns ass itl be used.

It's left in the theatre most of the shifts I've seen and nobody would bat a fucking eye if you welder your way into that pla-

Welp

2017-01-26 22:16 UTC, N3X15 commented
This has become a discussion beyond discussion of the merits of the PR or any issues with its code.

Locked until both sides can calm their tits.

2017-01-26 22:21 UTC, PJB3005 commented
Whatever I give the fuck up.

2017-01-26 23:09 UTC, N3X15 commented
Unlocked and reopened.  After discussion in Discord, the cutoff period will be on Monday at 12AM GMT.  Discussion should remain about this PR and shall remain civil or I will non-surgically embed my foot in your descending colon.

2017-01-26 23:13 UTC, SonixApache commented
Potential for abuse by shitters is large. Of course there could just be IC and OOC repercussions for being a massive screaming faggot, but either way. Not to mention it would fuck over antags pretty easily.
If it only had two tiles range, didn't penetrate walls and was usable only once per minute it might not be so bad, but if something as neutered as that is even still worth adding? I just don't know.

2017-01-26 23:14 UTC, Shadowmech88 commented
To those who voted :-1: on this PR, would it change your mind if the cooldown between screams or as a result of too much screaming was increased, to any degree?
Please answer via :+1: / :-1: on this post.

2017-01-26 23:17 UTC, Intigracy commented
I still think people who scream too much should take oxy damage or be mute to the point of whispering for a time.

2017-01-26 23:44 UTC, TheFriggenSawbones commented
Sore throats caused by screaming, only curable by nice tea. Gives you some dumb fucked up font.

2017-01-26 23:49 UTC, TheFriggenSawbones commented
@ThePlapatin you're evading against aren't you

2017-01-26 23:51 UTC, Shaska- commented
Other than it being obnoxious, I find screams to be a good indicator that something is wrong, whether that is someone has a broken hand and needs surgery or someone being slaughtered in maintenance. If everyone can just scream on command, we'd quickly be desensitized to people screaming and learn to ignore it, rather than act on it. If it does end up being added, I think it at least should have a unique sound, rather than the same ones used for pain.

2017-01-27 00:14 UTC, TheFriggenSawbones commented
@ThePlapatin are you ban evading again

2017-01-27 01:15 UTC, JustSumBody commented
>emoji-ocracy
lel

2017-01-27 03:02 UTC, Jeroen52 commented
@JustSumBody It is emoji-cracy you troglodyte.

2017-01-27 04:54 UTC, 9600bauds commented
![dance](https://cloud.githubusercontent.com/assets/6526157/22360923/810606f4-e433-11e6-8076-696f2fa2b562.gif)

2017-01-27 07:09 UTC, SarahJohnson489 commented
If you devalue screams nobody cares which defeats the purpose

2017-01-27 08:19 UTC, SangriaMonkey commented
If you incorporated some kind of cooldown and alternative non-painful scream sounds, maybe.

2017-01-27 09:25 UTC, SarahJohnson489 commented
Yeah, a drastically different scream would be alright.

2017-01-27 10:09 UTC, Shadowmech88 commented
What screams exist that don't sound fearful/painful like our current screams?

2017-01-27 16:39 UTC, Exxion commented
@SangriaMonkey There's already a cooldown
Maybe read the whole OP

2017-01-27 22:30 UTC, SangriaMonkey commented
Easy killer. I think it'd be funnier if you could knock yourself out with oxygen damage by spam-screaming but this probably isn't getting merged either way.

2017-01-27 23:21 UTC, Exxion commented
That would be pretty funny, but as far as I know oxygen damage can't knock you out other than by critting you
Which is... probably kind of shitty

2017-01-28 02:15 UTC, Rattlederp commented
I think its important to quote goofball on his own meme pull request on the tgstation git, for the sake of discussion of course
![meme](https://cloud.githubusercontent.com/assets/12190187/22393506/c8ad9cea-e4d5-11e6-8646-83bc1236b3e7.PNG)

2017-01-28 04:05 UTC, Exxion commented
Honestly? Not a whole lot more
We are in dire need of a remake that actually gets somewhere

2017-01-28 06:37 UTC, Shadowmech88 commented
* Players may now audibly scream an absolute maximum of once per minute.
* If a player audibly screams as frequently as three times in four minutes, they lose the ability to scream audibly for ten minutes.

2017-01-28 08:06 UTC, Intigracy approved these changes

2017-01-28 18:04 UTC, ShoMek commented
@PJB3005 says:

> Our playerbase is consistent of powergaming shitters

This will only benefit players who powergame and validhunt non-stop, this is an antag nerf.
So how come you think this will be good for the game?

It will certainly be used to annoy as well, of course, and even if I think that'll be an issue, I worry way more about the antag nerf point.
And I do think we need more audio/visual feedback, but I see this as a balance issue, which of course requires more discussion.

I mean, even if this was an ideal place and *scream would ONLY be used in a proper sceneario, would you really want that extra layer of difficulty for antags? Now consider that this is NOT an ideal place, people will turn it into a meme regardless of the cooldown, people WILL use it to powergame/validhunt (probably with macros too), and now answer the same question. This is what we should be talking about.

I mean, c'mon, here's a real quote of the people who want this PR to get merged, which was meant to be an answer to a valid point AGAINST the PR:

> It does have gain you shit

Nothing else.

2017-01-28 18:14 UTC, PJB3005 commented
@ShoMek Can you actually fucking read what I said?

I think the points proponents have brought up are valid and correct. Period.

Why do you go and assume that my points are voided by all your arguing? I stand by my points and think that your counter arguments are stupid. Period.

2017-01-28 18:26 UTC, ShoMek commented
@PJB3005 I read all of your posts.
I can safely say you don't know how to properly discuss anything, as the most far you can go is:
«I think you are wrong and you are overreacting». Without, of course, giving any real counter-argument.

Like you did just now.

I mean, I did try to bring up balance discussions, but you completely ignored it. Thankfully it won't matter as this PR will never get merged.
Go ahead, keep ignoring everything and arguing about personal stuff.

2017-01-28 18:37 UTC, SkowronX commented
PR is still dumb

2017-01-28 18:39 UTC, PJB3005 commented
@ShoMek I have brought up my points and said I don't think your counter arguments are correct. Period.

That's all.

If you want me to pull arguments out of my ass and make myself look like an idiot just so this conversation keeps going on, no.

2017-01-29 09:26 UTC, ThePlapatin commented
imagine all those changeling rounds with 0 genomes or vamp rounds with no blood that already happen, now imagine even stunning and removing their headset can't stop them from calling for help.

Every round is a 0 genome changeling round, a dark dark time.

2017-01-29 17:51 UTC, Exxion commented
Calling for help in a radius of like 5 tiles without a name being attached

2017-01-29 21:02 UTC, ThePlapatin commented
There's plenty of public places where murder occurs that a scream could save your life or at least get you cloned.
Bar backroom, kitchen coldroom, captain's office, iaa's office, maint pretty much anywhere.
A call for help even without a name attached is still a lot more than nothing, tricky pen sales will go through the roof if you have to put someone to sleep just to stop them getting you caught.

2017-01-30 00:15 UTC, N3X15 commented
Monday, 12AM GMT:  13 :+1:, 22 :-1:, 4 meme

2017-01-30 00:15 UTC, closed without merging