Fixes supermatter not consuming simple mobs inside simple mob holders
d3athrow/vgstation13 pull request #13646
Opened 2017-01-25 20:10 UTC by jknpj

Also stop people from power from holders.

:cl: 
 * bugfix: Fixes a bug with supermatter not consuming simple mobs being hold by humans

2017-01-25 20:11 UTC, PJB3005 commented
I disagree with the way this is implemented.

Deletion of the holder without context should delete the contained mob no questions asked. All code like dropping holders should just take care to eject the mob beforehand so that doesn't happen.

2017-01-25 20:13 UTC, AI-is-rogue commented
>being hold by humans

 👌

2017-01-27 19:45 UTC, N3X15 requested changes

2017-01-27 19:45 UTC, N3X15 commented on code/modules/supermatter/supermatter.dm
> +
This whole thing is a bit too snowflakey for me.  The holder is the one that has the odd behaviour, and it should be the one to perform whatever steps are needed to correct any weird shit that happens when it's deleted.  For example, moving this logic to Destroy().

2017-01-27 19:45 UTC, N3X15 commented on code/modules/supermatter/supermatter.dm
> +			Consume(H.stored_mob)
Same here.

2017-01-27 19:45 UTC, N3X15 commented on code/modules/supermatter/supermatter.dm
> +			return
Immediately after this block, it calls qdel anyway.  There should be a istypeinlist() check afterward that which returns on match, or sets the power modifier from 200 to 0, or whatever tickles your fancy.

2017-02-03 17:17 UTC, jknpj commented
I'll see if i can do something about this messing with holders, not with supermatter

2017-02-03 17:17 UTC, closed without merging