Banannon
d3athrow/vgstation13 pull request #13658
Opened 2017-01-26 21:49 UTC by Shadowmech88

![banannon_full](https://cloud.githubusercontent.com/assets/3991927/22351640/7ec0bb96-e3de-11e6-814a-d063cb374763.png)

Adds the banannon, a new weapon for traitor clowns. It can be bought for 13 TC.
The banannon fires armor-piercing discarding sabonanas, which deal 30 damage by default. In flight they drop their peel, on average about 4-5 tiles from the shooter, which increases their damage to 60 and spawns a banana peel on that tile.
The banannon holds 10 shots, and can be reloaded with bananas.

:cl:
 * rscadd: Added the banannon, a new gun for traitor clowns.

2017-01-26 21:52 UTC, Skullyton commented
>Giving the clown a banana rail gun
>That's purchasable using default traitor-level TCs

I know it's supposed to be an alternative to the revolver for clowns, but a 10 round magazine that actually does more damage the further away the target is, and can be reloaded using regular grown bananas

What the crap

2017-01-26 21:53 UTC, Shadowmech88 commented
What cost do you suggest?

2017-01-26 22:00 UTC, Skullyton commented
Max + the TC increase from being on the roundstart report

Only those clowns who are willing to go above and beyond may get the banannon

2017-01-26 22:01 UTC, Shadowmech88 commented
The average clown doesn't even have access to a steady supply of bananas, though.
It'd be tougher for them to refill it than for a traitor to refill a revolver.

2017-01-26 22:05 UTC, Aurx commented
You can get bananas 9/10 rounds if you actually try.  
You can also get plant bags full of bananas.  Hundreds of bananas.  All in your backpack.  

As is, this is massively better than the revolver due to effortless access to ammo, larger magazine, and the creation of peels.

2017-01-26 22:05 UTC, Skullyton commented
Ghetto botany?

Actual botany, then buy the banannon when you've got a full bag of nanas?

2017-01-26 22:08 UTC, Aurx commented
Upon review of the code, this appears to be usable by non-clumsy individuals.  

Please rectify this most pressing issue, posthaste.

2017-01-26 22:16 UTC, Lokiamis commented
60 damage after 4-5 tiles is fucked up

2017-01-26 22:19 UTC, Shadowmech88 commented
It's the same amount of damage that standard bullets deal at all distances.

2017-01-26 22:22 UTC, Kitfox88 commented
shadow the fact that you implemented my shitpost makes me happy

2017-01-26 22:25 UTC, SonixApache commented
is it APFSDS or APFSDS-T?

2017-01-26 22:47 UTC, Ephx1 commented
There have literally been dozens of rounds where the botanists call me out of nowhere to give me a truckload of bananas. On top of that it's piss easy to grow your own with little to no effort.

2017-01-26 22:51 UTC, Kurfursten commented
Doesn't the clown already have like four traitor items?

There are several jobs that have no specific traitor item - Chaplain, Paramedic, Trader, Virologist, Scientist, Captain, Head of Personnel...

2017-01-26 22:56 UTC, SonixApache commented
IMO; keep it in, but for clownsquad bus shit rather than as a trator item.

2017-01-26 23:23 UTC, Shadowmech88 commented
* Banannon price increased to 18 TC
* The clumsy check for the banannon is now inverted, non-clumsy users have a 50% chance of the gun exploding in their hands.

2017-01-27 01:40 UTC, calzilla1 commented
Make it NODROP, play bannana man globally when bought,  and stop when the clown dies

2017-01-27 12:06 UTC, PJB3005 requested changes

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +	if(flag)
Or, you know, you're trying to point-blank somebody.

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +/obj/item/weapon/gun/banannon/afterattack(atom/A as mob|obj|turf|area, mob/living/user as mob|obj, flag, params, struggle = 0)
No `as xxx`

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +	if(Fire(A,user,params, "struggle" = struggle))
BYOND even fucking *allows* named arguments to be passed as strings? Jesus

Remove the quotes.

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +/obj/item/weapon/gun/banannon/Fire(atom/target as mob|obj|turf|area, mob/living/user as mob|obj, params, reflex = 0, struggle = 0, var/use_shooter_turf = FALSE)
Remove `as xxx`

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +			to_chat(M, "<span class='danger'>[src] blows up in your face.</span>")
`\the [src]`

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +			M.drop_item(src, force_drop = 1)
Done by `qdel`, don't bother.

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +	if(in_chamber)
so, `return in_chamber`?

2017-01-27 12:06 UTC, PJB3005 commented on code/modules/projectiles/guns/projectile/banannon.dm
> +		user.drop_item(W, force_drop = 1)
How would you insert a banana into the gun if the banana is stuck to your hand? Why force this?

2017-01-27 16:37 UTC, Exxion commented on code/modules/projectiles/guns/projectile/banannon.dm
> +			to_chat(M, "<span class='danger'>[src] blows up in your face.</span>")
`\The`*

2017-01-27 19:35 UTC, Shadowmech88 commented
Conflicts fixed.

2017-01-27 21:17 UTC, yclatious commented
https://www.youtube.com/watch?v=yModCU1OVHY

Banana man when

2017-01-27 21:26 UTC, PJB3005 approved these changes

2017-01-28 14:22 UTC, merged