Adds a medical swimsuit to the fitness locker, sprited by anonymous
d3athrow/vgstation13 pull request #13671
Opened 2017-01-27 18:23 UTC by Gef21

title says it all really

http://i.imgur.com/1g6h2wQ.png
http://i.imgur.com/GMoLRxk.png
http://i.imgur.com/49XBJ6B.png
http://i.imgur.com/6oh4V51.png

🆑 
 * rscadd: Added a medical swimsuit to the fitness locker

2017-01-27 18:31 UTC, PJB3005 requested changes

2017-01-27 18:31 UTC, PJB3005 commented on code/modules/clothing/under/miscellaneous.dm
> +/obj/item/clothing/under/medicalswimsuit
There already seems to be an `/obj/item/clothing/under/swimsuit`, could you change this to that?

2017-01-27 18:31 UTC, PJB3005 commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "A fancy swimsuit with a similar colour scheme to that of the medical department"
Period here.

2017-01-27 18:39 UTC, Gef21 commented on code/modules/clothing/under/miscellaneous.dm
> +/obj/item/clothing/under/medicalswimsuit
done and tested

2017-01-27 18:39 UTC, Gef21 commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = "A fancy swimsuit with a similar colour scheme to that of the medical department"
done

2017-01-27 18:42 UTC, Exxion commented
Looks more like the CE hardsuit than medical

2017-01-27 18:56 UTC, PJB3005 approved these changes

2017-01-27 20:20 UTC, aceedex commented
It's paramedic colors I think

2017-01-27 21:30 UTC, clusterfack commented
You can directly include images into your posts by doing ! [] (link)

2017-01-27 21:34 UTC, PJB3005 commented
Without spaces of course.

2017-01-28 01:37 UTC, TheFriggenSawbones commented
NO

2017-01-28 01:39 UTC, JustSumBody commented
beach map when

2017-01-28 01:39 UTC, kol1th commented
Delete this pr right now.

2017-01-28 01:49 UTC, SonixApache commented
what the fuck is this

2017-01-28 02:08 UTC, Exxion commented
There we go
I was wondering when the complaining would start

Surprised it took that long

2017-01-28 02:15 UTC, Shadowmech88 commented
Kind of strange how it came all at once within the span of half an hour.

2017-01-28 02:28 UTC, clusterfack commented
It's almost as if there is some place where people congregate, and a group that uses in some meta fashion that acts in a uniform manner to influence public opinion.

2017-01-28 03:38 UTC, jakmak5 commented
waifupandering/10

2017-01-28 14:05 UTC, Probe1 commented
Change it to underwear and I might merge it.

2017-01-28 20:20 UTC, Gef21 commented
I have no idea how to do that and the emojicracy don't like this so I'm just gonna close it

2017-01-28 20:20 UTC, closed without merging