Holodeck update
d3athrow/vgstation13 pull request #13672
Opened 2017-01-27 18:33 UTC by Lokiamis

Preview: https://webmshare.com/WJEbK

+Expanded to 11x10 (up from 5x10) on Box and Meta
+All of the older holodeck rooms have been expanded to match new dimensions. 
+Windows are tinted and doors have been switched to prevent most light from bleeding in and give the holodeck privacy. Very immersive if you keep your flashlights off. 
+8 new holodeck rooms have been added
+Wired the radioactive death transmitter machine in Box maint because Kurf told me to
-Ghetto theater on Box had to be cut. What space was left has been reworked. Nothing major from other stations were lost.
-Deff will be a separate PR since Probe is 2slow, so the holodeck will look goofy if this is merged by itself. It won't break the map(I hope), the new rooms just won't fit the holodeck properly.
-There are almost certainly new material farming exploits to be found and fixed. Pretty sure you can't grab anything rare, like wood.

![box](https://cloud.githubusercontent.com/assets/25004372/22382586/a82e4688-e49c-11e6-8466-a6bf4b04a64f.png)

![meta](https://cloud.githubusercontent.com/assets/25004372/22382589/abe89a76-e49c-11e6-8f80-0f4eebc691dc.png)

:cl: 
 * rscadd: Holodeck updated

2017-01-27 18:44 UTC, Ephx1 commented
AI Hologram implementation 2017

2017-01-27 18:46 UTC, Lokiamis commented
@Ephx1 law 2 join my basketball team

2017-01-27 18:55 UTC, PJB3005 commented
Could you shuffle around the walls so that double walls like this are gone? They look really bad in game.

![](http://i.imgur.com/S783j5X.png)

2017-01-27 19:09 UTC, ultraplen commented
rip ghetto theatre. I´ve never ever seen it used but it had potential.

2017-01-27 19:59 UTC, Lokiamis commented
@PJB3005 
![111](https://cloud.githubusercontent.com/assets/25004372/22385550/7be5f1b8-e4a9-11e6-8d61-1cde54b06090.png)

2017-01-27 20:12 UTC, Ephx1 commented
I'm curious as to why you kept the viewing area south of the holodeck on box since it's all tinted windows now.

2017-01-27 20:14 UTC, Shadowmech88 commented
Once I *eventually* get around to fixing one-way windows that area could be used to see in to the holodeck without allowing people inside the holodeck to see out.

2017-01-27 20:19 UTC, Aurx commented
I don't like the airlock sprite that was chosen.  That icon is synonymous with retro-areas like tcommsat, which I don't feel to be a fitting association.  
I think the standard grey with green stripe airlock would fit better, or maybe the stark-white one.

2017-01-27 20:22 UTC, Lokiamis commented
@Ephx1 As a hazard and as a window to space, like the 3 above the bridge. While you can't see in, you can still see if there's activity inside by the lighting.
@Shadowmech88 That'd be good. You can see through tinted windows if you're right next to them, but only if there's one on the tile.
@Aurx I'll throw some grey/greens in.

2017-01-29 16:08 UTC, CptWad commented
got a few photos of what the new holospaces look like?

2017-01-29 21:35 UTC, PJB3005 commented
You know we could probably enable lighting on the holdeck. I think the area copying code it uses is awful though and fucks up lighting.

2017-01-29 23:54 UTC, Lokiamis commented
Old
![old](https://cloud.githubusercontent.com/assets/25004372/22409174/15b7961c-e65c-11e6-828e-bd655c89ae44.png)
New
![new1](https://cloud.githubusercontent.com/assets/25004372/22409175/1859a7de-e65c-11e6-80cc-3c2d64886d0f.png)

![new2](https://cloud.githubusercontent.com/assets/25004372/22409177/1b8fa3e0-e65c-11e6-85d9-15698522866f.png)

![new3](https://cloud.githubusercontent.com/assets/25004372/22409179/1e4bb8a8-e65c-11e6-94a1-64423a766c36.png)

![new4](https://cloud.githubusercontent.com/assets/25004372/22409181/20d8fb4e-e65c-11e6-92bd-c952fe2f5b5d.png)



Things I'm not happy with
-The "space" room still looks like shit. Would be nice to get properly animated/scrolling space tiles
-The "meeting room" carpeting is shit. Think it's missing pieces or something because I couldn't get the edges to blend well
-"Theater" room costumes will have to be hand placed until #13669 is fixed. Instruments that spawn in the holodeck don't work for some reason, but instruments you take into the room from elsewhere will. Had to axe the piano for this reason.
-Couldn't get linked machines to work for some reason. Specifically an airlock with a bolt switch in the rage cage. Didn't try a range target device for this reason
-Tajarans in the "zoo" room don't spawn with the abhorrent furry snowflake names I gave them, just show up as Unknown
-Holo windoors would be nice. I tried and failed to add these.

@PJB3005 What's wrong with the lighting?

2017-01-30 16:46 UTC, PJB3005 commented
@Lokiamis I mean, we should enable dynamic lighting on the holodeck. Right now it's always 100% lit.

2017-01-30 17:32 UTC, Lokiamis commented
@PJB3005 You would have to do it on an area-by-area basis unless you want a beach illuminated by florescent bulbs.

2017-01-30 17:36 UTC, PJB3005 commented
@Lokiamis of course.

2017-01-31 02:44 UTC, N3X15 commented on code/game/machinery/computer/HolodeckControl.dm
> +
wat

2017-01-31 02:46 UTC, N3X15 requested changes
Fix dem lines.

2017-01-31 03:24 UTC, N3X15 approved these changes

2017-02-03 02:07 UTC, CptWad commented
Oh no #13734
PROOOOBE
THIS MAP EDIT WAS FIRST
AND APPROVED BEFORE YOURS

2017-02-03 10:55 UTC, Lokiamis commented
I can add the missing pipe if nobody cares.

2017-02-04 22:49 UTC, PJB3005 requested changes
How do the new areas work on deff which wasn't modified?

2017-02-04 22:49 UTC, PJB3005 commented on code/game/machinery/computer/HolodeckControl.dm
> +	name = "Light floor"
Remove capitalization here.

2017-02-04 22:49 UTC, PJB3005 commented on code/game/machinery/computer/HolodeckControl.dm
> +	floor_tile
What? This doesn't seem to define anything.

2017-02-04 22:49 UTC, PJB3005 commented on code/game/machinery/computer/HolodeckControl.dm
> +/obj/structure/window/holo/attackby(obj/item/weapon/W as obj, mob/user as mob)
Remove `as obj` and `as mob` here.

2017-02-04 23:25 UTC, Lokiamis commented on code/game/machinery/computer/HolodeckControl.dm
> +/obj/structure/window/holo/attackby(obj/item/weapon/W as obj, mob/user as mob)
Do you want them gone from the reinforced window that already exists too?

2017-02-04 23:27 UTC, Lokiamis commented on code/game/machinery/computer/HolodeckControl.dm
> +	floor_tile
Eh? I removed these lines and the light floors stopped working. I don't know what you mean.

2017-02-04 23:28 UTC, Lokiamis commented
@PJB3005  
>How do the new areas work on deff which wasn't modified?

>Deff will be a separate PR since Probe is 2slow, so the holodeck will look goofy if this is merged by itself. It won't break the map(I hope), the new rooms just won't fit the holodeck properly.
They fill the holodeck tiles that are available starting from the left. It's ugly, but I don't know of a workaround besides waiting. Probe has priority for Deff right now.

2017-02-05 09:31 UTC, PJB3005 commented on code/game/machinery/computer/HolodeckControl.dm
> +/obj/structure/window/holo/attackby(obj/item/weapon/W as obj, mob/user as mob)
Eh leave that.

2017-02-05 09:32 UTC, PJB3005 commented on code/game/machinery/computer/HolodeckControl.dm
> +	floor_tile
Well OK then.

2017-02-05 09:32 UTC, PJB3005 commented
Ah, OK. 

I was worried it might bulldoze the rest of the station or such.

2017-02-05 21:48 UTC, PJB3005 approved these changes

2017-02-05 22:19 UTC, Intigracy commented on code/game/machinery/computer/HolodeckControl.dm
> +	floor_tile
Turf code is stupid weird and all have a floor_tile subtype.

2017-02-06 23:58 UTC, Yelier commented
Really cool stuff! Did you get the chess idea from the thread? I remember shilling for it a lot.

2017-02-07 15:57 UTC, Lokiamis commented
Man, I was probably shilling it with you. All the pieces are labeled, by the way. Some of the constructs look alike.

2017-02-08 06:34 UTC, Lokiamis commented
@Probe1 are you fucking serious man #13730

2017-02-08 07:13 UTC, Probe1 commented
I knew your PR had a needs fixing on it and didn't check it closely enough. Sorry.

2017-02-08 07:23 UTC, Zth-- commented
These conflicts are not that hard to fix, they're only a few. But yes, my PR should've been merged last

2017-02-10 00:21 UTC, closed without merging

2017-02-10 01:14 UTC, CptWad commented
RIP

2017-02-10 01:23 UTC, Probe1 commented
Look just restore it and I'll fix the conflicts.

2017-02-10 02:06 UTC, Lokiamis commented
It's gone. I'm trying to fix it in another way, which isn't working.

2017-02-10 04:11 UTC, CptWad commented
everyone knows that the second map conflict is unfixable. I just hope to see it back again soon.