Adds Poutine recipe, food and sprite.
d3athrow/vgstation13 pull request #13686
Opened 2017-01-28 14:37 UTC by Aryuananime

![poutine](https://cloud.githubusercontent.com/assets/25397382/22397335/3d99258a-e53d-11e6-9867-97b3c117841f.png)

Now you too can enjoy this Canadian delight in spess, if the birds want to trade their seeds. 

:cl: 
 * rscadd: Added Poutine recipe, food and sprite.

2017-01-28 14:39 UTC, PJB3005 requested changes

2017-01-28 14:39 UTC, PJB3005 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	name = "Poutine"
You should remove the capitalization here, because BYOND will treat it as a proper noun and examine text and such will say "That's Poutine"

2017-01-28 17:18 UTC, PJB3005 approved these changes

2017-01-28 18:48 UTC, merged

2017-01-29 20:30 UTC, Kurfursten commented
>An entire cheesewheel in the recipe

Those are some extremely cheesy fries

2017-01-29 20:34 UTC, Shadowmech88 commented
*Dangerously cheesy.*

2017-01-29 21:24 UTC, PJB3005 commented
Oh I forgot to mention: did you add this to the wiki?

2017-01-29 21:35 UTC, Kurfursten commented
He did add it to the wiki, that's how I learned that it takes _an entire cheesewheel_

2017-01-29 21:36 UTC, PJB3005 commented
Ah OK.