Makes No-Fruit and No-Fruit Pie Reaction-Time-Based
d3athrow/vgstation13 pull request #13699
Opened 2017-01-29 09:28 UTC by Shadowmech88

I figured I'd see what people think of this change to no-fruit mechanics.

No-fruits and no-fruit pies now reshuffle their lists each time they reach the ends of them, rendering it impossible to predict the next cycle.
*To compensate*, the cycling time has been reduced from once every decisecond to once every four deciseconds. It's now humanly possible to react to the no-fruit's appearance and hit it before it changes, though it's still not easy.

:cl:
 * tweak: No-fruit and no-fruit pie cycling is now truly random, and can't be predicted.
 * tweak: The cycling speed of no-fruit and no-fruit pie has been reduced, so that it's now humanly possible to react to the fruit's appearance before it changes again.

2017-01-29 09:54 UTC, DoctorMonkey commented
It seems like a good idea, but is 4 deciseconds too slow? Seems like at that speed people could pluck whatever they want fairly easily, although that's just totally from my imagining of it

2017-01-29 09:59 UTC, Shadowmech88 commented
I tried and I wasn't always able to react fast enough.
The changes are very easy to make locally if you'd like to see what it's like yourself.

2017-01-29 14:13 UTC, Probe1 commented
I have no idea why you thought this would be merged.  The entire problem was that you could do this, defeating all those nice things that we have in favor of growing no-fruit instead.

2017-01-29 17:32 UTC, kilozombie commented
Probe, nobody can even aim for no-fruit as it is, you have to aim for no-fruit multiple ticks before the one you're actually wanting. You have to memorize the entire list to get what you want. This is a good thing.

The previous PR did NOTHING TO STOP NO-FRUIT POWERGAMING. None whatsoever. And it doesn't matter, because _nobody was powergaming with it in the first place._

2017-01-29 20:56 UTC, Kurfursten commented
This seems fine if the vox/roid/mutant plants are removed from the list of available items

2017-01-29 20:58 UTC, Shadowmech88 commented
I could do that, but I don't want to do it in *this* PR.
I could make another one to do that and let it get merged first.

2017-01-29 21:31 UTC, kilozombie commented
I think vox plants should stay on the list, at least. Otherwise it's impossible to get them without a trader.

Xenoarch plants for sure should be removed, especially if/when there's a change to them (kurf my babe please). Mutant plants make sense as well, considering a floral somatoray or mutagen is more fun as is.

2017-01-29 21:34 UTC, Kurfursten commented
The whole point is it's impossible to get them without trading, that's what makes it fun. It's not something you can count on getting every time, adds more interaction to the game, and is something the traders have you can't get elsewhere.

It's not as though you can only get flour from traders and 90% of the recipes are locked without it.

2017-01-29 21:35 UTC, kilozombie commented
Hey, that's true. I'm not entirely opposed to it.

2017-02-01 17:06 UTC, Iamgoofball commented
so like am I missing something or is botany really this critical to the station's balance that it has to be nerfed and that this kills tactical fruits or something?

2017-02-01 19:50 UTC, kilozombie commented
"You see, it allows people to eat new kinds of food and make new kinds of fruit, which just isn't okay, because they aren't made in the way that I, personally, think they should be." - despotate

2017-02-04 05:21 UTC, Shadowmech88 commented
In the interest of compromise, I've combined #13786 and #13807, removing as much theoretical lag as possible without changing the core functionality of the no-fruit.
* No-fruits and no-fruit pies no longer play a sound when cycling.
* No-fruit is now immutable.
* No-fruit now requires ten times the nutrition to grow.
* No-fruit can no longer roll prehistoric plants or vox plants.

I think that the reduction in cycling frequency, plus the removal of the sound, plus preventing them from being genetically modified, *plus* making them harder to grow in general, will make it far less trivial than it is now to produce enough no-fruit to tax clients, hopefully returning them to the position they were in for nearly a year without issue.

2017-02-04 05:34 UTC, kilozombie commented
Better than my PR by miles now.

No-fruit, Vox only, Final Destination

2017-02-05 01:05 UTC, PJB3005 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +var/global/list/special_fruits = list()
No need for `/global` here.

2017-02-05 01:13 UTC, Shadowmech88 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +var/global/list/special_fruits = list()
I was just copying what @N3X15 did.

2017-02-05 02:30 UTC, N3X15 submitted a review, later dismissed

2017-02-05 02:30 UTC, N3X15 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +
This is broken, please pull the fixed version from my PR.

2017-02-05 04:00 UTC, Shadowmech88 commented
@N3X15 
Done.

2017-02-05 18:34 UTC, Probe1 commented
We're going with N3X15 PR.  Reopen and adjust yours to the changes he made in a few days I don't want to see any nofruit till Wednesday.  

Everyone is caring way too much about something way too minor.

2017-02-05 21:05 UTC, 9600bauds commented
OK. I'm telling you all the following with the best interests of transparency and collaborator responsibility in mind.

After a stupid fucking fight in the collaborator chat I can see that **none of the collaborators to touch this stupid fucking debacle should have been allowed to touch it.** Every single last one of them is too caught up in this stupid fucking drama and a horrible fucking witch hunt and their decisions are very clearly biased and non-transparent, even if to them they don't seem like so. They are not acting in the interest of the image of all collaborators and they are not acting in the interests of the server.

I don't give a rat's ass who opened what PR and I especially don't give a rat's ass about no-fruit so I'm putting a kibosh to this operation, in the interests of the image of all collaborators and in the interests of the server. **I sincerely plead to all the other collaborators to stop.**

Here it goes.

I care about my friend Probe very much so I'm going to try to explain his stupid fucking decision in a way that makes this whole thing seem less bad. 
You see, all the collaborators involved in this no-fruit non-sense up until now are way too tired of it and they want this stupid fucking drama to stop. So my smart friend Probe **_temporarily_** merged #13786, **_juust_** for the lag-prevention bits of it, and graciously told the people to finish #13699, THIS PR, so that it can be merged again come Wednesday.
Of course, we know this is all a stupid fucking lie made up by me because for that to make sense, this PR should have been left open, since we all know that any changes pushed to a closed PR brick the whole thing so that it has to be remade.

So here's my version of it.
I remind you all that I don't fucking care about no-fruit. 
Looking at the votes alone it's clear that #13786 should not have been merged. Looking at the votes alone again, I have chosen this PR instead. I fully intend to revert #13786 and instead this PR should be finished up fully, and, come Wednesday, when everyone has calmed down, #13699, THIS PR, will be merged instead.
Why wait until Wednesday? I don't know, because all the collaborators are stupid fucking babies and need a time-out from this shit.
Until Wednesday comes around, please, I urge everyone else to not open any more no-fruit PRs, to please not open any more no-fruit issues, and to please keep all the no-fruit discussion right here in this PR.
Why this stupid discussion stonewall? I don't know, because all the collaborators are stupid fucking babies and need a time-out from this shit.

So here's my tl;dr closing statement.
**Please be fucking civil. Lord knows I can barely keep this boiling pot of shit from spilling over, so please don't stir it.**
Don't open any no-fruit issues or PRs until Wednesday. On Wednesday, if this PR is finished, I will personally merge it and I will personally revert #13786.

2017-02-05 21:12 UTC, 9600bauds requested changes

2017-02-05 21:12 UTC, 9600bauds commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +		if(initial(T:hydroflags) & filter)
This uses the : operator which is very haram and explicitly against contribution standards, please find a way to do this without the : operator.

2017-02-05 21:33 UTC, kilozombie commented
I just really hope we can all be understanding and civil about this whole thing for a little while.

2017-02-05 21:36 UTC, Exxion commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +		if(initial(T:hydroflags) & filter)
Just typecast `T` to `/obj/item/weapon/reagent_containers/food/snacks/grown`

2017-02-05 22:57 UTC, Megamaw commented
is there any way to make it so the sound only plays once no matter how many no-fruit are in range?

f l a v o r

2017-02-05 23:02 UTC, 9600bauds approved these changes

2017-02-05 23:04 UTC, 9600bauds commented
100% tested?

2017-02-05 23:09 UTC, Shadowmech88 commented
Yep, varedited it and confirmed the restricted fruits weren't in the possibilities list.

@Megamaw There is, but I don't want to try it in this PR.

2017-02-09 03:02 UTC, 9600bauds commented
![fjrbk6t](https://cloud.githubusercontent.com/assets/6526157/22767594/102bf452-ee5b-11e6-8564-15a3d67ac820.png)

2017-02-09 03:02 UTC, merged