Past Grenades
d3athrow/vgstation13 pull request #13717
Opened 2017-01-30 06:42 UTC by Shadowmech88

Adds a new variant of chrono grenade, the past grenade.
This variant, 30 seconds after detonation, resets everything in range of the blast at the time of detonation to its state at the time of detonation, effectively rewinding time for those atoms.
Results include bringing items that were destroyed in those 30 seconds back into existence, healing wounds, refilling containers and restoring charge to power cells, and of course teleporting everything back to where it was at the time.

This may be a bit difficult to visualize, so I'll have some WebMs up soon.

:cl:
 * rscadd: Added a new variant of chrono grenades which, 30 seconds after detonation, reset everything in range of the blast at the time of detonation to its state at the time of detonation, effectively rewinding time for those entities.

2017-01-30 06:44 UTC, kilozombie commented
What about bombs with timers or an activated nuke? I saw it asked in the thread, can you prolong the assplosion with past grenades?

2017-01-30 06:45 UTC, Shadowmech88 commented
You can with the nuke. You can't with timers, because I haven't added a special case for them yet.

2017-01-30 14:43 UTC, Skullyton commented
What happens if you detonate a past grenade, then detonate a future grenade?

We need some chrono-destabilization handling

2017-01-30 15:52 UTC, SkowronX commented
You can't do that Snake!

2017-01-30 20:28 UTC, Shadowmech88 commented
>What happens if you detonate a past grenade, then detonate a future grenade?

Future grenades don't affect items currently tethered to the past, and neither do other past grenades.
Stacking time effects would be a nightmare, so it's not possible.

2017-01-30 23:27 UTC, Shadowmech88 commented
Timers now properly have their time reset when caught in a past grenade, so they should be able to delay the detonation of toxins bombs now.

2017-02-01 07:01 UTC, PJB3005 requested changes
You probably need more update icon calls around the place.

2017-02-01 07:01 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +/datum/var/being_sent_to_past = FALSE
Yeah I'd really rather not have this be datum level...

2017-02-01 07:01 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
Dear God what is this indentation?

2017-02-01 07:01 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +	var/list/resettable_vars = list(
Make this static.

2017-02-01 07:01 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +									"locked_to",
Uh no you definitely cannot blindly copy locking stuff.

2017-02-01 07:01 UTC, PJB3005 commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +									"timeleft",
But  why the white space

2017-02-01 07:01 UTC, PJB3005 commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +									"timeleft",
Oh it's because I didn't scroll to the right on my phone.

2017-02-01 07:05 UTC, Shadowmech88 commented on code/game/atoms_movable.dm
> +/datum/var/being_sent_to_past = FALSE
It needs to be, for resetting things like reagent datums.

2017-02-01 07:06 UTC, Shadowmech88 commented on code/game/atoms_movable.dm
> +	var/list/resettable_vars = list(
To prevent it from being altered?
Will making it static change its scope?

2017-02-01 07:10 UTC, Shadowmech88 commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
Not sure why Github did that, looks fine locally.
![image](https://cloud.githubusercontent.com/assets/3991927/22498016/4089a8f6-e81b-11e6-9b2b-3bb2afac3a76.png)

2017-02-01 11:00 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
It's because you used tabs.

And even if you didn't Jesus you only need to indent that once, not like 10×.

2017-02-01 11:10 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +	var/list/resettable_vars = list(
To prevent the list being recreated every time it's called.

2017-02-01 11:10 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +/datum/var/being_sent_to_past = FALSE
Of course, but I'm iffy on making this be a variable on the most low level of types because it does incur a performance overhead on everything.

2017-02-01 17:00 UTC, Shadowmech88 commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
I figured the standard for lists was intending out to the end of the line where the list is defined.
I can back it up to just one or two tabs if it's a problem.

2017-02-01 17:01 UTC, Iamgoofball commented on code/game/atoms_movable.dm
> +/datum/var/being_sent_to_past = FALSE
just don't init it by default

2017-02-01 17:02 UTC, Iamgoofball commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
afaik that IS the standard

2017-02-01 17:02 UTC, Iamgoofball commented on code/game/objects/items/weapons/grenades/chronogrenade.dm
> +	duration = 10 SECONDS	//DON'T FORGET TO CHANGE THIS TO 30 SECONDS BEFORE MERGE
dont forget

2017-02-01 17:03 UTC, Iamgoofball commented on code/game/turfs/turf.dm
> +	spawn(duration)
gross, you ported stonedMC so use timers and callbacks instead

2017-02-01 17:04 UTC, Iamgoofball commented on code/modules/reagents/Chemistry-Holder.dm
> +	spawn(duration)
1. copypasta
2. ew gross you ported stonedMC use timers and callbacks not sleeps

2017-02-01 17:04 UTC, Iamgoofball commented on code/modules/reagents/Chemistry-Reagents.dm
> +	spawn(duration)
# c o p y p a s t a

2017-02-01 17:04 UTC, Iamgoofball commented on code/modules/reagents/Chemistry-Reagents.dm
> +	spawn(duration)
also you know the drill stonedMC timers/callbacks

2017-02-01 17:04 UTC, Iamgoofball commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +									"deepfried")
the important vars :+1:

2017-02-01 17:07 UTC, PJB3005 commented on code/game/atoms_movable.dm
> +									"being_sent_to_past",
Only one extra tab.

If this is actually the standard shoot whoever invented it.

2017-02-01 17:07 UTC, PJB3005 commented on code/game/turfs/turf.dm
> +	spawn(duration)
We haven't ported timers yet.

2017-02-01 22:59 UTC, ihadtoregisterforthis commented
Goofball no goofing 

@Shadowmech88 what happens if you throw a grenade before something catastrophic happens, like two shards colliding or Nar-Sie being summoned?

2017-02-01 23:01 UTC, Shadowmech88 commented
Past grenades only affect things that currently exist in the local area, so it can't undo something like Nar-Sie being summoned or a supermatter cascade.
It *would* bring the supermatter back into existence after it exploded, though.

2017-02-03 21:03 UTC, N3X15 commented
@PJB3005 Please re-review when possible

2017-02-03 21:40 UTC, PJB3005 requested changes

2017-02-03 21:40 UTC, PJB3005 commented on code/controllers/garbage.dm
> +		flags |= INVULNERABLE
You can compress this into a single line: `flags |= INVULNERABLE | TIMELESS`

2017-02-03 21:47 UTC, Shadowmech88 commented
Done.

2017-02-05 23:35 UTC, N3X15 commented
@PJB3005 Has he resolved the issues you raised?

2017-02-06 16:40 UTC, PJB3005 approved these changes

2017-02-06 23:09 UTC, Shadowmech88 commented
Conflicts fixed.

2017-02-07 21:43 UTC, merged

2017-02-07 21:49 UTC, Shadowmech88 commented
WOOO