Spider edits - Queen upper limit
d3athrow/vgstation13 pull request #13711
Opened 2017-01-29 20:37 UTC by Skullyton

Fixes #8578

After a bit of research, I found that it wasn't spider nurses evolving into queens, but spiderlings evolving straight into queens.

The way it was done was making a global list of all spider types, said global list was only accessed in one file that wasn't where it was even declared, and had no way to filter it out (So, you'd have spiderlings become salk the spiderling, or some strange subtype of spider hunter that spawned dead)

So, I changed it from a global to a local associated with spiderlings, and added the basic giant spider types it should evolve into, which gave me a greater degree of control over what spawns.

With that, I added a global list of all spider queens in existence, added to when a spider queen spawns, removed from when a spider queen is destroyed. This list is then used in the life() of spider nurses who will evolve into a queen should the number of queens fall under the define of 5 natural spider queens at maximum.

:cl:

* rscadd: Adds static upper limit for active spider queens

2017-01-29 23:03 UTC, Riekland commented
>After a bit of research, I found that it wasn't spider nurses evolving into queens, but spiderlings evolving straight into queens.

Why not just leave the no limit on queens but make it so that queens can only come from nurses?
I'm of the firm opinion that if you're retarded enough to leave spiderlings lying around, you deserve the holocaust that comes from it.

2017-01-29 23:19 UTC, Skullyton commented
Well, as of right now it checks if there's any 'queen slots' available, and if so, it evolves into such.

Would you prefer something over time? I was avoiding doing too much because N3x15 is doing stuff regarding spider AI

2017-01-30 00:40 UTC, SonixApache commented
thank fuck

2017-01-30 01:36 UTC, Riekland commented
I would prefer the only way for spider queens to spawn being spider nurses evolving after I dunno, five or ten minutes?
It's like putting a cap on the amount of cockroaches, it removes a lot of the fun and hilarity if you can't open a storage closet and gets drowned in a tidal wave of mobs.

2017-01-30 04:10 UTC, ShoMek commented
I love @Riekland 's idea. That kind of "maintenance work" idea sounds really fun and good for the game.

2017-01-31 03:41 UTC, Probe1 commented
That's a poor comparison.  Cockroaches just move around.  Spider Queens web, lay eggs (MORE SPIDERS), attack players, and move around.  It's not great for performance.  It's not great for balance.  It's mirrored in xeno code which people like.

2017-01-31 10:49 UTC, Skullyton commented
Spider queens are a boss mob almost. Bad idea to let a lot develop

2017-01-31 15:59 UTC, Riekland commented
Well why don't you put it to a s e r v e r p o l l since it's a matter of balance

2017-01-31 17:49 UTC, Probe1 commented
Because I don't see it as a contentious issue and I don't think something that has as much to do with server performance and consistency as it does balance requires it.

2017-02-04 15:50 UTC, Skullyton commented
I've got it.

Rather than having the amount of queens be static, have it scale with spider population.

So, maybe 1 queen to every 10 spiders

2017-02-04 19:01 UTC, Probe1 commented
Delaying the inevitable lag instead of solving it.

2017-02-04 22:45 UTC, PJB3005 requested changes

2017-02-04 22:45 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
Make this static.

2017-02-04 23:31 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
var/static/list?

2017-02-05 11:44 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
Yeah.

2017-02-05 19:16 UTC, Exxion commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
What's that even do for a list?

2017-02-05 19:25 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
Think it makes it uneditable during gameplay, which helps keep the list amount down?

2017-02-05 19:26 UTC, Exxion commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
I'm not sure if BYOND can make lists fully static, but even if it can, you don't want to. It would break `is_type_in_list()`

2017-02-05 19:39 UTC, Shadowmech88 commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
I thought it served to prevent the list from being created every time the code is executed, instead being created only once.

2017-02-05 22:15 UTC, PJB3005 commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
Yes. This way there'll be one global list, and not one list per spiderling, which would be inefficient.

2017-02-05 22:51 UTC, Exxion commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
Ah, then that makes sense
I thought that was `global`

2017-02-21 02:35 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm
> +	var/list/spider_types = list(/mob/living/simple_animal/hostile/giant_spider, /mob/living/simple_animal/hostile/giant_spider/nurse, /mob/living/simple_animal/hostile/giant_spider/hunter)
@PJB3005

2017-02-21 04:15 UTC, Probe1 commented
Ping PBJ to re-review or I'll do it tomorrow.

2017-02-21 06:15 UTC, PJB3005 approved these changes

2017-02-21 13:22 UTC, merged