This Message Will Self-Destruct
d3athrow/vgstation13 pull request #13740
Opened 2017-01-31 23:51 UTC by Shadowmech88

Adds explosive paper.
Once something is written on explosive paper, when it is read, it will notify the reader that it will self-destruct after a set amount of seconds, and will explode once that time is up.
The explosion is small enough to not cause a breach, though it will still hurt.

The default time is five seconds, though it can be varedited/subtyped to change that as needed.

2017-01-31 23:55 UTC, Intigracy requested changes

2017-01-31 23:55 UTC, Intigracy commented on code/modules/paperwork/explosive_paper.dm
> +				detonating = TRUE
move above the spawn()

2017-02-01 01:03 UTC, merged

2017-02-01 01:04 UTC, Intigracy commented
wait I didn't mean to do that
oops

2017-02-01 01:04 UTC, Intigracy commented
Make a different PR if you planned to add it somewhere.

2017-02-01 01:48 UTC, CptWad commented
wew
How about 2 telecrystals? While you are at it increase the decoys to 2 crystals too since you can make like 20 fucking decoys of yourself

2017-02-01 01:50 UTC, Blithering commented
Making twenty decoys of yourself is the best use for your telecrystals though.