Adds custom artifact creation. Adds the dead harvest artifact effect
d3athrow/vgstation13 pull request #13751
Opened 2017-02-01 14:21 UTC by Skullyton

Re-approaches #10742 by making it an artifact effect, rather than a snowflaked object.

The dead harvest effect checks for dead mobs in its vicinity, should it find any, it will gib them and add points to its internal reservoir. Should it reach enough points, it will spawn a mob from an internal mob list (4 different variations of list as of right now. Regular necromancy mobs, infection-based zombies, necromorphs, and a randomly generated list).

The different effect triggers do different things. Should it be touch based, any mob living or dead will be harvested that touch it, unless they are the controller (First person to touch it, assuming it can be controlled)

Should it be pulse based, the artifact will revive mobs that are in its spawn list in the vicinity of the object.

Should it be aural based, it's much more random to whether it will harvest and/or spawn a mob.

Because I got tired of having to spawn a shit ton of artifacts to try and test this, I added in custom artifact creation to the admins secret tab. It's not overly robust, but it's better than nothing.

:cl:
* rscadd: Adds the dead harvest artifact effect

2017-02-01 14:41 UTC, BobdaBiscuit commented
>custom artifact creation
Thank fuck for that finally being made.

2017-02-01 14:45 UTC, jknpj commented
Make us whole

2017-02-01 15:52 UTC, Sprok0 commented
You'll probably want to add mob_spawn and can_be_controlled, and maybe controller to the copy_for_battery var, or making an artifact battery with this will reroll all those settings.

2017-02-01 16:19 UTC, Skullyton commented
I was informed somebody was redoing batteries, but I'll take a look.

Never interacted with the batteries before, is there a good PR utilizing them for reference?

2017-02-01 16:20 UTC, BobdaBiscuit commented
I'm ripping all the old battery code up and redoing it soonish so I'd say leave it for now.

2017-02-01 16:21 UTC, Skullyton commented
Alrighty

2017-02-03 18:55 UTC, PJB3005 requested changes

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +				var/mob/living/simple_animal/mob_to_add = pick(typesof(/mob/living/simple_animal))
`existing_typesof` is probably a better idea here.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +			for(var/i=0,i<max_mobs,i++)
`for(var/i = 0 to max_mobs)`

Note that this'll iterate one more time so drop the max mob count by one.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +	if(holder)
Compress these ifs with `&&`, please.

In fact do it like this:

```dm
if (!holder || !user)
    return
...
```

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +	if(holder)
Cut the indentation here, see above comment.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +						to_chat(user, "<span class = 'sinister'>You feel a slight biting sensation, which subsides</span>")
Period here.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +						to_chat(L, "<span class = 'sinister'>You [pick("feel tingly","are overcome with a sense of dread","feel incomplete")]</span>")
Period here.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +	if(holder)
And here.

2017-02-03 18:55 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +	if(!(sacrifice.isDead()) && !override) //No eating the living unless they come willingly
Why even wrap the call in parentheses.

2017-02-03 19:39 UTC, Skullyton commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +			for(var/i=0,i<max_mobs,i++)
Ah, okay.

Went back to old java practices, my bad

2017-02-03 19:39 UTC, Skullyton commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +				var/mob/living/simple_animal/mob_to_add = pick(typesof(/mob/living/simple_animal))
What does existing_typesof return?

2017-02-03 19:40 UTC, Skullyton commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +	if(!(sacrifice.isDead()) && !override) //No eating the living unless they come willingly
Bad habit, I read it easier with more parentheses

2017-02-04 14:20 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +				var/mob/living/simple_animal/mob_to_add = pick(typesof(/mob/living/simple_animal))
It's the same deal except it cuts out potentially broken things without icon and such.

2017-02-04 15:38 UTC, Skullyton commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_deadharvest.dm
> +			for(var/i=0,i<max_mobs,i++)
I think I'll have the max mob count at 7, keeps things nice

2017-02-04 15:47 UTC, PJB3005 approved these changes

2017-02-04 15:50 UTC, merged

2017-02-04 23:04 UTC, BobdaBiscuit commented
REEEEEEEEEEEEEEEEEEEE

2017-02-04 23:30 UTC, Skullyton commented
????

2017-02-04 23:36 UTC, Skullyton commented
PJB just informed me of the details.

I apologize

2017-02-04 23:48 UTC, BobdaBiscuit commented
Any chance of having aura being able to have a master? Even if it's rtandom if there's a master or if the mobs are wild.

Could be real neat for antags.