Fixes a runtime
d3athrow/vgstation13 pull request #13784
Opened 2017-02-02 22:49 UTC by Zth--

[03:58:15]DEBUG: Runtime in <b>vehicle.dm</b>, line <b>117</b>: <b>undefined proc or verb /mob/living/simple_animal/hostile/mimic/copy/has gravity().

2017-02-02 23:16 UTC, N3X15 requested changes

2017-02-02 23:16 UTC, N3X15 commented on code/game/objects/structures/vehicles/vehicle.dm
> +	var/turf/T = get_turf(loc)
Should also add a `if(!T)` check, in case the vehicle is nullspaced (qdel).

2017-02-02 23:30 UTC, Zth-- commented on code/game/objects/structures/vehicles/vehicle.dm
> +	var/turf/T = get_turf(loc)
Done

2017-02-03 22:25 UTC, N3X15 approved these changes

2017-02-03 22:25 UTC, merged