High-Frequency Machete
d3athrow/vgstation13 pull request #13826
Opened 2017-02-05 00:30 UTC by jknpj

![machete](https://cloud.githubusercontent.com/assets/17928298/22622606/aa22ece6-eb1d-11e6-9541-f2219803302d.png)
https://webmshare.com/omnZ0
https://webmshare.com/aDnP7
https://webmshare.com/wnQ5j

Adds High-Frequency Machete, an alternative all-purpuse weapon to the iconic energy sword, and its upgraded form, the High-Frequency Pincer Blade "Bloodlust". Both come with tons of unique sounds for enhanced murderbone experience.

The machete, unlike the energy sword it is always medium sized, can't be used as a shield and even with in high-frequency mode its force lower (25 against esword's 30) but  besides having higher sharpness (1.7) it also has other two fun gimmicks:

* When in high-frequency mode it can instantly cut down kudzu.
* When in normal mode it becomes a robust throwing weapon with 20 throwing force 8 speed and range.

Bloodlust was made with high risk high reward in mind. It is two-handed always large-sized weapon with 2.5 seconds attack delay packing whooping 34 force, 2 sharpness(really, really sharp.) and the ability to act as a shield, making it really strong but also really difficult to use and hide.

* It keeps its ability to instantly cut down kudzu when in high-frequency mode(wielded)
* Due being heavy, the bloodlust throwing force, speed range are always shit.

:cl:
 * rscadd: Adds High-Frequency Machete
 * rscadd: Adds High-Frequency Pincer Blade "Bloodlust", made with two high-frequency machetes.

2017-02-05 02:52 UTC, Aurantiaco commented
Does it make you fucking invincible?

2017-02-07 03:23 UTC, icantthinkofanameritenow commented
Refresh my memory, what's the advantage of having higher sharpness vs. higher force?

2017-02-07 03:38 UTC, Shadowmech88 commented
If a weapon has sharpness, it has a certain % chance to sever a limb, provided that limb is above its personal damage threshold for severability. From sharpness 0.1 to 1.9, this chance is simply higher. At sharpness 2.0 and above, the damage threshold necessary for the limb to be severed is lowered, scaling inversely with sharpness.
More force just applies more damage.

2017-02-07 13:42 UTC, Fruktlimpa commented
Should give you a message when you craft Bloodlust that says "You feel fucking invincible"

2017-02-07 14:37 UTC, jknpj commented
@Fruktlimpa it's already there: `to_chat(user, "<span class='notice'>You combine the two [W] together, making a single scissor-bladed weapon! You feel fucking invincible!</span>")`

2017-02-08 20:40 UTC, PJB3005 requested changes

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/melee/energy.dm
> +		icon_state = "[base_state][active]"
Not sure why you need an if here, since both ends of the if are exactly the same.

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/melee/energy.dm
> +	return
Trailing return.

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +	icon_state = "bloodlust[wielded ? 1 : 0]"
You can do `icon_state = item_state = "bloodlust[...]"`

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +	sharpness = wielded ? 2.0 : initial(sharpness)
Oooh the redundant decimal!

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +	return
Trailing return.

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +	user.delayNextAttack(25) // Big blade, big attack delay.
This will make you attack delay any time you click anywhere in your viewport.

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/bloodlust/afterattack(null, mob/living/user as mob|obj, null, null, null)
Jesus christ what is this proc signature.

How is this even compiling
aaaaaaah

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/bloodlust/attack(target as mob, mob/living/user as mob)
Remove `as x`

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/melee/energy.dm
> +/obj/item/weapon/melee/energy/hfmachete/attack(target as mob, mob/living/user as mob)
Remove `as x`

2017-02-08 20:40 UTC, PJB3005 commented on code/game/objects/items/weapons/melee/energy.dm
> +/obj/item/weapon/melee/energy/hfmachete/attack_self(mob/living/user as mob)
Remove `as x`

2017-02-09 19:24 UTC, kol1th commented on code/game/objects/items/weapons/melee/energy.dm
> +		animate(src)
Throwing animations when?

2017-02-09 21:23 UTC, jknpj commented
Thanks git

2017-02-09 21:23 UTC, closed without merging