Makes large artifact triggers datums
d3athrow/vgstation13 pull request #13856
Opened 2017-02-06 03:21 UTC by BobdaBiscuit

At the request of PJB I have turned the shitty old code into shitty current code, all effect triggering has been moved outside of the artifact object into a trigger datum.

The artifact has a series of events that can be invoked and passed onto the trigger datum along with information needed to decide if the artifact should activate. This is easily expanded upon so new triggers can be easily added.

I have tried to not remove any features/change functionality as best as I could but a few things have changed (that I can remember to write here).

* Artifact icon no longer decides what trigger it could have
* Rates of different triggers appearing has changed obviously
* Secondary effects take a few moments to toggle if they are enviroment based

I doubt people will really care.

Done some tests and solved all runtimes I could find.
I need some help in getting projectile tests to work since they do nothing as is (also an issue with the current code apparently).

:cl:
* tweak: Xenoarch large artifact trigger behaviour has been slightly tweaked as some changes to the back end have been done.

2017-02-06 03:30 UTC, BobdaBiscuit commented
Half asleep but just realised 99% of the logging in the triggers could be moved to a line in Triggered(), possibly with some context checks.

I'll be doing that later.

2017-02-06 18:43 UTC, N3X15 commented
Let me know when this is ready

2017-02-06 19:41 UTC, N3X15 commented
I see nothing wrong with the usage of events.  I can't comment as to the rest as I've been out of the loop for a while.

2017-02-11 03:58 UTC, N3X15 commented
```
BobdaBiscuit - Today at 7:57 PM
yeah dont merge that
I was hoping someone would give me top tips
to modernising the old code
like the huge if statements```

2017-02-11 05:16 UTC, BobdaBiscuit commented
I mean if no one comes along we may aswell merge it at some point and when someone bitches about it I can direct them to the trigger datum to fix it in.

2017-02-11 11:49 UTC, PJB3005 requested changes
Sorry for the late review on this one.

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/trigger.dm
> +		key0 = my_artifact.on_attackhand.Add(src, "owner_attackhand")
Need to clear this handler in `Destroy`

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_energy.dm
> +	my_artifact.on_attackhand.Remove(key0)
This should be done on the parent and do super calls.

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/trigger.dm
> +	var/obj/machinery/artifact/my_artifact
Need to clear all of these in `Destroy`

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +/obj/machinery/artifact/Destroy()
While you're at it, could you make artifacts `qdel` their effects?

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/trigger.dm
> +	if (my_effect.effect == EFFECT_TOUCH)
Not very keen on this being in the base type. Should probably just make `EFFECT_TOUCH` effects be guaranteed to have the on touch trigger instead.

2017-02-11 11:49 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_energy.dm
> +	triggertype = "energy"
These should be made `#define`s

2017-02-11 21:07 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  	qdel(copy_for_battery); copy_for_battery = null
This is a list, right? You can just null lists directly.

2017-02-11 21:42 UTC, BobdaBiscuit commented
Tbh I don't think the trigger types should be defines but I did it anyway.

2017-02-11 22:13 UTC, BobdaBiscuit commented
So current behaviour differences that I know of.

* Artifact icon no longer decides what trigger it could have
* Rates of different triggers appearing has changed obviously
* Secondary effects take a few moments to toggle if they are environment based
* Any ontouch based effects automatically have the touch trigger
* ontouch effects toggle the artifact icon/activation messages (I think this was a thing before)

2017-02-14 05:00 UTC, BobdaBiscuit commented
Aight I did some major unfucking, it's a bit spaghetti but all runtimes/functionality issues that I could find in all the tests are gone.

Gonna need new reviews for the code though.

2017-02-17 16:02 UTC, unusualcrow commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
> +			if(trigger_gas == "TOXINS" && env.toxins > MOLE_TRIGGER)
You'd probably want to use =>

2017-02-17 17:53 UTC, unusualcrow commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
> +			if(trigger_gas == "TOXINS" && env.toxins <= MOLE_TRIGGER)
This is gonna conflict with the above. Keep the activation to >= and this as <

2017-02-17 17:54 UTC, unusualcrow commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
> +			if(trigger_gas == "TOXINS" && env.toxins <= MOLE_TRIGGER)
Keep this part at <, not <=

2017-02-17 17:54 UTC, BobdaBiscuit commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_gas.dm
> +			if(trigger_gas == "TOXINS" && env.toxins <= MOLE_TRIGGER)
Hue, oops.

2017-02-17 18:35 UTC, PJB3005 requested changes

2017-02-17 18:35 UTC, PJB3005 commented on code/modules/admin/topic.dm
>  					var/obj/machinery/artifact/custom = new /obj/machinery/artifact(get_turf(usr))
Making this spawn a subtype that doesn't initialize effects instantly would probably be better.

2017-02-17 18:42 UTC, BobdaBiscuit commented on code/modules/admin/topic.dm
>  					var/obj/machinery/artifact/custom = new /obj/machinery/artifact(get_turf(usr))
I'm planning that for a future pr that will also add in trigger choosing to the badmin spawn menu.

2017-02-17 18:44 UTC, PJB3005 commented on code/modules/admin/topic.dm
>  					var/obj/machinery/artifact/custom = new /obj/machinery/artifact(get_turf(usr))
Eh alright then.

2017-02-17 18:44 UTC, PJB3005 approved these changes

2017-02-17 18:44 UTC, PJB3005 commented
@BobdaBiscuit this ready?

2017-02-17 18:44 UTC, BobdaBiscuit commented
Yes.

2017-02-17 18:50 UTC, jknpj commented
Soon

2017-02-19 17:28 UTC, merged

2017-05-01 00:07 UTC, Exxion commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  	effect = rand(0,MAX_EFFECT)
Why

2017-05-01 10:46 UTC, BobdaBiscuit commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  	effect = rand(0,MAX_EFFECT)
Because we can't have nice things and I'm shite at this whole well designed system thing. Feel free to replace it.

2017-05-01 13:34 UTC, Exxion commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  	effect = rand(0,MAX_EFFECT)
I kind of already did
But this was there before you did anything anyway
I was just complaining