Adds two new artifact effects: Plant killer and Plant helper
d3athrow/vgstation13 pull request #13868
Opened 2017-02-06 22:48 UTC by jknpj

Adds plant helper and plant killer as possible artifact effects. Both effects have a random chance to successfully activate each activation/pulse.

Plant Helper aura effect will refill your plants water, nutriment really slowly and deal with weeds and pests.
Plant Helper pulse effect will refill water, nutriments, remove weeds, pests and toxins and even rejuvenate your crops but will also improve their yield and mutate them so you have to be very careful with it.

Plant Killer aura effect will dry your crops of both water and nutriment, make them age faster and make weeds appear more often.
Plant Killer pulse effect will quickly remove water and nutriment, fill their trays with toxin and make their yield worse while making pests and weeds life easier. It will also have 1% of instantly killing a crop every time its pulse is successfully activated.

:cl:
 * rscadd: Adds two new artifact effects: plant helper and plant killer.

2017-02-06 22:57 UTC, PJB3005 requested changes
The bad mutation possibility for the helper is probably not something that should be included.

2017-02-06 22:57 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +						H.waterlevel += rand(2,8)
These should probably be capped unless hydroponics code can handle it.

2017-02-06 22:57 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +						H.mutation_level++
Does this even work? Sounds like you'd need to call procs, no?

2017-02-06 22:57 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +			if(H.seed && !H.dead && prob(rand(8,36)))
> `prob(rand())`

This guy understands how probabilities work.

2017-02-06 22:57 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +						H.yield_mod++
This seems extreme.

Just leave this sitting at your plant for a few minutes and the yield will become insane.

2017-02-06 22:57 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_plantkiller.dm
> +						H.waterlevel -= rand(1,5)
Caps.

2017-02-06 23:03 UTC, jknpj commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +						H.waterlevel += rand(2,8)
max water is capped at 100

2017-02-06 23:35 UTC, Aurx commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_planthelper.dm
> +			if(H.seed && !H.dead && prob(rand(8,36)))
It's extra random!

2017-02-07 00:28 UTC, AI-is-rogue commented
Is there any reason someone would want the plant killer effect?

2017-02-07 00:37 UTC, Shadowmech88 commented
Not all artifact effects need to be desirable.

2017-02-07 00:38 UTC, AI-is-rogue commented
I know but I am still curious.

2017-02-07 01:13 UTC, jknpj commented
@AI-is-rogue https://www.youtube.com/watch?v=ugJfjmxOR2I

2017-02-08 03:50 UTC, N3X15 commented
@PJB3005 You done with this?

2017-02-08 11:37 UTC, PJB3005 approved these changes

2017-02-08 17:11 UTC, FudgePucker commented
I just came up with an idea for the plant killer effect, make it work on kudzu.

2017-02-09 01:30 UTC, merged