Minor peacekeeper tweaks.
d3athrow/vgstation13 pull request #13878
Opened 2017-02-07 19:56 UTC by icantthinkofanameritenow

See the changelog. With the new description, there is no excuse for someone to be a shitter on Peacekeeper.

2017-02-07 19:57 UTC, Intigracy requested changes

2017-02-07 19:57 UTC, Intigracy commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<span class='warning'><big><b>Under ASIMOV, you are an enforcer of the PEACE and preventer of HUMAN HARM.You are expected to follow orders and prevent harm above all else. Space law
Space after HARM.

2017-02-07 20:15 UTC, icantthinkofanameritenow reviewed
fixed the space.

2017-02-07 20:16 UTC, Ephx1 commented
That's very specific to Asimov, I'm not sure that's a good idea.

2017-02-07 20:18 UTC, icantthinkofanameritenow commented
@Ephx1 
Asimov is the default, so it will be sufficient for roundstart barring adminbus law changes beforehand.  Even if they are changed, that last line doesn't leave any room for interpretation.

2017-02-07 20:41 UTC, TheFriggenSawbones commented
![Image of BLOODHOUND](http://netstorage.discovery.com/feeds/brightcove/asset-stills/apl/1405103765501B02BBB_12670802701197_Bloodhound.jpg)

2017-02-07 21:42 UTC, Probe1 submitted a review, later dismissed

2017-02-07 21:42 UTC, Probe1 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<span class='warning'><big><b>Under ASIMOV, you are an enforcer of the PEACE and preventer of HUMAN HARM. You are expected to follow orders and prevent harm above all else. Space law
Brevity is important.

2017-02-07 21:42 UTC, Probe1 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			module_sprites["Hound"] = "bloodhound"
Why

2017-02-07 21:46 UTC, icantthinkofanameritenow commented on code/modules/mob/living/silicon/robot/robot.dm
> +			module_sprites["Hound"] = "bloodhound"
Because "Bloodhound" sounds too aggressive. It's supposed to be peaceful.

2017-02-07 21:47 UTC, Probe1 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			module_sprites["Hound"] = "bloodhound"
Keeping the peace and being peaceful aren't the same thing.

2017-02-07 21:49 UTC, icantthinkofanameritenow commented on code/modules/mob/living/silicon/robot/robot.dm
> +			module_sprites["Hound"] = "bloodhound"
It still sounds like it's better suited to hunting criminals than it is at keeping the peace.

2017-02-07 22:30 UTC, SonixApache commented
What if your lawset isn't asimov when you get built?

2017-02-07 22:53 UTC, icantthinkofanameritenow commented
@SonixApache 
I removed the specifically asimov related parts, and any more changes would defeat the purpose of changing the notifier at all.

2017-02-07 22:57 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<span class='warning'><big><b>You are expected to follow orders and prevent harm above all else. Space law means nothing to you- you are not a Security Officer.</b></big></span>")
>You are expected to follow orders and prevent harm above all else.

Really only applies to asimov. Replace it with something like "You are expected to follow orders and keep the peace" or add a per-law clause, this is dumb.

2017-02-07 23:09 UTC, SonixApache commented
👌

2017-02-08 04:17 UTC, Probe1 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<span class='warning'><big><b>You are expected to follow your laws above all else. Space law means nothing to you- you are not a Security Officer.</b></big></span>")
You're still saying 1.  A mouthful and 2.  That space law doesn't apply when it does under robocop.

2017-02-08 11:52 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<span class='warning'><big><b>You are expected to follow your laws above all else. Space law means nothing to you- you are not a Security Officer.</b></big></span>")
Increase the warning size, add a sound (the poke sound from TS3 is a good one) and remove the 'space law [...] to you' part.

2017-02-09 05:48 UTC, 9600bauds commented on code/modules/mob/living/silicon/robot/robot.dm
> +			module_sprites["Hound"] = "bloodhound"
Voxbloodhound

2017-02-11 01:02 UTC, gbasood commented
@Intigracy @Probe1 pls

2017-02-12 02:55 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<font size='12' color='red'><b><b>You are expected to follow your laws above all else. You are not a Security Officer.</b></font>")
No `<font>` tag. Use `danger` and `big` as classes.

2017-03-16 20:16 UTC, icantthinkofanameritenow commented
Stopped caring, doesn't seem like it's necessary now.

2017-03-16 20:16 UTC, closed without merging