Time Suit
d3athrow/vgstation13 pull request #13894
Opened 2017-02-08 06:21 UTC by Shadowmech88

![timesuit_display_large](https://cloud.githubusercontent.com/assets/3991927/22725503/6a269836-ed93-11e6-887e-aa6cc3a5bc45.png)
Adds the time suit, a space-worthy lightly-armored suit with time-related capabilities.

Wearing both the suit and the helmet causes the wearer to be timeless, meaning they will be unaffected by external time effects such as chrono grenades.
Additionally, the wearer receives three spells, held inside a unique spellmaster for time spells. These allow the wearer to stop time in a radius of two tiles for five seconds, with a thirty second cooldown, send themselves ten seconds into the future, with a thirty second cooldown, and send themselves ten seconds into the past, with a sixty second cooldown.
WebM of the abilities in combat: http://puu.sh/tTp80/99391f3a95.webm

:cl:
 * rscadd: Added the time suit, a space-worthy lightly-armored suit which confers time-related abilities to the wearer.

2017-02-08 10:59 UTC, Exxion commented
Calling it "sending you to the past" is really kind of a misnomer because the effect is exactly the same as sending you to the future except you can move around and do stuff for the duration rather than just vanishing

2017-02-08 11:07 UTC, Skullyton commented
It resets everything that was in the circle to its original position, health, charge, etc.

2017-02-08 12:01 UTC, SonixApache commented
Simple time-suit mobs with one time ability WHEN

2017-02-08 13:30 UTC, AlphaBuffalo commented
Might as well be a telelporting suit

2017-02-08 13:44 UTC, SkowronX commented
needs a better sprite

2017-02-08 14:03 UTC, Skullyton commented
What's wrong with it?

Hell, what's right with it?

2017-02-08 14:28 UTC, PJB3005 commented
Shading looks weird.

2017-02-08 18:02 UTC, calzilla1 commented
Make it when he stops time it has a 1/100 chance to say ZA WARDO

2017-02-08 18:18 UTC, Intigracy commented
I loved this game.

Sick reference brah.

2017-02-08 18:36 UTC, HarseTheef commented
One step closer to a time cop ERT to remove people who break time law.

2017-02-08 23:36 UTC, Skullyton commented
@calzilla1 That's already a thing with the spell timestop

Not all timestops have to be jojo references

2017-02-09 01:13 UTC, Probe1 commented
Doesn't the spell time stop play ZA WARDO

2017-02-09 01:36 UTC, Exxion commented
Yeah
That's what Skullyton just said

2017-02-09 14:54 UTC, Intigracy commented
This specifically is a reference to Timeshift, I knew as soon as I saw the suit sprite.

You're in a time suit that looks just like that and can reverse, freeze, and fast forward time.

2017-02-09 16:22 UTC, SonixApache commented
I thought it was Reverse, slow and stop time.

2017-02-09 19:35 UTC, kol1th commented
https://github.com/tgstation/tgstation/pull/7084

2017-02-09 19:35 UTC, Intigracy commented
Same shit, you moving faster than everything else is you fast forwarding.

2017-02-09 19:37 UTC, Intigracy commented
Also who cares about a TG feature tangentially related?

2017-02-09 21:32 UTC, NigglyWiggly commented
The shading looks weird on the sprites, yeah.

Not just wearing a DeLorean as a suit/10

2017-02-09 22:28 UTC, Shadowmech88 commented
Conflicts fixed.

2017-02-10 01:13 UTC, kol1th commented
@Intigracy People were talking about time police and that's pretty related.

2017-02-12 01:30 UTC, Skullyton commented
A guy who isn't colourblind did a redo of the sprites

https://my.mixtape.moe/bkwhma.rar

2017-02-12 12:51 UTC, diammz commented
i'd be that guy, but i wasn't satisfied with the initial redo so i updated them again.

https://my.mixtape.moe/mfqpoi.rar

2017-02-12 12:53 UTC, diammz commented
i'd be that guy, but i wasn't satisfied with the initial redo so i updated it again. (in-hand sprites included)

https://my.mixtape.moe/mfqpoi.rar

![suit](https://cloud.githubusercontent.com/assets/25720704/22862193/901f4f66-f12a-11e6-82ec-4cac46619b96.png)

2017-02-12 16:20 UTC, Skullyton commented
Nicr

2017-02-13 05:51 UTC, diammz commented
custom activation and deactivation sfx for that homey feeling

https://my.mixtape.moe/clzmqu.rar

2017-02-18 00:05 UTC, Shadowmech88 commented
Better sprites and sounds are added, this should be ready to go.

2017-03-10 02:43 UTC, Skullyton commented
A ready to go PR is kill

2017-03-10 03:08 UTC, Shadowmech88 commented
I'll get around to fixing it.

2017-03-10 11:22 UTC, Shadowmech88 commented
Conflicts fixed and ready to go.

2017-03-18 14:42 UTC, PJB3005 requested changes

2017-03-18 14:42 UTC, PJB3005 commented on code/modules/clothing/spacesuits/time.dm
> +	if(istype(H) && H.get_item_by_slot(head) == src)
Should be `slot_head` here.

2017-03-18 14:42 UTC, PJB3005 commented on code/modules/clothing/spacesuits/time.dm
> +/obj/item/clothing/head/helmet/space/time/equipped(mob/living/carbon/human/H, head)
Why is the second parameter called `head` anyways?

2017-03-18 14:42 UTC, PJB3005 commented on code/modules/clothing/spacesuits/time.dm
> +	if(istype(H) && H.get_item_by_slot(wear_suit) == src)
`slot_wear_suit`

2017-03-18 14:42 UTC, PJB3005 commented on code/modules/clothing/spacesuits/time.dm
> +/obj/item/clothing/suit/space/time/equipped(mob/living/carbon/human/H, wear_suit)
Naming of the second argument.

2017-03-18 21:18 UTC, ComicIronic commented on code/game/objects/items/weapons/grenades/chronogrenade.dm
> +		if(!A.being_sent_to_past)
So a single target can be affected even if timeless? Also, there's a lot of copypaste to all of this - make these procs.

2017-05-04 03:29 UTC, Shadowmech88 commented
*Now* it should be ready.

2017-05-04 05:16 UTC, Commandersand commented
Where do you get this? Bus only?

2017-05-04 05:36 UTC, Shadowmech88 commented
For now.

2017-05-04 17:05 UTC, PJB3005 approved these changes

2017-05-09 21:03 UTC, ComicIronic commented
Approved, merging.

2017-05-09 21:03 UTC, merged