Cuts down on hairstyle power creep(shaver port)
d3athrow/vgstation13 pull request #13911
Opened 2017-02-09 21:23 UTC by JustSumBody

nerfs #13906
Fun fact: The sprite for this was in the .dmi this whole time. Doesn't seem to have an inhand though, not sure if that's kicking around somewhere or someone wants to take a crack at it
Basically: Aim at head or face to shave. Takes 5 seconds on other people, half a second on yourself. 
![image](https://cloud.githubusercontent.com/assets/19365096/22803644/c944489e-eee3-11e6-90fd-f1e23bec1598.png)

Currently not sure how to make it obtainable, someone decide

2017-02-09 21:35 UTC, N3X15 requested changes

2017-02-09 21:35 UTC, N3X15 commented on code/game/objects/items/weapons/cosmetics.dm
> +					user.visible_message("[user] shaves his facial hair clean with [src].", \
>his

YOU DON'T KNOW ME

And before you ask, yes, Character Setup lets females have facial hair.

2017-02-09 21:35 UTC, N3X15 commented on code/game/objects/items/weapons/cosmetics.dm
> +				to_chat(user,"<span class='warning'>There is not enough hair left to shave!</span>")
Balding has hair that can be shaved.

2017-02-09 21:35 UTC, N3X15 commented on code/game/objects/items/weapons/cosmetics.dm
> +					user.visible_message("[user] shaves his head with [src].", \
Needs more `\his`

2017-02-09 21:38 UTC, 9600bauds commented
Leave one of these in the bathrooms somewhere, have more orderable from C*rgo or an Autolathe I guess

2017-02-09 21:51 UTC, N3X15 approved these changes

2017-02-09 21:52 UTC, TheFriggenSawbones commented
bARBERS
'WHEN

2017-02-10 00:00 UTC, gbasood commented
@TheFriggenSawbones wyci
not like it's harder than skill capes

2017-02-10 00:42 UTC, Lokiamis commented
There should be one for the warden to use on prisoners, as is tradition.

2017-02-10 00:44 UTC, Probe1 commented
Add it to the Autolathe.  A crate in cargos silly.

2017-02-10 01:31 UTC, 9600bauds commented on code/game/machinery/autolathe.dm
> +		new /obj/item/weapon/razor, \
does this really not need the ()

2017-02-10 01:32 UTC, JustSumBody commented on code/game/machinery/autolathe.dm
> +		new /obj/item/weapon/razor, \
Wew, it worked without it. That's interesting

2017-02-10 01:39 UTC, JustSumBody commented
I detest mapping, if someone else wants to go for it.

2017-02-10 01:59 UTC, Shadowmech88 commented
You could avoid mapping if you put it in the code for the warden's locker.

2017-02-10 12:43 UTC, Ephx1 commented
This could be cool on the service borg module

2017-02-10 13:04 UTC, Probe1 commented
Something interesting for service borgs?  NO HAVE MORE DICE.

2017-02-12 05:43 UTC, merged