Messenger bag fixes and plastic civilian job tweaks
d3athrow/vgstation13 pull request #13926
Opened 2017-02-10 18:07 UTC by jknpj

Fixes chaplain and trader jobs not spawning with messenger bags and adds plastic bags for assistants and some civilian jobs. About plastic bags:

![bag](https://cloud.githubusercontent.com/assets/17928298/22838141/88eb05e8-efa2-11e6-9ce4-710757b9279a.png)

:cl:
 * bugfix: Fixes chaplain and traders not spawning with messenger bags
 * rsadd: Adds plastic bags to assistant, bartender, chef, botanist, cargo tech, janitor and librarian starting gear

2017-02-10 18:14 UTC, SonixApache commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
are you for real

2017-02-10 18:16 UTC, jknpj commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
it's a feature

2017-02-10 18:27 UTC, Skullyton commented on code/game/jobs/job/civilian.dm
> +		var/obj/item/weapon/storage/bag/plasticbag/shitterbag = new /obj/item/weapon/storage/bag/plasticbag(H)
>shitterbag

2017-02-10 18:41 UTC, yclatious commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
My sides

2017-02-10 19:40 UTC, Kurfursten commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
While funny, I don't think we should do this for the designated new player job. People might suffocate before learning the controls.

2017-02-10 22:12 UTC, Ephx1 commented
Cool, but when do you make them look not shit?

2017-02-10 22:42 UTC, jknpj commented
@Ephx1 when you sprite it

2017-02-10 23:42 UTC, Exxion commented
Wow, service will get plastic bags now

2017-02-10 23:43 UTC, Exxion commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
[Honk]

2017-02-10 23:49 UTC, despotate commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
If you can't learn the interface within one minute of joining you don't deserve to stay on this server

casuals please leave

2017-02-11 00:58 UTC, gbasood commented on code/game/jobs/job/assistant.dm
> +		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
remove

2017-02-11 00:59 UTC, gbasood requested changes
remove the RNG bag on head

2017-02-11 01:23 UTC, SonixApache commented on code/game/jobs/job/assistant.dm
> +	if(prob(1) && H.player_age >= 15)
I guess that works. Sort of.

2017-02-11 02:04 UTC, Probe1 commented
```

	if(prob(1) && H.client.player_age >= 15)
 		H.equip_or_collect(new /obj/item/weapon/storage/bag/plasticbag(H), slot_head)
 	else
 		H.put_in_hands(new /obj/item/weapon/storage/bag/plasticbag(H))

```

👁‍🗨

2017-02-12 17:56 UTC, gbasood approved these changes

2017-02-12 19:59 UTC, gbasood commented
Can you take a look at #13929 while you're at it

2017-02-12 20:00 UTC, Exxion commented
Did you actually read the OP, Sood?

2017-02-12 21:12 UTC, jknpj commented
@gbasood i fixed it, sorry for the trouble.

2017-02-13 01:15 UTC, merged