Supermatter Shards Can No Longer Be Invisible Sprayed
d3athrow/vgstation13 pull request #13936
Opened 2017-02-11 03:57 UTC by Shadowmech88

Fixes #13841

:cl:
 * tweak: The supermatter shard can no longer have invisible spray applied to it.

2017-02-11 04:01 UTC, F-OS commented
Rip fun.

2017-02-11 04:24 UTC, Aurantiaco commented
honk is dead

no honk

2017-02-11 04:34 UTC, Probe1 commented
I like how I open the game and hear people bitch about it.  I look at what it is  and it's clearly absurd.  Spraying it at all should irradiate the fuck out of you and possibly kill you.

But then I open github and hear about how its funny and no this is classic comedy.

You guys wonder why I sometimes don't treat your emojis like divine mandate.  This is why.

2017-02-11 04:36 UTC, N3X15 commented
Also this was considered during the invisibility spray PR and was rejected because it would, in fact, actually be funny.

2017-02-11 04:38 UTC, Probe1 commented
It turned out players didn't actually find it funny to walk into an invisible insta kill shard.

2017-02-11 05:12 UTC, BobdaBiscuit commented
People walk into the invisible insta kill shard anyway.
Hiding one in the same tile as a closed door is always comedy gold.

2017-02-11 05:18 UTC, mtpowell commented
>adds shard but not singularity

rev up them commits

2017-02-11 05:21 UTC, Probe1 commented
I ignored that @mtpowell because it actually is kinda impressive and funny to make the singlo vanish.

2017-02-11 05:24 UTC, mtpowell commented
@Probe1 
It's not too impressive, you can paint it invisible when it's stage one and doesn't pull/radiate. I'd argue it's even easier than the shard.

2017-02-11 05:28 UTC, Probe1 commented
Yeah you're right. I acknowledged that and wrote it off but really it's the exact same bullshit in the end.

2017-02-11 05:28 UTC, clusterfack commented
Why does this use preattack? This all would have been avoided if you had used afterattack instead.

2017-02-11 05:30 UTC, Probe1 commented
I assumed so he could avoid having clowns shard themselves.

2017-02-11 05:45 UTC, Shadowmech88 commented
Actually it was to prevent "You attack the X with the can of invisible spray!" messages.

2017-02-11 08:05 UTC, Kitfox88 commented
>I assumed so he could avoid having clowns shard themselves.

sacrifices must be made for the sake of honks

2017-02-11 11:32 UTC, PJB3005 requested changes

2017-02-11 11:32 UTC, PJB3005 commented on code/game/objects/items/weapons/cosmetics.dm
> +	for(var/i in prohibited_objects)
Use `is_type_in_list` instead.

2017-02-11 11:32 UTC, PJB3005 commented on code/game/objects/items/weapons/cosmetics.dm
> +	var/list/prohibited_objects = list( //For fun removal
Make this `/static`

2017-02-11 11:44 UTC, SonixApache commented
Making the spray activate the shard (but still make it invisible) might be a better move.

2017-02-11 14:38 UTC, Skullyton commented
After personally dealing with one of these things, I kinda disagree with making it impossible as it is possible to deal with.

Should ash the fucking clown that does it, but don't make it impossible

2017-02-11 20:06 UTC, StreptoMutans commented
You didn't listen

2017-02-13 17:06 UTC, gbasood commented
I think this is an important change but I will also miss it

2017-02-17 01:21 UTC, Shadowmech88 commented
* The supermatter shard is no longer exempted from being invisible sprayed, however doing so will cause you to touch the can to the shard, with results the same as touching the shard with any object.

2017-02-19 00:37 UTC, Sprok0 commented
Touching the shard with an item just deletes the item and irradiates you, sprays are one-use and you'll almost always have a radsuit if attempting this in the first place.

2017-02-19 21:54 UTC, PJB3005 approved these changes

2017-02-19 21:59 UTC, merged

2017-02-20 02:31 UTC, Killette2 commented
Greytide implant + invisible spray
"Clown, spray that shard for me"