Guillotine
d3athrow/vgstation13 pull request #13939
Opened 2017-02-11 09:00 UTC by Shadowmech88

![guillotine_open](https://cloud.githubusercontent.com/assets/3991927/22852655/30083c70-f006-11e6-9448-ae4cd8166725.png)
Adds a guillotine.
Humans can be buckled into it. The human is able to unbuckle themselves unless the stocks are closed via a verb, in which case it'll take them 30 seconds to get out.
The rope can be untied in 10 seconds via Alt+click, which will drop the blade and decapitate the victim. Alt+clicking again will raise the blade.

WebM of it in action: http://puu.sh/tY9B9/2365d5bedc.webm

2017-02-11 09:52 UTC, PJB3005 requested changes

2017-02-11 09:52 UTC, PJB3005 commented on code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
> +			M.visible_message(\
No backslashes here.

2017-02-11 09:52 UTC, PJB3005 commented on code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
> +		anchored = !anchored
The proc for a generic wrench based unanchor is obj level but I can't recall the name right now.

2017-02-11 10:11 UTC, Kurfursten commented on code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
> +		anchored = !anchored
wrenchanchor

2017-02-11 13:58 UTC, Ephx1 commented
Should give it a small chance to fail slicing cleanly, causing them to scream in agony and deal like 80 brute.

2017-02-11 16:00 UTC, CptWad commented
dealing 80 brute to your head would decapitate it anyway

2017-02-11 16:03 UTC, Ephx1 commented
Oh well you get my point anyways, messing it up miserably, causing bleeding and screaming,

2017-02-11 17:01 UTC, Exxion commented on code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
> +			M.visible_message(\
?????
Who cares?

2017-02-11 18:11 UTC, FudgePucker commented
IT GOES IT GOES IT GOES IT GOES

2017-02-11 18:13 UTC, Lokiamis commented
Would it be possible to have the head just drop slightly instead of flying up a tile?

2017-02-11 18:29 UTC, calzilla1 commented
Only if you add a bucket

2017-02-11 20:05 UTC, eplgr commented
I like the idea but I think it needs an animation and sounds.

2017-02-11 20:11 UTC, Exxion commented
Yo does this shit use resist yet

2017-02-15 03:32 UTC, diammz commented
![guillotine](https://cloud.githubusercontent.com/assets/25720704/22959553/a3412966-f337-11e6-97df-e34087f44394.gif)

https://my.mixtape.moe/xgrmve.dmi

2017-02-15 04:46 UTC, Blithering commented
Can you make it so that you can leave a candle on the same tile, that will slowly burn through the rope? I want to twirl my moustache at the dastardly deathtrap while the mime plays dramatic music on a piano in the background

2017-02-15 05:33 UTC, Shadowmech88 commented
It's going to be tricky to get the blade animation to synch up with the decapitation, but I'll try.

2017-02-15 07:52 UTC, diammz commented
im not much of a coder but you could split the animation into two parts, the blade falling and the cut+dangling rope and make it decapitate between the two

2017-02-15 12:25 UTC, PJB3005 commented
The issue is delays and timing with flick and such.

It's doable but very finnicky.

2017-02-15 12:45 UTC, PJB3005 commented on code/game/objects/structures/stool_bed_chair_nest/guillotine.dm
> +			M.visible_message(\
I do.

It's ugly.

2017-02-17 07:35 UTC, Shadowmech88 commented
* Escaping from a guillotine is now handled by the resist verb.

2017-02-17 09:45 UTC, Shadowmech88 commented
* Animation added to guillotine.
WebM of new and improved guillotine, with sound: http://puu.sh/u73de/aaf793a752.webm

2017-02-17 12:40 UTC, diammz commented
i see you improved the dangling rope animation, that looks much better

2017-02-17 16:04 UTC, Sprok0 commented
Does this have a delay before putting someone in it? If not, you can inescapably kill anyone nearby by putting them on it and closing the stocks via macro to skip the right-click menu.

2017-02-17 16:15 UTC, eplgr commented
It now looks _really_ good.

2017-02-17 20:07 UTC, Shadowmech88 commented
I didn't think about right-click macros.
I'll add a five-second delay to putting someone into the stocks.

2017-02-17 20:55 UTC, Shadowmech88 commented
* Placing someone into a guillotine now takes five seconds.

2017-02-20 04:30 UTC, unusualcrow commented
itgoesitgoesitgoesitgoesitgoesitgoesitgoesitgoes
/obscure reference

Looks pretty cool. Just needs a way to create it so it isn't adminbus only and then forgotten.

2017-02-20 04:32 UTC, Blithering commented
Maybe wood block + an executioner's sword or the blade of one?

2017-02-20 18:19 UTC, PJB3005 approved these changes

2017-02-20 18:23 UTC, merged