[WIP] AAC Fixes
d3athrow/vgstation13 pull request #13977
Opened 2017-02-13 01:45 UTC by N3X15

# Executive Summary
Fixes and improvements for the Atmospherics Automation Console.

# Changelog
:cl:
* rscadd: "AAC now has a \\"Run Once\\" button."

2017-02-13 22:24 UTC, PJB3005 requested changes

2017-02-13 22:24 UTC, PJB3005 commented on code/modules/atmos_automation/statements.dm
> +	if(user.restrained() || user.lying || user.stat)
`user.incapacitated()` gets the `user.restrained() || user.stat` checks here. Doesn't seem like a helper for lying exists though.

2017-02-13 22:24 UTC, PJB3005 commented on code/modules/atmos_automation/statements.dm
> +	if(user.mutations && user.mutations.len)
`in_range` already handles TK it seems.

2017-02-13 22:24 UTC, PJB3005 commented on code/modules/atmos_automation/statements.dm
> +		if ((!in_range(parent, user) || !istype(parent.loc, /turf)))
`isturf`

2017-02-13 23:23 UTC, N3X15 commented
Done @Probe1

2017-02-14 15:50 UTC, PJB3005 approved these changes

2017-02-14 21:47 UTC, merged