Adds a new HoS coat
d3athrow/vgstation13 pull request #13983
Opened 2017-02-13 05:21 UTC by Blithering

Adds a new design of HoS coat, because Sundowner is the smug coat wearing bastard every HoS wishes to be.
![sundownercoat2](https://cloud.githubusercontent.com/assets/15067109/22871676/08a0cc64-f1ab-11e6-9dd1-c32b5e4098a5.png)
The coat spawns in HoS lockers, replacing the duplicate Jensen coat.
plsnoconflicts

2017-02-13 05:21 UTC, kol1th commented
in game screenshots when

2017-02-13 05:29 UTC, 9600bauds commented
ingame screenshot

![ef8](https://cloud.githubusercontent.com/assets/6526157/22871940/3fd9666c-f194-11e6-87aa-3ab48a0b4302.jpg)

2017-02-13 05:43 UTC, kol1th commented
yes very good

2017-02-13 09:05 UTC, yclatious commented
>Traitor HoS going full sundowner on greyshits with energy machetes

Its the kind of thing you never knew you wanted but need.

2017-02-13 12:02 UTC, jknpj commented
Kids are cruel clown. And i am very in touch with my inner child!

2017-02-13 12:25 UTC, Probe1 commented
holy shit 
![download 1](https://cloud.githubusercontent.com/assets/8550416/22883298/8f05fe48-f1bd-11e6-876f-31902c49e24e.jpg)

2017-02-15 23:59 UTC, unusualcrow commented
looks kinda shitty tbh

2017-02-23 18:42 UTC, Probe1 requested changes

2017-02-23 18:42 UTC, Probe1 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		new /obj/item/clothing/suit/armor/hos/sundowner(src)
Keep the jensen coat and add the sundowner as well.

2017-02-23 18:45 UTC, Blithering commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		new /obj/item/clothing/suit/armor/hos/sundowner(src)
I considered that, but thought having an additional HoS armour to hand out every round might upset the balance.

2017-02-23 18:52 UTC, Probe1 commented
oh boy dmi conflicts

2017-02-23 18:53 UTC, Probe1 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		new /obj/item/clothing/suit/armor/hos/sundowner(src)
That's acceptable.

2017-02-24 00:05 UTC, Probe1 approved these changes

2017-02-24 01:28 UTC, Blithering commented
Fixed some of the janky shading on the sleeves and collar. 
![sundownercoat2](https://cloud.githubusercontent.com/assets/15067109/23286559/67bf6b64-fa30-11e6-9d64-be6cf1800147.png)
Minor change but it would have bugged me if I didnt.

2017-02-24 05:54 UTC, merged