Ports Anomaly containers from Bay
d3athrow/vgstation13 pull request #14002
Opened 2017-02-14 00:58 UTC by jknpj

![anomaly](https://cloud.githubusercontent.com/assets/17928298/22910088/84c7ac6e-f236-11e6-83ac-bd850a1a4442.png)
**A safe way to transport deadly shit.**

Finally a safe way for traders sell artifacts and xenoarchs to take their research to centcomm. Right now they can only store unknown artifacts, but they're pretty much the only kind of artifact that needs this kind of container.

:cl: 
 * rscadd: Adds Anomaly container, a safe way to transport and store unknown artifacts. They can be ordered from cargo for 50 zeny.

2017-02-14 08:23 UTC, Skullyton commented on code/datums/supplypacks.dm
> +	containertype = /obj/structure/closet/crate/secure/scisec
So it's a crate, locked inside a smaller secure crate?

2017-02-14 08:43 UTC, Shadowmech88 commented on code/datums/supplypacks.dm
> +	containertype = /obj/structure/closet/crate/secure/scisec
It'd make more sense for this kind of thing to be shipped in a big wooden box like what cows come in, wouldn't it?

2017-02-14 12:34 UTC, SonixApache commented
>50 zenny
fucking capcom piricing

2017-02-14 19:18 UTC, Kurfursten commented
But can it safely contain a damaged supermatter shard?

The containers shards come in don't take them back once they've been destabilized at all

2017-02-14 19:26 UTC, PJB3005 commented
> But can it safely contain a damaged supermatter shard?

Why should it?

2017-02-14 19:27 UTC, Kurfursten commented
>A safe way to transport deadly shit

2017-02-14 19:29 UTC, PJB3005 requested changes

2017-02-14 19:29 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +	if(Adjacent(user))
Needs to check `user.incapacitated` too.

2017-02-14 19:29 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +/obj/structure/anomaly_container/attack_robot(var/mob/user)
Should just make this call `attack_hand` outright probably.

2017-02-14 19:29 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +/obj/structure/anomaly_container/proc/release()
This could probably use logging.

2017-02-14 19:29 UTC, jknpj commented
>But can it safely contain a damaged supermatter shard?

It only contain unknown artifacts.

2017-02-14 19:30 UTC, Kurfursten commented
Well that's okay. It'd probably end up more desirable for engineering than science if it could.

2017-02-14 19:50 UTC, jknpj commented
We need those black supermatter containers to be ordeable too.

2017-02-14 20:12 UTC, PJB3005 commented
Order a new shard?

2017-02-14 20:16 UTC, Sprok0 commented
Those don't come in a shard box, just a normal crate. The special black shard crates are unique and can't be replaced.

2017-02-15 15:03 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +	if(Adjacent(user))
Still need to check for alive-ness here.

2017-02-15 16:10 UTC, jknpj commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +	if(Adjacent(user))
aren't ghosts incapacited?

2017-02-15 16:41 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/tools/anomaly_container.dm
> +	if(Adjacent(user))
The user could get killed after opening the alert window and still he adjacent.

2017-02-16 16:32 UTC, PJB3005 approved these changes

2017-02-16 17:05 UTC, merged