Cultify artifact only cultifies simulated tiles
d3athrow/vgstation13 pull request #14017
Opened 2017-02-14 20:53 UTC by Sprok0

Fixes part of #14006 where the effect would destroy unsimulated tiles, the rest is working as intended

2017-02-14 21:03 UTC, Exxion commented on code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cultify.dm
>  		for(var/turf/T in spiral_block(get_turf(holder), range))
You could just change this to `var/turf/simulated/T`
But either way works

2017-02-15 02:02 UTC, gbasood commented
hrm

2017-02-15 06:03 UTC, BobdaBiscuit commented
>the rest is working as intended

Plain deletion of windows and de-reinforcing of r-walls doesn't seem very good.

2017-02-15 06:50 UTC, PJB3005 approved these changes

2017-02-15 19:35 UTC, PJB3005 requested changes
I'm not keen on adding so much for loops and special cases. Using an argument to cultify to specify whether it should be "destructive" would be much better.

2017-02-15 19:38 UTC, Sprok0 commented
That seems like a whole lot of work for something this limited

2017-02-15 19:59 UTC, gbasood commented
I'm also in favor of arg to cultify

2017-02-15 20:23 UTC, Blithering commented
Is this effect separate from Nar'sie's cultifying effect?

2017-02-15 20:25 UTC, Sprok0 commented
This is only the artifact effect, which applies the nar'sie cultify effect to certain objects around for (mostly) aesthetic purposes. If I need to go through every actual cultify proc and add a non-destructive version to each one I'll just close this tbh.

2017-02-15 20:27 UTC, Blithering commented
Righto, was just making sure. Removing narnar's ability to turn everything into spooky junk would be a shame.

2017-02-16 19:49 UTC, Zth-- commented
Isn't having 1 loop instead of 4 faster?

2017-02-19 18:08 UTC, Sprok0 commented
I'll get back to this later

2017-02-19 18:08 UTC, closed without merging