[WIP] Chef RAMsay
d3athrow/vgstation13 pull request #14109
Opened 2017-02-19 19:21 UTC by jknpj

![chefbot](https://cloud.githubusercontent.com/assets/17928298/23105458/4779833c-f6be-11e6-802a-2beb256ef2e9.png)
https://webmshare.com/play/Vn1Wj
**WHAT IS THIS? WHO PUSHED THIS COMMIT? THIS [WIP] CHEF RAMSAY IS RAAAAAAAW!**

This is a port of goon's chefbot. It isn't here to make food for you, it isn't here to make your life easier. It is make here to make you a REAL chef <s>or the annoy the fuck out of you for making shitfood</s>.

It hunts and destroy any food with either shit reagents or over 10 units of corn oil and make your regret your choice of becoming a chef. When emaged it will destroy food WITHOUT shit reagents and taunt the fuck out any live being around him and explode when destroyed.

Right now there's no way to acquire him, so i need some ideas about how to make him obtainable. Other than that i'm welcoming quotes and harsh reviews about its shitcode since the original code was a mess and i'm pretty sure this has a lot of potential.

2017-02-19 19:23 UTC, Shadowmech88 commented
You could make him have a % chance to spawn when a burned mess is spawned.

2017-02-19 19:24 UTC, Exxion commented on goon/code/obj/machinery/bot/chefbot.dm
> +	var/shit_reagents = list(TOXIN,STOXIN,SLIMEJELLY,PLASMA,NANITES,HONKSERUM,SILENCER,DISCOUNT,AMATOXIN,PSILOCYBIN,CARPPHEROMONES,BUSTANUT,ROGAN,MOONROCKS,TOXICWASTE,CHEMICAL_WASTE,HORSEMEAT,OFFCOLORCH
Why no Silencer?
And I know why not minttoxin, but personally I think that should be allowed

2017-02-19 19:26 UTC, Exxion commented
He just like
Bursts out of the wall in a burning rage?
Fund it

2017-02-19 19:27 UTC, Shadowmech88 commented on goon/code/obj/machinery/bot/chefbot.dm
> +	var/shit_reagents = list(TOXIN,STOXIN,SLIMEJELLY,PLASMA,NANITES,HONKSERUM,SILENCER,DISCOUNT,AMATOXIN,PSILOCYBIN,CARPPHEROMONES,BUSTANUT,ROGAN,MOONROCKS,TOXICWASTE,CHEMICAL_WASTE,HORSEMEAT,OFFCOLORCH
Players can't even cook anything with mint toxin, can they?
RAMsay would just smash the mint in the backroom every time he's spawned.

2017-02-19 19:29 UTC, Ephx1 commented
Bursts out of the _Microwave_ in burning rage.

2017-02-19 19:29 UTC, unusualcrow commented
Make him buildable with a chef hat, a couple forks, and a box.

2017-02-19 19:35 UTC, jknpj commented on goon/code/obj/machinery/bot/chefbot.dm
> +	var/shit_reagents = list(TOXIN,STOXIN,SLIMEJELLY,PLASMA,NANITES,HONKSERUM,SILENCER,DISCOUNT,AMATOXIN,PSILOCYBIN,CARPPHEROMONES,BUSTANUT,ROGAN,MOONROCKS,TOXICWASTE,CHEMICAL_WASTE,HORSEMEAT,OFFCOLORCH
Being forced to stay silent after eating shitfood should not be torelable.

Minttoxin seems reasonable, as you start with it in your backroom.

2017-02-19 19:37 UTC, jknpj commented
@unusualcrow the thing makes buttbots look like child's play in the annoying scale, you don't want them flooding the station

2017-02-19 19:46 UTC, EmiliaMcWaifushitter commented
no ghandi's flip flop quote?

2017-02-19 19:50 UTC, eplgr commented
This is a feature that will guarantee the food is not harmful, right? With no effort being made.
Please take into account that fact.

2017-02-19 20:30 UTC, Exxion commented on goon/code/obj/machinery/bot/chefbot.dm
> +	var/shit_reagents = list(TOXIN,STOXIN,SLIMEJELLY,PLASMA,NANITES,HONKSERUM,SILENCER,DISCOUNT,AMATOXIN,PSILOCYBIN,CARPPHEROMONES,BUSTANUT,ROGAN,MOONROCKS,TOXICWASTE,CHEMICAL_WASTE,HORSEMEAT,OFFCOLORCH
I
Don't think Silencer actually mutes you

2017-02-19 21:20 UTC, jknpj commented on goon/code/obj/machinery/bot/chefbot.dm
> +	var/shit_reagents = list(TOXIN,STOXIN,SLIMEJELLY,PLASMA,NANITES,HONKSERUM,SILENCER,DISCOUNT,AMATOXIN,PSILOCYBIN,CARPPHEROMONES,BUSTANUT,ROGAN,MOONROCKS,TOXICWASTE,CHEMICAL_WASTE,HORSEMEAT,OFFCOLORCH
`/datum/reagent/drink/silencer/on_mob_life(var/mob/living/M)

	if(..())
		return 1
	M.silent = max(M.silent, 15)`

2017-02-19 21:49 UTC, Probe1 commented
DNM is for the wip title obviously but just throwing that out there.

2017-02-19 22:08 UTC, Ephx1 commented
Oh and about the way to get him. If you do go for something silly like him just appearing from shit food, have it be from a fully upgraded microwave. Or craftable with a microwave, two arms, speaker, chef's hat, prox sensor, and knife.

2017-02-19 22:22 UTC, jknpj commented
![thesalid](https://cloud.githubusercontent.com/assets/17928298/23107272/b19fceaa-f6d8-11e6-95f0-02219954b18b.jpg)

2017-02-19 22:22 UTC, Ephx1 commented
That's the delicious undercooked irony.

2017-02-19 22:25 UTC, Kurfursten commented
Pity this is probably going to hit before I can rewrite nutrition. It would be nice if Chef Ramsay would keep track of your cooking and berate you for too much fat / sweets / cholesterol.

2017-02-19 22:27 UTC, jknpj commented
We can rebuild him, we have the technology

2017-02-19 22:51 UTC, PJB3005 requested changes

2017-02-19 22:51 UTC, PJB3005 commented on goon/code/obj/machinery/bot/chefbot.dm
> +					if(findtext(M.wear_id:assignment, "chef") || findtext(M.wear_id:assignment, "cook"))
IT'S THE RUNTIME OPERATOR EVERYBODY RUN!

2017-02-19 22:51 UTC, PJB3005 commented on goon/code/obj/machinery/bot/chefbot.dm
> +						if(M.client.IsByondMember())
Not sure whether this is hilarious or we should give no incentive to support Byond.

2017-02-19 22:51 UTC, PJB3005 commented on goon/code/obj/machinery/bot/chefbot.dm
> +			if("fire")
Aren't there defines for this?

2017-02-19 22:51 UTC, PJB3005 commented on goon/code/obj/machinery/bot/chefbot.dm
> +			else
Wha

2017-02-20 00:14 UTC, Kurfursten commented on goon/code/obj/machinery/bot/chefbot.dm
> +						if(M.client.IsByondMember())
well, it's not really an incentive, the only thing that it is used for is to determine if he can ask if they "bought their [cooking] license"

seems harmless

2017-02-20 01:45 UTC, carshalash commented
Those roburger possibilities are fucking great

2017-02-20 05:58 UTC, kol1th commented
muh perspective

2017-02-20 14:25 UTC, unusualcrow commented
@jknpj https://my.mixtape.moe/nnnaot.ogg
Use this for the dramatic sound. 
There was a bit of a "tss" sound left over at the beginning from someone talking, so I cut that out and I turned up the volume a little since it was fairly quiet.

2017-02-20 15:54 UTC, unusualcrow commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
fucing

2017-02-23 18:54 UTC, PJB3005 approved these changes

2017-02-28 00:43 UTC, Probe1 requested changes
Fix it ignoring melee damage and the description.

Also consider having it bark out lines at random because unless it happens upon dodgy food it does nothing of interest.  Having a random bark() at passers would be good.

2017-02-28 00:43 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +	desc = "(icon, name, concept, and any kind of consistency or sense is currently pending)"
Whoops forgot something

2017-02-28 00:43 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +	on = 1 // ACTION
There's no way to turn it off.

2017-02-28 00:43 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +/obj/machinery/bot/chefbot/attackby(obj/item/W as obj, mob/user as mob)
There's no way to punch it but there's no attack delay on hitting it with anything else.  Don't worry though!  MELEE ATTACKING IT DOES NO DAMAGE.

2017-02-28 00:45 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +/obj/machinery/bot/chefbot/attackby(obj/item/W as obj, mob/user as mob)
Also you can kick it and that DOES do damage.

2017-02-28 02:47 UTC, Kurfursten commented on goon/code/obj/machinery/bot/chefbot.dm
> +/obj/machinery/bot/chefbot/attackby(obj/item/W as obj, mob/user as mob)
can you punch any bot? usually that opens a menu

2017-02-28 03:04 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +/obj/machinery/bot/chefbot/attackby(obj/item/W as obj, mob/user as mob)
Hopefully but probably not.  Still needs fixed, especially the complete lack of code handling being attacked by an object that isn't a projectile/beam/leg.

2017-02-28 05:11 UTC, Shadowmech88 commented on goon/code/obj/machinery/bot/chefbot.dm
> +	on = 1 // ACTION
Possibly intentional?

2017-02-28 22:36 UTC, jknpj commented on goon/code/obj/machinery/bot/chefbot.dm
> +	on = 1 // ACTION
It was intentional but i ended adding a kick_act to turn it off.

2017-03-01 02:01 UTC, unusualcrow commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
you did it again you DOUBLE SHITCODER

2017-03-01 03:46 UTC, Probe1 commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
i dont get it

2017-03-01 03:46 UTC, Probe1 approved these changes

2017-03-01 05:47 UTC, Shadowmech88 commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
This is probably a typo and should be fixed.

2017-03-01 08:59 UTC, jknpj commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
jesus christ

2017-03-01 08:59 UTC, jknpj commented on goon/code/obj/machinery/bot/chefbot.dm
> +					say("THIS [uppertext(shitfood.name)] [why_is_it_bad()][dork? ", DID YOU BUY YOUR FUCING COOKING LICENSE, [uppertext(dork)]?" : "!"]")
yeah i'm using an old version of the file, haha

2017-03-01 17:54 UTC, merged

2017-03-01 18:35 UTC, Shadowmech88 commented
Should there have been a changelog for this?

2017-03-01 18:47 UTC, Probe1 commented
Yeah there should have been but that's on me.