Snowmap Salvage: Wendigos
d3athrow/vgstation13 pull request #14115
Opened 2017-02-20 01:38 UTC by kol1th

Wendigos

- Can eat at corpses to regain lost health
- Can consume human corpses
- Evolution tree

Alpha wendigo - Can only be one on the map at a time through evolution

- Has an enrage level
- Lot of health
- Its attacks have a chance to throw and stun a person

![image](https://cloud.githubusercontent.com/assets/16979948/23109033/e08113aa-f6c9-11e6-82b4-cf71bfdadbce.png)
![image](https://cloud.githubusercontent.com/assets/16979948/23109041/f07b9be0-f6c9-11e6-9d3c-855f10fef084.png)

2017-02-20 02:02 UTC, Zth-- commented
How much is a "lot of health"? Because people already kill spider queens as if they were spiderlings

2017-02-20 02:03 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/wendigo.dm
> +		for(var/mob/living/simple_animal/hostile/wendigo/alpha/A in world)
Right, I was told to redo this, odd it didn't carry over.

You don't want it cycling through all of the world list, else we end up in some serious shit.

Here's what you'll need to do

>Make a global list related to wendigo alphas (See blobs/core)
>On wendigo/alpha New(), add the wendigo alpha to this list
>On Destroy, remove the wendigo alpha from the list

Then just have this list basically the same, except it's
>for(var/mob/living/simple_animal/hostile/wendigo/alpha/A in wendigo_alphas)

Basically https://github.com/d3athrow/vgstation13/pull/13711/files , doing this'll save you a whole lot of processing

2017-02-20 02:04 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/wendigo.dm
> +	if(health < 300 && enraged == 0)
Rather than having it hardcoded, have it check to see if they're at health of maxHealth

2017-02-20 02:06 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/wendigo.dm
> +						if(do_after(src, mob_target, 50, needhand = FALSE))
I have a bad feeling about this do_after, considering it'd be during a life() process.

Somebody test this with multiple wendigo attacking multple targets, corpses and living. If everything stops, have set waitfor = 0 at the top of this process

2017-02-20 02:20 UTC, Skullyton commented
@Zth-- 600, with healing as it chews at corpses scaling with its damage output

Spider queens have 500

2017-02-20 12:01 UTC, Riekland commented
>outlines on the sprites

2017-02-20 19:09 UTC, SkowronX commented
hueg wendigo needs some refinement, and some alteration to make it not look like a gorilla.

2017-02-20 19:55 UTC, Probe1 commented
Most sprites have some sort of outline or shading.  A notable example of what doesn't is the nuka cola vend which looks like hell.

2017-02-20 19:55 UTC, Shadowmech88 commented
Most sprites don't have a solid black outline.

2017-02-20 22:40 UTC, Skullyton commented
Most sprites aren't primarily black either

2017-02-21 03:17 UTC, gbasood commented on code/modules/mob/living/simple_animal/hostile/wendigo.dm
> +						if(do_after(src, mob_target, 50, needhand = FALSE))
Another problem being what's stopping the wendigo from taking other actions while the do_after is happening

2017-02-21 04:01 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/wendigo.dm
> +						if(do_after(src, mob_target, 50, needhand = FALSE))
Absolutely nothing and it's intended that way, you can potentially stop somebody from getting eaten by distracting it

2017-02-23 18:39 UTC, Probe1 requested changes
Address the reviews left by Dragonbro and Sood please.

2017-02-24 02:14 UTC, kol1th commented
For another time.

2017-02-24 02:14 UTC, closed without merging

2017-02-24 02:18 UTC, Skullyton commented
Hang on a minute