Fixes mobs changing direction in space to go after prey while drifting
d3athrow/vgstation13 pull request #14154
Opened 2017-02-23 01:40 UTC by Skullyton

While taking a look at how mobs move in space, I found that, while they do have a drifting capability in space, they tend to try and move towards their prey, shifting their angle of drift through sheer willpower alone.

After further research, I found that it was down to GoTo using walk_to to walk towards the target, which it would keep doing so each tick regardless of gravity, spacing, etc.

Now, should the offending mob be in space, it will have its walk_to reset by using walk(src,0). However, as it uses Process_Spacemove to check for if a mob may be exempt from such limitations such as gravity (See space carp) it does mean that mobs such as spider queens and ranged hivebots can navigate space as mobs by pushing off their own fired projectiles.

Tested, but as this affects general mob movement I can't guarantee all will be well.

Mobs that just walk around and are generally not spacefaring such as chickens and cows still wandered as normal.

2017-02-23 01:44 UTC, N3X15 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +			spaced = 0
Lattice also works (for humans, anyway).

2017-02-23 01:45 UTC, N3X15 requested changes

2017-02-23 01:45 UTC, N3X15 commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +			spaced = 0
Should also have a `break` here so that it breaks out of the loop after setting spaced to 0.

2017-02-23 03:42 UTC, Skullyton commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +			spaced = 0
Fair point, figured Process_Spacemove'd catch that, or it was a turf type.

The break's a good call, too

2017-02-23 04:26 UTC, Exxion commented
Wait what
Why can they push off projectiles?
Normally only dense AND anchored things work

Maybe there should be a general proc for this

2017-02-23 04:32 UTC, Skullyton commented
I would assume it'd be because projectiles are dense so they call bump on collision?

2017-02-23 04:35 UTC, Exxion commented
`Bump()` only cares about density of the thing being collided with, not the thing doing the colliding

2017-02-23 04:37 UTC, Skullyton commented
Projectiles are some strange and evil things

2017-02-23 04:38 UTC, Exxion commented
There is not a single thing about projectiles that makes sense

2017-02-23 12:16 UTC, Kitfox88 commented
Firing your gun and then jumping off the bullet is pretty awesome though.

2017-02-24 01:59 UTC, IzayaChan commented
This has killed me a few times

2017-02-24 10:21 UTC, Skullyton commented
Changes made, further review requested

2017-02-24 17:57 UTC, Exxion commented
This is going to make clearing the salvage shuttle very easy
Obviously I'm not suggesting we leave it in, because using bugs as balance is bad, but maybe we should  add some extra difficulty to the salvage shuttle after this is merged

2017-02-26 13:17 UTC, Kurfursten commented
Please get this in the game already, I am tired of Russians walking through space in zig zag patterns following a jetpack with nothing but a knife

2017-02-26 15:12 UTC, Intigracy commented
`>The reason this is here is to stop the curving of emitter shots.`
But that sounds cool what the fuck Agouri

2017-03-04 02:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +			spaced = 0
There is a break now, and it cheks for lattice, window, and grille

2017-03-06 00:38 UTC, Exxion commented
The curving of emitter shots by the singulo, I guess?
But
1. The singulo pulls anchored things anyway
2. There's an entirely separate thing used to prevent that

2017-03-08 21:30 UTC, N3X15 approved these changes

2017-03-08 21:31 UTC, merged