Suicide Disease Fix
d3athrow/vgstation13 pull request #14152
Opened 2017-02-22 18:49 UTC by MidnightGlow

:cl:
 * rscadd: Suicide disease should no longer cause a victim to suicide repeatedly.

2017-02-22 19:20 UTC, Aurx commented
I thought the issue was attempting suicide even when dead, not that suicide didn't work?  
This just makes it so that you can't dodge death for more than twenty seconds, not that you can't suicide again while dead unless there's some really strange interaction going on.

2017-02-22 19:47 UTC, MidnightGlow commented
Only other fix I could think of would be to not change the suiciding flag back to 0, but that would make the disease only able to kill you once. But I suppose that would also get rid of the bug? I couldn't reproduce the issue or find the exact cause, so this was just a workaround until someone had a better idea

2017-02-22 19:57 UTC, Aurx commented
Looking at the suicide effect code, it doesn't seem to actually check if you're alive or if you're already suiciding.  I'm not familiar with how life() works when you're dead.  There may have been a mistaken assumption made somewhere in there, but the simplest fix might just be to make the entire effect of effect/suicide conditional on `if not dead and not suiciding already`.  

Though the bit in life() that calls the bit that does virus shit is already in block that's not called if you're dead.  So I have no clue how the fuck the virus would be procing to cause dead people to suicide if they're fucking dead.  

I mean, if your fix works when you test it (you did test it, right?) then I have literally no clue what the fuck.

2017-02-22 21:20 UTC, MidnightGlow commented
It works, but I never could reproduce the issue exactly as reported anyway. My best guess is the person submitting the issue only thought they saw dead bodies suiciding but they were actually only close to dead? Either way, this worked when tested and should fix the problem

2017-02-22 23:55 UTC, eplgr commented
I think it works as intended and this is an awful change.
It's a fukken stage4 symptom, what do you expect to happen?

If someone puts you into cryo, and you come out, and you STILL have the virus, OF COURSE you should keep trying to kill yourself. It's a suicide syndrome.

The bottom line of this pr is "I put someone in cryo and it didn't fix him, pls remove this feature from the game".

2017-02-22 23:57 UTC, Aurx commented
@eplgr 
Read the fucking code.  Read the fucking issue.

2017-02-22 23:59 UTC, eplgr commented
I read the code way before all of these "issues" started to appear.

It's intended. If you are alive and infected with this virus, yes, you should suicide repeatedly.

2017-02-23 00:00 UTC, Aurx commented
@eplgr
Read the fucking code. Read the fucking issue.

2017-02-23 00:01 UTC, Exxion commented
@eplgr Read it a bit more closely, then

2017-02-23 00:02 UTC, eplgr commented
Oh, my bad, I thought you were refering to the virus2 code itself. Whoops.

2017-02-23 00:14 UTC, Probe1 commented
honk honk

2017-02-23 02:14 UTC, Intigracy commented
instead just put an `if(stat) return` at the top of the proc.

2017-02-23 02:15 UTC, Intigracy requested changes

2017-02-23 02:15 UTC, Intigracy commented on code/modules/virus2/effect/effect.dm
>  	mob.adjustOxyLoss(175 - mob.getToxLoss() - mob.getFireLoss() - mob.getBruteLoss() - mob.getOxyLoss())
also this needs to have a `min(0, `

2017-02-24 02:08 UTC, N3X15 commented
changelog should be a `bugfix`, not rscadd

2017-03-08 04:16 UTC, Probe1 commented
Dylans PR addressed it + conflicts + changes needed.  But don't think I don't love you all the same for trying and appreciate the time you gave us.

2017-03-08 04:16 UTC, closed without merging