Profiler and reboot for admins with +SERVER/+DEBUG, client skin stuff.
d3athrow/vgstation13 pull request #14255
Opened 2017-03-03 12:59 UTC by PJB3005

:cl:
* rscadd: All admins with `+DEBUG` or `+SERVER` now get profiler access, and having `+SERVER` grants you hard reboot access. There are buttons for this under the "Server" dropdown.
* rscadd: Renamed the "File" dropdown to "Client"
* rscadd: There is now a reconnect button under the "Client" drop down menu.

2017-03-05 00:14 UTC, Probe1 requested changes

2017-03-05 00:14 UTC, Probe1 commented on vgstation13.dme
> +#include "maps\test_tiny.dm"
Thanks Doc

2017-03-05 00:17 UTC, PJB3005 commented on vgstation13.dme
> +#include "maps\test_tiny.dm"
I'm a genius I'm telling you.

2017-03-05 00:23 UTC, Intigracy commented
Reboot isn't logged though, pls log.

2017-03-05 00:42 UTC, PJB3005 commented
@Intigracy if you'd read the diff you'd see I added logging.

2017-03-12 07:08 UTC, Probe1 approved these changes

2017-03-12 07:10 UTC, merged