pPS
d3athrow/vgstation13 pull request #14291
Opened 2017-03-08 15:15 UTC by jknpj

![pps](https://cloud.githubusercontent.com/assets/17928298/23709433/37773a78-03f8-11e7-925f-63afd2e7be32.png)

Adds pPS, the pAI Positioning System and tweaks the GPS to be able to see pAIs with it installed.

:cl:
 * rscadd: Adds pPS, the pAI positioning system. Avaiable for 10 memory.

2017-03-08 18:38 UTC, PJB3005 requested changes

2017-03-08 18:38 UTC, PJB3005 commented on code/modules/mob/living/silicon/pai/software.dm
> +				tag = copytext(sanitize(tag), 1, 20)
You should run this through `strict_ascii` for encoding compatability reasons.

2017-03-08 18:38 UTC, PJB3005 commented on code/modules/mob/living/silicon/pai/software.dm
> +					to_chat(src, "<span class = 'caution'>The tag must be four letters long!</span>")
You mean characters since you're not filtering out letters only.

2017-03-08 18:38 UTC, PJB3005 commented on code/modules/mob/living/silicon/pai/software.dm
> +		GPS_list.Add(src)
What's with the indents?

2017-03-08 18:38 UTC, PJB3005 commented on code/modules/mob/living/silicon/pai/software.dm
> +/mob/living/silicon/pai/proc/handle_list()
That's a really generic proc name for something so specific.

2017-03-08 18:38 UTC, PJB3005 commented on code/modules/mob/living/silicon/pai/software.dm
> +		if(istype(A, /mob/living/silicon/pai))
Copy paste.

2017-03-08 18:41 UTC, jknpj commented on code/modules/mob/living/silicon/pai/software.dm
> +		GPS_list.Add(src)
a mistake

2017-03-08 19:23 UTC, Kurfursten commented on code/modules/mob/living/silicon/pai/pai.dm
> +	var/pPS = 0 //Do we have pPS installed?
This variable shouldn't be necessary, right? You can just check the list of purchased software to see if it's owned

I guess you could make the argument that this saves searching a list but the performance hit is negligible I think

2017-03-09 15:16 UTC, jknpj commented on code/modules/mob/living/silicon/pai/pai.dm
> +	var/pPS = 0 //Do we have pPS installed?
It's a shameless way to check if we're in the GPS.List too.

2017-03-10 12:59 UTC, jknpj commented
Hold on i still have to debug this, something's fucky with the new ascii shit.

2017-03-11 22:34 UTC, PJB3005 approved these changes

2017-03-12 12:05 UTC, merged