Fixes morphing masks transforming the holder when put inside their pocket
d3athrow/vgstation13 pull request #14347
Opened 2017-03-14 13:32 UTC by jknpj

This also allowed you to keep the mask in your pocket after using the remove mask spell.

2017-03-14 17:17 UTC, Shadowmech88 commented
I'm pretty sure PJB wanted me to use `get_item_by_slot()` instead of accessing the mask slot var directly, but I can't remember why.

2017-03-14 17:26 UTC, PJB3005 commented
@Shadowmech88 here's why:

If somebody somewhere down the line makes inventory datums finally, he'll have to kill all direct variable reads. If we keep using `get_item_by_slot` that won't be an issue.

2017-03-14 17:27 UTC, PJB3005 requested changes
Figure out why `get_item_by_slot` is returning the wrong thing, don't fix it like this.

2017-03-14 17:51 UTC, Shadowmech88 commented
My guess is that the second argument to `equip()` passes the slot to which the item was equipped. So when you put it in your left pocket, it's likely checking `get_item_by_slot(slot_l_store)` since, I believe, `slot_l_store` would be what is passed as the second argument to `equip()`.

A solution might be checking `wear_mask == slot_wear_mask` or `get_item_by_slot(slot_wear_mask) == src`.

2017-03-15 12:16 UTC, jknpj commented
but `get_item_by_slot(slot_wear_mask) == src` is what is currenctly being used. I have no clue why this is happening but using a direct check works.

2017-03-15 12:27 UTC, Shadowmech88 commented
>but get_item_by_slot(slot_wear_mask) == src is what is currenctly being used

Incorrect.
What's being used is `get_item_by_slot(wear_mask) == src`.
`slot_wear_mask` is an inventory slot define.
`wear_mask` is a carbon-level var or, in this scope, whatever was passed as the second argument to `equip()`.

2017-03-15 12:32 UTC, jknpj commented
the more you know

2017-03-15 12:47 UTC, PJB3005 commented
@Shadowmech88 why did you even name that parameter like that.

2017-03-15 12:51 UTC, Shadowmech88 commented
Because that's how the happiest mask named the second argument in its `equipped()` and I was using that as a template.

2017-03-15 13:26 UTC, PJB3005 approved these changes

2017-03-15 21:28 UTC, merged