Extinguisher frames can now be dismantled
d3athrow/vgstation13 pull request #14395
Opened 2017-03-20 04:28 UTC by Skullyton

:cl:
* rscadd: Extinguisher cabinets can now be dismantled
* rscadd: Extinguisher frames can now be built from metal

2017-03-20 04:31 UTC, Orangerush commented
skullyton is /our guy/

2017-03-20 08:10 UTC, N3X15 approved these changes

2017-03-20 10:52 UTC, Zth-- commented
((((wiki))))

2017-03-20 12:20 UTC, Probe1 commented
Wiki then merge

2017-03-20 15:24 UTC, Exxion requested changes

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/items/mountable_frames/extinguisher_cabinet.dm
> +	desc = "For easy storage of extinguisher cabinets"
Period. Also, you're storing the cabinet?

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/structures/extinguisher.dm
> +	if(!WE.remove_fuel(1, user))
Does this check if the welder is actually on?

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/structures/extinguisher.dm
> +/obj/structure/extinguisher_cabinet
I think something is missing here

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/items/mountable_frames/extinguisher_cabinet.dm
> +	new /obj/structure/extinguisher_cabinet/empty(get_turf(src), get_dir(user, on_wall), 1)
Does the extinguisher cabinet properly set pixel offsets with `dir`?

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/structures/extinguisher.dm
> +		to_chat(user, "<span class='notice'>There is still an extinguisher inside</span>")
Period.

2017-03-20 15:24 UTC, Exxion commented on code/game/objects/structures/extinguisher.dm
> +		to_chat(user, "<span class='notice'>\The [src] needs to be open before you can dismantle it</span>")
Period.

2017-03-20 18:03 UTC, PJB3005 commented on code/game/objects/structures/extinguisher.dm
> +	if(!WE.remove_fuel(1, user))
It does.

2017-03-20 21:46 UTC, ComicIronic commented on code/game/objects/items/mountable_frames/extinguisher_cabinet.dm
> +	desc = "For easy storage of extinguisher cabinets"
What's the bet on extinguisher being replaced with extinguisher cabinet and this being missed?

2017-03-21 00:00 UTC, Skullyton commented on code/game/objects/items/mountable_frames/extinguisher_cabinet.dm
> +	new /obj/structure/extinguisher_cabinet/empty(get_turf(src), get_dir(user, on_wall), 1)
I'd hope so, every other frame mounting uses this

2017-03-21 00:29 UTC, Emilc4h commented
@Probe1 Wiki is updated.

2017-03-21 00:34 UTC, Skullyton commented
Thank you @Emilc4h

2017-03-21 02:28 UTC, Exxion approved these changes

2017-03-21 11:14 UTC, merged