firedoor deconstruction
d3athrow/vgstation13 pull request #14402
Opened 2017-03-20 23:54 UTC by Skullyton

:cl:
* rscadd: Firedoors can now be deconstructed, weld them then use a socket wrench on them
* rscadd: Adds firedoor frames you can use to construct firedoors

![carp hut beta 2017-03-20 234136](https://cloud.githubusercontent.com/assets/9110500/24126859/6921c8fc-0dc8-11e7-92c7-c3d4928fd6a6.png)

2017-03-21 00:03 UTC, FudgePucker commented
can you make the frames out of metal?
If so it might be griffable to just place like 20 of them in the hallways then flip the fire alarm. Socket wrenches are not everyday items you see on the station, and if you have access you can always just space all two of the only ones on the station.

2017-03-21 00:20 UTC, kernikov commented
Wouldn't that be as easy as adding a socket wrench step to construction, as long as the door isn't dense yet.

2017-03-21 00:24 UTC, Skullyton commented
Will do.

Same cost as a airlock frame?

2017-03-21 00:24 UTC, Skullyton commented
Wait, shit, that was a question.

@FudgePucker You can't make more of them as of right now.

2017-03-21 18:21 UTC, PJB3005 requested changes

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +/obj/item/firedoor_frame/proc/construct_firedoor(mob/user)
...Why not put this in the `attack_self` directly?

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +	if(!istype(user.loc,/turf))
`!isturf()`

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +	if(!user || !src)
`!src` is literally impossible.

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			if(!src)
Not possible.

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			if(src.loc != user)
Should check whether it's still in hands instead.

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			var/list/directions = new/list(cardinal)
What the unholy shit is this?

Just make it go by dir and check only once if that dir is blocked. This is so overengineered.

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			B.dir = dir_to_set
`B.change_dir(dir_to_set)`

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			for (var/obj/machinery/door/firedoor/B in user.loc)
Make this use `get_turf`. I'm pretty sure right now you could literally build firelocks inside lockers.

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			var/obj/machinery/door/firedoor/border_only/B = new(user.loc,0)
`get_turf`

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +			F.dir = SOUTHWEST
W-what?

2017-03-21 18:21 UTC, PJB3005 commented on code/game/machinery/doors/firedoor.dm
> +	if(istype(C, /obj/item/weapon/wrench/socket) && blocked)
Helpful error message if it isn't welded yet would be appreciated.

2017-03-21 18:21 UTC, SonixApache commented
a new age of advanced shittery is upon us

2017-03-21 19:19 UTC, Skullyton commented on code/game/machinery/doors/firedoor.dm
> +			var/list/directions = new/list(cardinal)
This is literally window placement code.

Two birds with one stone, we make a good way of doing firedoors, and we make better window code

2017-03-25 12:41 UTC, Skullyton commented
Right, border firedoor construction just checks if there is a firedoor facing that direction.

Turns out there is already a check to see if two border firedoors are on the same tile which would qdel the door, made that now drop the frame as well.

2017-03-27 11:56 UTC, SonixApache commented
Out of the scope of this PR, but should consider adding post-emag repair functionality.

2017-03-27 14:54 UTC, Skullyton commented
Looking at it, emagging sets blocked to TRUE.

So, repair would be just deconstructing and reconstructing the firedoor with a socket wrench.

2017-03-27 15:57 UTC, merged

2017-03-27 19:04 UTC, SonixApache commented
I found a firelock frame outside the box bridge on my local test serb, will test more.