Make small lightable objects not work in an environment with little oxygen
d3athrow/vgstation13 pull request #14418
Opened 2017-03-23 23:26 UTC by unusualcrow

Fixes #14417

Makes sense, right? 
No, I didn't touch welders.

:cl:
* tweak: You can no longer light lighters, matches, campfires, or cigarettes in space.

2017-03-23 23:29 UTC, BobdaBiscuit commented
>space heater needing oxygen to heat stuff up

Is it even fire based or is it something like a quartz/element based?

2017-03-23 23:35 UTC, unusualcrow commented
OH SHIT i meant to do that to the campfire type, not the space heater lemme fix

2017-03-23 23:45 UTC, unusualcrow commented
aw fuck build failed

2017-03-24 03:38 UTC, Probe1 commented on code/ATMOSPHERICS/hvac/spaceheater.dm
> +	if(!on && cell.charge > 0 && env.oxygen >= 5)
1.  Why is a campfire checking for cell charge what is this lazy copy paste shit.

2.  There should be feedback to the player that it didn't work and why.

2017-03-24 03:38 UTC, Probe1 requested changes
Add player feedback about the flame failing in some In Character language.

2017-03-24 07:03 UTC, PJB3005 commented on code/ATMOSPHERICS/hvac/spaceheater.dm
> +	if(!on && cell.charge > 0 && env.oxygen >= 5)
The cell charge is because of celt. That's just how the campfire works.

2017-03-24 07:34 UTC, CptWad commented
**The flame on the [src] goes out in a weak fashion.**

2017-03-24 08:44 UTC, IAGFPRMF commented
Sounds cool.

2017-03-24 13:24 UTC, Probe1 commented on code/ATMOSPHERICS/hvac/spaceheater.dm
> +	if(!on && cell.charge > 0 && env.oxygen >= 5)
Yeah. I'm still not gonna miss an opportunity to point out _what the fuck is this_.

2017-03-24 21:44 UTC, PJB3005 commented on code/game/objects/items/weapons/cigs_lighters.dm
> +		to_chat(M, "The flame on the [src] suddenly goes out in a weak fashion.")
`\the`

2017-03-24 22:24 UTC, PJB3005 requested changes

2017-03-24 22:24 UTC, PJB3005 commented on code/ATMOSPHERICS/hvac/spaceheater.dm
> +	var/datum/gas_mixture/env = T.return_air()\
Why is there a backslash here?

2017-03-24 22:24 UTC, PJB3005 commented on code/game/objects/items/weapons/cigs_lighters.dm
> +		to_chat(M, "The flame on the [src] suddenly goes out in a weak fashion.")
Also you're not guaranteed to have a holder, are you?

2017-03-24 22:24 UTC, PJB3005 commented on code/game/objects/items/weapons/cigs_lighters.dm
> +				to_chat(M, "<span class='notice'>The [name] suddenly goes out in a weak fashion.</span>")
`\The [src]`

2017-03-24 22:54 UTC, unusualcrow commented on code/ATMOSPHERICS/hvac/spaceheater.dm
> +	var/datum/gas_mixture/env = T.return_air()\
typo

2017-03-24 23:34 UTC, PJB3005 approved these changes

2017-03-24 23:48 UTC, Exxion commented on code/game/objects/items/weapons/cigs_lighters.dm
> +				to_chat(M, "<span class='notice'>\The [name] suddenly goes out in a weak fashion.</span>")
`[src]`, not `[name]`
But only for this one

2017-03-25 00:54 UTC, Probe1 approved these changes

2017-03-25 20:27 UTC, Zennyization commented
What about candles buddy?

2017-03-25 22:20 UTC, unusualcrow commented
>What about candles buddy?

done

2017-03-25 23:50 UTC, merged