Add table climbing
d3athrow/vgstation13 pull request #14421
Opened 2017-03-24 15:20 UTC by DamianX

The long awaited feature.

:cl:
 * rscadd: Added table climbing.

2017-03-24 15:23 UTC, kilozombie commented
please no

2017-03-24 15:24 UTC, Probe1 commented
You're not adding this without making significant revisions to every map to prevent people from waltzing into departments.

2017-03-24 15:24 UTC, kilozombie commented
Check that code

2017-03-24 15:25 UTC, Intigracy commented
10/10 code

2017-03-24 15:26 UTC, Probe1 commented
We've had enough meme PRs this season.  Label your PRs for what they do or don't make them at all please.

2017-03-24 17:09 UTC, Exxion commented
Quick someone post NO FUN ALLOWED

2017-03-24 17:52 UTC, Probe1 commented
![z7herxu](https://cloud.githubusercontent.com/assets/8550416/24307052/13b2dd42-1099-11e7-94ca-0d6ba62647d5.png)

2017-03-24 18:06 UTC, Exxion commented
Yeah that one

2017-03-26 14:27 UTC, troots commented
dont be a probe and read the code

2017-03-26 15:57 UTC, Probe1 commented
the sad truth is I read it but doubted myself and thought I didn't understand it.  so I went back to leave a comment and re-read the code while waking up and see if I could figure out how it worked.

turned out I was just dumb.

2017-03-26 18:41 UTC, Exxion commented
If you had opened this on April Fools', it would have been merged immediately, albeit only for a day

2017-03-26 19:02 UTC, Intigracy commented
Nah this is worth keeping around, it'd stop the adminhelps asking how to tableclimb.

2017-03-26 19:04 UTC, Exxion commented
Oh yeah, due to the sound it would also remove the use of a bar deskbell
Ship it

2017-03-27 00:09 UTC, ihadtoregisterforthis commented
>4 days into the season 
>We've had enough meme PRs this season

2017-03-31 18:33 UTC, Intigracy commented
I'll merge this tomorrow.

2017-03-31 18:39 UTC, kilozombie commented
yis

2017-03-31 18:43 UTC, Intigracy requested changes
few small things

2017-03-31 18:43 UTC, Intigracy commented on code/game/objects/structures/tables_racks.dm
> +	M.visible_message("<span class='danger'>You bang your head on \the [src.name].</span>", "<span class='danger'>[usr] bangs his head on \the [src.name].</span>", "You hear a bang.")
change the `[src.name]`s to `[src]`

`bangs his head` needs to be `bangs \his head`

2017-03-31 18:43 UTC, Intigracy commented on code/game/objects/structures/tables_racks.dm
> +	if(O != user || !ishuman(usr) || !in_range(src, usr) || usr.incapacitated() || usr.lying) // Doesn't work if you're not dragging yourself, not a human, not in range or incapacitated
`!in_range(src, usr)` should be `!Adjacent(user)`

replace usr with user for these, usr isn't very sane

2017-03-31 19:09 UTC, Exxion commented on code/game/objects/structures/tables_racks.dm
> +	M.visible_message("<span class='danger'>You bang your head on \the [src.name].</span>", "<span class='danger'>[usr] bangs his head on \the [src.name].</span>", "You hear a bang.")
Also another [usr]

2017-03-31 19:45 UTC, DamianX commented
Oh fuck the madman reopened it

2017-03-31 20:04 UTC, SonixApache commented
proper title when

2017-03-31 20:04 UTC, Exxion commented
You bungled it
He said change them to `[src]`, not `[name]`

2017-03-31 20:05 UTC, Exxion commented
@SonixApache Never

1. Get a calendar
2. Shut up

2017-03-31 20:08 UTC, DamianX commented
It doesn't NOT work though, I wonder if there's a difference.

2017-03-31 20:08 UTC, Intigracy requested changes

2017-03-31 20:08 UTC, Intigracy commented on code/game/objects/structures/tables_racks.dm
> +	M.visible_message("<span class='danger'>You bang your head on \the [name].</span>", "<span class='danger'>[user] bangs \his head on \the [name].</span>", "You hear a bang.")
`>[name]`

lmao it needs to be `[src]`

2017-03-31 20:09 UTC, Intigracy commented
Just a standard we apply.

Doing [src] automatically allows reference of gender (with \his) and a few other things

2017-03-31 20:10 UTC, Intigracy approved these changes

2017-03-31 20:23 UTC, Exxion commented
It DOES not work, actually.
If `src` were a proper noun, it would not appear properly if you used `[name]`

2017-04-01 02:12 UTC, merged

2017-04-01 02:17 UTC, Intigracy commented
this shouldn't ever get reverted

2017-04-03 06:43 UTC, kernikov commented
>doesn't apply brain damage

smh

2017-04-03 07:46 UTC, DamianX commented
You think I didn't think about it?