the Strike Team rewrite
d3athrow/vgstation13 pull request #14446
Opened 2017-03-27 21:57 UTC by JMWTurner

Moved from #13611 

It's happening!

Here's how strike team work now:
* When a strike team is called, a message is sent to every ghost that isn't job-banned from Strike Teams. After a minute, if at least one ghost applied, every selected applicant gets spawned at their spawning landmarks.
* If there are enough commando, one of them might be a leader. Other commando have to follow his orders. The deathsquad leader (Creed) can spawn when there are at least 4 deathsquads, the ERT leader always spawn even if he's alone, the Elite Syndicate strike teams don't have leaders.

The revamp isn't fully over though, next come the map changes. I'll wait for this part to go through.

![secret](https://cloud.githubusercontent.com/assets/21122521/22229837/74b4dbd8-e1da-11e6-837d-f4dbe7e80586.png)
![save](https://cloud.githubusercontent.com/assets/21122521/22229839/75c8b936-e1da-11e6-958e-09fcf533fa26.png)
![recruit](https://cloud.githubusercontent.com/assets/21122521/22229842/77b9a3fe-e1da-11e6-90d8-6fd6b51dcd2b.png)
![bravo](https://cloud.githubusercontent.com/assets/21122521/22229844/78a0c978-e1da-11e6-92c7-57055bcb67c6.png)

These changes will allow new/custom strike teams to be easy to implement, and remove heaps of snowflaking (like seriously, whoever created ERTs, I'm looking at you)

:cl:
* rscadd: Added strike team datums, thus purging lots of copypasted code, and allowing for the easy adding of new strike teams types.
* tweak: Removed the JoinResponseTeam and the like buttons. Now ghosts join strike teams just like dionae and posibrains.
* rscadd: The strike team buttons for admins have been grouped together for easy use.
* experimental: Added framework for custom strike teams.
* tweak: Syndicate Elite Strike Teams now spawn with OSIPR instead of pulse rifles. Although they still cannot reach the station on most maps yet.

2017-03-27 21:58 UTC, JMWTurner commented
I'll now work on fixing the issues that were pointed out in the original PR

2017-03-27 22:25 UTC, JMWTurner commented
There we go.

2017-03-27 22:44 UTC, JMWTurner commented
I stop coding in DM for a few months and I can't even write defines anymore. This is just sad.

2017-03-29 23:29 UTC, PJB3005 requested changes

2017-03-29 23:29 UTC, PJB3005 commented on __DEFINES/setup.dm
> +#define TEAM_DEATHSQUAD			"Death Squad"
Put this in its own file, not `setup.dm`

2017-03-29 23:29 UTC, PJB3005 commented on code/game/machinery/computer/communications.dm
> +	var/sent = 0
So, `var/sent = sentStrikeTeams(TEAM_ERT)`?

2017-03-30 01:19 UTC, JMWTurner commented
done

2017-03-30 07:18 UTC, JMWTurner commented
actually done

2017-03-30 15:45 UTC, PJB3005 approved these changes

2017-03-30 22:44 UTC, merged

2017-03-30 22:44 UTC, Probe1 commented
![choo-choo-train-images-chootrain](https://cloud.githubusercontent.com/assets/8550416/24529329/f446dd70-1578-11e7-8d27-4e5263bd4f03.gif)