[WIP] Adds more xenoarch large artifact triggers, adds manual trigger picking to the admin spawn option
d3athrow/vgstation13 pull request #14448
Opened 2017-03-27 23:24 UTC by BobdaBiscuit

U N A T O M I C for testing purposes, if you want anything separated out let me know.

Uses the new trigger datums to add in some new triggers, mostly as an example.

Will be committing mostly finished and tested portions when finished.

TODO:
- [x] Manual trigger picking for admin spawned artifacts.
- [ ] Light level based trigger.
- [ ] Come up with new triggers, send help.
- [ ] Test everything.

2017-03-27 23:38 UTC, Skullyton commented on code/modules/admin/topic.dm
> +					var/answer2 = alert("Randomly generated triggers (safer), or manually picked (might break certain effects)?",,"Random","Manual")
Double comma drifting?

2017-03-27 23:40 UTC, BobdaBiscuit commented on code/modules/admin/topic.dm
> +					var/answer2 = alert("Randomly generated triggers (safer), or manually picked (might break certain effects)?",,"Random","Manual")
Copy pasted from the original code, I assume there's an argument that's by default there.

I can shove a null or something there if you want.

2017-03-28 02:32 UTC, BobdaBiscuit commented
\>left some copy paste comments in from the singulobeacon
WHOOPSIES

2017-03-28 04:20 UTC, Yelier commented
Here's some trigger ideas:
-Blood shed near it
-Light level
-Bike horn (I know you have sound down already, but HONK)
-Being on a fire tile
-Hit with a Bible/null rod

2017-03-28 04:22 UTC, BobdaBiscuit commented
Light's actually already finished in this pr, blood and fire could be good though.

I'm wanting to avoid "rub x on artifact" triggers as much as possible as energy already has a few of them.

2017-03-28 04:26 UTC, Yelier commented
Oh, my bad. Didn't see the part where you said you had done light.

Also, how about an "insert credits" trigger? Or is that too close to "energy trigger"?

2017-03-28 04:32 UTC, BobdaBiscuit commented
A pay2use trigger would be pretty funny/unique in itself, could most likely give it an internal timer so it runs for a time depending on how much money it has,

2017-03-28 09:41 UTC, Shadowmech88 commented
>Activates when no one is looking

Does this check for all mobs, or just clients looking at it?

2017-03-28 10:00 UTC, Shadowmech88 commented
Also some more ideas:
* Artifact requests sacrifice of specific mobs, requiring them to be killed in the artifact's view.
* Artifact requires a living player to touch it to activate its effect, using them as a conduit and dealing quite a bit of damage to them in the process. Could even make a similar version for aura effects which damages the player more slowly over time as long as they remain adjacent to the artifact.
* Artifact must be traveling at a certain speed in order to remain active (Easiest way to do this would probably be to have it store its current turf and the `world.time` on each `process()`, then on the next process check the distance from its current turf to the stored turf and use the difference in `world.time` to calculate average speed.
* Artifact activates when destroyed, such as via an explosion. Obviously only good for a single activation, so its effect would need to be pretty good to balance that.
* Artifact activates when caught in an `ex_act()` that *doesn't* destroy it, such as an IED.
* Artifact requests that the one who would activate it inflict some sort of injury on themself. Would really only work for effects that get applied to a single person.
* Artifact requests to be fed a random food item or beverage.

2017-03-28 11:57 UTC, jknpj commented
Nuke artifact when?

2017-03-28 12:12 UTC, Skullyton commented
Artifact effect thats triggered when an artifact is triggered nearby

2017-03-28 15:06 UTC, BobdaBiscuit commented
>Nuke artifact when? Triggered by the actual nuke disk, of course.

Will most likely be in an update when I make some rarer "super effects" that need more effort to activate.

2017-03-29 23:24 UTC, PJB3005 requested changes

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			spawn(1)
Is this `spawn` still needed?

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		spawn(1)	//delay logging so if admin tools override/other fuckery occurs the logs still end up correct
Is this `spawn` still needed?

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/trigger.dm
> +	..()
To do sanity just check the result of `my_artifact.Topic()` here.

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_electricity.dm
> +/datum/artifact_trigger/electricity/Destroy()
?

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_light.dm
> +/datum/artifact_trigger/light/Destroy()
?

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_light.dm
> +		else if(my_effect.activated)
Not sure whether this `if` is needed since it's the else.

2017-03-29 23:24 UTC, PJB3005 commented on code/modules/research/xenoarchaeology/artifact/triggers/unknown_trigger_pay2use.dm
> +		toucher << browse(dat, "window=anomaly;size=450x500")
Make this use browser datums, please.

2017-03-30 12:31 UTC, BobdaBiscuit commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		spawn(1)	//delay logging so if admin tools override/other fuckery occurs the logs still end up correct
Yes, in some instances effects need to manually override their trigger from whatever is generated, ie forcefield forces a touch trigger etc.

In a future pr I plan to sort it out so it doesn't need that.

2017-03-30 12:31 UTC, BobdaBiscuit commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			spawn(1)
Yes, in some instances effects need to manually override their trigger from whatever is generated, ie forcefield forces a touch trigger etc.

In a future pr I plan to sort it out so it doesn't need that.

2017-03-30 14:05 UTC, PJB3005 approved these changes

2017-04-02 21:12 UTC, merged