[WIP] Scootaloos
d3athrow/vgstation13 pull request #14499
Opened 2017-04-01 07:43 UTC by unid15

![april fools ?](https://cloud.githubusercontent.com/assets/9512290/24576600/02572b8a-16bf-11e7-951d-9a1722f1feed.gif)

TODO:

* [ ] Life() proc

* [ ] Health and damage systems

* [ ] Fix shit

* [ ] Put description here

:cl:
 * rscadd: Added octopuses

2017-04-01 08:17 UTC, Probe1 requested changes

2017-04-01 08:17 UTC, Probe1 commented on cfg/admin.txt
> +unid role=admin
derp

2017-04-01 08:17 UTC, Probe1 commented on code/modules/mob/living/carbon/alien/alien.dm
> +	return EYECHECK_FULL_PROTECTION
👌

2017-04-01 08:17 UTC, Probe1 commented on code/modules/mob/living/carbon/martian/examine.dm
> +				msg += "<B>It has severe bruising!</B>\n"
Do we use ```<b>``` tags for bolding text?  I vaguely remember it being some span stuff.

2017-04-01 08:17 UTC, Probe1 commented on code/modules/mob/living/carbon/martian/examine.dm
> +	msg += "*---------*</span>"
What the hecks this code doing?

2017-04-01 08:17 UTC, Probe1 commented on vgstation13.dme
> +#include "maps\test_tiny.dm"
💯

2017-04-01 08:49 UTC, SonixApache commented
the name is retarded

2017-04-01 08:51 UTC, Iamgoofball commented on code/modules/mob/living/carbon/martian/examine.dm
> +				msg += "<B>It has severe bruising!</B>\n"
`<span class = 'danger'>`

2017-04-01 08:53 UTC, carshalash commented
Its the name that won the polls.

2017-04-01 09:16 UTC, ultraplen commented
Is this an april fools joke or will we actually be getting jellyfish-people ?

2017-04-01 10:35 UTC, SonixApache commented
@carshalash that doesn't make it any less retarded

2017-04-01 13:51 UTC, BobdaBiscuit commented on cfg/admin.txt
> +unid role=admin
sneaky coders at it again

2017-04-01 14:26 UTC, NigglyWiggly commented
_**YES**_

2017-04-01 15:14 UTC, Kitfox88 commented
gonna need to sprite some metal slug outfits for the costume vendor

2017-04-01 15:50 UTC, PJB3005 commented on cfg/admin.txt
> +unid role=admin
Won't matter anyways, this file is overriden automatically by the server.

2017-04-01 15:52 UTC, Kurfursten commented
Is the intent to ever make this a roundstart race option, or just for adminbus? If the answer is the former, implementing it as a species like every other race rather than as its own mob type is probably(?) preferable. Knowing whether it is or not really shapes the nature of a lot of discussion. If it's just a gimmick race, no problem, but otherwise we might need to talk about how a lack of space protection / inability to walk over shards / inability to wear gloves would shut out quite a few jobs.

I'd also like it if you posted a full list of pros and cons, I believe I saw in their code they don't drop things when slipped, which is great because otherwise it would be totally impossible to play a sec officer or something as a scootaloo (always carrying tasers in hand) -- and also that they have full welding protection.

2017-04-01 16:52 UTC, Ephx1 commented
> Roundstart race option

Only if we remove Skeletons and Vox.

2017-04-01 17:57 UTC, Intigracy commented on code/modules/mob/living/carbon/martian/examine.dm
> +	msg += "*---------*</span>"
It's there on every mob examine if you'd notice ingame, it marks the end of the examine for easy viewing.

2017-04-01 18:00 UTC, unid15 commented
They're never ever becoming a species until we get an organ rework and an inventory slot rework

2017-04-01 18:45 UTC, Intigracy commented
But my aunt's name is Scootaloo

2017-04-01 18:55 UTC, Riekland commented
um actually the plural of octupus is octopussyi sweetie xx

2017-04-01 19:34 UTC, Kurfursten commented
Cool; since they're not really a 'for real' job consideration doesn't matter

Go nuts!

2017-04-01 21:59 UTC, invoid9 commented
Is voting for the name still an option? My vote goes to Quagaar, since their head kinda looks like a fucked up roast chicken.

2017-04-01 22:34 UTC, Ephx1 commented
Quagaar warrior job when?

2017-04-01 23:11 UTC, adu6oo commented
if these arent round start im going to shoot myself irl. other than that the pr looks great and i cannot wait

2017-04-02 03:49 UTC, TheFriggenSawbones commented
you're a blessed man unid

2017-05-19 06:35 UTC, Intigracy commented
Finish it my man

2017-05-27 15:45 UTC, unid15 commented
I'm currently taking a break, if any of you guys want to pick this up you're welcome to do so, and I'll gladly try to help if any questions come up

2017-06-12 02:20 UTC, closed without merging