Drag damage now checks for bleeding or fractures
d3athrow/vgstation13 pull request #14535
Opened 2017-04-04 06:58 UTC by SonixApache

There's now two procs, drag_damage and drag_damage_crit. 
Drag_damage checks for gravity, then checks if the target is bleeding or has an unsplinted fracture, and applies damage from there.
Should be less of a hassle.
Tested.

:cl:
 - tweak: Drag damage now applies only if someone is bleeding or has unsplinted fractures -- not just if they have brute damage.
 - tweak: Drag damage shouldn't apply to AIs anymore.

2017-04-04 08:56 UTC, Skullyton commented
maybe rather than applying a generic brute damage to the person, you apply it to the injured limb?

It's odd that dragging a guy with a broken foot might make their arm break

2017-04-04 09:00 UTC, SonixApache commented
Sounds logical, working on that now.

2017-04-04 13:38 UTC, Probe1 commented
Consolidate that changelog into a couple lines.

2017-04-04 13:44 UTC, SonixApache commented
Like so?

2017-04-04 14:00 UTC, SonixApache commented
should be good for check

2017-04-04 15:11 UTC, PJB3005 approved these changes

2017-04-04 18:07 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
What happens if you do `for(x in null)? Alternatively, to avoid these questions, make drag_damage always return an empty list.

2017-04-04 19:04 UTC, PJB3005 commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
for x in null just doesn't iterate at all IIRC.

2017-04-04 20:02 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
Doesn't mob.dm line 1309 mean it'll always return a list anyway?

2017-04-04 23:06 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
Not if they're non-human.

2017-04-04 23:27 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
True, but drag_damage checks for humans anyway, so it shouldn't ever try to pull a null list.

2017-04-04 23:31 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
Yeah but that's what I mean. If it's not human, there is no return value, so Byond returns null.

ALSO

drag_damage should *not* be typechecking src, human should overwrite it.

2017-04-04 23:47 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
what

2017-04-05 00:00 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
```
proc/my_proc()
    if(a)
        return list()
    // but what if !a?
```

2017-04-05 05:57 UTC, Probe1 commented
Yeah that cl is great @SonixApache .  I know its picky but no one needs 6 new lines on the same topic.  Peoples attention span is shorter than this comment and you really wanna drive the high points home and let them check github for the gritty details.

2017-04-05 08:35 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
on the former, i could just else return list()
but what do you mean with the typechecking part?

2017-04-05 14:16 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
```
/a/proc/blep()
    if(istype(src, /a/b))
        do_thing()
    else
        do_other_thing()
```
is bad.
```
/a/proc/blep()
    do_other_thing()

/a/b/blep()
    do_thing()
```
is correct.

2017-04-05 17:08 UTC, Kurfursten commented
Is it okay to use colons in changelogs now? That won't fuck anything up?

2017-04-05 17:14 UTC, PJB3005 commented
Yes because you're not writing YAML anymore.

2017-04-06 12:42 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
I don't understand why that's good or bad, but more importantly, I don't really understand what you're saying I *should* do.

Keep the mob-level drag_damage() proc but make it not return a list of organs, and make drag_damage_human() at the human level that does?

2017-04-06 16:07 UTC, Shadowmech88 commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
>and make drag_damage_human()

No, you'd have
`/mob/proc/drag_damage()` and `/mob/living/carbon/human/drag_damage()`

2017-04-06 16:09 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
In the same file? How does that even work? Doesn't the first overwrite the second?

2017-04-06 17:33 UTC, Kurfursten commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
Override not overwrite, which is the point. Only children of human get behavior B.

As for the file, it doesn't matter which file you put the procs in (as our misadventure with bottle overlays demonstrates).

2017-04-06 17:51 UTC, ComicIronic commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
@SonixApache It's called polymorphism - not having to know a type at runtime to use its implementation of an interface. In nearly all languages, `istype()` has no equivalent and is considered a type sin.

2017-04-06 19:52 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
Think I get it, will make changes.

2017-04-07 11:53 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +									for(var/datum/organ/external/damagedorgan in M.drag_damage())
changes made, czech it out

2017-04-07 11:55 UTC, SonixApache commented
*conflicts*

2017-04-07 12:05 UTC, SonixApache commented
hey cool conflicts resolved

2017-04-07 15:14 UTC, SonixApache commented
oh nice, it merged other branches

2017-04-07 15:29 UTC, SonixApache commented
compiled, tested, seems good

2017-04-07 15:44 UTC, PJB3005 requested changes

2017-04-07 15:44 UTC, PJB3005 commented on code/modules/mob/living/living.dm
> +							if(HM.drag_damage() && !(HM.health - HM.halloss <= config.health_threshold_softcrit))
Make a helper for checking crit instead.

2017-04-07 15:53 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +							if(HM.drag_damage() && !(HM.health - HM.halloss <= config.health_threshold_softcrit))
aaaaaaaaaaaaaaaa

2017-04-07 17:11 UTC, SonixApache commented on code/modules/mob/living/living.dm
> +							if(HM.drag_damage() && !(HM.health - HM.halloss <= config.health_threshold_softcrit))
dooooooone

2017-04-07 17:12 UTC, SonixApache commented
helper seems to work

2017-04-07 18:32 UTC, PJB3005 requested changes

2017-04-07 18:32 UTC, PJB3005 commented on code/__HELPERS/_macros.dm
> +#define isincrit(A) (A.health - A.halloss <= config.health_threshold_softcrit)
Don't use a macro for this, use a proc on the mob.

2017-04-07 20:18 UTC, SonixApache commented on code/__HELPERS/_macros.dm
> +#define isincrit(A) (A.health - A.halloss <= config.health_threshold_softcrit)
you're killing me, PJB

2017-04-07 20:36 UTC, SonixApache commented on code/__HELPERS/_macros.dm
> +#define isincrit(A) (A.health - A.halloss <= config.health_threshold_softcrit)
WAIT WHY IS THIS

2017-04-07 20:39 UTC, ghost requested changes
Procs left in weird places, it'll lead to bad things further down the line when somebody wants to make modifications.

2017-04-07 20:39 UTC, Skullyton commented on code/modules/mob/mob.dm
> +mob/living/carbon/human/isincrit()
Bad idea to leave procs referring to objects in unrelated files willy nilly. Should've said this in the discord, sorry. Put this proc in human_damage.dm or something relating to human helper procs and the mob/proc in mob_helpers.dm

2017-04-07 20:39 UTC, Skullyton commented on code/modules/mob/mob.dm
> +/mob/living/carbon/human/drag_damage()
Same stuff for these two

2017-04-07 21:26 UTC, SonixApache commented
moving procs and debugging icon updating

2017-04-07 21:38 UTC, SonixApache commented
and that one's done

2017-04-10 17:02 UTC, SonixApache commented
@PJB3005 pls

2017-04-10 20:33 UTC, PJB3005 approved these changes

2017-04-10 20:33 UTC, merged