Fish tanks 3.0
d3athrow/vgstation13 pull request #14569
Opened 2017-04-06 15:17 UTC by jakmak6

remake of https://github.com/vgstation-coders/vgstation13/pull/13992

Ports paradises fish tanks and sushi recipes.

Here is a webm of it in action

https://puu.sh/tJkcW/16db19a379.webm

You can make the boards for the fish tank and large fish tank via solder or order them from cargo

The eggs and fish care tools are bough from cargo in the aqua culture crate and the exotic fish eggs crate.

To add fish in just insert water and fish eggs to the tank and use the fish egg scoop to harvest any eggs that the fish lay. Re add the eggs to get more fish and use the net to pull fish out of the tank. Use the fish brush to clean the gunk off the tank to ensure happy and healthy fish.

Once harvested salmon and catfish can be gutted using any knife as so they could be used for making fish related recipes

here are the new sprites for the tanks courtesy of cptwad.

https://puu.sh/tZUFw/514a26d7a6.png

Other than the new sprites the code for the fishtanks and fixing sharkteeth code hasnt been changed

2017-04-06 15:29 UTC, DamianX commented on code/datums/supplypacks.dm
> +	name = "Aquaculture Supply"
supply vs Supply

2017-04-06 15:29 UTC, DamianX commented on code/datums/supplypacks.dm
> +	name = "Exotic Fish"
fish vs Fish

2017-04-06 15:41 UTC, yclatious commented
Are shark teeth compatible with the mayan weapon? Itd be neat if they were

2017-04-06 17:52 UTC, Kurfursten commented
Did you fix all that stuff from last time?

2017-04-06 18:07 UTC, jakmak6 commented
probably not

2017-04-06 19:22 UTC, Shadowmech88 commented
Shark teeth *could* be compatible with the macuahuitl if they were children of glass shards.

2017-04-06 19:27 UTC, Kurfursten commented
As mentioned before though, that would mean they wouldn't have teeth behaviors

2017-04-06 19:30 UTC, Shadowmech88 commented
Oh, right.

I suppose someone could change the macuahuitl to accept teeth in general, which would be more convenient than shark teeth only.

2017-04-06 22:50 UTC, jakmak commented
Thing is they were originally chidren of shards but I changed it on kurfs request. I can change it back if you want

2017-04-06 23:05 UTC, Shadowmech88 commented
I don't mind one way or the other.

2017-04-06 23:08 UTC, Kurfursten commented
Tooth macuahuitls should be their own PR so I can finally make xenotooth weapons

2017-04-06 23:23 UTC, Riekland commented
My position remains that they shouldn't be put in until they stop looking like shit
what no _I'm_ not gonna sprite it what do you take me for a non piece of shit

2017-04-07 10:58 UTC, BlueNexus commented
Sprites are still terrible,, and worse than before.

2017-04-07 12:04 UTC, ultraplen commented
Why are the two tanks drawn in different perspectives ?

2017-04-07 13:38 UTC, Kurfursten commented on code/modules/fish/fish_tank.dm
> +	return 0
aaaaa

2017-04-07 13:39 UTC, Kurfursten commented
@ultraplen In the original version, the large tank is supposed to work as a wall and block everything even air

2017-04-07 13:44 UTC, ultraplen commented
Okay. If it no doesn't block air and presumably only has a larger volume, do we really need both aquariums? The larger one could be scrapped, since it has the worst sprite.

2017-04-08 09:04 UTC, gbasood commented
You need to actually figure out git at some point dude
This is getting ridiculous

2017-04-08 18:09 UTC, jakmak6 commented
sood i remade it because the old PR was before https://github.com/vgstation-coders/vgstation13/pull/14380

2017-04-09 01:29 UTC, gbasood commented
okay but account # 6 tho

2017-04-10 21:50 UTC, Riekland commented
Okay so doing some looking back for other autism I found this comment by our lord and savior
https://github.com/vgstation-coders/vgstation13/issues/7946#issuecomment-177064712
I think that the two fishtank groups while not perfect are at least better than the ones in this PR
ps @Zth-- where's the fish tanks you promised HUH

2017-04-16 14:41 UTC, yclatious commented
Never ever

2017-04-26 03:34 UTC, FalseIncarnate commented
Hey there, I'm the guy who coded the fishtanks on Paradise initially, cool to see someone porting it elsewhere. If you wouldn't mind dropping a link back to the original PR somewhere in your description, I'd really appreciate that so that the coders and spriters who contributed to them can get their fair credit.

As Kuru stated, the large tanks are called "Wall Aquariums" because they take up the same space as a wall, and (at least for us) block atmos like a wall. They also have a higher volume both in terms of water and fish capacity, as well as a bit more health than the smaller aquarium. The perspective difference was mostly an issue of available space and trying to avoid any weird gaps if you use them as part of a wall, though I admit it definitely is a bit jarring in comparison to the (much better) perspective of the smaller tank.

Shark teeth were children of glass shards so that you could load them into pneumatic cannons for shrapnel cannons or leave them on the ground to shred the feet of the shoeless crew, though that was also mostly laziness on my part. Changing that is honestly fine (I might backport that change to be frank).

I would make sure you grab the most recent changes to fishtanks, as I cleaned up the code and made some tweaks to fish breeding. Not absolutely necessary, but if you plan to keep up with our fish, you'll find it easier to do if you have that stuff already when more is added.

2017-05-19 06:28 UTC, Intigracy commented
conflicts

2017-05-22 21:19 UTC, Skullyton commented
fix it!

2017-05-22 21:37 UTC, gbasood commented
ftfy

2017-05-22 21:46 UTC, ghost requested changes
partial pathing needs changing

2017-05-22 21:46 UTC, Skullyton commented on code/modules/fish/fish_items.dm
> +	suicide_act(mob/user)			//"A tiny net is a death sentence: it's a net and it's tiny!" https://www.youtube.com/watch?v=FCI9Y4VGCVw
partial pathing is a no-no

2017-05-22 21:46 UTC, Skullyton commented on code/modules/fish/fish_items.dm
> +	suicide_act(mob/user)
partial pathing!

2017-05-22 21:46 UTC, Skullyton commented on code/modules/fish/fish_items.dm
> +	New()
Partial pathing

2017-05-22 21:46 UTC, Skullyton commented on code/modules/fish/fish_items.dm
> +	New()
yet more partial pathing

2017-06-12 02:25 UTC, closed without merging

2017-06-12 02:30 UTC, Shadowmech88 commented
Was this ready to go aside from conflicts and partial pathing?

2017-06-12 02:33 UTC, Intigracy commented
Seems like it