Construction Permits 2.0
d3athrow/vgstation13 pull request #14571
Opened 2017-04-06 16:29 UTC by jakmak6

remake of https://github.com/vgstation-coders/vgstation13/pull/14011

What this change does is it adds in new mini blueprints called construction permits. What these are are basically MOMMI prints accessible to all engineers/atmostechs/autists in the engi vend. They can create new rooms for use of APC's and air alarms and rename those rooms but CANNOT rename roundstart rooms (so engineers cant go around and rename every hallway to benis). 

These DO NOT count towards the antag steal blueprints objective. This would make it easier and encourage autism forts because previously you either had to be a MOMMI or steal the CE blueprints (or worse be the CE).

2017-04-06 17:14 UTC, Commandersand commented
Assistants should have access to them tbh
Maybe HoP can pass some out?

2017-04-06 17:32 UTC, ComicIronic commented
>Assistants should have access to them tbh

Give a mouse a cookie and he'll ask for some milk.
What reason would an assistant have to have access to these which isn't a reason for that assistant to join the engineering department?

2017-04-06 17:40 UTC, ComicIronic submitted a review, later dismissed
Needs some changes.

2017-04-06 17:40 UTC, ComicIronic commented on code/game/objects/items/constructionpermits.dm
> +/obj/item/blueprints/construction_permit/attack_self
Fun fact about the terribly ambiguous syntax for DM: what you've done is create a type called `/obj/item/blueprints/construction_permit/attack_self` and overriden its `interact()` method to do nothing. Any reason you (presumably) tried to override attack_self from blueprints? Should monkeys be able to use it for good reason?

2017-04-06 17:40 UTC, ComicIronic commented on code/game/objects/items/constructionpermits.dm
> +	if ((usr.restrained() || usr.stat || usr.get_active_hand() != src))
This should be done by `..()`. It's an error in the `Topic` for blueprints that
```
if(..())
    return
```
isn't
```
if(..())
    return 1
```
You should fix that instead.

2017-04-06 17:40 UTC, ComicIronic commented on code/game/objects/items/constructionpermits.dm
> +	usr << browse(text, "window=blueprints")
Change the name of the window.

2017-04-06 17:48 UTC, PJB3005 commented
@ComicIronic he copy pasted the entire file from MoMMI prints and renamed things.

2017-04-06 17:58 UTC, ComicIronic commented
😭 🔫  brb

2017-04-06 18:03 UTC, jakmak6 commented
im not even going to deny that is exactly what i did. Still it does function as intedned

2017-04-06 21:13 UTC, DamianX commented
browser datum instead of browse() when

2017-04-07 17:52 UTC, SarahJohnson489 commented
Comic, it's because people get assblasted as fuck if you just take eng to fuck off and fort. That said, all but the most autistic people will refuse an assistant that asks for a set or care if they yoink some to autism. Much like how people already use the foyer engivend for a set of gloves with no problem. It's not problem at all for the people who are building forts to toggle the idscan wire either if this goes in.

2017-04-07 18:28 UTC, PJB3005 commented on code/game/objects/items/constructionpermits.dm
> +	if ((usr.restrained() || usr.stat || usr.get_active_hand() != src))
Or just remove this entirely because the master blueprint type probably already does it.

2017-04-07 18:30 UTC, PJB3005 requested changes

2017-04-07 18:30 UTC, PJB3005 commented on code/game/objects/items/constructionpermits.dm
> +/obj/item/blueprints/construction_permit/interact()
They're PERMITs, not blueprints. Why are you calling them blueprints?

2017-04-07 18:30 UTC, PJB3005 commented on code/game/objects/items/constructionpermits.dm
> +	usr << browse(text, "window=blueprints")
Make it use browser datums instead.

2017-05-19 06:40 UTC, Intigracy commented
Confirm you tested this and I'll merge it.

2017-05-23 00:59 UTC, Skullyton commented on code/game/objects/items/constructionpermits.dm
> +<p>According the permit, you are now in <b>outer space</b>, Beware the space carp.</p>
According TO the permit surely?

2017-05-23 01:00 UTC, Skullyton commented on code/game/objects/items/constructionpermits.dm
> +<p>According the permit, you are now in <b>\"[A.name]\"</b>.</p>
Same as above

2017-05-23 01:05 UTC, Exxion commented on code/game/objects/items/constructionpermits.dm
> +<p>According the permit, you are now in <b>outer space</b>, Beware the space carp.</p>
Also comma splice

2017-06-11 18:20 UTC, SonixApache commented
@jakmak3 @jakmak6 work on this faggot

2017-06-12 02:24 UTC, closed without merging

2017-06-12 02:32 UTC, jakmak3 commented
rip

2017-06-12 13:43 UTC, SonixApache commented
you can just open it yourself if you work on it again can't you

2017-06-12 13:52 UTC, Intigracy commented
If not, he can just say something and I'll reopen it

2017-06-12 13:54 UTC, SonixApache commented
ye