Increase time a facehugger spends idle after trying to make friends with your face and failing to do so
d3athrow/vgstation13 pull request #14602
Opened 2017-04-08 14:41 UTC by gbasood

#14598 made me look over the facehugger code again and I realized something
1.5 seconds between pounces from the same facehugger? That's REALLY DUMB
Let's change that.
🆑 
 - tweak: Increase time a facehugger spends idle after trying to make friends with your face and failing to do so (changed from 1.5 to 5 seconds of idle time)

2017-04-08 14:42 UTC, PJB3005 approved these changes

2017-04-08 15:01 UTC, Blithering commented
I thought they usually kill themselves in the attempt?

2017-04-08 15:04 UTC, gbasood commented
75% of the time.

2017-04-09 13:37 UTC, ComicIronic requested changes
Define it.

2017-04-09 13:37 UTC, ComicIronic commented on code/modules/mob/living/carbon/alien/special/facehugger.dm
> +				GoIdle(50)
Make it a define.

2017-04-09 13:53 UTC, PJB3005 commented on code/modules/mob/living/carbon/alien/special/facehugger.dm
> +				GoIdle(50)
comic'd

2017-04-10 00:01 UTC, ComicIronic approved these changes

2017-04-10 00:01 UTC, merged