Rebalances black and green core reactions
d3athrow/vgstation13 pull request #14649
Opened 2017-04-13 04:47 UTC by Commandersand

well the green slime core had a bunch of medicine you could get if you had access to a chem dispenser which is required to do those reaction? Seemed kinda useless so i removed the medicine reactions from green and put DD, rezadone, and peridoxin to the black core
Black cores now give 5u nanobots instead of 1u combat or 1u medical
i'll probably add some unique xenobio items to the green core later like a slime heart that needs to be coded and sprited and slime tiles
I'll probably include that in another PR that adds reactions to pyrite and sepia as well as excluding xenos from gold cores but right now i want to see what people think about this
"when you code it" they said
:cl: 
 * rscadd: black cores now give peridoxin, rezadone, and regular nanobots
 * rscdel: green cores no longer give medicine, instead gives a raincoat

2017-04-13 04:54 UTC, Commandersand commented
pls no bully

2017-04-13 04:58 UTC, carshalash commented
What did he mean by this.

2017-04-13 05:07 UTC, Commandersand commented
Oh yeah, both cores still give their slime toxins with plasma

2017-04-13 18:30 UTC, Yelier commented
Why exclude xenos from the gold core?

2017-04-13 18:40 UTC, Commandersand commented
Oh shit I forgot to mention, when I exclude xenos from Golden cores I'm gonna a put a xeno egg reaction for dark purple cores so you can raise xenos in the max containment pens

2017-04-13 18:40 UTC, Commandersand commented
Fuck

2017-04-13 18:44 UTC, Commandersand commented
Right now dark purples are only used for more plasma in case there are no miners and you somehow run out, even then you can get one mutation from purple and be completely fine with plasma since it's like 10 sheets? Might be 5

2017-04-13 18:45 UTC, Probe1 commented
.. okay why a raincoat?  That isn't right.  It shouts "I'm a placeholder".

2017-04-13 18:54 UTC, Commandersand commented
@Probe1 monster musume memes, the raincoat will stay but I think I'll get a special sprite for it

2017-04-13 22:06 UTC, ComicIronic commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/slimecasp/on_reaction(var/datum/reagents/holder)
Is this meant to be `slimerezadone`?

2017-04-13 22:36 UTC, ComicIronic commented
What's the value of the reference?

2017-04-13 23:04 UTC, SonixApache commented
slime tiles sound interesting

2017-04-14 03:09 UTC, Commandersand commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/slimecasp/on_reaction(var/datum/reagents/holder)
I'm honestly not sure, first time CODING instead of deleting a few lines

2017-04-14 03:11 UTC, Commandersand commented
Well I guess the coat can give some resistance to extinguishers so that it's not just cosmetic? It IS a raincoat after all

2017-04-14 03:21 UTC, Commandersand commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/slimecasp/on_reaction(var/datum/reagents/holder)
Oh fuck nevermind i see it, will fix when can

2017-04-14 03:51 UTC, Commandersand commented
oh no! i messed up my local branch

2017-04-14 04:16 UTC, Commandersand commented
alright so that should have fixed the rezadone line that wasn't actually copy pasted from the orange reaction

2017-04-14 08:16 UTC, Commandersand commented
i got a not shit slime tile sprite 
![image](https://cloud.githubusercontent.com/assets/22992659/25037746/7731ee58-20c0-11e7-9559-e916c4170b97.png)
what it'll do is slow down anyone but slime people and will come from green cores at 5 tiles each reaction
just need to CODE IT which won't be too much time

2017-04-15 01:42 UTC, Commandersand commented
and i managed to fuck my local branch again

2017-04-15 02:11 UTC, Commandersand commented
i manged to unfuck my local branch again

2017-04-16 06:15 UTC, Commandersand commented
tiles soon(within the next hour)

2017-04-16 06:36 UTC, Commandersand commented
DONE
now to the slime heart and coat

2017-04-16 06:39 UTC, Commandersand commented
oh yeah they delete when broken, slime completely loses it's form if you blow it up

2017-04-16 06:41 UTC, Commandersand commented
broken as in from bombs, you can crowbar them up and shit

2017-04-16 06:46 UTC, Commandersand commented
thanks shadowmech

2017-04-16 10:18 UTC, N3X15 commented
You do realize you can edit posts, right?

2017-04-16 11:26 UTC, PJB3005 commented
2 tiles per core seems a bit low, make it like 4 or 6.

2017-04-16 14:23 UTC, Commandersand commented
Yeah I know I can edit posts, I made it low because the slow is really strong but alright fam

2017-04-18 06:52 UTC, Commandersand commented
slime hearts will heal 3 toxins each second when held by a slime person and deals 5 toxins if you're not. It's 5/sec because why the hell would you be holding it?
you get one from injecting green cores with blood, this item is mostly for accidentally spraying yourself

2017-04-18 14:01 UTC, SonixApache commented
It's a hand-held object and not an organ?

2017-04-18 14:47 UTC, Commandersand commented
Yeah, it might be used as an organ when it's time to balance slime people into a round start race ;-)

2017-04-18 16:04 UTC, PJB3005 requested changes

2017-04-18 16:04 UTC, PJB3005 commented on code/game/objects/items/slime_heart.dm
> +	name = "Slime Heart"
Remove capitalization here, if it's capitalized BYOND treats it as a proper noun.

2017-04-18 16:04 UTC, PJB3005 commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	name = "Tile of slime"
Remove capitalization.

2017-04-18 16:04 UTC, PJB3005 commented on code/game/objects/items/slime_heart.dm
> +			spawn(1 SECONDS)
Process gets called every 2 seconds so this shouldn't be needed.

2017-04-18 16:04 UTC, PJB3005 commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	force = 1.0
Remove `.0` here.

2017-04-18 17:07 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
> +			spawn(1 SECONDS)
Which line exactly?

2017-04-18 17:07 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
> +	name = "Slime Heart"
Th-thanks byond

2017-04-18 17:09 UTC, PJB3005 commented on code/game/objects/items/slime_heart.dm
> +			spawn(1 SECONDS)
Just the entire `cd` stuff.

2017-04-19 05:22 UTC, Commandersand commented
oh yeah and removed the .0
i guess you wanted me to remove the cd stuff because you thought it's not working how i wanted it to or something since we spoke a bit on discord? It works as intended, ticks every second

2017-04-19 05:48 UTC, Exxion commented on code/game/objects/items/slime_heart.dm
> +	name = "slime Heart"
See now this just looks weird

2017-04-19 06:01 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
> +	name = "slime Heart"
fuck i forgot a letter

2017-04-19 06:04 UTC, Commandersand commented
anything else?
probably gonna start that raincoat tomorrow
i'll slap it in with the winter coats so that it's not just a meme cosmetic

2017-04-20 00:43 UTC, Commandersand commented
oh shit is adding a slimecoat this easy? i hope not

2017-04-20 01:09 UTC, Commandersand commented
(lol

2017-04-20 04:26 UTC, Commandersand commented
one more thing

2017-04-20 04:38 UTC, Commandersand commented
noice

2017-04-20 05:00 UTC, Commandersand commented
that SHOULD be it

2017-04-21 03:27 UTC, Commandersand commented
hmm i think I will add the broken galoshes while I wait

2017-04-23 13:45 UTC, PJB3005 requested changes

2017-04-23 13:45 UTC, PJB3005 commented on code/game/objects/items/slime_heart.dm
>  /obj/item/slime_heart/process()
Change this to `OnMobLife(var/mob)` and remove the `New` code

2017-04-23 13:45 UTC, PJB3005 commented on code/game/objects/items/slime_heart.dm
> +/obj/item/slime_heart/New()
You're not removing the object from `processing_objects`.

2017-04-23 15:01 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
>  /obj/item/slime_heart/process()
dang c*ders

2017-04-23 15:04 UTC, Commandersand commented
wait what

2017-04-23 15:05 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
>  /obj/item/slime_heart/process()
wait isn't that the old core?

2017-04-23 15:10 UTC, Commandersand commented on code/game/objects/items/slime_heart.dm
>  /obj/item/slime_heart/process()
oh nvm

2017-04-23 16:24 UTC, PJB3005 approved these changes

2017-04-23 16:24 UTC, merged