can now receive the odd root plant from digging grass
d3athrow/vgstation13 pull request #14640
Opened 2017-04-12 11:21 UTC by Skullyton

Didn't add garlic as that's a serious balance risk. Instead, just potato, carrot, and beet

:cl:
* rscadd: Digging grass can yield the odd seed or root plant

2017-04-12 11:56 UTC, PJB3005 requested changes

2017-04-12 11:56 UTC, PJB3005 commented on code/game/turfs/simulated/floor.dm
> +				switch(rand(1,6))
So, just use a pick over a set of typepath?

2017-04-12 13:52 UTC, PJB3005 approved these changes

2017-04-12 16:39 UTC, FudgePucker commented
Speaking of roots. We should add onions. I know about 1000 different cultanary uses for onions, like two for beets.

2017-04-12 17:59 UTC, Skullyton commented
>onion rings
>quiche
>french onion soup

yes

2017-04-12 20:03 UTC, Kurfursten commented
We already have quiche but it's made with garlic

2017-04-14 08:28 UTC, SonixApache commented
just like in my farming simulators

2017-04-15 00:38 UTC, merged