Adds in an option for admins to save logs to disk
d3athrow/vgstation13 pull request #14664
Opened 2017-04-15 08:40 UTC by BobdaBiscuit

Adds in an alert box to .getruntimelog, .getserverlog, Show Server Log and Show Server Attack Log. You can choose to open the file in notepad (as in current behaviour) or save it to disk.

Thought behind this is us on linux can't use the current verb and multiple admins on windows are reporting the current verb does't work either on occasionas and it's 99% gonna be byond shitting the bed with notepad. If this pr still doesn't work we can most likely lynch pomf or something.

2017-04-15 19:53 UTC, clusterfack commented
Wow talk about flubbed

2017-04-16 02:47 UTC, BobdaBiscuit commented
pls no bully

2017-04-16 14:06 UTC, PJB3005 approved these changes

2017-04-18 01:16 UTC, ComicIronic requested changes
DO THAT

2017-04-18 01:16 UTC, ComicIronic commented on code/modules/admin/verbs/getlogs.dm
> +	var/method = alert("What method do you wish to get the logs?",,"Save to file","Open in notepad")
Replace all this copypaste with a PROC

2017-04-18 06:04 UTC, BobdaBiscuit commented
No doubt I did something terribly wrong, it just werks(tm).

2017-04-23 13:45 UTC, merged