Adds Ancient Spellbook and New Spell, "Poly" Morph (Work in Progress)
d3athrow/vgstation13 pull request #14678
Opened 2017-04-17 18:09 UTC by Arthurdentist

Throwing this up now mostly for ideas to take this concept further. Its still a complete hack job that needs a lot of work.
## Ancient Spellbook
This PR adds a new single use spellbook to the game, the 'ancient spellbook'. It contains a random spell that can't be acquired under other normal circumstances.  So far the only possible spells are 'Disintegrate' and a new Spell, "Poly"Morph. 

To get the ancient spellbook you have to choose the spellbook bundle, and even then it isn't guaranteed you will get it. I intend to add at least one more unique spell to the spellbook; but I need to work on that. 

## "Poly"morph
This is a ranged spell that the wizard casts on a single target. The target is turned into a parrot for a short duration of time rendering them (mostly) harmless. Whilst they are a parrot they cannot be killed, so this spell isn't a way to get cheap and easy kills. Its effectively an alternative to the statue spell. 

It can remove an annoying person for a short amount of time but unlike the statue spell it can be cast at range. You can't use it to easily kill someone however, which you can do with the statue spell. The cooldown is pretty long and I don't *think* it is that powerful as a spell, but I am certainly up for tweaking it to make it properly balanced. 

I need to consider a better method of making an 'invincible' parrot. The method I am using currently is not at all pretty and I am sure there is a better way of doing it. 

## Things to do

- [ ] Code a third spell for the ancient spellbook
- [ ] Figure out a better way of making invincible parrots
- [ ] Currently when a person stops being a parrot, a random headset is dropped beneath their feet because new parrots spawn with a random headset. This ought to be fixed as well.
- [ ] Unique graphics for the ancient spellbook
- [ ] Balance the shit out of everything
- [ ] Fix any other dumb mistakes I have made

## Video
I'll make a video of the spell / book in action later today so you can see precisely how it all works. Just want to put this up first.

2017-04-17 18:10 UTC, Arthurdentist commented
Already conflicted and im not sure why. Wew

2017-04-17 18:13 UTC, unid15 commented on code/modules/spells/targeted/parrotmorph.dm
> +		M.transmogrify()
Indentation after spawn()

2017-04-17 18:19 UTC, clusterfack commented
I was right, we really are becoming runescape

2017-04-17 18:20 UTC, Arthurdentist commented
Ice Barrage soon

but actually I couldn't think of a better name for it. If you got one im all ears.

2017-04-17 18:24 UTC, Skullyton commented on code/modules/spells/targeted/parrotmorph.dm
> +	maxHealth = 99999999999
Would probably be better to give em status_flag = CANSTUN|CANKNOCKDOWN|CANPARALYSE|CANPUSH|GODMODE

2017-04-17 19:17 UTC, PJB3005 commented
I've already had EI NATH of this PR.

2017-04-17 19:19 UTC, PJB3005 requested changes

2017-04-17 19:19 UTC, PJB3005 commented on code/game/gamemodes/wizard/spellbook.dm
> +/obj/item/weapon/spellbook/oneuse/ancient/recoil(mob/living/carbon/user as mob)
Remove `as mob`

2017-04-18 01:54 UTC, ComicIronic commented on code/modules/spells/targeted/parrotmorph.dm
> +	health = 99999999999 //got to be better ways of doing this but I haven't figured it out yet
use `INFINITY`.

2017-04-18 12:47 UTC, Diavill commented
Summon swords when

2017-04-18 23:07 UTC, Shadowmech88 commented on code/modules/spells/targeted/parrotmorph.dm
> +	maxHealth = 99999999999
Could also just override the procs for the parrot taking damage and/or dying and make them do nothing.

2017-04-19 04:07 UTC, Durgen commented
How about a spell that would increase a target's susceptibility to damage for a certain amount of time?
Maybe the spell that could halve their brute resistance, burn resistance, etc.

2017-04-19 14:59 UTC, icantthinkofanameritenow commented
I'd suggest one to turn someone into a frog, but the parrot thing kind of covers that already. 

Maybe a self-healing spell that acts like tricord and stops internal bleeding? I know there's no way in hell that it would be balanced as a stand-alone spell, but if it only appears in a rare spellbook which itself isn't guaranteed to contain that spell then it should be fine.

2017-04-19 16:43 UTC, Blithering commented
What happens when you revert while being carried?

2017-04-19 17:42 UTC, Shadowmech88 commented
Un-transmogrifying in general places your old body on the turf of your current body, then moves you to your old body and deletes your current body.

You'd probably be fine, but I'm not sure what would happen to the animal holder if the animal inside it gets deleted.

2017-04-19 18:43 UTC, Blithering commented
@Shadowmech88 That might be answered in https://github.com/vgstation-coders/vgstation13/issues/14689 my big worry was wizards using the spell to nullspace the crew one parrot at a time.

2017-04-20 17:41 UTC, Arthurdentist commented
I can't fix binary merge conflicts im not clever enough so lets take this from the top and pretend it never happened.

2017-04-20 17:41 UTC, closed without merging