Fix #14313
d3athrow/vgstation13 pull request #14697
Opened 2017-04-20 03:39 UTC by Lancemaker

Instances of Chair/couch and its variances are now layered (the variable is called Plane) properly. I added dir = 1 to the base object, so north will be the default chair direction.

2017-04-20 04:59 UTC, Commandersand commented
noice

2017-04-20 06:04 UTC, PJB3005 requested changes
1. You shouldn't change the default direction. South (2) is always default. 
2. This is a really bad way to fix this in general, consider doing the following in `New()`:

```dm
if (ticker) 
    initialize()
```

2017-04-20 06:25 UTC, SonixApache commented
add descriptive title, put [fixes x] in the description

2017-04-20 08:49 UTC, clusterfack commented
The problem is that the construction dir isn't being passed as an argument to new, and its not being sent. Or rather that the construction code itself needs to call update_dir() on everything that gets constructed, and that this should have an update_dir() proc that calls handle_layer() (or just rename handle_layer() to update_dir())

2017-04-20 13:00 UTC, Lancemaker commented
clusterfack
what i understood was that there is an execution order to change the plane variable(that will in the end determine if the object is layered above or below the player). when the object is created everything is pointing south, therefore the handle_layer() is useless to the created object independent to where the usr that created it is facing. There is another proc creating this object, and when it creates it changes its direction after the object is initialized. So my fix just changes the char dir to the usr dir and adds the proper order and puts the handle_layer to work. 

PJB3005,
>  You shouldn't change the default direction. South (2) is always default. 
i will do that. 
> This is a really bad way to fix this in general, consider doing the following in New():
`if (ticker) 
    initialize()`
so you want me to put my code inside initialize? or remove it completely ? because the code before initialize() is what is making handle_layer() work when the object is created using iron for exemple.

2017-04-20 13:25 UTC, SonixApache commented
no you fool, make the title descriptive, like "properly layers couches"
and in the description (the first post) put "fixes x"
both without quotation marks

2017-04-20 14:37 UTC, Lancemaker commented
SonixApache,
Sorry bro, im new to this, if you can point me to the formatting guidelines i will appreciate it.

2017-04-20 14:40 UTC, SonixApache commented
This is good. don't think there's formatting guidelines defined anywhere, this is just more readable.
I'm not sure if 'fixes X' is required to be in the OP to autoclose the issue if it's already in the commit messages, but you might as well throw it in there for good measure.

2017-04-21 11:01 UTC, DamianX commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/obj/structure/bed/chair
what's with all the extra spaces here and and there?

2017-04-21 11:01 UTC, DamianX commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/obj/structure/bed/chair/MouseDrop_T(mob/M as mob, mob/user as mob)//to bucle : if Mob has no butt, return.
buckle

2017-06-11 18:20 UTC, SonixApache commented
Ded?

2017-06-11 19:11 UTC, closed without merging