Robotics console hacking
d3athrow/vgstation13 pull request #14716
Opened 2017-04-22 16:00 UTC by oldcroc

The robotics control console can be hacked in a way similar to how the cargo console is hacked. If you solder the robotics console board, build the console, and multitool the console it removes access on the robotics console. This can be undone by dismantling and soldering the robotics console board again.

2017-04-22 16:41 UTC, PJB3005 requested changes

2017-04-22 16:41 UTC, PJB3005 commented on code/game/machinery/computer/robot.dm
> +	name = "Robotics Control"
Don't do this. It shouldn't be capitalized.

2017-04-22 16:41 UTC, PJB3005 commented on code/game/machinery/computer/robot.dm
> +	var/access_removed = 0
No. Change `access_req` and such.

2017-04-22 16:41 UTC, PJB3005 commented on code/game/machinery/computer/robot.dm
> +/obj/machinery/computer/robotics/attackby(I as obj, user as mob)
No. No copy pasting.

2017-04-22 16:41 UTC, PJB3005 commented on code/game/machinery/computer/buildandrepair.dm
> +	return
Trailing return.

2017-04-22 16:41 UTC, PJB3005 commented on code/game/machinery/computer/buildandrepair.dm
> +	to_chat(user, "<span class='notice'>You [access_hacked ? "" : "un"]connect the security fuse.</span>")
It's DISconnect.

2017-04-22 22:08 UTC, Commandersand commented
Nice

2017-04-23 20:58 UTC, Intigracy commented on code/game/machinery/computer/robot.dm
> +			to_chat(user, "You overide the consoles access restrictions")
's

2017-04-23 20:59 UTC, Intigracy commented on code/game/machinery/computer/robot.dm
> +			to_chat(user, "The consoles firewall stops you from changing its settings")
console's, add period to the end

2017-04-24 13:26 UTC, SonixApache commented
adios malf, we hardly knew ye

2017-04-24 17:18 UTC, Allspice commented
PRs "hacking comms console and ID console circuits" coming up next.

2017-04-27 20:46 UTC, ComicIronic commented on code/game/machinery/computer/robot.dm
> +	name = "robotics Control"
Why would you change this?

2017-05-31 05:16 UTC, SonixApache commented
is this ded

2017-05-31 18:25 UTC, closed without merging

2017-05-31 21:38 UTC, SonixApache commented
this is ded