Makes hyperzine poisonous for diona.
d3athrow/vgstation13 pull request #14721
Opened 2017-04-23 06:41 UTC by IsdatAfamas

Tired of green fuckers running to your chem station every round begging for their pills to make them even more OP? Worry no longer.

# Changelog
:cl:
* tweak: Diona are now allergic to hyperzine!
/:cl:

2017-04-23 07:54 UTC, ultraplen commented
A fair nerf. Possibly a bit harsh.

2017-04-23 08:09 UTC, BobdaBiscuit commented
If only you knew what kind of hell you are inviting in by doing this.

2017-04-23 08:29 UTC, AutismSpider commented
Better ways to do this to bad no one gives a fuck.

2017-04-23 09:17 UTC, Kurfursten commented
With the current numbers, this will crit a Diona in 13 seconds, consuming 0.39u Hyperzine

The low lethal dosage should be taken into account when considering splash/smoke mechanics

2017-04-23 09:31 UTC, PJB3005 commented
Yeah the damage is WAY over the top.

Make it more manageable but still not something you want to consistently use.

2017-04-23 09:32 UTC, PJB3005 submitted a review, later dismissed

2017-04-23 09:32 UTC, PJB3005 commented on code/modules/reagents/Chemistry-Reagents.dm
> +		if(H.species.name == "Diona")
Use `isdiona(H)`

2017-04-23 14:27 UTC, Fruktlimpa commented
Dionae is a pretty shit race lets not lie. The massive slowdown would make them extremely annoying to play which is why everyone chugs hyperzine in the first place.
Instead of making hyperzine a death sentence or forcing them to chug other pills at the same rate. Isn't it possible to make them slightly slower than a human by consuming hyperzine?
I realize it isn't ideal because it would still force them to chug hyperzine but at least then they wouldn't be speedy trees of no brute damage.

2017-04-23 15:05 UTC, IsdatAfamas commented
Im going to make the damage dealt a lot more reasonable (and potentially counteracted with chems) and also make the speed up to not be as great as it is for other species.

2017-04-23 15:08 UTC, IsdatAfamas commented
Will also try to make regeneration not work for diona while on hyperzine in which case Ill probably reduce damage dealt even more so

2017-04-23 15:21 UTC, BobdaBiscuit commented
IMO, if you make hyperzine not make dionas sanic, and then disable their regen while under it's effects the damage is unneeded.

2017-04-23 15:50 UTC, Ephx1 commented
_It begins!_

2017-04-23 16:59 UTC, Blithering commented
Disabling the regen when hyperzine is present as @BobdaBiscuit suggested seems like a fair tradeoff to me, not sure how feasible that is code wise though

2017-04-23 17:00 UTC, BobdaBiscuit commented
It's perfectly possible, I had a look through the code for em and it's just a isdiona() + has hyperzine test and we're gucci

2017-04-23 17:47 UTC, Kurfursten commented
I think disabling the regeneration is an interesting idea, because combat is when you would most want regeneration AND movement speed, and it's not trivial for most jobs to remove the hyperzine when combat is over unless you're carrying a pAI to smoke it out.

Overall, I appreciate its simplicity and balance as an idea.

2017-04-23 17:54 UTC, IsdatAfamas commented
Alright, so no damage dealt to diona, but no regen, and speed buff is nerfed.

2017-04-23 18:28 UTC, Exxion commented
If it's less effective AND prevents regeneration, is the damage really necessary?

2017-04-23 18:35 UTC, IsdatAfamas commented
@PJB3005 Let me know if there are any other issues.

2017-04-23 18:35 UTC, IsdatAfamas commented
@Exxion It isn't. I forgot to remove it in last commit.

2017-04-24 00:30 UTC, gbasood commented
>Dionae is a pretty shit race lets not lie. 

Yeah man regenerating through anything but burn damage
So shit

2017-04-24 01:34 UTC, Exxion commented
And taking enough burn damage to be critted in two (2) standard laser shots

2017-04-24 01:43 UTC, aceedex commented
maybe speed up diona a bit in exchange then, because I feel its unplayable without hyperzine

2017-04-24 01:55 UTC, Exxion commented
Consider these options:
* Git Gud

2017-04-24 02:08 UTC, gbasood commented
I'd rather make a balance change that's overkill and then find a halfway point afterwards then fiddle around with multiple PRs that are "too harsh man" according to a small subset of players

2017-04-24 05:05 UTC, Commandersand commented
just make hyperzine heat up bodies enough to deal burn if you overdose

2017-04-24 07:07 UTC, Fruktlimpa commented
@gbasood 
>Yeah man regenerating through anything but burn damage
So shit

I meant more in a sense that they are a stupid meme race that literally cannot function without hyperzine. Anyone who would willingly play Dionae without so much as a drop of hyperzine is insane.

2017-04-24 08:58 UTC, SolariousGabriella commented
I think this PR is bad because it changes the two main diona things, which is being slow and having high regen. Diona already suck, even with non nerfed hyperzine. Here is my ideas to fix diona, and make them more like tree people they should be.
>slightly faster base movement speed (still slower than human)
>unaffected by zas
>chemicals don't work on them

No zas, can't be chloral or sleepypen meme'd but they're stuck being sorta slow forever because they can't eat hyperzine.

2017-04-24 09:03 UTC, Shadowmech88 commented
I keep seeing people claim that dionae are OP.

Now, I haven't played in a while, so I'm honestly asking: are there a significant number of players rolling dionae? Something like 30%-40% at least?
Because that's what I would expect to happen if we had a race that was truly overpowered, that a significant number of people would be playing it for the advantage it offered.

2017-04-24 11:00 UTC, BobdaBiscuit commented
Actually we had a week were the majority of sec teams were all diona, is was a pretty funny meme.

2017-04-24 13:23 UTC, SonixApache commented
if you're going to take away their regen you might as well make them as fast as humans
level the playing field

2017-04-24 13:34 UTC, IsdatAfamas commented
Regen is still there but only when they have no hyperzine in system

2017-04-24 13:37 UTC, SonixApache commented
Yes, that's the point. If they don't have their bullshit regeneration anymore, why make them slower still than humans on drugs?

2017-04-24 21:51 UTC, FudgePucker commented
Number one murder bone weapon is egun.
Zap and laser to death.
Number one lethal option security has is egun.
Zap and laser to death.
Everybody has a toolbelt with a welder.
Stuns are king burn damage is second.

Hell they can't survive polyacid smoke grenades. How are they super OP again?

I like Solarious' idea. They are so slow it takes half a round to cross the station, you take hyperzine or roleplay a tree. A minor speed nerf instead of a super major "oh god how can it be possible to move this slow" one. Nerf regen so you can kill one in full light with a esword and then we have balance.

2017-04-24 23:26 UTC, Blithering commented
Combat isn't the only factor when considering a race's strengths. Remember they don't need to breathe or eat, are unaffected by pressure, heal from radiation, can shrug off ZAS and ignore overdose limits on meds. Surviving as a diona is a lot simpler because you can pretty much ignore everything that isn't fire.

2017-04-24 23:33 UTC, Exxion commented
At the cost of walking at roughly the same speed as a slime mold.
Which is why hyperzine is too good for them, which is why this PR exists

Also, all of you fucks saying that dionae are unplayably slow need to either get more patient or stop playing dionae

2017-04-25 01:46 UTC, Intigracy commented
Clearly we should just make dionae unable to move.

2017-04-25 01:48 UTC, Shadowmech88 commented
They are trees, after all. Trees don't move.

2017-04-25 01:49 UTC, Intigracy commented
wait sorry wrong meme

the obvious solution is to remove skeletons

2017-04-25 17:10 UTC, DamianX commented
Fix the changelog already

2017-04-26 21:51 UTC, PJB3005 approved these changes

2017-04-27 00:22 UTC, ComicIronic requested changes
Needs fixing.

2017-04-27 00:22 UTC, ComicIronic commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		if(isdiona(src))
Use `else if`.

2017-04-27 00:22 UTC, ComicIronic commented on code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
> +			if(light_amount >= 3 & !reagents.has_reagent(HYPERZINE)) //If there's enough light, and you do not have hyperzine in body, heal
Use `&&`, `&` is a bitwise operation.

2017-04-27 17:17 UTC, IsdatAfamas commented
@ComicIronic done

2017-04-27 17:25 UTC, BobdaBiscuit commented
How fast is it ingame compared to the human base speed? Cause the tally boost seems hella lower.

2017-04-27 17:32 UTC, IsdatAfamas commented
@BobdaBiscuit Human slowdown by default is 0. Diona is 7 without hyperzine, and 3 with, so somewhat slower then humans still.

2017-04-27 17:35 UTC, BobdaBiscuit commented
Eh if it's still too slow I suppose another pr can be made to tweak it.

2017-04-27 20:20 UTC, ComicIronic approved these changes

2017-05-14 21:55 UTC, IsdatAfamas commented
MERGE WHEN

2017-05-14 22:03 UTC, BobdaBiscuit commented
/>fair diona nerf that most people agree with
/>still not merged nearly a month later

REALLY MAKES YOU THINK

2017-05-14 22:26 UTC, Intigracy commented
If this needs adjusting we can do so.

2017-05-14 22:26 UTC, merged