adds power creep
d3athrow/vgstation13 pull request #14760
Opened 2017-04-28 22:57 UTC by Skullyton

2017-04-28 23:03 UTC, ComicIronic submitted a review, later dismissed

2017-04-28 23:03 UTC, ComicIronic commented on code/game/objects/items/weapons/power_cells.dm
> +		use(power_to_use)
The sound effect and the rest of the code should be indented under an `if` for this - if the cell can't give you the power you want, this returns a 0.

2017-04-29 04:21 UTC, Kurfursten commented on code/modules/food/recipes_microwave.dm
> +	time = 300
since no other kitchen recipe uses this, it might confuse people

2017-04-29 10:19 UTC, Skullyton commented on code/modules/food/recipes_microwave.dm
> +	time = 300
It's for balancing

2017-04-29 17:51 UTC, FudgePucker commented
Good shit :ok_hand:

2017-04-29 18:45 UTC, PJB3005 requested changes

2017-04-29 18:45 UTC, PJB3005 commented on code/game/objects/items/weapons/power_cells.dm
> +	name = "power crepe"
crêpe

2017-04-29 18:45 UTC, PJB3005 commented on code/game/objects/items/weapons/power_cells.dm
> +	desc = "Warning: May contain dairy products, 12,000kw of searing death, gluten."
`kW`

2017-04-29 18:46 UTC, PJB3005 commented on code/game/objects/items/weapons/power_cells.dm
> +			user.set_light(2,2,"#ffff00")
Doesn't this fuck with things like getting set on fire?

2017-04-29 19:05 UTC, Skullyton commented on code/game/objects/items/weapons/power_cells.dm
> +	name = "power crepe"
Don't have atom on this computer, will have to wait till monday for accents

2017-04-29 19:05 UTC, Skullyton commented on code/game/objects/items/weapons/power_cells.dm
> +			user.set_light(2,2,"#ffff00")
If you're on fire, why are you eating something that deals burn damage?

2017-04-29 19:09 UTC, Shadowmech88 commented on code/game/objects/items/weapons/power_cells.dm
> +	name = "power crepe"
What if you add it via editing the file on Github?

2017-04-29 19:14 UTC, ComicIronic commented on code/game/objects/items/weapons/power_cells.dm
> +			user.set_light(2,2,"#ffff00")
Bzzt, wrong answer.

2017-04-29 19:29 UTC, Skullyton commented on code/game/objects/items/weapons/power_cells.dm
> +			user.set_light(2,2,"#ffff00")
Well, how would you recommend doing it?

Most things that update lighting update it every so few ticks (The light virus effect, radglow, and I would assume fire), but there's no real way to revert back to that with this.

Two ways I can think of doing it. Store the light settings in temporary variables to be restored after the cooldown, or check if the person is alight already and if so don't light them up.

2017-04-29 20:37 UTC, Sarcalogo commented
![deus ex human revolution prequel](https://cloud.githubusercontent.com/assets/15669103/25558700/058ab3a2-2cfa-11e7-9488-eea7ac4eaf17.png)
https://www.youtube.com/watch?v=lY5hDzWfnxw

2017-04-29 20:40 UTC, Skullyton commented
???

2017-04-29 20:47 UTC, Sarcalogo commented
*bing bing yahoo*

![image](https://cloud.githubusercontent.com/assets/15669103/25558760/5fb856bc-2cfb-11e7-8fa9-3166bd7dc51e.png)

2017-04-29 21:47 UTC, PJB3005 commented on code/game/objects/items/weapons/power_cells.dm
> +			user.set_light(2,2,"#ffff00")
To handle this properly you need wrappers, managers for lighting colors and whatever.

so... I'd just recommend it not doing anything if they're already lit. Not perfect but least effort.

What you'd need is a list of light effects on mobs, then produce a final color, range and power based on all of those.

2017-04-29 21:54 UTC, Exxion commented on code/game/objects/items/weapons/power_cells.dm
> +	desc = "Warning: May contain dairy products, 12,000kw of searing death, gluten."
That's still the wrong unit, so who cares

2017-04-29 22:12 UTC, PJB3005 commented on code/game/objects/items/weapons/power_cells.dm
> +	desc = "Warning: May contain dairy products, 12,000kw of searing death, gluten."
Oh yeah.

`kJ`

2017-04-30 00:10 UTC, Skullyton commented on code/game/objects/items/weapons/power_cells.dm
> +	desc = "Warning: May contain dairy products, 12,000kw of searing death, gluten."
wouldn't it be just (J) Joules in this case? or 12kJ ?

2017-04-30 00:49 UTC, PJB3005 approved these changes

2017-05-07 10:32 UTC, Megamaw commented
are we ready to approve because this is an amazing pr

2017-05-19 06:18 UTC, merged

2017-05-19 06:18 UTC, Intigracy commented
Make sure you update the wiki.