Changes Security Cyborgs Back to What They Once Were
d3athrow/vgstation13 pull request #14762
Opened 2017-04-29 01:56 UTC by Shadowmech88

Resurrection of #13873, which was still waiting on a server poll.
Slightly modified in that I tried my hand at a better spawn-text for security borgs.

:cl:
 * tweak: The peacekeeper module is once again called the security module.

2017-04-29 13:02 UTC, PJB3005 commented
Make it say that you don't give a flying fuck about your lawset.

2017-04-29 13:13 UTC, Shadowmech88 commented
I don't see how what I've currently written could possibly be misinterpreted.

2017-04-29 16:41 UTC, PJB3005 commented
It's not possible to misinterpret, but it doesn't mention ANYWHERE that you don't give a fuck about spacelaw.

2017-04-29 17:44 UTC, Shadowmech88 commented
I disagree with the notion that security borgs should have more restrictions placed on their behavior than the other modules.
The previous text was an effort to prevent naive players from thinking that Space Law could possibly supercede their silicon laws.
This text accomplishes that.

2017-04-29 18:47 UTC, FudgePucker commented
I mean they are no longer baby blue right? I don't see the reason why they should be called security.

You can arrest murder boners armed to the teeth covered in the blood of your victims, you can kill comfermed (by AI or fellow borg eye witnessing powers) changelings and vampires, but you shouldn't be able to arrest people for petty crimes and go "hurr dur standing orders for following space law :^)"

2017-04-29 18:52 UTC, FudgePucker commented
Also quick lawset question, people act like NT default is captain one human, but the captain can act outside of the interest of NT, does that mean you can treat the captain as an enemy of the corporation if he orders you to do something like murder everyone?

2017-04-29 19:00 UTC, Shadowmech88 commented
The only law above "Serve the crew with priority according to rank and role." is "Protect your assigned space station to the best of your ability." Nothing is mentioned about the "interest of NT."
If the captain is damaging the station itself the lawset allows you to stop him, but otherwise the captain controls the silicons and can do whatever he wants with them.

2017-04-29 19:16 UTC, ComicIronic requested changes
Not touching the politics aspect in this review.

2017-04-29 19:16 UTC, ComicIronic commented on code/modules/mob/living/silicon/robot/robot.dm
> +			to_chat(src, "<font size='15' color='red'>Regardless of your module, your wishes, or the needs of the beings around you, absolutely nothing takes higher priority than following your silicon lawset
1. You forgot to take off the ending `<span>`.
2. Use a span, not font.

2017-04-29 20:34 UTC, Sarcalogo commented
![check these dubs](https://cloud.githubusercontent.com/assets/15669103/25558679/744e4566-2cf9-11e7-8739-7f094e118a66.png)

https://www.youtube.com/watch?v=VXlZWSjqg2Y

2017-04-29 23:13 UTC, yclatious commented
>upvoting your own shitpost

Sarca, cmon lad

2017-04-29 23:31 UTC, ComicIronic approved these changes

2017-04-30 22:37 UTC, Sarcalogo commented
It's not a shitpost.

2017-04-30 22:51 UTC, Exxion commented
You can say that, but it doesn't change the facts

2017-05-03 00:52 UTC, Sarcalogo commented
Look at my pull request history and previous discussions before you claim that I'm not actually Sarcalogo.  I most definitely am.

2017-05-03 03:42 UTC, HarseTheef commented
Isn't this just us changing the name back and forth at this point without actually touching or doing anything?  Why does anyone even care if it has no affect on game-play whatsoever?

2017-05-03 06:25 UTC, Exxion commented
Alright yes you are
But why are you here?

2017-05-03 18:16 UTC, PJB3005 commented
@HarseTheef because they feel the PR was unjustly merged and they want revenge on the ivory tower coder metaclub.

2017-05-03 20:09 UTC, aceedex commented
I for one like the sound of security cyborg.

2017-05-03 20:10 UTC, Exxion commented
Secborg rolls off the tongue better than peaceborg or whatever the short name is, but beyond that I couldn't care less what they're called

2017-05-03 21:27 UTC, FudgePucker commented
I thought the short name was "arrest valid seeking sillycon shitbag"?

2017-05-19 06:49 UTC, Intigracy commented
Ask for Pomf's opinion.

2017-05-19 19:42 UTC, Shadowmech88 commented
@d3athrow 
What's your opinion?

2017-06-17 02:26 UTC, SonixApache commented
pomf doesn't want to talk, just make a server poll and be done with it

2017-07-02 17:24 UTC, SonixApache commented
@Shadowmech88 resolve conflicts, bug collabs for a server poll

2017-07-19 04:30 UTC, gbasood commented
http://ss13.moe/index.php/poll/120
Whoever makes polls with a title like is fucking dumb btw

2017-07-19 04:31 UTC, d3athrow commented
Lolwhat

2017-07-27 00:34 UTC, Shadowmech88 commented
Conflicts fixed.

2017-07-27 00:52 UTC, SonixApache commented
HIT IT

2017-07-27 03:47 UTC, d3athrow commented
ok

2017-07-27 03:47 UTC, merged