Changes the tool-belt examine text slightly
d3athrow/vgstation13 pull request #14771
Opened 2017-05-02 00:59 UTC by Emilc4h

Removes light replacers from the examine list, seeing as they apparently have a w_class too high to fit inside, but leaves them in the can_only_hold list because Kurfusten said so and I trust him more than myself.

Closes #14768

2017-05-02 02:41 UTC, Commandersand commented
just increase the total_max_w_class for the belt fam

2017-05-02 03:24 UTC, Emilc4h commented
I mean I _guess_ but like I said I'm just doing what Kurfusten said because he's cool.

I guess that wouldn't hurt.

2017-05-02 21:05 UTC, PJB3005 approved these changes

2017-05-02 21:15 UTC, Kurfursten commented
This change as it is now would allow normal toolbelts to hold foam extinguishers, plus enlarged tank welders. So it's a categorical buff.

2017-05-02 21:17 UTC, ComicIronic commented on code/game/objects/items/weapons/storage/belt.dm
> +	fits_max_w_class = 3
You should use w_class defines for this if you're going to make this kind of change.

2017-05-03 03:40 UTC, HarseTheef commented
I will reserve my support, because I would personally like to see said tool-belt buff.

2017-05-03 08:37 UTC, SonixApache commented
tg/baycode inventory sizes when

2017-05-03 12:38 UTC, ComicIronic commented
We need that bot on this repo.
```
W
Y
C
I
```

2017-05-03 17:03 UTC, JustSumBody commented
powercreep

2017-05-03 19:06 UTC, Emilc4h commented on code/game/objects/items/weapons/storage/belt.dm
> +	fits_max_w_class = 3
I would if I knew how to.
Unless you mean just changing the light replacer's w_class, except that doesn't seem like a good idea.

2017-05-03 19:47 UTC, ComicIronic commented on code/game/objects/items/weapons/storage/belt.dm
> +	fits_max_w_class = 3
There are defines for all the w_class values. You can see that the belt's w_class is `W_CLASS_LARGE`, for example. 3 is `W_CLASS_MEDIUM`, I believe.

2017-05-04 22:30 UTC, FudgePucker commented
@Kurfursten can't you just specify the pocket extinguishers instead of the parent extinguisher?

@JustSumBody "I have no real valid argument against this PR but still disagree with it." ITS THAT WORD, THAT MAGIC WORD

2017-05-04 22:49 UTC, Kurfursten commented
You could, but that's not what's being done here. By contrast there's no easy solution for the welder problem.

I think it's unfair to last out at SumBody like that, though: he's right. We've always had special rewards for using the CE belt, to encourage people to play that role and unite the engineering team. By making light replacers, foam extinguishers, and large-tank welders more widely available in toolbelts we are decreasing the substantialness of the reward for using the CE belt.

Since we have a Janibelt now specifically for holding stuff like the light replacer, it feels more than ever that engineers should leave lights to the janitor.

2017-05-04 23:25 UTC, FudgePucker commented
I guess it would be too much to change all instances of welders with a new welder copy to move away from having the stock welder being the parent?

That's a fair argument.
I just don't like the power creep argument.
I don't think a single PR will result in a downward spiral of other game breaking PRs using the first PR as an excuse.
Its the slippery slope argument, only worse.

2017-05-05 05:32 UTC, Exxion commented
Yeah I know powercreep is a buzzword
But this is like... the definition of powercreep

2017-05-05 05:35 UTC, Shadowmech88 commented
Isn't the light replacer pretty much just a janitor thing?
Janitors have janibelts now, which can already hold light replacers.

Why buff normal toolbelts as well?

2017-05-06 10:38 UTC, SarahJohnson489 commented
I'd love to free up more space in my toolbox so I can carry more minerals, boxes, wires and cells.

Nah, eng has to do it a lot too so I end up stealing it or making one once minerals drop.

2017-05-06 12:41 UTC, SonixApache commented
CE's belt still holds the RPD and RCD, unlike normal belts. That's reason enough to use it.

2017-05-19 06:22 UTC, Intigracy requested changes
If you want to add the light replacer, add just the light replacer.

2017-05-19 06:22 UTC, Intigracy commented on code/game/objects/items/weapons/storage/belt.dm
> +	fits_max_w_class = 3
```
fits_ignoring_w_class = list(
		"/obj/item/device/lightreplacer"
		)
```

remove the change you made

2017-06-08 04:16 UTC, Intigracy commented
Make the change if you want this merged

2017-06-14 19:01 UTC, SonixApache commented
@Emilc4h status?

2017-06-17 20:27 UTC, Shadowmech88 commented
Couldn't a collab just make the necessary change to the existing PR using the web interface and then merge it? It's only a single line.

2017-06-17 20:31 UTC, Intigracy commented
Muh self merge

2017-06-17 20:36 UTC, Intigracy approved these changes

2017-06-17 20:54 UTC, SonixApache commented
@skullyton

2017-06-17 22:30 UTC, merged