Space Geese NOW
d3athrow/vgstation13 pull request #14772
Opened 2017-05-02 02:09 UTC by TheFriggenSawbones

It's happening.

This pr adds a new type of mob, The Space Goose.
![2017-04-23_15-47-07](https://cloud.githubusercontent.com/assets/17213510/25601443/d0aa389c-2eb1-11e7-9f52-49fcdf57b861.gif)

Very similar to space carp, a bit more beefy and less damage. Quacks when it attacks and can be butchered for LIVERS which you can use to make a new dish, Foie Gras.

This PR also reworks the Carp Migration event, it's now An Animal Migration. It's basically the same thing except it can either spawn Space Geese or Carp.

~~~Credits~~~
Space Goose Sprite @Dizor 
Liver and Foie Gras sprites @Blithering 
Github help @HarseTheef 
Coding help @JustSumBody 

🆑 
 * rscadd: Adds Space Geese
 * rscadd: Adds Goose Livers
 * rscadd: Adds Foie Gras
 * rscadd: Reworks the Carp Migration event.

2017-05-02 02:11 UTC, BobdaBiscuit commented
CALL THE SHUTTLE THE GOOSE IS LOOSE!

2017-05-02 02:11 UTC, HarseTheef commented
Congratulations!

2017-05-02 02:14 UTC, salamandooo commented
I like it, very cute sprite

2017-05-02 02:19 UTC, Orangerush commented
more geese sprites WHEN?

2017-05-02 02:33 UTC, ReindH commented
That's a duck.

2017-05-02 02:41 UTC, FudgePucker commented
11/10 :ok_hand:

2017-05-02 02:50 UTC, TheFriggenSawbones commented
@ReindH please don't make up lies to defame me

2017-05-02 03:41 UTC, Shadowmech88 commented
>less damage than space carp

Don't underestimate the strength of geese.
Seriously, a goose will mess you up.

2017-05-02 03:49 UTC, AI-is-rogue commented
@Shadowmech88 
I can confirm this. Geese are terrifying.

2017-05-02 03:51 UTC, IAGFPRMF commented
So what do they look like on space tiles? Do they "walk" through space like in the gif above?

2017-05-02 04:14 UTC, carshalash commented
Nigga thats just the duck from courage the cowardly dog with red eyes. That aint no goose.

![image](https://cloud.githubusercontent.com/assets/16896032/25603742/a5d6eecc-2f41-11e7-9894-3b058ad0df6c.png)

2017-05-02 04:16 UTC, ReindH commented
TOLD YOU SO!

2017-05-02 04:21 UTC, TheFriggenSawbones commented
@IAGFPRMF http://i.imgur.com/cSY9ZIZ.gifv

2017-05-02 04:22 UTC, carshalash commented
The ducks from courage the cowardly dog were also from space.

2017-05-02 04:32 UTC, Gunosaguki commented
make them passive when honked by a clown

2017-05-02 04:52 UTC, Anton-Kr requested changes
ITS A FUCKING DUCK

2017-05-02 05:03 UTC, AutismSpider commented
![duck_brothers](https://cloud.githubusercontent.com/assets/10268342/25604649/afcc0d1c-2eca-11e7-8df0-2e1bcb28a3be.png)

Were  the space chicken?

2017-05-02 07:16 UTC, Riekland commented
but
why

2017-05-02 07:30 UTC, TheFriggenSawbones commented
why not

2017-05-02 07:43 UTC, Furbeh commented
![](https://s-media-cache-ak0.pinimg.com/originals/32/0e/fd/320efdcd5d2f8bb0cbae681b4fd56176.jpg)

2017-05-02 07:45 UTC, carshalash commented
Duck, duck, clearly not a goose

2017-05-02 10:27 UTC, NigglyWiggly commented
The problem is that Ducks are nice and Geese are hell creatures and this is clearly just a duck with a long neck

2017-05-02 10:31 UTC, Exxion commented
From the front, its head looks like a Bellsprout

2017-05-02 12:28 UTC, BestName commented
@Shadowmech88
You're thinking of swans

2017-05-02 13:18 UTC, Shadowmech88 commented
Geese may not be as bad as swans, but they're still pretty bad.

2017-05-02 14:09 UTC, Exxion commented
The only difference I'm aware of is that swans know no fear

2017-05-02 16:09 UTC, DamianX commented on code/modules/reagents/reagent_containers/food/snacks/meat.dm
> +	New()
ugh, relative paths

2017-05-02 16:12 UTC, DamianX commented
Space goose has evolved to be far greater than the traditional goose. In fact, it sports not one but FOUR livers that you can butcher out of it.
![image](https://cloud.githubusercontent.com/assets/6307265/25627423/d34f3442-2f62-11e7-80c3-0269fdfb4852.png)

2017-05-02 17:12 UTC, TheFriggenSawbones commented
the goose lore is deep

you see... NanoTrasen bio-engineered the geese to have MULTIPLE livers, and be space fairing, so they could mass produce foie gras and sell it to rich people for dope profits.

except one day the syndicate blew up Goose Observation Post 32 and released the geese into the wild, causing the great Murder of Space Geese to spread throughout the universe.

2017-05-02 18:06 UTC, ComicIronic commented on code/game/machinery/kitchen/microwave.dm
> +			if (istype(O,/obj/item/weapon/reagent_containers/food/snacks/meat/goosemeat))
Can you put this with the rest of the meat? It makes the block a bit neater.

2017-05-02 18:08 UTC, ComicIronic requested changes

2017-05-02 18:08 UTC, ComicIronic commented on code/modules/admin/topic.dm
>  					new /datum/event/carp_migration
Change the name of the datum.

2017-05-02 18:08 UTC, ComicIronic commented on code/modules/reagents/reagent_containers/food/snacks/meat.dm
> +	New()
Yeah, don't do this.

2017-05-02 18:54 UTC, Commandersand commented
Dang c*ders

2017-05-02 18:55 UTC, ComicIronic commented
Banned for slur.

2017-05-02 19:33 UTC, TheFriggenSawbones commented
travis why

2017-05-02 19:42 UTC, TheFriggenSawbones commented
what does it MEAN

2017-05-02 19:50 UTC, ComicIronic approved these changes

2017-05-02 19:51 UTC, ComicIronic requested changes

2017-05-02 19:51 UTC, ComicIronic commented on code/datums/helper_datums/command_alerts.dm
>  /datum/command_alert/carp/announce()
Didn't change this path!

2017-05-02 20:06 UTC, ComicIronic requested changes

2017-05-02 20:06 UTC, ComicIronic commented on code/modules/events/animal_migration.dm
> +	for(var/mob/living/simple_animal/hostile/carp/C in spawned_carp)
This won't remove Geese after the migration is over - you need to loop over a more generic type.

2017-05-02 20:06 UTC, ComicIronic commented on code/modules/events/animal_migration.dm
> +	var/list/spawned_carp = list()
Change the name of this variable.

2017-05-02 20:22 UTC, ComicIronic approved these changes

2017-05-02 21:05 UTC, PJB3005 approved these changes

2017-05-02 22:47 UTC, d3athrow commented
quack

2017-05-03 01:46 UTC, Megamaw commented
official goose lore + excellent animation

merge it

2017-05-03 08:35 UTC, SonixApache commented
i fucking hate geese

2017-05-04 04:39 UTC, Kuranon commented
I don't like how it's basically just "it's a goose but now it's here in space too". For space carps, I thought for the longest time it was actually just some weird spacefaring alien lifeform before reading the lore because it just looked so alien and that's kind of believeable in whatever weird scifi univerese SS13 is in, but literal space birds that seem to be in no way different from the actual Earth animal is just over the line for dumb. The sprite is really mediocre compared to carp as well, and  the way it literally walks through space is very unappealing to see

2017-05-04 04:49 UTC, Shadowmech88 commented
This may be using the existence of space bears as a precedent, but space bears are incredibly uncommon mobs, usually only seen during adminbus.
I agree that, for such a common mob, having it just be an Earth animal that doesn't need to breathe seems somewhat lazy.

I'd suggest either making it an actual goose that can't survive in space, in which case it would be comparable to goats, or making it look reasonably alien so that it merely resembles a goose, in the same vein as space carp.

2017-05-04 08:34 UTC, clusterfack commented
Slippery slope with the prefix space

2017-05-04 11:20 UTC, yclatious commented
Glad to see its shaping up to be a real thing but like others have said, you should really get a new sprite for it, this just looks like goons wacky unkillable animals, a actual fucked up goose in space would fit much better than this wacky cutesy thing, besides, geese are the spawn of satan, why is this one cute?

2017-05-04 11:23 UTC, Furbeh commented
It's cute cause it's actually a duck with a long neck, not a goose

2017-05-04 16:12 UTC, Riekland commented
What he said
Space carp have extra fins and teeth, space bears have stars in their coats
What makes this anything other than just a goose

2017-05-04 20:36 UTC, ReindH commented
The fact that it's a duck?

2017-05-04 21:18 UTC, PJB3005 commented
You know I feel that at one point we need to start having quality control.

Maybe we should begin with this PR 🤔

2017-05-04 21:26 UTC, yclatious commented
Cmon pjb, the code is decent and the only really big issues are the sprite and maybe the liver ammount,  dont be a no fun dutchman and just ask for those to be fixed before a merge.

2017-05-04 21:41 UTC, TheFriggenSawbones commented
@PJB3005 what do you even mean

2017-05-04 21:44 UTC, Commandersand commented
Brb porting dakis

2017-05-04 22:09 UTC, sonime commented
Make it not common, like admin-only thing and I'll give it a thumbs up

2017-05-04 22:31 UTC, TheFriggenSawbones commented
@sonime my problem with that is I don't want it to be admin spawn only

2017-05-04 22:36 UTC, yclatious commented
If we are all going to be honest here, even if it was adminspawn only, it would still be spammed like a certain race of short stacked door fuckerson release, except instead of a certain *someone* spawning them its just be memebones.

2017-05-05 02:14 UTC, Blithering commented
Where would they spawn in the event? in space like carp do?

2017-05-05 02:55 UTC, TheFriggenSawbones commented
Yeah they spawn in carp areas.

I could totally make them an infestation event instead but I'd like a bit more feedback first.

2017-05-09 07:54 UTC, mtpowell commented
No, god no.

There's no point to this, it's a snowflake mob with a snowflake ingredient. It's even weaker than carp and therefore NERFS carps by taking up their spawns.

2017-05-09 08:08 UTC, Exxion commented
It's a meme mob except without an actual meme to at least give it some humor value
I'm sorry Sawbones but I really don't see the point

2017-05-09 12:37 UTC, Riekland commented
I don't actually get it is there some epic twitter meme about geese or something

2017-05-19 06:53 UTC, Intigracy commented
conflicts
memes
what next

2017-05-20 23:06 UTC, TheFriggenSawbones commented
@Intigracy trying 2 figure out what i need to change to get it merged, outside of the conflicts ofc

2017-05-20 23:23 UTC, PJB3005 commented
I was serious when I said we need quality control.

Seriously. Make this something other than a dumb meme or I doubt it's getting merged.

2017-05-21 03:23 UTC, Shadowmech88 commented
At the very least make the space goose look like it's not just a regular goose that can breathe in space.

2017-06-17 02:31 UTC, SonixApache commented
wipe this meme off the face of the earth

2017-06-17 05:27 UTC, Exxion commented
https://www.youtube.com/watch?v=WChTqYlDjtI

2017-06-17 05:27 UTC, closed without merging