Talking medbots
d3athrow/vgstation13 pull request #14775
Opened 2017-05-03 19:24 UTC by Software-Pirate-Captain

Hello there!

This is a fairly small pull request that doesn't really change anything major to do with game balance, although I'll clarify up front that it does make medbots take a few extra seconds to start actually treating problem if their speakers are enabled.

This adds a new folder full of sounds, some of which are then played by station-built medbots when treating people. There's sounds for being built, being destroyed, being emagged, types of damage, beating severity, things like that. Might update it with a few more if it's popular/well received!

I'm not aware of any changes to balance except for slightly delaying the actual healing injections, it's just a fun little fluff thing.

2017-05-03 19:31 UTC, Kammerjunk commented
>This is a fairly small pull request
>Files changed 20

¯\\_(ツ)_/¯

2017-05-03 19:32 UTC, Software-Pirate-Captain commented
Those are just audio snippets, not really anything code-related. I mean, you've got a point, but it's not like I've entirely rewritten cult or something.

2017-05-03 19:33 UTC, yclatious commented
Webm with sounds when

2017-05-03 19:33 UTC, Riekland commented
I really like this
I thought I would hate it but I love it
Aren't there some unused lines for radiation and shit? That would be nice to have so that people coming into medbay could have the little boxes scream at them about the green glowing

2017-05-03 19:34 UTC, Software-Pirate-Captain commented
Yeah, there's a lot, including for internal bleeding and broken bones, but I'd rather put up this small-ish version first and upgrade it later than spend forever struggling with a few tough parts, refusing to release the bits that do work.

Is that fair?

2017-05-03 19:36 UTC, Riekland commented
No, you have to add a DNM tag and then leave the pr up for a few years while you make other shit and then come back to it after someone's added OC soundfiles and start drama
I don't even know how it works but I would have assumed something like IB is an on off thing in the limb that the medbot could check
Don't look at me though

2017-05-03 19:37 UTC, Software-Pirate-Captain commented
I do intend to tackle it by cycling through every limb on the patient, as you suggest, but right now I'm trying to do some kind of managed, staged delivery rather than just throw the entire kitchen sink in one go and get out of my depth. :)

2017-05-03 19:37 UTC, Kammerjunk commented
Sure, nothing wrong with deploying small bits fast rather than big bits slow far as I see

2017-05-03 20:17 UTC, TheFriggenSawbones commented
It's neat but it could use some work maybe.

For one, they seem to overlap alerts sometimes which causes the sounds to overlap, its kinda messy.

This becomes more apparent when you have 2-3 (the norm I guess) medbots running at once.

I'm also not a fan of the flat-line sound, especially on medibot death.

2017-05-03 20:20 UTC, Software-Pirate-Captain commented
I'm aware of the overlap but I've been struggling with a while on fixing it, since they don't always seem to pause when they're supposed to. Provided that they don't detect the wounded patient when they're right to it and have to actually move to it, there's no problem.

I'm not so sure about 2/3 bots being the norm, I normally only ever see one of them in medical and even then that's if you're lucky, but if you're sure I'll take your word for it.

I'll take another look at this if those things you mentioned become an issue.

2017-05-03 23:05 UTC, Riekland commented
`>they don't always seem to pause when they're supposed to.`
I bet you'd need to redo all of bot code to fix that
Do we have a volunteer here or are you gonna be a LIL BITHC

2017-05-03 23:13 UTC, Exxion commented
>tfw bots still aren't even mobs

2017-05-03 23:14 UTC, Software-Pirate-Captain commented
Latter, sadly. I can lay out _exactly_ why they overlap and don't always report if you'd like, it's to do with the specialist reagent thing.

Essentially, if it detects that a person already has the reagent it would give them to fix a given damage type, it'll just move on. When it gives tricord for three of those, it means that as soon as it treats one, it'll ignore the others, since they already have the "treatment" in them for anything that isn't it's special reagent.

You're right, it WOULD require almost entirely redoing medbots, no I'm nowhere good enough to do that, not without tearing out the specialism thing which is actually a really nice piece of work.

2017-05-03 23:46 UTC, Shadowmech88 commented
@Software-Pirate-Captain 
If you wish to prevent the sounds from overlapping, you can have medbots play their alert sounds on a specific channel just for them. Only one sound can be played on a channel at a time, so you would only hear the last to be played rather than hearing all of them at once.

2017-05-03 23:48 UTC, Software-Pirate-Captain commented
...Learn something new everyday. Is there some example code for this? I'll tweak it tomorrow and adjust the pullreq if so!

2017-05-03 23:57 UTC, Shadowmech88 commented
You just need to add a new sound channel define, as seen here: 
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/__DEFINES/setup.dm#L1372

Then give that channel define as an argument to `playsound()`, for example 
`playsound(src.loc, 'sound/medbot/Chemical_Detected.ogg', 35, channel = CHANNEL_MEDBOT)`

2017-05-04 22:51 UTC, Software-Pirate-Captain commented
Implemented channels as suggested. Doesn't seem to be queuing them correctly, instead dropping one that would overlap instead of playing both at once, but that's still a big improvement.

Anything else?

2017-05-05 02:24 UTC, Shadowmech88 commented
>Doesn't seem to be queuing them correctly, instead dropping one that would overlap instead of playing both at once

That's intended. When using a single channel, playing a sound terminates any sounds that were already playing.
I didn't mean to imply that they would be queued and played one after another.

2017-05-05 19:32 UTC, Software-Pirate-Captain commented
Then I guess that's working as intended! :)

With that sorted, I think that's everything I'd wanted to tackle for this one. Is the next step to sit back and wait for it to be merged or closed?

2017-05-05 19:44 UTC, Commandersand commented
Wait five years for collabs to do their job

2017-05-06 20:01 UTC, ihadtoregisterforthis commented
Could you provide a demonstration of this in action?

2017-05-09 21:15 UTC, ComicIronic commented
This is still waiting for a video with sound.

2017-05-10 21:54 UTC, Software-Pirate-Captain commented
Got a somewhat busy IRL schedule right now, I'll get on it as soon as a gap in finals opens up. Apologies.

2017-05-23 19:46 UTC, Software-Pirate-Captain commented
Aaaaaalrighty, got some Webms with sound for you all. How would you like them hosted? I'll throw them up on a burner Mega account for now.

2017-05-23 19:47 UTC, Shadowmech88 commented
Puu.sh is the simplest way to host, I think.

2017-05-23 19:55 UTC, Software-Pirate-Captain commented
There's gotta be a way that doesn't involve another piece of dodgy freeware?

2017-05-23 20:02 UTC, Shadowmech88 commented
>dodgy freeware

I thought it was fairly common and dependable.

Anyway, there are plenty of free direct-access filehosting sites you can upload to from a browser. https://pomf.cat/ for example.

2017-05-23 20:05 UTC, Exxion commented
It is fairly common, though at one point someone did manage to hijack their update server or something and give a bunch of people viruses or something
They're probably more careful now though

2017-05-23 20:10 UTC, Software-Pirate-Captain commented
I'll use the Pomfcat one. As I said, turns out I need to reshoot some of the stuff due to an audio desynch. Please bear with me!

2017-05-23 20:39 UTC, Software-Pirate-Captain commented
https://a.pomf.cat/mytyjy.webm
https://a.pomf.cat/isgdyb.webm
https://a.pomf.cat/ivfqpf.webm
https://a.pomf.cat/undpno.webm

Ta-Da!~

Apologies for the desynch, I've tried a couple of things but can't fix it. The software seems to just be behind what going on by half a second. Seems to get worse as time goes on, since towards te end of the long one it's several seconds out of whack, but there's nothing I can do, it seems.

2017-05-23 21:20 UTC, Shadowmech88 commented
Put them in the OP as well.

2017-05-23 21:21 UTC, Software-Pirate-Captain commented
Done. What're your thoughts?

2017-05-23 21:30 UTC, Shadowmech88 commented
I think it sounds fine.

2017-05-23 21:38 UTC, yclatious commented
Sounds good and fits surprisingly well so, good stuff.

2017-05-23 22:08 UTC, Software-Pirate-Captain commented
Alright. Any ETA on it being merged, or is it just the waiting game now?

2017-05-24 07:12 UTC, Skullyton commented on code/game/machinery/bots/medbot.dm
> -		var/message = pick("All patched up!","An apple a day keeps me away.","Feel better soon!")
feature loss!

2017-05-24 07:17 UTC, Skullyton commented
>there's a radiation detected.ogg

You've given me an idea

2017-05-24 17:51 UTC, Software-Pirate-Captain commented
I pulled those messages out on purpose due to finding them annoying as hell, guess I shouldn't have just assumed that everyone else did too.

As for the unusued lines, I intend to come back to this when the real world quietens down for me and do something with them. The internal bleeding, major and minor fracture lines as well as the radiation one are just perfect.

2017-05-31 23:30 UTC, Software-Pirate-Captain commented
Any updates on this one?  It's just sitting around being all open right now, and I'm not aware of any action I need to take?

2017-06-03 01:50 UTC, SonixApache commented
HL1 bitching betty sounds are nice, but it feels wrong having them on something that isn't a suit

2017-06-03 11:45 UTC, Skullyton commented
holy moly, this's been open a month.

Have one last scour through the code and find places where it doesn't check for shut up when it comes to making the sounds.

Heck, I'll go through it now

2017-06-03 11:47 UTC, ghost requested changes
just have more of the sounds adhere to shut_up and it'll be golden

2017-06-03 11:47 UTC, Skullyton commented on code/game/machinery/bots/medbot.dm
> +			playsound(src.loc, 'sound/medbot/Biohazard_detected.ogg', 35, channel = CHANNEL_MEDBOTS)
have a shut_up check for here

2017-06-03 11:47 UTC, Skullyton commented on code/game/machinery/bots/medbot.dm
> +		playsound(src.loc, 'sound/medbot/Flatline_custom.ogg', 35, channel = CHANNEL_MEDBOTS)
shut_up check needed here

2017-06-04 15:08 UTC, merged