Re-adds Valentine's Day Chocolate
d3athrow/vgstation13 pull request #14788
Opened 2017-05-05 14:36 UTC by Shadowmech88

Except it only appears in uplinks and merch computers on Valentine's Day.
If one is somehow spawned otherwise, such as via cooking, and it's not Valentine's Day, it gets replaced with a burned mess.

2017-05-05 18:34 UTC, Skullyton commented on code/game/machinery/computer/store.dm
> +	if(month == "02" && day == "14")
Might be an idea to have a define or macro or something, so we don't have all these month and day variables floating around, and encourage others to have some things locked behind certain dates.

2017-05-05 18:36 UTC, PJB3005 commented on code/game/machinery/computer/store.dm
> +	if(month == "02" && day == "14")
Do `if (time2text(world.realtime, "DD:MM") == "14:02")` instead.

2017-05-05 21:02 UTC, Blithering commented
It was a shame to have all the holiday stuff reverted rather than commented out. Automating the readding of it is even better.

2017-05-05 23:40 UTC, Shadowmech88 commented on code/game/machinery/computer/store.dm
> +	if(month == "02" && day == "14")
I'll format it as `"MM/DD"` instead.

2017-05-05 23:47 UTC, Skullyton commented on code/game/machinery/computer/store.dm
> +	if(month == "02" && day == "14")
madman

2017-05-05 23:52 UTC, ComicIronic requested changes
Woops

2017-05-05 23:52 UTC, ComicIronic commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	if(time2text(world.realtime, "MM/DD") == "02/14")
`!=`

2017-05-06 00:02 UTC, ComicIronic approved these changes

2017-05-06 12:45 UTC, SonixApache commented
neat

2017-05-14 22:28 UTC, merged