Added bricks to smelting recipe
d3athrow/vgstation13 pull request #14804
Opened 2017-05-07 20:12 UTC by AlphaBuffalo

As title states. Tested works, but with a weird bug that when you make bricks it also makes glass, I suspect it has something to do with the smelter itself or maybe something else but it shouldnt cause a problem since this is a minor content addition anyways.

2017-05-07 20:45 UTC, Commandersand commented
>more things miners will never bother to smelt

2017-05-07 21:03 UTC, AlphaBuffalo commented
I only added because wad was making a new station and was using the brick walls, I added brick walls before I added a smelting recipe for the bricks

2017-05-08 11:27 UTC, ComicIronic requested changes

2017-05-08 11:27 UTC, ComicIronic commented on code/modules/mining/smelting.dm
> +		MAT_SAND = 1
`MAT_GLASS`. This is the source of your bug.

2017-05-08 14:36 UTC, Shadowmech88 commented
Won't changing the materials to `MAT_IRON` and `MAT_GLASS` just make it require smelting an iron sheet and a glass sheet instead of smelting an iron sheet and a pile of sand?

2017-05-08 14:37 UTC, AlphaBuffalo commented
/datum/smelting_recipe/glass
	name = "Glass"
	ingredients=list(
		MAT_GLASS = 1
	)
	yieldtype = /obj/item/stack/sheet/glass/glass

You need MAT_GLASS to make Glass

2017-05-08 18:32 UTC, ComicIronic approved these changes

2017-05-12 19:06 UTC, AlphaBuffalo commented
Is this ready for merge?

2017-05-12 19:14 UTC, Commandersand commented
Yes, just wait for c*llabs to do their god damn job

2017-05-14 00:40 UTC, Exxion commented
>implying any of us have jobs

2017-05-19 07:01 UTC, Intigracy commented
Did you test to make sure it works after the change?

2017-05-22 18:33 UTC, AlphaBuffalo commented
it worked

2017-05-22 21:39 UTC, merged