Bringing back flavor text
d3athrow/vgstation13 pull request #14893
Opened 2017-05-18 17:33 UTC by CodenameB

This PR will bring back flavor text, reverting it's deletion some time ago.

Additionally, this adds a dna.flavor_text variable that has been used to fix changelings, cloning, and DNA modifiers to allow them to copy flavor text correctly. 

Another feature makes it so that your flavor text will not appear if your face isn't recognizable. 

These two fixes should prevent all of the metagaming problems that the previous incarnation of flavor text had. 

This is my first PR in a long time, so I may be doing this wrong. There may be ways to simplify my code, I don't really understand byond that well yet.

Thanks to DamianQ on discord for the help in bugfixes.

2017-05-18 17:37 UTC, Commandersand commented
QUESTION, does it still show if you scramble your DNA?

2017-05-18 17:38 UTC, Shadowmech88 commented
Is the changing of flavor text logged? I remember in the past there was an issue with people using flavor text for unlogged communication.

2017-05-18 17:46 UTC, CodenameB commented
Commandersand :
I haven't actually tested scrambling DNA, I didn't think to. I don't believe it will be an issue, since if it did remove flavor text, everyone would lose their flavor text upon getting an SE injection, or accidentally getting radiation, so that would be a problem. It WILL remove their flavor text if they copy a monkeyman's UE.

Shadowmech88:
I don't remember hearing that issue. In any case, I think I made sure not to reimport changing flavor text mid-round, so that shouldn't be a problem either.

2017-05-18 18:15 UTC, Shadowmech88 commented
The format for replying to people on Github is @username, it'll give them a notification even if they're not subscribed to the thread.

2017-05-18 20:50 UTC, Exxion commented
Optimally, there would be separate flavor texts applied depending on whether you can see the face or just the body, whether you've heard them speak, etc.
But that's probably excessive for this server
Well, maybe the first example isn't

But this removes all the really bad problems with the old system, so it's fine

2017-05-18 22:42 UTC, Orangerush commented
Imagine being the c*ders to remove flavor text in the first place instead of fixing it

2017-05-18 22:42 UTC, Riekland commented
h*ll yeah

2017-05-18 23:48 UTC, cadaverouscoyote commented
about time

2017-05-19 03:19 UTC, BobdaBiscuit commented
\>just deleting the database migration file and leaving a missing number

Kek

2017-05-19 04:50 UTC, clusterfack commented
How is this supposed to fix the problem with voice changers?

2017-05-19 05:08 UTC, CodenameB commented
@clusterfack the voice changer mask is a HIDEFACE mask right? If so, wearing it will make it so that your flavor text isn't displayed.

2017-05-19 14:06 UTC, Uqualm commented
https://en.wikipedia.org/wiki/Kill_Bill:_Volume_1

2017-05-19 14:08 UTC, Commandersand commented
>literal who fixes flavor text when the c*ders just outright removed it

:thinking:

2017-05-19 18:51 UTC, PJB3005 commented
You literally cannot fix flavor text properly.

2017-05-19 18:55 UTC, PJB3005 commented
Unless you're planning to make flavor text fool proof bug and exploit free (good fucking luck), this shit aint getting merged on my watch mate.

2017-05-19 19:02 UTC, PJB3005 commented
Actually nevermind I decided to read the OP.

I still think it's a retarded mechanic though.

2017-05-19 19:08 UTC, Commandersand commented
>PJB says he won't merge and that it'll never be properly fixed before reading the OP

:thinking:

2017-05-19 19:21 UTC, Orangerush commented
I came here to laugh at PJB

2017-05-19 19:24 UTC, Riekland commented
![1493785557136](https://cloud.githubusercontent.com/assets/9220789/26263539/26f8aabc-3cd1-11e7-90e3-26fb84d5e163.jpg)

I refuse to believe that PJB is a real human being and that he, a teenage dutch girl, is allowed to make decisions or contributions to this serb

2017-05-19 19:25 UTC, Kammerjunk commented
I also came here to laugh at PJB
Ha

2017-05-19 20:08 UTC, BobdaBiscuit commented
Heh

2017-05-19 21:24 UTC, Exxion commented
I still think there should be two separate parts for body and for face (for example, "he's tall" would always show, but "he's ugly" would only show if the face is visible and not fucked up), but I'm not going to insist on it

2017-05-19 21:36 UTC, cadaverouscoyote commented
> Actually nevermind I decided to read the OP.

![rotoscoping](https://cloud.githubusercontent.com/assets/18200977/26267667/6a1d7bbe-3cb9-11e7-8e79-654071ffb650.jpg)

2017-05-19 21:46 UTC, Shadowmech88 commented
>I still think there should be two separate parts for body and for face

That would require administrating flavor text, though.
Otherwise what's to stop people from putting their name in their body text so it shows up even when their face is hidden?

2017-05-19 21:49 UTC, Exxion commented
That would be blatant metagaming and would fall firmly within the realm of illegal
Old flavor text had a strictly worse version of the same exploit, and I only ever saw one person do that. And they're permabanned now.

2017-05-23 22:56 UTC, CodenameB commented
I put back the migration. Can I get another review?

2017-05-24 07:46 UTC, DamianX requested changes

2017-05-24 07:46 UTC, DamianX commented on vgstation13.dme
> -#include "code\modules\migrations\SS13_Prefs\007-remove-flavortext.dm"
don't remove this

2017-05-24 07:46 UTC, DamianX commented on code/modules/migrations/SS13_Prefs/007-remove-flavortext.dm
> +/datum/migration/sqlite/ss13_prefs/_009
You don't need to change this file at all, just revert it back to what it originally was.

2017-05-24 16:04 UTC, DamianX commented on code/modules/migrations/SS13_Prefs/007-remove-flavortext.dm
> +return TRUE
You missed an indent here.

2017-05-24 16:35 UTC, DamianX commented on code/modules/mob/mob.dm
> +/mob/proc/update_flavor_text()
This proc and the one below are useless, get rid of them.

2017-05-24 16:45 UTC, DamianX commented on code/game/atoms.dm
> +				H.dna.flavor_text = H.dna.flavor_text
did you mean `H.dna.flavor_text = H.flavor_text`?

2017-05-24 16:47 UTC, DamianX commented on code/game/dna/dna_modifier.dm
> +					databuf.dna.flavor_text=connected.occupant.flavor_text
I don't think copying Structural Enzymes should copy the flavor text as well?

2017-05-24 17:02 UTC, DamianX commented
You reset pox raiders' flavor text but not nuke ops'. Did you look into this?

2017-05-24 17:13 UTC, CodenameB commented
I very briefly thought about nuke ops, however unlike Vox they keep their original bodies, so keeping their flavor text seemed fine. Besides, their faces are covered anyway, so flavor text won't be displayed unless they are captured and stripped, in which case it is rather unimportant.

For stealth ops, a bunch of people with the same last name and no flavor text would make them an instant giveaway to metagamers. If you allow flavor text, you can never be 100% sure, even if you have flavor text memorized, that your favorite static name didn't just change names.

2017-05-24 17:46 UTC, CodenameB commented on code/game/dna/dna_modifier.dm
> +					databuf.dna.flavor_text=connected.occupant.flavor_text
Hm, I removed line 977 from dna_modifer.dm, so I don't know why this isn't listed as outdated.

2017-05-24 21:12 UTC, SonixApache commented
i have a suggestion on how to fix this for the angry traditionalists that stalk the github

"Add a toggle."

2017-05-24 21:33 UTC, DamianX commented
Did that stop the attack animation shitposting? Riddle me this.

2017-05-24 21:51 UTC, SonixApache commented
You can't kill the shitposting, but the toggle got the feature through.

2017-05-24 21:55 UTC, Shadowmech88 commented
Does it appear as though this feature won't go through?
The votes are overwhelmingly in its favor.

2017-05-24 22:06 UTC, SonixApache commented
¯\_(ツ)_/¯

2017-05-24 22:34 UTC, Exxion commented
Personally, I just like to give plenty of time for review. The last changes were only a few hours ago.

2017-05-24 22:44 UTC, CodenameB commented
I haven't seen any colabs actively against allowing it in, just PJB saying he dislikes the mechanic.

2017-05-24 23:59 UTC, Unknown-as-Captain commented
Don't think this fixes the problem with wizards still keeping the flavor text from your (((staticname))).

Furthermore, doesn't flavortext still allow metagay in the sense that having flavortext more-or-less confirms you're not a wizard, newcop or pox raider? There will ALWAYS be some problem with this dumb feature.

2017-05-25 16:54 UTC, cadaverouscoyote commented
>having flavortext more-or-less metaconfirms you're not a wizard, newcop or pox raider

if it can still be edited mid-round, no

2017-05-25 16:55 UTC, Skullyton commented
Idea: Flavortext is toggleable, and if not customized defaults to the randomized flavortext from april fools

2017-05-26 00:19 UTC, FudgePucker commented
Big problem with this.
It encourages bay style RP where you are roleplaying by being an OC DO NOT STEAL instead of roleplaying via your actions.

2017-05-26 03:32 UTC, Exxion commented
There is exactly no reason one would hinder the other

2017-05-26 09:57 UTC, nuklearcellphoneg commented
Flavor text is 100% fine as a concept, the only issue that ever came from it was it being abused to see through disguises, to communicate, y'know exploits. I think having it as a 'toggle' thing is dumb too, just have it on all the time- in regards to attack animations, they never should have been added in the first place- 66 to 63 votes.

Does setting force random name/appearance remove the flavor text? If not, it needs to, otherwise it renders the point of that null and void.

2017-05-26 14:50 UTC, CodenameB commented
@nuklearcellphoneg 
This fixes those exploits.

I'll check into appearance bans. but it is my understand that appearance ban is very rarely used anyway.

2017-05-26 19:07 UTC, Exxion commented
The issue @Unknown-as-Captain brought up is still relevant though

2017-05-27 05:01 UTC, Unknown-as-Captain commented
And if this gets added can we please have the administration do something about "flavor texts" that aren't even IC descriptions but forum-signature-tier random shit that has nothing to do with the character
Case in point, Sawbone's flavor text

2017-05-27 05:04 UTC, CodenameB commented
@Exxion I don't see what issue he mentions? Nuke ops and other human antags still get flavor text, so there is no meta. Likewise, "The wizard had Sawbone's flavor text" can in no way be used as a meta tool, other than you know who the player would be any other round. This knowledge does not benefit you. After all, you get the exact same knowledge about every single other player too.

@Unknown-as-Captain I agree, but that is an administration issue. PRs won't fix that.

2017-05-27 05:14 UTC, Unknown-as-Captain commented
You see (((Staticname Lesbian)))'s flavor text on a random assistant
This random assistant is not (((Staticname Lesbian)))
There is a 99% chance this means they are a wizard, now the roundtype was spoiled to me from some stupid feature in a way I couldn't avoid noticing.
It's like some faggot ickocking that you have to ignore. My gameplay is worsened by having to ignore this ickocking faggot and play dumb until I confirm the wizard IC.

2017-05-27 05:20 UTC, CodenameB commented
@Unknown-as-Captain The obvious simple solution is don't be a stealth wizard if you're gonna be a flavor text snowflake. 

However, to actually fix it: someone can write a very quick fix (probably two lines of code) that gives wizards a second popup after they pick their name to give them the option to change their flavor text at round start. If this still isn't merged by Monday I'll do it myself. Nuke ops too, would be just as easy.

2017-05-27 05:21 UTC, Unknown-as-Captain commented
The obvious simple solution is let's stop adding more issues into the game and say "I'll fix it later maybe".

2017-05-27 05:24 UTC, CodenameB commented
@Unknown-as-Captain Feel free to learn to code anytime friendo. I just don't have time to fix it at midnight on a Friday.

2017-05-27 15:57 UTC, Exxion commented
Raiders at least *do* lose their flavor text, unless I'm fucking stupid and misread the code

2017-05-27 17:11 UTC, CodenameB commented
Vox raiders are set to loose flavor text. If I am changing wiz and ops, then I'll probably change them too.

2017-05-27 17:26 UTC, Exxion commented
Ops and raiders specifically are kind of problematic, because if they're trying for stealth, they could be fucked over either by their flavor text *or* their lack of flavor text, and I'm not really sure how to fix that.
I guess that applies to wizards too, but fuck stealth wizards

2017-06-17 02:34 UTC, SonixApache commented
@Intigracy when

2017-06-17 05:25 UTC, Exxion commented
When the exploit on wizards/raiders/ops is fixed
The author hasn't done anything recently though
Someone else can write those popups, or, even better, come up with a better solution
But the popups are sufficient if nobody can think of anything better

2017-06-19 03:12 UTC, cadaverouscoyote commented
if flavor text can still be edited the same as i remember it, there's no need. when you clicked the button it brought up an empty window, and if you didn't re-enter your flavor text yourself then it would be cleared. to my knowledge there's no way to discern if somebody accidentally cleared it or not.

but maybe i just don't fuckin get it because i never even saw the problem with flavor text in the first place. if there was a discrepancy that exposed somebody as an antag which would be noticeable ic, then it's an ic issue. if they're exposed by something that _nobody_ could know ic, acting on that info would be metagay and breaking the rules. i don't see the point in removing the feature instead of the metagamer, may as well remove deadchat and re-entering your body as a ghost. even that absurd example would prevent more metagaming and save admins more effort than removing flavortext.

seems like bad policy to me to change the code to accommodate those who break the rules instead of just enforcing them, but then again not my server.

2017-06-19 03:39 UTC, Shadowmech88 commented
I think the issue is people metagaming in ways that can't be reliably tracked, or reliably judged due to plausible deniability.
Sure, you can't *call them out* as an antag due to flavor text or whatever, but you could be more cautious around them than you would otherwise, in a way that can't be detected by others but still impacts the round nonetheless.

If we have the ability to patch those holes via code without any major impact to the quality of the feature, shouldn't we?

2017-06-19 03:53 UTC, cadaverouscoyote commented
>but you could be more cautious around them than you would otherwise, in a way that can't be detected by others but still impacts the round nonetheless

that's why i drew the comparison to deadchat and ghosting for.

>If we have the ability to patch those holes via code without any major impact to the quality of the feature, shouldn't we?

yeah i'm just gettin pissed it's taking more than a month to re-add a feature removed over what's a non-issue imo, which has been mostly rectified. couldn't merge it three weeks ago then patch it up later when there's ass to be dragged, lord no.

2017-06-20 04:35 UTC, nuklearcellphoneg commented
It was removed for pretty big metagaming issues honestly.

2017-06-20 04:44 UTC, Exxion commented
Yeah that

This implementation doesn't have a button to change flavor text mid-round, which is why the popup for certain antag types to set their flavor text at roundstart is important.
This implementation *couldn't* really have that button, because it attaches flavor text to DNA, and multiple people can have the same DNA if there's a changeling or wacky geneticist antics.

2017-06-20 13:31 UTC, cadaverouscoyote commented
well fuckin shit

2017-06-21 19:23 UTC, CodenameB commented
I haven't done the wizard/ops/raiders fix because I still don't really truly understand flavor text since someone else wrote it, and I don't understand how the wizard's name popup works either. I'll get working on it some weekend, but would love if someone else could take a look.

2017-07-06 23:53 UTC, SonixApache commented
@CodenameB conflicts

2017-07-07 18:35 UTC, Riekland commented
wait hold on why aren't we just porting the bay flavour text that has you make different lines for different body parts that only show up if they're not covered up

2017-07-07 19:44 UTC, Exxion commented
1. Someone would have to do it
2. More trouble for administrators having to administrate each piece of flavor text
3. The unfathomable amount of shitposting that would occur virtually everywhere

In that order.

2017-07-13 15:46 UTC, Blithering commented
>not tattooing your name and blood type on each body part for easy identification

2017-08-06 16:37 UTC, N3X15 commented
As much as I hate enabling the waifushittery, please fix the conflicts and contact me so I can get a parallel MR up on the secret repo to fix the conflict.

2017-08-06 23:44 UTC, merged

2017-08-06 23:50 UTC, Exxion commented
We were still waiting on something
Though I guess I should have actually hit the request changes button to make it more clear

2017-08-07 00:34 UTC, Riekland commented
hey nexis remember when you said that you wouldn't do this kind of shit after you took your bi-weekly break for realsies this time
haha yeah

2017-08-09 23:38 UTC, Intigracy commented
This broke SQL