The Mouthbay Update - Dentisty
d3athrow/vgstation13 pull request #14945
Opened 2017-05-20 00:42 UTC by CodenameB

This PR will make the following changes:

Add two new surgeries to the Medbay arsenal. Tooth replacement, and tooth extraction.
The bioprinter can now print generic teeth to insert into a mob.
Gold can now be used to craft gold teeth, these have a new sprite. No other special properties.
An alternate title for doctors has been added, "Dentist"
There is a minor bugfix with dragging objects that affected teeth and caused unrelated stacks to merge.

Suggested followup: Allow replacing teeth with gold to change a mob's desc_modifier to reflect this. This would require some significant changes to the teeth code that I don't think I'm up to.

Thanks to @Kurfursten on github for the idea. Thanks to Shadowmech88 on discord for coding help and the bugfix.

2017-05-20 02:33 UTC, Shadowmech88 commented
When you insert a gold tooth into someone's mouth, does it turn into a regular tooth, or can it be extracted as a gold tooth?

2017-05-20 02:40 UTC, CodenameB commented
@Shadowmech88 

Right now, it very simply increases the patient's teeth counter by one. Adding a gold teeth counter (or different species teeth counter) would involve greatly changing the way teeth are currently coded. Right now, as far as I can tell, they are just a number var. The species and such aren't applied to the teeth until after they pop out, the obj doesn't exist before that. They aren't like organs at all.

I might be misreading the code entirely however.

2017-05-20 02:43 UTC, Shadowmech88 commented
I wonder if it's worth having 32 individual tooth datums for each human mob, just to keep track of all the properties of their teeth.

2017-05-20 04:13 UTC, Kurfursten commented
Since you don't take tooth damage to an individual tooth (Rather, any one tooth has a chance of popping out), it seems like just a counter for gold teeth would be fine (then you could calculate a chance of a gold tooth falling out).

Neat though. 👍 Perhaps another logical extension of this is that a random ailment someone can get (like appendicitus) is "tooth ache" which causes pain but goes away if a tooth is lost (by any means).

2017-05-20 13:34 UTC, Blithering commented
inserting xeno/goliath/catbeast teeth to increase bite damage when?

2017-05-20 13:44 UTC, PJB3005 commented
I don't think the dentist alt title is deserved. 👍 to the rest though.

2017-05-20 14:06 UTC, DamianX commented
You're going to need a changelog

2017-05-20 15:46 UTC, CodenameB commented
@PJB3005
I understand your concern regarding the alt title, here is my reasoning for adding it:

The thought behind the alt title is that the dental job will grow to meet the title. I had the same thoughts as @Kurfursten regarding a random illness (I was thinking an abscessed tooth) but coding it seemed intimidating since it might involve those aforementioned 32 tooth datums. Once we add implanting teeth from other races (to give yourself fangs or extra strong bites, etc) and add some stuff like a debuff to "sweet" food that causes cavities if too much is eaten (Thus ensuring chefs can't spam ice cream and other cheap food, and to make vending machines less appealing) then we would need full time dentists.

Adding the title now puts in a reminder to work on that, and adds motivation.

2017-05-20 19:08 UTC, PJB3005 commented
No, not really.

First I find your point about teeth cavities dumb. Such a feature would cause only infuriation.

If we go that route, add dentist later, not now.

All the other alt titles somewhat make sense. Dentist? Not really. They can stick with surgeon.

2017-05-20 19:12 UTC, PJB3005 requested changes

2017-05-20 19:12 UTC, PJB3005 commented on code/game/machinery/bioprinter.dm
> +		if(choice == !"tooth")
1. This doesn't work, you want `!=`
2. Terrible hack. Do something else.

2017-05-20 19:12 UTC, PJB3005 commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
No relative pathing please.

2017-05-20 19:12 UTC, PJB3005 commented on code/modules/surgery/tooth.dm
> +		return target_zone == "mouth"
Use defines here.

2017-05-20 19:12 UTC, PJB3005 commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
No relative pathing.

2017-05-20 19:12 UTC, PJB3005 commented on code/modules/surgery/tooth.dm
> +/datum/surgery_step/extract
Change the name, it's too generic.

2017-05-20 20:03 UTC, DamianX commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
It's like this on all surgeries, just saying.

2017-05-20 20:04 UTC, PJB3005 commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
So?

2017-05-20 20:18 UTC, DamianX commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
So we may want to fix all of them

2017-05-20 23:55 UTC, CodenameB commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
@PJB3005 
This is the way all of the surgeries are coded. I literally lifted that line directly out of the face surgery code. If you want to go and fix every single surgery, by all means go ahead. I'm not going to.

2017-05-20 23:58 UTC, CodenameB commented on code/game/machinery/bioprinter.dm
> +		if(choice == !"tooth")
If you have actual suggestions, feel free to list them. This line is merely to make it not produce runtimes. The code works fine.

2017-05-21 03:25 UTC, Shadowmech88 commented on code/modules/surgery/tooth.dm
> +	can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
I believe he wants you to just fix this surgery.

2017-05-21 05:29 UTC, PJB3005 commented on code/game/machinery/bioprinter.dm
> +		if(choice == !"tooth")
The code is assuming every thing printed is an organ, which is why you need this hack. Rewrite it so it checks whether the printed thing is an organ before assuming it's one.

2017-05-21 21:55 UTC, CodenameB commented on code/modules/surgery/tooth.dm
> +		return target_zone == "mouth"
Gonna need some help on the best way, if any, to do this.

2017-05-23 22:57 UTC, CodenameB commented
@PJB3005 I believe I have made the changes you requested.

2017-05-29 17:44 UTC, merged