Reduces cost of Shield Generator circuits
d3athrow/vgstation13 pull request #14943
Opened 2017-05-20 00:25 UTC by SonixApache

From 
MAT_GLASS = 2000, SACID = 20, MAT_PLASMA = 10000, MAT_DIAMOND = 5000, MAT_GOLD = 10000
to 
MAT_GLASS = 2000, SACID = 20, MAT_DIAMOND = 2000, MAT_GOLD = 2000

Diamond ensures they won't be TOO common.

:cl:
 - tweak: Lowered costs of shield generator circuitry

2017-05-20 11:15 UTC, PJB3005 approved these changes

2017-05-20 18:28 UTC, SonixApache commented
resolved conflicts

2017-05-23 05:20 UTC, Intigracy commented on code/modules/research/designs/boards/machine_engie.dm
> +	materials = list(MAT_GLASS = 2000, SACID = 20, MAT_PLASMA = 10000, MAT_DIAMOND = 5000, MAT_GOLD = 10000)
wow bill, your mom lets you have TWO materials vars?

2017-05-23 05:20 UTC, Intigracy requested changes

2017-05-23 05:20 UTC, Intigracy commented on code/modules/research/designs/boards/machine_engie.dm
> +	materials = list(MAT_GLASS = 2000, SACID = 20, MAT_PLASMA = 10000, MAT_DIAMOND = 5000, MAT_GOLD = 10000)
Wow Bill, your mom lets you have TWO materials vars?

2017-05-23 09:41 UTC, SonixApache commented on code/modules/research/designs/boards/machine_engie.dm
> +	materials = list(MAT_GLASS = 2000, SACID = 20, MAT_PLASMA = 10000, MAT_DIAMOND = 5000, MAT_GOLD = 10000)
how does this shit slip under the radar

2017-05-23 17:58 UTC, merged