Brans experimental shield generator as 'starscreen' shield generators
d3athrow/vgstation13 pull request #14946
Opened 2017-05-20 00:56 UTC by SonixApache

Brans the experimental shield generators and their related circuits as 'Starscreen'.
Only the front-end is affected; no paths or object names were changed.
Also fixes  #14940
Tested.

:cl:
 - spellcheck: Branded the former experimental shield generators as 'Starscreen' shield generators

2017-05-20 04:45 UTC, Kurfursten commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen.dm
> +	desc = "Gnerates a box-shaped wall of energy when active."
Nanotrasen saving money on vowels?

2017-05-20 09:11 UTC, SonixApache commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen.dm
> +	desc = "Gnerates a box-shaped wall of energy when active."
goddamnit

2017-05-21 04:44 UTC, Exxion commented
Sounds like they want to overthrow Megatron

2017-05-21 16:28 UTC, SonixApache commented
noted for future renaming efforts

2017-05-23 00:24 UTC, Intigracy requested changes

2017-05-23 00:24 UTC, Intigracy commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen_external.dm
>  /obj/machinery/shield_gen/external/New()
This New() has no reason to exist if it's just a ..() call, just turn it into a definition.

2017-05-23 06:53 UTC, clusterfack commented
STARSCREAM

2017-05-23 06:56 UTC, Shadowmech88 commented
Should we code a new hostile robot mob and a new artifact effect which transforms machines into them?

2017-05-23 09:45 UTC, SonixApache commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen_external.dm
>  /obj/machinery/shield_gen/external/New()
so, remove the /New() and ..() ?

2017-05-23 10:49 UTC, Kurfursten commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_gen_external.dm
>  /obj/machinery/shield_gen/external/New()
Yes

2017-05-23 11:08 UTC, DamianX commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_capacitor.dm
> +	name = "Starscreen shield capacitor"
\improper

2017-05-23 11:13 UTC, SonixApache commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_capacitor.dm
> +	name = "Starscreen shield capacitor"
it's a brand name though

2017-05-23 14:54 UTC, Skullyton commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_capacitor.dm
> +	name = "Starscreen shield capacitor"
\improper makes it interpret it as a lowercase name, so in instances of \the [src], it'd go the Starscreen shield capacitor

2017-05-23 14:56 UTC, SonixApache commented on code/WorkInProgress/Cael_Aislinn/ShieldGen/shield_capacitor.dm
> +	name = "Starscreen shield capacitor"
I asked around and now I know what \improper means and does

2017-05-23 17:57 UTC, Intigracy approved these changes

2017-05-23 18:00 UTC, merged

2017-05-23 18:30 UTC, SonixApache commented
next up: renaming the singulo to Magnotron!