Adds Borg Tipping
d3athrow/vgstation13 pull request #15102
Opened 2017-06-01 07:49 UTC by mtpowell

Disarming a borg has a chance to tip it over, similar to pushing over a carbon, with a small chance for the cover to pop open 

![](http://i.imgur.com/uh12mby.gif)

2017-06-01 07:52 UTC, adu6oo commented
i'll throw my remaining two cents here after dumping my entire wallet in the coding discord. 

this is a hackjob way of balancing borgs and in my eyes it just doesnt make sense for some random person on a space station to be able to shover over a mass of metal like nothing

2017-06-01 07:58 UTC, Riekland commented
I don't like it
Maybe only make it possible when a borg is flashed or out of power since one imagines they have some kind of stabilizing shit since zas doesn't affect them

2017-06-01 08:04 UTC, TheFriggenSawbones commented
this is dumb

2017-06-01 08:07 UTC, Zennyization commented
This is a really poor idea. I personally dont see an issue with how borgs currently are, they can be disabled and killed/shut-down really easily. They're meant to be played differently to humans, just making them able to get tipped over is silly. It is even more silly that you thought having their cover pop open was a balanced idea.

2017-06-01 09:05 UTC, troots commented
damn i thought i could finally appreciate service borgs' work with tips but instead it's a meme

2017-06-01 09:18 UTC, Shadowmech88 commented
I would be less opposed to this if there was already *any* other way to knock over a borg.
They remain standing even while dead, or up against strong airflow, how does it make sense for a human to be able to just push them down?

2017-06-01 09:22 UTC, jknpj commented
does it unequip their modules?

2017-06-01 09:53 UTC, mtpowell commented
Now you can only tip them over if they're flashed or dead and it unequips their modules

2017-06-01 10:12 UTC, Shadowmech88 commented
It should be noted that a borg having its cover pop open, especially while stunned, in combat is an instant death sentence since the carbon can simply take their battery out and render them helpless.

2017-06-01 10:13 UTC, ghost requested changes
interesting way of approaching balancing borgs. A few changes to meet standards, and you want to avoid using sleeps wherever possible

2017-06-01 10:13 UTC, Skullyton commented on code/game/objects/items/devices/flash.dm
> +			sleep(length*10)
avoid sleeps, use spawn([amount of time]) instead then tab everything you want to happen after the amount of time. Then, check if the same still applies (in this case, check if flashed is still equal to 1)

Sleeps tend to mess with just about everything

2017-06-01 10:13 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +			sleep(50)
same for here. Spawn it off, check if everything is still the same

2017-06-01 10:13 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +		visible_message("<span class='danger'>[disarmer] has tipped over [src]!</span>")
\The [disarmer] has tipped over \the [src]!

2017-06-01 10:13 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +		visible_message("<span class='danger'>[disarmer] has attempted to tip over [src]!</span>")
\The [disarmer] has attempted to tip over \the [src]

2017-06-01 10:13 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +			visible_message("<span class='danger'>[src]\'s cover flies open!</span>")
\The [src]\'s cover flies open!

2017-06-01 10:19 UTC, mtpowell commented on code/game/objects/items/devices/flash.dm
> +			sleep(length*10)
is spawn in tenths of seconds?

2017-06-01 10:33 UTC, Skullyton commented on code/game/objects/items/devices/flash.dm
> +			sleep(length*10)
yes, you could also do [number of seconds] SECONDS if you want to make it more readable

2017-06-01 10:59 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +	lying = 0
other way, other way

2017-06-01 11:00 UTC, Skullyton commented on code/game/objects/items/devices/flash.dm
> +			spawn(length*10)
SECONDS is basically value*10, so length SECONDS would improve readability

2017-06-01 11:01 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +	return
this return's redundant, as it'd've reached the end of the process and auto returned just after this line

2017-06-01 11:29 UTC, Kurfursten commented
I don't know if this is the solution to it, but Borgs really do have an insane amount of stun immunities. ZAS, shoves, water, lube, chemicals, tasers, eguns, bananas/any slippery food, clown PDAs, soap, knockdown from head damage, tabling, window-throwing, nettle-stun, stun gloves, stun prods, stun batons. That's on top of their immunity to toxins, suffocation, higher resistance to brute and burn, immunity to temperatures, radiation, pressure high and low, viruses...

People always defend this by saying "But there's a robotics console". Isn't that kind of unfun gameplay? Wouldn't it be better to have options for the whole crew to take down borgs (instead of just people with flashes) and no robotics console (or perhaps an announced delay so they can rush to the console and try to stop it) so the borg actually has some counterplay in the seconds before they die?

The great thing about SS13 is that no matter your department, you always have *something* that gives you a fighting chance against the person attacking you - even a lowly botanist. Unless that person is a cyborg. That's why the best traitoring is done in deadpop with no silicons, and why most daytime traitoring involves subverting the borgs first to do your work for you.

2017-06-01 11:34 UTC, Shadowmech88 commented
We could add in more no-access makeshift borg stunning tools like the blinder.

2017-06-01 11:36 UTC, mtpowell commented
@Kurfursten I agree but knocking over borgs doesn't make sense, as much as I'd want it in the game. And any good MILF/Subverted borgs space the console/extra board asap.

2017-06-01 11:38 UTC, SonixApache commented
How's it work and how long's it last?

2017-06-01 11:48 UTC, jknpj commented
http://www.youtube.com/watch?v=wUQMvlH39XA

2017-06-01 11:50 UTC, mtpowell commented
@SonixApache 
If a borg is flashed or dead(for fun), you can disarm push them over and it adds 5 seconds onto their flashed knockdown time, and a VERY small chance at popping open their covers when they get knocked over.

2017-06-01 11:52 UTC, jknpj commented
needs a way to help borgs getting up too

2017-06-01 11:57 UTC, SonixApache commented
neat

2017-06-01 12:33 UTC, Fruktlimpa commented
>locked cover being popped open from falling

This is silly, very silly.

2017-06-01 12:34 UTC, SonixApache commented
@Fruktlimpa you ever see one of those safes being dropped from a building to open them? Basically the same thing.

2017-06-01 12:43 UTC, Riekland commented
I would say make the chance of the cover popping open only happen if they're unlocked
Keep them powerful but have a chance if they start shooting you mid hack or something

2017-06-01 12:49 UTC, Fruktlimpa commented
@SonixApache We are talking tipping here, not dropping them off station into atmospheric re-entry. Nanotrasen sure as fucked skimped the budget on borgs if a mere tip can cause their cover to open from that tiny impact.

2017-06-01 12:53 UTC, SonixApache commented
@Fruktlimpa I like to think borgs are as tall as and weigh as much as vans.
And yes, nanotrasen skimped on the lock budget pretty hard if you consider that an ID card with some jury-rigged wires and batteries can force it open.

2017-06-01 13:16 UTC, Riekland commented
>Nanotrasen sure as fucked skimped the budget on [anything]

isn't that the whole lore

2017-06-01 13:49 UTC, Commandersand commented
HE HAS CHALLENGED THE SILICON METACLUB

2017-06-01 13:54 UTC, Unknown-as-Captain commented
wtf do you mean an object with a low center of gravity can be tipped over but its like made of metal???

2017-06-01 13:57 UTC, jknpj commented
Stunning a borg overloads their sensors, fucking up their stabilization. I didn't like it at first but it's reasonable.

2017-06-01 14:10 UTC, ghost approved these changes

2017-06-01 14:13 UTC, Skullyton commented on code/game/objects/items/devices/flash.dm
> +	else if(istype(M, /mob/living/silicon))
issilicon is basically this check, why the change?

#define issilicon(A) istype(A, /mob/living/silicon)

2017-06-01 14:31 UTC, mtpowell commented on code/game/objects/items/devices/flash.dm
> +	else if(istype(M, /mob/living/silicon))
Because the M is an object of 'living' and I needed access to the length var I added to silicon

2017-06-01 14:57 UTC, adu6oo commented
this is good now

2017-06-01 15:17 UTC, Skullyton commented on code/game/objects/items/devices/flash.dm
> +	else if(istype(M, /mob/living/silicon))
well, change it back, we've got those helpers for a reason, in case the definition of silicon is changed

2017-06-01 18:21 UTC, moistnuggie commented
i like and support this, borgs are pretty stronk so its good for them to atleast have another weakness that mostly anybody can take advantage of

i dont understand the "It's a big heavy robot you shouldn't be able to knock em over" we are still able to pull these things with us, aswell as move them, i imagine them being as heavy as a vending machine and those are pretty easy to tip over

idk i like this, people have to be more open to change

2017-06-01 18:37 UTC, AutismSpider commented
@Kammerjunk >stun batons dont work on borgs

but thats wrong can stun borgs with them if  the baton is set to stun same with the prod any one can make all the other stuff is true.

2017-06-01 18:50 UTC, SonixApache commented
@AutismSpider I just beat myself to death with a stun baton as peacekeeper borg, not sure if you're right.

2017-06-01 18:59 UTC, Talvan commented
All you need to do is flash a borg and it's dead. Why add some dumb borg tipping meme?

2017-06-01 19:43 UTC, IzayaChan commented
Borgs deserved to get fucked like this
FUCK BORGS

2017-06-01 22:32 UTC, CptWad commented
@Talvan 
borg flashing is a chore. Having to spam a flash on a borg (with a chance that the flash suddenly stops working) while switching hands to beat the shit out of a borg is honestly the worst thing next to killing an unrobust full power vamp thats spamming abilities to get away
As someone who has beaten the shit out of a lot of borgs, this is honestly a breath of fresh air

2017-06-01 22:34 UTC, Talvan commented
@CptWad You don't have to spam flash a borg though? Just one flash, press X beat the shit out of it, press X again, flash. It's that easy. If you think stunning a borg is hard, I don't believe you've robusted many borgs.

2017-06-01 22:35 UTC, Kurfursten commented
@IzayaChan I mean, it's not really a fucking. Just making flashes better against borgs isn't that big a deal. Now if there was a new way to stun them, that would be something.

2017-06-01 22:47 UTC, CptWad commented
\>flash borg
\>attack 4x
\>flash
\>attack 4x
\>flash
\>attack 4x
\>etc
its pretty tedious

2017-06-01 22:48 UTC, Talvan commented
Except you don't even need to hit it that many times to actually disable it?

2017-06-01 22:49 UTC, CptWad commented
what do you think everyone has an esword on hand? Usually melee fights against borgs are with stun batons or tools since you cant use shit like an axe and soforth

2017-06-01 22:52 UTC, Talvan commented
You don't need to chew through all 300 hitpoints of a borg. Just disabling its actuator, camera, or battery is enough. Breaking these modules will make a borg effectively useless AND they're easy to damage.

2017-06-01 22:59 UTC, CptWad commented
You don't get to choose which part of a borgs modules you damage though, its up to chance.
Though being lucky enough to tag one is great
generally you DO have to chew through some of the health because half of it is its armor module

2017-06-01 23:01 UTC, Talvan commented
I dunno, one of those three parts tends to go before the borg itself dies.

2017-06-01 23:20 UTC, SonixApache commented
@CptWad did you know toolboxes do 15 brute per hit

2017-06-01 23:31 UTC, Kurfursten commented
You're saying he's underestimating right? He only said attack 12 times, 300 health requires 20 hits at 15 damage each.

2017-06-01 23:35 UTC, Talvan commented
Did you not read the whole argument or what? You only need to disable one of the three critical modules of a borg. One of the three always goes before the borg dies. Even then, you're assuming you're the only person fighting the borg. One of you must have a gun, right?

2017-06-01 23:42 UTC, Kurfursten commented
What I don't get is why the conversation even goes this direction. As a carbon, you're a glass of water and a cablecoil from being taken out of the round - slip and cuff.

The expectation for dealing with a silicon, you're telling me, is "have a flash and a gun"? This is why people (rightly) identify silicons as the most entitled players.

2017-06-01 23:43 UTC, Talvan commented
They're entitled because they have to listen to every retard's orders? They're entitled because they're often outnumbered 2 to 20?

2017-06-01 23:50 UTC, Kurfursten commented
No, because their players are the whiniest. Any other antag is outnumbered 1 to 60.

But really I'll refer you to above. The problem with borgs isn't when they're antagonists, it's much worse when they're not They stifle the round because they are SUCH an obstacle to deal with, they are the ultimate validhunting tools: unlimited access and a laundry list of immunities, *every antagonist* needs to have a plan to deal with the silicons before they do something creative. I've never seen a truly great antag gimmick during daylight hours, it's only at night - my usual hours to play - when the silicons aren't playing.

2017-06-01 23:50 UTC, Talvan commented
So you don't play with silicons yet you know how bad silicons are?

2017-06-01 23:51 UTC, SonixApache commented
*three hundred health*

2017-06-01 23:52 UTC, Talvan commented
But let's stick to the point here, every non-antagonist borg can be blown with the push of a button. Even if you don't choose to blow up a cyborg, you can simply avoid them like you would avoid anyone else.

2017-06-02 01:54 UTC, Kurfursten commented
C'mon Talvan, for someone who said "Did you not read the whole argument or what?", scroll up! You're so predictable that your only talking point was highlighted in my first post.

2017-06-02 02:10 UTC, Blithering commented
Can borgs that have been tipped over get up? Its not very clear.

2017-06-02 02:11 UTC, Talvan commented
They should get up on their own, yeah.

2017-06-02 10:45 UTC, mtpowell commented
@Blithering 
`to_chat(src, "<span class='notice'>Starting self-righting mechanism.</span>")`

2017-06-02 14:25 UTC, Skullyton commented
As the tag says, add a changelog (Inline'll do, should be explained in the commented out section in the header) and if it's finished we'll test merge it

2017-06-02 14:36 UTC, Unknown-as-Captain commented
@Talvan it takes a good 150-200 brute on average to damage any relevant components. 12 attacks is perfectly reasonable for a 15 force weapon.
Eff off

2017-06-02 14:44 UTC, SonixApache commented
*ten second stuns*
*remote killswitch*
*muh 300 health*

2017-06-02 15:08 UTC, mtpowell commented
@Skullyton 
Done

2017-06-02 15:22 UTC, Skullyton commented
Let's see how this goes

2017-06-02 15:22 UTC, merged

2017-06-02 22:27 UTC, Talvan commented
Where is this on the changelog?

2017-06-02 22:30 UTC, Exxion commented
Should be there

2017-06-02 22:44 UTC, SonixApache commented
there was an issue with @PJBot not properly pushing the inline changelogs, but that shoulda been fixed