Adds self-diagnosis messages for various borg interactions
d3athrow/vgstation13 pull request #15117
Opened 2017-06-02 15:42 UTC by SonixApache

![image](https://cloud.githubusercontent.com/assets/8468269/26733307/bb5d336e-47ba-11e7-8062-13089c6eaf67.png)

🆑 
 - rscadd: Borgs now get some messages regarding what's happening to their body and components, as long as their self-diagnosis unit is working.

2017-06-02 15:55 UTC, HarseTheef commented
Very nice, quality of life!

2017-06-02 16:43 UTC, SkowronX commented
Coders should focus more on things like this

2017-06-02 18:54 UTC, SonixApache commented
Some changes: Added a helper proc, added messages for when components are destroyed, fixed up the message saying which broken component is removed.
Should be good to go.

2017-06-02 19:30 UTC, ghost requested changes
remove src.

2017-06-02 19:30 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot.dm
> +				if(src.can_diagnose())
Sweet jesus why are you using src.?

2017-06-02 20:03 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot.dm
> +				if(src.can_diagnose())
i have no idea

2017-06-02 20:14 UTC, ghost approved these changes

2017-06-02 21:56 UTC, Exxion commented on code/modules/mob/living/silicon/robot/robot.dm
> +				if(src.can_diagnose())
It completely doesn't matter at all. I still don't know why people got so upset about it for a few days.

2017-06-03 04:20 UTC, JustSumBody commented on code/modules/mob/living/silicon/robot/robot.dm
> +				if(src.can_diagnose())
NONSTANDARD FORMATTING CHANGE AAAAAAAAAAAAAAAA

2017-06-04 15:00 UTC, merged

2017-06-04 15:32 UTC, SonixApache commented
neat