Adds voucher-only vending items + example + vendomat messages
d3athrow/vgstation13 pull request #15152
Opened 2017-06-05 16:16 UTC by SonixApache

Adds a new framework for voucher-only vending machine items.
Also adds a glowing voucher that can be redeemed at vendomats for glowsticks, as an example.

Also adds and changes some messages regarding broken vendomats, to help the user figure out why it isn't working. Not very atomic, but I was in the file anyway.

:cl:
 - rscadd: Added a framework for voucher-only vending machine items.
 - tweak: Added some feedback messages for broken vending machines

2017-06-05 16:23 UTC, SonixApache commented on code/game/machinery/vending.dm
> +	prices = list( //Just for the glowing vouchers. Maybe should add a 'vouched' section to vendomats?
Wait, I DID add a 'vouched' section to vendomats.

2017-06-05 21:10 UTC, Blithering commented
Vouchers are cool, it would be nice to have more ways to obtain them though, like Dr. Acula rewards or arcade prizes.

2017-06-05 21:17 UTC, SkowronX commented
Buy them with pomf coins

2017-06-05 21:28 UTC, Blithering commented
Voucher for icecream dispensers to give pomf brand icecream?

2017-06-05 22:19 UTC, EmiliaMcWaifushitter commented
GLOWING vouchers!

2017-06-08 04:25 UTC, Intigracy commented
We could add continuity between rounds via rewarding successful antags with vouchers the next round they play.

2017-06-08 04:27 UTC, Intigracy requested changes

2017-06-08 04:27 UTC, Intigracy commented on code/game/machinery/vending.dm
> +			to_chat(user, "<span class='notice'>The glass in the [src] is broken! Fix it first.</span>")
\the

2017-06-08 04:27 UTC, Intigracy commented on code/game/machinery/vending.dm
> +		to_chat(user, "<span class='notice'>The glass in the [src] is broken, it refuses to work.</span>")
\the

2017-06-08 04:27 UTC, Intigracy commented on code/game/machinery/vending.dm
> +		to_chat(user, "<span class='notice'>The [src] is dark and unresponsive.</span>")
\the

2017-06-08 04:28 UTC, Intigracy commented on code/game/machinery/vending.dm
> +		to_chat(user, "<span class='notice'>The [src] is dark and unresponsive.</span>")
\The*

2017-06-08 13:34 UTC, SonixApache commented
![spongebob_the](https://user-images.githubusercontent.com/8468269/26931185-eb99ba80-4c5f-11e7-93af-3f2c21ad9bc8.jpg)

2017-06-08 22:03 UTC, SonixApache commented
![image](https://user-images.githubusercontent.com/8468269/26952731-ff983588-4ca6-11e7-9494-bda48f079441.png)
seems aight now

2017-06-08 22:05 UTC, Exxion commented
You don't need `\improper` before already-lowercase names
Also...

2017-06-08 22:06 UTC, Exxion commented on code/game/machinery/vending.dm
> +	name = "\improper "
honk

2017-06-08 22:06 UTC, SonixApache commented on code/game/machinery/vending.dm
> +	name = "\improper "
I KNOW ;_;

2017-06-08 22:08 UTC, SonixApache commented
yeah aight fixed that too

2017-06-08 22:43 UTC, Intigracy commented
Add the voucher to the arcade maybe?

If more get added we can just make it a box like the other prizes.

2017-06-08 23:19 UTC, SonixApache commented
There's only two (sets of) glowsticks per Vendomat, and only one or rarely two vendomats per map. If you manage to win more than two it becomes a wasted prize.

And honestly,the GLOWING voucher should be something you get from admins.

2017-06-09 00:04 UTC, merged