Zth  newvendingmachines
d3athrow/vgstation13 pull request #15339
Opened 2017-07-04 23:13 UTC by d3athrow

Custom vending machines, fixed the issue with setting the original account number.

2017-07-04 23:36 UTC, Commandersand commented
Cool

2017-07-04 23:38 UTC, Knightkiller11 commented
Jesus whats with all the commits? Half of them don't seem related to custom vending machines at all.

2017-07-04 23:53 UTC, SonixApache commented
dem commits tho

2017-07-04 23:54 UTC, SkowronX commented
wew

2017-07-05 01:34 UTC, d3athrow commented
Yeah I know gonna fix it when I have a chance

2017-07-05 05:03 UTC, d3athrow commented
K nice n clean

2017-07-05 21:25 UTC, gbasood commented
Needs an actual descriptive changelog

2017-07-10 04:20 UTC, N3X15 requested changes
Add the adjacency checks and you should be golden.

2017-07-10 04:20 UTC, N3X15 commented on code/game/machinery/machinery.dm
> +	if(!user.Adjacent(src))
Should check adjacency prior to input(), as well.

2017-07-10 04:20 UTC, N3X15 commented on code/game/machinery/vending.dm
> +			for(var/datum/money_account/D in all_money_accounts)
Adjacency check before and after input().

2017-07-10 04:20 UTC, N3X15 commented on code/game/machinery/vending.dm
> +				var/account_try = input(user,"Please enter the already connected account number","Security measure") as num
Adjacency check before and after input().

2017-07-10 04:20 UTC, N3X15 commented on code/game/objects/items/stacks/stack_recipes.dm
> +	new/datum/stack_recipe("box",							/obj/item/weapon/storage/box							),
Hard tabs are cancer, if you align stuff, use spaces.

2017-07-10 05:57 UTC, N3X15 approved these changes

2017-07-10 05:58 UTC, merged

2017-07-14 17:53 UTC, Zth-- commented
cool