Grippers [WIP] [DNM]
d3athrow/vgstation13 pull request #15338
Opened 2017-07-04 15:02 UTC by jknpj

Ports Grippers from bay. They are items that are supposed to emulate a hand for when you need to put something into something else (like components into a machine frame), but limited to a whitelist of items related to the work area the cyborg module is associated with (sometimes not even those), like circuit boards and components for Engineering, food items for Service etc. They take one item and can be dropped with an action button. Any action that would unequip modules(dead battery, tipping, module reset, etc) or death forces the gripper to drop the item.

This PR don't actually add them to cyborgs and there's still a lot to test and hardcoded shit to remove if i want them to work properly.

Bellow a list with all current grippers and what they can hold:

* **Magnetic Gripper**: Can hold circuit boards, stock parts, camera assemblies, tanks and cells.
* **Chemistry Gripper**: Can hold pills, glass containers and pill bottles.
* **Organ Gripper**:  Can hold any organ(head, arm, eyes, etc) organic or robotic.
* **Service Gripper**: Can hold glass containers, food, seeds, plant bags and fedoras.
* **Paperwork Gripper**: Can hold clipboards, paper, photos, folders, ids, books and newspapers.
* **Sheet Inserter**: Can hold and insert sheets. Can't use them.

Know issues: 
* **Powergaming the vox's skipjack like there's no tomorrow**: As a feature, holding an item that have action buttons enable them to the gripper's user, but that kinda makes engiborgs able to use jetpacks roundstart by gripping them,since jetpacks are tanks.
* **Can you emag me?**: Paperwork grippers can hold ids, emags are ids.
* **Hardcoded silicon checks**: A lot of machinery(mostly service) will simply refuse to interface with silicons, even if they now have a way to do so,.
* **Magic numbers**: My bad.
* **Jakmak's/Yclat mental health**: They're gonna freak.
* **Balance**: I... still know know a good way to actually add them. Upgrades? Roundstart? Removing the shitcode silicon beaker was my primary reason to port this but i think the other grippers like the organ one are not fundamental enough to have at roundstart.

So i've been shilling this over a long time and after procrastinating for so long i've finally decided to get some feedback and force myself to either finish or buy this forever. Images/WEBM later.

2017-07-04 15:25 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/inventory.dm
> +/mob/living/silicon/robot/proc/activate_module(var/obj/item/I)
But why?

2017-07-04 15:26 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +		return 0
Double tab?

2017-07-04 15:29 UTC, jknpj commented on code/modules/mob/living/silicon/robot/inventory.dm
> +/mob/living/silicon/robot/proc/activate_module(var/obj/item/I)
I don't actually remember why i did it. Autism with I = Item i guess.

2017-07-04 15:29 UTC, jknpj commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +		return 0
Oversight.

2017-07-04 16:29 UTC, jakmak6 commented
i honestly attempted to code something like this to go along with a ENG borg RPED robotics upgrade but i couldnt get it to function right so i scrapped it. Provided the list of stuff they can hold is small (no guns or weapons) and is kept primary for utility to facilitate autism projects and make mediborgs better medbay staff i actually support this

2017-07-04 16:36 UTC, Theophrastus1 commented
Good work my man, this is great to make borgs more than just mobile law 2 machines outside of sec and medbay. Might actually see some more service borgs that don't just fucking dump dice and money and lighters all over

2017-07-04 17:00 UTC, Blithering commented
What module would get the paperwork gripper?

2017-07-04 17:02 UTC, Theophrastus1 commented
@Blithering I'd imagine Service.

2017-07-04 17:02 UTC, Knightkiller11 commented
Standard, maybe? Potentially Supply as well, given the use of the supply console

2017-07-04 17:40 UTC, Supermichael777 commented
consider adding a blacklist

`blacklist = list(stuff)`

and then in the pickup check

```
if(I and blacklist.find(I, 1, blacklist.len))
 tochat(this item is incompatible!)
```

2017-07-04 17:54 UTC, AI-is-rogue commented
Can you alt click with the grippers to hand things to others?

2017-07-04 18:59 UTC, Unknown-as-Captain commented
beep beep silicreep

2017-07-04 19:40 UTC, SonixApache commented
Paperwork gripper seems like it wouldn't fit any module. Could be added by bus for captain / HoP borgs.

2017-07-04 19:55 UTC, Ephx1 commented
Just to let you know, if you add this, medical cyborgs are 100% better than their human counterparts.

2017-07-04 20:03 UTC, jknpj commented
@AI-is-rogue no because give code is carbon only but it's not hard to add it, i'll see what i can do.

@ephx1 bay solved this by making two modules out of the mediborg module:

![crisis](https://user-images.githubusercontent.com/17928298/27841763-67b5201c-60da-11e7-89a8-10811a46e054.png)
![surgery](https://user-images.githubusercontent.com/17928298/27841764-67b7b110-60da-11e7-89a7-13d78c1623cd.png)

This is why i think we can push the organ gripper behind upgrades, as we already have surgery tool upgrades.

2017-07-04 20:45 UTC, Ephx1 commented
All of them behind upgrades.
Very expensive upgrades.

2017-07-04 21:01 UTC, Unknown-as-Captain commented
\>no [balance]

2017-07-04 21:47 UTC, yclatious commented
It all comes tumbling down, tumbling down, tumbling doooown.

Dont be a fool to yourself, if this shit isn't restricted to fuck, you are just making borgs better than humans and while its true that for some modules, a "endgame" human player can be better, it doesn't mean you should make borgs even better by default, they are already in a good spot, making a med borg even fucking better than a normal doc is absolutely heretical and you yourself have admitted that for Bay it went down a slope so fucking slippery its like Megamaw having a handle on the lube bottle before getting his daily dose of Vitamin D from a skeleton, if this goes down and ends up with silicons getting a massive fucking nerf from being too good or permanently ending up as busted as fuck good with nobody having the balls to nerf them since coders love them silishits, its on you.

2017-07-04 22:07 UTC, SonixApache commented
![image](https://user-images.githubusercontent.com/8468269/27843621-f505ccec-6115-11e7-8551-d24956f61308.png)

2017-07-04 22:08 UTC, SonixApache commented
Camera assemblies don't need to be picked up to be used.

2017-07-04 22:09 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +		/obj/item/weapon/camera_assembly,
Camera assemblies don't need to be picked up to be used.

2017-07-04 22:11 UTC, yclatious commented
![sonixsuckssilicondickdaily](https://user-images.githubusercontent.com/22319825/27843647-fa3c896a-610d-11e7-9449-20dd7453caef.jpg)

2017-07-04 23:07 UTC, jknpj commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +		/obj/item/weapon/camera_assembly,
Verily true, call me retard.

2017-07-04 23:38 UTC, SonixApache commented
Definitely think the trauma / surgical module setup for borgs would be a good idea.

2017-07-04 23:52 UTC, strawberrytan commented
Engineering borgs able to build machinery and load plasma tanks into rad collectors?

Please give

2017-07-05 00:17 UTC, Kammerjunk commented
`Your flesh is an insult to the perfection of the digital.`
No but for really why even be a carbon

2017-07-05 00:50 UTC, Rattlederp commented
The silicon slots will be filled every game if this doesn't have heavy restrictions on it as others have said. 

As for splitting up cyborg modules, it does seem like a step in the right direction. HOWEVER, then the other powerful borgs like engineering would probably need to have something similar done to them so that they're not just engineers with ZAS, fire, toxins, suffocation, and slipping immunity.

2017-07-05 01:01 UTC, Blithering commented
Add this as a late game upgrade
Add advanced robot limbs with job specific tool attachments
Line between carbon and silicon blurs
Everyone gets put on keeper lawset
Station becomes a utopia

2017-07-05 02:26 UTC, Talvan commented
@Blithering save that for another pr

2017-07-05 02:54 UTC, SonixApache commented
@Rattlederp "blame the coders"

2017-07-05 03:19 UTC, jakmak6 commented
ylcat is right regarding this being a powercreep the sillicons. If this gets put in then it would probably be time for a long awaited sillicon nerf. And i dont mean a half assed nerf like removing ion damage and increases its stun by 3 seconds or flashing and disarming the borg gives it a one(1) percent chance for its cover to open. Actual nerfs that maybe make the secborg no longer capable of single handedly eliminating an entire ERT/nukeop squad with the 1 hit of doom

2017-07-05 04:20 UTC, Unknown-as-Captain commented
So this is a great "interface" of sorts to add or improve modules, such as the silly large beaker mediborgs get.
That's fine. That should definitely be improved.
However this also touches balance in all sorts of naughty bits and right now nobody has even found a clue on where to START balancing the (((potential))) new uses this gripper dealio gets.

Basically, what I'm saying is, the best course of action here is code the grippers, code them good, but limit them to only what silicons can already do and don't make any balance changes.
THEN everyone can sit and have a not-so-civilized discussion on what else to do with these.

2017-07-05 09:18 UTC, jknpj commented
Another "silicons OP" episode becomes a "secborgs OP" episode.

2017-07-05 11:41 UTC, SarahJohnson489 commented
Like the others said, implement it in an easy to maintain format for the black/whitelist and not actually in the borgs so it doesn't sit in dnm then conflict hell forever. At least then it'll be around for if people want to overhaul spiderbots for a spiderbot ops gimmick or whatever.

The grippers themselves are an extreme case of power creep for the silicons who are already highly resilient roundstart all-access powergay with little reason not to play as one. Closing that already small gap to do-everythingville is a very dangerous game even at the most extreme of emag/illegal equipment modules/uplink or space modified borg exoskeleton only.  I wouldn't hold my breath on them going somewhere.

2017-07-05 11:59 UTC, yclatious commented
Lads, you can go and do a downvote brigade like its some sort of reddit squad all youd like but I think itd be better if you presented some actual arguments as to how this isn't busted as fuck and how it wont create several balance issues and what not instead of just downvoting the opposite opinion someone dared to flash at you, cause as of so far, I dont see this as much more than people who like silicons, since almost all downvoters are borg and AI players players, saying fuck off to the warnings of powercreep by multiple people because they just want a buff.

Its a more popular skeleton nerf and so far, no actual argument has been said in favour of this that assures massive balance shifts wont happen, so excuse this sour puss for actually trying to be unbiased for a few times, id like some arguments and theory crafting in a discussion part of a PR instead of trying to emojicracy shun people who disagree.

2017-07-05 13:01 UTC, jknpj commented
>no actual argument has been said in favour of this that assures massive balance shifts wont happen

Because it's hard to tell at this point, we can only speculate:
* Allowing engiborgs to build machinery is hardly an issue when they can print+crowbar flatpacks
* Allowing engiborgs to upgrade machinery by rebuilding them with better components isn't that bad. Would be a hellish task on most important machines anyways.
* Allowing engiborgs to hold tanks means they can for once set up engines that aren't the TEG without help, both good and bad as this also mean they can blow the AME by themselves and make canister bombs. Without being able to mark new rooms and make APCs/ACCs their **WE BUILD** is still worse than both mommis and humans.
* Chemistry gripper won't be that balance breaking too since we have beaker drinking now and borgs already can make you drink chems by spamming you with their internal beaker
* The organ gripper is great. With them borgs can finally perform important surgeries like limb/head transplants and that's it. But does this invalidates human MDs?
* The service gripper IS literal servicecreep, i'm not trying to kid anyone. They allow **service** cyborgs to work in any part of the **service** department, even hydroponics, in a intuitive way, but it makes some of their modules pretty redundant/undesired.
* Borgs already insert sheets into machinery. This is just a helping hand to supply borgs.
* The paperwork gripper is strange. They are used in bay on their service subtype clerical cyborgs and we don't have those. Besides the ability to change access using the ID console i'm still testing what other issues this can lead to. Unlocking other cyborgs/mommis with a proper ID doesn't work but i've still have to test if they can swipe red code/call ERT and yadda yadda.

One of the design philosophies behind grippers is to remove snowflake items and allow silicons to interact more with the station without relying on their cell-powered magic, hell, the magical duper beakers that service borgs have is the silliest thing ever and just makes drinkmaking a hellish task. One example of this would be if we removed the mat synth from engiborgs but allowed their magnetic grippers to hold the vanilla mat synth and matter cartridges. The balance can swing both ways.

2017-07-05 13:12 UTC, jakmak6 commented
you are right about the majority of your predictions about borgos how borgos would use their new grippers. Engi borgs would become better credit to engineering team but still limited in autism construction due to blueprints but would still be worthwhile for general engineering. 

Mediborg would be better for everyone since they already kinda have a chemistry gripper and being able to do complex surgeries would help people.

Service borg could use some power crepe so no problems there.

Supply borgs are a joke and never used seriously so it shouldnt be noticed

The paperwork gripper may be a bit dangerous if it can hold IDs/EMAGs since these are silicons we are talking about and they WILL be abused massively. Still all the other functions this arm offers are extremely beneficial for the use of borgos since holding paper is relatively harmless.

2017-07-05 14:03 UTC, yclatious commented
Speculation and theorycrafting is just as fine in times where arguments cant be solid and done, thanks for actually doing something instead of downboating.

Regarding your predictions, here is my take on it:

-I personally see the engie borg building thing as a massive boon, a bit too big of a boon, since flatpack production and what not requires some level of cooperation and a mechanic being around, saying its fine for them to now being able to make machines from scratch since they can do it by some more complex and time consuming way is a bad argument for it, you cant use the same argument for a MoMMI getting a RCD and you shouldnt get to use it here too, its kind of slope thinking, we can do x in a harder way so lets make upgrade A to make it much easier to be done, I don't think its that great of a mentality to have. It might also have some really rather bad results when you can law 2 borgs to make you recall consoles and what not but thats just theoretical powergaming being though out.

-Upgrading machinery will likely not be done at all since its mostly mechanics work since science has permanent bunker syndrome. Lazy fuckheads.

-Tank holding is one of the few things I can fully support as engie borgs admittedly did always need them, though I will admit, im going to miss borgs requesting greyshits to come to engie to put some tanks in, I always enjoyed it.

-Apologies if I am just spouting shit but cant borgs remove beakers with the cryo interface? Some antag can just make any borg grab the mix beakers and splash em and then put em back on to nobody's suspicion, giving people beakers filled with whatever chems to random people is probably not a good idea, doesn't sound like the !FUN! kind of antagging though I might just be doing over analytical powergaming predictions.

-It invalidates most surgery need from docs and makes you able to do it perfectly fine and likely to do it better than them till they get incision tools and what not from science. Not bueno in my books unless the borg sub-type thing is made.

-Just about the only other one I fully agree with, they do need love, I cant call it creep there when it was for the most part a actually needed thing, borgs of the service type were the only ones I ever though needed a actual gripper at all to begin with so no issues here.

-Fine enough

-Access changes by borgs is a absolute fucking no no, delet.

2017-07-05 14:15 UTC, Kammerjunk commented
I don't really play like half the departments and rarely have super strong opinions about stuff but here's a few things:
* Flatpacks and circuit boards: Am I missing something on this? I feel like I am. Being able to work with whatever the mechanic has already scanned for flatpacking is a bit different than being able to create any board.
* Medborgs: None of these grippers are currently going into anything and it's just a pure feature. Assume it becomes modular and assume the medborg will be capable of having the chem gripper and the sheet gripper (and organ gripper for head transplants exclusively). You're right that it wouldn't invalidate the MD in much the same way a Robocop secborg with an illegal weapons module wouldn't invalidate an officer, but the medborg here will still be better than the MD in every single way save one. If you get your first cloned patient to stuff the cloner, there is no real splendor of flesh in this burgeoning empire of steel. This is perhaps my biggest warning due to experience in medbay (having learned much of it under medborg Cyrridven and having played medborg a bit myself as well as a bunch of MD).
* Servborg's Magical Mover and Shaker: Spot on. Very snowflakey, very awkward to handle, super strange to even have. Currently your best friend in cult if the chap's MIA/KIA/never arrived due to being able to synth holywater, but that's about its only gameplay use AFAIK.

I don't know how you intend to implement these, but that'd be my notes on it. The biggest warning I can think of is that they shouldn't be allowed to get unlimited grippers. I don't know if I think they should be allowed to get grippers in general (because almost all of them are a pretty big upgrade IMO), but I know I think they shouldn't be allowed to get *all* of them.
That borg nerf doesn't sound so bad post-grippers.

@yclatious Sure, just click the cryo and eject beaker. Examine cryo to see beaker reagent.

2017-07-05 16:44 UTC, Unknown-as-Captain commented
"you can kind of already do this in a roundabout, hard to manage way" doesn't mean "haha fuck yeah let's let borgs use pills same thing right >:)"

2017-07-05 17:29 UTC, jknpj commented
If you really think using your beaker to forcefeed patients is roundabout and hard to manage when compared to pills you clearly never played when they had to use syringes/droppers.

2017-07-05 18:13 UTC, Unknown-as-Captain commented
And what does that have to do? Yes, using syringes/droppers was harder than using a beaker. Yes, using a beaker is STILL harder to manage than popping pills off the fridge.

It's like you're telling me here that wiping your ass with leaves isn't any harder than wiping your ass with Quilted Northern Ultra Plush: 3 Ply Toilet Paper because, god forbid, a long time ago we had to wipe our asses with our hands.

2017-07-05 18:51 UTC, SonixApache commented
#15344
there, nerfed, grippers now viable

2017-07-05 22:06 UTC, FudgePucker commented
I think it would be fine if it was an upgrade and not round start.

2017-07-05 23:16 UTC, Skullyton commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	//TL note: kuro means black. This is a list of items that can't be held even if their parent is whitelisted.
Why the nonsense?

2017-07-05 23:21 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	//TL note: kuro means black. This is a list of items that can't be held even if their parent is whitelisted.
because weeb

2017-07-06 01:36 UTC, clusterfack commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	//TL note: kuro means black. This is a list of items that can't be held even if their parent is whitelisted.
Superior nippon code, compiled 10,000 times

2017-07-06 01:39 UTC, clusterfack commented
I think this is an **extremely** obvious powercreep slippery slope that is being added that people will inevitably start adding more things to. And worst of all it takes away from the distinctiveness of borgs having no hands and just a built in set of modules to do their actions.

2017-07-06 03:27 UTC, AutismSpider commented
>give the cyborg a mommi like hand/claw
>the thing they should never get unless they get massive handicap like the mommis have.

Only the damn Engi/Supplys hould get this others can fuck off.

2017-07-06 03:30 UTC, Unknown-as-Captain commented
It's a pretty nice interface to replace the shitcode pseudo-grippers we already have, like replace the magic buggy silicon beaker with just a beaker gripper. Or random shit like food tray gripper.

Buuuut it will inevitably lead to heyy, look we have a perfectly working beaker gripper why not add a couple more things to its whitelist ;]

2017-07-06 03:39 UTC, SonixApache commented
ah yes, the slippery slope argument

2017-07-06 20:22 UTC, Kurfursten commented
Say what you want about slippery slope but it literally happens here. I've seen people ask for MoMMI RCD and soldering iron modules, which were coded for the purpose of giving human engineers something MoMMIs don't have. Engborg is currently in a really good balance spot, I think. An inability to setup most engines on its own, or finish reconstructing bomb areas (e.g.: APC repair) *encourages* engborgs to cooperate with human staff, rather than replacing them. Meanwhile they have strengths engineers don't have: plasma/temp/rad resistance with no slowdown, energy-based RCD that can throw down plating for days, and the fabled mat synth.

Other departments, like medbay, probably will struggle with this too, but I don't have the same passion that I do for engineering.

2017-07-06 21:13 UTC, SonixApache commented
*what* human staff

2017-07-06 22:03 UTC, Rattlederp commented
Well Sonix has a point there, anyone who's played Chief Engineer knows the engineers, assuming someone actually bothered to sign up for one, don't even cooperate with each other let alone cyborgs. A good big of them just fuck off on their own to do their own autism. Or fuck off with the free glubs. The ones that stick around want usually want to learn how do we engeneir=

2017-07-06 22:04 UTC, Kurfursten commented
If our problem is that people would rather roundstart as an engborg or MoMMI than human engineer *already*, that's symptomatic of poor balance; lack of incentives to play carbon.

Purely as a thought experiment, though, the current round has five human engineering staff (you can count this without entering the game via the join-as prompt which allows you to see active in each role, therefore this isn't in-game knowledge). Whether or not there are MoMMIs or cyborgs at all, I can't speculate because that would be in-game information.

2017-07-09 16:15 UTC, SarahJohnson489 commented
It'd be different if you were able to late join as mommi/eng borg and there were more than 2 slots each. Some people take not having to wrangle sci to get borg/mommi'd as enough of an incentive to just cope with being worse.

2017-07-09 20:05 UTC, FudgePucker commented
I still hold the thought that it should be an upgrade and not round start.

This change will make engiborgs better than MoMMIs. I would rather have a RCD than the ability to make air alarms and APCs. Not mentioning the better mat synth and better HP. Also the lawset makes it more likely for you to be subverted and unleash your autism on the crew.

2017-07-16 17:41 UTC, Skullyton commented on __DEFINES/atoms.dm
> +#define SEMI_TRANSPARENT 128
So, translucent?

2017-07-17 06:56 UTC, Exxion commented on __DEFINES/atoms.dm
> +#define SEMI_TRANSPARENT 128
Not really, since it doesn't scatter the light/blur the image

2017-07-17 18:51 UTC, ghost requested changes
grammar changes

2017-07-17 18:51 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Used to give a service cyborg an service gripper."
give a service cyborg a service gripper

2017-07-17 18:51 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Used to give a engineering cyborg an magnetic gripper."
a magnetic gripper

2017-07-17 18:51 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Used to give a supply cyborg an sheet inserter."
a sheet inserter

2017-07-17 18:51 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Used to give a medical cyborg an chemistry gripper."
a chemistry gripper

2017-07-17 18:52 UTC, Skullyton commented
- When using a chemistry gripper to put a regular beaker into a chemistry machine, it unequips the chemistry gripper and puts it back in your modules
 - When moving away, the regular beaker (The one off the table in chemistry) it is removed from the dispenser as if it were the borg module beaker

2017-07-17 18:57 UTC, ghost requested changes
a few problems showing from testing

2017-07-17 18:57 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/magnetic_gripper
You've got overwriting subtypes, the only one that exists is the sheet insertion gripper upgrade

2017-07-17 18:57 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/magnetic_gripper
You've got overwriting subtypes, the only one that exists is the sheet insertion gripper upgrade

2017-07-17 18:57 UTC, Skullyton commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/magnetic_gripper
You've got overwriting subtypes, the only one that exists is the sheet insertion gripper upgrade

2017-07-17 19:05 UTC, jknpj commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/magnetic_gripper
Thanks ctrl+c

2017-07-17 19:38 UTC, ghost requested changes
needs a way to acquire them in-game. Exofab seems the best place.

2017-07-18 16:13 UTC, jknpj commented
Back to devhell with this one.

2017-07-18 20:12 UTC, FudgePucker commented
I mean if it is not yet obtainable there is no problem with merging it just so that the author doesn't have to keep fixing conflicts.

The real controversy is when and how this is obtainable, right now it would just be an admin spawnable item right?

2017-07-18 20:33 UTC, jknpj commented
I'm fixing a few issues, moving the gripping act to its own proc, as well as porting part of aurora's gripper refactor code to make them a little more robust, i'll get it done soon enough.

2017-07-24 09:56 UTC, closed without merging