leap now casts properly
d3athrow/vgstation13 pull request #15347
Opened 2017-07-05 23:11 UTC by Skullyton

As it depends on a sleep for its fancy animation, it would take some time for cast to finally call take_charge, which would let you stack casts of the jump spell.

Now, everything's handled in after_cast, as cast just had a second argument that was never used anyway.

Also adds some sanity so you're not jumping in space of all places.

Tested, no runtimes that I could see. Couldn't stack-jump or jump into the nth dimension in space.

Fixes #15278
Fixes #13581

2017-07-05 23:23 UTC, SonixApache commented
rip rapid space travel
does this fix the thing where you can cut the cooldown by just spamming the button?

2017-07-06 01:36 UTC, Blithering commented
RIP energy legs

2017-07-06 03:02 UTC, kilozombie commented
I dislike this not because I think it's wrong to fix bugs, but because this bug is really cool.
I'll miss it if this ends up getting merged.

2017-07-06 06:27 UTC, Exxion commented
>if

2017-07-06 06:32 UTC, Fruktlimpa commented
Does this prevent people spamjumping so that they practically leave the screen and all kinds of fucked up shit happens with their sprite and causing lag and all hell? If so, good.

2017-07-06 11:27 UTC, Skullyton commented
Yes. Now each cast only lets you jump once.

2017-07-06 12:39 UTC, SonixApache commented
turbojump ability that undoes this WHEN

2017-07-06 16:18 UTC, FudgePucker commented
Quantum frog boots that let you jump in space when?

2017-07-06 22:44 UTC, Intigracy commented on code/game/dna/genes/goon_powers.dm
> +				to_chat(target, "<span class='warning'>You're in space. No.</span>")
How about something with actual flavor, like "You have nothing to leap off of." with a check for catwalks?

2017-07-06 23:16 UTC, strawberrytan commented
No more leaping through space

RIP

2017-07-07 12:44 UTC, Blithering commented
@FudgePucker seven league boots as a new wizard artifact?

2017-07-09 23:18 UTC, Unknown-as-Captain commented
Boots of blinding speed when?

2017-07-11 15:43 UTC, PJB3005 requested changes

2017-07-11 15:43 UTC, PJB3005 commented on code/game/dna/genes/goon_powers.dm
> +/spell/targeted/leap/after_cast(list/targets)
Just use spawn or waitfor don't change this.

2017-07-12 23:17 UTC, RealestEstate commented
I was actually planning on removing superjumping in space myself, but Skully beat me to, gg. I'll try to make a pr that makes super farts will propel the user in space at crazy velocity in the direction he is facing. don't you guys fret.

2017-07-13 00:49 UTC, gbasood commented on code/game/dna/genes/goon_powers.dm
> +/spell/targeted/leap/after_cast(list/targets)
why not

2017-07-16 02:28 UTC, merged