Gives vox raiders their own radio freq
d3athrow/vgstation13 pull request #15389
Opened 2017-07-11 17:46 UTC by jakmak6

As it stands now vox raiders use the same radios that the nukies use allowing for them to hear station freq. However since vox cant understand galcomm the station freqs just clog up their radios. So i gave the vox their own radio frequency, own radios, own all in one server box (same one nukies have) and inter z level functionality while removing the ability for them to hear station radio frequencies. 

Also be noted i added other stuff to the vox. 3 extra new radios, 3 agent IDs with trader access and trader sprite, and a single station bounced radios so they can negotiate with crew

2017-07-11 17:47 UTC, jakmak6 commented
I will fix bus an ministation at another time until them DNM

2017-07-11 18:03 UTC, SonixApache commented
>vox can't understand humans so i removed their radio
>i also gave vox stuff to help them negotiate with humans
???

2017-07-11 18:39 UTC, DamianX commented on code/game/machinery/telecomms/broadcaster.dm
> +		if(signal.frequency == SYND_FREQ && syndi_allinone == 1) // if syndicate broadcast, just
Why duplicate code? A simple OR should work

2017-07-11 18:46 UTC, DamianX commented on code/game/machinery/telecomms/machine_interactions.dm
> +					if (newfreq != SYND_FREQ || RAID_FREQ)
The logic is flawed, this will always return true

2017-07-11 22:04 UTC, jakmak6 commented on code/game/machinery/telecomms/broadcaster.dm
> +		if(signal.frequency == SYND_FREQ && syndi_allinone == 1) // if syndicate broadcast, just
Not having the check meant the messages would be shared across the 2 channels

2017-07-11 22:06 UTC, jakmak6 commented
Sonix removing hearing station radios means chat would be spammed less with useless gunk and a spare SBR unused allows for slightly easier ransom demands

2017-07-11 22:07 UTC, SonixApache commented
how can you make demands if you can't understand them

2017-07-11 22:10 UTC, DamianX commented on code/game/machinery/telecomms/broadcaster.dm
> +		if(signal.frequency == SYND_FREQ && syndi_allinone == 1) // if syndicate broadcast, just
Lines 158-161 and 164-167 are the same, is what I'm saying

2017-07-11 22:17 UTC, jakmak6 commented
Sonix vox hearing raw galcomm was useless chatspam while vox yelling in birdspeak could be interpreted via silicon/crew vox. Besides the only time vox would need to hear station radios is when making demands/negotiating

2017-07-11 22:20 UTC, SonixApache commented
yes but *if the birds cannot speak galcom through a radio, why give them a radio*
aaaa

2017-07-11 22:59 UTC, jakmak6 commented
Because crew will likely have a translator while birds wouldn't. Besides the SBR was a after thought demanded from the discord. If you want I can remove it

2017-07-11 23:03 UTC, SonixApache commented
I don't really care, I just didn't get it. Makes sense now.

2017-07-12 03:11 UTC, jakmak6 commented
i pissed off github again

2017-07-12 09:33 UTC, Durgen commented
I disagree with the premise that hearing scrambled station comms is not useful to raiders.
Information can be gathered by sudden spikes in the chatter of different departments.
Also sometimes station vox will drop helpful hints in pidgin on the common channel.

2017-07-12 13:00 UTC, jakmak6 commented
durgen while you are right in that a spike in telecomms activity means something is going on having your chatbox filled with useless gargle in green, blue, and red text while you are trying to coordinate with your 5 other team mates who have weird goofy names that are difficult to tell eachother apart just makes communicating in this team based game mode hell. The singular station bounced radio can be used for tapping into station freq if you so please but overall vox hearing station radio is useless except when the vox are attempting negotiations which during that circumstance the crew would have a sillicon/vox translator

2017-07-12 13:20 UTC, jakmak6 commented
ok fixed the map issue ready for merge

2017-07-12 13:37 UTC, ValkyrieSkies commented
Include a universal recorder the Raiders can use for translating during negotiation.

2017-07-12 13:39 UTC, jakmak6 commented
No. Giving them a universal recorder would might as well be giving them gallcom. In the event they would neogiate with crew then the crew would need to figure out translation while the vox wouldnt have to worry about it. Besides translating via universal recorder is a hell of its own

2017-07-12 13:41 UTC, ValkyrieSkies commented
Fair enough, I suppose the crew just needs to have a Vox or silicon crew member to give their response.

2017-07-12 13:49 UTC, Talvan commented
If you're gonna give the birds so much stuff why not nerf their magboots? Remember that their magboots have ZERO (0) downsides.

2017-07-12 14:09 UTC, SonixApache commented
i don't condone adding free shit to the vox just so they can survive after being cloned

2017-07-12 14:11 UTC, jakmak6 commented
i honestly want to remove the cloner, reduce raider teams from 6 to 4, and get rid of vox being able to end the round by going home

2017-07-12 14:59 UTC, jakmak6 commented
and sonix giving the vox spare radios and IDs is apparently to far?

2017-07-12 15:47 UTC, SonixApache commented
yes

2017-07-12 15:50 UTC, Talvan commented
RADIOCREEP

2017-07-12 21:34 UTC, RealestEstate commented
yeah, the raider cloning is a fucking mess. the raiders become capable of speaking galcomm after they get cloned. we were able to utilize this once by making a rezadone farm and using a stolen chem dispenser to reclone our raiders  and powergay the comms. raider only comms will prevent this powergay just a little bit unitl it eventually gets fixxed.

2017-07-20 14:36 UTC, jakmak6 commented
ill fix the map conflicts once wads PR is merged

2017-07-30 19:56 UTC, N3X15 requested changes

2017-07-30 19:56 UTC, N3X15 commented on code/game/machinery/telecomms/machine_interactions.dm
> +					if (newfreq != SYND_FREQ || RAID_FREQ)
Seconded

2017-08-30 21:55 UTC, closed without merging