Space Nazis
d3athrow/vgstation13 pull request #15429
Opened 2017-07-16 16:29 UTC by DeityLink

I'm back bitches

Recycled #10510 ,removed mediguns and other TF2 references.

WEBM: https://www.dropbox.com/s/cpkgxj6223la8mb/dreamseeker%202016-06-12%2005-22-22-09.webm?dl=0

![hitler](https://cloud.githubusercontent.com/assets/7573912/15988848/d1a6dd82-305f-11e6-8efb-9947673d1eec.gif)

:cl:
* rscadd: Space Nazis! They draw their weapons in presence of an enemy. They can run out of ammo and switch from ranged to melee combat. Mecha Hitler is here too.
* rscadd: Nazi Knives, powerful when thrown, can be looted off nazi corpses.
* bugfix: Ranged hostile mobs no longer drop loaded ammo casing when they shoot.

2017-07-16 16:39 UTC, yclatious commented
I know people meme about ss13 having no real consistent graphical design but having a mecha hitler sprite from wolfestein is just pushing it, Im fine with the rest of the stuff but get a spriter to atleast make it look like it slightly fits, it just stands out hard.

2017-07-16 16:41 UTC, DeityLink commented
It's not the exact sprite from wolfenstein 

http://starsmedia.ign.com/stars/image/article/105/1059412/big-boss-of-the-day-wolfenstein-3-ds-mecha-hitler-20100108090106653-000.jpg

I spent an hour back then adapting it to 32x32.

2017-07-16 16:50 UTC, outbools commented
>New mobs
>Not component-based

2017-07-16 16:57 UTC, yclatious commented
It doesn't mesh with anything else around it to start with, maybe its just because of its own nature as a wierd looking "mech" with quad miniguns and the head of adolf hitler, but its color scheme is weird and to my knowledge few items even have those sort of colors so it sticks out like a green-ish cyan box in a mostly clean and white/grey space station, its legs are just odd, they look like two massive pneumatic hammers and don't resemble any other mech legs at all, not even the abstract technological Phazon legs, the quad miniguns just look like they are dangling out, no illusion of depth or anything and they look loosely connected, faithful to the original for sure, but it doesn't fit with everything else we got.

I don't mean to shit on you, its damn impressive you were able to do the sprite but it doesn't resemble anything like the current mechs we have, they stand out hard, the sprite just needs a rework into its own, thing to fit into the station instead of trying to look like a 32x32 version of the original. My advice would be making it just a dual minigun but make em look better and have a ilusion of depth, add in ripley like mech legs instead of the ground pounders, lower the torso a few pixels and make the glass dome slightly larger.

2017-07-16 17:05 UTC, DeityLink commented
Well of course if I planned to add an actual mecha based on the Wolfenstein design I'd put the effort of it looking right but here it's just a mob, who's meant to be a direct reference, and who's so hilariously overpowered that it's probably gonna remain bus-only, or final boss of a vault.

Having look as much as possible like the original was the point. If it doesn't sit well, I'll just remove it.

2017-07-16 17:15 UTC, yclatious commented
Eh, fair enough then.

2017-07-16 22:59 UTC, Riekland commented
MEIN LEBEN

2017-07-16 23:03 UTC, Riekland commented
also why would you make this and not just add the actual wolfenstein blue outfits instead of those ugly as shit greatcoats and stahlhelms
like the space soviet shit is bad enough but every single space nazi sprite is the most edgy piece of shit ever made
at least the soviet ones can be reused since ushankas are just hats and shit but you can't wear a fucking ss uniform without looking like hudson
like I'm genuinely not happy with this because of how it's just edgy space Wehrmacht instead of funny old blue wolfenstein renfrerence haha

2017-07-16 23:43 UTC, DeityLink commented
These are the nazi outfits that are already in the game...

2017-07-17 17:23 UTC, Riekland commented
and they're SHIT
I mean I guess the greatcoats aren't that bad but the hardsuits pass by killzone levels of pretend nazi edgyness and go straight into deviantart

2017-07-17 17:52 UTC, ghost requested changes
some formatting changes

2017-07-17 17:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	name = "Nazi Officer"
Maybe add \improper in front of these capitalized names so it's "the greyshit stabs the Nazi Officer" rather than "the greyshit stabs Nazi Officer"?

2017-07-17 17:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	name = "Nazi Soldier"
\improper

2017-07-17 17:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	name = "Nazi"
\improper

2017-07-17 17:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	name = "Nazi Trooper"
\improper

2017-07-17 17:52 UTC, Skullyton commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	sleep(10)
I feel you're gonna need a set waitfor = 1 at the start of this proc if you're gonna use a sleep, lest we end up with sleepy zombie syndrome again

2017-07-18 17:51 UTC, Blithering commented
The mobs having ammo counts and melee as a backup is great, and would be a nice addition to the existing russian mobs as well as these new ones. The Luger is also neat, that sprite has been unused for too long.

2017-07-18 22:10 UTC, clusterfack commented
Wolfenstein away mission when

2017-07-19 01:20 UTC, DeityLink commented
formating changes done.

2017-07-21 01:24 UTC, Mark9013100 commented
ACHTUNG

2017-07-24 04:21 UTC, NigglyWiggly commented
If you're gonna use the grey nazi suits we already have, the mechahitler blends even less
If you make nice wolfenstein style outfits, then it's cementing it as a straight up wolfenstein thing, but at least it looks consistent within itself

2017-07-24 12:13 UTC, DeityLink commented
@NigglyWiggly I said I'd rather remove the Mecha Hitler. The original idea was to give a nazi counterpart to our russian mobs, but with an AI a bit more elaborate, and then I threw hitler on top for bus/memes.

2017-07-30 20:08 UTC, merged

2017-07-30 22:16 UTC, Blithering commented
Will you be giving the Russian mobs a facelift with the new code?

2017-07-30 23:58 UTC, DeityLink commented
They could use it, but it's not top of my todo list