Fixed a few more mechas issues
d3athrow/vgstation13 pull request #15611
Opened 2017-08-01 17:45 UTC by DeityLink

Fixes #15604 

removed the CANKNOCKDOWN status_flag from borgs since they can't be knocked down anyway. So mechas will no longer infinitely dash into them.
Mecha throws now also check for HULK'd mobs.

2017-08-01 19:33 UTC, Riekland commented
But borgs can be knocked down
If you flash them they can get tipped over

2017-08-01 19:36 UTC, DeityLink commented
Never seen a tipped over borg ever.

2017-08-01 21:29 UTC, Riekland commented
That's because you don't read the changelog

2017-08-01 21:40 UTC, DeityLink commented
What changelog? From when? I've been mostly away for the past year because of studies and stuff.

2017-08-01 21:49 UTC, Riekland commented
the changelog that detailed how borgs can be tipped from the time when that pr was merged
don't complain to me bintch im not here to tell you where to look read through it all its what i did and look ho intelligent it made me

2017-08-03 05:13 UTC, Exxion requested changes

2017-08-03 05:13 UTC, Exxion commented on code/game/mecha/mecha.dm
> +					L.locked_to = 0
`L.locked_to.unlock_atom(L)`

2017-08-03 05:20 UTC, Exxion approved these changes

2017-08-03 16:59 UTC, merged