adds passenger seats to space pods
d3athrow/vgstation13 pull request #15620
Opened 2017-08-02 02:19 UTC by MadmanMartian

Was looking through the WorkInProgress files, and found that spacepods came under this, so I'm going to be poking at them for a bit, assuming I have the permission of pomf.

First up is adding passenger seating to the space pod. It seems odd that something 64x64 would not have room for more than 1 person, especially considering when you can just as easily stack an infinite number of people into a 3x1 escape pod.

Also changed the enter/exit pod verb to the spacepod tab that's used when firing weapons, rather than it being in the objects tab.

Not in a finished state. I think I need to change a few things regarding controls and such first (Such as passengers being able to fire any on-board weaponry).

If you've got any suggestions for other quality of life changes for spacepods, leave them in the comments section and I'll see what I can do.

**Requesting sprites**
- [ ] A taxi-like space pod. Basically a recolor of the current space pod with New York taxi colouring
- [ ] Different pod armor piece for the taxi space pod, so it's acquirable in some way.

**Things to do**
- [ ] Either take the trigger away from passengers entirely, or make it something the pilot can toggle and control (Gunners soon)
- [ ] Add a way for pilots to disallow people from trying to be passengers, maybe even an ejector seat.
- [ ] Add a tie in so that, if the pilot gets out, a passenger can opt in to take control instead.

2017-08-02 03:12 UTC, Kurfursten commented
![untitled](https://user-images.githubusercontent.com/9782036/28856066-74b11a72-7706-11e7-9f3d-7b6591606693.png)

I'm not a real spiter but what do you think?

2017-08-02 03:50 UTC, Exxion commented
Pomf hasn't touched spacepods in...
Well before I started coding here

Please, yes, for the love of god, do whetever the fuck you want to spacepods
Nothing you could do could make them worse than they already are

2017-08-02 09:41 UTC, MadmanMartian commented
@Kurfursten that seems a bit too bright and golden, new york taxis are a bit more towards the red-orange side. At least from what I can see, but I'm a tad toneblind so there's that

![classic taxi](https://s-media-cache-ak0.pinimg.com/originals/ac/5f/b0/ac5fb00cf57c5fdd3d1141b27ec53ff2.jpg)

![modern taxi](http://www.nyc.gov/html/tlc/images/features/fi_industry_yellow_taxi_photo.jpg)

2017-08-02 10:03 UTC, Kurfursten commented
![untitled](https://user-images.githubusercontent.com/9782036/28868689-d65cd372-773f-11e7-863a-81c4dd97ea0a.png)

The original colors were actually taken from a photo of a Taxi

Here's a darker tone though

2017-08-02 13:56 UTC, MadmanMartian commented
Still looks waaay too much like a pimpmobile. Maybe it's the white highlights, giving it too much of a golden look to it

2017-08-02 16:36 UTC, Dacendeth commented
Would it be possible to increase your view distance while riding in a pod? It doesnt have to be anything drastic, and it could be default or an optional attachment you have to build/research and put inside.

2017-08-02 23:36 UTC, Intigracy commented
That second one looks fine.

Also taxis obviously should hold 2/3 passengers instead of 1.

2017-08-02 23:49 UTC, Exxion commented
The antialiasing or whatever on the word "TAXI" on it looks awful though

2017-08-03 01:22 UTC, Kurfursten commented
Grey highlights + 2-color shading on TAXI

![untitled](https://user-images.githubusercontent.com/9782036/28901795-536c7d6a-77c0-11e7-971f-e64a6211a2f3.png)

2017-08-03 12:41 UTC, PJB3005 requested changes
Occupants and passengers should be indistinguishable, except for the first passenger being pilot. No duplicating code to handle both occupant and passenger.

2017-08-03 16:49 UTC, MadmanMartian commented
just found a better way of setting verbs, hang on.

@PJB3005 It's gonna use the alternate proc for assigning the pilot sadly

2017-08-03 17:48 UTC, PJB3005 commented
> @PJB3005 It's gonna use the alternate proc for assigning the pilot sadly

No offense but that just sounds like "I don't want to refactor"

2017-08-04 00:52 UTC, MadmanMartian commented
I'm refactoring to remove the copypaste code in the two entry procs, but I need some way to have a distinct difference between pilots and passengers so I can have things affect each of them differently. 

Would you prefer I just have it so that passengers[1] be considered the pilot? Seems like it'd get a bit odd

2017-08-04 02:03 UTC, Exxion commented
Yeah that would be a bad idea
You could have the pilot also be one of the passengers, though. They enter the pod as a passenger then are designated the pilot.
Similar system could be used for the gunner.

2017-08-04 02:19 UTC, Kurfursten commented
You could use an associative list to define the role of each person inside, which could be useful in the case of setting up pods with different jobs. e.g.: pilot, gunner, passenger, navigator.

2017-08-04 13:32 UTC, MadmanMartian commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
Requesting a second opinion on this. I can't test it by myself

2017-08-04 13:36 UTC, MadmanMartian commented
Alright, that's all the verbs done as far as I'm aware. 

Time to see what I can do about the construction process to allow for alternate pod designs

2017-08-04 13:53 UTC, Kurfursten commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
You can!

Aghost out of your body once inside, then use the secrets panel to spawn yourself as a test dummy and load in as the second passenger. This trick is useful for all kinds of two-person testing you'll do over time.

2017-08-04 14:17 UTC, MadmanMartian commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
Problem is I need to be both the pilot and the passenger at the same time, as to test this I have to eject as the pilot, then see if the prompt pops up for the passenger

2017-08-04 14:19 UTC, PJB3005 commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
Alert menus are pretty terrible, don't do this.

A message and verb or HUD button somewhere to take over is better.

2017-08-04 18:01 UTC, Shadowmech88 commented
>The firefighter ripley and the regular ripley are copypastes of one another largely, so I assume that is acceptable?

Sometimes code is the way it is because it's old and no one's fixed it, not because the way it is is acceptable.

2017-08-05 14:21 UTC, MadmanMartian commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
How abouts do I add verbs only under certain conditions? I tried occupant.verbs += (verb), but that only seems to work for verbs defined under the subtype of the occupant, and not the spacepod.

Verbs seem like quite a mess, hence I want to UI it up a bit

2017-08-05 16:57 UTC, PJB3005 commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
Action buttons.

2017-08-05 17:42 UTC, Exxion commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
Yes, use action buttons
But if you want an example of how to conditionally add verbs, check the spacepod equipment file
I don't remember how it's done but I know it's done in there

2017-08-06 15:19 UTC, MadmanMartian commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					var/answer = alert(L,"The pilot has evacuated \the [src]. Do you wish to take over?",,"Yes","No")
new verb(), nasty stuff

2017-08-07 02:03 UTC, MadmanMartian commented on code/WorkInProgress/pomf/spacepods/spacepods.dm
> +					L.forceMove(T)
Feck, missed one. Gotta use move_passenger_outside for button handling

2017-08-07 02:04 UTC, MadmanMartian commented
- Adds lists for action button handling for space pods
- Attempts to handle the quantum fuckload of references the pod holds when qdel'd, it just didn't seem right for all of those to be there
- Adds the taxi pod, thank you @Kurfursten !

2017-08-07 14:02 UTC, SarahJohnson489 commented
A lot of space explorers wanted a cargo hold of some sort.

2017-08-07 15:37 UTC, MadmanMartian commented
That was what I wanted to do next.

I wanted to just do bits at a time, now I've ended up rewriting half the damn thing

2017-08-10 23:21 UTC, merged

2017-08-10 23:32 UTC, MadmanMartian commented
The absolute madman