Stasis Bags
d3athrow/vgstation13 pull request #15636
Opened 2017-08-05 01:11 UTC by jakmak6

See https://github.com/vgstation-coders/vgstation13/issues/15561

I have resurrected stasis bags/cryobags from our code. These bags are one use bodybags that if you put someone inside of it stops all bleeding/oxyloss/toxin buildup/chem metabolism/ floor dragging harm/ ect.

The bags in turn for being inside them give a slow but steady uptick in brain damage so you cant keep someone in stasis forever.

However there are 2 types of stasis bags. A simple one that does the brain damage and a advanced one that does no brain damage while loosing none of the advantages.

These bags however do not protect from the effect of being in a vacuum and extreme temperatures (super cold or a plasma fire)

Currently no way to get these bags other than adminbus. I will add in some to paramedic locker/protolathe so until then DMN

2017-08-05 01:33 UTC, CptWad commented
jakmak and his clone commit army

2017-08-05 01:34 UTC, CptWad commented
> I will add in some to paramedic locker/protolathe so until then DMN

pls dont use the map, just add it directly to the paramedic closet content

2017-08-05 01:34 UTC, jakmak6 commented
i intend to.

2017-08-05 01:38 UTC, Exxion commented
Comment or something when you want the DNM taken off

2017-08-05 01:45 UTC, jakmak6 commented
ye i will do that

So deciding how to get them. This is what i want. For the standard brain damage bags cargo order locked in paramed access crate, box of 4-5 in parameds locker, A few in vox skipjack, protolathable for 5 sheets iron, 1 sheet glass, 3 sheets plastic, and 5 sheets of plasma with research levels plasma 2, bio 4, material 2, and bluespace 3

Advanced bag is only gettable by protolathe, ERT base, Deathsquad base, nukeop ship (maybe?) Protolathe Material price 5 sheets of iron, 1 sheet of glass, 3 sheets of plastic, 7 sheets of plasma ,2 sheets of gold, 1 sheet of uranium Science level needs to be plasma 4, bio 5, material 3, and blue space 4.

2017-08-05 01:46 UTC, jakmak6 commented
Maybe i could raise the brain damage rate on the shitty bags. .2 per tick is a bit low

2017-08-05 04:14 UTC, CptWad commented
Cool.
Why plastic?

2017-08-05 05:03 UTC, jakmak6 commented
because what else would a body bag be made out of?

2017-08-05 06:16 UTC, CptWad commented
neometallic fiberous material

2017-08-05 15:20 UTC, jakmak6 commented
eh your probably right. ill lower the plastic cost and raise the metal cost

2017-08-06 10:39 UTC, PJB3005 requested changes

2017-08-06 10:39 UTC, PJB3005 commented on code/game/objects/items/bodybag.dm
> +	var/cryobag_reg = 0
Nope. Not happening. Use inheritance properly.

2017-08-06 10:39 UTC, PJB3005 commented on code/game/objects/items/bodybag.dm
> +/*/obj/structure/closet/body_bag/cryobag/MouseDrop(over_object, src_location, over_location)
Remove this.

2017-08-06 10:39 UTC, PJB3005 commented on code/game/objects/items/bodybag.dm
> +/obj/item/bodybag/cryobag/advanced/attack_self(mob/user)
Reorder this so it's below the main item definition.

2017-08-06 10:39 UTC, PJB3005 commented on code/game/objects/items/bodybag.dm
> +		var/obj/item/O = new/obj/item(src.loc)
Using a bare `/item` is a terrible idea. Make a subtype.

2017-08-06 10:39 UTC, PJB3005 commented on code/modules/mob/living/carbon/human/life.dm
> +	var/adv_stasis = 0 //for the adv cryobag
Nope. This shouldn't be tracked on the mob.

2017-08-06 10:39 UTC, PJB3005 commented on code/modules/mob/living/carbon/human/life.dm
> +	adv_stasis = istype(loc, /obj/structure/closet/body_bag/cryobag/advanced) && loc:opened == 0
Nice runtime operator.

2017-08-07 04:22 UTC, outbools commented
Use my implementation please
https://github.com/ParadiseSS13/Paradise/pull/7903

2017-08-14 12:09 UTC, Moonman1946 commented
Being a good paramedic means stabilizing someone before bringing him to medbay, and carrying a roller bed or something so he doesn't lose blood on the way there.
The bag completely deletes the need for both, changing the paramedic into a click&drag bot, might as well hire an assistant, give him bunch of bags and nothing else and tell him to do it.
do it.

2017-08-14 13:38 UTC, Donnager1778 commented
If the person inside can't escape the stasis bag it is a great murder item, push somebody down and very quickly drop them into a stasis bag. You could space the bag and it's hard to stop. You could say the same for the parapen but dragging a regular body is noticeable, somebody dragging a stasis bag probably wouldn't be noticed, and nobody is going to try and open it like they do with lockers/bodybags.

It's a cool idea but I think even the basic one should be locked behind r&d, cost quite a bit in asteroid materials and there shouldn't be any roundstart. Except maybe the vox trader ship has a chance to spawn with a basic one, as something to sell.

2017-08-14 15:05 UTC, jakmak6 commented
Moon you need to remember the average paramedic isn't that smart. The roller bed when deployed sucks to have to work with in compact spaces and this item being locked behind cmo/paramedic access roundstart means that just like the biofoam it will be seldom used. Sure a good doc would go through the effort of procuring them but just like the biofoam most won't use them.

And donnager you can leave the stasis bag ad anytime provided you are not incapacitated or stunned.  The bag does not put you in some form of a permanent stun. It's like being put in a unlocked locker. You can walk away at any time

I don't know now if I want to give some to the paramedic locker now. I will think about it. For now they won't be in the paramedic locker

2017-08-14 17:32 UTC, Donnager1778 commented
I thought the bag froze you up kinda like cryo, if it's just a bag you can leave that's fine then.

I still think it should have to be bought or made in research, not something for free.

2017-08-14 22:52 UTC, jakmak6 commented
Yeah I can see where the confusion would come from with that. I want to add new RnD stuff to make sci med department cooperation less of a shitty meme and more of a decent quality meme but at the same time paramedic could use more goodies to make the job more unique and attractive instead of just going normal doc. It's partially why I went with 2 separate bags. A shitty one for low Matt cost and for roundstart paramedic and cargo and a high quality one that's mineral expensive, no down side and protolathe only. But I am still taking suggestions

2017-08-21 06:58 UTC, outbools commented
Your code doesn't solve problems with stasis bags. They halting only certain effects looping in human Life() while a lot of bleeding/poison/dying processes stored in a mob Life().

Also you're doing same thing oldcoders did with bags. Fucking bag loc check right in the Life() proc. Why do you need this, again? Can't you figure out a better approach for it? Why you need to call istype on current loc each 2 seconds?

My proposals:

- Look at my code i linked above
- Remove loc check from Life() and use define from my code above instead
- Make stasis halt mob Life() so it may save patient from everything but cloneloss and braindamage
- Give bag ability to be lockable by medical ID

2017-10-19 09:30 UTC, Shadowmech88 commented
@jakmak6 do you plan to continue working on this?

2017-10-22 11:55 UTC, PJB3005 commented
Considering this is jakmak and it's been dead for months, I'm closing this. Comment if you want to have it reopened.

2017-10-22 11:55 UTC, closed without merging