ATMs drop contained IDs on destroy
d3athrow/vgstation13 pull request #15672
Opened 2017-08-10 13:52 UTC by MadmanMartian

No more ID nullspacing

closes #14820
closes #15653

2017-08-10 14:40 UTC, PJB3005 requested changes
`Destroy` is for deletion, not generic deconstruction. You should still delete the ID, but not drop it.

If you need to drop the ID on deconstruction put that somewhere else.

2017-08-10 15:50 UTC, MadmanMartian commented
@PJB3005 done

2017-08-10 15:50 UTC, PJB3005 approved these changes

2017-08-10 16:42 UTC, merged

2017-08-11 02:25 UTC, mtpowell commented
Tis a sad day for clowns