24/7 Deathmatch
d3athrow/vgstation13 pull request #16233
Opened 2017-10-13 19:32 UTC by N3X15

Turn /vg/ into what it always wanted to be, a 24/7 highlander server.

2017-10-13 19:39 UTC, DamianX requested changes

2017-10-13 19:39 UTC, DamianX commented on code/controllers/configuration.dm
> +	/*
dead code, remove it

2017-10-13 19:41 UTC, ultraplen commented
![bbc5b63c-17c7-11e7-8929-b083b7a9ddcd](https://user-images.githubusercontent.com/20318196/31563425-491d2ea4-b05f-11e7-97a6-7359ffd399da.png)

idk i dont this pr would be good for the server culture

2017-10-13 19:43 UTC, N3X15 commented
The culture of silent murdergangs roaming the station, hunting for even the slightest hint of fun?

2017-10-13 19:43 UTC, PJB3005 approved these changes
Getting closer to the authentic TG experience every day.

2017-10-13 19:45 UTC, DrSnips commented
Merge when?

2017-10-13 19:46 UTC, ultraplen commented
the murdergangs are very different from just straight up highlander because murdergangs need to rp for a little bit before they lynch someone

2017-10-13 19:50 UTC, N3X15 commented
Since when have they ever RPed to smash someone's face in with a toolbox?

2017-10-13 19:52 UTC, Unknown-as-Captain commented
Needs to play https://www.youtube.com/watch?v=ciPu4DnKBuM in a loop

2017-10-13 19:53 UTC, ultraplen commented
Although its anecdotal, whenever I shuffle down the main hallway, with a crossbow in one hand and a stunprod in the other, I usually have say"HANDS UP RIGHT NOW OR ILL KILL YOU" pretyped so that I can say it before shooting someone.

2017-10-13 20:48 UTC, ihadtoregisterforthis commented
:+1: Finally a step in the right direction

2017-10-13 23:20 UTC, Aurx commented
I'm confused.  
N3X15, why did you write a PR that does nothing at all?

2017-10-14 03:09 UTC, Zennyization commented
What is wrong with you.

2017-10-14 04:26 UTC, Exxion commented on code/controllers/configuration.dm
> -	// their information, but it is the only way (at least that I know of).
Looks like someone didn't know their undocumented BYOND "features" very well

2017-10-14 21:54 UTC, merged

2017-10-14 21:55 UTC, ShiftyRail commented
Holy fuck he did it the absolute madman

2017-10-14 21:56 UTC, aceedex commented
Nice meme lad

2017-10-14 21:58 UTC, DrSnips commented
We did it reddit.

2017-10-14 21:59 UTC, WhiteHusky commented
**_`THE MEMING BEGINS AT FULL FORCE`_**

2017-10-14 22:00 UTC, WhiteHusky commented
The meming has stopped.
#16241

2017-10-15 03:28 UTC, Exxion commented
Holy shit what the fuck