Advanced Security Cameras show cyborgs cameras, just like their non-advanced counterpart.
d3athrow/vgstation13 pull request #16274
Opened 2017-10-19 03:52 UTC by Unknown-as-Captain

Despite Adv Cameras now working some people still used their non-advanced counterpart because it shows cyborgs while the advanced ones don't.
This was surprisingly easy to do, since the HTMLUI was made for the crew monitoring console which does this thing to begin with.

To do some other time: It might get a little hard to spot the cyborg icons when you specifically want to watch cyborgs only, so I could either make the cyborgs another color, or add the text-based menu that never was implemented.

:cl:
 * rscadd: Advanced Security Cameras now show cyborg cameras, just like their non-advanced counterpart.

2017-10-19 18:22 UTC, Kammerjunk commented
1. Enable hotkeys
2. Hold down movement key
3. Hit tab
4. Let go of movement key

The client should now be moving in that direction until you hit the movement key again (either with hotkeys or with the arrow keys)

2017-10-21 01:07 UTC, Shadowmech88 commented
@Unknown-as-Captain 
Have you used the suggested method to test two cyborgs moving at once?
Alternatively, would you like to use the PR test server to test it with multiple people?

2017-10-21 02:13 UTC, Unknown-as-Captain commented
I won't be available to test this until 2 days from now, if it ends up only updating one borg at a time it's a one line change

2017-10-21 16:51 UTC, PJB3005 requested changes

2017-10-21 16:51 UTC, PJB3005 commented on code/modules/html_interface/map/adv_sec/adv_camera.dm
> +		if("Robots" in C.network)
Make this a define like `CAMERA_NETWORK_ROBOTS`.

2017-10-24 03:01 UTC, Unknown-as-Captain commented
Tested multiple cyborgs by creating a sushi belt and spawning 10 borgs in it, works alright.

2017-10-24 15:51 UTC, PJB3005 approved these changes
Nice job fixing all the camera nets while you were at it 👍

2017-10-24 15:51 UTC, merged