HUDs No Longer Track Invisible Mobs
d3athrow/vgstation13 pull request #16276
Opened 2017-10-19 05:06 UTC by Shadowmech88

Specifically mobs made invisible or practically invisible via `alpha` manipulation, such as with a cloaking cloak or invisible spray.
Fixes #14691 

:cl:
 * rscadd: Mobs made invisible or practically invisible via alpha manipulation, such as via a cloaking cloak or invisible spray, can no longer be seen by HUDs.

2017-10-19 05:29 UTC, Kurfursten commented
I thought this was a feature.

Permanently invisible mimes, particularly the ones with invisible backpacks (or wearing an invisible suit for the belt slot) from which to whip out a taser, gotta have *some* counterplay. And if they want to block HUDs they can invisible-spray themselves a tinfoil hat to wear.

2017-10-19 05:36 UTC, Unknown-as-Captain commented
It's a very lame counterplay if a whole department automatically counterplays without even meaning to.

Use c-ray scanners famalam

2017-10-19 05:38 UTC, Durgen commented
https://github.com/vgstation-coders/vgstation13/issues/14691

2017-10-19 05:47 UTC, Shadowmech88 commented
There should be a counterplay, but SecHUDs and MedHUDs are not the right ones. They're too plentiful, are available by default, and in Security's case are found on every member of a team which exists to thwart you.
It really hurts the effectiveness of invisibility items.

Currently AIs are capable of tracking invisible individuals. I was planning on fixing that, but I could leave it in if you think it'd be a good weakness for invisibility items to have.

2017-10-19 07:04 UTC, clusterfack commented
Why the fuck did you decide to use GOTOs? Lol

2017-10-19 07:59 UTC, HarseTheef commented
p-ray scanners are the counter play.  They are incredibly effective and silly easy to mass produce.

2017-10-19 09:45 UTC, Kurfursten commented
Interesting, so T-ray (and P-ray) scanners work as well?

I guess that's good enough

2017-10-19 09:46 UTC, Shadowmech88 commented
Should I make AI unable to track invisible mobs, then?

2017-10-19 12:54 UTC, Emilc4h commented
You could just presume they use visual sensors instead of bio sensors to track people and go ahead with it.  Pretty easy for an AI to bolt someone invisible in (or just doorshock them if they're not Asimov).

2017-10-20 08:57 UTC, Dacendeth commented
Cloak of cloaking already hid you from huds I thought?

2017-10-21 00:44 UTC, Shadowmech88 commented
* Invisible mobs can no longer be tracked by AI cameras.

2017-10-21 16:25 UTC, PJB3005 requested changes

2017-10-21 16:25 UTC, PJB3005 commented on code/game/data_huds.dm
> +proc/check_HUD_visibility(var/mob/living/carbon/human/target, var/mob/user)
Code's duplicated for the AI.

2017-10-21 18:02 UTC, PJB3005 approved these changes

2017-10-21 18:08 UTC, merged