Adamantine Golem Respawn Time
d3athrow/vgstation13 pull request #16271
Opened 2017-10-18 07:45 UTC by Shadowmech88

When a player dies as an adamantine golem, they must now wait 10 minutes before they can spawn again using an adamantine golem rune.
Golems are still replenishable, but hopefully no longer an endless stream of powerful combatants who respawn as soon as they die, a la manifested ghosts.

The time limit has been made a define so that it can easily be changed.

:cl:
 * tweak: When a player dies as an adamantine golem, they must now wait 10 minutes before they can spawn again using an adamantine golem rune.

2017-10-18 13:27 UTC, Unknown-as-Captain commented
What if I simply ghost when I know I'm about to die?

2017-10-19 04:35 UTC, Shadowmech88 commented
* The code now checks for the golem's `mind`'s `key`, which does not change when the player inside the golem ghosts.

2017-10-21 16:55 UTC, PJB3005 requested changes

2017-10-21 16:55 UTC, PJB3005 commented on code/modules/mob/living/carbon/species.dm
> +		spawn(GOLEM_RESPAWN_TIME)
Don't use spawn for this. Better would be to store the `world.time` they died in the list too, then see if `world.time > death_time + GOLEM_RESPAWN_TIME`

2017-10-21 20:20 UTC, PJB3005 approved these changes

2017-10-21 20:20 UTC, merged