Wizard Spell: Doppelganger
d3athrow/vgstation13 pull request #16280
Opened 2017-10-20 01:38 UTC by Shadowmech88

Adds a new spell, Doppelganger. It costs 10 spell points, half that of a standard spell.
Each use spawns a simple wizard mob with the same name and appearance as the wizard who summoned it. It is hostile to everyone but its summoner. By default it will only melee attack, but can use magic missile if the spell is upgraded.
The doppelgangers do not expire, nor is there a limit on how many the wizard may summon.
The spell has a default cooldown of 30 seconds, which can be decreased to 10 seconds for 20 spell points.

I'm going to wait until #16279 is merged to complete this because .dmi conflicts are not fun.

:cl:
 * rscadd: Added a new spell, Doppelganger. It creates a body double of the wizard that can be used for misdirection or reinforcements. If the spell is upgraded, the doppelganger becomes able to fire magic missiles.

2017-10-20 03:12 UTC, Aurx commented
No limit and magic missile makes me think you'll see wizzymen holing up somewhere and just amassing a giant army of unstunable stun-spamming clones.  Is that intended player behavior?

2017-10-20 03:16 UTC, Shadowmech88 commented
He could amass an army, but he couldn't guide it. The doppelgangers just wander around, they don't follow the wizard.

2017-10-20 15:49 UTC, Cyadox commented
I'd be more concerned with it being like spider mobs, where they amass to the point that only a bomb will kill them. There's no limit to what a wizard could do if he just holed them up in a room like virology, etc.
I'm not saying that's a bad thing. Personally more excuses to legitimately use bombs is fine in my books, but I can see some butthurt over spamming the spell in a closed room.

2017-10-20 15:53 UTC, Hugh-G-Rection commented
Staff of Necromancy already exists and lets you create infinite armies as well, a more dangerous one in my opinion.

2017-10-20 15:59 UTC, Exxion commented
NEW WIZARD STRAT:
1. Steal the hand teleporter
2. Find or build a secret room somewhere people won't find it
3. Sit in there for half an hour spawning these exactly as they go off cooldown
4. Open portal when ready to flood the station

2017-10-20 16:17 UTC, Hugh-G-Rection commented
Exact same thing I've done on the satellite a dozen times, but the issue here is you wouldn't be able to get them into the portal rapidly en-masse because they aren't hostile towards you. Portal doesn't send things that are on/under it on creation, only things that move into the space, OR things that are created on it, which is why the goat trick works just by opening stacked crates, or necromancy on stacked corpses.

2017-10-20 22:09 UTC, Aurx commented
Any idiot can make a conveyor belt.

2017-10-20 23:01 UTC, Lokiamis commented
You could make them target each other if they haven't attacked anyone else in a while, or something to that effect.

2017-10-21 16:17 UTC, PJB3005 requested changes

2017-10-21 16:17 UTC, PJB3005 commented on code/modules/spells/aoe_turf/conjure/doppelganger.dm
> +var/list/doppelgangers
Just initialize this list in the declaration.

2017-10-21 18:31 UTC, PJB3005 approved these changes

2017-10-21 18:59 UTC, Shadowmech88 commented
Git told me I had 15,000 additions and deletions on Bagelstation and wouldn't let me change branches until I committed, and now I don't know how to get rid of them.

2017-10-21 20:19 UTC, PJB3005 commented
Er, do you just want to completely remove bagel from the diff or do you have some changes to the map?

If you want to just remove it, get the version from the main repo and commit that.

2017-10-22 02:52 UTC, Shadowmech88 commented
It wouldn't let me directly download it, I had to save it as a text file and then re-save it as a .dmm with Notepad++.
When I tried re-committing it, it said I had no changes to commit.

I think the issue is something to do with line endings, and it may not be possible for me to save the repo's copy of the map without doing those changes to every single line.

2017-10-22 02:58 UTC, Shadowmech88 commented
Also, now literally every branch I check out says I have changes to bagelstation, and won't let me switch branches until I commit or stash the changes.

2017-10-22 03:36 UTC, SarahJohnson489 commented
Yeah, even if someone tries to swarm meme, just walk away and come back with flamethrowers to hose the place down or just weld it up and burn it out with plasoxy. I don't know the AI exactly but it should have enough of the usual acquisition delay that anyone not asleep at the keyboard should be able to start booking it if they stumble on one.

@Shadowmech88 Can you put an arbitrary global cap at like 40? 50? and have it spit back a feedback message to the caster(s) when they try to make one over the cap? I know the optimizations have helped since spider apocalypses killing the server but why tempt fate.

2017-10-22 03:42 UTC, Exxion commented
That was completely a joke. AIs with no interaction with each other have no problems in numbers that people could feasibly get to by making one mob at a time.

2017-10-22 03:44 UTC, SarahJohnson489 commented
Alrighty then, I just remember the old chug from spider apocalypses and wanted to get ahead of it if say 2-3 wizards took and spammed it from different parts of the station.

2017-10-22 10:02 UTC, Shadowmech88 commented
The PR's fixed, though I still need to get Git sorted out.

2017-10-22 11:53 UTC, merged