Rattle Me Bones
d3athrow/vgstation13 pull request #16296
Opened 2017-10-21 11:29 UTC by Shadowmech88

A spooky vault for the Halloween season.
Adds the Skeleton Den, a new vault in which the objective is to not rattle the skeletons' bones.
![skeleton_den](https://user-images.githubusercontent.com/3991927/31851261-f12440ce-b627-11e7-8fda-2bd9cc5a6c54.png)
Bumping into any of the skeleton models will cause all the skeleton models in that room to become hostile to you. Some of the skeleton models move around the room on predetermined paths, as seen here:
https://puu.sh/y3sNg/a3baaed5ca.webm
(The stuttering at the end is a video error, not in-game.)
In a couple of the rooms there are skeleton mobs which will attack you by default, requiring you to fight them while still avoiding the skeleton models.

This PR also adds new abstract objects called movers, along with subtypes transporters, redirectors, and speed adjuster. While mapping, a transporter can be placed on the same tile as an object or mob in order to cause it to continuously move in the transporter's `dir` when the game begins. If something with a transporter crosses over a redirector, the transporter's `dir` will change to the redirector's `dir`. If something with a transporter crosses over a speed adjuster, the transporter's `step_delay` will change to the speed adjuster's `step_delay`. This allows mappers to create moving hazards that follow simple or complex courses without ever having to touch any code.

:cl:
 * rscadd: Added a new vault, the skeleton den. Don't rattle their bones!
 * rscadd: Added a new system by which mappers may create moving hazards which follow simple or complex courses without needed to touch any code.

2017-10-21 11:31 UTC, Shadowmech88 commented
A couple things I need input on:

* First, would it be *more* or *less* fun if the maze full of things you shouldn't touch, some of which move, was pitch-black and you had to provide your own light source?
Currently the vault is fully-bright inside, but I feel like that does reduce some of the challenge and atmosphere.

* Second, I have no idea what rewards to put in the loot room at the end.

2017-10-21 11:33 UTC, jknpj commented
>Second, I have no idea what rewards to put in the loot room at the end.

fifth dissolve injectors ACK ACK!

2017-10-21 14:17 UTC, SonixApache commented
A gold medal, special gloves (swat/combat/centcomm) and a money bag full of golden coins.

2017-10-21 15:19 UTC, Exxion commented
All walls should be at least two tiles thick to prevent disposal memes

2017-10-21 15:33 UTC, Shadowmech88 commented
I'm just going to make disposal pipe schematics fail when used on super-reinforced walls. I'm tired of people piping through impenetrable barriers.

2017-10-21 15:35 UTC, Exxion commented
That works too.

2017-10-21 16:01 UTC, FudgePucker commented
Wait I thought you could only make disposal pipes on plating, how are people putting them ON walls? I thought the problem was with it putting you on the wall from the next turf over?

2017-10-21 16:04 UTC, Exxion commented
Fuck dude I don't know

2017-10-21 16:11 UTC, PJB3005 requested changes

2017-10-21 16:11 UTC, PJB3005 commented on code/modules/maps/movers.dm
> +	if(host)
Merge these two if statements into 1.

2017-10-21 16:11 UTC, Shadowmech88 commented
Are they being put onto the next tile by a delivery chute, or by an exposed pipe launching them out?

2017-10-21 16:18 UTC, FudgePucker commented
Fun traitor idea: make a SME below cargo in the hidden room next to the mining supplies, reroute disposals to shoot into shard. It produces power for the station by recycling the trash. What do you mean people use disposals as a shortcut across the station?

2017-10-21 17:57 UTC, Blithering commented
Do the skeleton mobs rattle the bones when they bump into them? that might make the maze impossible.

2017-10-21 18:02 UTC, Shadowmech88 commented
Skeletons are not rattled by being bumped by other skeletons.
As for the disposals, can a person exit a disposal pipe through an inlet?

2017-10-21 18:07 UTC, PJB3005 approved these changes

2017-10-21 18:10 UTC, FudgePucker commented
Maybe block it off with shutters like the HoP line ones. Meaning even if you reverse though the disposals you will still be blocked off.

2017-10-21 18:17 UTC, unid15 commented
Amazing!

2017-10-21 18:26 UTC, Shadowmech88 commented
Added [Do Not Merge] because it's still WIP.

2017-10-21 20:49 UTC, Exxion commented
```
/turf/simulated/wall/invulnerable/Entered(atom/mover)
    qdel(mover)
```

2017-10-23 06:50 UTC, Shadowmech88 commented
Nobody has offered their thoughts on the lighting situation yet.

2017-10-23 07:21 UTC, Shadowmech88 commented
Also, I tested it and disposal pipes can't be secured while on a wall tile, meaning walls can't be piped through. I also tried riding through a pipe that terminated at a wall and it just dumped me on the pipe's turf, not the wall's turf. I'm not sure what people are talking about when they mention bypassing walls with disposal pipes.

2017-10-23 10:06 UTC, Kitfox88 commented
Make it pitch black other than your own light sources. Get Tomb of the Giants in this bitch.

2017-10-23 10:14 UTC, Shadowmech88 commented
* The loot room of the skeleton den now contains a pirate outfit, gold metal, pirate lord's armor, pirate lord's hat, optical thermal eyepatch, two energy cutlasses, five dissolve injectors, three gold coins, and a bag containing three hundred gold coins.
* The skeleton den has been made pitch-black. Bring a light source.

2017-10-23 10:14 UTC, Shadowmech88 commented
This is now ready, content-wise.

2017-10-29 17:07 UTC, merged