Meter Broadcasting Fix
d3athrow/vgstation13 pull request #16316
Opened 2017-10-23 11:35 UTC by Shadowmech88

Fixes all pipe meters broadcasting at all times.
Pipe meters now have a `broadcasting` var which can be toggled with a multitool. By default, it's turned off.
Fixes #16315

2017-10-23 17:42 UTC, PJB3005 requested changes
This is completely the backwards and wrong way to solve this issue.

*First* of all this breaks basically every map because meters ARE hooked up to general atmospheric monitors.

So, you'd need to go and edit every map to fix this...

So then why wouldn't you be able to make *frequency* default to zero, and then edit every map?

That just proves that this solution is backwards and makes no sense fundamentally, but *even then* the frequency thing is still the wrong solution.

Instead of making it check if the frequency is 0, just check whether the `id_tag` is falsey. A meter with a null ID can't be received from so there'd be no point to it broadcasting in the first place. Meters that aren't hooked up to anything will have no ID on the map and won't broadcast, *and* you're not breaking anything.

2017-10-23 17:42 UTC, PJB3005 commented on code/game/machinery/machinery.dm
> +	if("toggle_broadcast" in href_list)
This should be a meter-specific override.

2017-10-24 16:05 UTC, Shadowmech88 commented
Fixed.

2017-10-24 16:15 UTC, PJB3005 approved these changes

2017-10-29 17:03 UTC, merged