Adds console screens to the protolathe.
d3athrow/vgstation13 pull request #16510
Opened 2017-11-10 01:27 UTC by DrSnips

Does what it says on the tin. Adds the console screen to the list of basic stock parts the protolathe can make.

2017-11-10 01:33 UTC, clusterfack commented
I don't really think this autolathe specific thing makes much sense to have the protolathe produce

2017-11-10 01:34 UTC, DrSnips commented
The proto is more or less just an advanced autolathe and it has all other stock parts to start as well.

2017-11-10 01:36 UTC, Shadowmech88 requested changes

2017-11-10 01:36 UTC, Shadowmech88 commented on code/modules/research/designs/stock_parts.dm
> +	desc = "Used in the construction of computers and other devices with a interactive console."
"*an* interactive console."

2017-11-10 01:37 UTC, clusterfack commented
I mean not really, those were added from the protolathe to the autolathe to give it some more purpose. Which made sense. 

This however is going the other way, making the protolathe which already produces 95% of the produceable items in the game able to produce more.

2017-11-10 01:40 UTC, Kurfursten commented
I'm with Cluster on this one, the autolathe already took a blow to relevance when console screens were added to tool storage and tech storage with the stock parts in vending machine update.

I imagine if the console screen is put into the protolathe, the compressed matter cartridge is next.

2017-11-10 01:43 UTC, DrSnips commented
Funny you should say that about matter carts since Ive been wanted to add multiple material types of matter carts to the protolathe.

2017-11-10 01:45 UTC, MadmanMartian reviewed
should make it require illegal research

2017-11-10 01:45 UTC, Shadowmech88 commented
Travis seems to have had a hiccup, I'm not sure how to restart the build.

2017-11-10 01:46 UTC, Shadowmech88 approved these changes

2017-11-10 01:47 UTC, DrSnips commented
The autolathe still has it's advantages like having all designs to start as well as them being generally cheaper. To make even a beaker in the proto you need bluespace and material research done a bit as well as three times the materials. Is the beaker bigger? Yes. But two large glass beakers from the auto is still cheaper than the bluespace one from the proto.
Time wise the auto is stronger.

2017-11-10 01:47 UTC, DrSnips commented
Let me commit something and see if that restarts it.

2017-11-10 01:52 UTC, clusterfack commented
>having all designs to start

Which wont really matter if the protolathe starts eating all of its designs

2017-11-10 01:52 UTC, Kurfursten commented
But you made the console screen require materials = 1 and cost trivial amounts of material and time so literally none of that applies. 🤔

2017-11-10 01:53 UTC, ringringllingling commented
well, okay dokey, i guess you did the work, whether it went through or not, so here's your free coke.

2017-11-10 01:56 UTC, DrSnips commented
All the other basic stock parts require the same. It's not like it should get special treatment.

2017-11-10 03:09 UTC, ringringllingling commented
wait, didn't the console screen cost the same to make in the protolathe as the autolathe?  you should shore that up.

2017-11-10 03:19 UTC, Unknown-as-Captain commented
R&D is beyond unsalvageable at this point, trying to draw lines in the sand is pointless.

2017-11-10 03:20 UTC, DrSnips commented
The cost matches the current autolathe cost. Is there something I don't see?

2017-11-10 03:30 UTC, clusterfack commented
>R&D is beyond unsalvageable at this point, trying to draw lines in the sand is pointless.

This is the kind of ideology that corrodes the codebase as a whole

2017-11-10 16:02 UTC, PJB3005 approved these changes

2017-11-10 17:36 UTC, Exxion commented
>It's already bad, so trying to keep it from getting even worse is pointless

2017-11-10 20:10 UTC, Aurx commented
Honestly, the autolathe needs to die.  Or the protolathe, either one.  
There's simply no reason for both to exist, and trying to """balance""" them is silly when they're trying to share a very specific niche that doesn't have enough room.

2017-11-10 20:16 UTC, DrSnips commented
Auto serves the need of immediate and cheap designs with no fuss.
Proto serves the need of complex designs that are higher in cost but also requires a lot more setup. Requiring a console, proto, and if research isnt done you need a DA and have science access to do research.
Like I said before with the beaker example.

2017-11-11 04:11 UTC, gbasood commented
To be honest I don't see the point of keeping both around at all.
The most impact the difference has had on me is playing MoMMI on derelict, and that's about it.

2017-11-11 04:46 UTC, Kurfursten commented
@gbasood @Aurx I don't think taking away Cargo's autolathe or giving Cargo a protolathe to replace said autolathe are good solutions. Cargo having access to an autolathe is so old and ubiquitous that every codebase has it in common.

2017-11-12 04:03 UTC, ringringllingling commented
I don't think there is anything wrong with the autolathe or the protolathe.  They both work fine.  Its just a pain having to use the autolathe to make console screens for the mechanic or if r&d wants to build something.  Maybe remove the autolathe from R&D?

As long as the cost for the console screen in the protolathe is the same as the autolathe its all good.

2017-11-12 07:46 UTC, DrSnips commented
Careful there. Removing the autolathe from research will likely encourage moving all autolathe designs to the proto to make up for it. I don't think that should ever be the case. Each plays a role and I've already talked about that.

2017-11-12 07:50 UTC, Aurx commented
Eh.  It'd more just encourage R&D to build one when they wanted autolathe things.

2017-11-12 07:50 UTC, Aurx commented
Eh.  It'd more just encourage R&D to build one when they wanted autolathe things.

2017-11-17 16:33 UTC, SonixApache commented
console screen in auto- and protolathe is fine because they're used by different groups
R&D will likely queue up a few screens in the protolathe along with the other five billion stock parts they need
cargo / assistants / mechanics / whoever will likely get them from the autolathe since those are more easily accessible

i don't see the issue

2017-12-03 06:14 UTC, icantthinkofanameritenow commented
In most stations, RnD already has an autolathe. It's pointless.

2017-12-03 17:24 UTC, FudgePucker commented
Mechanics need to make an autolathe. If it wasn't for the screen in tech storage they would have to go to cargo or science to get one.

2017-12-03 17:24 UTC, PJB3005 commented
So, just make them rely on tech storage then I'd say.

On 3 Dec 2017 18:24, "FudgePucker" <notifications@github.com> wrote:

> Mechanics need to make an autolathe. If it wasn't for the screen in tech
> storage they would have to go to cargo or science to get one.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/16510#issuecomment-348799004>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHu1w8mQOjFbsFvCksuqz9PgE1dvest3ks5s8tk_gaJpZM4QY8NK>
> .
>

2017-12-08 14:07 UTC, Pathid commented
There is a part vendor for them in primary tool storage too.

2017-12-17 05:08 UTC, closed without merging