Atmos-related shortcuts
d3athrow/vgstation13 pull request #16543
Opened 2017-11-11 06:22 UTC by Kurfursten

Can't tell you how often I don't want to fuck with the rotate pipe verb or open the pump interface.

Incidentally, it's weird that there needs to be an allowed check on interacting with the pumps, since by default they have no access requirement, but perhaps it's for some mapped in special pumps or adminbus where players aren't meant to mess with them.

🆑 
* rscadd: Alt-clicking a gas pump or volume pump will toggle it on/off.
* rscadd: Alt-clicking a pipe segment that isn't wrenched down will rotate it.

2017-11-11 06:46 UTC, Kurfursten commented
General reminder that no matter how small the change, compile before you push

2017-11-17 23:33 UTC, PJB3005 requested changes

2017-11-17 23:33 UTC, PJB3005 commented on code/ATMOSPHERICS/components/binary_devices/pump.dm
> +		investigation_log(I_ATMOS,"was turned [on ? "on" : "off"] by [key_name(user)].")
Make this into a proc.

2017-12-25 18:45 UTC, PJB3005 commented
@Kurfursten is this ever going to get fixed.

2017-12-26 07:11 UTC, Kurfursten commented
Yes

2018-01-17 16:31 UTC, DamianX commented
when

2018-01-17 19:02 UTC, Kurfursten commented
Tonight, I just got to a stopping point on my main branch

2018-01-18 04:49 UTC, Kurfursten commented
What's new?
* Now works on most binary devices (fully tested)
* Now a binary-level proc

2018-01-18 09:38 UTC, DamianX commented
Some maps override the `open` var for certain valves, you have to fix this those

2018-01-18 23:30 UTC, Kurfursten commented
This is ready to merge

2018-01-19 07:19 UTC, merged