Service borg H.U.E.Y. upgrade and upgrade tweaks/cleanup
d3athrow/vgstation13 pull request #16564
Opened 2017-11-14 00:11 UTC by jknpj

![nunames](https://user-images.githubusercontent.com/17928298/32756070-5a66c2d8-c8bf-11e7-9d3c-c3d579adcdac.png)

Cleans up upgrade code a little, fixes an odd bug with the lyscis machine and grippers, removes the ability to hold seeds and glass containers from the cooking upgrade and adds the H.U.E.Y. upgrade, it gives service borgs a mini hoe, clippers, plant bag and analyzer.

Also makes the cooking module cheaper for losing the plant bag and gripper upgrades.

:cl:
 * rscadd: Adds the H.U.E.Y. upgrade to service cyborgs! It comes with a mini hoe, clippers, plant bag, plant analyzer and makes the service gripper able to handle seeds and glass containers.
 * tweak: Removes the botanics-related upgrades from the cooking upgrade and makes it cheaper.

2017-11-14 00:15 UTC, Shadowmech88 commented
>removes the ability to hold [...] glass containers from the cooking upgrade

So service cyborgs with the cooking upgrade no longer have a way to cook with reagents?

2017-11-14 00:20 UTC, jknpj commented
Drink containers(shaker, drinking glass, mugs) can hold reagents just fine. Buckets/Fertilizer bottles are glass containers.

2017-11-14 01:26 UTC, Shadowmech88 commented
How often are grinders used in cooking? I imagine they can't use them without touching beakers specifically.

2017-11-14 02:05 UTC, jknpj commented
You can actually load the grinder with a shaker. Alt+click to pop out the beaker and insert a shaker.

2017-11-28 19:56 UTC, PJB3005 requested changes

2017-11-28 19:56 UTC, PJB3005 commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/proc/locate_component(var/obj/C, var/mob/living/silicon/robot/R, var/mob/living/user)
Sorry for not getting to this sooner, but you absolutely should not mix the possible return type here.

2017-12-08 17:44 UTC, PJB3005 commented
You still didn't fix the mixed return type.

2017-12-08 19:56 UTC, jknpj commented
I am not a clever man.

2017-12-08 21:01 UTC, PJB3005 commented on code/game/objects/items/robot/robot_upgrades.dm
> +		return
Return `null` explicitly. A bare `return` implies that this proc doesn't return anything ever.

2017-12-09 21:26 UTC, PJB3005 approved these changes

2017-12-09 21:26 UTC, merged