Adds drums, makeshift drums, and bongos
d3athrow/vgstation13 pull request #16662
Opened 2017-12-01 17:48 UTC by RealestEstate

Adds 3 types of drums. a regular drum that can be ordered through cargo much like the other instruments, a makeshift drum that can be constructed using a wooden bowl and a sheet of leather, and bongos that can be constructed by combining 2 makeshift drums. the bongos can be played without checking for dexterity so things like monkeys and retards can play the bongos.
makeshift drums can be disassembled using wirecutters.

Here is a video demonstrating the process:
http://webm.land/media/9ziM.webm

  :cl:
*rcadd: Added drums and makeshift drums

2017-12-02 16:43 UTC, PJB3005 requested changes

2017-12-02 16:43 UTC, PJB3005 commented on code/game/objects/items/devices/instruments.dm
> +		visible_message("<span class='notice'>[user] cuts the leather face off the drum with [I]. </span>")
`\the [I]`, also wouldn't you want `\the [src]` instead of `the drums`?

2017-12-02 16:43 UTC, PJB3005 commented on code/game/objects/items/devices/instruments.dm
> +		var/woodbowl = /obj/item/trash/bowl
Why define this in a local variable? It can't be changed here.

2017-12-02 16:43 UTC, PJB3005 commented on code/game/objects/items/devices/instruments.dm
> +		var/bongos = /obj/item/device/instrument/drum/drum_makeshift/bongos
Again, why declare the type locally?

2017-12-02 19:01 UTC, RealestEstate commented
The pointless variables should be gone now, and fixed up the decon notice

2017-12-03 12:20 UTC, Riekland commented
no more fucking midi instruments please god

2017-12-03 15:33 UTC, RealestEstate commented
bro, I have like 3 more instruments getting coded in after this. we'll be an interactive black midi orchestra by the end of it.

2017-12-03 16:10 UTC, PJB3005 approved these changes

2017-12-07 15:31 UTC, merged