airlocks no longer spawn an invisible locking forcefield on you
d3athrow/vgstation13 pull request #16709
Opened 2017-12-07 23:31 UTC by MadmanMartian

as requested in the thead. Not entirely sure if I'm using canmove correctly in this case.

closes #13576

2017-12-07 23:46 UTC, Unknown-as-Captain commented
What's the point of the canmove of the victim gets stunned anyways?

2017-12-08 01:32 UTC, Pathid commented
The explanation for that and the "forcefield" being a thing: https://github.com/vgstation-coders/vgstation13/issues/13576#issuecomment-274309879

2017-12-08 06:48 UTC, SonixApache commented
muh doorcrushing

2017-12-08 13:37 UTC, Pathid commented
After thinking about this, do we really want to remove doors catching people who are being ZAS'd through them? Or breaking the grip of somebody happening to pull the victim through the door?

The objection of "excellent timing" being necessary to pull someone out falls flat since you can just grab them and spam-click the tile you're on. And as each crush is really only 10 brute you get many tries.

2017-12-08 17:40 UTC, Unknown-as-Captain commented
Just like use firelock

2017-12-08 17:46 UTC, PJB3005 requested changes

2017-12-08 17:46 UTC, PJB3005 commented on code/game/machinery/doors/airlock.dm
> +				L.canmove = 0
I'm 99% sure that force setting `canmove` won't work for mobs like humans.

2017-12-08 19:54 UTC, Hugh-G-Rection commented
Going full realism mode, the implication here is that someone is being closed inside what is essentially an airtight steel clamp. My thoughts are the damage is way too low, and it opens and closes far too fast. They definitely shouldn't be able to move if an airlock is closed on them, maybe pulled/ripped out at the loss of a limb? If doors open/close time after a crush was slowed to just under stun time, the damage could be increased and AI could still reliably kill people without help, and even with someone there to assist they couldn't get them out of the airlock without opening it (assuming AI would bolt it closed around them) and so would have to delimb the person to free them, likely killing them from bloodloss.

I'm just trying to think of a change that would alter the dynamics of it's use, instead of always being mash as fast as possible. But I'm also just blogposting because I'm bored at work so feel free to ignore me entirely.

2017-12-27 11:57 UTC, DamianX commented
Is this going anywhere?

2018-01-17 16:07 UTC, closed without merging