Gives keycard scanners more things that they can do
d3athrow/vgstation13 pull request #16760
Opened 2017-12-12 16:13 UTC by jakmak6

This PR adds more access lifting to the head of staff keycard scanner. There are currently 6 new options on the keycard scanner. 

Grant Emergency Mining Base Access
Revoke Emergency Mining Base Access
Grant Emergency Xenoarchaeology Base Access
Revoke Emergency Xenoarchaeology Base Access
Remove Crew Weapon Restrictions
Re Enable Crew Weapon Restrictions

The new function does what it says on the tin. Removing the mining base/xenoarch base access removes the access check for mining/xenoarch access on airlocks/windoors/shuttle consoles.

The remove crew weapon restrictions removes the access check for armory on all crates, airlocks, windoors, and lockboxes(WIP).

99% tested

Issues. 
With the xenoarch access grant it gives access to all normal science and RnD access doors since there isnt a regular xenoarch access and the research shuttle/xenoarch base just uses science/RnD access.
The armory access lift removes access on the brig cell windoors. This is because the box station armory has several windoors with the same access as the brig cell doors
Lockbox access removeal is still WIP.
The new options on the keycard scanner are misaligned. https://puu.sh/yER54/bb23b05ac9.png

2017-12-12 16:20 UTC, PJB3005 requested changes
Adding all these global variables and `allowed()` overrides on airlocks is getting ridiculous. Make it into a  generic global list of access levels that doors should ignore, and add/remove from this list for these buttons.

EDIT: The lockbox hardcode is probably still fine though.

2017-12-12 23:12 UTC, Unknown-as-Captain commented on code/modules/security levels/keycard authentication.dm
> +			</ul>"}
Remove </ul>s except the last

2017-12-12 23:33 UTC, Blithering commented
A setting to allow security into areas would be a neat use

2017-12-13 01:08 UTC, Arthurdentist commented
I'd change the name "Xenoarchaeology Base" and "Mining Base" to just "Science Station" and "Mining Station", but that is just me.

2017-12-14 16:41 UTC, jakmak6 commented
@Blithering i didnt want to add to much to it to prevent it from being to OP.

@Arthurdentist still trying to figure out what sounds best for the new access elevation things

2017-12-25 18:40 UTC, closed without merging