Curtains are now anchored in place.
d3athrow/vgstation13 pull request #16797
Opened 2017-12-16 11:50 UTC by Sooose

One line change that makes curtains anchored to the ground.

2017-12-16 13:38 UTC, SonixApache commented
unmovable curtains

2017-12-16 14:48 UTC, Exxion commented
*What* meme potential?

2017-12-16 22:12 UTC, Sooose commented
Being able to move them on top of you to hide like a plant, I suppose. You can still wire cut them to get the full cost of making them back.

2017-12-18 05:16 UTC, DamianX commented
If memes are a concern, a way to anchor/unanchor them could work.

2017-12-18 07:24 UTC, DamianX requested changes

2017-12-18 07:24 UTC, DamianX commented on code/game/objects/structures/curtains.dm
> +			to_chat(user, "<span class='notice'>You cut the [src] down.</span>")
This should be `\the [src]` or just `[src]`

2017-12-18 07:24 UTC, DamianX commented on code/game/objects/structures/curtains.dm
> +		user.visible_message("[user] [anchored? "unsecures" : "secures"] the [src].", "You [anchored? "unsecure" : "secure"] the curtains.")
same here

2017-12-18 11:38 UTC, SonixApache commented
with re-anchor options i declare this a :+1:

2017-12-18 15:57 UTC, DamianX approved these changes

2017-12-20 03:46 UTC, merged