Cat ears give extremely mild brain damage over time
d3athrow/vgstation13 pull request #16831
Opened 2017-12-19 20:58 UTC by Unknown-as-Captain

Takes 10 full minutes of uninterrupted wearing before the wearer has ill effects. If you wanted to wear them for a stageplay or a prank, the gradual brain damage is very manageable.

Some guy in the thread wanted this. I don't really care if it gets merged or not. I think this is PR is self-explanatory enough so I won't even make any comments in it.

:cl:
 * tweak: Cat ears made more goofy.

2017-12-19 21:03 UTC, EenKogNeeto commented
Only if things like the fedora do too.
Tbh I'll just pop a alky pill every hour or so and keep wearing them like I have been for years.

2017-12-19 21:05 UTC, Commandersand commented
>implying fedoras shouldn't heal brain damage

2017-12-19 21:13 UTC, yclatious commented
Make it surgery-to-fix brain damage and we have a deal.

2017-12-19 21:18 UTC, Ephx1 commented
Toptier.
@EenKogNeeto 
It used to give some extreme brain damage along with toxins, or maybe that was an admin special version.

2017-12-19 21:28 UTC, DrSnips commented
Why should this be a thing and how does it make sense?

2017-12-19 22:51 UTC, FudgePucker commented
@DrSnips
Memes.

Why don't we just deal brain damage to people who pick up the captains spare <5 mins into the round if they aren't captain or HoP (or traitor, although then it could be abused as a detector.)
I think power gaming assfaggots are 100 times more cancerous for the server than waifus.

2017-12-19 23:16 UTC, DrSnips commented
I don't think waifus should ever be a factor in decision making. Anti or pro.

2017-12-20 00:33 UTC, Arthurdentist commented
unironically buffs the anime virus and cursed dice

2017-12-20 01:31 UTC, Kurfursten commented
I'd rather see cat ears removed than turned into another trap for new players. Same reason I disagreed with the "spooky" meme camera. As someone who has literally never put on cat ears as far as I can remember.

A year down the line everyone forgets the joke and the effect isn't documented anywhere, not in the item description, no verbose warning messages, not on the wiki (nor is there a very good place to put it on the wiki).

2017-12-20 03:35 UTC, Pathid commented
The dreaded Waifus will take alkysine and the ears will be a trap for the ignorant and the new. Which I'm not against in principle, but I think it would be more fun to instead make them give a slight chance of getting non-contagious Kingston's Syndrome.

2017-12-20 03:38 UTC, DrSnips commented
Im gonna shoot this down real quick because that's a very easy way to catbeast someone. Catbeast is usually reserved for bus or other intervention.

2017-12-20 03:40 UTC, Pathid commented
I thought of that but the way I'm imagining it the chance would be very low. You'd have to make someone wear the ears through several rounds to have a decent chance of doing that, and you'd be on the hook if you're a non-antag.

2017-12-20 03:42 UTC, DrSnips commented
Its likely best to not make it a valid/valid bait item.

2017-12-20 04:03 UTC, Pathid commented
Probably. Adding weird little effects to costumes though, not the worst idea. Slow brain damage is just dull. Now, maybe rolling for a medium-sized burst of brain damage from time to time, that might actually do  something.

2017-12-20 04:04 UTC, Unknown-as-Captain commented
I said I wouldn't comment but this is more about the implementation than the "politics" of it.
The reason why this isn't a straight-up removal was in the off chance that a clown or mime wanted them for a stageplay or prank or trying to infiltrate a kingston adminbus invasion or something.
What if I just added a message when the ears are equipped?

2017-12-20 04:06 UTC, Unknown-as-Captain commented
Also, what if they just made you clumsy while worn instead of brain damage?

2017-12-20 04:12 UTC, DrSnips commented
I just don't think spite coding is a good practice. Should I code it so if you wear a grey jumpsuit you get X brain damage per second because I don't like a certain group of players? No and it should never be that way.

2017-12-20 04:31 UTC, DamianX approved these changes

2017-12-20 10:20 UTC, SonixApache commented
[needs changelog]

2017-12-20 12:15 UTC, DamianX commented
But that would only enable them more. Also there is already sort of a changelog.

2017-12-20 12:32 UTC, jknpj commented
I mean it needs a PROPER changelog. Unless you want to repeat the lootbox episode, that is.

2017-12-20 12:36 UTC, DamianX commented
I could play the Devil's advocate and mention the table climbing changelog(s)

2017-12-20 12:42 UTC, DrSnips commented
I think we gave a special pass to tableclimbing due to the nature of things.

2017-12-20 12:51 UTC, Blithering commented
What if the brain damage was removed when the ears were? That way it's less of a hassle to deal with for medbay.

2017-12-20 13:01 UTC, Jeroen52 commented
What about a very small chance to catbeast someone wearing cat ears?

2017-12-20 13:10 UTC, DrSnips commented
Scroll up.

2017-12-20 13:10 UTC, ShiftyRail commented
@Jeroen52 if it was a high enough chance to matter, it would remove people from the round too often. If it was a low enough chance, it would serve no purpose.

@Unknown-as-Captain add a little flavour text to warn newfriends.

2017-12-20 13:17 UTC, DrSnips commented
A bit of flavor text isn't enough to warn players. See lootbox flavor text clearly stating GIB LOOT and how well it stopped people from using them.

2017-12-20 14:12 UTC, Arthurdentist commented
Could add an obvious warning similar to the "are you feeling lucky?" warning from cursed dice. I agree with Kurfurst overall though and I don't think this is a good change.

2017-12-20 14:48 UTC, jknpj commented
I feel like this feature would be great in a cat ear subtype(make the cursed dice use it)

2017-12-20 19:00 UTC, Unknown-as-Captain commented
I agree with @Kurfursten's reasoning.
Added a warning on equip, and a message on unequip to make sure.
I liked the idea of it making you clumsy but kept the brain damage for now.

2017-12-21 17:52 UTC, Zennyization commented
I dont understand peoples obession with PR's like this. Why do cat-ears need to give people brain-damage, why are people not allowed to wear them. This is really pointless.

2017-12-21 18:00 UTC, Ephx1 commented
it's funny

2017-12-21 18:51 UTC, PJB3005 requested changes

2017-12-21 18:51 UTC, PJB3005 commented on code/modules/clothing/head/misc_special.dm
> +	if(H.head == src)
Compare the `slot` variable instead of checking the mob's inventory variables directly.

2017-12-21 18:51 UTC, PJB3005 commented on code/modules/clothing/head/misc_special.dm
> +	if(wearer.head == src)
Use `get_item_by_slot(slot_head)` instead of reading the inventory variables directly.

2017-12-22 20:04 UTC, Unknown-as-Captain commented
I don't think github's browser resolve conflicts feature works.

2017-12-22 20:26 UTC, SonixApache commented
ya blew it

2017-12-25 00:06 UTC, Unknown-as-Captain commented
@PJB3005 I believe I complied with your review

2017-12-26 12:17 UTC, Shadowmech88 commented
Personally, I'm not sure it's necessary to add a mechanical disadvantage to a cosmetic item because of the behavior associated with it.
Players are already free to treat crew members wearing cat ears like garbage, short of actually assaulting them.

To me it seems like the kind of thing that should be punished IC, since it is tied to behavior and behavior is entirely IC.

2017-12-26 12:29 UTC, PJB3005 approved these changes

2017-12-27 20:06 UTC, outbools commented
It's totally fine for waifu players to take brain heal pills constantly.



That's just like they do in real life amirite

2017-12-27 20:19 UTC, SonixApache commented
@outbools 🔥

2017-12-28 06:32 UTC, Lokiamis commented
Meta feature that doesn’t make any sense. The ears are shitty, open a PR to remove them if you don’t like them.

2017-12-29 03:15 UTC, agentofzog commented
it should only affect females

2018-01-01 21:55 UTC, Unknown-as-Captain commented
No conflicts here

2018-01-04 15:47 UTC, DamianX commented
Into the trash it goes.

2018-01-04 17:31 UTC, Unknown-as-Captain commented
So those 20 votes aren't counted as positive, then?

Can you give a reason for closing this after a week of no updates?

2018-01-04 17:54 UTC, DamianX commented
One of those "votes" comes from myself, just because this got a chuckle out of me doesn't mean I support it.
3-4 collabs weren't too thrilled to have this merged.
This PR comes off as coders trying to police what a certain group of players should wear, I think we can agree this is not a good thing.
Additionally, it breaks my emulshions. Would you like me to reopen this and create a server poll?

2018-01-04 18:08 UTC, Unknown-as-Captain commented
I can change this to simply remove the cat ears from the autodrobe if you'd like. I thought that to be the more restrictive option but I agree it's more immulsions friendly. I was going for an effect similar to floor-length braids and perhaps it didn't make a lot of sense in the end.

A poll would be great as well.

2018-01-04 18:33 UTC, DrSnips commented
As Damian said I don't think policing what people can and can't wear via code is a good path to go down. A poll could be made but I don't think even then its a good idea. "I don't like X group of people so lets add a debuff to having an item on them if I can get Y people to agree with this idea." X could become grey jumpsuits and Im pretty sure I could find Y people who also dislike the group of people who wear grey jumpsuits.

2018-01-04 18:54 UTC, DamianX commented
http://ss13.moe/index.php/poll/137

2018-01-05 22:55 UTC, Megamaw commented
from what i've learned, regardless of what the result is, your poll can be dismissed as 'illegitimate' or a 'meme poll'.

i would argue this is a 'meme poll'.

a poll does not mean your pull gets instantly accepted.

2018-01-05 23:39 UTC, DamianX commented
hide megamaw posts
ignore megamaw posts
do not reply to megamaw posts

2018-01-06 01:01 UTC, Ephx1 commented
Imagine still being this sour over skeletons

2018-01-12 01:15 UTC, merged

2018-01-12 01:15 UTC, DamianX commented
Update the wiki I guess

2018-01-20 13:46 UTC, NigglyWiggly commented
This is fucking retarded.
Why in the fuck

2018-01-20 15:08 UTC, Ephx1 commented
Very fitting you of all people would complain about this.