Helpers for spells
d3athrow/vgstation13 pull request #16846
Opened 2017-12-23 01:40 UTC by ShiftyRail

Still a work in progress, need to find and tag the xenomorphs spells.
Helpers for spells, fix the hardcoding issues for #16819

Also did absent-mindedly a bunch of absolute pathing refactors in the dna folders, I'll revert it if I'm asked.

2017-12-23 21:12 UTC, ShiftyRail reviewed
>cannot request changes on your own PR

2017-12-23 21:12 UTC, ShiftyRail commented on code/game/gamemodes/wizard/spellbook.dm
> +	var/debug_nb_sorts = 0
DEBUG VARIABLE AA

2017-12-23 22:31 UTC, ShiftyRail commented
Should be finished.

2017-12-24 12:35 UTC, ShiftyRail commented
This time it should be all good, tested and all.

2017-12-24 12:49 UTC, PJB3005 requested changes
Use defines for all the spell types.

2017-12-24 14:51 UTC, PJB3005 approved these changes

2017-12-26 11:56 UTC, merged