Fixes mommi drop_item() runtime
d3athrow/vgstation13 pull request #16843
Opened 2017-12-22 14:30 UTC by jknpj

```
[09:06:49] Runtime in ,: bad arg name 'dontsay'
  proc name: drop item (/mob/living/silicon/robot/mommi/drop_item)
  usr: HA-N1-WA () (/mob/living/silicon/robot/mommi)
  usr.loc: space (270, 280, 1) (/turf/space)
  src: HA-N1-WA (/mob/living/silicon/robot/mommi)
  src.loc: space (270,280,1) (/turf/space)
  call stack:
  HA-N1-WA (/mob/living/silicon/robot/mommi): drop item(null, null, 1)
  HA-N1-WA (/mob/living/silicon/robot/mommi): drop from inventory(the station bounced radio (/obj/item/device/radio/borg))
  the station bounced radio (/obj/item/device/radio/borg): Destroy()
  the station bounced radio (/obj/item/device/radio/borg): Destroy()
  qdel(the station bounced radio (/obj/item/device/radio/borg), 0, 0)
  HA-N1-WA (/mob/living/silicon/robot/mommi): Destroy()
  HA-N1-WA (/mob/living/silicon/robot/mommi): Destroy()
  HA-N1-WA (/mob/living/silicon/robot/mommi): Destroy()
  HA-N1-WA (/mob/living/silicon/robot/mommi): Destroy()
  HA-N1-WA (/mob/living/silicon/robot/mommi): Destroy()
  ...
  HA-N1-WA (/mob/living/silicon/robot/mommi): singularity act(9, the gravitational singularity (/obj/machinery/singularity))
  the gravitational singularity (/obj/machinery/singularity): consume(HA-N1-WA (/mob/living/silicon/robot/mommi))
  the gravitational singularity (/obj/machinery/singularity): Crossed(HA-N1-WA (/mob/living/silicon/robot/mommi))
  HA-N1-WA (/mob/living/silicon/robot/mommi): Move(space (270,280,1) (/turf/space), 2, 0, 0, 0)
  HA-N1-WA (/mob/living/silicon/robot/mommi): Move(space (270,280,1) (/turf/space), 2, 0, 0, 0)
  HA-N1-WA (/mob/living/silicon/robot/mommi): Move(space (270,280,1) (/turf/space), 2, null)
  HA-N1-WA (/mob/living/silicon/robot/mommi): Move(space (270,280,1) (/turf/space), 2, null)
  HA-N1-WA (/mob/living/silicon/robot/mommi): Move(space (270,280,1) (/turf/space), 2, null)
  AdrianoKing (/client): Move(the floor (270,281,1) (/turf/simulated/floor), 2)
  AdrianoKing (/client): move loop()
```

Turns out mommis don't overwrite borg's drop_from_inventory()

2017-12-23 16:29 UTC, PJB3005 requested changes

2017-12-23 16:29 UTC, PJB3005 commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	if(!isMoMMI(src))
No src type checks.

2017-12-23 21:03 UTC, PJB3005 commented
Question: why isn't adding `dontsay` to `drop_item()` a solution here?

2017-12-23 21:57 UTC, jknpj commented
because mommis still use the default drop_from_inventory()

2017-12-26 12:28 UTC, PJB3005 approved these changes

2017-12-26 12:29 UTC, merged