Can no longer crawl under plastic flaps
d3athrow/vgstation13 pull request #16929
Opened 2017-12-29 18:58 UTC by MadmanMartian

You can still be thrown/slipped under plastic flaps, you now can't just click to crawl under a plastic flap.

2017-12-29 18:59 UTC, Duny- commented
Crawling was a mistake.

2017-12-29 19:13 UTC, PJB3005 requested changes
Nope, not happening like this. No hardcode here.

2017-12-29 22:29 UTC, SGuivenne commented
Either keep crawling and the plastic flap thing because FUCK is it convenient, or remove crawling entirely, this isn't an option that'll make anyone happy.

2017-12-30 00:18 UTC, closed without merging

2017-12-30 00:21 UTC, SonixApache commented
Any way you'll revive this?