Minor fix for explosive chemical reactions
d3athrow/vgstation13 pull request #17151
Opened 2018-01-20 22:48 UTC by N3X15

# Changelog
:cl:
 * bugfix: Fixes a bug with explosive chemical mixtures erroneously removing holders in mobs.

2018-01-20 22:48 UTC, PJB3005 commented
Shitstorm in 3... 2... 1...

2018-01-20 22:50 UTC, PJB3005 requested changes

2018-01-20 22:50 UTC, PJB3005 commented on code/modules/reagents/Chemistry-Recipes.dm
> +	if(istype(holder, /mob))
Use `ismob`

2018-01-20 22:52 UTC, PJB3005 approved these changes

2018-01-20 23:11 UTC, merged

2018-01-20 23:52 UTC, ShiftyRail commented
This could have used more time for discussion.
Speedmerges are (in theory) for hotfixes and game-breaking bugs.

2018-01-20 23:54 UTC, Chazach commented
that merge......
h-he's fast!

2018-01-20 23:57 UTC, small-boss commented
are we doing pr merge speedruns too now?

2018-01-21 00:02 UTC, kilozombie commented
Wait, so since when was this a bug?

2018-01-21 00:03 UTC, aceedex commented
When there's peer review and discussion before merging 
🖓🕵

2018-01-21 00:07 UTC, DrCelt commented
lmao nothing changes

2018-01-21 00:11 UTC, aceedex commented
You could have stopped this

2018-01-21 00:13 UTC, DrCelt commented
nobody could and nobody can except pomf and he doesn't have the balls

2018-01-21 00:16 UTC, EdXbtkOEwGw commented on code/modules/reagents/Chemistry-Recipes.dm
> +	if(ismob(holder))
Holy mother of snowflake batman.

If what you want to do is remove the reagent clearing (which I see no evidence of being a bug, for the record) then what is this hardcoded shit doing here?
The chemical reaction already implicitly removes potassium and water.

2018-01-21 00:20 UTC, kilozombie commented
time to go back to killing and cloning
treating is for weenies :^)

2018-01-21 00:34 UTC, SarahJohnson489 commented
tfw your extinguisher hit count is higher than your pill force feeds