Thrones
d3athrow/vgstation13 pull request #17200
Opened 2018-01-23 12:51 UTC by MadmanMartian

Adds thrones. Made from 40 wood planks, takes 10 seconds to build, and will make the captain green with envy.

Also removes copypaste from the chair section, as it was getting weird in there.

:cl:
* rscadd: Can now build thrones from wood.

2018-01-23 13:43 UTC, DeityLink commented
Reminds me that stone still isn't a material.

2018-01-23 15:50 UTC, Diavill commented
where sprite

2018-01-24 12:17 UTC, ultraplen commented
Been a while since I worked on the chair code, but have you made sure that all the chair layers work fine after your copy-paste removal? I think I recall that bunch of the chairs need snowflake stuff to make the layers appear correctly.

2018-01-24 13:09 UTC, MadmanMartian commented
Their specific snowflake bits should still work, I just moved the overlay adding and removing down to regular chair level as that was the bit that was redundantly copypasted

2018-01-28 23:14 UTC, DamianX commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	..()
This is going to completely turbofuck vehicles and possibly others, make sure the return value is passed along

2018-01-30 19:54 UTC, PJB3005 requested changes

2018-01-30 19:54 UTC, PJB3005 commented on code/game/objects/items/stacks/stack.dm
> +				for(var/ii=1;ii<=R.other_reqs.len,ii++)
`for (var/ii = 1 to R.other_reqs.len)`

2018-01-30 19:54 UTC, PJB3005 commented on code/game/objects/items/stacks/stack.dm
> +		if(R.other_reqs.len)
This is gonna break. You can still build it provided the UI doesn't update.

2018-01-31 12:55 UTC, PJB3005 requested changes
Now the building code uses materials even if the construction fails to find all materials.

2018-01-31 14:39 UTC, MadmanMartian commented
@PJB3005 changes made

2018-02-07 20:49 UTC, jknpj approved these changes

2018-02-07 20:49 UTC, merged