Ports the Portable Seed Extractor from TG and adds it to the H.U.E.Y. upgrade
d3athrow/vgstation13 pull request #17269
Opened 2018-01-29 21:09 UTC by jknpj

I couldn't test this properly yet.

:cl:
 * rscadd: Ports the portable seed extractor from TG. It doubles ad both plant bag and seed extractor but it can only extract at most two seeds per crop.
 * rscdel: Removed the plant bag from the H.U.E.Y. upgrade.
 * rscadd: Added the portable seed extractor to the H.U.E.Y. upgrade.

2018-01-30 19:30 UTC, PJB3005 requested changes

2018-01-30 19:30 UTC, PJB3005 commented on code/__HELPERS/unsorted.dm
> +		return FALSE
Should do a `CRASH()` instead because this is clearly an error.

2018-01-30 19:30 UTC, PJB3005 commented on code/__HELPERS/unsorted.dm
> +/proc/seedify(obj/item/O, obj/machinery/seed_extractor/extractor, mob/living/user)
`extractor` and `user` should default to null if they're optional.

2018-01-30 19:30 UTC, PJB3005 commented on code/game/objects/items/weapons/storage/bags.dm
> +		if(usr)
`usr` aint happening.

2018-01-30 22:00 UTC, jknpj commented on code/game/objects/items/weapons/storage/bags.dm
> +		if(usr)
fug

2018-01-31 12:45 UTC, PJB3005 commented on code/game/objects/items/weapons/storage/bags.dm
> +	var/mob/user = usr
Wait. You mean action buttons actually don't pass a user?

TG why.

2018-01-31 12:46 UTC, PJB3005 approved these changes

2018-01-31 12:46 UTC, merged