wearable trashbags and chicken bucket hats & storage item tweak
d3athrow/vgstation13 pull request #17274
Opened 2018-01-30 04:08 UTC by RealestEstate

lets you wear an empty trashbag on the outer suit slot and an empty kfc bucket as a hat. also tweaks how the code handles wearing a storage on item on a slot and having it not function as a storage item while in that slot (ie wearing plastic bags on your head).

https://media.discordapp.net/attachments/239823497365422091/385482537100771338/trashofficer.png

sprites courtesy of Blithering, aka the Grand Duke of the Trashin' Fashion Scene.
 * rscadd:empty trash bags can be worn on the suit slot and empty chicken buckets can be worn as hats. Sprites courtesy of Blithering

2018-01-30 12:34 UTC, SonixApache commented
unnecessary tweaks
bring back hat storage

2018-01-30 13:45 UTC, unid15 commented on code/game/objects/items/weapons/storage/storage.dm
> +	for (var/i in no_storage_slot)
```
if(no_storage_slot.Find(slot) && contents.len)
    return CANNOT_EQUIP
```

2018-01-30 19:15 UTC, PJB3005 requested changes

2018-01-30 19:15 UTC, PJB3005 commented on code/game/objects/items/weapons/storage/storage.dm
> +	var/list/no_storage_slot = new/list()//if the item is equipped in a slot that is contained in this list, the item will act purely as a clothing item and not a storage item (ie plastic bags over head
Use `list()`, not `new/list()`

2018-01-30 19:15 UTC, PJB3005 commented on code/game/objects/items/weapons/storage/storage.dm
> +/obj/item/weapon/storage/proc/can_be_inserted(obj/item/W as obj, stop_messages = 0,mob/M, slot)
Where are you changing the usage of this proc to pass the new arguments?

2018-01-31 02:44 UTC, RealestEstate commented
I think I've addressed the changes as they were suggested

2018-01-31 02:51 UTC, Lokiamis commented
My favourite pr

2018-01-31 04:41 UTC, RealestEstate commented
why is icons/mob/head.dmi a conflicting file? is there another PR that is using it?

2018-01-31 12:44 UTC, Lokiamis commented
Because of #17240

2018-01-31 12:50 UTC, PJB3005 approved these changes

2018-02-03 15:44 UTC, SkowronX commented
da trashman

2018-02-17 11:26 UTC, DamianX commented
please fix the conflicts

2018-03-01 16:00 UTC, closed without merging