adds stubborn brain syndrome, reworks becoming a zombie after death a bit
d3athrow/vgstation13 pull request #17296
Opened 2018-01-31 17:29 UTC by MadmanMartian

Stubborn brain syndrome - where the brain is just too stubborn to stay dead.

become_zombie_after_death isn't a boolean anymore. If 1, the subject becomes a zombie without a mind to control it. If 2, the subject becomes a zombie with a mind to control it.

Also, sweet jesus zombies need a rework. Tested the virus on an unathi, and it became a bald dude with a lizard tail.

2018-01-31 17:45 UTC, ShiftyRail requested changes
Don't use `TRUE` and `TRUE + 1`, I think you should use more explicit defines.

2018-01-31 19:10 UTC, DamianX commented
>TRUE+1
surely this is a joke

2018-02-01 10:46 UTC, MadmanMartian commented
It is. It's a non-boolean value, but I don't see the bloody point of having a define for 1 and 2 when the number is used for maths as well as gating

2018-02-01 12:32 UTC, DamianX commented
yeah just use numbers
???

2018-02-01 22:51 UTC, Riekland commented
>unathi

2018-02-01 23:02 UTC, MadmanMartian commented
I test all my viruses on 
- a chicken vox thing
- a monkey
- a clown
- a tajaran
- a skellington
- an unathi

2018-02-02 19:07 UTC, Riekland commented
>tajaran
>unathi

2018-02-07 12:10 UTC, jknpj approved these changes
Looks alright for me.

2018-02-07 20:26 UTC, merged