[WIP] Chem Master 4000 - A more advanced chem master
d3athrow/vgstation13 pull request #17301
Opened 2018-02-01 22:41 UTC by Reviire

In essence, this is identical to the normal chem master, except it has an internal reagent storage, and retains reagents even after you remove the beaker. Generally more convenient than the standard one.

Definitely not finished, since it's pretty much just better it'll need some way to acquire it, maybe changes to how good it is. I'm not quite sure.

TODO: 
Get my hands on the sprite.
Put it into R&D
Learn how to code

The sprite, opinions?
https://cdn.discordapp.com/attachments/390134069582888960/393395409890050049/Screenshot_2017-12-21-21-32-45-679_com.meltinglogic.pixly.png

:cl:
 * rscadd: Adds the Chemical Manipulator, essentially a better chem master.

2018-02-01 22:42 UTC, Reviire commented
I don't understand github at all those commits weren't supposed to be there I was confused.

2018-02-03 08:02 UTC, ShiftyRail commented on code/game/machinery/kitchen/snackbarmachine.dm
> +		if(istype(SP, /obj/item/weapon/stock_parts/manipulator))
Make a list of all those types and use `if (is_type_in_list(SP, L)`.

2018-02-03 08:02 UTC, ShiftyRail commented on code/game/machinery/kitchen/snackbarmachine.dm
> +	if(buffer_mode == 1)
Use a define for this.
`#define STORAGE 1` and then `if (buffer_mode == STORAGE)`.
Same for next line.

Additionally, you could use a switch statement.

2018-02-03 08:02 UTC, ShiftyRail commented on code/modules/reagents/machinery/chem_master.dm
> +			if(storage_mode == 1)
You could use defines as well as a switch statement here and in the following lines.

2018-02-03 18:09 UTC, MadmanMartian commented on code/game/machinery/kitchen/snackbarmachine.dm
> +/obj/machinery/chem_master/RefreshParts()
You don't seem to be doing anything with these scancounts, lasercounts, and manipcounts. Why is this here if the max_snack_size modifier is commented out?

2018-02-05 08:24 UTC, Reviire commented on code/game/machinery/kitchen/snackbarmachine.dm
> +/obj/machinery/chem_master/RefreshParts()
It wasn't even named right, I dunno i just got sidetracked and started doing something, then got sidetracked again. It was pointless and I removed it.

2018-02-05 08:50 UTC, Reviire commented
So it seems like everything is working as it should. It's always possible I'm retarded and I missed something big, but I think everything is working. Just need to get that sprite.

2018-02-17 20:22 UTC, Probe1 commented
CL and the PR needs a way better description of what this actually does.  "Way better" isn't descriptive.

2018-02-20 23:27 UTC, Probe1 commented
Reading all these formatting line changes in the middle of a PR that adds content gives me ptsd from  @dylanstrategie coding practices.

2018-02-21 00:29 UTC, Probe1 requested changes
Fix the ? on the machine please.  Otherwise I don't see any issues jumping out at me.

2018-02-21 07:38 UTC, Probe1 submitted a review, later dismissed

2018-02-26 09:08 UTC, Probe1 commented on code/modules/reagents/machinery/chem_master.dm
> +	name = "\improper Chem Master"
Why change this?

2018-02-26 09:09 UTC, Probe1 commented on code/modules/reagents/machinery/chem_master.dm
> +			manipcount += SP.rating
Why change this?

2018-02-26 10:01 UTC, DamianX requested changes

2018-02-26 10:01 UTC, DamianX commented on code/game/machinery/kitchen/snackbarmachine.dm
> +		dat += "<A href='?src=\ref[src];eject=1'>Eject beaker.</A><BR>"
remove this period

2018-02-26 10:01 UTC, DamianX commented on code/game/machinery/kitchen/snackbarmachine.dm
> +					<td class="column1">
Why is this class defined? Why is this even a table in the first place?

2018-02-26 10:01 UTC, DamianX commented on code/modules/reagents/machinery/chem_master.dm
> +		dat += "<A href='?src=\ref[src];ejectbottle=1'>Eject pill bottle.</A><BR>"
delete this period

2018-02-26 10:01 UTC, DamianX commented on code/modules/reagents/machinery/chem_master.dm
> +		dat += "<A href='?src=\ref[src];eject=1'>Eject beaker.</A><BR>"
delete this period

2018-02-26 10:01 UTC, DamianX commented on code/modules/reagents/machinery/chem_master.dm
> +				<table>
why is this a table?

2018-02-26 10:01 UTC, DamianX commented on code/modules/reagents/machinery/chem_master.dm
> -		else if(href_list["main"])
you deleted this, so the "(Back)" button from the "(?)" won't work

2018-02-26 10:01 UTC, DamianX commented on code/modules/reagents/machinery/chem_master.dm
> -					<A href='?src=\ref[src];createpill_multiple=1;createempty=1'>Create empty pills</A><BR>
bring this back, no reason to remove this, especially on the old chem master that you shouldn't be changing anyway

2018-03-09 04:02 UTC, DamianX commented
![image](https://user-images.githubusercontent.com/6307265/37189913-14449c4c-2357-11e8-90c9-c2717050235a.png)

2018-03-09 04:02 UTC, closed without merging

2018-03-09 18:55 UTC, nuklearcellphoneg commented
no pls finish this