fixes unlimited explosion works 2.0: nazi boogaloo
d3athrow/vgstation13 pull request #17335
Opened 2018-02-04 21:46 UTC by jknpj

Same deal as #16111. Doing the same with Vox Armalis just to be sure.

Closes #17334

:cl:
 * bugfix: Fixes Mecha Hitler holocausting the whole server with infinite german explosions.

2018-02-04 22:43 UTC, Intigracy commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	explosion(loc,1,2,3)
won't this just delete the gatling gun you just spawned?

2018-02-05 02:20 UTC, Intigracy requested changes

2018-02-05 02:20 UTC, Intigracy commented on code/modules/mob/living/simple_animal/hostile/human/nazi.dm
> +	explosion(loc,1,2,3)
And now that I think about this, pretty sure this is just going to cause an explosion/spawn in nullspace. Cast `loc` somewhere before the qdel.

2018-02-05 02:21 UTC, Intigracy commented on code/modules/mob/living/simple_animal/vox.dm
>  	explosion(get_turf(loc), -1, -1, 3, 5)
Same here.

2018-02-05 17:57 UTC, Intigracy approved these changes

2018-02-05 17:57 UTC, merged

2018-02-06 10:33 UTC, DeityLink commented
Trying not to laugh out loud at work