[WIP] Enables spiderbot radios + other spiderbot speech fixes
d3athrow/vgstation13 pull request #17446
Opened 2018-02-14 12:03 UTC by Pathid

By the power of copypaste I'm fulfilling anon's request from the thread. This enables spiderbots to use the radio they had inside of them all along. It only gets the common channel. Still trying to figure out how to make their speech appear in the silicon font.

I have concerns about letting ventcrawling tattletales run around all the time so I might make the borg radio have to be installed in them instead of spawning on creation, I don't know yet.

:cl:
* rscadd: Spider-bots have working radios now.

2018-02-14 15:13 UTC, Kurfursten commented
IIRC you want to override get_message_mode to `return MODE_ROBOT`, then to change the speech bubble, override /say to `return ..(message, "R")`

You may need to do some testing on this

2018-02-14 19:12 UTC, Pathid commented
Didn't I already do that? I've got the bubble working but the font is still normal.

Also after rethinking this, the radio did serve a purpose before. It allowed them to listen. And with the fact that they were capable of speaking on intercoms with :i might have given them enough comms capability already.

2018-02-14 19:16 UTC, Pathid commented
Alright, figured it out.

2018-02-16 03:47 UTC, Pathid commented
Wait I can make this better.

2018-02-17 19:16 UTC, jknpj commented
You might want to take a look at #15778

2018-02-18 10:40 UTC, DamianX requested changes

2018-02-18 10:40 UTC, DamianX commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +		for(var/i = 1; i <= lob_range; i++)
use `for(var/i in 1 to lob_range)`

2018-02-18 10:40 UTC, DamianX commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +	to_chat(src, "<span class='notice'>Radio is [radio.listening ? "" : "no longer"] receiving broadcasts.</span>")
this will result in an extra space character that I cannot unsee

2018-02-18 10:40 UTC, DamianX commented
Do you think players reading the changelog will have any clue what the MOB_ROBOTIC flag does?

2018-02-18 10:43 UTC, Probe1 commented
Yeah keep in mind what I said last time.  You don't need to include backend and minor bug fixes for the changelog, and it's best to condense stuff.  Additions with additions instead of a new line for every **related** thing.

2018-02-18 15:03 UTC, DamianX commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +	if(stat)
use `incapacitated()`

2018-02-19 06:02 UTC, DamianX commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +		to_chat(src, "Can't do that while incapacitated or dead.")
Needs a `return` after this

2018-02-19 06:31 UTC, Pathid commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +		to_chat(src, "Can't do that while incapacitated or dead.")
Good spot.

2018-02-19 06:37 UTC, DamianX approved these changes

2018-02-19 06:47 UTC, merged