Alien acid now takes 3 seconds to apply on nuclear bombs with bonus sanity code.
d3athrow/vgstation13 pull request #17482
Opened 2018-02-17 06:48 UTC by Probe1

Resolves https://github.com/vgstation-coders/vgstation13/issues/17438
Celt helped me do most of it so it's his fault if it's broken.  Not that it is I tested it to death.  Thank you for the help Celt.

2018-02-17 07:05 UTC, DamianX commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +	user.visible_message("<span class='alien'>\The [usr] vomits globs of vile stuff all over [O]. It begins to sizzle and melt under the bubbling mess of acid!</span>")
`usr` vs `user`

2018-02-17 07:07 UTC, DamianX commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +		if(!do_after(usr,target,3 SECONDS))
`usr` vs `user`

2018-02-17 07:07 UTC, DamianX commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +			to_chat(usr, "<span class='alien'>You have to stay next to the object to acid it!</span>")
`usr` vs `user`

2018-02-21 08:52 UTC, Probe1 commented
Well I knew it was a bad idea to use githubs built in conflict resolver.  But there I went pressing buttons.

2018-02-21 09:15 UTC, ghost requested changes

2018-02-21 09:15 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
>  	if(O.acidable())
Reeeee remove this line why did you add it back

2018-02-21 09:15 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +  else
And this line rrrreee

2018-02-21 09:15 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
>  		to_chat(user, "<span class='alien'>You cannot dissolve this object.</span>")
And also this one gosh darn it

2018-02-21 09:25 UTC, ghost requested changes

2018-02-21 09:25 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +		if(is_valid_target_to_acid(O,usr))
Usr

2018-02-21 09:25 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
Usr

2018-02-21 09:25 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +	user.visible_message("<span class='alien'>[src] begins to violently twist and contort!</span>", "<span class='alien'>You begin to evolve, stand still for a few moments</span>")
Should be user, not src

2018-02-21 09:34 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +	if(!(spell_flags & INCLUDEUSER) && target == usr)
User

2018-02-21 09:37 UTC, DrCelt commented on code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
> +		if(is_valid_target_to_acid(O,user))
Actually I lied this one is meant to be usr

2018-02-21 09:40 UTC, DrCelt commented
Looks good 👌

2018-02-21 09:48 UTC, Probe1 commented
do_after is running twice and I don't know why.

2018-02-21 10:11 UTC, DamianX commented
Looks like `is_valid_target()` is called by both `channeled_spell()` and `before_cast()`.
https://github.com/vgstation-coders/vgstation13/blob/7bdd3f77cf82e47139ab330a7112b55bd57a569e/code/modules/spells/spell_code.dm#L213-L214

2018-02-23 12:59 UTC, merged