Improving Trader Options
d3athrow/vgstation13 pull request #17484
Opened 2018-02-17 10:32 UTC by Kurfursten

![untitled](https://user-images.githubusercontent.com/9782036/36340109-e11c1b90-139a-11e8-8a40-cd30619be1b3.png)

Mecha graveyard has several mechas you can salvage for parts, but the 2 RIPLEYs and CLARK have been extra beefed up to be sure to drop plenty of goodies. **Important note: the trader shuttle cannot go to the mecha graveyard, only the mining or research shuttle will fit the dock.**

Wonderful Wardrobe can end up getting stuff like thermals, vampire cape, security plasmaman suit, cat morphing mask, or even just 10 random worthless jumpsuits and a maid outfit... and that's just with one generation. It uses the completely unaltered list from Spessmart. This might need more blacklisting or less items, I'll let github help me decide on that. Just remember it is a premium item so it should have a chance for *something* exciting.

🆑 
* Trader Vendor: Replaced box of marauder parts with a destination disk for a mecha graveyard full of wonderful salvageable robotics stuff. Bring your toolbelt and a suit!
* Trader Vendor: Replaced bottle of nanobots, bottle of rezadone, and bottle of peridazon with a box containing all three
* Trader Vendor: Added the Wonderful Wardrobe. It contains 20 random Spessmart approved clothing items.

2018-02-17 18:58 UTC, Probe1 commented
Balance added because thermals.

2018-02-17 20:27 UTC, Kurfursten commented
If people want to discuss this more I can go generate more random closets to give you examples of an average haul.

The chances of getting any specific good thing (e.g.: thermals) are very low but the chances of getting at least one cool/good thing are pretty high.

2018-02-17 20:31 UTC, Probe1 commented
I personally don't have an issue with it or need statistical testing.  Adding traitor items to something still qualifies for a balance label though.

2018-02-18 14:33 UTC, Dacendeth commented
I look foward to a trader opening a wonderful wardrobe and a live face hugger popping out.

2018-02-18 18:22 UTC, Kurfursten commented
That is definitely a possibility. And yet... I feel like it's an acceptable risk for the same reason as stuff like thermals appearing. Buyer beware.

2018-02-18 19:33 UTC, Dacendeth commented
Do you think it would be better if instead of those purple tiles you had the hyperspace tiles that make you get shoved out into space somewhere? Just incase you get trapped there by someone calling the shuttle away?

2018-02-18 19:34 UTC, Kurfursten commented
Oh yeah, we could do that. Seems like a good idea.

2018-02-20 06:40 UTC, Kurfursten commented
What's new?
* Now bordered by transit tiles that kick you out into space if you touch them
* Added an external airlock by where the mining/research shuttle docks so that it doesn't make you depressurize your ship if you left the door open (most people do)

This is ready for merge

2018-02-20 07:07 UTC, MadmanMartian requested changes
transit tiles alone aren't what throw you around and teleport you. Surround the map with /obj/effect/step_trigger/teleporter/random/shuttle_transit to teleport them into deep space, and /obj/effect/step_trigger/thrower for what throws you.

Make the surrounding transit turf border 7 tiles or more around, lest players break their immersions by seeing other dungeons.

2018-02-20 07:13 UTC, MadmanMartian requested changes

2018-02-20 07:13 UTC, MadmanMartian commented on code/game/objects/items/trader.dm
> +	new /obj/item/weapon/reagent_containers/glass/bottle/peridaxon(src)
Call ..()

2018-02-20 07:13 UTC, MadmanMartian commented on code/game/objects/items/trader.dm
> +	var/random_clothes = clothing.Copy()
Call ..()

2018-02-20 08:03 UTC, Kurfursten commented
![untitled](https://user-images.githubusercontent.com/9782036/36413004-2c8a470c-15e2-11e8-8413-ee4525a80808.png)

As you can see from the screenshots
* Hyperspace radius increased
* Hyperspace properly throws you into deep space
* Disk not compatible with Trader ship

2018-02-20 08:50 UTC, MadmanMartian commented
we could do with an opaque spaceturf for spacebound dungeons in the future

2018-02-20 08:51 UTC, MadmanMartian approved these changes

2018-02-21 07:48 UTC, merged