Faction/Role Hud Icons
d3athrow/vgstation13 pull request #17577
Opened 2018-02-23 01:44 UTC by DeityLink

https://cdn.discordapp.com/attachments/343178619192868864/416403883498405889/hudiconsgood.webm

Alright, so it's a bit different from how it used to be. Previously, you'd automatically get a hud icon when you were a certain kind of antag, namely cultist, wizard, nukeop, etc. But now that antagonists have been split between their role and their faction, I judged that since the goal of those icons is to help team antags find each others, it should be controlled by the faction datum. They now have an hud_icons list() that can either remain empty (which means no icons, should you need a faction whose members don't automatically know each others) or have one or more strings matching the icon_states in role_HUD_icons.dmi
When drawing the icons, the faction checks the role's logo_state var. If said var is in hud_icons, it'll be drawn. If not, the first icon in the hud_icons list will be used instead. Useful for factions whose members can have subroles (such has nuke ops and their leaders, or revs and their heads, or later wizard and their apprentices, etc)
Lastly, previously if you were multiple sorts of antags at the same time, you'd see your icons stack, hiding each others. Now, if there are multiple factions using icons in-game, the icons will blink and cycle.

![icons](https://user-images.githubusercontent.com/7573912/36573920-5f57d204-1843-11e8-833b-91f12d78f3a5.gif)

2018-02-24 00:07 UTC, MadmanMartian commented on code/datums/gamemode/factions/faction.dm
> +						to_chat(world,"[hud_icon] pause_before=[offset * HUDICON_BLINKDURATION];pause_after=[HUDICON_BLINKDURATION*(factions_with_icons - 1 - offset)]")
Debug message, please fix.

2018-02-24 00:17 UTC, DeityLink commented on code/datums/gamemode/factions/faction.dm
> +						to_chat(world,"[hud_icon] pause_before=[offset * HUDICON_BLINKDURATION];pause_after=[HUDICON_BLINKDURATION*(factions_with_icons - 1 - offset)]")
AHHHHHHHHH

2018-02-24 01:30 UTC, MadmanMartian requested changes

2018-02-24 01:30 UTC, MadmanMartian commented on code/modules/mob/living/login.dm
> +		if (iscultist(src) || iswizard(src) || isnukeop(src))
Have an IsInFaction check or something, so it's more modular than sticking a macro to see if the person is in 'one of these factions'

And don't have the IsInFaction check just look at every faction macro

2018-02-24 01:30 UTC, MadmanMartian commented on code/datums/gamemode/factions/faction.dm
> +	for (var/datum/faction/F in ticker.mode.factions)
There has got to be a better way that
>Looping through every faction
>Having it call update_hud_icons
>>Within that, it loops through every faction again
>>Then loops through the members of that particular faction 3 times

2018-02-24 10:03 UTC, ShiftyRail commented on code/datums/gamemode/factions/faction.dm
> +	for (var/datum/faction/F in ticker.mode.factions)
Have a list of factions from which you remove src and loop through that.
BYOND just does nothing when you ask to remove an item from a list and the list doesn't contain it.

2018-02-24 10:03 UTC, ShiftyRail commented on code/datums/gamemode/factions/faction.dm
> +					if(R_target.antag && R_target.antag.current)
None of these procs sleep or spawn. What's stopping you from doing it all in one go ?

2018-02-24 19:19 UTC, MadmanMartian approved these changes

2018-02-25 20:10 UTC, FudgePucker commented
This raises an interesting question, if you are a cult member and a rev member, do you kill a head of staff if they are a cult member?
Do you have more loyalty to the revolution or to narsie?

2018-02-25 23:07 UTC, DeityLink commented
It's up to the player to decide

2018-02-25 23:38 UTC, merged