Hacky method of adding pressure differentials causing window blowouts in ZAS
d3athrow/vgstation13 pull request #17653
Opened 2018-02-27 19:23 UTC by d3athrow

http://ss13.moe/uploads/2018-02-27_11-41-34.webm example

~~Behold my shitty coding abilities~~

Need testing and then bugs need to be squished
Values need to be figured out and changed for production

:cl:
 * rscadd: Added a system that causes pressure differences between two zones to potentially connecting windows to take damage until breaking.

2018-02-27 21:11 UTC, Probe1 commented
testmerge to live you say?  without any review?

2018-02-28 00:15 UTC, AutismSpider commented
merge to live i want see all the windows blow out form a tiny fuel fire

2018-02-28 03:27 UTC, ihadtoregisterforthis commented
Or just from nothing.
![ruhroh](https://user-images.githubusercontent.com/13305885/36768452-0530aa9c-1c1e-11e8-8513-2497c6c069ee.png)

Shouldn't this need a remap to go along?

2018-02-28 08:11 UTC, Probe1 commented
probably but lets see if the codes good before all that.

2018-02-28 13:18 UTC, d3athrow commented
Ok listen I'm gonna say it one more time

2018-02-28 13:21 UTC, d3athrow commented on code/game/objects/structures/window.dm
>  	pressure_resistance = 4*ONE_ATMOSPHERE
the values

2018-02-28 13:21 UTC, d3athrow commented on code/game/objects/structures/window.dm
> +	pressure_resistance = 130*ONE_ATMOSPHERE
are low

2018-02-28 13:21 UTC, d3athrow commented on code/game/objects/structures/window.dm
> +	pressure_resistance = 500*ONE_ATMOSPHERE
for testing

2018-02-28 13:21 UTC, d3athrow commented on code/game/objects/structures/window.dm
> +	pressure_resistance = 2500*ONE_ATMOSPHERE
!

2018-02-28 16:08 UTC, DeityLink commented
I love it, but firelocks should be opennable if the pressure/temperature on all sides

<insert pic of those firelocks "saving" people>

2018-02-28 17:38 UTC, CptWad commented
In doing some research on glass materials
glass (regular) has a resistance to vertical forces will resist pressures upwards of 1x10^6 KPa
Temperatures of 500+ C will melt glass completely.
source: http://www.saint-gobain-sekurit.com/glossary/glass-properties

Its rather hard to find information on the pressure resistance on glass but from what I understand glass wont break easy unless directly impacted by a force (bending forces). Glass resists passive pressures easily but will melt against high temperatures. 

So if this was REALISTIC higher grade of glass will have stupid high pressure resistance ultimately but it would be temperature that would decide if glass is destroyed.

2018-02-28 21:54 UTC, FudgePucker commented
Will ref plasma glass have near infinite protection? How will you contain miniature suns?

2018-02-28 23:11 UTC, DrCelt commented
blowout soon, fellow stalker

2018-02-28 23:30 UTC, CptWad commented
I did a fuckload of math
heres some calculations based on glass.
A two inch pane of glass is resistant up to a pressure difference at about 60 kPa
A three and a half inch pane of glass is resistant up to a pressure difference at about 183 kPa
A five inch pane of glass is resistant up to a pressure difference at about 373 kPa

There is not a lot of good information online about this for some reason
this however makes a lot of sense then what I found at first
so really, how thicc are our panes of glass you think? Just a regular one

2018-03-01 04:23 UTC, SonixApache commented
Could just throw in some bogus variables, like `3*ONE_ATMOSPHERE`, to see what works/sticks.

2018-03-02 17:19 UTC, MadmanMartian reviewed
Clean it up (remove the commented out code rather than leaving it in, less random whitespace, stop abusing the horizon it did nothing to deserve this, etc.), it's giving people eye cancer trying to review it.

2018-03-03 06:28 UTC, Cisrox commented
i've wanted this for so long, thank you so much

2018-03-23 18:49 UTC, chesse20 commented
vox and plasmaman buff! Add this Please

2018-04-27 07:03 UTC, DamianX commented
What's the worst that could happen?

2018-04-27 13:52 UTC, d3athrow commented
Everything

2018-04-27 17:12 UTC, MadmanMartian commented
wouldn't it break the windows to the gas miners?

2018-05-01 07:17 UTC, Exxion requested changes
I'm too tired to do a full review right now but I just noticed this. I'll look closer tomorrow

2018-05-01 07:17 UTC, Exxion commented on code/controllers/subsystem/air.dm
> +	var/init_done = 0
There's already a subsystem-level var for this called `initialized`

2018-05-01 07:17 UTC, Exxion commented on code/ZAS/Zone.dm
> +	if(SSair.init_done)
Should be `if(SS_READY(SSair))` to prevent possible (but unlikely) runtimes

2018-05-01 07:17 UTC, Exxion commented on code/ZAS/Zone.dm
> +	if(SSair.init_done)
Same

2018-05-02 23:06 UTC, oatzandhoez commented
Saying this as an atmos tech player, we're going to need to spawn with a supply of plasmaglass or you're going to have a riot on your hands.

2018-06-08 14:40 UTC, DamianX commented
At some point we'll have to decide what to do with this.

2018-06-08 14:42 UTC, MadmanMartian commented
Needs mapping changes and the values bringing back up

2018-06-08 14:44 UTC, d3athrow commented
Just close it, nobody wants it.

On Fri, Jun 8, 2018 at 9:43 AM, MadmanMartian <notifications@github.com>
wrote:

> Needs mapping changes and the values bringing back up
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/17653#issuecomment-395782692>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AArJgwIaeTqe7ZVwFD7bh92iDxRQL8yqks5t6o1_gaJpZM4SVgDX>
> .
>

2018-06-08 14:45 UTC, DamianX commented
15 thumbs pointing up and no thumbs pointing down?

2018-06-08 14:53 UTC, MadmanMartian commented
Gib blowout

2018-06-08 15:13 UTC, d3athrow commented
@DamianX 
1. Emojiacracy isn't real
2. This would add about 5 minutes to the startup time as it has to build the touching zones list that involve windows.
3. People in the thread weren't amused by it.

2018-06-09 21:59 UTC, Exxion commented
Pomf can obviously reopen this if he wants

I think that a less-hacky method was already planned in the XGM PR, though. Not sure what it was.
I can think of one possibility, which is definitely still hacky, but would perform better and also allow for multi-tile objects to not fuck up around windows

2018-06-09 21:59 UTC, closed without merging

2018-06-10 18:53 UTC, ihadtoregisterforthis commented
Flew too close to the sun and its wings exploded from the pressure increase