Runtime hunting: Chem mask on the floor edition
d3athrow/vgstation13 pull request #17791
Opened 2018-03-09 13:01 UTC by DamianX

```
x10 chemmask.dm,290: undefined variable /turf/simulated/shuttle/floor/var/back
  proc name: pack check (/obj/item/clothing/mask/chemmask/proc/pack_check)
  src: the chemical mask (/obj/item/clothing/mask/chemmask)
  src.loc: the floor (147,93,2) (/turf/simulated/shuttle/floor)
  call stack:
  the chemical mask (/obj/item/clothing/mask/chemmask): pack check(the floor (147,93,2) (/turf/simulated/shuttle/floor))
  the chemical mask (/obj/item/clothing/mask/chemmask): process()
  Objects (/datum/subsystem/obj): fire(0)
  Objects (/datum/subsystem/obj): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing()
```

2018-03-09 14:46 UTC, jknpj commented
this is fucking hilarious

2018-03-09 15:16 UTC, Probe1 commented
😨

2018-03-09 17:04 UTC, Shadowmech88 requested changes

2018-03-09 17:04 UTC, Shadowmech88 commented on code/modules/clothing/masks/chemmask.dm
>  		mask_shutdown(user)
The code would still get here if the `istype(M)` fails, and proceed to attempt to call `update_inv_wear_mask()` on a non-mob in `mask_shutdown()`. An `istype()` check should be added to that proc as well.

2018-03-09 22:05 UTC, DamianX commented
Tested it too, for good measure.

2018-03-10 00:14 UTC, Shadowmech88 approved these changes

2018-03-10 16:13 UTC, merged