Fixes atmos connector continuity during shuttle transit
d3athrow/vgstation13 pull request #18051
Opened 2018-04-09 05:55 UTC by Pathid

Closes #18050

:cl:
* bugfix: Portable atmos devices hooked to connectors aboard shuttles will no longer disconnect on departure and arrival.

2018-04-09 07:50 UTC, DamianX commented
There must be a better way

2018-04-09 08:31 UTC, Pathid commented
Probably.

2018-04-09 10:10 UTC, DamianX commented on code/ATMOSPHERICS/components/unary/portables_connector.dm
> +			if(AM.loc != src.loc)
AM may be null now
src may be null now
connected_device may be null now

2018-04-09 11:14 UTC, DamianX commented
Yeah, that's what I was thinking, if you feel like it.

2018-04-13 01:03 UTC, PJB3005 commented
Could also move it to atom locking and just tell dimensional push to fuck off.

2018-04-20 15:12 UTC, MadmanMartian requested changes
There has to be a better way

2018-05-10 01:20 UTC, DamianX commented
better way when?

2018-05-26 12:51 UTC, closed without merging