Allows radiation collectors to pick up rads from glowing ghouls
d3athrow/vgstation13 pull request #18124
Opened 2018-04-20 11:58 UTC by unid15

TODO:
- add more comments to emit_harvestable_radiation() - like which units of power are used etc..
- do the same for other radiation sources

:cl:
 * rscadd: Radiation collectors are now affected by glowing ghouls

2018-04-20 17:35 UTC, spoonylove commented
Does this mean geneticist can actually help make an engine for the station?

2018-04-21 00:38 UTC, MadmanMartian requested changes

2018-04-21 00:38 UTC, MadmanMartian commented on code/game/dna/genes/goon_disabilities.dm
> +		L.apply_radiation(5, RAD_INTERNAL)
>RAD_INTERNAL

Why would they be receiving radiation from an internal source?

Use RAD_EXTERNAL so they can protect themselves using radioactive protection gear, and know if it's happening with the radiation detection badges.

2018-04-26 20:04 UTC, MadmanMartian approved these changes

2018-04-28 07:43 UTC, IzayaChan commented
I want to see a station powered by tards with tourettes

2018-04-29 21:58 UTC, merged