Ai can ping
d3athrow/vgstation13 pull request #18191
Opened 2018-04-29 21:38 UTC by PublicEnemyMaiPai

closes##18180
lets AI Buzz Ping Beep Halt and Law

:cl:
 * rscadd: AI can now Beep Ping Buzz Halt and Law

2018-04-29 21:39 UTC, PublicEnemyMaiPai commented
plz tell me i didnt fuck it up again lol

2018-04-29 21:57 UTC, jknpj commented on code/modules/mob/living/silicon/ai/emote.dm
> +		if("law")
You're not the law, pal.

2018-04-29 21:57 UTC, jknpj commented on code/modules/mob/living/silicon/ai/emote.dm
> +		if("halt")
ditto

2018-04-29 21:59 UTC, PublicEnemyMaiPai commented
well i couldnt have it check for robocop, otherwise its checking for being a secborg, and who am I to deny the malf its right to tell its attackers it is the law and they should halt

2018-04-29 22:24 UTC, DamianX requested changes

2018-04-29 22:24 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(get_turf(src), 'sound/machines/twobeep.ogg', 50, 0)
Change `get_turf(src)` -> `src`

2018-04-29 22:24 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(get_turf(src), 'sound/machines/ping.ogg', 50, 0)
Change `get_turf(src)` -> `src`

2018-04-29 22:24 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(get_turf(src), 'sound/machines/buzz-sigh.ogg', 50, 0)
Change `get_turf(src)` -> `src`

2018-04-29 22:24 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(get_turf(src), 'sound/voice/biamthelaw.ogg', 50, 0)
Change `get_turf(src)` -> `src`

2018-04-29 22:24 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(get_turf(src), 'sound/voice/halt.ogg', 50, 0)
Change `get_turf(src)` -> `src`

2018-04-29 22:34 UTC, DamianX requested changes

2018-04-29 22:34 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(src), 'sound/machines/buzz-sigh.ogg', 50, 0)
remove the first `)` after `src`

2018-04-29 22:34 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(src), 'sound/machines/ping.ogg', 50, 0)
remove the first `)` after `src`

2018-04-29 22:34 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(src), 'sound/machines/twobeep.ogg', 50, 0)
remove the first `)` after `src`

2018-04-29 22:34 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(src), 'sound/voice/halt.ogg', 50, 0)
remove the first `)` after `src`

2018-04-29 22:34 UTC, DamianX commented on code/modules/mob/living/silicon/ai/emote.dm
> +			playsound(src), 'sound/voice/biamthelaw.ogg', 50, 0)
remove the first `)` after `src`

2018-04-30 18:04 UTC, DamianX commented
I second jk's opinion: `law` and `halt` seem out of place.

2018-04-30 18:31 UTC, PublicEnemyMaiPai commented
I suppose i can make the correction requested when i get home then.

2018-05-01 18:19 UTC, DamianX approved these changes

2018-05-03 00:46 UTC, merged