Balances the masks of transmogriphication
d3athrow/vgstation13 pull request #18205
Opened 2018-05-02 15:21 UTC by MadmanMartian

Masks take 5 seconds to put on.

Can no longer become boss mobs through the amorphous mask.

:cl:
* tweak: The magic of the masks of morphing falters, they are no longer as effective as they once were.

2018-05-02 15:23 UTC, Fruktlimpa commented
Upset Xenoarch exploiters in 3..2..1

2018-05-02 15:34 UTC, Shadowmech88 commented
If this is because of people dying as their mob, then immediately taking the mask off and putting it back on again to re-fill its health, that could be fixed by just re-opening #14599.

2018-05-02 15:37 UTC, MadmanMartian commented
It was more of a pre-warning that the nerd is about to become mecha hitler in a crowded bar

2018-05-02 15:40 UTC, Shadowmech88 commented
What about tying the time necessary to the health of the mob in the mask somehow? 5 seconds seems like a long time to wait every time you want to turn into a corgi or something similarly weak.

2018-05-02 15:57 UTC, jknpj submitted a review, later dismissed

2018-05-02 15:57 UTC, jknpj commented on code/modules/clothing/masks/transmog.dm
> +	target_type = pick(existing_typesof(/mob/living/simple_animal) - existing_typesof(/mob/living/simple_animal/hostile/humanoid) - typesof(/mob/living/simple_animal/hostile/retaliate/cockatrice) - type
remove the manual cockatrice list and you might as well use the bad mob list

2018-05-02 16:15 UTC, Blithering commented
Maybe have dying when transformed drain the mask of power, giving it a cooldown before it can be put back on?

2018-05-02 16:30 UTC, PublicEnemyMaiPai commented
What about removing the mask giving the user a seizure?

2018-05-02 17:10 UTC, Shadowmech88 commented
Once #18206 is merged, dying while transformed will kill you for real.
Unless you think it should not do that, but in that case you should say so there.

2018-05-02 18:06 UTC, ShiftyRail commented on code/modules/clothing/masks/transmog.dm
> +	if(do_after(M, src, 50))
5 SECONDS reads better than 50 (deciseconds) - at least in my opinion.

2018-05-03 02:40 UTC, Blithering commented
@Shadowmech88  Seems fair, so long as the mobs that tend to immediately die have been weeded out of the lists

2018-05-03 21:42 UTC, iFlashYou commented
More science nerfs...

2018-05-07 19:33 UTC, jknpj requested changes

2018-05-07 19:33 UTC, jknpj commented on code/modules/clothing/masks/transmog.dm
> +	target_type = pick(existing_typesof(/mob/living/simple_animal) - existing_typesof(/mob/living/simple_animal/hostile/humanoid) - typesof(/mob/living/simple_animal/hostile/giant_spider/hunter/dead) -
ackshually i forgot blacklisted_mobs is a simple parent list, you'll need to use existing_typesof() on it

2018-05-26 12:55 UTC, DamianX commented
when

2018-06-05 10:31 UTC, Pathid commented
Five seconds do_after for putting it on is pretty anti-fun. Why not have it on the revert instead and add a cooldown to that so they're stuck as the animal for a while? Since #18206 got merged there's risk/reward there.

2018-06-24 20:08 UTC, DamianX commented
5 seconds seems harsh but I don't like them doing it instantly either. Let's see how it goes, might tone it down at a later time.

2018-06-24 20:08 UTC, merged