Plasmamen Fire Sprite Bug
d3athrow/vgstation13 pull request #18210
Opened 2018-05-03 22:20 UTC by PublicEnemyMaiPai

fixes #18196
:cl:
 * rscadd: Plasmamen keep their snowflake fire sprite after cloning

2018-05-03 22:24 UTC, PublicEnemyMaiPai commented
oh great what did i do wrong today?

2018-05-04 00:19 UTC, MadmanMartian requested changes

2018-05-04 00:19 UTC, MadmanMartian commented on code/modules/medical/cloning.dm
> +			if(isplasmaman(H))
I didn't notice before, but this is in the wrong place.

Put this in the growClone proc so it only sets it once.

2018-05-04 02:12 UTC, PublicEnemyMaiPai commented on code/modules/medical/cloning.dm
> +			if(isplasmaman(H))
alrighty my bad, ill do this tomorrow

2018-05-04 12:31 UTC, MadmanMartian requested changes

2018-05-04 12:31 UTC, MadmanMartian commented on code/modules/medical/cloning.dm
> +					if(isplasmaman(H))
There isn't a human reference at this point. Put it somewhere below line 230

2018-05-04 19:08 UTC, MadmanMartian commented on code/modules/medical/cloning.dm
> +	H.fire_sprite = "Plasmaman"
Gotta tab this one across so it's under the if conditional

2018-05-05 14:41 UTC, MadmanMartian approved these changes

2018-05-05 14:41 UTC, merged