while hallucinating, chance your coworkers may look like a hostile mob
d3athrow/vgstation13 pull request #18423
Opened 2018-06-04 14:33 UTC by MadmanMartian

2018-06-04 14:53 UTC, unid15 commented on code/modules/flufftext/Hallucination.dm
> +				var/image/horror = image(initial(random_mob.icon), initial(random_mob.icon_state))
Copy appearance by doing horror.appearance = initial(random_mob.appearance) instead

2018-06-08 14:38 UTC, DamianX requested changes
See unid's recommendation

2018-06-24 04:57 UTC, Killette2 commented
(kills coworker on purpose knowing about this feature)
hehe oops I was hallucinating! my character is crazy!
Seems like an administration nightmare

2018-06-24 05:50 UTC, Pathid commented
That's just good roleplaying. 

Jokes aside, this feature could definitely use logging for when and who is being disguised. Otherwise you get a situation where you can never act on it on that 1/100 chance it does happen because there's no reason for the admins to believe you're not just a shitter.

2018-06-24 11:35 UTC, Killette2 commented
What if it is logged that you are hallucinating, that still doesn't solve the following issue. The player can chose to attack the person they're hallucinating, fully knowing that it's a hallucination but doing it because the window for valids is open. Sure it's "roleplay" but it's a shitty reason to do serious possible harm to someone.

2018-06-24 19:59 UTC, merged