Beekeeping 3.6
d3athrow/vgstation13 pull request #18592
Opened 2018-06-22 21:41 UTC by DeityLink

Fixes #18587

![image](https://user-images.githubusercontent.com/7573912/41800072-392a7c6e-7674-11e8-9398-607d390679c3.png)

![image](https://user-images.githubusercontent.com/7573912/41800094-4b9b2182-7674-11e8-97f5-77c2de8e3a1e.png)

I've done some testing to squash the most obvious bugs, but as always I'm expecting you guys to break my stuff. Have some fun.

:cl:
* experiment: BEEKEEPING 3.6 - I'm back again baby
* tweak: You no longer have to land the extinguisher spray right onto a bee swarm to calm them down. Calming bees has never been easier!
* tweak: Bees no longer remain angry forever! If they can't find a target for an extended period of time, they'll calm down. This doesn't apply to angry bee infestations.
* tweak: When an empty apiary is available, no more than one queen will swarm at once to populate it.
* rscadd: Homeless bees will die after about 10 minutes if left alone. Except queen bees, who'll try to recruit homeless workers to build colony. Their swarms will target empty apiaries in priority, but if they can't find any, they'll build their own from scratch! Each species has their own wild hive.
* rscadd: Wild hives work like normal ones, except that you cannot add queen bee packets or beezeez, or empty bees into them.
* rscadd: Added Hornets. They have a chance to spawn from infestation events, and traitor botanists may purchase Hornet Queen Packets for 2 TC each. Hornets have a chance to deal partial damage through protection, so handle carefully!
* tweak: lots of back-end optimization.

2018-06-22 22:31 UTC, Exxion commented
It looks like `empty_beehive()` still doesn't add the removed bees to `bees_outside_hive`

2018-06-22 23:30 UTC, DeityLink commented
empty_beehive() is only used in instances where the hive is getting destroyed, so doing so would be kinda obsolete.

2018-06-23 00:00 UTC, Exxion commented
No, it would not. That is the list the beehive uses to null the references to itself on the bees. Not adding them means the beehive fails to get GCed and causes the bug I mentioned in #18587.
It would also work if you nulled their `home` directly in `empty_beehive()`, but you have to do one or the other.

2018-06-23 00:08 UTC, DeityLink commented
Well I double checked but the bees created by empty_beehive() are homeless, their home isn't set (which is the arg following loc on New() ).

    var/mob/living/simple_animal/bee/lastBees = getFromPool(/mob/living/simple_animal/bee,get_turf(src))

2018-06-23 00:42 UTC, Exxion commented
The mob's home isn't set, but the individual datums still are, from what I can see. But I'll check this version once I'm done with what I'm working on

2018-06-23 10:36 UTC, DeityLink commented
Guess I was really tired, thank you for catching that. Bee datums created by empty_beehive() will no longer have a home.

2018-06-24 12:20 UTC, MadmanMartian requested changes
Just a few grammar problems

2018-06-24 12:20 UTC, MadmanMartian commented on code/datums/uplink_item.dm
> +	desc = "Place her into an apiary tray, add a few packs of BeezEez, then lay it inside your nemesis' office. Surprise guarranted. Protective gear won't be enough to shield you reliably from those."
guaranteed, not guarranted.

These, not those.

2018-06-24 12:27 UTC, DeityLink commented on code/datums/uplink_item.dm
> +	desc = "Place her into an apiary tray, add a few packs of BeezEez, then lay it inside your nemesis' office. Surprise guarranted. Protective gear won't be enough to shield you reliably from those."
fix'd

2018-06-24 12:31 UTC, MadmanMartian approved these changes

2018-06-25 12:06 UTC, merged