adds anvils
d3athrow/vgstation13 pull request #18600
Opened 2018-06-24 00:54 UTC by MadmanMartian

- they go clang if thrown at somebody
 - Need to be strong to pull them, need to be strong and hulkster to pick it up to throw it
 - can be used for crafting
 - misc bug fixes

2018-06-24 00:59 UTC, DamianX commented on code/game/objects/items/anvil.dm
> +		M.visible_message("<span class = 'warning'>\The [M] attempts to pick up \the [src].</span>")
\>can_pickup
\>contains a `visible_message`
i dislike this

2018-06-24 03:00 UTC, Unknown-as-Captain commented
Check that it can't be moved by a light breeze

2018-06-24 11:23 UTC, MadmanMartian commented
It takes a bit of oomph to push it now. Can't move it via locker as it's a dense object.

2018-06-24 16:20 UTC, unid15 requested changes

2018-06-24 16:20 UTC, unid15 commented on code/game/objects/items/anvil.dm
> +	if((M_HULK in M.mutations) && (M_STRONG in M.mutations))
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/helper_procs.dm#L31

Use ``M.get_strength()`` for all checks in this file

2018-06-25 11:43 UTC, jknpj commented on code/game/objects/items/stacks/stack_recipes.dm
> +		new/datum/stack_recipe/dorf("training sword", /obj/item/weapon/melee/training_sword,	4, time = 12,	on_floor = 1, inherit_material = TRUE),
indent

2018-06-25 21:47 UTC, MadmanMartian commented
Removed it just being a proximity thing for crafting - We'll not go the cheap and casual way with this.

Also can't just magic one out of thin air using plasteel and metal, you'll have to order one for the time being.

2018-06-25 22:09 UTC, MusgardTiger commented
Can't we add it in a corner in some maintenance tunnel?

2018-06-26 18:18 UTC, merged

2018-08-02 04:14 UTC, SonixApache commented
I can't figure it out. Does this actually do anything?

2018-08-02 05:48 UTC, MadmanMartian commented
No