Strange rocks are now revealed using the 1cm brush
d3athrow/vgstation13 pull request #18903
Opened 2018-07-20 17:49 UTC by boy2mantwicethefam

Shoutout to @DrSnips for holding my hand through the whole process and for telling me to do it
You no longer need to carry a welder with you everywhere. 100% untested like literally almost every PR who the fuck goes through all the waiting for it to compile and boot a client-side server for every single change? Yell at Lummox to unfuck his compiling or something don't ask me
:cl: Boy2Man
 * rscadd: You can use a 1cm brush to reveal strange rocks.
 * rscdel: You can no longer use a welder to reveal strange rocks.

2018-07-20 17:53 UTC, SonixApache commented
>🆑 Boy2Man

you have to go back

2018-07-20 17:56 UTC, aceedex commented
>he doesnt compule using the test map
Shameful

2018-07-20 17:56 UTC, boy2mantwicethefam commented
@SonixApache Fixed and upvoted :^)

2018-07-20 18:15 UTC, MadmanMartian requested changes
some nice changes, does lock artifacts strictly behind xenoarch though.

2018-07-20 18:15 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +			for(var/mob/M in viewers(world.view, user))
Use visible_message instead.

2018-07-20 18:15 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +			for(var/mob/M in viewers(world.view, user))
Use visible_message instead

2018-07-20 18:15 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +		return
Redundant return. Delete this.

2018-07-20 18:57 UTC, boy2mantwicethefam commented
Done done and done

2018-07-20 19:10 UTC, ShiftyRail commented
You need to replace the whole block
```dm
for(var/mob/M in viewers(world.view, user))
     M.show_message(...)
```
Becomes
```dm
M.visible_message(...)
```

2018-07-20 19:12 UTC, MadmanMartian requested changes

2018-07-20 19:12 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +				M.visible_message("<span class='info'>[src] reveals nothing!</span>",1)
Noooo.

Instead of the for(var/mob/M ... block, just put visible_message("<span class='info'[whatever the message is]</span>")

2018-07-20 19:44 UTC, Inorien commented
since when were strange rocks not xenoarch locked anyway? on the off-chance you excavate a rock AND.are carrying a welder, this fucks you

this means i no longer have to research and carry a gatling welder to make xenoarch possible. massive QoL and massive support

2018-07-20 20:17 UTC, DamianX commented
I assume this might be somewhat explained on the wiki so

2018-07-20 20:34 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +				M.visible_message("<span class='info'>[src] is brushed away revealing [inside].</span>",1)
Tab this back one.

2018-07-20 20:35 UTC, MadmanMartian submitted a review, later dismissed

2018-07-20 20:35 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +				M.visible_message("<span class='info'>[src] is brushed away revealing [inside].</span>",1)
Hell, put this above the inside = null as well, so it actually shows what was revealed. Odd that it isn't a reported bug.

2018-07-20 20:53 UTC, Pathid commented
> this means i no longer have to research and carry a gatling welder to make xenoarch not a pain in the ass.

Or even.. carrying welding fuel in a large beaker or two.

2018-07-20 22:23 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +				visible_message("<span class='info'>[src] is brushed away revealing [inside].</span>",1)
It's still going to read "strange rock is brushed away revealing  "

2018-07-20 22:35 UTC, DamianX requested changes

2018-07-20 22:35 UTC, DamianX commented on code/modules/research/xenoarchaeology/finds/finds.dm
>  				visible_message("<span class='info'>[src] is brushed away revealing [inside].</span>",1)
You still need to dedent this line and remove that trailing `1`

2018-07-20 22:35 UTC, DamianX commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +			visible_message("<span class='info'>[src] reveals nothing!</span>",1)
another trailing 1

2018-07-20 23:22 UTC, DamianX commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +			visible_message("<span class='info'>\The [src] reveals nothing!</span>",1)
dude literally just delete this `,1` what the fuck

2018-07-20 23:31 UTC, DamianX approved these changes

2018-07-23 11:34 UTC, Sooose commented
There is absolutely no need to carry a welder at all for xenoarch if you can do arithmetic and know how to search for smalls properly.

2018-07-25 03:17 UTC, Blithering commented
What about the rocks that required acid to open, are they still the same or is the brush guaranteed to work?

2018-07-25 14:07 UTC, MadmanMartian commented on code/modules/research/xenoarchaeology/finds/finds.dm
> +			visible_message("<span class='info'>\The [src] is brushed away revealing \The [inside].</span>")
visible_message("<span class='info'>\The [src] is brushed away revealing \the [inside].</span>")

2018-07-26 21:30 UTC, merged