Nightvision Color Resets on Login
d3athrow/vgstation13 pull request #18975
Opened 2018-07-26 14:49 UTC by flagzzzz

Fixes #18533 and #18967. It should be robust enough to work for any new scanners that are added in the future. The implementation is peculiar since the ```update_colour()``` that is called in ```/mob/Login()``` has a 50 tick delay before the color actually changes.

:cl:
* bugfix: Nightvision goggles reapply color on login

2018-07-26 17:01 UTC, DamianX requested changes
Nope. Not getting away with that sleep. Also not getting away with snowflaking the glasses check.
Make `get_screen_colour` somehow return the color matrix from equipped items, instead.
Also don't use things like `get_item_by_slot(slot_glasses).on` because it's the equivalent of using the `:` operator, which is literally hitler

2018-07-27 17:33 UTC, DamianX requested changes

2018-07-27 17:33 UTC, DamianX commented on code/modules/mob/mob_helpers.dm
> +	if(!difference.len || !istype(difference))
I assume this is nonsensical celt code aka not your fault but either `!difference` or `!istype(difference)` can/should be removed

2018-07-27 17:33 UTC, DamianX commented on code/modules/mob/mob_helpers.dm
> +	else if(get_item_by_slot(slot_glasses) && istype(get_item_by_slot(slot_glasses), /obj/item/clothing/glasses/scanner))
don't call get_item_by_slot 3 times.
use `is_wearing_item` with the appropriate parameters and store the result in a variable, run your checks on that

2018-07-27 20:21 UTC, DamianX commented on code/modules/mob/mob_helpers.dm
> +	var/obj/item/clothing/glasses/scanner/S = is_wearing_item(slot_glasses)
you need to specify the type you're looking for to `is_wearing_item` or this will runtime for `glasses` that are not `scanner`s

2018-07-27 20:24 UTC, DamianX commented on code/modules/mob/mob_helpers.dm
> +	var/obj/item/clothing/glasses/scanner/S = is_wearing_item(/obj/item/clothing/glasses/scanner)
aaand you also need to pass the slot

2018-07-27 20:27 UTC, flagzzzz commented on code/modules/mob/mob_helpers.dm
> +	var/obj/item/clothing/glasses/scanner/S = is_wearing_item(/obj/item/clothing/glasses/scanner)
It works either way from my testing, but I'll add it in for robustness. Thanks for your patience with my brainletism.

2018-07-28 07:06 UTC, DamianX commented
Great. Does it work?

2018-07-28 13:59 UTC, flagzzzz commented
Github doesn't let me upload webms so I posted it on discord https://cdn.discordapp.com/attachments/239823463802470400/472763612679766017/nightvisionfix.webm

2018-07-28 16:36 UTC, DamianX approved these changes
Further improvements could be making the scanners' equip/unequip procs call update_colour to reduce code duplication but this is good.

2018-07-28 16:36 UTC, merged