Escape pod shuttlification
d3athrow/vgstation13 pull request #19359
Opened 2018-08-16 01:55 UTC by MadmanMartian

Shuttlifiy escape pods, rather than having them be an area that teleports around in their own weird way.

Tested. Pods work through the shuttle panel and during natural escape shuttle movement.

2018-08-16 03:36 UTC, MadmanMartian commented
give me my map render, bot!

2018-08-16 07:35 UTC, DamianX commented on code/controllers/shuttle_controller.dm
> +	/*
delete this whole block?

2018-08-16 07:35 UTC, DamianX reviewed
>using `global` for global variables
>`proc/` instead of `/proc/`
absolutely disgusting

2018-08-16 09:24 UTC, DamianX commented
oh and let's not kill this with conflicts

2018-08-16 12:37 UTC, MadmanMartian commented
woo!

2018-08-16 13:17 UTC, MadmanMartian commented
Escaping via escape pod will need reworking. Now I remember why I needed that is_on_shuttle check

2018-08-17 11:40 UTC, DamianX commented on code/game/gamemodes/objective.dm
> +		if(player.stat == 2) //They are dead
`2` -> `DEAD`

2018-08-17 11:40 UTC, DamianX commented on code/game/gamemodes/objective.dm
> +		if(player.stat == 2) //Do not suffer the human to live
`2` -> `DEAD`

2018-08-18 01:37 UTC, Kurfursten commented
Finish this so I can get packed priority

2018-08-18 09:03 UTC, DamianX requested changes

2018-08-18 09:03 UTC, DamianX commented on code/game/shuttles/emergency.dm
> +/datum/shuttle/escae/pod/one/name = "Escape pod 1"
escae?

2018-08-18 09:03 UTC, DamianX commented on code/game/shuttles/emergency.dm
> +/datum/shuttle/escae/pod/two/name = "Escape pod 2"
escae?

2018-08-18 09:03 UTC, DamianX commented on code/game/shuttles/emergency.dm
> +/datum/shuttle/escae/pod/three/name = "Escape pod 3"
escae?

2018-08-18 09:03 UTC, DamianX commented on code/game/shuttles/emergency.dm
> +/datum/shuttle/escae/pod/four/name = "Escape pod 4"
escae?

2018-08-18 09:03 UTC, DamianX commented on code/game/shuttles/emergency.dm
> +/datum/shuttle/escae/pod/five/name = "Escape pod 5"
escae?

2018-08-19 10:34 UTC, merged