Enables and facilitates wide screen spessmen
d3athrow/vgstation13 pull request #19693
Opened 2018-09-17 13:29 UTC by d3athrow

I'm sure i fucked up somewhere or forgot something
:cl:
 * rscadd: Widescreen spacemen

2018-09-17 15:39 UTC, Exxion commented
New powergaming strat: Ambush from above
Also, how does this interact with `client.dir`? Not that anything else in the codebase plays nice with it either

2018-09-17 15:47 UTC, d3athrow commented
`Also, how does this interact with client.dir? Not that anything else in the codebase plays nice with it either`
It is not accounted for, does anything even set client.dir other than admin abuse variable editing mid round?

2018-09-17 15:53 UTC, Exxion commented
Mindbreaker/Spiritbreaker

2018-09-17 15:54 UTC, DeityLink commented
I was also pondering whether the Confusion rune in Cult 3.0 could mess with it.

2018-09-17 15:59 UTC, d3athrow commented
I just searched for client.dir in the codebase and got no hits 🤔

2018-09-17 16:04 UTC, Exxion commented
https://github.com/vgstation-coders/vgstation13/blob/80f35b7d06c1dab7bb9ff18777c95874b968addd/code/modules/flufftext/Hallucination.dm#L346

2018-09-17 19:33 UTC, jknpj commented on code/game/objects/items/robot/robot_items/robot_binoculars.dm
> +				C.changeView("[view[1]+8]x[view[2]+8]")
![image](https://user-images.githubusercontent.com/17928298/45645609-60b36e00-ba97-11e8-9a31-9b52bfe8ab10.png)

Something really weird going on

2018-09-17 20:19 UTC, d3athrow commented
lmao didn't know that label would do that, i just wanted to meme

2018-09-17 21:09 UTC, d3athrow reviewed
@jknpj Should be fixed with https://github.com/vgstation-coders/vgstation13/pull/19693/files#diff-2aec593799a15c879d8f95f7276b689aR1802 commented out.

2018-09-18 06:13 UTC, Durgen commented
does anyone else think this is a bad idea?

2018-09-18 12:02 UTC, DeityLink commented
I'd like to see it for myself at least once.

2018-09-18 13:13 UTC, jknpj commented
Looks good, but since i've only been compiling test tiny i don't know how the splash screens look

2018-09-18 17:05 UTC, Exxion commented
@Durgen Yes, but I too would like to see it anyway

2018-09-18 17:06 UTC, d3athrow commented
What is the worst that can happen?

2018-09-18 17:19 UTC, Exxion commented
Pretty much everything in the game expects a square view, and being able to see farther along one axis just because screens are wider than they are tall is weird
But I didn't say we shouldn't try it

2018-09-18 20:21 UTC, Durgen commented
@d3athrow giving players with widescreen monitors a significant advantage over those without them and changing the timeless square aesthetic

2018-09-18 20:24 UTC, DeityLink commented
Basically what @Durgen said. I'd like to see it once just to be sure it's a bad idea but I'd like it reverted eventually. Plus that means less space for the chat.

2018-09-18 20:29 UTC, d3athrow commented
@Durgen Who doesn't have a 16:9/16:10 monitor by now?
@DeityLink If you want to see what its like just test it locally, don't +1 a PR you know you already want to revert later.

2018-09-18 21:25 UTC, Durgen commented
@d3athrow people who have something like 21:9 or third world frens with 4:3. Regardless, it would be a major change to the aesthetic and gameplay of spess.

2018-09-18 21:25 UTC, Hugh-G-Rection commented
Tie the ability to an in-game item and this would be a great addition. Captain starts with it. With a spare one on his desk. For reasons.

2018-09-20 16:29 UTC, CthulhuOnIce commented
This seems pretty interesting tbh, widescreen has worked on other servers. 
Maybe make a verb/preference that toggles between the two modes. (Widescreen and non-widescreen)

2018-09-24 14:25 UTC, Dacendeth commented
wont this look horrible with blindness overlays, that stuff already messes up when you have the eyesight genetic power active?

2018-10-30 10:46 UTC, DamianX commented
I resized my window to make it look like this:
![image](https://user-images.githubusercontent.com/6307265/47712932-4e515600-dc39-11e8-9593-17ef5f67fccf.png)

Is this how I'm supposed to be using it? Why is it not the default, then?

2018-10-30 10:48 UTC, DamianX commented
Full-screen overlays need to be adjusted
![image](https://user-images.githubusercontent.com/6307265/47713128-c586ea00-dc39-11e8-8a53-cb4a4dbf3cb4.png)

2018-10-30 11:05 UTC, DamianX commented
The main screen now shows space to the side:
![image](https://user-images.githubusercontent.com/6307265/47713817-7a6dd680-dc3b-11e8-8220-ed226e94c108.png)

xenos have this thing in the middle of the screen:
![image](https://user-images.githubusercontent.com/6307265/47713919-b3a64680-dc3b-11e8-882f-cbb8a03a5c1c.png)

tooltips appear in a completely wrong position:
![image](https://user-images.githubusercontent.com/6307265/47713953-d0db1500-dc3b-11e8-82b3-44534f8b42b0.png)

2018-12-22 10:50 UTC, Intigracy requested changes
Conflicts as well as the above images.

2019-02-05 21:39 UTC, closed without merging