Exporting some Dynamic Mode stats
d3athrow/vgstation13 pull request #19845
Opened 2018-09-28 04:05 UTC by DeityLink

And fixing a dumb bug

2018-09-28 17:49 UTC, gbasood requested changes
Overall looks sound, although the stat code is scattered throughout a lot
Remove the commented code I pointed out

Important questions:
 - Did you test this?
 - Do you have an example of the JSON file that would be exported at round end? Because I, or whoever else makes the stats server process the resulting file, would want that as reference for when they write the processor code on the web server side.

2018-09-28 17:49 UTC, gbasood commented on code/datums/statistics/stat_helpers.dm
> -			if(M.special_role == "Cultist")
This won't ever apply again so you can just remove the commented-out cultist check

2018-09-28 17:49 UTC, gbasood commented on code/datums/statistics/statcollection.dm
> +	//to_chat(world,jsonout)
remove this commented code

2018-09-28 17:49 UTC, gbasood commented on code/datums/gamemode/dynamic/dynamic.dm
> +				message_admins("DYNAMIC MODE: [drafted_rules.len] elligible rulesets.")
\>\>\>\>UNATOMIC
don't actually care just jokes

2018-09-29 20:35 UTC, DeityLink commented
@gbasood 
![image](https://user-images.githubusercontent.com/7573912/46250294-df18f400-c437-11e8-993c-0924a111c3d3.png)
1. yep the above pic was the resulting json code pasted into http://jsonviewer.stack.hu/
2. I'll send you on Discord

2018-09-29 20:41 UTC, DeityLink commented
So basically the idea is to have all 5 population levels stacked on the same graph, and a vertical red line or something to mark successful_injections

2018-10-01 23:26 UTC, gbasood commented
Okay so:
1. For `pop_levels` objects, the format should be more like:
 - `dynamic_stats` top object, like it already is
 - array of objects instead of objects directly on the `pop_levels` object
 - The pop_level objects should have named variables rather than being an array.

Same for threat levels and successful injections. Array of objects with named variables.

Example:
```json
{
  "dynamic_stats": {
    "threat_levels": [
      {
        "time": "2018-09-29 22:17:42",
        "threat": 67.6
      }
    ],
    "pop_levels": [
      {
        "time": "2018-09-29 22:17:42",
        "total_server_pop": 1,
        "living_players": 1,
        "living_antags": 1,
        "dead_players": 0,
        "observers": 0
      },
      
    ],
    "starting_threat_level": 77.6,
    "roundstart_rulesets": "Syndicate Traitors, ",
    "roundstart_pop": 1,
    "successful_injections": [
      
    ]
  }
}
```

2018-10-06 16:29 UTC, gbasood approved these changes

2018-10-09 15:43 UTC, merged