Fixes NPC Wizards Speaking in Deadchat
d3athrow/vgstation13 pull request #19963
Opened 2018-10-04 20:25 UTC by Shadowmech88

The `say()` comes before the NPC wizard dies in the same proc, and BYOND is single-threaded, so I have absolutely no idea how they could be dying before speaking. It's like how the Lawgiver sometimes repeats what the user says *before* the user says it.
In any case, this gives them a second where it just looks like they died, before they *actually* die, so they should now have time to say their death phrase and stop saying it in deadchat.
Fixes #19954.

:cl:
 * bugfix: Dead NPC wizards such as doppelgangers no longer speak in deadchat.

2018-10-04 23:18 UTC, DamianX commented
absolutely disgusting

2018-10-04 23:30 UTC, Shadowmech88 commented
I know fixing race condition-type situations like this with `sleep()` and `spawn()` are bad practice, but I have no idea where I'd even start figuring out why, in a block
```
a()
b()
```
`b()` would execute before `a()`. `say()` isn't delayed at all, is it? I can't imagine why it would be.

2018-10-05 07:29 UTC, Exxion commented on code/modules/mob/living/simple_animal/hostile/human/wizard.dm
> +	alpha = 0
`invisibility 101` dude

2018-10-18 12:38 UTC, MadmanMartian requested changes
Absolutely heretical

2018-10-19 23:01 UTC, Shadowmech88 commented
Ideas for a less heretical fix?

2018-10-20 04:39 UTC, DamianX commented
Find out why say is being delayed

2018-10-20 07:48 UTC, Shadowmech88 commented
So I looked into it. When the wizard's `say()` is called, it calls `/mob/living/simple_animal/say()`, which then calls `/mob/living/say()`. `/mob/living/say()` has no `sleep()`s or `spawn()`s in it whatsoever and, as far as I can tell, could not possibly be delayed.
Furthermore, I did some testing.
![image](https://user-images.githubusercontent.com/3991927/47252885-48759c80-d411-11e8-9e28-18180b8a1fbc.png)
![image](https://user-images.githubusercontent.com/3991927/47252888-4c092380-d411-11e8-8c1d-49e1e743b791.png)
![image](https://user-images.githubusercontent.com/3991927/47252891-4f9caa80-d411-11e8-9eae-91acc941b3a9.png)
As far as I can tell, this suggests that there is no delay of `say()`, since the messages appear sequentially in the order that they should. The only issue is that the message appears in deadchat, because the wizard is dead. However, the only place in `simple_animal` code where the mob's `stat` is set to `DEAD` is `/mob/living/simple_animal/death()`. Which means that when the `say()` is executed in `/mob/living/simple_animal/hostile/humanoid/wizard/death()`, given the fact that the parent is not called until after the `say()`, and the `say()` does not seem to be delayed, I don't see how the wizard could be dead by that point, and yet it is.
It seems that *something* is setting the mob's `stat` to `DEAD` before `death()` is called, but I'm not sure how I'd begin finding what that is, if it's not in `simple_animal` code.

2018-10-20 07:53 UTC, DamianX commented
What does the call stack leading up to `src.say("SCYAR...` look like?
Maybe the procs that deal with receiving damage are setting `stat`.

2018-10-20 08:03 UTC, Shadowmech88 commented
Wew, I found the problem.
Turns out there's no problem with the `death()` proc itself or the mob's `stat`, it works as intended the first time.
The issue is that doppelgangers are supposed to expire after a certain amount of time, which means if one has already been killed, it then calls `death()` a second time once that time's up. This causes them to speak in deadchat because they're attempting to die while already dead.

2018-10-20 13:48 UTC, MadmanMartian approved these changes

2018-10-20 13:49 UTC, merged