Tasing and shooting borgs temporarily slows them down
d3athrow/vgstation13 pull request #20035
Opened 2018-10-08 20:47 UTC by SonixApache

🆑 
 - tweak: Shooting a borg with a taser now slows them down for ~18 seconds. Shooting them with something else will slow them down for ~3 seconds.

2018-10-08 20:50 UTC, aceedex commented
mob/carbon/human/silicon when?

2018-10-08 21:03 UTC, Exxion commented
No, shooting them with *anything that deals no damage* slows them for 18 seconds. This includes tasers, but also includes water guns, laser tag guns, the practice laser, temperature guns, etc.

2018-10-08 21:11 UTC, SonixApache commented
🤔

2018-10-08 21:17 UTC, Exxion commented
Dude that's what the code says, quite clearly

2018-10-08 21:24 UTC, SonixApache commented
oversight, i'm on it

2018-10-08 22:13 UTC, SonixApache commented
slight adjustment, but oversight fixed

2018-10-09 04:50 UTC, Dacendeth commented
>laser tag guns slowing borgs
BRING IT BACK!

2018-10-17 10:23 UTC, jknpj requested changes

2018-10-17 10:23 UTC, jknpj commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if (movement_speed_modifier > 0.8)
NO MAGIC NUMBERS

2018-10-18 12:34 UTC, MadmanMartian requested changes
Remove magic numbers. Wizwazles begone.

2018-10-18 12:36 UTC, MadmanMartian commented
Theoryexploit - get tased, then install a VTEC for faster zoom

2018-10-18 18:37 UTC, SonixApache commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if (movement_speed_modifier > 0.8)
i'll get to it, i swear

2018-10-28 00:49 UTC, Ephx1 commented
rest in piss forever shiticons

2018-10-30 01:44 UTC, luzzgawr commented
It's a good idea. Movespeed is terrifyingly strong in combat and often underestimated. 

t. Shitter that doesn't play anymore

2018-11-01 14:16 UTC, SonixApache commented
I'LL FIX IT EVENTUALLY

2018-11-01 14:16 UTC, closed without merging