The ol' spicy keychain
d3athrow/vgstation13 pull request #20315
Opened 2018-10-19 07:43 UTC by BarneyGumball

Let's you heat up pretty much any holdable item on the bunsen burner.  Burns whoever proceeds to pick it up without the appropriate protection.  That protection being a pair of highly heat proof gloves.

:cl:
 * rscadd: You can now heat up items on the bunsen burner to play hilarious pranks on your friends!  Be careful though, whatever you're holding will get really hot.  Best you wear something to protect your hands.

2018-10-19 09:20 UTC, Shadowmech88 commented
The addition of a new item-level var solely for a meme that can only be performed with bunsen burners seems odd.
I'd rather have a var to properly track the item's actual temperature a la reagent heating, along with a var to determine how quickly it gains/loses heat based on the type of material from which it is made.

2018-10-19 09:47 UTC, BarneyGumball commented
I can move the var to an item flag.

I don't like the idea of item temperatures though.  As it is, heating an item functions as a quick little "haha" moment, at which point you can go back to using the item.  Having proper item heating/cooling has much longer lasting implications for any items that get heated up.  I can only imagine the nightmare after a plasma fire.  Also, having every `/obj` in the world process temperature changes probably wouldn't be worth the performance cost.

2018-10-19 13:22 UTC, SGuivenne commented
only if we can heat up the chain of command and then burn people with it.   I also expect this to eventually be used to brand people as punishment for crimes.

2018-10-19 17:14 UTC, I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE commented
I imagine the best way performance-wise to implement this would be an on-pickup event but I'm still not convinced adding a single var is that bad

Also, what if spicy items had a red outline like staff of reanimation mobs?

2018-10-19 18:17 UTC, kilozombie commented
> I imagine the best way performance-wise to implement this would be an on-pickup event but I'm still not convinced adding a single var is that bad
> 
> Also, what if spicy items had a red outline like staff of reanimation mobs?

There would have to be a tiny window where it's spicy hot but not visibly hot so you can really give somebody the ol' spicy cryptographic sequencer

2018-10-19 18:22 UTC, kilozombie commented
Also, steal the Duck Game "the item you're holding is red hot" hissing sound effect

2018-10-19 18:50 UTC, I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE commented
Excuse me in the original spicy keychain picture the keys are visibly red

2018-10-19 22:01 UTC, MadmanMartian requested changes
What the vox person said. And, for goodness sake don't make it just a bunsen burner.

2018-10-19 23:02 UTC, BarneyGumball commented
>don't make it just a bunsen burner

I'm open to suggestions.

2018-10-19 23:29 UTC, kilozombie commented
Have it be a function in the oven, like in the original

2018-10-27 22:40 UTC, BarneyGumball commented
Alright, so I:
* Adjusted the contents of some messages.
* Made it so you can heat up items in the oven and the deep fryer.
* Fixed the gloves protection so you can't just remove your gloves after you've picked up the heated item.

2018-10-27 23:02 UTC, BarneyGumball commented on code/game/objects/items.dm
> +					"<span class='warning'>[user] cries out in pain and jerks \his [hand_used] \
I don't actually know if `[hand_used]` works here, pls advise.

2018-11-11 22:11 UTC, MadmanMartian commented
So, added a proc for you to use. Attempt_heating. It's object level, takes an argument of the object being used to heat it, and the user if available.

Use that.

2018-12-04 04:02 UTC, BarneyGumball commented
This pr SUCKS

2018-12-04 04:02 UTC, closed without merging