rapiers
d3athrow/vgstation13 pull request #20819
Opened 2018-11-25 06:41 UTC by RealestEstate

introduces rapiers
they have 2 stances:
-a high stance which does 20 force
-a low stance which has a chance to parry but only does 13 force

they're essentially shittier katanas
viedo =
https://streamable.com/xuxoy

2018-11-25 07:24 UTC, unid15 requested changes

2018-11-25 07:24 UTC, unid15 commented on code/game/objects/items/weapons/weaponry.dm
> +		user.visible_message("<span class='warning'>You switch your stance with the [src] to [stance]!</span>")
This message will be displayed to everybody around

2018-11-25 07:24 UTC, unid15 commented on code/game/objects/items/weapons/weaponry.dm
> +	to_chat(viewers(user), "<span class='danger'>[user] is impaling \himself with the [src.name]! It looks like \he's trying to commit suicide.</span>")
Is there a reason not to use visible_message in suicide_act, other than old habits?

2018-11-25 07:56 UTC, RealestEstate commented on code/game/objects/items/weapons/weaponry.dm
> +		user.visible_message("<span class='warning'>You switch your stance with the [src] to [stance]!</span>")
how do I make it only display itself to the user?

2018-11-25 08:00 UTC, unid15 commented on code/game/objects/items/weapons/weaponry.dm
> +		user.visible_message("<span class='warning'>You switch your stance with the [src] to [stance]!</span>")
user.visible_message("[user] does a thing", "You do a thing")

2018-11-25 08:02 UTC, unid15 commented
aw are there no sprite difference for the stances? that'd be cool

2018-11-25 08:20 UTC, DamianX commented on code/game/objects/items/weapons/weaponry.dm
> +	to_chat(viewers(user), "<span class='danger'>[user] is impaling \himself with the [src.name]! It looks like \he's trying to commit suicide.</span>")
visible_message is definitely the way to go

2018-11-25 08:53 UTC, DamianX commented
Spessmart-only?

2018-11-25 09:56 UTC, Kurfursten commented on code/game/objects/items/weapons/weaponry.dm
> +	desc = "It is currently held low. In this stance you can parry attacks. Allez !"
space

2018-11-27 02:04 UTC, RealestEstate commented
@unid15 what kind of sprite differences did you have in mind? currently the different stances do have a difference in sprites as one is angled up and the other is angled down. Was there something else you had in mind?

2018-11-27 02:05 UTC, RealestEstate commented on code/game/objects/items/weapons/weaponry.dm
> +	desc = "It is currently held low. In this stance you can parry attacks. Allez !"
like between "allez" and "!"?

2018-11-27 02:37 UTC, RealestEstate commented on code/game/objects/items/weapons/weaponry.dm
> +		user.visible_message("<span class='warning'>You switch your stance with the [src] to [stance]!</span>")
I only want it to display the stance switch to the user though

2018-11-27 02:41 UTC, DamianX commented on code/game/objects/items/weapons/weaponry.dm
> +		user.visible_message("<span class='warning'>You switch your stance with the [src] to [stance]!</span>")
You can use `to_chat` or `show_message`. The latter can let you take into account the user being blind.

2018-11-27 20:10 UTC, unid15 commented
Oh, there actually are sprite differences. Could've sworn there weren't, for some reason. Nevermind that then!

2018-11-28 19:20 UTC, SGuivenne commented
we need fencer apparel, a higher bleed chance, and a near 0 (if not 0) chance of limb removal if youre going this route.  remember fencing swords are thrusted, not slashed like a katana.

2018-12-06 11:17 UTC, DamianX commented on code/game/objects/items/weapons/weaponry.dm
> +	desc = "It is currently held low. In this stance you can parry attacks. Allez !"
yes

2018-12-06 11:17 UTC, DamianX commented
when

2018-12-08 20:21 UTC, RealestEstate commented
@DamianX won't be for a while, I'm gonna take a break on this.
in the meantime [DNM]

2018-12-09 23:43 UTC, DamianX commented
Shout when you want this reopened

2018-12-09 23:43 UTC, closed without merging