Click monkey, become monkey
d3athrow/vgstation13 pull request #21025
Opened 2018-12-12 04:03 UTC by MadmanMartian

Ghosts can now possess dionae and mushmonkeys via clicking on them, should they have no client controlling them.

2018-12-12 05:27 UTC, Dacendeth commented
diona nymphs die pretty quickly if no one signs up, wont this be not very useful when it comes to nymphs as unless you're quick they'll be dead already?

2018-12-12 11:30 UTC, ShiftyRail commented
What if someone signs up as a diona, builds up a personality or something, and then ghosts ?

2018-12-12 23:49 UTC, spoonylove commented
Not actual monkies? This would double the amount of mush people too theoretically too right?

2018-12-13 00:58 UTC, Emilc4h commented
Actual monkeys wouldn't be great because of the inevitable "whoops all the geneticist's monkeys just legged it", though that could be fixed by making it only apply to post-roundstart monkeys.

I presume it's just a QoL change for existing mid-round ghost roles, and the current method for re-entering the round as a human is the Machine-Man Interface - just dropping into a monkey and getting your monkey/human block switched would make MaMIs even more uncommon than they already are.

2018-12-13 01:03 UTC, spoonylove commented
Some actual round testing would be nice in this case. How many monkies out of the pen do geneticists use really? 2-3? MaMis might as well not exist I havent seen one I dont think ever.

2018-12-13 01:09 UTC, Emilc4h commented
They get used every now and then, but not that often. I still think it'd be best to restrict this change to pre-existing ghost roles, but I guess testing things never hurts.

2018-12-22 10:39 UTC, Intigracy commented
Can you address the `diona nymphs die right away if they don't have a client` part of this?

2018-12-22 10:40 UTC, Intigracy requested changes
Can you address the `diona nymphs die right away if they don't have a client` bit?

2018-12-22 12:34 UTC, MadmanMartian commented
looks like it's intended

`/datum/seed/proc/handle_living_product(var/mob/living/host)
	if(!host || !istype(host))
		return

	if(!product_requires_player)
		return

	currently_querying = list()
	request_player(host)

	if(product_kill_inactive)
		spawn(675)
			if(!host.ckey && !host.client)
				host.death()  // This seems redundant, but a lot of mobs don't
				host.stat = 2 // handle death() properly. Better safe than etc.
				host.visible_message("<span class='warning'><b>[host] is malformed and unable to survive. It expires pitifully, leaving behind some seeds.</span>")

				if(mob_drop)
					new mob_drop(get_turf(host))
				else
					var/obj/item/seeds/S = new(get_turf(host))
					S.seed_type = name
					S.update_seed()
`

2018-12-22 19:39 UTC, Intigracy commented
Yeah because it didn't want to waste a seed if there's no players to take it over.

Which is redundant if players can now take it over at any time.

2018-12-23 16:29 UTC, MadmanMartian commented
would be unatomic, but okay.

2018-12-24 02:56 UTC, Exxion commented
Not really
It's removing an old fix for something you made a new fix for

2018-12-24 03:25 UTC, Intigracy approved these changes

2018-12-24 03:25 UTC, merged