Adds More Botany Chemical Reactions
d3athrow/vgstation13 pull request #21247
Opened 2019-01-07 04:23 UTC by bathosbathtime

This PR adds a series of chemical reactions using botany chemicals.  I saw someone in the thread mention that they miss being able to do chemical reactions inside of plants, so I hope that this might help.  I went down the list of plant chemicals on the wiki so if there is one that isn't listed there it got skipped over.  I also skipped over creatine and fix-o-vien as I wasn't sure how they'd interact inside of a plant.  They can be added if needed.
Also nitroglycerin removes phenol and formic acid since they're used in the reaction now.
EDIT: the weedeater reaction has been removed due to conflicts.

:cl:
 * rscadd: Mirrors over chemical reactions to botany chemicals

2019-01-07 06:05 UTC, MadmanMartian requested changes
I rewrote reagent code so we didn't have to have botany subtypes of normal chem reactions.

Refer to #20652

2019-01-07 06:18 UTC, bathosbathtime commented
Ah, I will update these tomorrow to add the new IDs to all of the reactions instead of having new ones.  I even noticed the new IDs in some of the recipes but I was unaware of the purpose.  Thank you.

2019-01-07 06:26 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(INAPROVALINE = 1, ALLICIN = 1)
This already works

2019-01-07 06:26 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(RADIUM = 1, ALLICIN = 1)
This already works

2019-01-07 06:27 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(CHLORINE = 1, NITROGEN = 1, ALLICIN = 1)
This already works

2019-01-07 06:28 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(ALKYSINE = 1, BLEACH = 1, ALLICIN = 1)
This already works

2019-01-07 06:28 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(CARBON = 1, HYDROGEN = 1, ALLICIN = 1)
This already works

2019-01-07 06:29 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(WATER = 1, CARBON = 1, ALLICIN = 1)
This already works

2019-01-07 06:29 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(OXYGEN = 1, ALLICIN = 1, CARBON = 1)
This already works

2019-01-07 06:29 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(SILICON = 1, HYDROGEN = 1, ALLICIN = 1)
This already works

2019-01-07 06:30 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(ETHANOL = 1, ALLICIN = 1, CHLORINE = 1)
This already works

2019-01-07 06:31 UTC, MadmanMartian commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list(CORNOIL = 3, FORMIC_ACID = 1)
This already works

2019-01-07 06:32 UTC, MadmanMartian commented
A lot of these already work.

2019-01-21 06:37 UTC, Kurfursten commented
#21353

2019-01-21 13:12 UTC, closed without merging