Revs is now delayed by 5 minutes
d3athrow/vgstation13 pull request #21314
Opened 2019-01-17 20:55 UTC by ShiftyRail

Hopefully the rounds will now last 15 minutes instead of 10
[tweak]

:cl:
- tweak: Roundstart revs is now delayed by 5 minutes

2019-01-17 21:17 UTC, boy2mantwicethefam commented
GRUDGECODE
But seriously the sudden initiative from revs is what allows rev rounds to end quickly before command and security digs in place and gradually gets rid of revolutionaries in a terribly slow slog until it ends in a theorycrafted incident where revs bomb the whole thing or the real deal events in which the shuttle arrives or they all manage to kill the head revolutionaries as they kill & hold or grab & implant people. Not sure if the shuttle can depart though

2019-01-17 21:22 UTC, ShiftyRail commented
In an ideal world it would be changeling'd

2019-01-17 21:27 UTC, boy2mantwicethefam commented
In an ideal world SS13 wouldn't be on BYOND

2019-01-20 00:36 UTC, MadmanMartian commented on code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
> +		return 1
Tab this back once, as execute is expected to return 1, else the ruleset is dumped.

2019-01-22 01:59 UTC, MadmanMartian requested changes
do the thing

2019-01-27 15:58 UTC, MadmanMartian approved these changes

2019-01-29 14:28 UTC, merged