Fixing bug #21330
d3athrow/vgstation13 pull request #21332
Opened 2019-01-19 21:45 UTC by DeityLink

Fixed #21330

:cl:
* bugfix: Fixed Nar-Sie rising in nullspace if the anchor blood stone got destroyed during Act IV.

2019-01-19 22:01 UTC, Kurfursten commented
The other odd thing about this case is that no one was dancing at all. Both @Arthurdentist and I watched the fight and no cultist ever danced (or if they did it was very briefly and immediately interrupted by gunfire and explosions, 3 welderbombs went off by the stone)

2019-01-19 22:45 UTC, MadmanMartian requested changes

2019-01-19 22:45 UTC, MadmanMartian commented on code/datums/gamemode/factions/bloodcult/bloodcult_buildings.dm
> +	if (src && loc)
Src can never be null, you'd be better off checking if(!gcDestroyed && loc)

This is evidence of a worse problem involving the while loop never properly breaking. Go to 1382 and change it to while(!gcDestroyed && loc && anchor)

Honestly, this is rather gunked and may need some rework

2019-01-19 23:11 UTC, DeityLink commented
@Kurfursten The anchor's dance is a bit different from the sacrifice one. The "dance" begins as soon as the blood stone becomes an anchor upon Act IV beginning. This bug never happening before means that this is the first time that the crew actually manages to destroy the anchor. Not bad.

2019-01-19 23:12 UTC, MadmanMartian approved these changes

2019-01-19 23:12 UTC, MadmanMartian reviewed
Try and rework it so it doesn't require a while loop.

2019-01-19 23:14 UTC, DeityLink commented
I can use a different while loop but what's wrong with while loops specifically?

2019-01-19 23:15 UTC, MadmanMartian commented
very dependent on break conditions so as to not kill the serb. Better to avoid them in practice.

2019-01-19 23:16 UTC, DeityLink commented
I've tried recursively call a proc instead before but BYOND didn't like that. I could have two procs call each other alternatively instead I guess.

2019-01-20 00:51 UTC, Exxion commented
That won't work either
This is fine

2019-01-20 07:14 UTC, Kurfursten commented
Wait, you're saying the cult automatically wins a set number of ticks after the spread blood objective?

2019-01-21 00:51 UTC, DeityLink commented
@Kurfursten No, the dance only actually progresses if there are dancers. If there are no dancers, progresses slowly rolls back every tick.

2019-01-21 01:40 UTC, Kurfursten commented
Alright I'm gonna trust you on this one that it was a fluke even though neither of us saw any dancers. You did test this right to make sure the cult failure happens?

2019-01-21 08:20 UTC, DeityLink commented
I'll test tonight.

2019-01-24 11:46 UTC, merged

2019-01-27 20:32 UTC, DeityLink commented
For the record I wasn't done testing.

2019-01-27 23:04 UTC, DeityLink commented
And just so we're clear, it spawning at ALL when it got destroyed was the real issue here, not just the fact that it spawned in nullspace.

2019-01-27 23:13 UTC, MadmanMartian commented
yup