further dab fixes
d3athrow/vgstation13 pull request #21366
Opened 2019-01-22 13:04 UTC by SonixApache

tested

🆑 
 - tweak: fixes slight oversight where *dab would cause you minor damage

2019-01-22 13:09 UTC, boy2mantwicethefam commented
cringe but redpilled

2019-01-22 13:52 UTC, Tokanova commented
have you ever considered this is working as intended?

2019-01-24 08:57 UTC, MadmanMartian requested changes
Needs an 'Are you sure you want to do this?' in front of the suicide.

2019-01-24 17:20 UTC, MadmanMartian approved these changes

2019-02-06 18:16 UTC, merged