Wizards no longer spawn with robotic organs.
d3athrow/vgstation13 pull request #21452
Opened 2019-01-28 07:53 UTC by boy2mantwicethefam

Something's wrong with handling internal mob organs, but this is not the PR for it. Instead this fixes wizards spawning with prosthetic organs, meaning they can't take EMP or else they'll kill themselves.
fixes #21437 
:cl:
 * bugfix: Wizards no longer spawn with prosthetic organs. Now you can take EMP again.

2019-01-28 08:25 UTC, ShiftyRail commented
Not really the proper way to fix it but it shouldn't cause (too much) problems.

2019-01-28 08:28 UTC, boy2mantwicethefam commented
![](https://i.imgur.com/qcnWryU.png)

2019-02-01 15:00 UTC, jknpj requested changes

2019-02-01 15:00 UTC, jknpj commented on code/datums/gamemode/misc_gamemode_procs.dm
> +	wizard_mob.revive(0) //Used to properly refresh limb icons and make prosthetic internal organs organic
literally just call update_body() after make_all_robotic_parts_organic()

2019-02-12 20:55 UTC, closed without merging