Midround bomberman
d3athrow/vgstation13 pull request #21520
Opened 2019-02-02 00:19 UTC by ShiftyRail

[content] [gameplay] [wip]

## General idea

There's often not a lot to do when you're a ghost, but still want a way to be kept in the round somehow, or if you're waiting for the round to end.
This PR tries to make this experience less dull, by allowing ghosts to create their own bomberman arenas midround, and by changing the way bombermen are generated using transmorgification.

With a transmog, the original body & mind is kept, so if you're suddenly being cloned in the middle of a bomberman match, you can dip in back in the round.

## To be tested

Everything. Dream Deamon isn't playing nice with me and testing this with multiple accounts is a pain.
I'll ask some anons to hop on the test server maybe tomorrow to see if there are any major issues.

I also want to check if the "You're being cloned!" message still applies when transmorgified, and if it doesn't, make it so.

:cl:
- rscadd: Ghosts can now freely create midround bomberman arenas.
- tweak: Joining  a bomberman arena will no longer prevent you from being cloned or brought back as your original character.

2019-02-02 03:04 UTC, I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE commented
I'll take midround thunderdome any day of the week before this, thanks

2019-02-02 03:19 UTC, SonixApache commented
good gateway to arena datums and more things to do for ghosts, good idea

2019-02-02 13:37 UTC, ShiftyRail commented
Why not have both ?

2019-02-02 21:51 UTC, Exxion commented
Out of curiosity, what happens if you get revived while actively playing Bomberman? Does the Bomberman just go braindead/catatonic/etc.?

2019-02-04 10:27 UTC, DeityLink commented on code/modules/mob/dead/observer/observer.dm
> +	new /datum/bomberman_arena(locate(250, 250, 2), pick("15x13 (2 players)","15x15 (4 players)","39x23 (10 players)"), src)
Why not search for a landmark that can then be placed on Z2?

2019-02-05 20:48 UTC, ShiftyRail commented
@Exxion The bomberman just gets deleted. His gear falls on the ground, and he's removed from the arena's players. (as far as I'm aware)

2019-02-24 08:59 UTC, ShiftyRail commented
Fuck mappers and fuck conflicts

2019-02-24 09:26 UTC, ShiftyRail commented
Oh God oh fuck

2019-02-24 11:30 UTC, ShiftyRail commented
@MadmanMartian You (or someone else) broke the line endings in Roid
Reeee

2019-03-07 18:14 UTC, Kurfursten commented
What is the status on this?

2019-03-07 19:14 UTC, ShiftyRail commented
Need to make it so it doesn't break Roid station maybe

Le jeu. 7 mars 2019 à 19:14, Kurfursten <notifications@github.com> a écrit :

> What is the status on this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/21520#issuecomment-470635526>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ad9lmm9rktce43jUpp8EwUQwuRby_z9Cks5vUVb-gaJpZM4afTG->
> .
>

2019-03-14 14:18 UTC, SonixApache commented
conflicts

2019-04-07 19:21 UTC, ShiftyRail commented
Fucking conflicts
I'll just use a hardmapped location, soft-mapping the landmark can come next time

2019-04-07 20:01 UTC, MadmanMartian requested changes
use the dungeon loading function

2019-04-07 21:37 UTC, ShiftyRail commented
Bomberman arenas aren't dungeons, they're created and destroyed on the fly, which makes sense as they're supposed to be different every round and there's 3 different types of them

I don't understand what you're asking me to do here.

2019-04-17 20:17 UTC, ShiftyRail commented
Not feasible at this time, bomberman arenas are not a map element and are dynamically generated. The dungeon loader was not made for this kind of problems.

2019-04-18 18:50 UTC, Kurfursten commented
Is this tested?

2019-05-06 15:21 UTC, ShiftyRail commented
Yes it is. I even got players to test it on the test server.

2019-05-06 15:29 UTC, merged