Advanced Clown Shoes now also require the user to be clumsy.
d3athrow/vgstation13 pull request #21526
Opened 2019-02-02 13:10 UTC by boy2mantwicethefam

closes #21312 
That was easy
:cl:
 * tweak: The advanced clown shoes now require the user to also have M_CLUMSY beside being a clown.

2019-02-02 13:12 UTC, Dacendeth commented
Now if only clowns kept their rye immune clumsy after being cloned

2019-02-02 13:36 UTC, ShiftyRail commented
The feature request also suggested to remove the hard-coded "clown" requirement.

2019-02-02 13:41 UTC, boy2mantwicethefam commented
Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

2019-02-02 16:44 UTC, Intigracy commented
You made it so people who are clumsy can't use the shoes fam.

2019-02-02 16:49 UTC, Intigracy requested changes
the way you have this doesn't even work right, it works for everyone who ISN'T clumsy

2019-02-02 16:49 UTC, Intigracy commented on code/modules/clothing/shoes/miscellaneous.dm
>  /obj/item/clothing/shoes/clown_shoes/advanced/attack_self(mob/user)
```suggestion
/obj/item/clothing/shoes/clown_shoes/advanced/attack_self(mob/living/user)
```

2019-02-02 16:49 UTC, Intigracy commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.mind && M_CLUMSY in user.mutations)
```suggestion
	if(user.mind && !clumsy_check(user))
```

2019-02-04 02:33 UTC, Intigracy approved these changes

2019-02-04 02:34 UTC, merged