Cursed D20s can now be properly scanned.
d3athrow/vgstation13 pull request #21535
Opened 2019-02-02 23:17 UTC by boy2mantwicethefam

Shout-out to @lunstra for fixing it
Nothing will fix the brain damage I received from witnessing the device analyzer code and seeing return -1 and return -2 though
[bugfix] [easyfix]
This was supposed to function since #17665, so it's a bugfix
:cl:
 * bugfix: D20s can now be scanned, and are also considered anomalous for the purpose of research. Also adds a commented out notice to the device analyzer code regarding scanning.

2019-02-02 23:23 UTC, ShiftyRail commented on code/modules/research/mechanic/device_analyser.dm
> +AN OBJECT NEEDS TO HAVE RESEARCH SO THAT IT CAN BE SCANNED
It would be even better to say, "his `origin_tech` var must not be empty;

2019-02-02 23:24 UTC, boy2mantwicethefam commented on code/modules/research/mechanic/device_analyser.dm
> +AN OBJECT NEEDS TO HAVE RESEARCH SO THAT IT CAN BE SCANNED
Done

2019-02-02 23:36 UTC, MadmanMartian requested changes
there's a thing in the xenoarch datums that applies origin_tech

2019-02-02 23:56 UTC, boy2mantwicethefam commented
That's a fair point

2019-02-03 00:13 UTC, boy2mantwicethefam commented
Okay so the problem of cursed dice not being scannable could be two things
1. A bug that I have no idea what could cause, and might look into later on
2. Bussed dice
I guess at the very least this PR lets bussed dice be scanned :man_shrugging:

2019-02-03 00:16 UTC, Lunstra commented
Well my "finding" of this was mainly due to someone in deadchat saying d20s couldnt be scanned so I spawned one to check so probably option 2. Not a bug at all then ¯\_(ツ)_/¯

2019-02-03 00:19 UTC, boy2mantwicethefam commented
Hey, xenoarch items that are supposed to have anomaly research but can't because they were bussed is still a bug, but less of a bug and more of an oversight

2019-02-03 01:32 UTC, DrSnips commented on code/modules/research/mechanic/device_analyser.dm
> +AN OBJECT NEEDS TO HAVE RESEARCH SO THAT IT CAN BE SCANNED
While this is partly true its actually based on 3 things and not just research. If an item has 1)A design datum. 2)A "starting materials" value. or 3)Research values. It tries to make a design from those factors in that order.

2019-02-03 10:23 UTC, boy2mantwicethefam commented
Now that I think about it, it's more of an oversight than anything. Maybe a PR later

2019-02-03 10:23 UTC, closed without merging

2019-02-03 13:36 UTC, DrSnips commented
Why not just change the tags?

2019-02-05 17:26 UTC, boy2mantwicethefam commented
It's not about changing the tags, it's an oversight about xenoarcheology items that are bussed in not spawning with research flags if the original item doesn't have any because a little bit of anomaly research is applied. If I get to revisit this, I'll make this a more thorough thing including most of the archeological items

2019-02-05 17:59 UTC, DrSnips commented
I ment the tags on the PR.