Adds scientist screams
d3athrow/vgstation13 pull request #21692
Opened 2019-02-14 09:47 UTC by boy2mantwicethefam

I said I'll do it even if the manual screaming PR is not merged
I was this close for it to check resident science man's ckey too
Funny > Balance, I know this can be a way to check if someone sneaking around is a scientist but come on
:cl:
 * rscadd: Scientists now have Half-Life screams.

2019-02-14 11:03 UTC, ShiftyRail commented
Meme PR

2019-02-14 12:31 UTC, MadmanMartian requested changes
fix those femsci screams. Jesus christ. They're females not chipmunks.

2019-02-14 12:38 UTC, boy2mantwicethefam commented
@MadmanMartian It's the future Deity chose

2019-02-14 15:25 UTC, Irradiation commented
Deity isn't the be-all-end-all of design decisions. That female scream can go burn in whatever unholy hell spawned you.

2019-02-14 16:37 UTC, Durgen commented
Do only science personnel use these?

2019-02-16 08:53 UTC, boy2mantwicethefam commented
@Durgen Yes.
Anyway female scientists can no longer scream high-pitched variants of the normal science sounds.

2019-02-20 14:38 UTC, MadmanMartian requested changes

2019-02-20 14:38 UTC, MadmanMartian commented on code/modules/mob/living/carbon/emote.dm
> +					if(H.mind.assigned_role in science_positions)
April fools check, or close.

2019-02-20 16:25 UTC, boy2mantwicethefam commented on code/modules/mob/living/carbon/emote.dm
> +					if(H.mind.assigned_role in science_positions)
k but in a bit

2019-02-20 20:44 UTC, merged

2019-02-20 21:28 UTC, Exxion commented on code/modules/mob/living/carbon/emote.dm
> +						if(MALE)
lmao

2019-02-20 21:28 UTC, MadmanMartian commented on code/modules/mob/living/carbon/emote.dm
> +						if(MALE)
Code(male)