loose catbeasts are now black
d3athrow/vgstation13 pull request #21997
Opened 2019-03-10 20:21 UTC by Intigracy

human_face.dmi is edited because I had to cut the ears off of the hair and make them part of the head, unless you want brown ears on black beasts.

There's a few more files changed that have to do with the way the icon-based skin colors work, because it is/was a mess that still needs further work (random skin tone should be moved to species datums, for example)

:cl:
 * tweak: Loose catbeasts are now black.

2019-03-10 20:22 UTC, MadmanMartian commented
>RUNTIME IS ROGUE

2019-03-10 20:24 UTC, DeityLink commented
So it's like because they're bad omen or something?

2019-03-10 20:30 UTC, ShiftyRail commented on code/__HELPERS/mobs.dm
> +	else if(species == "Tajaran"
You forgot a `)`

2019-03-10 20:32 UTC, boy2mantwicethefam commented
That's racist you can't say the n-word

2019-03-10 20:45 UTC, Kurfursten commented
I feel like a better implementation of this would be to create a black hairstyle and a brown hairstyle and just set which one they get based on if they're black or not.

2019-03-13 13:31 UTC, Hoshi-chan commented
13% of all catbeasts...

2019-03-19 18:29 UTC, SonixApache commented
when

2019-03-19 18:32 UTC, Kurfursten commented
If you're gonna do it, do it right. We both know this isn't the right way to do it. Make it a black hairstyle and set h_style then call update_hair.

Editing the face file is a hacky solution.

2019-03-19 18:32 UTC, Kurfursten requested changes
If you're gonna do it, do it right. We both know this isn't the right way to do it. Make it a second racial hairstyle and set h_style then call update_hair.

Editing the face file is a hacky solution.

2019-03-20 00:22 UTC, Intigracy commented
Nope.

I'd rather see the ears poking out of things.

2019-03-20 00:27 UTC, Intigracy commented
You can merge it or close it, but I have no interest in changing it.

2019-03-20 00:40 UTC, closed without merging

2019-03-20 00:45 UTC, Zth-- commented
Uhm, closing the PR over personal preference? ... when there's clearly more active collabs?

This is not how I want my collabs to behave

2019-03-20 00:59 UTC, Kurfursten commented
This isn't personal preference, this is a matter of coding standards. In the original comment he claimed it was only this way because he didn't know how to manage it besides this hacky solution, and now he's gone back to change it to say he prefers it this way. It's not changeloged, it's not atomic, and the last comment gives off a serious air of "I'm too lazy to do this right".

And not that it matters but I am currently the most active collab on this repo according to Insights. Nor does this matter, but I'm going to take the sprites and do this the right way instead of half assing it.

2019-03-20 01:03 UTC, Intigracy commented
Nah I'll just make a poll to see if people want to see ears through
headgear.

2019-03-20 01:16 UTC, Kurfursten commented
I feel like you're unnecessarily making drama here -- issuing an ultimatum and now acting petulant about it.

There's are two reasons why it's designed the way it is: it's consistent with the tail behavior, and it creates an interesting gameplay scenario in which people are forced to remove helmets to identify catbeasts. Stopping unknowns for questioning. Designing the feature in the way you have is gunked because it encourages people to look for things with large on-character sprites to exploit how our clothing overlay code works. 

But *even if* people wanted cat ears visible at all times, this would still not be the proper implementation. You should still make it a hairstyle and add an exception so that it draws the ears on top of all helmets. Don't insist on code we both know is bad out of stubbornness. If you want help coding this I am happy to help you or, honestly, just do it myself.

2019-03-20 01:31 UTC, Intigracy commented
Sorry, I'm being unfair here. Do what you think is the better method.

Though the difference in doing it as a hair vs part of the face is that the entire ear shows instead of just the part that would be sticking out from whatever headgear.

2019-03-20 01:36 UTC, Kurfursten commented
Yeah, that's what I'm saying. I think if we *do* want ears sticking out, we should go full monte and have the whole ear sticking out. I think it's still fair to poll if you want to as long as people know the reasons it is how it is.

Because if that's the way people want it, it should apply evenly to all hats from big to small. The snakehat cosmetic shouldn't be better at hiding ears than an airtight space helmet, dig?

2019-03-20 02:09 UTC, Intigracy commented
That looks absolutely awful though

2019-03-20 02:36 UTC, Kurfursten commented
I mean I think ears-through-hardsuit-helmet is gonna look bad no matter how you do it

2019-03-20 02:48 UTC, Zth-- commented
As long as you reach consensus then it's fine by me. I think closing this PR was rather harsh and that's why I commented in the first place. But yeah let's get over this