Walking into airlocks while brain-damaged has the same chance of making you headbutt it.
d3athrow/vgstation13 pull request #22151
Opened 2019-03-22 12:16 UTC by boy2mantwicethefam

Technically a bugfix but I consider it a big enough change that it should be treated like a feature PR
UNLIKE @PJB3005 !!!
:cl:
 * balance: Walking into airlocks while brain-damaged now has a chance to make you headbutt it, the same as clicking it.

2019-03-22 12:23 UTC, codeungabunga commented
This is implemented in such a way that it would encourage needless micro by stepping next to an airlock and clicking it, rendering it pointless.

2019-03-22 12:26 UTC, boy2mantwicethefam commented
It can already trigger when clicking an airlock, that's been a thing for years

2019-03-22 13:18 UTC, Kurfursten requested changes
Make a proc for headbutt instead of pasting the code

2019-03-22 13:24 UTC, boy2mantwicethefam commented
I was thinking the same tbh

2019-03-22 14:58 UTC, codeungabunga commented
I was unaware of such a feature, if it's consistent then it's good.

2019-03-28 20:10 UTC, MadmanMartian requested changes

2019-03-28 20:10 UTC, MadmanMartian commented on code/game/machinery/doors/door.dm
> +				O.take_damage(damage) //Brute damage only
Dangerous to assume they'll have a head

2019-03-29 02:37 UTC, Kurfursten approved these changes
you got my half

2019-03-30 14:41 UTC, MadmanMartian approved these changes

2019-03-30 17:47 UTC, merged