readds null rod vamp smiting
d3athrow/vgstation13 pull request #22179
Opened 2019-03-24 10:40 UTC by SirSkeleto

why was this removed in the first place
thuribles still work
if the null rod protects the holder why cant it smite bitches too
i dun geddit

:cl: 
- null rod fucks up vampires once more

2019-03-24 10:44 UTC, bathosbathtime requested changes

2019-03-24 10:44 UTC, bathosbathtime commented on code/game/objects/items/weapons/null_rod.dm
> +					V.nullified = min(5, V.nullified + 2)
unlogged change, ban he

2019-03-24 10:46 UTC, bathosbathtime commented on code/game/objects/items/weapons/null_rod.dm
> +					V.nullified = min(5, V.nullified + 2)
Logged now, please ignore.

2019-03-24 12:44 UTC, SonixApache commented
Supposedly the null rod was now an item of defense, and the thurible an item of offense.

2019-03-24 14:00 UTC, d3athrow commented
people were stealing the nullrod to use against antags I think

2019-03-24 16:12 UTC, Hoshi-chan commented
> people were stealing the nullrod to use against antags I think

Simple. Make it so only the chaplain can wield it, then.

2019-03-25 14:12 UTC, SirSkeleto commented
> > people were stealing the nullrod to use against antags I think
> 
> Simple. Make it so only the chaplain can wield it, then.

`if(V && user.mind && (user.mind.assigned_role == "Chaplain"))`

2019-03-25 18:48 UTC, Kurfursten commented
This may be pedantic but this isn't a revamp

Also, avoid hard checks to assigned role where possible outside of actual spawning code. Instead check to see if they're a religious leader if you want to do that.

2019-03-27 08:00 UTC, SirSkeleto commented
originally it wasn't called a revamp but i was talking to bathos and he said if i didn't take the opportunity to do a shitty pun he would do unspeakable things
partially true anyway

2019-03-29 02:34 UTC, merged