IDs with the right access can be thrown against doors to open them
d3athrow/vgstation13 pull request #22311
Opened 2019-04-02 09:07 UTC by DamianX

:cl:
 * rscadd: IDs and PDAs with the right access can be thrown against doors and airlocks to open them.

2019-04-02 10:11 UTC, MadmanMartian commented
This also makes it so that you can throw *people* with the right access to open doors/airlocks

Can't open a door for fear of shock? Slip the captain and just use him as a battering ram!

2019-04-02 10:25 UTC, DamianX commented
That's already a thing, though.

2019-04-02 14:55 UTC, bathosbathtime commented
Giving a monkey man your ID and throwing him  during subverted AI times is a high level medbay strat, can confirm.

2019-04-02 19:34 UTC, SonixApache commented
Does a similar thing happen for IDs without the proper access?

2019-04-02 19:44 UTC, DamianX commented
similar to what?

2019-04-02 20:13 UTC, SonixApache commented
Does throwing an ID with not enough access at a door that requires access produce a "You don't have enough access" noise?

2019-04-02 20:28 UTC, DamianX commented
Throwing at it anything that's not an ID with access now does that.

2019-04-04 14:59 UTC, Dacendeth commented
What about throwing emags at doors or is that too weird, also do wallets work correctly with this?

2019-04-04 16:17 UTC, DamianX commented
I'm not gonna do emags with this PR but I have no opinion about it one way or another.
Wallets should work but 0% tested.

2019-04-08 13:39 UTC, agentofzog2 commented
Seems like it;ll just make it even easier to avoid shocked doors.

2019-04-08 14:11 UTC, jknpj commented
bolt them with the lights disabled, this is still humancreep though

2019-04-18 18:02 UTC, Kurfursten commented on code/game/machinery/doors/door.dm
> +	if(!can_access(thing.GetAccess(), req_access, req_one_access))
check_access already exists for this function, see access.dm L143

2019-04-28 15:05 UTC, ShiftyRail requested changes
Do the check_access thing please

2019-05-05 13:45 UTC, ShiftyRail approved these changes

2019-05-05 17:56 UTC, merged

2019-05-05 18:16 UTC, SonixApache commented
🎉