Fixing a potential exploit of the sacrifice target re-roll mechanic
d3athrow/vgstation13 pull request #22474
Opened 2019-04-16 07:33 UTC by DeityLink

:cl:
* bugfix: If the sacrifice target escape the station on the emergency shuttle or an escape pod, the cult won't be able to just reroll a new target at an altar.

2019-04-16 08:04 UTC, MadmanMartian requested changes
The escape pods were converted to shuttle types, so the transit turf check won't work. Use the following instead

var/datum/shuttle/S = is_on_shuttle(T)
if(emergency_shuttle.shuttle == S || emergency_shuttle.escape_pods.Find(S))

2019-04-16 12:41 UTC, SonixApache commented
literally why

2019-04-16 14:04 UTC, DeityLink commented
What do you mean why? It's an exploit, an oversight, a bug, an unintended feature.

2019-04-16 18:10 UTC, SonixApache commented
so the point of reroll is to get new targets when the original target is impossible to acquire
but yet if the target is on a moving shuttle or pod, which is impossible to call back, they can't get a new target?

2019-04-16 18:39 UTC, DeityLink commented
* Wait for the entire station to evacuate on the shuttle while preparing some blood nades
* "The shuttle has left the station"
* Reroll sacrifice target, which is now most likely a cultist since everyone else left (or is dumbfounded in escape)
* Immediately perform sacrifice while blood grenades are being detonated
* Summon Nar-Sie before the shuttle even reaches Centcom

We don't want that.

2019-04-16 19:50 UTC, SonixApache commented
🤔 
- shuttle leaves, cult is cucked out of a victory
- unless they manage to set up runes and beat everyone on the shuttle
- if they DO somehow manage that, the crew gets insta-cucked out of their safety and gets instawarped back to the station just to die for memes because the spread blood objective is a joke

2019-04-17 00:02 UTC, DeityLink commented
I'll say it again. This feature was created to deal with destroyed bodies and people leaving into space in the middle of the round. This feature was NOT created to give the cult a guaranteed way to start Act 3 (whether the shuttle is brought back or not) after the shuttle leaves the station.

2019-04-17 00:41 UTC, SonixApache commented
I think leaving this untouched combined with #22443 would be the better way to go for general play, unless you want to reward high-risk clutch gameplay.

2019-04-17 01:22 UTC, DeityLink commented
I'm sure even @ShiftyRail would approve of it. After all, 

> "Victory without risk is triumph without glory." - Corneille, El Cid

2019-04-17 06:18 UTC, bathosbathtime commented
>antag doesn't get green text if objectives not ready before shuttle leaves
>
What a bold new direction to take the cult.

2019-04-17 10:47 UTC, ShiftyRail commented
At the risk of being stuborn, I don't see how it addresses the issue of a cult sacrificing at t - 0.05 seconds feeling unfair and frustrating. 
Which was I wanted to address, since people told me it bothered them.

2019-04-17 14:46 UTC, DeityLink commented
@ShiftyRail Instead of just getting a quasi-guaranteed sac re-roll and shuttle yank after the shuttle leaves (which was easy to do due to this exploit, hence maybe why people complained about it) the cult will now need to get their hands on the sacrifice target before the shuttle leaves, or kidnap them while aboard the shuttle which is risky and thus shouldn't feel unfair.

2019-04-22 13:07 UTC, merged