Ports Dreamseeker window flashing from TG
d3athrow/vgstation13 pull request #22483
Opened 2019-04-16 22:12 UTC by boy2mantwicethefam

Untested but probably works
This ports window flashing from TG
What the hell is with preferences though? I had to copypaste the whole thing from start to finish, why is it so much spaghetti and will anyone explain what each thing does?
The subsequent PR related to this will be having midround roles make your Dreamseeker window flash orange, preferably with options to have it off, for special/antag roles only, and for all roles.
:cl:
 * rscadd: Added a new function to the game that makes your Dreamseeker window flash orange. Currently not used by anything.

2019-04-16 22:12 UTC, boy2mantwicethefam commented
Yes I AM going to test it when I get the chance

2019-04-17 07:42 UTC, ShiftyRail commented
Did you get an authorisation from the AGPL boogeyman

2019-04-17 08:20 UTC, boy2mantwicethefam commented
![AGPL boogeyman secured](https://i.imgur.com/iYmyqmC.png)
I think it counts

2019-04-17 18:53 UTC, Intigracy requested changes
Because it might get passed a mob with no client

2019-04-17 18:53 UTC, Intigracy commented on code/__HELPERS/unsorted.dm
> +    if(!C || (!C.prefs.window_flashing && !ignorepref))
Change `!C`to `!istype(C)`

2019-04-21 15:43 UTC, Intigracy approved these changes

2019-04-22 12:44 UTC, merged