Security RPG 2.0
d3athrow/vgstation13 pull request #22540
Opened 2019-04-19 20:59 UTC by KingofHONK

The much beloved security RPG is back! 

The RPG is located in security armory, within the secure locker. It has one shot, and no other way to get ammo besides that. Obviously to be used in true code red shit is hitting the fan scenarios or flashy executions.

2019-04-19 21:00 UTC, SonixApache commented
👎 , it's literally just a loaded RPG. If you're going to do it, do it right.

2019-04-19 21:01 UTC, KingofHONK commented
would it make you happier if I put a sec skirt in with it?

2019-04-19 21:03 UTC, Cockswain commented
Dare i say this is our guy?

2019-04-19 21:05 UTC, ShiftyRail commented
>doesn't compile

Lel

2019-04-19 21:05 UTC, DamianX commented
🤔

2019-04-19 21:06 UTC, ShiftyRail commented on code/game/objects/structures/crates_lockers/closets/secure/vault.dm
> +    return list(
Put that part at the end of the proc, because else everything after the "return" will be ignored

2019-04-19 21:19 UTC, SonixApache commented
Making an actual 'security' RPG that is actually single-use would be good.

2019-04-19 21:40 UTC, SirSkeleto commented
d o e s n t c o m p i l e

2019-04-20 01:49 UTC, PaulRitter commented
>It has one shot, and no other way to get ammo besides that. 

thats just not true sorry. totally onboard with sonix, do it right or don't do it at all, this is just a loaded rpg, you can reload it if you get your hand on shells.

**single-use or bust**

2019-04-20 02:05 UTC, mtpowell commented
``/obj/structure/closet/secure_closet/vault/armory/atoms_to_spawn()` ``

``atoms_to_spawn()` ``

`` ` ``

2019-04-20 03:02 UTC, jknpj commented
This is fucking stupid

2019-04-20 11:55 UTC, PaulRitter requested changes

2019-04-20 11:55 UTC, PaulRitter commented on code/game/objects/structures/crates_lockers/closets/secure/vault.dm
> +/obj/structure/closet/secure_closet/vault/armory/atoms_to_spawn()`
remove the ` at the end of atmos_to_spawn(), thats probably why its not compiling

2019-04-20 11:55 UTC, PaulRitter commented on code/game/objects/structures/crates_lockers/closets/secure/vault.dm
> +/obj/structure/closet/secure_closet/vault/armory/atoms_to_spawn()`
also whatever shiftyrail said, don't be that person that adds unreachable code

2019-04-20 13:12 UTC, agentofzog2 commented
Obviously sec should get a LAW instead of an RPG.

2019-04-20 15:13 UTC, SGuivenne commented
Actually what zog said.  Give them something distinct from the syndicate RPG or people will panic when some asshole shoots someone with it.  Make it a LAW or an AT40 or something.

2019-04-20 16:05 UTC, Kurfursten commented
How about a special rpg that doesn't breach the floor? Because as is only antags would use it.

2019-04-20 17:36 UTC, SonixApache commented
There was a lot of talk about a 'remote breaching charge' when discussing the first implementation of this meme. It'd just bust through walls, without necessarily breaking the floor.
Using it for that (and maybe mecha destruction?) would be cool.

2019-04-28 22:47 UTC, ShiftyRail commented
Either fix it or have it closed

2019-04-28 22:47 UTC, ShiftyRail requested changes
Do what the review comments say.

2019-04-29 22:29 UTC, ShiftyRail commented
I fixed it for you because I'm a c*llab and I can do it

2019-04-30 15:23 UTC, ShiftyRail commented
This is where I cover in shame and admit I'm a utter failure as a human being and defers you to #22703

2019-04-30 15:23 UTC, closed without merging