Starts trying to convert scrubbers to XGM
d3athrow/vgstation13 pull request #22552
Opened 2019-04-20 18:13 UTC by MadmanMartian

Great googly moogly are mapped scrubbers trash.

Did you know that half of box security corridor has scrubbers set to not syphon plasma, simply because of mapping accidents?

2019-04-20 18:26 UTC, Exxion requested changes
I think you made a mistake on one thing when using find and replace

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	TLV[GAS_OXYGEN] =		list(-1, -1,  -1,  -1) // Partial pressure, kpa
```suggestion
	TLV[GAS_NITROGEN] =		list(-1, -1,  -1,  -1) // Partial pressure, kpa
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +			TLV[GAS_OXYGEN] = 		list(16, 19, 135, 140) // Vox use same partial pressure values for N2 as humans do for O2.
```suggestion
			TLV[GAS_NITROGEN] = 		list(16, 19, 135, 140) // Vox use same partial pressure values for N2 as humans do for O2.
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	TLV[GAS_OXYGEN] =		list(-1, -1,  -1,  -1) // Partial pressure, kpa
```suggestion
	TLV[GAS_NITROGEN] =		list(-1, -1,  -1,  -1) // Partial pressure, kpa
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	var/nitrogen_dangerlevel = get_danger_level(environment.partial_pressure(GAS_NITROGEN), TLV[GAS_OXYGEN])
```suggestion
	var/nitrogen_dangerlevel = get_danger_level(environment.partial_pressure(GAS_NITROGEN), TLV[GAS_NITROGEN])
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	current_settings = TLV[GAS_OXYGEN]
```suggestion
	current_settings = TLV[GAS_NITROGEN]
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	percentages[GAS_OXYGEN]=nitrogen_percent
```suggestion
	percentages[GAS_NITROGEN]=nitrogen_percent
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
> +	danger[GAS_OXYGEN]=nitrogen_dangerlevel
```suggestion
	danger[GAS_NITROGEN]=nitrogen_dangerlevel
```

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
>  	percentages["co2"]=co2_percent
I'm not sure if you'd also need to update something somewhere else if you changed this to `GAS_CARBON`, but if not you should

2019-04-20 18:26 UTC, Exxion commented on code/game/machinery/alarm.dm
>  	danger["co2"]=co2_dangerlevel
Same here as the other one that isn't a suggested change

2019-04-21 00:50 UTC, Exxion approved these changes

2019-04-22 12:39 UTC, merged

2019-04-22 14:32 UTC, PJB3005 commented
This broke air alarm scrubber preferences it seems.

2019-04-22 15:13 UTC, MadmanMartian commented
It did, because it was far from finished.

2019-04-22 15:42 UTC, PJB3005 commented
Mark the PR as explicitly WiP next time.

2019-04-22 15:59 UTC, SirSkeleto commented
or you could use github's cool new draft pr feature

2019-04-22 16:08 UTC, PJB3005 commented
Yes, that's what I meant.