teleport/blink slip bug fix
d3athrow/vgstation13 pull request #22705
Opened 2019-04-30 20:11 UTC by DDihanov

[hotfix]

closes #22699

:cl:
 * tweak: Added flag which prevents mob from slipping

Might be some better way to do this. It turns out the problem wasn't just the blink method, but rather the forceMove method which is also used by the admin helper method to teleport.

2019-04-30 21:49 UTC, PaulRitter requested changes

2019-04-30 21:49 UTC, PaulRitter commented on code/modules/mob/mob.dm
> +	unlock_from()
move this back to the wiz code, we dont want everything to unlock itself if it attempts a teleport

2019-05-01 20:27 UTC, SonixApache commented
should probably toss the administrative changes into a seperate PR

2019-05-01 20:52 UTC, Kurfursten commented on code/modules/mob/living/living.dm
> +	if (!src.can_slip)
src

2019-05-01 20:53 UTC, Kurfursten commented
You shouldn't put such different things in a single PR, and that's coming from a guy who has done some pretty unatomic things in the past. These aren't even vaguely related. For your CL you need to use: rscadd, bugfix, tweak -- it will not use the icons if you don't use the right tags.

2019-05-02 04:54 UTC, DDihanov commented
I thought the wizard change wasn't that big so I thought I would merge them.

2019-05-02 08:21 UTC, DamianX commented
Surely there's a way that doesn't require a new mob var

2019-05-02 08:39 UTC, closed without merging