global throwatstation proc
d3athrow/vgstation13 pull request #22929
Opened 2019-05-14 08:28 UTC by SonixApache

:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

2019-05-14 08:35 UTC, CyberpunkBenShapiro commented
The runtime is exactly where and what it says it is. To fix it just get rid of the forcemove proc override for the immovable rod on line 150 it's jank code anyway

2019-05-14 08:38 UTC, SonixApache commented
or i can just do that and it'll work™

2019-05-14 08:44 UTC, CyberpunkBenShapiro commented
the runtime was happening because starting was always null due to the refactor

if(null) code is clutter spaghetti and not a runtime fix

Either make sure the starting variable is defined properly or remove the override proc because an if(null) is the same as commenting it out but more confusing for someone down the line to look at

2019-05-14 08:50 UTC, SonixApache commented
I think the runtime was happening because `starting` gets set in immobilerod.dm's `throw_at` proc (L#74), which is normally called before the first `forcemove`.
I'm not sure how to set the var before moving it without more snowflake code.

2019-05-14 08:55 UTC, CyberpunkBenShapiro commented
Two ways: 
- make a rod/throwatstation proc that calls throw_at and sets the starting location for forcemove to behave correctly
- realise that the reason why that entire proc override exists is for a lazy way to check if the z level is the same as the one it spawned in and have it just be deleted when changing z levels

either or

2019-05-14 08:58 UTC, CyberpunkBenShapiro requested changes

2019-05-14 08:58 UTC, CyberpunkBenShapiro commented on code/modules/events/immovablerod.dm
> +/obj/item/projectile/immovablerod/New(atom/start)
You removed everything in this proc so you can remove this proc too

2019-05-14 08:59 UTC, SonixApache commented
The proc exists to do clang shit, alongside that small z level check.
I think this works; setting the starting var there isn't so bad since it's all local to Z-1 anyway.

2019-05-14 16:29 UTC, Blithering commented
This is neat, now we just need a throwstationat proc

2019-05-15 06:12 UTC, SGuivenne commented
Could this eventually be used to throw non rod items at station like meteors, cows, or xenomorphs?

2019-05-15 07:10 UTC, SonixApache commented
Yes, you just call `ThrowAtStation()` on the meteor, cow or xenomorph and it'll get thrown.

2019-05-17 15:36 UTC, merged