Protected Cameras
d3athrow/vgstation13 pull request #22958
Opened 2019-05-16 16:57 UTC by otatoh

[tweak] 
Protects the AI core, AI upload, bridge, captain's office, and armory from being broken at roundstart as promised in #22846. Removed the flawless camera subtype as it didn't end up being used. 

:cl:
 * tweak: The cameras in the AI core, AI upload, bridge, captain's office, and armory are now unable to be broken at roundstart.

2019-05-16 17:03 UTC, aceedex commented
In the interest of the hot milfs in your area, RD should be protected/if milf is rolled no cameras should go broken

2019-05-16 17:47 UTC, brndd commented
maybe include telecomms too

2019-05-16 17:49 UTC, DamianX commented
Why, though?

2019-05-16 17:57 UTC, brndd commented
Dunno, just feels appropriate. Most of the "high security" areas should probably be exempt from this, IMO.

2019-05-16 18:39 UTC, DamianX commented
My question was directed to the PR in general

2019-05-16 18:43 UTC, FudgePucker commented
Yeah I think more "important" areas should have their cameras protected.
The point of the chance of broken cameras is box having little to no areas being camera blind and the fact that a cut camera is a HUGE red flag. Some areas would just be retarded for a secret base.

In engineering, TEG room, CE office, PA room, singularity cameras, and SMES's. Oh and atmospherics, all of it. These areas are important and in open areas.

In medbay, Chemistry, lobby, cyro, and cloning. Open those doors AI.

In science, this is the most important area for rouge AIs. RDs office, server room, robotics, and R&D.

In security, all the doors to the armory, brig cells, and perma must be covered. HELP AI SECURITY MURDERING ME, STUN ALL OFFICERS AND FREE ME.

An important thing to note is that the more cameras not in the pool of broken cameras means more chance of broken cameras in more useful locations. All main hallway cameras.

2019-05-16 21:01 UTC, I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE commented
That's like 1/2 to 2/3 of each department

>An important thing to note is that the more cameras not in the pool of broken cameras means more chance of broken cameras in more useful locations

It's rolled per camera, no such pool

2019-05-16 21:27 UTC, bathosbathtime commented
While I personally would like it if the protected cameras only had a reduced chance to be broken, this is what was promised in the first PR and may have influenced support so it should be merged.  Assuming this PR will get the support I believe it will.

2019-05-17 00:42 UTC, SGuivenne commented
Can we please protect cameras in space.  We both know nobody will ever fucking fix those.

2019-05-17 00:43 UTC, FudgePucker commented
Space cameras being disabled is a buff to ops.

2019-05-17 03:10 UTC, Accipitermaris commented
I think broadly any area that would be considered Grand Trespass in Space Law should have protected cameras. I think that this makes the most sense from an in-universe standpoint. The AI perspective is also valid but also not one I have as strong of an opinion on. (Like Vape says, if we go off of what we think an AI will need, we'll end up whitelisting all of medbay's cameras.)

2019-05-17 08:01 UTC, TurboGay commented
> 
> 
> I think broadly any area that would be considered Grand Trespass in Space Law should have protected cameras. I think that this makes the most sense from an in-universe standpoint. The AI perspective is also valid but also not one I have as strong of an opinion on. (Like Vape says, if we go off of what we think an AI will need, we'll end up whitelisting *nearly all of medbay's cameras.)

Is it really a bad thing that an AI would have vision in a highly trafficked department like medbay though? That's usually where I open a large majority of doors for injured people when doctors aren't around to do so. This is also coming from slight bias as an AI player, but I think telescience could also do with being protected as it's typically used to help with recovering players/bodies or saving people from harm.

2019-05-17 11:06 UTC, PJB3005 requested changes
This is absolutely the wrong way to implement this. Fix the maps to use the flawless type instead.

2019-05-17 15:09 UTC, otatoh commented
Closing this to remake the PR in a less retarded way.

2019-05-17 15:09 UTC, closed without merging