Changes shoes a bit so that clown shoes make a sound every step (except advanced ones)
d3athrow/vgstation13 pull request #23111
Opened 2019-06-02 12:03 UTC by boy2mantwicethefam

Stepstaken is removed because it's not used by anything
Replaced with step_sound_counter and step_sound_threshold, the former keeps track of the steps made and gets reset when a sound happens and the latter is how many steps required until sound is played
Clown shoes now make a noise every step except for the advanced ones, but you can var-edit the advanced ones to 1 if you're insidious
:cl:
 * tweak: Clown shoes now make a noise every step. This does not apply to the advanced clown shoes.

2019-06-02 14:47 UTC, SonixApache commented
*why*

2019-06-02 14:49 UTC, boy2mantwicethefam commented
someone suggested it and it sounds fun

2019-06-02 15:26 UTC, ShiftyRail requested changes
Use the modulo `%` properly instead of using a third useless var

2019-06-02 16:11 UTC, boy2mantwicethefam commented
it's basically a shorthand for increments right?

2019-06-02 16:17 UTC, Exxion commented
No
It's the remainder
`....a: 1 2 3 4 5 6 7 8 9`
`a % 3: 1 2 0 1 2 0 1 2 0`
`a % 5: 1 2 3 4 0 1 2 3 4`

2019-06-02 16:25 UTC, boy2mantwicethefam commented
yeah that's what I mean

2019-06-02 16:26 UTC, boy2mantwicethefam commented
...I think

2019-06-02 20:04 UTC, Kharkov72 commented
too much
thats too much

2019-06-02 20:06 UTC, KingofHONK commented
![sickos](https://user-images.githubusercontent.com/24867955/58766771-7054e300-8550-11e9-9640-c1ff294cdaaf.png)

2019-06-02 20:44 UTC, boy2mantwicethefam commented
Did some tests, % is not necessary, code is also slightly clearer, reviewed code however and saw that there's no check if it's above the threshold, will fix
Also there is only one more var for a total of two vars for movement (beside the one that is the sound playing), one to keep track of how much movement left until next sound play and the other to check if it's eligible to play a sound on movement

2019-06-02 21:19 UTC, Exxion commented
No, modulo is still the correct method

2019-06-03 16:41 UTC, Intigracy commented on code/modules/clothing/clothing.dm
> -				if(stepstaken % 2 == 1)
stepstaken was used right here lol

2019-06-03 16:47 UTC, Intigracy commented
Adding thresholds as a var is fine, but there's no reason to not use modulo instead of reinventing the wheel

The clown shoes change should be its own thing honestly

2019-06-03 21:19 UTC, ShiftyRail commented
Modulo *is* the correct method. There's a reason I hit the red cross instead of the more neutral option.
There's no need for a third var when this does the job perfectly well.

2019-06-10 05:15 UTC, Kurfursten commented
This does not appear to have enough support.

2019-06-18 07:56 UTC, closed without merging