You can now kick and bite while in restraints and not pulled, tweak to canface and chair movement
d3athrow/vgstation13 pull request #23255
Opened 2019-06-14 17:34 UTC by dylanstrategie

Note to reviewers: Only functional change in objs.dm is on line 604

* You can now move with office chairs while handcuffed. You can now kick yourself off large objects while handcuffed onto an office chair
* You can now kick and bite people while handcuffed and not actively grabbed or pulled
* You can no longer face using click if you don't meet the requirements to face manually. This should not cause any edge cases
* You can now face while restrained as long as you are not being actively puled or grabbed

I'm aware the RestrainedClickOn proc looks ugly, but trying to pass it directly to UnarmedAttack allowed mobs to open airlocks and do other interactions that are not kosher for cuffed people, so... fun ? If anyone spots a better way to do it, go ahead and guide me

Otherwise, well... it will have an impact on balance for sure. Especially handcuffed people being able to bite and kick when someone is not actively keeping them in a good cuff grab, but hey, immersions, right ?

:cl:
 * rscadd: You can now move with office chairs while handcuffed. You can now kick yourself off large objects while handcuffed onto an office chair
 * rscadd: You can now kick and bite people while handcuffed and not actively grabbed or pulled
 * rscadd: You can now face while restrained as long as you are not being actively puled or grabbed

2019-06-14 18:05 UTC, ancientpower commented
Balance shouldn't be too big of a concern since kicking and biting won't really help you escape, and resisting arrest gives security a good reason to blow your brains out on the spot instead of making you serve a few minutes in the brig.

2019-06-14 18:27 UTC, Chazach commented
based and kill prisoners pilled

2019-06-14 19:04 UTC, Tokanova commented
what if kicking while cuffed an shit had a high chance of causing you to fall over since you can't use your arms to balance yourself

2019-06-14 21:05 UTC, DrSnips commented
Time to carry chloral as sec in case my tard hits their teething phase.

2019-06-14 21:07 UTC, AI-Is-Rogue commented
>You can now kick and bite people while handcuffed and not actively grabbed or pulled.

>and not actively grabbed or pulled

very naisu

2019-06-14 21:22 UTC, RealestEstate commented
this isn’t even as much of a sec nerf as it an antag-who-tries-to-kidnap nerf, but it’s still nice

2019-06-14 21:47 UTC, ShiftyRail commented
Why aren't you doing this in UnharmedAttack again 
If it is a `restrained` check I'm sure you can change it

2019-06-14 22:21 UTC, nuklearcellphoneg commented
Kill all security mains!!

2019-06-15 03:08 UTC, utilitas- commented
Make sure you still can't kick with bolas, and cannot bite with anything covering your face/a muzzle.
Also, using bite with a helmet on should headbutt, but that's a different beast.

2019-06-16 21:15 UTC, SonixApache commented
\>You can no longer face using click if you don't meet the requirements to face manually. This should not cause any edge cases
Sad, I enjoyed staring at people after being stunned.

2019-06-17 08:41 UTC, ShiftyRail commented
One of these days I'm going to regex all ifs to the proper, valid and logical syntax which is with a space after the keyword
`if` isn't a function, it's a keyword, it makes sense to have a space after

2019-06-17 08:48 UTC, ShiftyRail requested changes
I'm really not confident with using a `ClickOn` proc for something so concrete.
If there's a `UnharmedAttack` proc that exists, _use it_. Ensure that it will behave nicely and that there areno exploits.

Using such a direct Click-code proc for something like this is old-code tier, it will cause trouble down the line if we ever want to implement more things to do if we are restrained. It will hard to find and debug if we ever need to fix it or tweak it.

It also completely goes against the elegant logic of having concrete procs for concrete things (`attack`, `attackBy`, `bite_act`...) and abstract procs for abstract things.

2019-06-17 08:48 UTC, ShiftyRail commented on code/_onclick/other_mobs.dm
> +				delayNextAttack(-20) //This is only called when the kick fails
Can you explain why this is a negative value ?
Surely there is a proper way to reset all delays, rather than using a negative value for the delay

2019-06-17 08:48 UTC, ShiftyRail commented on code/_onclick/other_mobs.dm
> +		if(attack_type == ATTACK_KICK)
You should use a switch construct for this

2019-06-17 08:48 UTC, ShiftyRail commented on code/_onclick/other_mobs.dm
> +	if(!is_pacified() && a_intent == "hurt" && A.loc != src && !grabbed_by.len && !pulledby)
There must be a define for `"hurt"`, better to use it rather than a string

2019-06-17 16:01 UTC, dylanstrategie commented on code/_onclick/other_mobs.dm
> +				delayNextAttack(-20) //This is only called when the kick fails
Unsure, I can remove it if needed, but it's the way it is in UnarmedAttack

2019-06-17 16:02 UTC, dylanstrategie commented
The main issue with hooking into UnarmedAttack is that it's REALLY fucky and leads to exploits right off the bat, and making it work would essentially mean I'm already doing every check that UnarmedAttack is currently doing. Hence the proc bypass

2019-06-18 08:34 UTC, ShiftyRail commented on code/_onclick/other_mobs.dm
> +				delayNextAttack(-20) //This is only called when the kick fails
Fair enough

2019-06-18 08:35 UTC, ShiftyRail commented
The effort required is worth it. Please keep our click code readable

2019-07-20 17:26 UTC, SonixApache commented
dylaaaaaaaaan

2019-08-14 08:46 UTC, ShiftyRail commented
Fix it

2019-08-23 15:01 UTC, Lokiamis commented
Big D

2019-09-22 11:16 UTC, Kurfursten commented
You may request to have this reopened

2019-09-22 11:16 UTC, closed without merging