Adds new fat religion
d3athrow/vgstation13 pull request #23439
Opened 2019-07-06 22:58 UTC by Kharkov72

The fat religion!
Converting people to it makes them too absolute units, the incense has a 5% chance to give you a small amount of nutriment.
Keywords include obesity, fat, obese, and absolute unit.
![apple pie](https://user-images.githubusercontent.com/25846834/60761874-f7015200-a01f-11e9-9a77-8b9325d5d157.png)

:cl:
 * rscadd: Adds the fat religion.

2019-07-06 23:07 UTC, DrSnips commented on code/modules/reagents/Chemistry-Reagents.dm
> +	description = "This fragrance reminds you of a nice home-cooked meal, and sometimes even feels like it fills you up.."
..

2019-07-07 03:52 UTC, BomberBro commented
![taft](https://user-images.githubusercontent.com/51391726/60763749-a51cf400-a040-11e9-9817-76b8eedfac21.jpg)

2019-07-08 17:39 UTC, Kurfursten commented
I think @DeityLink had objections to increasing the number of non-flower based incenses, hence our compromise on plump helmets.

2019-07-09 01:27 UTC, DeityLink commented
I guess we can make an exception for cornoil since it's got a very distinct smell.

2019-07-09 05:42 UTC, Kurfursten requested changes
You need to add a fragrance to the grown corn item, so that you can make more sticks

2019-07-09 14:38 UTC, Kurfursten approved these changes

2019-07-09 14:38 UTC, merged