Adds instant-orderable insulated gloves to the black market.
d3athrow/vgstation13 pull request #23798
Opened 2019-08-08 16:51 UTC by MadmanMartian

Available at roughly the same price as the full supply pack from cargo

:cl:
 * rscadd: Adds insulated gloves to the black market.

2019-08-08 16:55 UTC, boy2mantwicethefam commented
It's tactical!

2019-08-08 16:59 UTC, jknpj commented
I get the reference

2019-08-08 17:14 UTC, ShiftyRail commented
Sneaky coders

2019-08-08 17:39 UTC, SonixApache commented on code/modules/clothing/gloves/color.dm
> +	siemens_coefficient = 1
😒

2019-08-08 17:39 UTC, SonixApache commented
i don't get the reference

2019-08-08 20:51 UTC, GlassEclipse commented
What if instead of always being fake, you made it have a 15% fake, 70% real, 15% to be fake and have superglue in them

2019-08-10 04:09 UTC, brndd requested changes

2019-08-10 04:09 UTC, brndd commented on code/modules/clothing/gloves/color.dm
> +	desc = "These gloves will protect the wearer from ecstatic shock."
change this to "eclectic shock" please

2019-08-10 19:17 UTC, Intigracy commented
This is just a trap for people who don't read github.

At least the fake insulateds that spawn on the map have a chance of being real.

2019-08-18 23:52 UTC, Kurfursten commented
Needs accurate changelog. No lying in cls except for april fools, even if the desc gives it away.

2019-08-30 16:29 UTC, MadmanMartian commented
Giving away everything in the changelog is pretty boring

2019-08-30 22:25 UTC, Intigracy commented
noob traps are still gay

2019-09-03 01:23 UTC, MadmanMartian commented
Budget insulated gloves

2019-09-06 23:03 UTC, Intigracy commented
Budget insulated gloves have a random coefficient assigned when they're created.

These are always fake.

2019-09-22 11:22 UTC, Kurfursten commented
Let's compromise on "yellow" gloves. Fix conflicts and you're in.

2019-10-07 19:40 UTC, MadmanMartian commented
fun is verboten

2019-10-07 19:40 UTC, closed without merging