Snaxi Hotfixes
d3athrow/vgstation13 pull request #23911
Opened 2019-08-17 23:35 UTC by GlassEclipse

Speedmerge thnx
should fix building in snow, 33.259103% tested. also minor other changes + apparently my ide likes adding tabs

2019-08-17 23:41 UTC, GlassEclipse commented
Okay tested it actually and it works (apparently turfs change themselves to the new turf when built upon e.g. lattice instead of deleting and making a new one). Bandaid fix doesnt realllllly work

2019-08-18 01:52 UTC, plosky1 commented
All the mine tiles are regular mine tiles so...yeah.

2019-08-19 03:06 UTC, Kurfursten requested changes

2019-08-19 03:06 UTC, Kurfursten commented on code/game/turfs/unsimulated/snow.dm
> +		sleep(rand(3 MINUTES, 6 MINUTES))
Substance change not logged

2019-08-19 03:06 UTC, Kurfursten commented on code/game/turfs/unsimulated/snow.dm
> +			temperature = T_ARCTIC-20
:cl: this too

2019-08-19 03:06 UTC, Kurfursten commented on code/game/turfs/unsimulated/snow.dm
> +	snow_state = 0
There has to be a better implementation. Will look into this later. Do you have the runtime?

2019-08-19 18:37 UTC, GlassEclipse commented on code/game/turfs/unsimulated/snow.dm
> +	snow_state = 0
Yeah there's an out of bounds exception in /proc/cache_snowtile()
for(var/i = 1 to overlay_counts[parent.snow_state+1])
overlay_counts is out of bounds. I checked and apparently the snow_state gets up to 6, if you look at greaten_snowfall and lessen_snowfall I'm not really sure how. The New() fix didn't seem to work.

2019-08-19 18:38 UTC, GlassEclipse commented on code/game/turfs/unsimulated/snow.dm
> +	snow_state = 0
Also, this only happens on mine tiles. Not the permafrost tiles that make up the pathways

2019-08-19 18:39 UTC, Kurfursten commented on code/game/turfs/unsimulated/snow.dm
> +	snow_state = 0
Just paste the whole runtime here or in a hastebin

2019-08-20 01:05 UTC, SonixApache commented
did you cut the 5 minute sound files into smaller bites yet so it doesn't lag every time someone steps outside?

2019-08-20 15:05 UTC, GlassEclipse commented
It doesn't lag after it gets loaded. If there isn't a way to load it normally, I'm just going to make a proc that instantly plays a sound then stops called load_sound(), then set snowstorms to load on roundstart

2019-08-20 16:47 UTC, SonixApache commented
or you could just cut the sound file into a bunch of more manageable files

2019-08-20 22:53 UTC, GlassEclipse commented
Why don't YOU cut admin ogg's into managable files, those are 5 mins long.
It's honestly strange that it lags at all, thanks byond

2019-08-21 07:01 UTC, GlassEclipse commented
Alright, I fixed everything except the minor lag whenever hearing snowstorm sound for the first time.

2019-08-21 12:22 UTC, SonixApache commented
what you could do is cut the 5 minute snowstorm sound file into a bunch of managable bits that have fade-ins and fade-outs - that way you could play them randomly to prevent sameysound AND not lag people at the same time

2019-08-21 12:53 UTC, GlassEclipse commented
In another PR, sure. But this has important HOTfixes in it.

2019-08-22 00:06 UTC, MadmanMartian commented on code/game/turfs/turf.dm
> +	if(istype(src,/turf))
This will never not be true

2019-08-22 01:05 UTC, GlassEclipse commented on code/game/turfs/turf.dm
> +	if(istype(src,/turf))
True.

2019-08-22 02:16 UTC, merged