Cultist Cyborgs (4th time's the charm)
d3athrow/vgstation13 pull request #23995
Opened 2019-08-26 03:28 UTC by GlassEclipse

This time I've fixed all the minor requested changes. It is now producible at the robotic fabricator with similar requirements to the H.O.N.K. board. In addition, it now has a cute culthugborg sprite and works on hugborgs AND service borgs.

:cl:
 * rscadd: Cultist borg board added to the robofab. It requires 3 materials and 1 NT research. It uses phazon.

2019-08-26 03:30 UTC, Kharkov72 commented
I suggest making the design take bananium instead of phazon, cleaning up the design path to be clearer, and posting the absolutely blessed sprite to remind people what it looks like

2019-08-26 03:31 UTC, GlassEclipse commented
Phazon good, bananium bad. It's basically the phazon version of the H.O.N.K. upgrade, so I'll keep it this way.

2019-08-26 09:34 UTC, boy2mantwicethefam commented
FINALLY TGBORGS

2019-08-26 10:40 UTC, SonixApache commented
how many times do we have to teach you this lesson old man

2019-08-26 10:59 UTC, ShiftyRail commented
I think it's a silly idea to artificially toe the line between a real antag and a "fake" antag.

2019-08-26 12:02 UTC, GlassEclipse commented
It was literally in the game and it was fun. Y'all got issues.

2019-08-26 12:10 UTC, jknpj commented
>supernatural and arcane
>needs no anomaly research
arcane research when

2019-08-26 14:58 UTC, tuypo1 commented
I thought the previous opposition was due to the black market, why the hell does this still have so many down votes.
Sure it should probably be strictly hugborg only but that will become apparent and be fixed in a few weeks anyway so we may as well let it go through as is for now just to see what happens.

2019-08-26 15:24 UTC, jknpj commented
>why the hell does this still have so many down votes

maybe because

>Sure it should probably be strictly hugborg only

2019-08-26 16:15 UTC, ghost commented
Add a way to get the hugborg reliably and maybe. When you have to pray you're in the deadpool when one is found, that means the people who actually try to be a cultborg will never actually get it.

2019-08-26 17:25 UTC, SonixApache commented
You say that as if cultborgs should be a common feature.

2019-08-26 21:46 UTC, ghost commented
It's not common, I'm trying to make it so that any person who WANTS to get it can work hard to become one.

2019-08-26 21:58 UTC, Blithering commented
I could make an alternate sprite for a really cult one if not being sure if its a friendly cult borg or a cult cult borg is an issue, similar to red eye MoMMIs.

2019-08-26 22:27 UTC, ghost commented
And I'll repost my logic here:
Having it be a hugborg exclusive means that you have to have 3 things happen to become one:
>Hugborg gets found (RNG)
>You're dead while it gets found (RNG) and get RNG picked to become the controller
>A scientist finds phazon for you and researches enough to print out the board 

This is all RNG. That's not how shit should work.
>You play cargo borg at roundstart.
>You work with sci to go to the clown roid and get phazon, then push scientists to get NT research so you can print out the board.
>You get to enjoy meme runes for some effort.

That's the better option. And keep in mind you can do the same thing with phazon for a noclip, super fast mech with an extra module slot that's infinitely producible.

2019-08-28 10:26 UTC, jknpj commented
>with an extra module slot that's infinitely producible.

Do not let your bugs be dreams

2019-08-28 14:04 UTC, SonixApache commented
phazon is literally stupidly easy to get
hugborg upgrade packs are emergent gameplay
if you make it a hugborg-only thing you can probably lower the material/research requirements for the board

2019-08-28 16:46 UTC, tuypo1 commented
On the one hand glasses reasoning for having it on service borgs does make a lot of sense
On the other hand it could still become too common
There is no easy answer

2019-08-28 16:49 UTC, ghost commented
Again, too common. How often do you see phazons? Phazons are objectively 100x as useful as a borg that can print cookies with blood, and people are tired of it and we don't see it that often. Once the initial hype dies down (during which I don't even expect to see it THAT often), it'll be a rare occurence.

2019-08-28 17:58 UTC, SonixApache commented
How often do I see phazon? Literally every round now that we've got a xenobiology autist active.
Phazon is STUPIDLY easy to get with slimes. I don't remember if phazon was blocked from the matter synth, but I can only assume it isn't and thus is double stupidly easy to mass produce.

Making cultborgs common, making hugborg sprites common is very dumb.

2019-08-28 18:13 UTC, jknpj requested changes

2019-08-28 18:13 UTC, jknpj commented on code/game/objects/items/robot/robot_upgrades.dm
> +	new_icons += list("Cult" = "cultborg")
Nah. Don't give hugborg icon to non-hugborg borgs. Check how the other upgrades do it.

2019-08-29 06:52 UTC, ghost commented on code/game/objects/items/robot/robot_upgrades.dm
> +	new_icons += list("Cult" = "cultborg")
I would like the service borg to use hugborg icon since we don't have any skin for service borgs. I guess I could just make it hugborg only...
But then I would add hugborg to the black market :3

2019-08-30 15:05 UTC, GlassEclipse commented
But again, why is it okay to have a noclip superfast 4 module mech if you have easy-to-get phazon? I would much rather have this RP tool than powergame mech(TM).

2019-08-30 16:35 UTC, SonixApache commented
\>RP tool

😒

2019-08-31 10:40 UTC, MadmanMartian commented
>arcane research when

How about now?

2019-08-31 20:44 UTC, GlassEclipse commented
Yeah chain hug really makes me want to powergame, phazons are good Ar Pe though.

2019-09-22 11:19 UTC, Kurfursten commented
no public support, and I'll say even though I think it's absurd it's a little bit of a shame to lose out on that sprite

2019-09-22 11:19 UTC, closed without merging

2019-10-17 17:10 UTC, Blithering commented
While this borg PR has been shot down a lot, the code itself seems to be relatively well received. Since the month of spooky things is well underway, perhaps it could see life as a default option only while Halloween holiday stuff is enabled?

2019-10-17 17:31 UTC, jknpj commented
Only if someone is willing to remake the PR and fix the conflicts