Fixes unlit welding tools repairing robotic limbs for free
d3athrow/vgstation13 pull request #24142
Opened 2019-09-12 14:10 UTC by Shaska-

Fixes #23776

:cl:
 * bugfix: Welding tools now have to be turned on to fix robotic limbs

2019-09-12 14:46 UTC, MadmanMartian requested changes
Add a use_fuel(amount) just before the S.heal_damage call

2019-09-12 15:27 UTC, Shaska- commented
Like this?

2019-09-12 21:29 UTC, Kurfursten commented on code/game/objects/items/weapons/tools.dm
> +				to_chat(user, "You press \the unlit [src] against [user == M ? "your" : "[M]'s"] [S.display_name], but nothing happens.")
format this with span class='warning' or 'notice'. Either one is acceptable so you can pick.

Warning is often used for fail messages but I think I like notice here because it's blue text (usually to indicate 'safe', like gently pushing someone on help intent) in contrast to the bold red attack format.

2019-09-12 21:48 UTC, Shaska- commented on code/game/objects/items/weapons/tools.dm
> +				to_chat(user, "You press \the unlit [src] against [user == M ? "your" : "[M]'s"] [S.display_name], but nothing happens.")
Yeah, notice seems to fit a lot better than warning, so I went with that.

2019-09-16 07:23 UTC, Kurfursten commented
ye like that

2019-09-16 07:23 UTC, merged