Fixes Simple Animals Becoming Traitors
d3athrow/vgstation13 pull request #24685
Opened 2019-10-31 03:30 UTC by Shadowmech88

Fixes #8446.

This excludes simple animals from becoming traitors. While I personally think it's pretty funny, and would be happy to change the PR to exclude mice specifically (since they can't even drag things), the bug does appear to be that animals at all are included.

Also, I don't know enough about role datums to test this, so I'll need someone to let me know what admin buttons to push in order to do so.

:cl:
 * bugfix: Simple animals can no longer be autotraitored.

2019-11-03 17:56 UTC, Probe1 commented
Would this effect secret mode anyway?

2019-11-03 17:58 UTC, Kurfursten commented
It will *affect* secret dynamic because midround traitor can be called by autotraitor (roundstart).

2019-11-03 18:12 UTC, Probe1 commented
Gotcha.  Please make an exception for borers which are exceptional and then we're good to go.

2019-11-03 18:14 UTC, Probe1 requested changes
/mob/living/simple_animal/borer would be excluded from traitor list.  As they can possess monkeys and players, and have complex interactions with the round as opposed to mice or carp or whatever, depriving them from an antagonist role would be counterproductive.  Exclude them from the block and I'm satisfied.

Ditto for monkeys.

2019-11-03 21:28 UTC, Shadowmech88 commented
Borers are now the sole exception to the "no `simple_animal`s" rule.
Monkeys do not need an exception added, as they are `/mob/living/carbon`, not `/mob/living/simple_animal`.

2019-11-03 22:55 UTC, Probe1 approved these changes

2019-11-03 22:56 UTC, Probe1 commented
If anything else comes to mind I'll shout.  That was the big one.  If anyone didn't follow my reasoning - the change is so antag slots aren't wasted on players with very little chance of affecting the round.  If you really want to be an antag simple mod prayer is a better way of getting it than the default behavior.

If anyone can think of anything else.. maybe pAIs?  Are pAIs simple mobs?

2019-11-04 07:11 UTC, Shadowmech88 commented
I believe pAIs are silicons, same as borgs.

2019-11-04 13:27 UTC, merged