Adds Mime Goblins
d3athrow/vgstation13 pull request #25040
Opened 2019-11-15 21:26 UTC by Kharkov72

![Untitled](https://user-images.githubusercontent.com/25846834/68976737-7e2bb700-07c4-11ea-901d-a19b8f0b9db9.png)
Behold, the slightly less annoying but still annoying counterpart of the clown goblin, the mime goblin.
Instead of slipping you, it silences you (and stacks) and is made exactly how you think it would be made.
This also adds the cluwne book-gibbing to faguettes (oversight) and tweaks its emotes to not be weird for the mime goblin to make (like how clown goblins cry and such)
[content]

:cl:
 * rscadd: Adds Mime Goblins!

2019-11-15 21:54 UTC, N3X15 commented
It doesn't spam false walls?  **DENIED**

2019-11-15 23:15 UTC, Kharkov72 commented
the nightmare beings have spoken, they now make invis walls  at a 10% chance.
![Untitled](https://user-images.githubusercontent.com/25846834/68982162-e209ac00-07d3-11ea-9738-9812be0c67af.png)

2019-11-15 23:19 UTC, N3X15 requested changes

2019-11-15 23:19 UTC, N3X15 commented on code/modules/mob/living/simple_animal/hostile/retaliate/faguette.dm
> +		return
This `return` might not be necessary.

2019-11-15 23:19 UTC, N3X15 commented on code/modules/mob/living/simple_animal/hostile/retaliate/faguette.dm
> +	var/msg = pick("drools slightly","mimes crying into a tissue","sloppily mimes tieing an invisible noose")
```suggestion
	var/msg = pick("drools slightly","mimes crying into a tissue","sloppily mimes tying an invisible noose")
```

2019-11-15 23:19 UTC, DrSnips commented on code/modules/mob/living/simple_animal/hostile/retaliate/faguette.dm
> +	desc = "A tiny talking beret and gloves. Is it miming for a baguette?"
Talking mimes?

2019-11-15 23:37 UTC, Kharkov72 commented
also since the return isn't needed someone (maybe me but unatomic) can also remove it from cluwne.dm

2019-11-16 17:39 UTC, MadmanMartian commented
I had something like this on another branch. It would only be visible to those it's hunting, and only in close proximity

So, you'd see somebody getting beaten by an unseen foe, truly the mime experience

2019-11-17 08:24 UTC, Shadowmech88 commented
With a sprite and animation like that, I feel like it's meant to be accompanied by a sound like this.
https://www.youtube.com/watch?v=-hmNVq6HUfQ

2019-11-17 18:28 UTC, Kharkov72 commented
They now slap around, thus it is decreed.

2019-11-17 18:34 UTC, Kharkov72 commented
>animal.dmi gets smaller
🤔 
I checked and made sure no sprites were getting yeeted into the void though.

2019-11-18 21:05 UTC, GermanSanta commented
This brings up the age old debate. Should mimes ever make a sound?

2019-11-20 14:09 UTC, Zth-- commented
> I checked and made sure no sprites were getting yeeted into the void though.

good enough

2019-11-20 14:09 UTC, merged