Clown Psychedelic Suit
d3athrow/vgstation13 pull request #25057
Opened 2019-11-17 01:36 UTC by GermanSanta

Have you ever had a project that drove you insane? Insanity is spending 4+ hours spriting this definition of insanity clown suit. Adding up to a grand total of 336 sprites.

192 in-hand sprites
24 Floor Sprites 
24 uniform sprites
24 uniform fat sprites 
24 backpack sprites 
24 Mob Mask Sprites
24 Shoe sprites

Then coding this all in neatly into the contraband autodrobe. 

Special Thanks to Vonadi for donating 55 sprites. In spriting, the fat psychedelic clown suit, giggles neon honkington, and giggles neon honkington's floor sprite. 
![gYIutUC_RziNCswH4kBPYg](https://user-images.githubusercontent.com/52895053/69001663-6af21780-08a8-11ea-81fb-ffe108869259.png)

Can't thank you enough for saving me all that work buddy.

2019-11-17 02:02 UTC, SonixApache commented
madman

2019-11-17 03:15 UTC, Zth-- commented
Good job. Post a gif so we can see it in action

2019-11-17 03:48 UTC, GermanSanta commented
![Clowngif](https://user-images.githubusercontent.com/52895053/69002747-bad9da00-08ba-11ea-84ac-ca5172c6d710.gif)

2019-11-17 04:20 UTC, GermanSanta commented
![clowngif](https://user-images.githubusercontent.com/52895053/69002949-48b7c400-08bf-11ea-8361-3555ec81f44b.gif)

2019-11-17 08:03 UTC, boy2mantwicethefam commented
Visual earrape

2019-11-17 09:01 UTC, ShiftyRail commented
It's content and therefore inherently good

2019-11-17 09:13 UTC, brndd commented
I have synesthesia and this is definitely raping my ears.

2019-11-17 09:15 UTC, brndd commented
Also, I hope I never see this in game but I'm updooting anyway.

2019-11-17 23:10 UTC, N3X15 commented
why

2019-11-18 01:20 UTC, Zth-- requested changes

2019-11-18 01:20 UTC, Zth-- commented on code/modules/clothing/under/miscellaneous.dm
> +	flags = HIDEBEARDHAIR
Remove this line

2019-11-18 01:20 UTC, Zth-- commented on code/modules/clothing/under/miscellaneous.dm
> +	body_parts_covered = FULL_HEAD|BEARD
Remove this change, leave it as `body_parts_covered = FULL_HEAD|BEARD|HIDEHAIR`

2019-11-18 01:35 UTC, Zth-- approved these changes

2019-11-18 15:31 UTC, FudgePucker commented
Change log

2019-11-19 11:55 UTC, Zth-- commented
In my opinion the animation's speed should be tuned down, it's way too harsh at its current state

2019-11-19 19:38 UTC, GermanSanta commented
Well you're not going to believe this one but Vonadi's current rate was twice as fast as it is now. The current animation speed is the same of that as the default psychedelic suit

2019-11-20 17:55 UTC, merged