Adds machine breakdowns and repairs
d3athrow/vgstation13 pull request #25101
Opened 2019-11-20 01:59 UTC by Goldsteel

[discussion][wip][gameplay][tweak]

There are many issues with this addition and it's not done yet. Many machines will need subtle changes, or in the case of telecommunications, breakdown immunity. There is an argument that machines should only break down WHEN IN USE rather than powered on and idle and another argument that breakdowns are unfun and uninteresting as a mechanic (pun not intended).

The original goal was to make mechanics have more of a responsibility to repair and replace wear and tear during a round, as currently they're just a loose end neither engineering nor science.

Sounds and icons are currently temporary and will be updated with something better than the cyborg component and windows crash sound. Don't worry.

Features:
(1) The subsystem checks every 2 seconds to see if a machine will break down, with a low probability. This is undecided as of yet.
(2) When a machine breaks down, it will power off and become unusable. It will report this to people and have an examine text to say it's broken.
(3) Broken machines can be screwdrivered and disassembled to replace broken bits.
(4) Broken bits are made by changing the part rating to -1, changing the icon and denoting them as broken.
(5) RPED/BRPED devices can effectively identify and replace broken parts and remove the broken flag if they find the culprit. This is faster and is encouraged. This change might follow a suggestion to give the mechanics 1 RPED at shift start.
(6) Machines that are powered down do NOT experience breakdowns.
(7) The code probably won't eat the circuit board this time.

Here's an example of it working:

![image](https://user-images.githubusercontent.com/28162068/69202104-6d6aa080-0b38-11ea-995b-27329afda172.png)

This is an older image, as the parts are now named properly. They drop if the machine contents is dumped on the floor through crowbaring.

![image](https://user-images.githubusercontent.com/28162068/69202143-8ffcb980-0b38-11ea-8389-652d800773f9.png)

I experienced a telecomms breakdown and had to spend time relinking all the machines to the bus, but it works just fine. 

:cl:
 * tweak: Machines now have a low chance to break down during a round. To counter this, a supply of parts will be needed to keep things running. The RPED and it's bluespace counterpart can be used to efficiently repair devices and replace components. Repairs can be done by hand, much slower.

2019-11-20 02:01 UTC, MadmanMartian commented on code/modules/power/power.dm
> +	if(BROKEN) // See machine breakdowns in machinery/machinery.dm
???

2019-11-20 02:01 UTC, Kharkov72 commented
Reposting that I would rather it be a new random event / something tha happens when it's fucked with (EMPs?) rather than something that can just randomly happen

2019-11-20 02:04 UTC, Goldsteel commented on code/modules/power/power.dm
> +	if(BROKEN) // See machine breakdowns in machinery/machinery.dm
oversight, removed

2019-11-20 02:06 UTC, aceedex commented
Neat idea that isn't very infringent on mechanics' more laid back approach.
All I really have to note is that SMES should have a damn high break tolerance, and that machines shouldn't become completely useless if they break to save some headache for those 5 man 4am rounds and should instead severely lose efficiency

2019-11-20 02:08 UTC, Goldsteel commented
The idea of machines becoming less efficient is on the table. This is just one implementation of the idea. You can set custom break chances (or 0 for never) for machines like the SMES and telecomms.

2019-11-20 02:20 UTC, DrSnips commented
No

2019-11-20 03:06 UTC, BomberBro commented
I'd be all for maybe weapons being able to damage machinery (shooting up an autolathe or toolboxing a console to break it), but having them just break for no reason or even a gay random event is just pointless busywork for the sake of busywork.

2019-11-20 03:50 UTC, ancientpower commented
Add a flag to disable this for certain machines and have it be part of ion storm and electrical overload instead of a per-machine basis.

2019-11-20 13:49 UTC, SonixApache commented
testmerge

2019-11-20 14:27 UTC, FudgePucker commented
Awful fucking idea.

First off the only jobs with access to spare parts are notorious shutters. The mechanic was lynched for spare rushing, the scientists will ignore you, and cargo has declared independence. Guess you gotta break into secure tech storage.

Secondly this will make the wild ride even more unbearable. Oh boy the cyrotube with the cyromix broke, time to be shoved into the empty cyrotube until the round ends.

Finally, mechanics are fucking awful and relying on a job filled with shitters just because of random chance bullshit is fucking stupid. It's like expecting assistants to fucking assist.

2019-11-20 14:55 UTC, MadmanMartian commented
Fudge, the cryo cell can't break as it's on the atmos machine sub, not the main machine sub, so in this itteration it can't break down.

2019-11-20 19:28 UTC, Goldsteel commented
I've taken on Bomberbros advice. I am now in the process of coding shooting/kicking/attacking machines having a chance of breakdown. Machines no longer break randomly, they must be smashed.

2019-11-20 19:33 UTC, FudgePucker commented
Kicking machines breaking componants will anger the science meta club because the fastest way to deconstruct stuff is to kick it.

2019-11-20 19:38 UTC, Goldsteel commented
I can always just set the DA to be breakdown 0 and put a meme in it's description about "Having a kickplate"

2019-11-20 20:27 UTC, Goldsteel commented
I'll be putting this on hold while r0b0 implements a system for machine health. Hopefully it will make more sense to have machines hold a HP value that decreases when they're damaged/used (perhaps healing machines with nanopaste?). If a machine drops to 0 HP then the breakdowns will fire.

2019-11-21 18:58 UTC, Goldsteel commented
Machines now have a HP value that decreases when they're shot or kicked (kick damage is only 1, don't lose your shit just yet). If a machine is just worn, you can apply nanopaste to it to give it it's HP back to 100.

Here's some examples of this working:

Nanopaste repairs to non-broken down machines.
![image](https://user-images.githubusercontent.com/28162068/69367615-81291a80-0c90-11ea-9304-84b3729fff07.png)
![image](https://user-images.githubusercontent.com/28162068/69367628-871efb80-0c90-11ea-8bd7-aabd77adee0d.png)

Doing damage to machines makes them break down with no RNG involved, currently.
![image](https://user-images.githubusercontent.com/28162068/69367716-afa6f580-0c90-11ea-992f-a39b9f4358af.png)

Offending components can be removed with an RPED/BRPED and replaced, or done manually a lot slower. This restores the machine to full HP.
![image](https://user-images.githubusercontent.com/28162068/69367752-c0576b80-0c90-11ea-8bbb-9f1f8a101874.png)
![image](https://user-images.githubusercontent.com/28162068/69367785-d1a07800-0c90-11ea-8db7-141baea270e3.png)

I'm working on dealing with all the snowflake machines and vendors, but it shouldn't be too difficult.

2019-11-22 01:38 UTC, Goldsteel commented
So, it turns out computers are a machine subtype and this breaks them. I'll have to fix that too.

2019-11-22 07:15 UTC, tuypo1 commented
Yeah making it a random announced event instead of just a random chance on the machine itself seems like it would be a better implementation

2019-11-22 16:58 UTC, Goldsteel commented
It's no longer random. It's now a machine HP based system. Damage machines by kicking, shooting or meleeing them if the object does enough damage.

I managed to get vending machines and consoles to stop being shit.

2019-11-22 17:31 UTC, Goldsteel commented
So, it turns out, lots of consoles have unique attack_hand() overrides and many common things also are machines with no parts like airlocks, shutters, air alarms, light switchs and so on. This will take more time to reconcile.

2019-11-24 09:31 UTC, PaulRitter commented on code/game/machinery/machinery.dm
> +		return
this should be return 1 no?

2019-11-24 11:10 UTC, PaulRitter requested changes

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/machinery.dm
> +		return
this should be `return 1` no?

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/machinery.dm
> +///obj/machinery/attack_hand(mob/user as mob)
?

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/machinery.dm
> +				machine_health = max(0,machine_health - Proj.damage)
would be cleaner to make a obj/machinery/take_damage and have these two lines in there. Would also be more future proof (ex. Machines saying ouch when being damaged. i dunno)

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/machinery.dm
> +			machine_health = max(0,machine_health - 1)
would be cleaner to make a obj/machinery/take_damage and have these two lines in there. Would also be more future proof (ex. Machines saying ouch when being damaged. i dunno)

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/computer/security.dm
> +	if(stat & (BROKEN))
wont be needed if you do the `return 1` in `obj/machinery/attack_hand`

2019-11-24 11:10 UTC, PaulRitter commented on code/game/machinery/computer/arcade/arcade.dm
> +	if(stat & (BROKEN))
wont be needed if you do the `return 1` in `obj/machinery/attack_hand`

2019-11-24 20:20 UTC, Goldsteel commented
This is still a WiP. There's a lot of stuff that's just hanging around that needs to be cleaned up.

2019-12-12 15:02 UTC, Kurfursten commented
wip...

2020-01-23 13:25 UTC, Kurfursten commented
Ask any collab to reopen this if you do work on it

2020-01-23 13:25 UTC, closed without merging