Bikehorn goes off if you step on it
d3athrow/vgstation13 pull request #26514
Opened 2020-05-16 15:40 UTC by Konater

Unintentionally making it so that it also goes off if you throw it or drop it, nice!

2020-05-16 15:47 UTC, jknpj commented
Time to crash the server with my conveyor belts and air horns

2020-05-17 03:17 UTC, DamianX commented
\>haha clown funny
\>server crashes
\>this gets reverted

Sound spam is not even funny, y'all dumb as fucc

2020-05-17 05:04 UTC, FudgePucker commented
Honk honk.

2020-05-17 10:00 UTC, ShiftyRail commented
They hated @DamianX because he told the truth

2020-05-17 10:02 UTC, ShiftyRail requested changes
Add a delay to it.
```dm
/obj/item/weapon/bikehorn/Crossed(var/mob/living/AM)
        if (world.time > next_honk)
	       honk()
               next_honk = world.time + 2 SECONDS
```

2020-05-17 10:47 UTC, jackfailure commented
Can you 3d print clown horns

2020-05-17 13:07 UTC, Konater commented
I am not good with computer but doesn't honk () already have a delay

2020-05-17 21:06 UTC, DamianX commented
That's true, it looks like it won't crash the server.
It's still mega stupid because a paper airplane flying over a bikehorn that's on the ground shouldn't make it honk.

2020-05-17 23:00 UTC, Konater commented
I should cut the A then right?

2020-05-18 21:41 UTC, Exxion commented
In its current form this would allow ghosts to honk the horn. Make sure to check if the mover is a living mob or something.

2020-05-18 22:05 UTC, Konater commented
Is that bad?

2020-05-18 22:22 UTC, Exxion commented
That ghosts moving over the horn would honk it? Yes.
Also sparks, fires, and literally anything else

2020-05-25 06:06 UTC, GreatBigFailure commented
> In its current form this would allow ghosts to honk the horn. Make sure to check if the mover is a living mob or something.

What if haunted bike horn ghosts can use to honk the living

2020-05-25 14:55 UTC, FudgePucker commented
>ghosts would be able to honk the horn

It's a feature.

Seriously, ghosts can spin chairs, tell me with a serious face that haunted bike horns wouldn't be the funniest shit.

2020-05-26 02:45 UTC, GreatBigFailure commented
> Seriously, ghosts can spin chairs, tell me with a serious face that haunted bike horns wouldn't be the funniest shit.

![Spookyhonk](https://user-images.githubusercontent.com/64218965/82855475-6c487080-9ed9-11ea-928f-7151f2bd5bf8.png)

600 hours in dream maker

2020-05-26 19:41 UTC, Exxion commented
Ghosts honking bikehorns on purpose would potentially be OK. Ghosts honking bikehorns any time they move over them wouldn't.

2020-07-02 13:14 UTC, DamianX commented
Re-open if you ever fix this, or don't

2020-07-02 13:14 UTC, closed without merging