Small RPED QoL change
d3athrow/vgstation13 pull request #26942
Opened 2020-06-23 12:10 UTC by robosperg

Open to changing to tier 5 or something similar to prevent dropping entirely with parts
:cl:
 * rsctweak: Console screens now considered a tier four part, should prevent it from dropping with tier ones when you use RPED/BRPED in hand

2020-06-23 12:10 UTC, robosperg commented
also 100% untested

2020-06-23 13:02 UTC, Kurfursten requested changes
I'm gonna need you to read 6 lines lower in the code

2020-06-23 15:02 UTC, Kurfursten approved these changes

2020-06-23 15:05 UTC, Kurfursten commented
While the change you've made is fine, what you **actually** need to do to get the result you want is to go into storage/bags.dm and look at bag/gadgets/mass_remove()

Make it use rped_rating() instead of just get_rating.

2020-06-24 00:01 UTC, robosperg commented
now tested and working

2020-06-24 00:43 UTC, robosperg commented
testing and working per kurf

2020-06-24 19:06 UTC, merged