Added advanced stun baton that HoS now starts with.
d3athrow/vgstation13 pull request #27086
Opened 2020-07-13 04:10 UTC by twirling-jesters

:cl:
 * rscadd: Did stuff!
 * rscdel: did other stuff!

2020-07-13 04:26 UTC, Dacendeth commented
30 second stun baton? uhhh pass.

2020-07-13 04:32 UTC, Kharkov72 commented
post the icon eggman

2020-07-13 04:36 UTC, Kurfursten commented on code/game/objects/items/weapons/stunbaton.dm
> +/obj/item/weapon/melee/baton/advbaton/New() //Pre-installing cell.
this is all inherited, remove it

2020-07-13 04:37 UTC, Kurfursten requested changes
inheritance

2020-07-13 09:26 UTC, boy2mantwicethefam commented
It can't be worse than the battering ram
or the SPS
or the flashbangs
or the shotgun
or the vector
or the 2 minute cuffs
or beepskies

2020-07-13 09:29 UTC, boy2mantwicethefam commented
oh and batons can still be equipped with batteries that make them last literally hundreds of stuns before needing to recharge, while prods drain high capacity cells in 6 hits and only stun for 10 seconds. It really can't be worse than what there already is

2020-07-13 09:32 UTC, boy2mantwicethefam commented
I didn't mention the lawgiver because fun should be allowed

2020-07-13 13:18 UTC, DrSnips commented
Could you explain a few things and maybe update the OP with some of them?
* Why is this item needed?
* Why does it start in the backpack rather than REPLACE his stun baton in his gear box in his locker?
* What's going on with the sprite. I thought the active state had an eletric effect and was lit/lighter at the tip. If it's just an issue with icon diff bot here just say so.

2020-07-13 13:43 UTC, twirling-jesters commented
> * Why is this item needed?
I feel like providing the HoS a go-to melee weapon that acts as just a slightly stronger, more efficient version of the stun baton would be worthwhile. Giving the HoS a "better baton" was something that telebatons tried to solve, but in my experience heads of security usually just opt for the standard stun baton due to its duration. This is just a slight bump up in duration (now about 4 seconds or so) which uses about half the power of a normal baton. Granted, this is my first pull request and the wiki told me to be conservative with my changes, so I didn't want to do too much to change from the standard baton model.
> * Why does it start in the backpack rather than REPLACE his stun baton in his gear box in his locker?
It would feel off-brand to put a non-standard, advanced item into a standard sec gear box. Plus, this prevents compounding urges to break into his office by not stuffing his locker with more high-value equipment. Replacing the telebaton in the locker was an option, but I feel like that still has a niche and should be left as a choice to the HoS.
> * What's going on with the sprite. I thought the active state had an eletric effect and was lit/lighter at the tip. If it's just an issue with icon diff bot here just say so.
This one might be with the icon diff bot, the active sprite for the advanced baton has the halo of light and sparks on my end.

Thank you for your questions/feedback. I've updated accordingly.

2020-07-13 18:48 UTC, Gazathor commented
why does the HoS need this, he has funny shoot gun.

2020-07-13 18:54 UTC, GreatBigFailure commented
So how long exactly does this version last? I like the concept but just "longer stun" seems a bit unfun if it lasts a super long amount.. 
Maybe make it have a 100% chance to stun when thrown or something similar.

2020-07-16 01:28 UTC, DrSnips commented
> Throwing your stun baton ever

Why would you ever do this?

2020-07-16 06:53 UTC, Theophrastus1 commented
Wow, what a useless addition to the game. Surely you couldn't be adding this for personal reasons.

2020-07-16 06:54 UTC, Theophrastus1 commented
> 
> 
> > Throwing your stun baton ever
> 
> Why would you ever do this?

For the sick takedowns to go in your ownage montage you play in the breakroom

2020-07-16 18:23 UTC, closed without merging