allows you to leave a lipstick kiss on paper
d3athrow/vgstation13 pull request #27532
Opened 2020-08-12 20:06 UTC by toomykins

i was very tired please forgive me
hold a piece of paper, click on it while having the help intent and bite intent on. makes you kiss the paper. Only leaves a mark if you have lipstick on.
:cl:
 * rscadd: Paper can now be kissed with lipstick.

2020-08-12 20:07 UTC, GreatBigFailure commented
That's cute

2020-08-12 20:17 UTC, Kurfursten commented
No stamp overlay? At least commit fully

2020-08-12 20:29 UTC, toomykins commented
i'll add a stamp overlay when i find a 6x6 kiss sprite

2020-08-12 21:25 UTC, toomykins commented
![absolute](https://user-images.githubusercontent.com/29069174/90069731-00fd8600-dcf3-11ea-9fb8-cbf7c96f68b0.png)
hope you're proud
i'll welcome any better sprite

2020-08-12 21:37 UTC, Kurfursten commented
If you make it grey you can use colors to make it match the lipstick color, like we do with reagent overlays for beakers

2020-08-12 22:21 UTC, DamianX requested changes
Check if the user has clothing that's covering the mouth.
It would also be a good idea to not copypaste this logic and improve `try_stamp` instead

2020-08-13 05:28 UTC, AI-Is-Rogue commented
Wait a sec, you used to be able to do this before. What happened?

2020-08-13 07:53 UTC, SonixApache commented
You were never able to do this before. You could use paper on your mouth to wipe off lipstick, which is something else.

2020-08-13 07:56 UTC, SonixApache commented on code/modules/paperwork/paper.dm
> +					to_chat(user, "<span class='notice'>You kiss the piece of paper, leaving a pair of lipstick lips.</span>")
`a pair of lipstick lips` - this could use rewriting, sounds weird
`leaving a lipstick impression` or something

2020-08-13 11:42 UTC, toomykins commented
lipstick can still be wiped off with paper by selecting the mouth zone and clicking yourself with the paper. applying a lipstick kiss onto a piece of paper requires you to hold the paper in your hand and then kiss it.
i've added some checks for species, specifically mouths and lips. subhumans without lips can apply lipstick, but can't kiss with it.

2020-08-13 23:20 UTC, AI-Is-Rogue commented
Oh, yeah. I thought wiping it off was the same as this. I always wondered why I couldn't leave lipstick marks on the paper.

2020-08-13 23:35 UTC, DamianX requested changes

2020-08-13 23:35 UTC, DamianX commented on code/game/objects/items/weapons/cosmetics.dm
> +		if(H.flags & SPECIES_NO_MOUTH)
```suggestion
		if(H.species.flags & SPECIES_NO_MOUTH)
```
test your code

2020-08-13 23:35 UTC, DamianX commented on code/game/objects/items/weapons/cosmetics.dm
> +			to_chat(user, "You try to apply the lipstick, but alas, you have no mouth.")
```suggestion
			to_chat(user, "<span class='warning'>You try to apply the lipstick, but alas, you have no mouth.</span>")
```

2020-08-13 23:35 UTC, DamianX commented on code/game/objects/items/weapons/cosmetics.dm
> +			to_chat(user, "Remove the equipment covering your mouth, first.")
```suggestion
			to_chat(user, "<span class='warning'>Remove the equipment covering your mouth, first.</span>")
```

2020-08-13 23:35 UTC, DamianX commented on code/modules/paperwork/paper.dm
> +			if(!(H.species.anatomy_flags & HAS_LIPS) || (H.flags & SPECIES_NO_MOUTH)) // skeletons can apply lipstick but cannot kiss
```suggestion
			if(!(H.species.anatomy_flags & HAS_LIPS) || (H.species.flags & SPECIES_NO_MOUTH)) // skeletons can apply lipstick but cannot kiss
```
test your code

2020-08-14 01:22 UTC, toomykins commented
woops, typo.
i did test my code, but since it's in an "if or" and i don't believe there's any races without mouths, with lips, it never really occured to me. thanks.

2020-08-14 10:52 UTC, tuypo1 commented
This totally won't be used for "ironic" sec trap borderline ERP

2020-08-15 13:10 UTC, cloutcode commented
lipstick in the sec dorms when?

2020-08-15 15:20 UTC, SonixApache commented
on box, there's lipstick just outside the east maint access area, in the lower locker

2020-08-21 23:56 UTC, DamianX commented on code/modules/paperwork/stamps.dm
> +proc/add_paper_overlay(obj/item/weapon/paper/P,image/stampoverlay,iconstate,Xoffset,Yoffset)
the `iconstate` parameter seems to be unused, why is it here?

2020-08-21 23:58 UTC, DamianX commented on code/modules/paperwork/stamps.dm
> +		stampoverlay.pixel_x = Yoffset * PIXEL_MULTIPLIER
These numbers seem weird. It used to be (5, -2), with your changes it becomes (2, 2). Did you test this particular case?

2020-08-22 00:03 UTC, DamianX commented on code/modules/paperwork/paper.dm
>  /obj/item/weapon/paper/attack_self(mob/living/user as mob)
It would be wise to add a cooldown to this. Before anything else in this proc, check if `(user.attack_delayer.blocked())` and return if so. After you're done kissing the paper, do `user.delayNextAttack(1 SECONDS)`. The reason for this is that each time one kisses the paper, an image is created and appended as an overlay. That is stupid but you don't necessarily have to fix it in this PR, a cooldown will suffice.

2020-08-22 06:33 UTC, toomykins commented on code/modules/paperwork/stamps.dm
> +proc/add_paper_overlay(obj/item/weapon/paper/P,image/stampoverlay,iconstate,Xoffset,Yoffset)
you're right, getting rid of it.

2020-08-22 06:39 UTC, toomykins commented on code/modules/paperwork/stamps.dm
> +		stampoverlay.pixel_x = Yoffset * PIXEL_MULTIPLIER
It used to be (5,-2) for envelopes, which are long.
it used to be -2 to 2 for x and -3 to 2 for y on paper.
you told me to improve try_stamp but this was impossible so i made a new proc, but i wanted to avoid having 4 parameters just for the rand x and y values and then also 2 parameters for the envelope values, so it's squished to just offset, with less stamping pixel offset diversity, but I think it looks fine regardless. -2 to 2 for both values still leaves 16 different spots for it to be stamped, rather than 20 on the original.

2020-08-22 06:49 UTC, toomykins commented on code/modules/paperwork/paper.dm
>  /obj/item/weapon/paper/attack_self(mob/living/user as mob)
added, although stamps don't have this.

2020-08-22 09:49 UTC, merged