new uplink item for chefs, wendigo meat
d3athrow/vgstation13 pull request #27560
Opened 2020-08-15 03:06 UTC by Feldnos

Costs 8 TC for non chefs, 2 tc for chefs

force feed it to any monkeyman to make a wendigo and release it in maintence somewhere with a whole bunch of monkeymen, watch greyshits and redshirts alike flee in terror
first pr lemme know if i need to fix anything

2020-08-15 03:11 UTC, boy2mantwicethefam commented
needs a changelog

2020-08-15 03:11 UTC, boy2mantwicethefam commented
I should look into wendigos tomorrow because they've been pretty fucked up for a while, a lot of their unique behavior is relegated to AI-only behavior and no player behavior

2020-08-15 03:14 UTC, boy2mantwicethefam commented
Oh yeah, also the wendigo transformation means the original person is gone. It's okay though, the game is meant to be dangerous

2020-08-15 03:15 UTC, GreatBigFailure requested changes

2020-08-15 03:15 UTC, GreatBigFailure commented on code/datums/uplink_item.dm
> +/datum/uplink_item/jobspecific/service/specialsauce
Forgot to change this. Should be
/datum/uplink_item/jobspecific/service/wendigomeat

2020-08-15 03:16 UTC, Feldnos commented
> Oh yeah, also the wendigo transformation means the original person is gone. It's okay though, the game is meant to be dangerous

i plan to make em like zombies but with how wendigos are right now putting a person in them is both broken and serves no purpose, since you cannot evolve while your ckey is in the body (no verb to take "bites" or consume people" and breaking bones with one hit going at super speed
for a person to transform they'd basically either have to ignore every single message while not getting to anti tox

2020-08-15 03:43 UTC, GreatBigFailure commented
I think 2TC is a bit too cheap, especially considering it's technically renewable and how strong wendigos can get. It could definitely lead to some interesting rounds though. A few super strong mobs is probably more interesting of a mobloose than a million weaker ones.

2020-08-15 03:47 UTC, Feldnos commented
> I think 2TC is a bit too cheap, especially considering it's technically renewable and how strong wendigos can get. It could definitely lead to some interesting rounds though. A few super strong mobs is probably more interesting of a mobloose than a million weaker ones.

what price do you think would be better for it?

2020-08-15 03:54 UTC, GreatBigFailure commented
Each wendigo drops 1 meat so it's not like 1 can be farmed for an infinite supply, I guess that's not much of a concern. 
Maybe 3 to 6. 6 would let them get a bundle as well, or a master trainer's belt so they can feed the wendigos, if that works? 
I'm not sure how strong each wendigo is at each tier so maybe I'm overthinking it.  If it was 6 then spending your whole TC stash on 3 mobs isn't great, though wendigo meat can be bitten a bunch of times I think.

2020-08-15 04:00 UTC, Feldnos commented
> Each wendigo drops 1 meat so it's not like 1 can be farmed for an infinite supply, I guess that's not much of a concern.
> Maybe 3 to 6. 6 would let them get a bundle as well, or a master trainer's belt so they can feed the wendigos, if that works?
> I'm not sure how strong each wendigo is at each tier so maybe I'm overthinking it. If it was 6 then spending your whole TC stash on 3 mobs isn't great, though wendigo meat can be bitten a bunch of times I think.

could make it like the vox box meat cloner, wendigo meat comes in a box, one meat, 4 human cubes ,3 lets it evolve to the next stage of the transformation, additional humans would have to be gotten manually, takes like 10 to make an alpha wendigo, although im not sure how wendigo transformation procs i have a feeling it procs on taking a bite and not actually finishing the meat, in which case i should definitely up the price

2020-08-15 04:15 UTC, Blithering commented
I think wendigos might be blacklisted from the master trainer belt, they're not quite mechahitlers, but still miniboss enemies. Plus the sprite for the second state really needs updating at this point, I should get on that.

2020-08-15 10:04 UTC, zakanater19 commented
Do they spread it by attacking or no?

2020-08-15 10:20 UTC, Feldnos commented
> Do they spread it by attacking or no?

they dont spread, no, but they evolve, much easier than zombies, and they have an okay ai that makes them somewhat of a threat for anyone not already armed to the teeth with riot armor or explosives

2020-08-15 15:18 UTC, SonixApache commented
you fucked up the 🆑 
should be like this
```
:cl:
 * rscadd: new uplink items for syndicate chefs
```

2020-08-15 15:35 UTC, dunsel-hordon commented
So explain wendingos? I thought they could also make more wendingos somehow?

2020-08-15 22:11 UTC, Blithering commented
Wendigoes get stronger by eating people, evolving into a successively stronger form two times. They can't make more wendigoes but killing one and eating the meat passes the curse to you, turning you into a new wendigo NPC.

2020-08-16 09:20 UTC, SonixApache commented
you still didn't do the :cl: right, just copypaste the entire thing

2020-09-05 12:19 UTC, DamianX commented
Votes are split, also I hate it.

2020-09-05 12:19 UTC, closed without merging