Fat gene now makes you fat
d3athrow/vgstation13 pull request #27670
Opened 2020-08-28 10:03 UTC by Stressedphysicist

Closes#27660 

:cl:
 * rscadd: Asides from adding the obesity mutation, the FAT block now also makes you fat, removing it makes you thin

2020-09-05 11:40 UTC, DamianX reviewed
This could be okay, but I wonder if instead of changing `overeatduration` itself, it could be better to make the code in `Life()` that reads `overeatduration` check for the fat gene?

2020-09-05 11:40 UTC, DamianX commented on code/game/dna/genes/goon_disabilities.dm
> +	else
This entire else clause does nothing, remove it.

2020-09-05 11:40 UTC, DamianX commented on code/game/dna/genes/goon_disabilities.dm
> +	else
This entire else clause does nothing, remove it.

2020-09-05 17:21 UTC, Stressedphysicist commented
> 
> 
> This could be okay, but I wonder if instead of changing `overeatduration` itself, it could be better to make the code in `Life()` that reads `overeatduration` check for the fat gene?

The thing is that `M_Fat` (the mutation that makes you fat) depends on the level of `overeatduration` and most of the code I have seen that deals with making the user fat works by setting `overeatduration = 600`.

I changed the Proc of the gene so the person stays fat until the gene is removed, but this might make M_Obesity useless

2020-09-05 20:08 UTC, Stressedphysicist commented
you press fat on admin panel, that person now fat
you activate fat block on thin man and he is now fat
simple as

2020-09-05 20:59 UTC, Zth-- commented
I'd like to see M_OBESITY merged into M_FAT. My reasoning is that becoming fat in-game is different than starting as a fat person and I don't see a justification for that inconsistency. It also makes sense that once you become fat is harder to become thin again

2020-09-06 22:06 UTC, Zth-- requested changes
remove M_OBESITY from setup.dm

2020-09-07 13:58 UTC, Zth-- approved these changes

2020-09-07 13:59 UTC, merged