Cluwnebans
d3athrow/vgstation13 pull request #27771
Opened 2020-09-09 16:31 UTC by ancientpower

how it works:
- cluwnebanned players can only latejoin as a cluwne
- cluwnebanned players cannot use or read (L)OOC
- cluwnebanned players are kicked upon death, and cannot rejoin the game until the next round

(sneaky cluwnebanned players can click observe while the server is initializing, but because this sets their time of death it also immediately kicks them from the server and prevents rejoining)

this is necessarily(?) hacky but seems to work fine

2020-09-09 20:32 UTC, Dacendeth commented
What if cluwne goes into a mindswap machine or a wizard shoots them with a staff of change?

2020-09-09 20:42 UTC, ancientpower commented
Those (and the mindswap spell) are both very easy to add checks to, I'll get around to them in a bit.

2020-09-09 20:44 UTC, Kurfursten commented on code/modules/mob/new_player/new_player.dm
> +		if(!ticker || ticker.current_state <= GAME_STATE_PREGAME)
due to lack of sanity, this allows you to use href exploits to join as a cluwne even if not banned

2020-09-09 21:30 UTC, SageOfLight commented
I can honk to this.

2020-09-09 21:55 UTC, KingofHONK commented
yesss...hahahaahahaa....YESSSSS

2020-09-09 21:58 UTC, ancientpower commented
Barred cluwnebanned players from mindswap, staff of change, and mind machine. If there's any IC methods of transforming/mind transfer I'm forgetting please let me know.

2020-09-10 03:16 UTC, GreatBigFailure commented
Can you force feed cluwnes? Test wendigo meat, royal gingjelly, and slime toxin on them to make sure.

2020-09-10 03:45 UTC, ancientpower commented
Tested, they can't eat or be fed and they don't metabolize any of the reagents that cause transformations.

2020-09-10 15:03 UTC, Exxion commented
If you want to be super extra thorough you can just check in `/mob/Login()` if the client is cluwnebanne and fail unless the mob is a cluwne (or rather has a var set that lets cluwnebanned players enter it or whatever)

2020-09-13 00:21 UTC, Kurfursten commented
Do what Exxion said and we'll merge it

2020-09-13 00:21 UTC, Kurfursten requested changes
What he said

2020-09-13 02:03 UTC, ancientpower commented
Done

2020-09-13 02:23 UTC, Kurfursten approved these changes

2020-09-13 02:23 UTC, merged

2020-09-13 02:42 UTC, dunsel-hordon commented
so now instead of permabanning people we cluwnebann them?