Toggle-Walk Verb
d3athrow/vgstation13 pull request #27815
Opened 2020-09-14 19:02 UTC by APCUnlocked

Adds (hopefully) a verb for toggling between walking and running, allowing for greater immersions. It will appear under the IC tab. 

[wip]

 * rscadd: Added a verb for toggling between walking/running.

2020-09-14 20:45 UTC, kernikov commented
me inhales.
me exhales.

2020-09-15 06:54 UTC, ShiftyRail commented on code/_onclick/hud/screen_objects.dm
> +			usr.toggle_move_intent()
```dm 
if (iscabon(usr)
      var/mob/living/carbon/C = usr
      C.toggle_move_intent()
```

2020-09-15 11:23 UTC, APCUnlocked commented
Should work now, tested it locally as well.

2020-09-15 12:36 UTC, ShiftyRail approved these changes

2020-09-15 13:23 UTC, SonixApache commented
>allowing for greater immersions

you mean allowing for more powergaming

2020-09-15 14:16 UTC, mrflarg commented
THIS NIGGA DOESN'T WANT TO BE BULLIED FOR WEARING MAGGIES SO HE MAKES THIS FOR HIS MACRO SHIT, HAHAHAHAHAHAHAHA

2020-09-15 18:49 UTC, DamianX requested changes
`src` is the object the proc/verb belongs to.
`usr` is the mob that started the current action.

The reason why using `usr` is incorrect here is because it's concievable that an action performed by some mob could result in a different mob's `toggle_move_intent()` being called, at which point this proc would behave incorrectly (changing `usr`'s intent instead of `src`'s).

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +	if(iscarbon(usr))
remove this and all code after it
replace it with `toggle_move_intent()` and nothing else

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +	switch(usr.m_intent)
remove all these `usr.`, so that this becomes `switch(m_intent)`, for instance.
do this to all lines inside this proc

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +	if(src.legcuffed)
remove all these `src.`, so that this becomes `if(legcuffed)`, for instance.

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +	if(istype(usr,/mob/living/carbon/alien/humanoid))
```suggestion
	if(istype(src,/mob/living/carbon/alien/humanoid))
```

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +
all this space is hurting my feelings

2020-09-15 18:49 UTC, DamianX commented on code/modules/mob/mob_movement.dm
> +
all this space is hurting my feelings

2020-09-15 19:15 UTC, ShiftyRail commented
Technically `usr` and `src` are going to be the same thing in any and all cases except an atom proc call, aren't they ?

2020-09-15 19:17 UTC, DamianX commented
With these changes alone, yes. It's possible that future code will call this new proc and expect it to behave correctly.

2020-09-16 14:24 UTC, DamianX approved these changes

2020-09-17 11:31 UTC, merged