radio jammer, jams radios
d3athrow/vgstation13 pull request #28372
Opened 2020-12-14 06:21 UTC by jjpark-kb

closes: https://github.com/vgstation-coders/vgstation13/issues/15211
:cl:
 * rscadd: Adds the radio jammer, an uplink item exclusive. The radio jammer will jam any radio output within a seven turf radius. If a radio is successfully jammed, the radio will emit a crackling sound.

2020-12-14 09:13 UTC, StreptoMutans commented
What happens if you throw the thing into the telecoms room?

2020-12-14 16:38 UTC, jjpark-kb commented
> What happens if you throw the thing into the telecoms room?

currently it only impacts radios, not telecoms.

2020-12-15 09:00 UTC, coronasaurus commented
*shuffles up to you*
*headset starts crackling*
nothin personel...

2020-12-24 14:25 UTC, jknpj requested changes
Needs to be scannable only by the syndicate mechanics scanner

2020-12-25 15:08 UTC, jjpark-kb commented
> Needs to be scannable only by the syndicate mechanics scanner

is there an item I can look at for reference?

2021-01-05 12:19 UTC, SonixApache commented
just add ```
	mech_flags = MECH_SCAN_ILLEGAL
	``` to the item deff

2021-01-16 00:37 UTC, jjpark-kb commented
I have become busy with college, so I really can't use my time to fix or continue this PR. Sorry :(

2021-01-16 00:37 UTC, closed without merging