Species Sprites + Randomized Numbers for Football Shirt
d3athrow/vgstation13 pull request #28506
Opened 2021-01-05 00:34 UTC by beesil

Adds species specific sprites for the football shirt.
Shirt number will now be one of four random variations, picked on spawn: 23 (original), 13, 69, or 56.

![image](https://user-images.githubusercontent.com/23635874/103593080-d3dc8a80-4ec2-11eb-8f90-9eefdbb0a68d.png)

:cl:
 * imageadd: Adds species sprites for the football shirt.
 * rscadd: The number on the back of the football shirt is randomized from one of four options: 23, 13, 69, or 56.

2021-01-05 15:13 UTC, Irradiation commented
NORF

2021-01-06 18:08 UTC, jknpj commented on code/modules/clothing/under/miscellaneous.dm
> +	_color = "redfootball_[shirt_number]"
Maybe...

```suggestion
	icon_state = "redfootball_[pick(23,13,69,56)]"
	item_state = icon_state
	_color = icon_state
```

2021-01-07 13:50 UTC, ShiftyRail commented on code/modules/clothing/under/miscellaneous.dm
> +	_color = "redfootball_[shirt_number]"
^ do that

2021-01-07 13:50 UTC, ShiftyRail requested changes
See suggested changes

2021-01-07 23:59 UTC, beesil commented
that's a much better way of doing it, I was lazy & copy-pasted from the greaser suit

2021-01-08 10:35 UTC, ShiftyRail approved these changes

2021-01-08 10:36 UTC, merged