Fixes Cyborg Examine Text
d3athrow/vgstation13 pull request #28575
Opened 2021-01-15 02:33 UTC by HarseTheef

Cyborg examine text is absolutely awful.  'Completely Unsalvageable' has caused many borgs to be round removed after simply getting components upgraded or were ghosted and looking around after being murdered.

![image](https://user-images.githubusercontent.com/74737391/104673223-e7e47100-56a6-11eb-9087-ddfd99b64848.png)

[tweak]

:cl:
 * tweak: Cyborg examine text upon death is more useful

2021-01-15 02:50 UTC, small-boss2 commented
>A cyborg emergency restart board will required once the necessary components are replaced.

will be

2021-01-15 04:14 UTC, PrimeDSS13 commented
I feel like the wording on this is a tad too gamey, though it is descriptive (maybe even a bit too handholdy). All the other descriptions describe it from a first-person perspective (ex. 'It looks severely dented!) and seem more like observations almost. Perhaps make it something that's more in line with other examines in the game? Maybe something like "It's in need of a restart. or "It looks like it's in need of a reboot." would fit a bit more.

2021-01-15 07:23 UTC, Kammerjunk commented
this is good cause I remember being very confused about this the first time I had to fix a borg
but also the things Prime said

2021-01-15 20:52 UTC, xeroxemnas commented
Good PR. Newfags don't even realize you can bring back dead borgs and just assume they're dead forever.

2021-01-16 12:25 UTC, jknpj commented
I'd honestly tweak the message to make it less immersion breaking

2021-01-18 19:11 UTC, Kurfursten requested changes
Massage the message into a more manageably immersive mode.

2021-01-20 21:22 UTC, HarseTheef commented
Message updated.

> On a side note, does this remove the text that informs the roboticist/fixer that the robot is ghosted? If so, it might be wise to re-implement something like that so people don't waste their time. I might just be reading it wrong though, so if I'm talking out my ass ignore this bit.

Man, I could rant about this for a few days straight.  That awful text before was entirely meaningless and misleading, because an emergency restart board will actually forcibly pull the borg back into its shell.  The text before made it look as if the user closed their client.

2021-01-20 21:41 UTC, HarseTheef commented
Message updated.

> On a side note, does this remove the text that informs the roboticist/fixer that the robot is ghosted? If so, it might be wise to re-implement something like that so people don't waste their time. I might just be reading it wrong though, so if I'm talking out my ass ignore this bit.

@PrimeDSS13 

Man, I could rant about this for a few days straight.  That awful text before was entirely meaningless and misleading, because an emergency restart board will actually forcibly pull the borg back into its shell, regardless of suicide or ghosting (There is NO escape from the horrors of cyborgification).  The text before made it look as if the user closed their client.

2021-01-20 21:43 UTC, Kurfursten approved these changes

2021-01-20 21:43 UTC, merged