Kick chargers to drop weapons
d3athrow/vgstation13 pull request #28862
Opened 2021-02-12 09:57 UTC by coldud13

Addresses #28850 and allows players to kick weapon chargers to drop the guns out of em, pretty simple.
:cl:
 * tweak: You can now kick chargers to release any weapons inside.

2021-02-12 09:59 UTC, ShiftyRail commented
What a nice buff to table-climber security

2021-02-12 14:40 UTC, Eneocho commented
Swap it from kicking to crowbaring and we have a deal.

2021-02-12 14:56 UTC, bathosbathtime commented
Using both methods would be best, I believe.

2021-02-21 21:54 UTC, Kurfursten commented on code/game/machinery/recharger.dm
> +			use_power = 1
this should be inside the prob chance

2021-02-21 21:54 UTC, Kurfursten commented on code/game/machinery/recharger.dm
> +			visible_message("<span class='notice'>\The [charging] pops out of \the [src]!</span>")
instead of pasting this, we should probably just have a proc for dropping the contained gun

2021-02-21 21:55 UTC, Kurfursten requested changes
those things I said

2021-03-14 17:58 UTC, Kurfursten commented
3 week checkin

2021-03-15 03:00 UTC, coldud13 commented
> 3 week checkin
oop forgot about this, will fix it up tonight

2021-03-19 12:36 UTC, coldud13 commented
okay crowbars work on it now

2021-04-02 23:47 UTC, Kurfursten commented
that wasn't what I asked at all!

make a proc for dropping the gun and call it from the now three (3) places that use it!

2021-04-03 05:17 UTC, Killette2 commented
We kick everything now

2021-04-11 09:11 UTC, ShiftyRail approved these changes
This is less than perfect but I don't want to live hanging for such a small change

2021-04-11 09:11 UTC, ShiftyRail commented on code/game/machinery/recharger.dm
> +			to_chat(usr, "You begin to pry out \the [charging].")
```suggestion
			to_chat(user, "You begin to pry out \the [charging].")
```

2021-04-11 09:11 UTC, ShiftyRail commented on code/game/machinery/recharger.dm
> +			to_chat(usr, "You can't pry anything out of \the [src]!")
```suggestion
			to_chat(user, "You can't pry anything out of \the [src]!")
```

2021-04-11 09:21 UTC, merged