You can no longer build robots on Castlestation
d3athrow/vgstation13 pull request #28887
Opened 2021-02-17 14:17 UTC by boy2mantwicethefam

Kept you waiting, huh?
As I mentioned in #28545 I was gonna work on this, and now Castletation's Will prevents people from building AI and Cyborgs. After all, why would you WANT machines if they're the bread and butter of tyranny?

![robots](https://pbs.twimg.com/media/EVrgQBHXQAEoysg.jpg)

:cl:
 * tweak: Castlestation will now prevent you from creating AI and Cyborgs. Unholy magics that mess with the fabric of reality are unaffected.

2021-02-17 17:23 UTC, PlausibleDeniability commented
Nice, should remove the posibrain from robotics too

2021-02-17 20:39 UTC, Dacendeth commented
if you can still build mommis posibrains still have a purpose

2021-02-17 23:46 UTC, boy2mantwicethefam commented
MoMMIs have the H-word (human) pass

2021-02-18 01:12 UTC, DamianX commented
I really, really, really like this image. Do you mind if I save it?

2021-02-18 02:13 UTC, boy2mantwicethefam commented
Me too! Save it, it's all yours my friend 😃

2021-02-19 11:16 UTC, jknpj commented
Who is "The station" ?

2021-02-21 22:08 UTC, Kurfursten requested changes

2021-02-21 22:08 UTC, Kurfursten commented on code/game/machinery/computer/ai_core.dm
> +				if(!map.map_specific_conditions("robot check"))
use defines

2021-02-22 04:54 UTC, Kurfursten requested changes
once you use defines this looks fine

2021-03-09 13:39 UTC, merged