Totally Radical Radiation Collectors
d3athrow/vgstation13 pull request #28895
Opened 2021-02-18 21:58 UTC by GreatBigFailure

Allows Jukebox radiation bursts, radio transmitters, and uranium floors, walls, and doors to generate power via radiation collectors. 

The power generated is very small. Each also has a significantly smaller range the collector must be within than the shard/singulo, limiting how many collectors each is able to affect. 

![kindarad](https://user-images.githubusercontent.com/64218965/108426379-ad23aa80-7209-11eb-8b5f-9b0305c8e2e0.png)

Jukeboxes emit about 1/5th the power of a baby singulo and have a few second cooldown between radiation bursts. Sprinting around on uranium floor wasn't able to break even on power generation:use on the empty station I tested this on. Bigger setups with more collectors will do much better.

>Why

This allows for limited freeform radiation engines to be made. Monkeymen on conveyor belts activating uranium floors while triggering infrared assemblies that release jukebox radiation, for example. Setting up the same engine is a chore. That's why people like goofy spider engines. 

**This doesn't let the particle accelerator, self charging batteries, etc generate power. Only what is listed above.** Baby steps and all that. 
[tweak]

:cl:
 * rscadd: Jukeboxes, transmitters, and uranium tiles/walls/doors now provide power to radiation collectors. Jukebox engine patent pending.

2021-02-18 22:00 UTC, jknpj commented
>Monkeymen on conveyor belts activating uranium floors while triggering infrared assemblies that release jukebox radiation, for example. 

Lag generators

2021-02-18 22:04 UTC, GreatBigFailure commented
>Lag generators

That is a concern, ya. I really don't know the different weights of things in terms of performance. I know the way the collector proc is made is for the sake of performance but whether or not it makes up for the tiles I don't know. Take a look at what it's doing and if you want it removed for now that's reasonable. 
If it causes a boatload of leg the first time it's done it's also very easy to remove, like 3 lines.

2021-02-19 07:57 UTC, mentgah commented
don't make engineering even more useless

2021-02-19 07:59 UTC, GreatBigFailure commented
> don't make engineering even more useless

I don't understand how this translates to that. This is giving engineers more creative options for engines.

2021-02-19 08:01 UTC, mentgah commented
i think they're incredibly lazy and not creative at all

2021-02-19 08:08 UTC, GreatBigFailure commented
That's fine but I don't understand how it makes engineers "more useless".

2021-02-19 17:27 UTC, gurfan commented
harvesting power from uranium tiles sounds funny and cool but the rest is just lazy and boring

2021-02-19 19:43 UTC, GreatBigFailure commented
> harvesting power from uranium tiles sounds funny and cool but the rest is just lazy and boring

I just don't get the perspective with it being lazy. In order to really get any reasonable amount of power you'd need a lot of radiation collectors set up around it. There's also no pre-built rad collector setup like the singulo or the SME so you'd need to wire and arrange them manually. You also need to use assemblies to trigger the radiation bursts adding an extra layer. Even then you'd be better off just adding more rad collectors to the singulo because it's incredibly easy to setup and produces far more power. 

I don't do engines because I find them boring. So I'm not particularly educated on it. Maybe I'm misunderstanding the flaw here. I can easily tinker with the specific numbers but if there's some flaw with the concept please explain.

2021-02-20 18:02 UTC, gurfan commented
>run to solars and grab the radio transmitter
>stick it in the sme room
>you know have a generator capable of running the station with zero maintenance and zero effort and zero chance of fucking up the station

if you find current engines boring adding even lazier ones isn't the way to go

2021-02-20 19:01 UTC, plosky1 commented
> > run to the radio room and grab the radio transmitter
> > stick it in the sme room
> > you know have a generator capable of running the station with zero maintenance and zero effort and zero chance of fucking up the station
> 
> if you find current engines boring adding even lazier ones isn't the way to go

This one does damage and he didn't state how well it would power the station.

I agree, this is a great change. The people commenting its "lazy" either don't play engineer or are just retarded. Everything in this PR requires work to setup and looks like great fun.

2021-02-20 20:37 UTC, GreatBigFailure commented
@gurfan A freshly born singulo has 100 power. As in the single tile type that dies on its own almost immediately from failed baguloosing. Every tick it sends out that 100 power to rad collectors in, if I remember right, a 20ish tile range. Each singulo tier is essentially just a 100 power difference. So the one that usually is being used to low/no maitenance power the station is jumping between 200-300 power. So the singulo is, on average, generating 250ish from (each) rad collectors. The radio transmitter generates a flat 50 (based on the 47-51 rads it inflicts on nearby humans according to the geiger counter) in a 10 tile range. 

Radio transmitters do actually overheat and auto shutdown as well. If you put it in the SME room which is an enclosed space it will overheat. You could set up a very easy cooling loop but now that's setup for far, far, far less power than the SME would generate with a similar loop. You can see how quick this would happen by turning it on in the radio maint room it's found in and just leaving it. It heats up in a few minutes and won't stay on. I fully admit this is a really lazy addition, it was harder to decide the numbers than to add the code. I think it'll add some nice flexibility though, even add options to current engines like uranium housing around the singulo collectors. 

>Zero chance of fucking up the station
Good, low power output, low risk. Tired of shuttle calls due to low power because I'm not risking a ban for half-knowing the SME.

2021-02-21 03:33 UTC, Kurfursten commented
Radio transmitters can be safely cooled with one (1) air conditioner, which is intended design because they're not an engine and shouldn't require engine tier cooling. Jukebox/radio transmitter able to radiate more power than it costs to run hurts my immersions. Unlike a shard or singularity, they aren't made of space magic. The problem is that there's not a very good way to model radiation recapture.

Overall the transmitter change is probably harmless since the numbers are tiny compared to a shard (like, a transmitter is putting off 1/32 of a minimum shard output), but it does break with the autistic spirit I feel. The bigger problem is the jukebox change. As far as I know, there is no cooldown whatsoever on pulsing a wire, meaning you can put out assloads of rads with an autoclicker sending hundreds of href requests per second.

2021-02-21 03:41 UTC, Kurfursten requested changes
Add a wire pulse cooldown

2021-02-21 03:55 UTC, GreatBigFailure commented
They don't have a cooldown? The wiki says they do. I guess it was the geiger counter cooldown making it seem that way while I was testing it. Okay fair enough, I'll add a cooldown. 
Regarding the autistic spirit and space magic: Remember that rad collectors are using plasma to something something power. Plasma is space magic.

2021-02-21 09:07 UTC, Eneocho commented
> 
> 
> They don't have a cooldown? The wiki says they do. I guess it was the geiger counter cooldown making it seem that way while I was testing it. Okay fair enough, I'll add a cooldown.
> Regarding the autistic spirit and space magic: Remember that rad collectors are using plasma to something something power. Plasma is space magic.

Imagine the uberautism someone will eventually reach. I KNOW someone will reach the MW or even GW range power using these methods and apexplasma.

2021-02-21 09:24 UTC, Kurfursten commented
For the record, adding a cooldown is good for everyone, not just reducing spammy href behavior. I realize in retrospect that you could very easily spam rads at people on live right now. No one ever thought to do it and this is a really unpleasant way to suddenly get hit with radiation poisoning.

2021-02-22 22:25 UTC, PrimeDSS13 commented
isn't that pretty unatomic and something that should be handled in another PR

2021-02-22 22:31 UTC, Kurfursten commented
Sure, it could be separated into another PR and made dependent on that PR passing.

As collaborators we have a vested interest in not creating an engine that strongly encourages people to use autoclickers and flood hrefs though.

2021-02-22 22:33 UTC, PrimeDSS13 commented
(in the interest of clarify to kurfs post above, I made a post about if a pulse delay should be in a separate PR or not but ultimately changed my mind on it and deleted it, not knowing kurf responded)

2021-02-22 22:36 UTC, Kurfursten commented
We discussed that in the coder discord, that does seem like the ideal solution. We're not out to make wire testing harder on anyone, just trying to prevent unnatural spam of a single wire type.

2021-03-02 15:01 UTC, Kurfursten approved these changes

2021-03-02 15:01 UTC, merged