Siege Cannon
d3athrow/vgstation13 pull request #29099
Opened 2021-03-29 04:18 UTC by GreatBigFailure

Siege Cannon is a new makeshift weapon intended as a (significantly) upgraded version of the current cannon. Excellent cannon sprite by Blithering.

![siegecannon](https://user-images.githubusercontent.com/64218965/112785070-2a201c00-9021-11eb-87c0-0167528932d4.png)

### Construction

Siege Cannons are made by assembling a normal cannon: gun barrel -> wheelchair -> weld, but do not add the igniter. Instead use a barricade kit on the assembly for a wooden frame, then 10 sheets of plasteel to re-enforce the barrel. Now you have your own Siege Cannon. Add welder fuel to it like a normal cannon, though it accepts 20 rather than 10.

### Damage

Siege Cannons differ from most "Just throw something really hard" style weapons, like IEDs and normal cannons, because they prefer larger projectiles over small. That means glass shards are no longer king when it comes to damage. Toolboxes are going to break some bones and a few rarely mentioned items might even do worse.
The counterplay is obviously to not stand in front of the cannon.

### Ammunition

Siege Cannons can be loaded with anything a normal cannon can and then some. They even accept humans if you want to be a death defying stuntman, or a particularly cruel warden.

![nowloadingclown](https://user-images.githubusercontent.com/64218965/112785551-38bb0300-9022-11eb-9492-7a7e83b7ad07.png)

If your munition of choice is, for some reason, humans then an obese one will hit even harder. With that said what you should really be loading is the new **cannonball**, made with 20 sheets of metal.

### Lay Siege

The real point of the Siege Cannon.
When a cannonball is fired from a Siege Cannon it becomes a wall damaging, computer destroying, machine breaking, HoS stunning projectile. Now you can siege the malf's core in the name of the king. 

![harkandverily](https://user-images.githubusercontent.com/64218965/112785827-ec23f780-9022-11eb-9d8f-ee62466080c7.png)

Mind you it may take a few shots to tear down tougher walls, and cannonballs are too bulky for one hand to carry.
Cannonballs don't just break walls, mind you. They'll also smash through the brig's windows, computers, and anything else standing between you and your plunder, yar har.

![YAAAAAR](https://user-images.githubusercontent.com/64218965/112785958-3311ed00-9023-11eb-9d16-3f5c7f1e5e7f.png)

Cannonballs can only be carried with two hands and don't have their sieging properties when thrown/fired from anything but a Siege Cannon.

Sorry.

:cl:
 * rscadd: Cannonballs can now be constructed with 20 sheets of metal.
 * rscadd: New siege cannons facilitate knight, pirate, and greyshit RP.  They also destroy walls when firing cannonballs.

2021-03-29 04:32 UTC, SageOfLight commented
CAN THE MANNONS.

2021-03-29 04:33 UTC, BomberBro commented
I like it, isn't the cannonball sprite a little big though?

2021-03-29 04:36 UTC, GreatBigFailure commented
> I like it, isn't the cannonball sprite a little big though?

Excellent cannon sprite by Blithering
Awful cannonball codersprite by me

2021-03-29 07:53 UTC, Dacendeth commented
the cannonball sprite is way to big.

2021-03-29 09:22 UTC, APCUnlocked commented
Sounds great, can't wait for the historical revolutionaries to re-enact the storming of Bastille

2021-03-29 13:58 UTC, Eneocho commented
It wrecks walls, can it wreck doors or blast doors?

2021-03-29 14:19 UTC, GreatBigFailure commented
> It wrecks walls, can it wreck doors or blast doors?

It takes much longer but yes it can destroy doors.
It mimics an explosion on most things. For airlocks it picks an explosion severity of 2 or 3. 3 just makes the airlock spark, 2 has a 25% chance of destroying it. So essentially a 12.5% chance of destroying an airlock per shot. Blast doors it tears through pretty quickly which is intentional. 
It takes a decent bit of time to get through things. Faster than disassembling them for sure and at a range but it's not one shot = no wall. It disassembles in stages and based on RNG. So wall -> partial wall -> girder -> nothing

2021-03-29 15:19 UTC, Blithering commented
I can't wait for the first malf AI to get taken out by a cargo train broadside barrage.

2021-03-30 12:38 UTC, GreatBigFailure commented
Little update:

- Limited loading items to weight class large and below. This is practically only due to mech parts being huge and therefor an instant-gib. I thought you couldn't even pick up anything bigger than large.
- Added more feedback messages when doing things
- No longer restricted filling the cannon to beaker-type containers
- You can now wrench it in place. You can still use the right click verb to rotate it while wrenched, this is intentional

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +	to_chat(user,"<span class='notice'>You unload the [src].</span>" )
```suggestion
	to_chat(user,"<span class='notice'>You unload \the [src].</span>" )
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +/obj/structure/siege_cannon/attackby(obj/item/W as obj, mob/user as mob)
`as mob` and `as objs` are not needed.

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +/obj/structure/siege_cannon/attack_hand(mob/user)
`attack_hand` is called for every kind of mob, including ghosts and dead people. While there is sanity for a human missing his hands or being restrained, there is *no* sanity for a dead human or a ghost. Add a stat check.

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +				to_chat(user,"<span class='notice'>You completely fill the [src] with [tF] units of fuel.</span>" )
```suggestion
				to_chat(user,"<span class='notice'>You completely fill \the [src] with [tF] units of fuel.</span>" )
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +		to_chat(user,"<span class='warning'>The [cAmmo] is too large to fit in the [src].</span>")
```suggestion
		to_chat(user,"<span class='warning'>The [cAmmo] is too large to fit in \the [src].</span>")
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +		to_chat(user,"<span class='notice'>You load \the [cAmmo] into the [src].</span>" )
```suggestion
		to_chat(user,"<span class='notice'>You load \the [cAmmo] into \the [src].</span>" )
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +		to_chat(user,"<span class='warning'>The [src] is already full.</span>" )
```suggestion
		to_chat(user,"<span class='warning'>\The [src] is already full.</span>" )
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +	visible_message("<span class='warning'>[user] is stuffing [C] into \the [src].</span>")
```suggestion
	visible_message("<span class='warning'>\The [user] is stuffing [C] into \the [src].</span>")
```

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +/obj/item/cannonball/proc/cannonEffect(var/atom/cTarg)
This is such a crime against OOP that I cannot in good faith support it.
Atoms already have an `hitby` proc which seems like a more natural place to put this.

2021-04-02 18:15 UTC, ShiftyRail commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +/obj/item/cannonball/proc/siegeMob(var/mob/living/L)
Likewise, `mob/hitby` is where this should go.

2021-04-02 23:43 UTC, Kurfursten requested changes
Address Shifty's review

2021-04-05 17:27 UTC, merged