Siege Cannon Bug Fix
d3athrow/vgstation13 pull request #29204
Opened 2021-04-10 23:51 UTC by GreatBigFailure

Fixes two bugs with siege cannon:
1. You could load the "grab" item
2. You could load multiple mobs as long as you attempted to load them before the first finished

By popular demand also allows anvils to be loaded if you manage to pick one up. This, shockingly, somehow isn't an instant-gib.
[bugfix]

:cl:
 * bugfix: Siege cannons can no longer load "grabs" but can load anvils.

2021-04-11 18:27 UTC, Exxion commented
Fixes #29207 
(Put that in the OP)

2021-04-12 19:35 UTC, Kurfursten requested changes

2021-04-12 19:35 UTC, Kurfursten commented on code/modules/projectiles/guns/projectile/constructable/siegecannon.dm
> +	if(loadedItem || loadedMob || istype(cAmmo, /obj/item/weapon/grab))
Instead of returning here, get the mob being grabbed and load them, for the most intuitive use of grab

2021-04-12 22:23 UTC, Kurfursten approved these changes

2021-04-12 22:23 UTC, merged