Adds emag effect for magboots
d3athrow/vgstation13 pull request #29210
Opened 2021-04-11 16:34 UTC by kane-f

[content]

Once applied, really high amount of item slowdown is applied without any of the benefits of magpulse or not slipping, cannot be reversed

:cl:
 * rscadd: Applying a cryptographic sequencer to magboots will now disrupt their mag pulse attraction system

2021-04-11 16:36 UTC, BomberBro commented
>cannot be reversed

Since magboots are both a finite and necessary resource, it might be good to have some sort of fix like being able to solder them back to normal

2021-04-11 16:40 UTC, kane-f commented
> > cannot be reversed
> 
> Since magboots are both a finite and necessary resource, it might be good to have some sort of fix like being able to solder them back to normal

Will probably add emagging them again to put them back to normal

2021-04-11 16:41 UTC, BomberBro commented
But it's an emag, it break things. It shouldn't be a magic card that can also FIX items since that's not it's "lore" purpose

2021-04-11 16:48 UTC, kane-f commented
> But it's an emag, it break things. It shouldn't be a magic card that can also FIX items since that's not it's "lore" purpose

Yeah I was thinking of the comms console, then I realised it's not fixed with an emag

2021-04-11 16:52 UTC, GreatBigFailure commented
Make using a solder on them fix them. Poor solder should get more love.

2021-04-11 16:53 UTC, kane-f commented
> Make using a solder on them fix them. Poor solder should get more love.

This has been done

2021-04-11 16:53 UTC, GreatBigFailure commented
That was fast. Almost like you had the idea before I posted that. I will still claim credit, you're welcome.

2021-04-11 16:56 UTC, kane-f commented
> That was fast. Almost like you had the idea before I posted that. I will still claim credit, you're welcome.

Earlier in the convo:

> > cannot be reversed
> 
> Since magboots are both a finite and necessary resource, it might be good to have some sort of fix like being able to solder them back to normal

2021-04-11 17:16 UTC, Eneocho commented
Will the emag then fix break the CE's Magboots?

2021-04-11 17:25 UTC, Kurfursten requested changes, later dismissed
The way you've implemented this, it can be "repaired" by just turning the shoes off and on again.

In fact, if you emag magboots that are turned off, no one would even notice because turning them on would re-adjust the speed and flags.

The solution you have here of "you just can't turn off magboots that are emagged" is an unsatisfying one. You'll never trick anyone like that.

2021-04-11 17:31 UTC, PavelCIA commented
make them unable to be turned off or taken off so people have to awkwardly shuffle to the nearest soldering iron at diona speed

2021-04-11 17:57 UTC, smalIboss commented
> 
> 
> make them unable to be turned off or taken off so people have to awkwardly shuffle to the nearest soldering iron at diona speed

this is a really good idea
they're stuck to the ground so you can't take them off, it makes sense

2021-04-11 18:17 UTC, Exxion commented
@Kurfursten If you can't turn them off, you can't fix them by turning them off. You can dislike the approach but it's not a code issue.

2021-04-11 19:34 UTC, ShiftyRail commented on code/modules/clothing/shoes/magboots.dm
> +	if(isEmag(O))
Replace this snippet by `emag_act`

2021-04-11 19:36 UTC, ShiftyRail commented
As Harris suggested, it's a finite resource, but to make it fixable with nothing more than a welder cheapens it a bit.

2021-04-11 20:21 UTC, kane-f commented on code/modules/clothing/shoes/magboots.dm
> +	if(isEmag(O))
Done

2021-04-11 20:23 UTC, kane-f commented
> Will the emag then fix break the CE's Magboots?

Magboots slowdown is stored in mag_slow, seperate from the general slowdown variable of clothing, (set in the emagging) so nothing is lost.

2021-04-11 21:00 UTC, Exxion commented
Though I don't think it's worth blocking the PR over as said above, I do agree with Kurf that this isn't a great method. It would be better if the new behavior were applied in the proc that toggles the magboots instead of only being applied once when you emag them. That way they could be turned off and on just fine and keep the behavior.

2021-04-12 19:01 UTC, jknpj commented on code/modules/clothing/shoes/magboots.dm
> +		to_chat(user, "<span class='warning'>The mag-pulse traction system cannot be turned off!</span>")
cannot be turned off?

2021-04-13 15:11 UTC, Dacendeth commented
Perhaps you should just be able to order more magboots?

2021-04-14 16:29 UTC, Eneocho commented
> 
> 
> Perhaps you should just be able to order more magboots?

A spacesuit kit. Has a normal spacesuit helmet, suit, breathing mask and magboots. Costs 150c.

2021-04-21 01:05 UTC, Eneocho commented
Since this changes the base magboot behaviour, does this affect the Syndie Magboots or the Elite Syndie Magboots?
If it does, it should either not have an effect on syndie magboots or have a positive effect due to some syndicate tech synergy.
@kane-f

2021-04-23 06:59 UTC, TGFH commented
Emagcreep. It's already one of the best possible purchases because it interacts with almost everything and has infinite uses. I don't really think it needs more.

2021-04-24 13:00 UTC, kane-f commented
> Since this changes the base magboot behaviour, does this affect the Syndie Magboots or the Elite Syndie Magboots?
> If it does, it should either not have an effect on syndie magboots or have a positive effect due to some syndicate tech synergy.
> @kane-f

I just made them immune now

2021-04-29 20:53 UTC, KingofHONK commented
> Emagcreep. It's already one of the best possible purchases because it interacts with almost everything and has infinite uses. I don't really think it needs more.

Counterpoint: Emags are a staple traitor item. There is nothing wrong with traitors having powerful items/abilities.

2021-05-04 00:31 UTC, TGFH commented
> 
> 
> > Emagcreep. It's already one of the best possible purchases because it interacts with almost everything and has infinite uses. I don't really think it needs more.
> 
> Counterpoint: Emags are a staple traitor item. There is nothing wrong with traitors having powerful items/abilities.

No, there's nothing wrong with that. I think it's an issue because if you make one item too good it just becomes a waste of TC to buy anything else.

2021-05-06 08:37 UTC, Theophrastus1 commented
> 
> 
> > > Emagcreep. It's already one of the best possible purchases because it interacts with almost everything and has infinite uses. I don't really think it needs more.
> > 
> > 
> > Counterpoint: Emags are a staple traitor item. There is nothing wrong with traitors having powerful items/abilities.
> 
> No, there's nothing wrong with that. I think it's an issue because if you make one item too good it just becomes a waste of TC to buy anything else.

Maybe if you're a powergaming tryhard for ebin valids. I'm a big fan of some of the lesser purchased items because you can do some fun gimmicks with it. If you just buy shit like emag revolver or ebow every traitor round, i don't think those items are the issue

2021-05-06 08:39 UTC, Kurfursten commented
Compile failure

2021-05-07 00:05 UTC, kane-f commented
> Compile failure

Fixed

2021-05-19 17:43 UTC, ShiftyRail approved these changes

2021-05-19 17:43 UTC, merged