Allows baguloose singulos on the escape shuttle again
d3athrow/vgstation13 pull request #29271
Opened 2021-04-18 15:09 UTC by Dacendeth

Dying instantly to an explosion on the escape shuttle in transit is not nearly as fun as running around from a singularity before getting sucked in.  This explosion code was only added in the first place to stop people from raiding centcom, but that place is trash to raid now and really admins should yell at people who do it instead.

:cl:
 * tweak: Baguloose on z2 will create singularity again.

2021-04-18 15:11 UTC, ShiftyRail commented
This allows !!!exploits!!! via controlled bagulooses/singularities on vaults with a part of the z-level in centcomm

2021-04-18 15:21 UTC, BomberBro commented
My major point of contention for this PR is that baguloosing on z2 can destroy the escape shuttle before it even arrives, which makes no sense both mechanicswise and from the "lore".

2021-04-18 15:21 UTC, Dacendeth commented
> 
> 
> This allows !!!exploits!!! via controlled bagulooses/singularities on vaults with a part of the z-level in centcomm
> I suggest that you keep the Z2 check, but make it overriden by a check on whether or not the user is on the escape shuttle

I am a simple man, I know how to delete and copy paste.

2021-04-18 15:50 UTC, Irradiation commented
Just merge it and also code something that auto-bans Razz if he makes it into Z-2 if the shuttle hasn't arrived yet

2021-04-18 17:01 UTC, Eneocho commented
How will I suicidemaxcap the shuttle now?

2021-04-18 17:08 UTC, RaccoonBro commented
Should just be able to use is_on_shuttle to override the Z2 check

2021-04-19 09:42 UTC, spacedgod1 commented
Explosions own escapees far better than piddly-ass 1x1 singulos. I prefer the instant gratification of a large explosion boosted by shrapnel code.
t. EORGer

2021-04-19 16:51 UTC, MadmanMartian requested changes
I put those changes in for a reason. A few griff singularities ate the spawn zone so players could not join the server. If you're doing this, make the spawn zone on all centcomm levels immune to singularities, maybe have an area check where they detonate, or otherwise prefer not to move in the direction of them.

2021-04-23 18:14 UTC, Dacendeth commented
Okay I figured out how to fix it but I still dont understand github perfectly soo uhh new pr time I guess.

2021-04-23 18:14 UTC, closed without merging