Supermatter chad during April Fools
d3athrow/vgstation13 pull request #29283
Opened 2021-04-18 22:54 UTC by boy2mantwicethefam

An image posted by a friend of mine compared the Supermatter Shard to a banana on a pillar. In my madness I have noticed it was more akin to the typical Chad meme that will be dead if you are reading this 10 years in the future, at least if it didn't get the coolface (trollface) treatment of having its grave desecrated and pissed on by millions of children who have run it through the "epic ironic humor" treatment where it became a dumb creepypasta material. In Deus Ex: Mankind Divided if you decide to do the mission where you go after the Orchid in the VersaLife vault instead of going after the terrorist and daughter of a local person, one of the canisters, although initially unlit, actually contains a clone of Adam Jensen, implying that the Adam you play as during the game is actually a clone, due to their lack of memories and the fact that their augments are completely different even if they look similar, sent to act as a sleeper agent until you get close enough to Janus to kill him. However, the game itself was pissed on due to interference from businessmen so probably nothing will actually happen with the Deus Ex franchise for at least a few more years after the creation of this pull request, and additionally the Breach gamemode sucks and I don't know how the heck anyone thought it should be an entire alternate gamemode when people wanted the main story and gameplay far more than they wanted this.  Actual manpower spent on making Breach could've been used to optimize the game so that it doesn't take literally a minute every zone transition to load the game.

:cl:
 * tweak: Updated localization files.

2021-04-18 23:57 UTC, Exxion commented on code/modules/supermatter/supermatter.dm
> +		desc = "A strangely translucent and iridescent crystal that looks like it used to be part of a larger structure. <span class='warning'>You are confident this is literally the best engine on the sta
>TGE

2021-04-19 00:23 UTC, boy2mantwicethefam commented on code/modules/supermatter/supermatter.dm
> +		desc = "A strangely translucent and iridescent crystal that looks like it used to be part of a larger structure. <span class='warning'>You are confident this is literally the best engine on the sta
Thermo-generic electricity

2021-04-19 00:27 UTC, boy2mantwicethefam commented on code/modules/supermatter/supermatter.dm
> +		desc = "A strangely translucent and iridescent crystal that looks like it used to be part of a larger structure. <span class='warning'>You are confident this is literally the best engine on the sta
For real, will fix.

2021-04-19 03:52 UTC, Eneocho commented
Your insanity has gone too far, B2M. You are dealing with matters no spessman should.

2021-04-19 16:44 UTC, MadmanMartian requested changes
there's a rogue pixel on the new supermatter sprites

2021-04-19 21:48 UTC, boy2mantwicethefam commented
If you mean the blue one it's intentional @MadmanMartian

2021-04-20 10:13 UTC, MadmanMartian commented
On the animated glow one.

2021-04-20 19:14 UTC, kane-f commented
change the user attack texts end thing to say "Your final thoughts are "Ouch!"" and its sold

2021-04-21 00:40 UTC, Kurfursten commented
White pixel top left corner in animation only in a few frames, as he said

2021-04-23 22:32 UTC, boy2mantwicethefam commented
I looked at the sprites and there's nothing wrong, the white pixel only appears in the bot's image when zoomed in, but the animation itself is clean, meaning the bot's image has image noise.

2021-04-24 04:05 UTC, merged