Diona liver
d3athrow/vgstation13 pull request #29403
Opened 2021-04-29 05:40 UTC by Zth--

Diona livers slowly metabolize chemicals into (a small amount of) ammonia up to a maximum of (currently) 30 units.
Ammonia is a known stinky fertilizer that can be used in different chemical reactions.
This has several implications:
- If you get it out of the body then it's free fertilizers! Nice!
- If you drink some ethanol you'll create diethylamine, an even better fertilizer! Cool!
- Food or drinks with liquid plasma are now super dangerous. That'll create lexorin and you don't want that inside you.
- Did I mention bleach? You weren't going to drink that either anyways, right?

And the major design flaw I found when doing this: water.
Water and ammonia creates space lube. Why wouldn't a plant based race be able to drink water? I found a possible answer: it's your fault for not sticking to sunlight and water only. I added a special check so it doesn't convert water into ammonia. It's safe to drink _only_ water. The moment you add another chemical inside your body then you'll metabolize it into ammonia and water will create space lube.

Don't forget you can puke inside containers (and buckets are containers!)

I'm open to suggestions and changes.

2021-04-29 06:07 UTC, robintime commented
this is actually a really interesting idea (i love the concept of alien biochemistry in general so this tickles my autism)

i think if possible you should snowflake it so that the dionammonia doesn't react with water to create space lube at all because 1. Wow Holy Gunk and 2. I would have to see diona clowns, and that would make me unhappy

2021-04-29 08:20 UTC, Eneocho commented
Honestly, adult diona should keep the weeds munching and fertilizer pouring abilities of nymphs. Makes no sense that they lose those powers, since they are only useful in botany.

2021-04-29 08:20 UTC, Eneocho commented
Also, add an exception to all food chemicals, lest you make lube whenever you eat anything. Or just remove the lube reaction inside of dionae.

2021-04-29 13:02 UTC, BomberBro commented
There are so many ways to get random chems inside of you that I think it'd be best if it just didn't form space lube (actually I think you mean space cleaner from the chemistry page at least) altogether OR space lube didn't damage diona when drank. Off the top of my head, a soul rambler's flute gives you chill wax if you're on screen and many, many virus symptoms give you chems.

2021-04-29 13:41 UTC, help-maint commented
What are the implications of a 0.5 metabolism liver?
Let's say I feed a diona 10 units kelotane, what happens compared to a human? Do they heal 50% slower on top of turning 50% of the kelotane into ammonia? Or does kelotane just need 50% less kelotane to do it's thing?

2021-04-29 14:43 UTC, boy2mantwicethefam commented
Changelog

2021-04-30 10:05 UTC, toomykins commented
*me pees on the floor
*me pees on the floor
*me pees on the floor
nice free fertilizer

2021-04-30 20:13 UTC, Eneocho commented
> 
> 
> *me pees on the floor
> *me pees on the floor
> *me pees on the floor
> nice free fertilizer

The return of Skylar.

2021-04-30 20:17 UTC, Eneocho commented
Add these diona livers to the organ printers.

2021-05-02 22:25 UTC, Zth-- commented
> What are the implications of a 0.5 metabolism liver?

After some testing I realized chems lived longer inside the carbon meaning you need less chems for the same effect. I reverted that to efficiency 1.

>Add these diona livers to the organ printers.

done

I added a transfer reagents spell for dionas. It lets you transfer your reagents into any tray.
I added a codersprite for diona livers.

I did not add a new ammonia alternative that does not create space cleaner because I feel it's too snowflakey. I have the changes on a commit so if it does become a demand I can just push it.

2021-05-03 00:20 UTC, Eneocho commented
Add #27376 to the PR since you cucked the no blood exploit.

2021-05-03 00:29 UTC, Eneocho commented
You could make diona ammonia a child of regular ammonia so it keeps all the features of ammonia but doesn't react like ammonia does. This would break any diethylamine production, however.

2021-05-03 00:29 UTC, Eneocho commented
Also, please give the eat weeds spell to diona adults, since it makes no sense an adult diona can't eat weeds but a nymph can.

2021-05-03 00:43 UTC, Zth-- commented
> Add "Fixes #27376" and "Fixes #26196" to the PR since you cucked the blood drinking exploit.

Cool, I didn't know they were reported.

> 
> 
> You could make diona ammonia a child of regular ammonia so it keeps all the features of ammonia but doesn't react like ammonia does. This would break any diethylamine production unless you added an ammonia define and only used this define with diethylamine.

I do it slightly different, define ammonias as ammonia+diona_ammonia and then update the recipes to use both ammonias except space cleaner. I don't like the outcome so I didn't include it in the PR


> 
> 
> Also, please give the eat weeds spell to diona adults, since it makes no sense an adult diona can't eat weeds but a nymph can.

I might in another PR, I think this one is fine as is

2021-05-03 00:53 UTC, Eneocho commented
You could change the nymph's nutrient pouring and weed eating into their own spellbuttons, since they are only verbs on a diona verb panel, not a proper spell.

2021-05-03 10:02 UTC, Kurfursten requested changes

2021-05-03 10:02 UTC, Kurfursten commented on code/modules/mob/living/carbon/racial_spells.dm
> +	for(var/obj/machinery/portable_atmospherics/hydroponics/target in targets)
Since you only want to target trays (and soil), you should override `is_valid_target` and have it target only trays. You could even add a fail message for not targeting a valid target.

2021-05-03 10:19 UTC, Eneocho commented
I would change the "Transfer reagents" spellname to "Fertilize" and it's description to "Taps into your internal nutrient storage to fertilize a plant". I would also change the "You carefully grab \the [target] and transfer 5 units from your system to it." to "you secrete some nutritional sap from your fingertips and let it fall into \the [target]" or similar.
This would feel less immulshon breaking.

2021-05-05 20:30 UTC, Zth-- commented
Done

2021-05-06 08:21 UTC, Kurfursten approved these changes

2021-05-06 08:21 UTC, merged