Barber Scissors: The Assistant of Seville
d3athrow/vgstation13 pull request #29582
Opened 2021-05-23 21:24 UTC by GreatBigFailure

Adds barber scissors and puts them in the barbervend. Sprite by Bomber Harris. 
Barber scissors work like pocket mirrors but you can change other people's hairstyles with them, not just your own. There's a 3 second delay on this and creates a warning message so no surprise haircuts. You also can't cut your own hair. Remember, you should always go to the barber with the second best haircut. 
Finally, this replaces the lipstick in barbervend's contraband with the pocket mirror. Mostly I just didn't like the lipstick being there because we have a makeup vendor already.

![bigscissor2](https://user-images.githubusercontent.com/64218965/119277058-789a0300-bbeb-11eb-9456-af04140cf700.png)

![barberscreenshot](https://user-images.githubusercontent.com/64218965/119277029-50aa9f80-bbeb-11eb-935d-5d96068d163c.png)

-->
:cl:
 * rscadd: Barbervends now sell scissors which allow actual barbering to take place.

2021-05-24 00:15 UTC, PavelCIA commented
on my way to give every prisoner a floorlength braid as warden so they cant run away

2021-05-24 02:08 UTC, calzilla1 commented
Some of the more "gaudy" hair styles should be locked behind getting a haircut. Hey, looking like a rejected anime protagonist ain't cheap.

2021-05-24 09:31 UTC, Eneocho commented
> 
> 
> Some of the more "gaudy" hair styles should be locked behind getting a haircut. Hey, looking like a rejected anime protagonist ain't cheap.

The haircut gang nerf... Is this the end of the meterlong pompadour hairdo?

2021-05-24 09:31 UTC, Eneocho commented
Sweeney Todd gimmicks soon?

2021-05-24 18:11 UTC, BomberBro commented
The scissors sprite was a WIP from awhile ago, if anyone has a better sprite feel free to throw it into the gauntlet.

2021-05-30 20:36 UTC, Kurfursten commented on code/game/objects/items/weapons/cosmetics.dm
> +		user.visible_message("<span class='warning'>[user] begins changing [target]'s style!</span>")	//Chitin, slime, etc. Can't use the word "hair"
`danger` is better for this  purpose, as it is bold

2021-05-30 20:36 UTC, Kurfursten requested changes
otherwise looks good to go

2021-05-31 20:43 UTC, Kurfursten approved these changes

2021-05-31 20:56 UTC, merged