Cabinets & Weights
d3athrow/vgstation13 pull request #30031
Opened 2021-07-19 04:13 UTC by Apogee-dev

Fills a handful of gaps in the game's selection of craftable furniture by adding the ability to build and dismantle wood cabinets, file cabinets, and weight machines, as well as anchor or deanchor weight machines. Rejoice in your ability to finally build your own gym or give your build slightly less ugly closets than the usual bare metal lockers.

:cl:
 * rscadd: File cabinets, weight machines, and wooden cabinets can now be built out of 2 metal, 2 plasteel, and 2 wood respectively, and can be disassembled with a welder (file cabinet, weight machine) or a crowbar (cabinet).
 * rscadd: Secure cabinets can now be made by adding airlock electronics to a wooden cabinet.
 * tweak: While open, secure cabinets (detective, bar, wondrous wardrobe) can now be dismantled into wood and airlock electronics with a crowbar instead of welded into metal like a normal secure locker.
 * tweak: Weight machines can now be anchored and deanchored with a wrench.

2021-07-19 05:55 UTC, Kurfursten requested changes
Now make the hologram variants that dismantle into nothing

2021-07-19 07:37 UTC, Apogee-dev commented
> Now make the hologram variants that dismantle into nothing

Good save, completely forgot about the holodeck.

2021-07-19 09:49 UTC, Eneocho commented
> 
> 
> > Now make the hologram variants that dismantle into nothing
> 
> Good save, completely forgot about the holodeck.

They are fixing exploits before they even happen? The c*ders are getting wise.

2021-07-19 14:49 UTC, Kurfursten commented
You could save a lot of copy/paste here if you just use inheritance so that it just checks can_disassemble in the parent

2021-07-20 00:28 UTC, Apogee-dev commented
> You could save a lot of copy/paste here if you just use inheritance so that it just checks can_disassemble in the parent

You're right, it's a pretty big savings. Done.

2021-07-23 21:52 UTC, Kurfursten approved these changes

2021-07-23 21:52 UTC, merged