Adds MoMMI flavoured adminbus autoborger
d3athrow/vgstation13 pull request #30162
Opened 2021-08-09 01:40 UTC by kane-f

[content]
Idea by @drawsstuff, possible sprite too soon.
:cl:
 * rscadd: Malfunctioning AIs can now spawn a MoMMI flavoured autoborger, if the gods are willing.

2021-08-09 03:22 UTC, Kurfursten requested changes
Get rid of ALL this copypaste and just make a new proc that handles the transformation itself, then override that. I believe you can get this down to 7 total lines of code.

2021-08-09 17:46 UTC, DeityLink commented
Are the mommi free-willed or auto-emagged? in the latter case, they should be slaved to the AI and you should have them added to the AI's faction like I did in https://github.com/vgstation-coders/vgstation13/pull/30161/files

2021-08-09 17:50 UTC, drawsstuff commented
> Are the mommi free-willed or auto-emagged? in the latter case, they should be slaved to the AI and you should have them added to the AI's faction like I did in https://github.com/vgstation-coders/vgstation13/pull/30161/files

They should probably be the standard keeper lawset with the usual [ERORR ACCOMPLISH OBJECTIVES AT ALL COSTS].

2021-08-09 18:15 UTC, DeityLink commented
so....emagged?

2021-08-09 18:19 UTC, Blithering commented
More important question, does this call for a third eye glow colour?

2021-08-09 18:54 UTC, kane-f commented
> Get rid of ALL this copypaste and just make a new proc that handles the transformation itself, then override that. I believe you can get this down to 7 total lines of code.

Done

2021-08-09 19:23 UTC, drawsstuff commented
> so....emagged?

No. Emagged mommis follow syndiemov or whatever you wanna call it, and have access to a stun arm.

2021-08-09 19:43 UTC, Eneocho commented
> 
> 
> More important question, does this call for a third eye glow colour?

On the one hand, it'd go along the concept of MoMMIs being blatantly obvious when not KEEPERs. On the other hand, that would disrupt the early stealth stage on an autoborger Malf round, since you could see the MoMMI waddling around with the purple eyes.

2021-08-09 19:47 UTC, Eneocho commented on code/game/machinery/autoborger.dm
> +	name = "Autimatic Crab Factory 5000"
```suggestion
	name = "Autismatic Crab Factory 5000"
```

2021-08-09 20:57 UTC, Kurfursten approved these changes

2021-08-11 18:39 UTC, Anton-Kr commented
Now make it not adminbus.

2021-08-11 19:48 UTC, drawsstuff commented
> Now make it not adminbus.

Sure, for 200 points

2021-08-11 20:18 UTC, merged