Cargo crate forwarding
d3athrow/vgstation13 pull request #31967
Opened 2022-02-01 14:45 UTC by kane-f

[content][system]
Working implementation of #29108.
List of things done:
- [ ] Receiving forwarded crates.
- [ ] Sending forwarded crates.
- [ ] Controls for toggling forwarding system on supply consoles.
- [ ] Viewing list of crates to forward on supply consoles.
- [ ] Tampering checks for pay.
- [ ] Timing system.
- [ ] Weighing crates.
- [ ] Stamping checks.
- [ ] Generated manifests.

:cl:
 * rscadd: Cargo can now enable an option on supply computers to enable crate forwarding, another method of receiving station funds for stamping manifests on forwarded crates from other stations. Failure to stamp these crates, keep proper stock intact or forward in enough time will result in funds docks instead.

2022-02-01 17:32 UTC, GreatBigFailure commented
No time to skim the code. Does this include the mentioned "special" crates or just items on the cargo list?

2022-02-01 20:40 UTC, kane-f commented
> No time to skim the code. Does this include the mentioned "special" crates or just items on the cargo list?

Will probably do those as I go.

2022-02-01 21:35 UTC, GreatBigFailure commented
You could always steal some of the old vendotron merch list for it. They're similar concepts.

2022-02-02 01:46 UTC, WindowsErrors commented
I read the original feature request

does some of the forwarded postage come inside a wooden crate that's also the same wooden crate that the random event chest mimic comes in on? I really enjoy remaining a two-tile radius and keeping my off hand above the movement keys out of some primal cargo worker instinct, akin to my GPS telling me to drive through the ghetto part of town

2022-02-02 07:59 UTC, Eneocho commented
Requesting for the blatant powergame crates' requester to have dumb names, like the powergamey or braindamaged names we sometimes get. 

`>25 eguns by "Domestique Abuserson`? Makes total sense.

2022-02-10 00:34 UTC, Kurfursten commented on code/controllers/subsystem/supply_shuttle.dm
> +		new /obj/machinery/crate_weigher(pickedloc)
instead of spawning a weigher with every shipment, I think it would make more sense to just map one in to each cargo bay

2022-02-10 01:11 UTC, Eneocho commented
Once this gets merged we'll only need the crate pushing each other thing for the ultra cargo experience.

2022-02-10 15:01 UTC, ghost commented on code/controllers/subsystem/supply_shuttle.dm
> +		new /obj/machinery/crate_weigher(pickedloc)
Done.

2022-02-10 22:30 UTC, Kurfursten commented
Unfortunately the changes to line didn't properly smoosh so you'll have to redo that one.

Also it's pretty questionable to include the old vendotron, mostly because you can potentially get multiple. But you did put on a 5 minute cooldown on forwarding so as long as you add enough random crates to appear it should be okay.

2022-02-11 00:03 UTC, Eneocho commented
Can you forward a crate by yourself? As in, I fill a crate with 40 asses, send it on it's way, then a few rounds later the asscrate appears on the forwarding system.

2022-02-11 03:33 UTC, Kurfursten commented
Out of scope but possible with persistence and cool idea

2022-02-11 04:51 UTC, Eneocho commented
> Out of scope but possible with persistence and cool idea

Not that out of scope. Kane-f's list of things he's going to do includes "Persistence for forwards between rounds ending up as forwards in a next station. (with a chance)".
I'm asking for that persistence to include also some custom player crates.

2022-02-11 12:37 UTC, kane-f commented
> Can you forward a crate by yourself? As in, I fill a crate with 40 asses, send it on it's way, then a few rounds later the asscrate appears on the forwarding system.

Dunno, sounds too exploitable, and would break distribution of finding otherwise rare or exclusive items, but on the other hand, if they were found on lowpop they'd benefit highpop rounds later.

2022-02-11 17:58 UTC, Eneocho commented
> > Can you forward a crate by yourself? As in, I fill a crate with 40 asses, send it on it's way, then a few rounds later the asscrate appears on the forwarding system.
> 
> Dunno, sounds too exploitable, and would break distribution of finding otherwise rare or exclusive items, but on the other hand, if they were found on lowpop they'd benefit highpop rounds later.

You could add a "MAX CUSTOM VALUE" kinda deal so you can't send a crate with 30 Laser AK-47s. Not sure how to diegetically explain that one however.

2022-02-20 02:10 UTC, WindowsErrors commented
surprised how nobodys made a comparison to the security prisoner transfer yet

2022-03-20 20:32 UTC, Kurfursten requested changes
I've looked this over and it looks solid, except that Line needs to be reupdated because the diff is huge

2022-03-20 21:25 UTC, Exxion commented
Line was apparently using CRLF line endings before. The huge diff is because this changes it to the correct LF.

2022-03-20 21:56 UTC, Kurfursten approved these changes

2022-03-20 21:57 UTC, Kurfursten commented
Force the line conflicts to resolve and I will merge

2022-03-21 15:02 UTC, kane-f commented
> Force the line conflicts to resolve and I will merge

Resolved now @Kurfursten

2022-03-21 20:50 UTC, merged

2022-03-21 20:58 UTC, Eneocho commented
DANGEROUSLY BASED

2022-03-22 01:04 UTC, Servalfang commented
do we get to alternatively loot them?

2022-03-22 15:22 UTC, Eneocho commented
Yes. You can forward the crates for extra cash for cargo/busywork or steal the shit if you deem it worth it.

2022-03-22 18:35 UTC, WindowsErrors commented
would it count as theft under space law because you're taking someone else's cargo crate or would it not because theft only applies to locked cargo crates

2022-03-22 18:50 UTC, WindowsErrors commented
speaking of which where's the screen that actually shows you the cargo crates to forward since there doesn't actually seem to be any way to actually see it

2022-03-22 19:20 UTC, Eneocho commented
Toggle on the forward crate system on the top center of the shuttle console then get the shuttle to return to the station. Every now and then some extra crates that you didn't order will appear next to a manifest.
Wrench down the crate weigher, put that manifest inside and drag the crate on top. The crate weight will be registered on the manifest. Stamp it then send back to centcomm with the manifest outside the crate (not so sure about this last bit).
If you have crates to forward there will be a button right next to the centcom requests button on the console which will tell you the details on what does the crate contain and if you have to stamp/weigh.

On that note, it seems the check is kinda broken, because I've sent back crates with the stamp and weight as the request asked for but the forward failed.

2022-03-22 20:11 UTC, WindowsErrors commented
if the crate forwarding screen not being on the console is a bug then it should probably get ironed out right quick considering how these things are supposed to have a time limit and also because my first instinct upon seeing a crate that shouldn't be there is to send it back without touching it in case it's the chest mimic that kills you in two hits

2022-03-22 20:56 UTC, Eneocho commented
The screen only appears AFTER you get crates to send back it seems.

2022-03-22 22:41 UTC, WindowsErrors commented
ok i get it now

2022-03-22 22:45 UTC, WindowsErrors commented
also is it just me or do the forwarded crates not despawn when the shuttle is sent back to centcom

2022-03-22 22:54 UTC, Eneocho commented
It does seem they do not despawn, but it might be because the forward was sent wrong.

2022-03-22 23:08 UTC, WindowsErrors commented
yea but it says i'm doing it right and the money gets sent to the budget but everything is still just sitting there

2022-03-22 23:44 UTC, WindowsErrors commented
just please fix the stuff not despawning when the shuttle's sent back, the average cargo forwarder shuttle looks like this by 12:30

![Screenshot (1673)](https://user-images.githubusercontent.com/58999300/159594456-5c59ba31-3d92-4c22-8227-4e2a7c5561c0.png)

the cargo workers have already broken open the good crates and the budget has thousands of dollars on it due to the constant erroneous payments from centcom

2022-03-23 01:59 UTC, WindowsErrors commented
[wiggi updaded](http://ss13.moe/wiki/index.php/Supply_Crates#Crate_Forwarding)

As an aside I feel like the option to toggle crate forwarding would probably be better put under the Permissions tab or something instead of being the large blue button in the middle of the screen that's right next to the Call Shuttle button, since the workers are gonna see "enable crate forwarding", wonder what that does, mindlessly flick it on, and then most cargo player's first instincts upon seeing a locked crate is to forcibly see what's inside like they're expecting to find a chest of pirate's treasure