Mulebots pickup sanity
d3athrow/vgstation13 pull request #32419
Opened 2022-04-18 22:09 UTC by ShiftyRail

Closes #32400 except for emagged mulebots, who can still pick up grilles and doors they lack access to.

2022-04-18 22:44 UTC, Kurfursten commented
doors they have access to*

also bugfix CL

2022-04-18 23:55 UTC, GreatBigFailure commented
To save me skimming the code: how much does this restrict them compared to what they are now? Is it a fully reset to just crates/lockers or is it more flexible? While current mules are ridiculously broken and need fixing there's a lot of fun stuff they can do that came from the oversight.

2022-04-19 00:48 UTC, Eneocho commented
I liked the MULE morgue tray and the MULE locker for ghetto bus travel. Please keep that in.

2022-04-19 01:04 UTC, GreatBigFailure commented
> I liked the MULE morgue tray and the MULE locker for ghetto bus travel. Please keep that in.

Mule morgue trays are my favorite addition in ages but to keep them we'd need to fix a lot about morgue trays. Those things have a lot of weird interactions.

2022-04-19 01:46 UTC, Kurfursten commented on code/game/machinery/bots/mulebot.dm
> +	if (!istype(C,/obj/item) && !istype(C,/obj/machinery) && !istype(C,/obj/structure) && !ismob(C))
`isitem()`

2022-04-19 01:49 UTC, Kurfursten commented
> To save me skimming the code: how much does this restrict them compared to what they are now? Is it a fully reset to just crates/lockers or is it more flexible? While current mules are ridiculously broken and need fixing there's a lot of fun stuff they can do that came from the oversight.

The code is very short

- if it is not an item, mob, or machinery, don't pick it up
- if emagged, you can pick up anything that is one of those 3, including the doors to the armory, door to the AI core, the AI, turrets, one piece of the gateway (permanently breaking it), a supermatter crystal, a singularity, etc.
- if not emagged, it can still pick up any of those, but not a window, grille, or a door you don't have access to

2022-04-19 02:43 UTC, GreatBigFailure commented
Thanks, more flexibility than I was expecting to stick around.
I've been testing a lot of things and haven't found anything obvious that might create issue. Even cryo tubes seem fine.

2022-04-19 02:55 UTC, WindowsErrors commented
by not emagged do you just mean the thing where you cut the wire and it says the platform is riding low

2022-04-19 03:24 UTC, Eneocho commented
Probably.

2022-04-19 03:40 UTC, Kurfursten commented
Yes, it must be riding low to grab stuff other than crates at all.

Tested / can grab: intercom, lightswitch, disposal (glitches out and lets you teleport to wherever it was attached), power cables (glitchy),  air pipes (EXTREMELY GLITCHY), gateway pieces (VERY GLITCHY), telecoms, nuke, and safe

2022-04-19 07:07 UTC, ShiftyRail commented
I will take this into account

2022-04-19 11:46 UTC, jknpj commented
> Yes, it must be riding low to grab stuff other than crates at all.
> 
> Tested / can grab: intercom, lightswitch, disposal (glitches out and lets you teleport to wherever it was attached), power cables (glitchy), air pipes (EXTREMELY GLITCHY), gateway pieces (permanently breaks the gateway?), telecoms, nuke, and safe

Maybe fun isn't worth the trouble

2022-04-19 11:58 UTC, kane-f commented on code/game/machinery/bots/mulebot.dm
> +		if (istype(C, /obj/structure/grille) || istype(C, /obj/structure/window))
Coincidentally I was working on the exact same PR
I'd rather this be locked behind things being anchored or non-dense/opaque, any similar checks to that.

2022-04-24 18:35 UTC, jwhitak commented
The goofiness of this is great, so I'm glad we can keep it for the emagged mules.

2022-04-26 07:12 UTC, luigil101 commented
Mule gunk shenanigans are peak Space Station 13

2022-04-30 21:39 UTC, Kurfursten requested changes
I don't really care about the macro change at all, just please add more protections against the stuff that actually breaks that I listed above

2022-05-15 00:25 UTC, Kurfursten commented
Can't make it, can't make it, change stuck
Please, I beg you

2022-05-19 04:05 UTC, WindowsErrors commented
I will continue to get a morgue tray and go The Simpsons: Hit & Run (2003) on the three people I see perfectly lined up in the medbay hallway while making the sound of bowling pins getting knocked down from my mouth

2022-05-22 13:49 UTC, ShiftyRail commented
oh hahaha been a long time innit

2022-05-22 16:43 UTC, Kurfursten approved these changes

2022-05-22 16:43 UTC, merged