Allows jetpacks to be used from the suit storage slot
d3athrow/vgstation13 pull request #32437
Opened 2022-04-24 09:26 UTC by ValkyrieSkies

Suits that are advanced enough to hold a jetpack in their suit storage can now actually use said jetpacks from suit storage - engineers and nukies rejoice!

![jetp](https://user-images.githubusercontent.com/19687076/164969668-ad04df38-226b-4785-ac7b-2fce3160b7ef.PNG)
:cl:
 * rscadd: Jetpacks can now be used from the suit storage slot

2022-04-24 21:11 UTC, gurfan commented
I don't like this. Forcing you to hold a backpack in one hand is an important drawback when flying around in space. Also this just looks wierd.

2022-04-24 22:48 UTC, kane-f commented
i kind of wanted to do this PR but wasn't sure if it was intended or popular

2022-04-26 08:22 UTC, Anton-Kr commented
Tbh I think this is the point. There should be a downside here

2022-04-27 05:24 UTC, tuypo1 commented
I think nukies/deathsquads should be able to do this but not just engineers, maybe the CE and an even more maybe the captain

2022-04-27 05:25 UTC, Exxion commented
-: Powercreep
+: Gets rid of a classic noob trap

2022-04-27 14:10 UTC, ValkyrieSkies commented
I was mostly throwing it out there to see what people thought at large, I'm not dedicated to this change.

2022-04-29 02:30 UTC, Blithering commented
Maybe update it so only specific suits can hold jetpacks in the suit slot if it's considered too strong for everyone. CE and captain suits yes, regular hardsuits no.

2022-04-30 21:45 UTC, Kurfursten requested changes, later dismissed
Implement it as Blithering suggested, it acts as another incentive to play head of staff. Then, update wiki for CE/cap/deathsquad/nukeop/ERT pages.

2022-05-01 01:23 UTC, DamianX commented
Having to hold your bag is annoying, I would prefer it if this worked on every suit.

2022-05-04 02:36 UTC, closed without merging