Fixes Swiss Tool tech values
d3athrow/vgstation13 pull request #32438
Opened 2022-04-24 12:24 UTC by ValkyrieSkies

Forgive me for what I must do.

Sets the tech value of Swiss Tools to what it takes to make them (Materials 5, Bluespace 3) rather than the incredibly high values of the base switchtool.

Closes #32422 

[sanity] [balance] [bugfix]
:cl:
 * rscadd: Sets Swiss Tool tech values to a more reasonable value

2022-04-24 15:28 UTC, Kurfursten commented
Needs to be done at the surgeon switchtool level since it is also way higher than its build tech

2022-04-24 17:19 UTC, Eneocho commented
The curse of the eternal coder. You either use your fun tech and have fun but risk losing it, or never use it to keep it hidden from the coder cabal.

2022-04-24 20:59 UTC, cloutcode commented
science doesn't deserve good things

2022-04-24 21:33 UTC, Kurfursten commented
In seriousness, this is an oversight of the worst kind.

> Put high tech values on it because it's supposed to be a space vault item
> Someone creeps it to be a station item but doesn't remove the rewarding tech values
> Now people complain because an item you can get cheaply at roundstart isn't a replacement for deconstructing phazon

If you really want to just remove R&D, it would be more honest to just make "Complete R&D for me" a button on the console so at least you're not filtering newbies for not knowing metaclub tricks.

2022-04-26 15:43 UTC, gurfan commented
it's fun because.... it just is OK?

2022-04-29 10:34 UTC, Blithering commented
I admit tech values never occurred to me when I added it to the vendor.

2022-04-29 10:38 UTC, Eneocho commented
> it's fun because.... it just is OK?

I do find fun to bypass half the fucking checklist when forced to RnD because most the autismo projects depend on RnD in one way or another.

2022-04-30 21:45 UTC, Kurfursten requested changes
Fix it at the surgeon switchtool level as requested

2022-05-01 17:41 UTC, ValkyrieSkies commented
> Fix it at the surgeon switchtool level as requested

The surgeon's switchtool has an assigned tech value, why does it need to be changed?

2022-05-01 17:48 UTC, Kurfursten commented
It's in the original issue, switch tools have a materials 9 tech reward but their design is materials 5; this means you can skip phazon at the cost of common iron. It's blue space is also too high but much less egregious.

2022-05-02 01:40 UTC, ValkyrieSkies commented
`/obj/item/weapon/switchtool/surgery
[...]
	origin_tech = Tc_MATERIALS + "=4;" + Tc_BLUESPACE + "=3;" + Tc_BIOTECH + "=3"`

Seems fine to me?

2022-05-02 01:47 UTC, Kurfursten commented
Oh, I'm sorry Valk, you were right. It's not at the surgeon switchtool level, it's at the base switchtool level.

switchtool.dm L19
![image](https://user-images.githubusercontent.com/9782036/166175059-8a7b6676-151c-4fcc-8cec-7a869e659f1a.png)

Just make it consistent with the surgeon's switchtool and I'll get this merged tonight

2022-05-02 01:59 UTC, Kurfursten approved these changes

2022-05-02 02:02 UTC, merged