Removes Cringe Ion Storm Laws
d3athrow/vgstation13 pull request #32454
Opened 2022-04-25 23:07 UTC by DorainGrey

Removes two OCK terms from the potential Ion Laws.
There's also an ion law that states the AI must "be read Woody's Got Wood to". Not sure about whether to keep that one, so I've left it out. It does essentially valid the AI but it's also kind of amusing.

2022-04-25 23:22 UTC, Jack7D1 requested changes
Be careful!

2022-04-25 23:22 UTC, Jack7D1 commented on vgstation13.dme
> +#include "maps\roidstation.dm"
```suggestion
#include "maps\tgstation.dm"
```

2022-04-25 23:22 UTC, Jack7D1 commented on vgstation13.dme
> +#include "maps\RoidStation.dmm"
```suggestion
```

2022-04-25 23:24 UTC, DorainGrey commented
> Be careful!

Thanks, I tend to use git add, for the specific file I was doing but this snuck in as I did this in 20 seconds.

2022-04-25 23:38 UTC, gurfan commented
angry valids made this pr

2022-04-25 23:40 UTC, DorainGrey commented
> angry valids made this pr

I really don't care I died, AI's can still easily get ion laws to kill a specific person.
This just removes the confusion.

2022-04-25 23:40 UTC, jwhitak commented
Giving the AI confusing terms in their ion laws is fun! I can see where the logic of this change is coming from, but it removes the soul...

2022-04-25 23:41 UTC, DorainGrey commented
> Giving the AI confusing terms in their ion laws is fun! I can see where the logic of this change is coming from, but it removes the soul...

I don't think OOC terms in AI laws are soul but that's just me. It's just banbait for AI's
Plenty of confusing possibilities left.

2022-04-25 23:59 UTC, Eneocho commented
Sovlless

2022-04-26 02:41 UTC, Exxion commented
I have actually gotten banned on this very server for using this word

2022-04-26 11:50 UTC, DorainGrey commented
Right I give up, inb4 this starts another argument over silicon laws in 6 months or so.

2022-04-26 11:55 UTC, DorainGrey commented
I give up, it'd be nice if the admemes at least gave us a clear ruling on what valid means in an IC context before closing it though.

2022-04-26 13:19 UTC, DamianX commented
"valid" being a _valid_ adjective to describe a person (the first thing that was r\*moved in this PR) is okay: the word itself can be used to mean a lot of different things. "Time to get those valids" has an established OOC meaning, and it would be best to keep it out of in-character baked-in laws.
Also, r\*move silicons.

2022-04-26 18:35 UTC, WindowsErrors commented
cringe?

2022-04-26 19:41 UTC, DorainGrey commented
Closing due to lack of interest. Just watch this be a problem again in 6 months.

2022-04-26 19:41 UTC, closed without merging