Fix hydroponics seeds never being able to lose some traits through mutations
d3athrow/vgstation13 pull request #33267
Opened 2022-09-12 21:12 UTC by gurfan

## What this does
fixes seeds never being able to lose some mutations like vine spreading

## Why it's good
k

## Changelog

:cl:
 * bugfix: Fixed hydroponics seeds never being able to lose some traits through random mutations.

2022-09-13 01:57 UTC, Kurfursten commented on code/modules/hydroponics/hydroponics_mutations.dm
> +					seed.voracious = (seed.juicy + 1) % 3
wait a minute that var name...

2022-09-13 01:57 UTC, Kurfursten commented on code/modules/hydroponics/hydroponics_mutations.dm
> +					seed.spread = (seed.juicy + 1) % 3
return of the juicy var...

2022-09-14 16:06 UTC, Kurfursten requested changes
Fix it

2022-09-14 16:57 UTC, gurfan commented
fixed

2022-09-14 17:48 UTC, Kurfursten approved these changes

2022-09-14 17:48 UTC, merged