Changed maracas
d3athrow/vgstation13 pull request #33280
Opened 2022-09-14 14:36 UTC by boy2mantwicethefam

(Has sound)

[maraca.webm](https://user-images.githubusercontent.com/41342767/190183497-69dc7bf0-32d4-4efb-922d-d47604df44ce.webm)

Maracas can no longer be emagged to unlock their explosive functionality and now have a delay of about 2 seconds before it detonates, during which it plays a familiar tune. However, their explosion power has been DOUBLED, making them vastly more powerful.
A friendly reminder that you can get explosive maracas from beating Cuban Pete in the Outbomb Cuban Pete arcade game.

:cl:
 * tweak: Maracas can no longer be emagged.
 * soundadd: Maracas now play a familiar tune before exploding.
 * tweak: The explosive power of explosive maracas has been drastically increased.

2022-09-14 14:38 UTC, west3436 commented
based emag anti-creep proponent

2022-09-14 14:38 UTC, Eneocho commented
cringe emag anti-creep soyman

2022-09-14 14:39 UTC, ancientpower commented
honestly they shouldn't explode emag or not

2022-09-14 15:05 UTC, PrimeDSS13 commented
> honestly they shouldn't explode emag or not

They're the reward from the Cuban Pete emagged arcade game, which is incredibly hard to win and will more likely kill you.
I think it's fine if it's the only way to obtain the explosive version, unlike before.

2022-09-14 15:47 UTC, Kurfursten commented
I actually like this. Emagging an arcade which then dispenses a dangerous reward makes more sense than rubbing your card on a piece of wood and suddenly it's a bomb. Emags should be less "outright magic" and more "hacker known as 4chan". Remember the height of emag fervor whens someone wanted to add emagging to paper?

And for the record, I'm **not** against features for the emag even though it already has uses. For example, if someone wanted to make it so the microwave can be emagged to always ruin food and hurl the burned mess into mouths a-la pneumo cannon, or emag hydro trays so they display wrong warning lights, or emag the chem dispenser to change the order of all the buttons so it fucks with muscle-memory chemists - those would all be cool and not magical.

2022-09-14 15:49 UTC, Eneocho commented
Space maracas have an internal battery that powers a speaker/motion sensor, which make the shaking sound. Emagging it damages the battery so it explodes, not magic.

2022-09-14 15:59 UTC, ManopolisJones commented
You know it's funny, I've never actually seen anyone do a concerted e-magged maraca attack against the station. I can only imagine how effective it would be.

2022-09-16 05:09 UTC, BomberBro commented
Somebody tell Robot about this PR

2022-09-19 21:35 UTC, SonixApache commented
> Somebody tell Robot about this PR

it's funny how population opinions change over time
#20123

2022-09-19 22:56 UTC, Kurfursten commented
This isn't really the same. Removal and reimagining are separate beasts to emojis.

2022-09-21 22:00 UTC, Kurfursten commented on code/game/objects/items/devices/maracas.dm
> +	if(!triggered)
just merge these 2 if-statements into a single line

2022-09-21 22:00 UTC, Kurfursten commented on code/game/objects/items/devices/maracas.dm
> +			triggered = 1
prefer TRUE

2022-09-21 22:00 UTC, Kurfursten commented on code/game/objects/items/devices/maracas.dm
> +			spawn(21) //The point in the audio file in which the tune changes
2.1 SECONDS

2022-09-21 22:01 UTC, Kurfursten requested changes
those things I said

2022-09-27 05:40 UTC, calzilla1 commented
Could the ones at Centcomm still be the old ones?

2022-09-30 12:31 UTC, Exxion commented
>Space maracas have an internal battery that powers a speaker/motion sensor, which makes the shaking sound. Emagging it damages the battery so it explodes, not magic.

This was an explanation I came up with as a joke which someone else then put in the game

2022-09-30 13:16 UTC, boy2mantwicethefam commented
@calzilla1 They could but I'm burned out on coding.

2022-09-30 13:22 UTC, Exxion commented
Speaking of that joke explanation, it's not really necessary anymore if they're not emaggable

2022-09-30 13:26 UTC, Exxion commented on code/game/objects/items/devices/maracas.dm
> +			spawn(21) //The point in the audio file in which the tune changes
I don't think this really matters but it's already done

2022-09-30 15:07 UTC, Kurfursten approved these changes

2022-09-30 15:07 UTC, merged