fix plasma seal suit modification
d3athrow/vgstation13 pull request #33648
Opened 2022-11-05 19:55 UTC by CrazyAmphibian

## What this does
makes it so that installing the plasma sealant module no longer will override plasma sealing that a suit already has.

## Why it's good
it fixes a silly quirk of how the module set clothing flags.

## Changelog
:cl:
 * added variable and checks into the plasma seal module

2022-11-05 20:56 UTC, Eneocho commented
Changelog should be:
:cl:
* bugfix: Fixes plasma seal suit mod removing inherent plasmaproofing from suits.
Or something similar.

2022-11-06 07:35 UTC, Eneocho commented
Add the "bugfix: " part too, please.

2022-11-12 18:01 UTC, Kurfursten commented on code/modules/clothing/spacesuits/rig_modules/rig_modules.dm
> +	var/already_has = FALSE //what kind of shitlang uses all cap booleans?
Stupid comment to add given that this is a repo convention to use a define, it's not part of the language

2022-11-12 18:02 UTC, Kurfursten requested changes
This implementation doesn't make sense. Just make it so you can't install the sealant on plasmaguarded outfits.

2022-11-12 19:10 UTC, CrazyAmphibian commented
> This implementation doesn't make sense. Just make it so you can't install the sealant on plasmaguarded outfits.

don't know how to do that, and something tells me the effort to code it (rather, learn how to code it to do that) just isn't worth it for what is admittedly a largely insignificant problem.

2022-11-12 19:35 UTC, Kurfursten commented
Here's how to code it:

In suit_modifier.dm at line 236, replace the existing check with this:
```
if(RM.can_install(R))
   continue
```

Then add this in rig_modules.dm - this will handle the default behavior we just replaced, don't install if we already have this type
```
/obj/item/rig_module/proc/can_install(var/obj/item/clothing/suit/space/rig/target)
   return !(locate(type) in target.modules)
```

This has the added benefit of making it more modular; you could theoretically have a future module that can be installed multiple times. Now for our intended change...

```
/obj/item/rig_module/plasma_proof/can_install(var/obj/item/clothing/suit/space/rig/target)
   if(!..())
     return FALSE
   if(target.clothing_flags & PLASMAGUARD)
     return FALSE
   return TRUE
```

2022-12-03 23:05 UTC, Kurfursten commented
Do the code frog man

2022-12-10 16:30 UTC, Kurfursten commented
WHERE'S THE CODE FROGMAN

2022-12-10 19:51 UTC, CrazyAmphibian commented
sorry, not touched SS in a hot minute.
that and i've been on a linux laptop for an extended period, where SS is not that optimal to play, and i doubt develop for.

2023-02-10 20:53 UTC, Kurfursten commented
FIX IT

2023-02-28 18:19 UTC, pedr69 commented
any day now....

2023-04-30 01:32 UTC, CrazyAmphibian commented
i once again remembered this was still open. now it is not.
FROG MAN WILL NOT DO CODE
thank you for the inside joke with friends, though.

2023-04-30 01:32 UTC, closed without merging