Adding the ability to paint on floors with brushes, and also the ability to use multiple crayons from a box while floorpainting
d3athrow/vgstation13 pull request #35367
Opened 2023-11-11 22:08 UTC by Volttekka

Credit to Anonymous user No.453861032 from the thread for the coding
The purpose of this pull request is the ability to paint on floors with a brush, as well as the ability to use all the crayons in a box of crayons to draw on the floor in the advanced graffiti.

Why it's good: this is a logical extension of the painting and floor graffiti systems, so there shouldn't be any issues.

This is my first time doing any sort of pull request, so lemme know if I goofed a bit on this

2023-11-11 22:13 UTC, kilozombie commented
Did you test it ingame to see if it works?

2023-11-11 22:14 UTC, DeityLink commented
what kilo said. other than that this is a good idea. (and thankfully for me compatible with the big paint PR I'm currently cooking)

2023-11-11 22:16 UTC, Eneocho commented
Closes #35300.

2023-11-11 22:37 UTC, Eneocho commented
Requesting an RGB/HEX input or something if you're painting with the rainbow crayon (as it can paint in all colours), or being able to add colours to an easel via crayon.

2023-11-11 22:37 UTC, SonixApache commented
add `closes #35300` somewhere to your OP so the collabs can auto-close it on merge.
Add a changelog to the end of your OP, something like this
```
 :cl:
  - rscadd: Thanks to >>453861032, you can now paint on floors with a paintbrush.
```

2023-11-11 22:44 UTC, jellyveggie2 commented
Code seems good, and other than making the pull request straight from Bleeding-Edge rather than a separate branch, the PR itself seems good too. Not that that should be an issue in this case I think.

@kilozombie 
> Did you test it ingame to see if it works?

Looking at the thread, I'm not sure he's ever set up a local server before. I'll test it a bit and report with results.

2023-11-11 23:01 UTC, jellyveggie2 commented
Brush graffitti is working fine, but box-crayoning is adding the same crayon multiple times. Probably an easy fix.

2023-11-11 23:09 UTC, jellyveggie2 requested changes

2023-11-11 23:09 UTC, jellyveggie2 commented on code/modules/html_interface/paintTool/custom_painting_datum.dm
> +				var/obj/item/toy/crayon/c = held_item
```suggestion
				var/obj/item/toy/crayon/c = crayon
```
This should fix the crayon issue, tested it just now.

2023-11-11 23:40 UTC, jellyveggie2 commented
Voltekka, the Closes #35300 should go in the OP text, rather than the title. See #35348 for an example. It should show up in the "Development" section here if done right:

> <img src="https://github.com/vgstation-coders/vgstation13/assets/78439377/8647003d-af64-4b73-b72b-53dd7273a98a" width=60% height=60%>


Also, there's no need to credit me in the changelog for a minor review. Keep in mind that changelog is what will go into the in-game changelog later on, verbatim:

> <img src="https://github.com/vgstation-coders/vgstation13/assets/78439377/57acb2ba-37d5-4f68-adf7-202c908adc7a" width=40% height=40%>

2023-11-12 00:15 UTC, Volttekka commented
Understood

2023-11-12 15:23 UTC, Eneocho commented
Thing is this doesn't quite close that feature request. Sure, you get all the colours from a regular crayonbox at once, but you are still limited to the main + shade of the rainbow crayon, which is why deleted the post saying this fixed it.

2023-11-13 01:04 UTC, Inorien commented
>clown crayon power creep

i knew it would come one day

2023-11-18 23:08 UTC, merged