Spessmen have unlocked the ability to look foward
d3athrow/vgstation13 pull request #35413
Opened 2023-11-19 22:51 UTC by ShiftyRail

Oh boys, this is going to be controversial.

## What this does

https://github.com/vgstation-coders/vgstation13/assets/31417754/75a33094-e67c-4efb-b1f6-aea66b0ec065

Click on spell, click on tile, you are now looking in that direction. You can also peek around walls corners, or use it through wall that have had a hole drilled on them.

Specifics:
- 4 tiles range, need an uninterrupted line of sight between you and the target.
- doesn't let you see through walls. If there's a wall between you and a tile, it'll be obscured
- flexible for future dev: you would be easily able to adjust the range for race, for example
- all living mobs can do it. Can restrict it to humans easily, again.
- moving, being moved, being hit, being touched, all this breaks your focus and drags you back to your tile.

## Why it's good for the game

There's a lot of places in ss13 where the 15x15 viewport shows its limitations. For example, Wheel's chapel is too big. Some other stations' court rooms are too big. Sometimes it's difficult to fit enough people in one space without it getting cluttered.

This aims to solve this, but also to give some new nice gameplay element by being able to look further than you can be seen, for example, to watch over a position, or to look through a wall, or other things. I think this has quite a few gameplay options.

## Point of contention

Yeah, it's a spell. I know, it adds a whole more button to the UI. My personal opinion at this moment is that it's probably the best way to do this. I will attempt to explain why:

- I think it's a big gameplay change, and I want people to be aware of it at the outset. Being able to see people from 3 tiles away can be very good for setting up ambushes, or just for other stuff. Simply speaking, I don't want this to be a secret feature that you have to """learn""". The game should be accessible, just because it wasn't designed as such at the start doesn't mean it should still be designed this way.
- All other options suck. A verb is a non-starter: verbs are shit, you can't pre-target a turf or a mob with them, people don't know they are here. Total verb death. The only verbs people commonly use - Rest, Cancel-Camera-View, Activate-Held-Item, etc - are all without a paramater. 
- A shortcut *is* a possible option, and one I'll do if enough people want to, but frankly, there's more than enough "secret shortcuts". Plus, sometimes it doesn't always work. Click code is prone to lagging (at least on my machine).

I'm open to any other suggestion (that isn't a verb).
Cheers

:cl:
- rscadd: You can now look forward and slightly shift your field of vision. Spy on people from afar. Watch the full courtroom from the back room. Do what you want.

2023-11-19 22:52 UTC, nervere commented
Balance and gameplay implications aside (which are well worth considering IMO), a permanent spell on the screen instead of a keybind is very, very silly.

2023-11-19 22:55 UTC, nervere commented on code/modules/spells/general/look_at_tile.dm
> +		message_admins("[i] at [current_turf.x], [current_turf.y]")
you left in this debugging line

2023-11-19 23:04 UTC, ValkyrieSkies commented
How does this affect hearing?

2023-11-19 23:13 UTC, ShiftyRail commented
@ValkyrieSkies It doesn't.

2023-11-19 23:16 UTC, gurfan commented
This sounds like a cool thing to add! I'm not going to bother reading the description until it's no longer a spell, though. :-1:

2023-11-19 23:21 UTC, ValkyrieSkies commented
> @ValkyrieSkies It doesn't.

Doesn't that kinda entirely defeat the courtroom example given?

2023-11-19 23:28 UTC, djkramer123 commented
Disregarding it being a spell (lol), being able to see a larger area usually requires some amount of work(having a head borer with upgrades, genetics) or uses your hands(scope, binoculars). Being able to look forward for free and blast people off screen is strong, and fairly unfun for the other person. Even just being able to spy on what someone is doing without them knowing is strong enough to make adding this worrisome

2023-11-19 23:32 UTC, ShiftyRail commented
No longer a spell. For info, it took about 0.8% of your screen space. And I check, it's resolution independent.

@ValkyrieSkies fair. I can probably make this work for hearing as well.

2023-11-19 23:47 UTC, GreatBigFailure commented
I like the idea and I don't think it being a balance thing would be an issue, but I do agree with the spell thing others dislike. 
Just shooting out spitball ideas for compromises: 
- If the spell AND balance are both an issue: Maybe make it work with certain eyewear. Glasses, contacts, goggles, you could click the equip "spell" icon, like the wrist watch in the clip, to trigger it. 
- If just the spell is the issue: Put a button beside bite/kick for it. Have it be little eyes. 
- Reduce the size of the "Gun auto" button and use that new space for this. 

Let people make their own keybinds for it, but make it available without doing so.

2023-11-19 23:48 UTC, ShiftyRail commented
@GreatBigFailure it's no longer a spell

2023-11-19 23:59 UTC, boy2mantwicethefam commented
I think the reason people don't like it is because it's too much degree of separation from what people expect from the game, too mechanically unusual to stare up in the front without any aid.

2023-11-20 00:06 UTC, pedr69 commented
some suggestions:
turn the spessman the direction he's looking - in the example vid you can look behind you
require your hands free to do this and give the spessman a "hand binocular" item for the duration - picrelated
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/bf94317a-0e5c-4118-bb69-b318607a1c68)

2023-11-20 00:06 UTC, juanototo2 commented
This will make lasers and other hitscan lethal-damage actually useful against targets that aren't stun immune. Therefore, I upvote.

2023-11-20 01:04 UTC, Eneocho commented
Seconding pedr's suggestion, make it use "hand binoculars".
>doesn't let you see through walls. If there's a wall between you and a tile, it'll be obscured

Does this account for x-ray?

2023-11-20 01:10 UTC, DorainGrey commented
Can you show an actual example of peering around walls etc?
Kinda hard to judge.

2023-11-20 01:16 UTC, wotisjanitor commented
If anything this should be a verb

2023-11-20 05:55 UTC, SonixApache commented
can  you make it like, ctrl+middleclick or something so my vision doesn't shift constantly whenever i miss-click on dragging someone

2023-11-20 06:16 UTC, xXxEMBERGHOSTSQUADDIExXx commented
does this fix #35161?

2023-11-20 07:24 UTC, d3athrow commented
would be much cleaner and potentially less abusable if it were a keybind+click&hold to set the eye at the current pointer position.

2023-11-20 07:24 UTC, falcon2346 commented
> can you make it like, ctrl+middleclick or something so my vision doesn't shift constantly whenever i miss-click on dragging someone

Seconding this. It's more obscure, but as far as I'm aware at least that particular combination isn't used for anything. Also give vox a 5 tile range for eagle eyes.

2023-11-20 07:31 UTC, xXxEMBERGHOSTSQUADDIExXx commented
this isn't really how eyes work

2023-11-20 08:33 UTC, ShiftyRail commented
@pedr69 @d3athrow things worth exploring

@SonixApache Middle Mouse Button is broken for me in byond :(
But I'll do it

2023-11-20 08:33 UTC, ShiftyRail commented
@xXxEMBERGHOSTSQUADDIExXx Yes, it does fix it

2023-11-20 09:42 UTC, jwhitak commented
This is a really dumb thing to add to the game to everyone for free. Gate it behind an item or something.

2023-11-20 12:40 UTC, Pastamadness commented
I'm definitely feeling like a bit of a reactionary here. I don't trust this not to be exploited by people somehow, despite everyone getting it.
The reasoning being pinned solely on a mapping issue in rooms that only exist for RP don't give it much of a justification to me.

2023-11-20 13:40 UTC, wotisjanitor commented
Imagining a scenario where i have a guy in a deserted corner of the station so i can stab him, but then i get outed because some guy off screen can see me who isn't using the cameras

2023-11-20 14:02 UTC, brndd commented
To address off-screen stalkers, maybe we could add little floating arrows (or other indicators) around the edges of the screen that appear for mobs that are just outside your field of vision. Make them full opacity when the mob is 1 tile out and fade to completely transparent at 5 tiles out.

2023-11-20 14:52 UTC, jwhitak commented
Let me rephrase. This is a great addition to the game - IF AND ONLY IF - it is not given to everyone. A lot of the feedback in the thread, discord, and here seems to agree.

This would be an excellent feature to give to the advanced cybereyes. It would also work wonders being added to special glasses, sniper scopes, genetic eyesight, etc. But giving everyone the ability to just stare forward at whim? Meh.

2023-11-20 15:23 UTC, Dacendeth commented
should be an item and/or a genetic power.

2023-11-20 15:24 UTC, SonixApache commented
I don't think giving this to every player would benefit gameplay.

2023-11-20 15:29 UTC, ShiftyRail commented
Well if I wanted this to be an item or a genetic power I would have PR'd it as an item or a genetic power. My idea was to give something new that would actually change things - sort of like crawling did.

2023-11-20 16:00 UTC, ShiftyRail commented
![image-5](https://github.com/vgstation-coders/vgstation13/assets/31417754/f28feed2-c35d-435d-9567-d7bc360bd27e)

What peeking across corners look like.

2023-11-20 16:23 UTC, xXxEMBERGHOSTSQUADDIExXx commented
on one hand it breaks the view range symmetry thats a pillar of the razors-edge-ness of combat
but on the other hand giving it to everyone could also amp up the robustness skill ceiling like with resting and tackling

2023-11-20 16:48 UTC, Dacendeth commented
I suppose i'm willing to try it as is at least.

2023-11-20 19:19 UTC, John-VI commented
I don't want to be in a situation where I'm liable to be blasted by someone from offscreen because they're looking forward harder (?) than I am. Like, if security might be sitting by a corner looking forward so they can see me before I see them, am I supposed to stop before every corner in the hallway and change my field of view so I can see what's in front of me?

2023-11-20 22:23 UTC, brndd commented
Given how fast our movement speed is, you can probably just run to within 7 tiles of them, turn 360 degrees and moonwalk away before they have time to react, even with forward-looking.

2023-11-20 23:03 UTC, GreatBigFailure commented
A lot of concerns brought up here are similar to when tackling was added. This is also probably most mechanically similar to tackling for reasons like 
>I think the reason people don't like it is because it's too much degree of separation from what people expect from the game, too mechanically unusual to stare up in the front without any aid.

What I mean is that comparing those concerns to how tackling, crawling, or similar features are viewed now can be a good measure. A lot of the concerns here will likely read as overly cautious or hyper-specific if this is added. 
Like getting caught during a crime by someone looking at you from offscreen. Isn't that the point? You could position a lookout as either sec or the criminals and actually benefit from it. If you're worried about a school shooter down the hall you can peek in and maybe save yourself in time. 

Personally it sounds fun. Not everything has to be an item or gene. In fact we have items and genes that do more powerful versions of this and hardly anyone seeks them out, and many don't use them even if they fall into their lap. This is probably not going to affect balance in any significant way.

2023-11-20 23:08 UTC, ShiftyRail commented
Hacked together a shitcode so that you can actually hear what's being said at a distance now - again for the courtroom.

@John-VI how can you be sure such a situation would happen before you've tested it? Like burnddi said, at best, you have a two tiles headstart. Unless the guy is using an autoaimer or an autoclicker, it won't make that much difference.
If this is the argument against it, then I'm not convinced at all and I'm not willing to withdraw this on a weak hypothesis like this one.

2023-11-20 23:13 UTC, wotisjanitor commented
> hear at a distance
That makes it worse

2023-11-20 23:14 UTC, xeroxemnas commented
If I wanted to play IS12 or colonial marines I'd just play those. Stop putting that shit in vanilla spess.

2023-11-20 23:15 UTC, ShiftyRail commented
@wotisjanitor The original intent of the PR is more to be able to look at, and hear things, that are just slightly offscreen without bumping into people. The "hear at a distance" is 3 tiles. Maximum.

2023-11-20 23:19 UTC, GreatBigFailure commented
> If I wanted to play IS12 or colonial marines I'd just play those. Stop putting that shit in vanilla spess.

Is the implication that this could only be used for combat? 
You can look at dangerous things from a further distance, like a hallway engine would be less dangerous to gather around. You can peak into departments to see if you should ring the bell, wait, or break in, etc. There's plenty of every-day uses here.

2023-11-20 23:34 UTC, Moonman1946 commented
I think the idea of giving this to fully assisted eyes is the best. I don't believe assisted eyes do anything at the moment and any emp will blow up your vision, usually unfixable without surgery. (At least to my experience when I wanted to run around with cyber eyes.) Letting cyber-eyed people zoom like that actually gives a reason for someone to want to use cyber eyes.

2023-11-21 00:26 UTC, Eneocho commented
The only benefit to upgraded eyes is better vision under dark conditions (you see about as well as a grey, still worse than a catbeast, if memory serves me well). If anything, robotic eyes are a fucking pain and almost never worth it, cause if they get damaged for any reason, you need to get your skull opened for repairwork instead of eyemeds.
I say experimental merge this for a few weeks, then revert, then see if we keep as vanilla or implemented on the robo eyes.

2023-11-21 08:13 UTC, ShiftyRail commented
Having slept on it, upgraded eyes *could* be the only thing that would make sense, but as said previously: I really had the idea of this as a new gameplay element, something that actually changes things. Like crawling did, like tacking did, like re-enabling rest spam did in #23314.

2023-11-21 08:21 UTC, xXxEMBERGHOSTSQUADDIExXx commented
stick to your guns on this one imo
we can consider the upgraded eyes thing seperately

2023-11-21 08:25 UTC, ShiftyRail commented
![binoculars](https://github.com/vgstation-coders/vgstation13/assets/31417754/35ac36bd-8107-4023-b885-bf8e37dcfaa9)

Comparison of leaning in and using binoculars. I think this image shows the two are absolutely not comparable.

2023-11-21 11:36 UTC, jwhitak commented
For a groundbreaking new gameplay element, it's getting very mixed response. Most people seem to like this idea(!), but not everyone agrees on if it should be given to all speesemen freely - to the point of the PR being 10-15 as of this post (with some permanently banned people on the 10 side). Crawling was almost all positive (though this was before emojicracy iirc), tacking was almost all positive, re-enabling rest spam was almost all positive. This one is way more mixed. Please reconsider this as a major gameplay change.

2023-11-21 11:50 UTC, ShiftyRail commented
From testing: it doesn't even let you shoot more than once.

2023-11-21 12:25 UTC, jwhitak commented
No, it's not that big at all. Just another factor in the pile of crushing paranoia that is SS13.

2023-11-21 13:01 UTC, wotisjanitor commented
I mean, I think this will legitimately change gameplay. Nobody comes to science asking for any robot organs or limbs, and that may change now.

2023-11-21 13:10 UTC, ShiftyRail commented
OK, i'm starting to see the writing's on the wall. One tile + look around walls with normal eyes.

3 tiles augmented eyes. 

I will code it in such a way that test rounds where everybody has 3 vision are possible just for observations.

Deal?

2023-11-21 13:18 UTC, brndd commented
That seems like a pretty good compromise. One tile is probably all it takes for rooms like the courtroom that are normally too big to see everything, and making cyber eyes actually useful seems like a cherry on top.

2023-11-21 16:07 UTC, GreatBigFailure commented
Having cyber eyes give a longer range makes sense, but I hope the organic eyes version isn't nerfed to uselessness for the compromise. Make sure to post comparison pictures if you can. 

Just spitballing an alternative: What if organic eyes narrowed your vision but had the current range? Like you could effectively **only** see in a cone in that direction

2023-11-21 16:24 UTC, ShiftyRail commented
Vision cones arent a good idea. As far as cyber eyes go, remember - they're vulnerable to EMPs.

2023-11-21 19:52 UTC, Eneocho commented
I feel we should just merge the thing as is without the compromise for a week experiment. It seems like a decent, if slightly out of place idea, but several such ideas started that way and are now staple. I say we give it a try.

2023-11-21 20:34 UTC, wotisjanitor commented
>we shouldn't test metge this


>just give it a try


?

2023-11-21 20:47 UTC, xeroxemnas commented
It's telling when half the people upvoting this trash are either permabanned or literal whos who don't even play. 
![54745757](https://github.com/vgstation-coders/vgstation13/assets/38308926/a407e39d-4e92-4f2c-a5fd-85581009003e)

2023-11-21 21:16 UTC, ShiftyRail commented
Calling it "trash" isn't really what's going to convince me to not at least try this on a test merge, man.

2023-11-21 21:20 UTC, xXxEMBERGHOSTSQUADDIExXx commented
delete that before everyone sees it imo

2023-11-21 21:49 UTC, xeroxemnas commented
> Calling it "trash" isn't really what's going to convince me to not at least try this on a test merge, man.

Yeah you'll just cry about it on discord instead then block anyone who disagrees with you lmao. Grow some backbone.

2023-11-22 06:00 UTC, SonixApache commented
test merge it and see how it goes for a month or two

2023-11-22 08:33 UTC, ShiftyRail commented
A month? Nah. A week would be enough.

2023-11-23 12:27 UTC, bathosbathtime commented
One of the reasons AI is a power role is that they can constantly see people who can not see them. I don't see how this change would have any impact other than making antags even more timid. The speed at which players move across the station means that this won't be useful for scouting out before a crime except to look out for people specifically using this mechanic to watch you. So it ends up just being another point of pressure against an antagonist that doesn't seem to have meaningful counterplay outside of glancing over your shoulder constantly which itself would eat into the time constraint you have when committing a high profile crime before someone eventually runs in from off screen and catches you in the act.
Frankly I don't see a single positive outcome this would have on gameplay. Do you have any intentions other than "shake things up?" There must be better solutions to subpar mapping.

2023-11-23 13:00 UTC, ShiftyRail commented
The comparison with AIs is a bit surprising. A leaning spessman is only 3
tiles away from the person he spies on. A leaning spessman cannot spy
through walls, and he gives up 3 tiles vision on his back to be able to see
forwards.

Oh, and he cant shock doors from far away either. A secoff on cam duty is
much closer to the AI than a leaning spessman.

As far as combat goes, here are a few things you can do:

- as an antagonist, camp the body of a guy you killed to punish imprudent
first responders. In particular, people who rush SPSes alone can have their
movement predicted easily.
- as a first responder, check if the path to a body is clear.
- as a warden, keep an eye on the desk without being seen from greyshirts.
- as an armoury raider, punish the warden for focusing on the desk by
sneaking up behind him.
- want to free your friend who's in perma? Can always lean forward to see
where he is and if sec is closeby.

In most cases, this rewards people with a plan and punishes people without
one. You can invent someone who's always looking 3 steps ahead in any
situation, but in practice that's kinda hard to do.

There are other non-combat uses as well. You can look at the courtroom from
the back rank without getting in the way of traffic. You can look at
something without pushing away other people. The chaplain or bartender can
shift his viewpoint to get a better view of what is happening and get
prettier screenshots. A mommi can look at carbons engines without being too
close.

Worth noting that you cant use this on a mech, on a spesspod... the actual
uses are quite limited.

So why merge this? One part new combat strats - which as it happens
advantage skillful players more, and in particular, antags - one part QoL
for looking around without shuffling people too much, one part for
unexpected new stuff. I want to see how this changes things. It could be
fun.

Worse come to worse this is easy to revert. I am curious to see how this
goes but this isn't like it's a 2000 lines big project that I have
emotional attachement to - this is just a simple, silly, gameplay idea.

Le jeu. 23 nov. 2023, 12:27, Bathos Bathtime ***@***.***> a
écrit :

> One of the reasons AI is a power role is that they can constantly see
> people who can not see them. I don't see how this change would have any
> impact other than making antags even more timid. The speed at which players
> move across the station means that this won't be useful for scouting out
> before a crime except to look out for people specifically using this
> mechanic to watch you. So it ends up just being another point of pressure
> against an antagonist that doesn't seem to have meaningful counterplay
> outside of glancing over your shoulder constantly which itself would eat
> into the time constraint you have when committing a high profile crime
> before someone eventually runs in from off screen and catches you in the
> act.
> Frankly I don't see a single positive outcome this would have on gameplay.
> Do you have any intentions other than "shake things up?" There must be
> better solutions to subpar mapping.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/35413#issuecomment-1824347796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPWLGV4XM76ROT3MTVH7GTYF46MJAVCNFSM6AAAAAA7SBV2ISVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRUGM2DONZZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-23 13:03 UTC, ShiftyRail commented
Also while I understand runechat was much less downvoted and had overall more support, the game kind of fearmongering (from you included, Bathos my dear friend) was discussed in the PR, and in practice runechat did not change fundamentally the way spessmen talk - while being a net positive change in QoL.

2023-11-23 13:22 UTC, bathosbathtime commented
I'm unconvinced this change has any merit.

2023-11-23 13:23 UTC, ShiftyRail commented
Well, at least we can both admit we aren't turning spessmen into AIs.

2023-11-23 14:25 UTC, SalmonIsTasty commented
I have mixed feelings about this PR, but I might just be too accustomed to the old ways

2023-11-23 15:29 UTC, SonixApache commented
> One of the reasons AI is a power role is that they can constantly see people who can not see them. I don't see how this change would have any impact other than making antags even more timid. The speed at which players move across the station means that this won't be useful for scouting out before a crime except to look out for people specifically using this mechanic to watch you. So it ends up just being another point of pressure against an antagonist that doesn't seem to have meaningful counterplay outside of glancing over your shoulder constantly which itself would eat into the time constraint you have when committing a high profile crime before someone eventually runs in from off screen and catches you in the act. Frankly I don't see a single positive outcome this would have on gameplay. Do you have any intentions other than "shake things up?" There must be better solutions to subpar mapping.

see this was my initial thought as well
and then i remembered the time i kept looking into the detective's office to see if he was there and he caught me looking into his office and got suspicious
if we had this, i could've looked into his office, seen him there, and delayed my arrival to make him less suspicious

so i want to test it out

2023-11-23 18:23 UTC, DorainGrey commented
I was unconvinced at first but I think this is worth test merging and then just server polling in a week.
If nothing else it'll be interesting.

Need to stop treating code changes as permanent IMO.

2023-11-23 19:22 UTC, wotisjanitor commented
they are always permanent

2023-11-23 19:28 UTC, SonixApache commented
> they are always permanent

much like your presence on the server, right?

2023-11-23 19:29 UTC, wotisjanitor commented
Yeah

2023-11-23 19:32 UTC, Eneocho commented
> they are always permanent

Just have kurf or a c*llab make a revert pr immediately after this gets merged with a reminder to revert on X day. That's more reliable for an experiment merge, rather than having the thing "experimentally merged" but the experiment never ends.

2023-11-23 21:01 UTC, GreatBigFailure commented
I don't think this will be nearly as useful for combat as people seem to think. Shifty please correct any of this if I have it wrong but:

- It limits your vision in the opposite direction
- You need to be standing still
- It's a significantly shorter range than our current ways to expand view
- The "spessmen are fast" logic applies here too, where in antags won't be able to perfectly snipe you running past, and secoff won't teleport cuffs onto you when you antag shuffle past them either
- **Most importantly: This is an extra button press and half-second commitment.** Combat speculation on paper always sounds hilariously overpowered. I mean look at baseball bats. All you need to do is toggle throw with a hotkey between every swing to be nigh invincible while still beating the person up, but no one does that because it's hard and extra mental-capacity already taken up spam clicking and dodging tasers 

Some people will get caught greytiding because of this. It's more of a buff to sec/command than anyone, that's fair, but so what? It's a buff in the right direction in my opinion. Being able to see someone commit a crime without them seeing you is a big RP buff. Buddy cops and someone is robbing the vault? Inflatable wall the hallway so you can peacefully arrest. See someone break into the armory? "AI please bolt the armory shut and let us know if the person inside is welding out", etc. 
This is coming from someone who is, in 99% of rounds, not acting in security's best interest.

I just don't think spessmen are going to stand around in the halls staring forward waiting for things to happen so they can leap in. I think it'll be useful for mundane things like peaking into departments, checking on things while maintaining conversations, and observing round-events like court cases. 

I think you're all being a little silly with your hypothetical perfect key-press 10,000 APM eagle eyed spessman watching you and killrresting you from across the station.

2023-11-24 15:28 UTC, ManopolisJones commented
This really isn't something that should be on /vg/ station, and in my opinion will only exist to further whittle down the identity of the classic ss13 experience that we have now.

2023-11-24 15:34 UTC, Pastamadness commented
> This really isn't something that should be on /vg/ station, and in my opinion will only exist to further whittle down the identity of the classic ss13 experience that we have now.

You say classic, I say regular.
You say modern(TG branch), I say terrible mess.

2023-11-26 06:40 UTC, Kurfursten commented
I see a lot of real accounts voting up and a lot of sockpuppets voting down. Still, this would be a remarkably big change so I'm inclined to ask for a vote given that there is clearly a lot of community care one way or the other.

2023-11-26 08:44 UTC, bathosbathtime commented
Would it be a vote for a test merge or regular merge? There are a few comments requesting a test merge and shifty has mentioned he would like at least that but we can move straight to a full merge vote if you feel it appropriate. It is also possible to have both a test merge and full merge as options on the vote but that would split the vote and make either more difficult, though we could simply count them both as yes and simply go with whichever is higher of the two if the total outweighs the no votes. Still, additional complications in options can be a turnoff and might result in users skipping over the vote entirely if they see too much text.

2023-11-26 09:40 UTC, SonixApache commented
teste merge into server vote

2023-11-26 09:42 UTC, Kurfursten commented on code/_onclick/click.dm
> +		if (H.mind.assigned_role == "Clown")
you should check for clumsy instead of checking assigned role

2023-11-26 09:51 UTC, Kurfursten commented
> Would it be a vote for a test merge or regular merge? There are a few comments requesting a test merge and shifty has mentioned he would like at least that but we can move straight to a full merge vote if you feel it appropriate. It is also possible to have both a test merge and full merge as options on the vote but that would split the vote and make either more difficult, though we could simply count them both as yes and simply go with whichever is higher of the two if the total outweighs the no votes. Still, additional complications in options can be a turnoff and might result in users skipping over the vote entirely if they see too much text.

In terms of code this is actually very small and doesn't meet my +200 cutoff for automatic trial on live. I will leave the vote specifics up to you headmins in that case.

2023-11-26 10:57 UTC, ShiftyRail commented
My personnal preference is to merge this for a week, automatic revert, and
then ask the following question:

"The PR #XYZ has been test-merged for a week. Should it be merged again ?"

This would have two benefits: one, it's merged for enough time to try it,
two, it is automatically reverted so there's no risk of it "sneaking in".

Le dim. 26 nov. 2023, 09:52, Kurfursten ***@***.***> a écrit :

> Would it be a vote for a test merge or regular merge? There are a few
> comments requesting a test merge and shifty has mentioned he would like at
> least that but we can move straight to a full merge vote if you feel it
> appropriate. It is also possible to have both a test merge and full merge
> as options on the vote but that would split the vote and make either more
> difficult, though we could simply count them both as yes and simply go with
> whichever is higher of the two if the total outweighs the no votes. Still,
> additional complications in options can be a turnoff and might result in
> users skipping over the vote entirely if they see too much text.
>
> In terms of code this is actually very small and doesn't meet my +200
> cutoff for automatic trial on live. I will leave the vote specifics up to
> you headmins in that case.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/35413#issuecomment-1826738284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPWLGUAZ63M5JITIQXOV2DYGMGMDAVCNFSM6AAAAAA7SBV2ISVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRWG4ZTQMRYGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-26 13:16 UTC, 9percents commented
Looks interesting, but will affect a lot of stuff, not just combat. It feels like it will just change everything.

Test merge will probably be a fun event, but permanent is questionable at this point.

2023-11-26 13:20 UTC, ShiftyRail commented
Before this is merged I want to add in a 15% chance every life tick for the
people being spied on that someone is spying on them + a message on
examine. I will be unable to do this for this week though.

Le dim. 26 nov. 2023, 13:16, 9percents ***@***.***> a écrit :

> Looks interesting, but will affect a lot of stuff, not just combat. It
> feels like it will just change everything.
>
> Test merge will probably be a fun event, but permanent is questionable at
> this point.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vgstation-coders/vgstation13/pull/35413#issuecomment-1826782078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHPWLGWV3U3SN2IXJP4MK2LYGM6JZAVCNFSM6AAAAAA7SBV2ISVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRWG44DEMBXHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-26 14:26 UTC, xXxEMBERGHOSTSQUADDIExXx commented
Would we really be talking about forcing a test merge against popular opinion if the author wasn't shifty? I think this is kind of a breach of the common practice and an example of discord-favoritism.

2023-11-26 14:57 UTC, brndd commented
The emojicracy is close enough that it's more controversial than it is against public opinion. Controversial changes are one of the main reasons testmerges exist.

2023-11-26 15:43 UTC, ghost commented
That's wrong, skid. Testmerges exist for the big and complicated updates in need of live feedback on bug fixes and possible improvements, see ShiftyFail's lightning system on a test server. This change is not big in and of itself but rather all of its consequences are, therefore it has no reason to be test-merged. Nobody in their right mind would suggest test-merging TG's combat system here because it takes a fundamental game mechanic and replaces it with cancerous gamer shortcuts, akin to this.

2023-11-26 15:45 UTC, xeroxemnas commented
There are 6 more negatives than there are positives, not to mention secmain is gitbanned so it's really more like 14-21. There are far less controversial PRs that got instantly closed due to lack of support. I'm not sure why Shifty gets a free pass here. Maybe if he worked on being less of an insufferable person then people would be more willing to give him the benefit of the doubt.

[](https://github.com/vgstation-coders/vgstation13/pull/35398)

2023-11-26 15:56 UTC, ShiftyRail commented
#32781 was closed because it was derelict. The air alarm chirping PR feels a bit different from this one because it's not touchant the gameplay in the same way.

2023-11-26 16:06 UTC, bathosbathtime commented
The server vote is what we would use to accurately determine where exactly popular opinion is so we can not at this time argue as if we know where this PR falls under popular opinion. Further, the collab has the authority to merge code that is unpopular if they believe it is in the best interest of the server. And while he has the authority to do so, I am the one talking about a test merge and not Kurfurst. I will not entertain the idea that I am biased in _favor_ of this change. A week long test merge would be the most accurate way of determining the server's opinion on this change, and I have asked Luzzy if he supports this idea or if we should go with a more decisive yet less accurate server vote for a full merge/deny. Vision is one of the most important parts of this game and I believe such a change in the fundamental nature of this mechanic, that anyone can do for free, should be determined with the best possible information available.

2023-11-26 16:14 UTC, brndd commented
A couple of the votes on this PR are from sockpuppet accounts that have been banned from GitHub. I know this because their votes aren't included in the reaction data from the API:

```
./scripts/list-github-reactions.sh https://github.com/vgstation-coders/vgstation13/pull/35413
+1: Securitymain, GreatBigFailure, west3436, juanototo2, brndd, Dacendeth, SnakeEater14, SageOfLight, JTGSZ, kacurasuo, SonixApache, RealestEstate, DorainGrey
eyes: Eneocho
-1: nervere, JonathanSpaceStation, djkramer123, xeroxemnas, Moonman1946, MercuriusGH, xXxEMBERGHOSTSQUADDIExXx, Volttekka, smashedandslammed, wankov, John-VI, wotisjanitor, jwhitak, Laz0rG, NigglyWiggly, bathosbathtime, ManopolisJones, ValkyrieSkies
```

That being said it seems this affects both the up- and downvotes in equal numbers. Just thought I'd point it out.

----

Out of curiosity I ran [the same script](https://gist.github.com/brndd/de89c8b314e94e63201d802267a8ba9f) on #32781 which seemed like a pretty close equivalent of this PR, and it also had banned socks manipulating the vote. The real vote discounting banned accounts on that PR was 14-19, and at least one of the downvotes is from this as-of-yet unbanned but still obvious sockpuppet: https://github.com/N3Xl5 (that's n3x15 with a lower-case `L` instead of a `1`).

In other words, don't place your unwavering faith in emojicracy, and even then a 40% to 60% vote definitely meets my definition of controversial.

2023-11-26 19:14 UTC, Kurfursten commented
@xeroxemnas 
> far less controversial PRs that got instantly closed due to lack of support

None of those PRs were closed instantly.
A third of those PRs were closed by their own author.
Another third of those PRs were literal jokes.
And you are claiming that Shifty gets a free pass over... Shiftyrail? One of those PR's you linked was his.

This is why we don't work on an emojiocracy. Aside from all the sockpuppets, we have some posters who never got their alkysine after cloning.

2023-11-27 05:21 UTC, bathosbathtime commented
As per the headmins:
Luzzy wants to use the large code changes, where there is a trial, test, and a vote. It is unclear to me the difference between the trial and the test but I get the general idea. If I understand correctly, a test merge.
I am in favor of a test merge followed by an automatic revert after a week, and a server poll after the revert. As I won't be doing the work to coordinate the automatic revert nor hotfixes if needed, I don't mind settling for a server vote before merging anything if that's all that's logistically viable.
However, Pomf has said that he is against this change unless his comment is implemented. Which would be the hotkey and click+hold to set the eye at the current pointer position.

2023-11-27 05:34 UTC, Kurfursten requested changes
Implement click+hold

2023-11-27 10:26 UTC, ShiftyRail commented
Sure, will do. Although if that does pass with click&hold I want to float around the idea of the original control scheme at some point. But no testmerge will be needed for that one.

2023-11-27 17:37 UTC, Eneocho commented
> And you are claiming that Shifty gets a free pass over... Shiftyrail? One of those PR's you linked was his.

Was gonna make a reference to that one simpsons scene where Janitor Willy complains that scots ruined scotland, but couldn't figure out how to phrase it.

2023-11-27 23:40 UTC, Kurfursten commented
Clowns and mimes are natural enemies, like /vg/ and TG
And /vg/ and Bay
And /vg/ and /vg/
Damn /vg/, they ruined this board

2023-11-28 00:17 UTC, wotisjanitor commented
Clowns and mimes don't even fight anymore

2023-11-28 00:36 UTC, Eneocho commented
Would've been more fitting as "Clowns and Seccies", cause most of the times now the clown and the mime are in kahoots for whatever bullshit they planned earlier.

2023-11-28 17:33 UTC, GreatBigFailure commented
> Implement click+hold

Just to be clear, this would mean you could **only** squint and peak at a distance, and in order to use your mouse for anything else it would require unsquinting, ya?
I already supported the PR so it's not a swayed vote, but I do think that's the best implementation. Only downside to it is it's a nerf to screaming down the hallway long-distance conversations, but oh well.

2023-11-29 17:22 UTC, Mintgreen01 commented
> I see a lot of real accounts voting up and a lot of sockpuppets voting down.

![3 It can't be that bad](https://github.com/vgstation-coders/vgstation13/assets/32711796/cc18707b-5c1c-40b8-987e-625474ec320d)

Since when are these "sockpuppets" an issue? Since recently, when Nervere/Burneddi/ShiftyFail/[insert any other full-of-themselves script kiddie here] made an out of the blue claim that it is one now?
![Безымянный](https://github.com/vgstation-coders/vgstation13/assets/32711796/f1a26a0f-d916-4e79-910a-5c08db62f14e)


As for the PR itself, in short: it breaks a fundamental game mechanic - fixed FoV - that has always been consistent with the game on all the servers all the time. All the maps in this game were made with this very thing in mind. The biggest change regarding this mechanic anywhere ever was vision cones that don't even manipulate the FoV itself.

Therefore, seeing as how even the "modern" or non-SS13 servers didn't dare to mess with this fundamental aspect of the game, this has absolutely zero (0) merit to be messed with on an old-school SS13 server. It shouldn't even be up to any kind of vote in the first place for that matter no matter how hard you try to claim everyone with an opposite view is a "sockpuppet", and I'm positive the majority will vote against this anyway.

On an unrelated note, the idea in itself would work and be approved by many as a passive ability locked behind some sort of effort to get (robotic eyes, a rare genetical power, etc) or a certain status (wizard's artefact, an item only available in a mime's uplink), but seeing the "all or nothing" attitude of this author, I say let him see this get closed only for someone else to pick it up and rework this into something awesome. This might just serve him a lesson.

Also
> Would we really be talking about forcing a test merge against popular opinion if the author wasn't shifty? I think this is kind of a breach of the common practice and an example of discord-favoritism.

2023-11-29 17:38 UTC, Kurfursten commented
Concerns about vote manipulation have been around since the start of the year but we officially had a meeting about it in June with administration. The word sockpuppet is the new meme but it's something that has really been growing for years now. And yes, we would be talking about a test merge followed by voting because it's content and that's also part of the content policy established at the June meeting. Although, I should note you are begging the question here - you are assuming your proposition (against popular opinion) when that's not clear. 

I understand you're a new player who has been here just a few weeks so you wouldn't be expected to know these things.

2023-11-29 18:51 UTC, xXxEMBERGHOSTSQUADDIExXx commented
With the sockpuppet concept, are github accounts not linked to a known player ckey considered sockpuppets? or are sockpuppets only accounts known to be duplicated or held by permabanned players? It might be a little hazy because a player could choose to make an account for voting on GH without having it correspond to their ckey

2023-11-29 18:52 UTC, Pastamadness commented
We certainly have seen fake probes and nexis recently.

2023-11-29 19:38 UTC, Mintgreen01 commented
> It might be a little hazy because a player could choose to make an account for voting on GH without having it correspond to their ckey, but does that count as a sockpuppet?
> 
> like if a new account appears and gives feedback on a pr, that doesn't mean it's a sockpuppet necessarily as maybe someone just finally decided to make a GH account

Obviously, UNLESS you happen to hurt a local script kiddie's bloated ego. Then you are a sockpuppet and deserve to have your account suspended.

2023-11-29 19:45 UTC, ShiftyRail commented
Before we get lost in white noise:

- will implement Pomf's suggestion, hold to view (although I do hope the test will show it is unnecessary)
- will implement a chance for players being spied on to get a random message
- will make it so you can see who spies on you via emojicracy.

As a proud script kiddie with over 800 PRs merged, I am just curious as to how this changes the game.

2023-11-29 20:18 UTC, Mintgreen01 commented
> As a proud script kiddie with over 800 PRs merged, I am just curious as to how this changes the game.

See, that's exactly what I'm talking about. Even in your attempt to come off as smug and sarcastic, unironically bragging about wasting years of your life coding in a baby's-day-out game engine you didn't miss the opportunity to stroke your ego by actually taking pride in something this insignificant. Nuff said.

2023-11-29 20:33 UTC, ShiftyRail commented
Buddy, I coded two Database reworks, a good half of the gamemodes ported for dynamic, a lighting system, the advanced graffiti and the painting DB. I like those features, I enjoyed coding them, and for the ones that did get merged and are played every day, I enjoy seeing them in action. It's simple as that: contributing is fun. Otherwise people wouldnt do it.

For this one I want to see how it looks like. There are opinions one way or the other. Let's test this. Maybe it'll be a fun addition to the game; maybe not. Let's see.

The sockpuppet thing is funny if true (and it's probably true). I cant imagine someone doing this, tbh.

2023-12-01 11:10 UTC, kacurasuo commented
Please make it not try to peek when you're a ghost

2023-12-10 03:52 UTC, Cartlord commented
This was compared to crawling, rest-spam, and tackling. I'll give my two-cents on that.
Crawling is awkward, a bit slower than running, and doesn't let you use items.
Rest-spam, while not something I'm very experienced in dealing with, seems like it has the obvious downside of dropping your items (unless you can rapidly add to and remove from backpack).
If you miss a tackle or your target has something that makes them less likely to be knocked down by it, you're down and they aren't.
The common thing here is that these all require skill, have a downside, or have something resembling counterplay.
What is an actual situation where you have counterplay to this? How are you meant to deal with it? Are you expected to just always look around yourself before you do anything suspicious, to make sure nobody's watching? What about when (not if) someone watching notices you look in all four directions rapidly and then knows you're up to some shady shit (because why else would you do that)?
It was also compared to a Security Officer operating cameras, but then there's the matter of opportunity cost - that isn't something that can be effectively done on low-population rounds because you won't have enough people to effectively respond to situations spotted on cams, and even if there are other people there's still the simple fact that one guy on cams is one guy who can't respond to threats as effectively (not to mention the number of ways antagonists can deal with cameras).

In short: while most other major things cited here have meaningful downside or counterplay, no such thing seems to exist for long-sight, as you can simply put your back to a wall to negate the lack of rear view.

2023-12-10 05:42 UTC, Kurfursten commented
I think the clickhold is a good solution because it's both intuitive to use and kind of a pain to maintain, having to hold click down prevents you from doing other things. I think it might be nice if the examine text on someone would indicate if they are currently peering in a direction though. Or something visual, like slightly tipping their sprite in the direction of their lean.

2024-01-19 12:30 UTC, Kurfursten commented
I believe Shifty is taking a break right now so this is derelict.

If you would like to reopen this, please do so implementing the clickhold solution that both Pomf and I have requested. This is not an emojiocracy, so I'm willing to give it a test-run if you will meet our request. As I said six weeks ago in my most recent comment, I believe clickhold provides a significant counterbalance to the advantages provided by looking forward.

2024-01-19 12:30 UTC, closed without merging