[revival] tile replace shortcut
d3athrow/vgstation13 pull request #35649
Opened 2023-12-21 07:41 UTC by nervere

## What this does
Closes #34990
This is a modified revival of Dorian's floor tile replacing shortcut.
To do it, have a floor tile in your active hand, and a crowbar in your inactive hand.
Click floor tiles to instantly replace them AND have the old floor tile appear on the tile.

Preview:
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/76c771cb-c763-41f4-b950-c9ec2dc8a7b1)

[tested][qol]
## Changelog

:cl:
 * rscadd: You can now replace tiles quickly by holding the stack of tiles in your main hand & a crowbar in your off hand.

2023-12-21 10:39 UTC, jwhitak commented
How does this interact with wooden floor tiles (they get destroyed by a crowbar, you need to use a screwdriver to safely remove them)?

2023-12-21 11:19 UTC, DorainGrey commented
I was going to fix this but good work !

2023-12-21 11:22 UTC, DorainGrey commented
Note though dilt is right, wooden tiles will be impacted with this.

I also suggest adding an override for Mommis, my plan was just to assume they had a crowbar when using a tile on already tiled floor.

2023-12-21 16:22 UTC, wotisjanitor commented
Why it's good:

2023-12-22 14:14 UTC, SonixApache commented
> Why it's good:

can we ban this guy for being too stupid to click the link to the original PR and generally just posting worthless comments

2023-12-22 22:19 UTC, Kurfursten requested changes
Make screwdriver consistent for wooden tiles

2023-12-26 06:24 UTC, wotisjanitor commented
Factor in the previous votes, please.

2023-12-27 04:50 UTC, nervere commented
I will work on this in a few days, I'm pretty busy with holiday events rn.



> Factor in the previous votes, please.

Those negative votes were because the PR deleted tiles. The change suggested in #34990, which this PR adds, was very popular.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/0d4eeee9-760b-44c7-8a64-2876d533bc29)

2023-12-27 14:33 UTC, wotisjanitor commented
Are you sure? That's not the reason I voted down. Not everyone who voted down also voted up on that comment

2024-01-17 13:18 UTC, Kurfursten commented
A few days...

2024-01-19 07:57 UTC, nervere commented
@Kurfursten Done.
- Macro now works with screwdrivers.
- Crowbars now destroy wood tiles when replacing them, screwdrivers do not.

2024-01-19 11:35 UTC, Kurfursten approved these changes
Update wiki Shortcuts page

2024-01-19 11:36 UTC, merged