The nasa, exca., and anom. suits from xenoarch finds are now contained in boxes. These contain both pieces of the suits.
d3athrow/vgstation13 pull request #36087
Opened 2024-02-27 00:55 UTC by DrSnips

## What this does

Something I found a bit annoying about finding the old suits via xenoarch is that you'll find the one half of a suit and then never find the other.
This remedies the situation by containing both halves in a box and you get the box ask the find from the dig.
## Why it's good

You're no longer screwed from finding the other half of a suit.
It's also nice because the box can be deconstructed in the DA for the anomaly research points.
## Changelog

:cl:
 * rscadd: NASA, Exca., and Anom. suits found from xenoarch digsites are now found in boxes that contain both halves. The box can be DA'd for research.

2024-02-27 01:26 UTC, DrSnips commented
Just getting this out there before some shmuck makes a bug report down the road about nothing going in the box, it's intentional that it can't hold anything. The box is supposed to be "old and useless" and is displayed in the description.
The box can be broken down and remade if you want the storage from a big box.

2024-02-27 01:49 UTC, jwhitak commented
These complainers clearly don't play clown! Boxes that store only the clothing, can't be refilled even with the same clothes you took out, and disintegrate when they are emptied is actually already in our code!

2024-02-27 10:06 UTC, Inorien commented
What would you say to rather than putting both drops together, guaranteeing that both drops will appear in the same xenoarch site? So you find one piece and can be sure that the next piece will be just near it.

> Nope! Only trash here...

2024-02-27 11:09 UTC, Blithering commented
I like the box solution, means you don't get incomplete sets because of a miner ploughing through and smashing the suit section, and tightens up the loot pool a bit. Could this be extended to the cult and Magus sets that can be dug up?

2024-02-27 12:26 UTC, hacker-on-steroids commented
what's next? a receipt and a 2 year warranty?
hello, customer service? the clothes i found in a 400 year old rock deposit don't come in a full set!

2024-02-27 12:30 UTC, DrSnips commented
> together but nearby in another site

1.I want to box intentionally as a waste item you can DA.
2.I'm not touching it to that degree. I'm not paid enough to deal with the spaghetti backbone and risk messing up other finds. Also how do I go about testing such a thing extensively? I spent about an hour trying to just find one of these things alone to test my changes. I'm not doing that again. I was tempted to have the box hard have anomaly research as a safety net and so I didn't have to test that because it doesn't have a tech origin to begin with so I had to go and find one in an actual living site to make sure it worked.

The current code just randomly makes an artifact each time based on the ID type(reagent type like C or Hg). Then updates nearby site's ID types for some rrason with a formula I don' t understand the purpose of. Like why is it trying to calculate a difference of distance and then take the square root of it?
Here's a link for you to get started yourself. https://github.com/vgstation-coders/vgstation13/blob/e7c0a1143e525a040f50a53359ec78243bbfff63/code/modules/research/xenoarchaeology/geosample.dm#L57

2024-02-27 12:40 UTC, DrSnips commented
> I like the box solution, means you don't get incomplete sets because of a miner ploughing through and smashing the suit section, and tightens up the loot pool a bit. Could this be extended to the cult and Magus sets that can be dug up?

I could extend it to that if interest was shown. All the cult stuff is actually a single loot table and then it rolls for which piece you get with a weight. I didn't touch this one because it's mechanically different. I'm not opposed to it but I just want to make sure if that's something that you want to be changed.
https://github.com/vgstation-coders/vgstation13/blob/46092f593b485267db1f27ea874a08075328ca11/code/modules/research/xenoarchaeology/finds/finds.dm#L494

2024-02-27 13:00 UTC, Blithering commented
Personally, I'd like it for the same reasons as the NASA and old suits, to cut down on incomplete sets and 100 hats no suit scenarios. If balance and faking antags might be an issue you could limit it to the ancient sets that advertise you as a fossil nerd rather than a book nerd

2024-02-27 13:08 UTC, Inorien commented
very conflicted over this, xenoarch is meant to be a treasure hunt, if the treasure was packaged as a set then where would be the reward in being lucky/dedicated enough to find the full set

2024-02-27 13:24 UTC, DrSnips commented
As someone who spent an hour to test their changes trying to find it, it's rewarding enough.

2024-02-28 03:00 UTC, DrSnips commented
Cult robes/armor are also bundled now in tesseracts for flavor. Smashing one will give you the goods.

2024-02-29 12:30 UTC, Blithering commented
Nice touch with the tesseracts, adds a bit of flavour

2024-03-06 05:40 UTC, Kurfursten commented
I don't see the code to give it origin tech, or a mech scan fail flag to prevent mechanics from spamming the boxes

2024-03-06 05:47 UTC, DrSnips commented
Was there a specific item that has mech scan fail in these boxes before this or would change behavior if you happened to find these items before this?

2024-03-06 05:58 UTC, Kurfursten commented
Scan items individually = need two blueprints, have to pay true costs, respects individual scan limitations
Scan box = get 2 items for the cost of cardboard instead of suit cost, jailbreak scan limitations

Don't try to fool me, I've learned your mechanic tricks by now

2024-03-06 06:07 UTC, DrSnips commented
And what exactly is the material cost of these suits?
Two blue prints that cost some paper vs one, big whoop there.
Again, can you give a specific example of an item scan capability affected here that was restricted from mech scan. Please post something with a bit more substance.

2024-03-06 06:12 UTC, Kurfursten requested changes, later dismissed
Conduct a review of all suit costs in general fab, let us know your findings

2024-03-06 06:15 UTC, DrSnips commented
Sure thing I'll meet you halfway. Just post the costs the costs for what you expect them to be when found via xenoarch before the changes here so I can make sure they match your expectations.

2024-04-17 11:57 UTC, west3436 commented
@DrSnips post the findings eggman

2024-04-17 12:00 UTC, DrSnips commented
Oh yeah I forgot I had this open still and thought it was closed. I can get back to this.

2024-04-29 03:11 UTC, jwhitak approved these changes

2024-04-29 03:27 UTC, jwhitak commented
To note, this means that the suits which xenoarch allowed to be scannable due to the anamoly tech origin addition (and didn't have mech scan fail) may no longer be replicated by a mechanic. If we want to change this, a future PR can add proper material costs to the suits.

2024-04-29 03:27 UTC, merged