Fixes crate weigher not going back up when pulled from under crate
d3athrow/vgstation13 pull request #36382
Opened 2024-04-20 00:59 UTC by SECBATON-GRIFFON

[bugfix][consistency]

## Changelog
:cl:
 * bugfix: Crate weighers now properly spring up when pulled from under crates.

2024-04-21 16:48 UTC, west3436 requested changes

2024-04-21 16:48 UTC, west3436 commented on code/game/cargo_forwarding.dm
> +
..() needed

2024-04-21 19:15 UTC, SECBATON-GRIFFON commented on code/game/cargo_forwarding.dm
> +
ah yea sorry, forgot

2024-04-22 05:01 UTC, jwhitak requested changes
The smarter fix would be to add this to the crate weigher's Move proc, so that this typecheck isn't called every single time a structure of any sort is moved.

2024-04-23 00:53 UTC, SECBATON-GRIFFON commented on code/game/cargo_forwarding.dm
> +
recommended change done instead

2024-04-23 00:58 UTC, SECBATON-GRIFFON commented
> The smarter fix would be to add this to the crate weigher's Move proc, so that this typecheck isn't called every single time a structure of any sort has something move off of it.

did this now

2024-04-23 11:03 UTC, west3436 approved these changes

2024-04-24 15:50 UTC, jwhitak approved these changes

2024-04-24 16:09 UTC, merged