Crab Claw Hands
d3athrow/vgstation13 pull request #36391
Opened 2024-04-22 12:48 UTC by 13spacemen

PR is Arthur from Discord's idea, I just wanted to see if I could code it

## What this does
Adds crab claw hand organs, you declaw crabs by butchering to get them, you can then surgically replace hands with them

- +7 punch damage
- can't wear gloves
- fail dexterity checks so no firing guns
- inherently have the claw mutation on the hands/claws, so you can butcher stuff

![Screenshot 2024-04-22 163239](https://github.com/vgstation-coders/vgstation13/assets/46101244/2dbec1af-c890-47e9-82b6-4f83b35738e6)

## Changelog

:cl:
 * rscadd: You can declaw crabs, and use those claws to replace people's hands. Claws punch harder and can butcher, but can't wear gloves or fire guns.

2024-04-22 13:05 UTC, jwhitak requested changes

2024-04-22 13:05 UTC, jwhitak commented on code/datums/helper_datums/butchering.dm
> +	var/obj/item/result //can also be a list of items
Instead of intentionally doing a bad type assignment and bragging about it in a comment here, why not just override the crab claws subtype?

2024-04-22 22:33 UTC, Theophrastus1 commented
now we just need the helmet
![Crab_helmet_equipped](https://github.com/vgstation-coders/vgstation13/assets/8057687/4c90f01a-0a63-4d1c-9e5b-552f26032c87)

2024-04-30 07:42 UTC, jwhitak approved these changes

2024-04-30 07:58 UTC, jwhitak requested changes
Any reason for the use of ``:`` over ``.``? Ideally we'd like to have reference errors found at compile time. Otherwise, the two should be identical.

2024-05-01 10:30 UTC, jwhitak approved these changes
Made a new commit to remove all instances of runtime typechecks, generalize the expected organ objects for the datums (removing the need for hand_type hardcoded), made a base hand datum which left and right hands are subtypes of (which can be properly worked on and expanded in the future).

2024-05-01 11:56 UTC, west3436 approved these changes

2024-05-01 11:56 UTC, merged