WIP Code cleanup of "chemCandH" file.
d3athrow/vgstation13 pull request #36426
Opened 2024-04-29 05:22 UTC by DrSnips

Tested and verified that it works still.

**BUG NOTICE** The laser and wave overlays are under the beakers which is unrelated to this cleanup but I think I will fix it here too. Making this PR WIP but I would like feedback if any other parts of this should be cleaned up or are of concern.

## What this does

Cleans up some code in an old project of mine. We can do better.

## Why it's good

I lay one of my ghosts to rest.

2024-04-29 21:02 UTC, DrSnips commented
Alright this thing is done and the effect layer organization bug is fixed.
WIP can be removed.

2024-04-30 14:48 UTC, west3436 requested changes

2024-04-30 14:48 UTC, west3436 commented on code/game/machinery/chemHandC.dm
> +	if(!user.incapacitated() && Adjacent(user) && !(stat & (FORCEDISABLE|NOPOWER) && user.dexterity_check()))
Parenthesis issue - `!(stat & (FORCEDISABLE|NOPOWER) && user.dexterity_check())` will be TRUE if the machine lacks power and the user passes the dexterity check or the inverse. Probably should be the following instead: `!(stat & (FORCEDISABLE|NOPOWER)) && user.dexterity_check()`

2024-04-30 16:14 UTC, west3436 approved these changes

2024-04-30 16:14 UTC, merged