Autodrobe Vox Outfits
d3athrow/vgstation13 pull request #36496
Opened 2024-05-13 04:23 UTC by falcon2346

## What this does
Adds Vox Sprites for a handful of Autodrobe outfits, specifically the first 5 boxes that did not already have Vox sprites for all items. This PR includes sprites for the following:
Marisa outfit box: All Clothing Items
Captain's casual box: Green Glasses, Flatcap
Monkey suit box: Monkey Suit
Wizard outfit box: All Clothing Items
School girl outfit box: Kitty Ears, black skirt
![dreamseeker_liIjENqaNg](https://github.com/vgstation-coders/vgstation13/assets/111808553/611126ad-2acb-4dfe-8945-3a3a1f6bf8a7)
Though pictured in this, the Jackboots, Green Suit, and Monkey Mask were not made by me, and are currently existing sprites in the game.

This also includes code contributed by @CrazyAmphibian to allow hats to hide the tail when given the HIDETAIL flag. Currently the only hat that uses this are the Kitty Ears.

Finally, somewhat unatomically, this fixes the Vox sprite for the Elite Security Skirt, which I happened to notice covered the hands.

## Why it's good
This gives more costume options for Vox clowns, as almost none fit properly currently. Also silly outfits are fun.

## How it was tested
I took the screenshots for the sprites in game.

## Changelog
[sprites]
:cl:
 * imageadd: Added Vox sprites for several Autodrobe items

2024-05-13 05:08 UTC, angryturnip commented
Vox are pox

2024-05-13 06:40 UTC, Eneocho commented
Vox are pox but monkeyvox is really funny to me

2024-05-16 13:49 UTC, west3436 requested changes

2024-05-16 13:49 UTC, west3436 commented on code/modules/clothing/head/misc_special.dm
> +can /*
Oops!

2024-05-16 20:30 UTC, falcon2346 commented on code/modules/clothing/head/misc_special.dm
> +can /*
Done

2024-05-16 21:36 UTC, west3436 approved these changes

2024-05-18 14:53 UTC, merged