Braindamage speech proc change.
d3athrow/vgstation13 pull request #36490
Opened 2024-05-12 05:58 UTC by Eneocho

## What this does
Changes the braindamage speech proc so it replaces a lot more words than before with their braindamaged counterpart. Also makes it so a lot of the words used in the forced braindamage lines are also spelled that way if said normally. Ex: Singularity becomes Scrungularity when spoken regularly because the forced braindamage line says scrungularity, and this is consistent with it.
It will also make it so 70% of the time, words that have two identical letters together like "look, wood, sleep, etc" lose one of those letters, becoming "lok, wod, slep, etc" (that's what the regex check is for).
Finally, it reduces the forced screaming and forced stutter chance a bit, since this felt better with those reduced odds.
### _This is by no means a comprehensive list._ Please suggest more rules to add if you happen to think of one, or point at ones that should be removed one they're too on the nose or don't fit.

## Why it's good
Expands the braindamage speech a bunch, making braindamage speech affect more than some very specific words.
:cl:
 * rscadd: Expands the braindamage speech, adding a good amount of extra words and syllables that will be replaced with their dumb counterpart.
 * tweak: Reduces the forced screaming chance and forced stutter chance when talking while braindamage by 15 and 5 percent respectively, since those values felt better with this change.

2024-05-12 13:59 UTC, boy2mantwicethefam commented
I don't think running every brain damage message through at least 50 replacetexts is a good execution

2024-05-12 17:26 UTC, Eneocho commented
> I don't think running every brain damage message through at least 50 replacetexts is a good execution

I'll look into how to improve it, I have an idea based on catbeast code. I'm way out of my field here so it might take a while.

2024-05-16 13:58 UTC, west3436 commented
I think this is extra annoying from a gameplay perspective, but from a coding perspective please use some associative lists.

2024-05-16 15:57 UTC, west3436 requested changes

2024-05-16 15:57 UTC, west3436 commented on code/modules/mob/mob_helpers.dm
> +	message = replacetext(message, "among us", "amogus")
My brother in Christ; please use an associative list here.

2024-06-17 14:50 UTC, hacker-on-steroids commented on code/modules/mob/mob_helpers.dm
> +	message = replacetext(message, "hos", "HITLER")
perhaps use `" hos ", " HITLER "` so you don't turn "those" into "tHITLERe"
though a borer hitlert sounds pretty funny

2024-06-17 14:50 UTC, hacker-on-steroids commented on code/modules/mob/mob_helpers.dm
> +	//specific words we want replaced every time, mainly references to the actual brain damage lines, so they stay consistent with brain damage regular speech
if you want them replaced every time you should put this at the start of the proc, so the 2/3 letter replacements don't garble your input

2024-06-26 06:56 UTC, hacker-on-steroids commented
now that i think about it again, you can't really make this much faster?
why even bother with associative lists or making a custom "find and replace multiple" function?
time complexity is `message length` * `number of substrings` either way

2024-06-26 07:35 UTC, Eneocho commented
Yeah, we figured something like that on the coder chat. The one idea that seems would be more performant was some fucked up schizophrenic regex, but I barely understand regex as is, I'm not a regexwizard that could craft something like that. So we instead came up with the idea of limiting the speech of brain damaged players to one sentence per second maximum. It's not noticeable on regular gameplay, but macrospam (which, on testing, caused fucktons of CPU lag) would instead get the lines replaced with a gibbers uncontrollably emote.

2024-08-06 01:06 UTC, hacker-on-steroids commented
merge when??

2024-08-06 05:02 UTC, Eneocho commented
> merge when??

No idea. Dilt said he was ok with merging it if west also was. I then asked west about it a good while back and he gave a "sure whatever" since there was no real difference between assoc list and no assoc list, performance-wise (and the 1 line a second throttle compensates for the very inefficient replace list)

2024-08-22 11:30 UTC, merged