pulse demon balance
d3athrow/vgstation13 pull request #36587
Opened 2024-05-25 17:22 UTC by SECBATON-GRIFFON

[balance][gamemode]

## What this does
Closes #36585.

## Why it's good
makes it easier to find and stop, checks if they're gone

## Changelog
:cl:
 * tweak: Pulse demons can no longer use powers for a few seconds after being EMPed, like with health regeneration.
 * tweak: Security officers, wardens, captains, AIs and cyborgs are now enemy jobs for pulse demons.
 * tweak: The enemy job requirements for pulse demons have been increased to 2.
 * tweak: Using a multitool on a cable will now show if a pulse demon is on the powernet.

2024-05-25 17:25 UTC, BomberBro commented
\>tweak: Security officers, wardens, captains, AIs and cyborgs are now enemy jobs for pulse demons.
You WHAT

Can AIs or cyborgs even do anything about pulse demons besides shut off power and hope for the best?

2024-05-25 17:26 UTC, SECBATON-GRIFFON commented
> Can AIs or cyborgs even do anything about pulse demons besides shut off power and hope for the best?

that's why i added them, according to feedback

2024-05-25 19:11 UTC, boy2mantwicethefam commented
Can you fix it so that the pulse demon can interact with the SMES it is in without having to connect to the APC?

2024-05-28 19:17 UTC, anonymoose-contributor commented
Seeing as pulse demons can emag cyborgs and AI, if my memory is correct, having silicons as an enemy job seems a bit counter-intuitive here.

2024-05-28 21:49 UTC, SECBATON-GRIFFON commented
> Seeing as pulse demons can emag cyborgs and AI, if my memory is correct, having silicons as an enemy job seems a bit counter-intuitive here.

emagging the AI doesnt do anything, plus borg covers need to be open for emagging to do anything

2024-06-06 06:47 UTC, CrazyAmphibian commented
you should make atmospheric technicians also count towards the enemy jobs

2024-06-06 06:48 UTC, jwhitak reviewed
Have you tested the case where the cable under a pulse demon is cut? Or other strange cases where powernets can be changed outside of the pulse demon's Move()?

2024-06-06 18:58 UTC, SECBATON-GRIFFON commented
> Have you tested the case where the cable under a pulse demon is cut? 

cutting it from underneath seems to remove the pulse demon from multitool detection as expected

2024-06-07 12:59 UTC, west3436 requested changes

2024-06-07 12:59 UTC, west3436 commented on code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
> +			if(current_cable.powernet)
```suggestion
			if(current_cable?.powernet)
```

2024-06-07 23:34 UTC, SECBATON-GRIFFON commented on code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
> +			if(current_cable.powernet)
i felt like this was covered by the new_cable if already but sure

2024-06-08 12:16 UTC, west3436 approved these changes

2024-06-08 12:16 UTC, merged