Traitor kill announcer
d3athrow/vgstation13 pull request #37139
Opened 2024-09-17 16:24 UTC by SECBATON-GRIFFON

[content][gamemode]
https://github.com/user-attachments/assets/616fbc88-170e-4f2f-833d-7a6c21ebc477

## What this does
adds an item called the KILLbot to the pointless badassery section of uplinks for 1 telecrystal, that announces various relevant lines from unreal tournament as seen above

## Why it's good
murderbone flavour

## How it was tested
see video

## Changelog
:cl:
 * rscadd: Uplinks now have a new item in the pointless badassery section: KILLbots! These sound systems make sounds for various events such as killstreaks, headshots and other miscellaneous round related things when held by someone.

2024-09-17 16:28 UTC, Eneocho commented
surely this won't cause issues

2024-09-17 16:29 UTC, MercuriusGH commented
Can you hear this on the entire Z level?

2024-09-17 16:33 UTC, SECBATON-GRIFFON commented
> Can you hear this on the entire Z level?

just around the person using it as normal

2024-09-17 16:51 UTC, MercuriusGH commented
> > Can you hear this on the entire Z level?
> 
> just around the person using it as normal

WEAK
ideally it should display text in the middle of your screen (with a portrait made from the head of the fragger)

2024-09-17 16:58 UTC, SECBATON-GRIFFON commented
> > > Can you hear this on the entire Z level?
> > 
> > 
> > just around the person using it as normal
> 
> WEAK ideally it should display text in the middle of your screen (with a portrait made from the head of the fragger)

alright fine, i'll make this an option for when this thing gets arcane tampered, maybe

2024-09-17 21:34 UTC, DrSnips commented
>arcane tamper on a traitor item in the pointless badass category.

Don't even bother at that point. That's some never going to happen shit.

2024-09-17 23:19 UTC, Eneocho commented
make it very obvious like mercurius suggests, that's more fun

2024-09-17 23:45 UTC, ErrorsWindows commented
can you do the execution machete that hippie station has, where you go to behead someone and it announces it to the entire station as a progress bar fills for 30 seconds while an osama bin laden speech plays in the background across the entire z level

2024-10-02 12:38 UTC, west3436 requested changes

2024-10-02 12:38 UTC, west3436 commented on code/game/objects/items/devices/roganbot.dm
> +				playsound(loc,'sound/effects/2003M/You_have_lost_the_match.ogg',100)*/
?

2024-10-02 12:38 UTC, west3436 commented on data/bunker.txt
Remove this one; it's in .gitignore now

2024-10-02 15:05 UTC, SECBATON-GRIFFON commented on data/bunker.txt
aye, it was getting annoying

2024-10-02 15:05 UTC, SECBATON-GRIFFON commented on code/game/objects/items/devices/roganbot.dm
> +				playsound(loc,'sound/effects/2003M/You_have_lost_the_match.ogg',100)*/
code that doesn't work that i left in to see if i could make it work, could just remove it entirely if you want

2024-10-02 15:25 UTC, SECBATON-GRIFFON commented on data/bunker.txt
aye, it was getting annoying. done

2024-10-02 17:28 UTC, merged