Allows credits to be claimed from recycling furnaces
d3athrow/vgstation13 pull request #37130
Opened 2024-09-17 00:29 UTC by SECBATON-GRIFFON

[content]

## What this does
enables this process

## Why it's good
lets greytide make a tiny bit of extra cash on the side (not much though, as something with 50 sheets of metal worth of mats just gives 10 bucks back)

## How it was tested
toolboxes in it, then adding sheet stacks as an exception to this credit counting to stop infinite money shenanigans

## Changelog
:cl:
 * rscadd: Recycling furnaces can now have credits claimed from them for recycling, albeit meager amounts in the majority of cases.

2024-09-17 03:17 UTC, wotisjanitor commented
this should require a janitor ID

2024-09-18 02:24 UTC, RealestEstate commented
Seconding the janitor ID proposal

2024-09-18 16:44 UTC, SECBATON-GRIFFON commented
> this should require a janitor ID, or else janitors will see all of their labors go to some greyshit

added a way for janitors to lock it to themselves now

2024-09-19 03:14 UTC, wotisjanitor commented
and if people dont like that i guess it could be hackable or something

2024-09-19 13:39 UTC, SECBATON-GRIFFON commented
> and if people dont like that i guess it could be hackable or something

i was debating making emags override it yea

2024-09-20 10:32 UTC, DeityLink commented
I'm sure there's a few cases where you can just loop a crafting recipe to perpetually recycle it generate cash from nothing. Not saying that economics matter but that's pretty dumb.

If disposals let you actually get rid of trash by shipping it out, and you didn't get both the materials AND the cash back, that'd make more sense to me.

2024-09-20 23:15 UTC, SECBATON-GRIFFON commented
> I'm sure there's a few cases where you can just loop a crafting recipe to perpetually recycle it generate cash from nothing. Not saying that economics matter but that's pretty dumb.
> 
> If disposals let you actually get rid of trash by shipping it out, and you didn't get both the materials AND the cash back, that'd make more sense to me.

good stuff to consider

2024-10-02 12:40 UTC, west3436 requested changes

2024-10-02 12:40 UTC, west3436 commented on data/bunker.txt
remove

2024-10-02 15:06 UTC, SECBATON-GRIFFON commented on data/bunker.txt
yea this thing got so annoying to remove after a while

2024-10-02 15:27 UTC, SECBATON-GRIFFON commented on data/bunker.txt
yea this thing got so annoying to remove after a while. done

2024-10-02 17:28 UTC, merged