More slime extract uses
d3athrow/vgstation13 pull request #37165
Opened 2024-09-23 19:42 UTC by SECBATON-GRIFFON

[content]

## What this does
cleans up the extract adding system to allow slime extracts to be applied to any object and for all types
lets silver slimes cook "perfect" forms of some recipes like plump helmet pie every time
lets oil slime extracts boost the power of TTVs and blast cannons
adds more chem dispenser options for adding pyrite slimes, honk serum and colorful reagent
lets pyrite slimes multiply the results of certain ores mined, with values of 2 for gold silver and uranium, 4 for diamond and 8 for phazon bananium telecrystal and mythril. it also boosts the odds of finding dusty crates within.
expands the system for slime reagent refills on spray bottles, allowing green slimes to refill luminol, red slimes to refill plantbgone and insecticide
lets slime extracts upgrade the output power of port gens, with darkpurple needed for pacman, additional metal for superpacman and additional adamantine for mrspacman
lets red slime extracts refuel bunsen burners with a version of glycerol with no bad side effects

## Why it's good
makes them more useful

## How it was tested
adding the relevant extracts, TBA

## Changelog
:cl:
 * rscadd: Silver slime extracts now allow for the creation of cooking recipes in their random probability "perfect" forms, such as frosted donuts.
 * rscadd: Red slime extracts now refill bunsen burners with glycerol and remove its downsides.
 * rscadd: Pyrite slime extracts now boost the output of mining tools depending on ore, with diamond multiplying by 4 and gold/silver/uranium by 2, and dusty crates becoming more common finds.
 * rscadd: Insecticide and plantbgone sprays can now be refilled with red slime extracts, luminol and fakecreep with green and pyrite respectively.
 * rscadd: Port generators can now accept slime extracts to boost their output. PACMAN requires dark purple, SUPERPACMAN requires dark purple and metal, and MRSPACMAN requires dark purple, metal and adamantine.
 * rscadd: Tank transfer valves and blastcannons can now have their power somewhat multiplied with oil slime extracts.
 * rscadd: Booze dispensers can now dispense honk serum and colorful reagent by adding pyrite slime extract to them.

2024-09-24 12:14 UTC, DeityLink commented
I'd argue that Xenobio needs less rewards and more of a job rework/QoL pass if you want players to actually play it. It's already got plenty of great rewards, but managing slimes is tedious and repetitive. It was fun to learn the first time, but now I'd rather play any other job with less epic rewards but more engaging gameplay.

2024-09-24 15:51 UTC, SECBATON-GRIFFON commented
> I'd argue that Xenobio needs less rewards and more of a job rework/QoL pass if you want players to actually play it. It's already got plenty of great rewards, but managing slimes is tedious and repetitive. It was fun to learn the first time, but now I'd rather play any other job with less epic rewards but more engaging gameplay.

i wouldnt mind doing some next. care to give ideas?

2024-09-24 18:16 UTC, DeityLink commented
A long time idea I've had in the back of my mind is xenobio HUD glasses that inform you whether the slimes consider you a friend or not, how hungry/electricity-charged they are/how closed to splitting.

Additionally Fire Extinguishers are long overdue for a proper fix of their spread pattern, it often makes no sense and the steam around the tile that you click at.

Something like the gun in Slime Rancher that can vacuum in live slimes, store and release them, would make moving slimes between pens infinitely less of a hassle (with a risk of it glomping you instead if you try to suck it in while it doesn't consider you a friend yet). Players could also use it to shoot slimes at people, automatically glomping them.

Bio suits ACTUALLY offering some protection from slimes so you don't take clone damage right away.

These are just a few ideas.

2024-10-01 05:15 UTC, angryturnip commented
I don't think TC should have an 8x multiplier, frankly

2024-10-01 05:40 UTC, jwhitak requested changes

2024-10-01 05:40 UTC, jwhitak commented on code/modules/mining/minerals.dm
> +	fortune_multiplier = 8
This was rejected by the administration, please remove the modifier for telecrystals. (You can insert them into an uplink for more TC)

2024-10-01 05:40 UTC, jwhitak commented on code/modules/reagents/machinery/chem_dispenser.dm
> +	slime_reagents = list("black" = BLOOD, "pyrite" = BANANA)
I personally find it a little unusual that this makes blood intstead of tricord here. How do others think?

2024-10-01 05:40 UTC, jwhitak commented on code/modules/mining/mine_turfs.dm
> +	fortune_multiplier = 8
See other comment

2024-10-01 15:48 UTC, SECBATON-GRIFFON commented on code/modules/mining/minerals.dm
> +	fortune_multiplier = 8
the ore actually produces bluespace crystals, i should clarify

2024-10-01 15:49 UTC, SECBATON-GRIFFON commented on code/modules/reagents/machinery/chem_dispenser.dm
> +	slime_reagents = list("black" = BLOOD, "pyrite" = BANANA)
really its for easier lifeline

2024-10-01 15:49 UTC, SECBATON-GRIFFON commented on code/modules/mining/mine_turfs.dm
> +	fortune_multiplier = 8
seen

2024-10-01 15:58 UTC, SECBATON-GRIFFON commented
> I don't think TC should have an 8x multiplier, frankly. But if that gets removed I think the rest is good

the TC mineral only produces bluespace crystals and isn't used in uplinks in any form, see my comment under the requested change

2024-10-02 12:39 UTC, jwhitak commented on code/modules/mining/minerals.dm
> +	fortune_multiplier = 8
I swear I checked it before posting this!!! The sheet/mineral has trolled me again...

2024-10-02 12:40 UTC, merged

2024-10-02 18:03 UTC, SECBATON-GRIFFON commented
> A long time idea I've had in the back of my mind is xenobio HUD glasses that inform you whether the slimes consider you a friend or not, how hungry/electricity-charged they are/how closed to splitting.

late but you can get the electricity thing from examining them already.