Admin Cookies are now entropy immune
d3athrow/vgstation13 pull request #37176
Opened 2024-09-25 08:09 UTC by DeityLink

:cl:
* tweak: Cookies spawned by admin in return for prayers are now blessed with a protection from thermal entropy, and will no longer freeze in space or burn in an inferno.

2024-09-25 12:14 UTC, west3436 requested changes
Linters

2024-09-25 12:14 UTC, west3436 commented on code/modules/admin/topic.dm
> +		if(!H.put_in_hands(reward)
```suggestion
		if(!H.put_in_hands(reward))
```

2024-09-25 14:36 UTC, SECBATON-GRIFFON commented on code/modules/admin/topic.dm
> +		if(!H.put_in_hands(reward)
0% tested

2024-09-25 19:35 UTC, west3436 approved these changes

2024-09-26 15:15 UTC, SonixApache commented
as someone who received a frozen cookie in response to a cry for help in the void once, i thank you

2024-10-01 05:44 UTC, jwhitak commented
I personally find it hilarious to give a cookie to someone dying in a fire or freezing in space only for the cookie to bust into flames/ash or freeze solid. Perfect for the slapstick humor of the station.

Ah well, rip

2024-10-01 05:44 UTC, merged