Buffs scientist bio suits against slimes
d3athrow/vgstation13 pull request #37222
Opened 2024-10-02 18:05 UTC by SECBATON-GRIFFON

[balance][qol][tweak]

## What this does
something requested by @DeityLink, makes scientist biosuits do moderate protection from melee (ie slime) attacks and also block them feeding on you entirely

## Why it's good
less of a hassle when slime raising goes wrong

## How it was tested
gonna do that, moves out of draft when done

## Changelog
:cl:
 * tweak: Scientist biosuits now offer some protection from slime attacks and total protection from slime feeding.

2024-10-02 22:18 UTC, Dacendeth commented
Feels like just checking for 100 bio coverage on all parts would be simpler use less snowflaky, also your current check doesnt care if they have the related helmet on or not.

2024-10-02 22:24 UTC, SECBATON-GRIFFON commented
> Feels like just checking for 100 bio coverage on all parts would be less snowflaky, also your current check doesnt care if they have the related helmet on or not.

i mean slimes don't really feed on that area do they? will add it if you think its necessary though, easy one line fix

2024-10-02 22:46 UTC, jwhitak commented
This is too strong of a buff - it nearly completely eliminates the risk of xenobio! Might as well port the tg style monitor remote management system.

I'd be fine with a tweak level of buff, but complete immunity is a no.

2024-10-02 22:50 UTC, SECBATON-GRIFFON commented
> This is too strong of a buff - it nearly completely eliminates the risk of xenobio! Other methods of getting immunity come with severe downsides (sliming oneself being the main example). Might as well port the tg style monitor remote management system.
> 
> I'd be fine with a tweak level of buff, but complete immunity is a no.

complete immunity has now been removed, feeding damage has been halved instead

2024-10-02 22:53 UTC, angryturnip commented
I think the risk of being killed by your slimes is part of the job and shouldn't be mitigated by a roundstart item. I'd rather something like this be gated behind being an advanced bio suit in the trader item pool or from using a slime core from a slime type that's at the end of one of the lines on a biosuit.

2024-10-02 22:54 UTC, angryturnip commented
That being said, I started writing that comment before seeing the change you made above. Still iffy on it though, but with the change I no longer think it'd need to be locked behind any other content

2024-10-02 23:07 UTC, jwhitak commented
I'm still iffy on it... I do like an upgrade to give immunity though. This seems to be a really good chance to add a slime suit upgrade for the biosuit using the new  slime_act system.

2024-10-03 00:30 UTC, DeityLink commented
Yeah I didn't suggest that they offer total protection, but if only that they at least delay slime dealing you clone damage. Since it's annoying to heal it should give you time to shove them off.

2024-10-03 02:28 UTC, RealestEstate commented
Remember to wear proper PPE

2024-10-11 05:55 UTC, jwhitak requested changes

2024-10-11 05:55 UTC, jwhitak commented on code/modules/clothing/suits/bio.dm
> +	desc = "A hood that protects the head and face from biological comtaminants. It has a reinforced synthetic lining to protect against slime glomps."
comtaminants

2024-10-11 16:55 UTC, SECBATON-GRIFFON commented on code/modules/clothing/suits/bio.dm
> +	desc = "A hood that protects the head and face from biological comtaminants. It has a reinforced synthetic lining to protect against slime glomps."
fixed all occurences of this now

2025-02-18 14:44 UTC, merged