Adds crate shelf subtype for mappers + adds crate shelves to cargo on 6 maps
d3athrow/vgstation13 pull request #37235
Opened 2024-10-04 23:47 UTC by kernikov

![synergy shelf](https://github.com/user-attachments/assets/c9291906-e517-498a-bd1c-6d2917493633)
![tg shelf](https://github.com/user-attachments/assets/e9be8d9f-6688-4427-9182-85075f923f84)
![roid shelf](https://github.com/user-attachments/assets/b93b0c38-d43f-4c27-a5cc-cea876270008)
![packed shelf](https://github.com/user-attachments/assets/7ffde7a3-d8ce-489d-8c87-c9c0e91d3865)
![deff shelf](https://github.com/user-attachments/assets/02009fc4-076d-48fc-9f2f-d9bb4a67ed7d)
![meta shelf](https://github.com/user-attachments/assets/9a91ef36-8473-4690-966d-4182045cf7a3)

CENTCOM has taken the liberty of pre-assembling some crate shelves for Cargo on a few stations.
They definitely didn't skip any steps! 
Nope! 

## What this does

New crate subtype for mappers to add crate shelves with a chance (based 20%) of having loosened bolts

Adds these crate shelves to the Cargo Bay Warehouses of the following stations:

- Synergy
- Roid
- Packed
- Box
- Deffiency
- Metaclub

## Why it's good
New content mapped in.
Cargo techs stay on their toes.

## Changelog
:cl:
 * rscadd: CENTCOM has added some shelves to the cargo warehouse of Box, Roid, Packed, Synergy, Def and Metaclub.
 * experiment: They might have skipped a couple steps so, be careful.

2024-10-05 01:56 UTC, west3436 requested changes

2024-10-05 01:56 UTC, west3436 commented on code/game/objects/structures/crateshelf.dm
> +          var/osha_violation = TRUE
```suggestion
          osha_violation = TRUE
```
This var has already been declared at the parent type so you can't redeclare it here

2024-10-05 01:56 UTC, west3436 commented on code/game/objects/structures/crateshelf.dm
> +          var/osha_violation = TRUE
Also you cut off a bunch of vars from the parent type. Move your entire code to the blank spot immediately preceeding the "tall" variant.

2024-10-05 02:09 UTC, west3436 approved these changes

2024-10-05 02:10 UTC, west3436 requested changes
Your indentation is still messed up here. Either use tab or 4 spaces

2024-10-05 02:11 UTC, west3436 commented on code/game/objects/structures/crateshelf.dm
> +		osha_violation = TRUE
Indentation issue

2024-10-05 02:12 UTC, kernikov commented on code/game/objects/structures/crateshelf.dm
> +		osha_violation = TRUE
I see it, thank you

2024-10-05 02:14 UTC, west3436 approved these changes

2024-10-05 18:33 UTC, SonixApache commented
the chance of it harming you is mega gay
would be nice if you could make it so crates mapped onto the rack automatically get loaded in

2024-10-05 21:08 UTC, west3436 commented
> the chance of it harming you is mega gay


That's the joke.gif

> would be nice if you could make it so crates mapped onto the rack automatically get loaded in


They do; they just don't render fully since it uses a series of overlays which mapdifbot doesn't like

2024-10-06 00:36 UTC, kernikov commented
> > would be nice if you could make it so crates mapped onto the rack automatically get loaded in
> 
> They do; they just don't render fully since it uses a series of overlays which mapdifbot doesn't like

Just so we're clear, that's byond the scope of this PR

2024-10-10 15:19 UTC, merged