Crucifix, a Null Rod variant
d3athrow/vgstation13 pull request #37315
Opened 2024-11-04 00:11 UTC by SnakeEater14

Adds in a standard gold cross as a null rod variant, for chaplains wanting to roleplay as a conventional priest.

![crucifixsprites](https://github.com/user-attachments/assets/052f0e01-b807-4bba-a7d1-98cbd357ab35)

## What this does
Adds in another null rod variant for chaplains to pick. Can be activated to emote raising it.

## Why it's good
Allows more conventional chaplains to carry something that makes sense roleplay-wise (most priests don't carry around sticks of obsidian in their pocket).

## How it was tested
Spawned in several times, tested out the emoting and description as a chaplain and non-chaplain.

## Changelog
:cl:
 * rscadd: Added crucifix, a null rod variant.

2024-11-04 01:02 UTC, Eneocho commented
> (most priests don't carry around sticks of obsidian in their pocket)

they do in spess

2024-11-04 22:00 UTC, MercuriusGH commented
mortis

2024-11-05 14:14 UTC, west3436 requested changes

2024-11-05 14:14 UTC, west3436 commented on code/game/objects/items/weapons/null_rod.dm
> +		desc = initial(desc)
Overwrite examine() here instead to use a different description based on whether or not the item is held by the chaplain. I can give you the code but it really isn't a difficult change so try it yourself first!

2024-11-05 14:14 UTC, west3436 commented on code/game/objects/items/weapons/null_rod.dm
> +	if(user.mind.assigned_role == "Chaplain")
```suggestion
	if(user.mind?.assigned_role == "Chaplain")
```
If, for whatever reason, the user no longer has a mind, this will prevent a runtime.

2024-11-06 19:35 UTC, Loafin34 commented
will this repel vampires

2024-11-07 15:42 UTC, west3436 approved these changes

2024-11-07 15:42 UTC, west3436 commented on code/game/objects/items/weapons/null_rod.dm
> +		user.delayNextAttack(1 SECONDS)
I'd just make this return the parent if it's done by a non-chaplain and remove the message when a non-chaplain attempts to use it.

2024-11-12 13:00 UTC, west3436 approved these changes

2024-11-12 13:00 UTC, merged